<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 ns1 oraxsl xp20 xref mhdr oraext utl dvm socket"
                xmlns:ns2="http://nucor.eia.com/common" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns3="http://oracle.com/sca/soapservice/Application2/NUC_EBizProductStructure_ABS/EbizProductStructure"
                xmlns:obj1="http://xmlns.oracle.com/xdb/APPS_NE"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns7="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAO/1.0"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/aq/Application2/NUC_PublishEBSProductStructure_ABF/AQ_DEQ_XXNUC_COMM_OUTINTF_Q">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/AQ_DEQ_XXNUC_COMM_OUTINTF_Q.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/ProductStructureABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryProductStructureAddRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"/>
        <oracle-xsl-mapper:param name="g_Invoke_queryProductStructure_OutputVariable.queryProductStructureRs"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/ProductStructureABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryProductStructureAddRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON FEB 15 12:21:43 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_Invoke_queryProductStructure_OutputVariable.queryProductStructureRs"/>
  <xsl:template match="/">
    <ns1:QueryProductStructureAddRs>
      <ns9:HeaderRs>
        <ns9:RequestDetails>
          <ns9:TransactionRequestID>
            <xsl:value-of select="$g_Invoke_queryProductStructure_OutputVariable.queryProductStructureRs/ns1:QueryProductStructureAddRs/ns9:HeaderRs/ns9:RequestDetails/ns9:TransactionRequestID"/>
          </ns9:TransactionRequestID>
          <ns9:ComponentID>
            <xsl:value-of select="$g_Invoke_queryProductStructure_OutputVariable.queryProductStructureRs/ns1:QueryProductStructureAddRs/ns9:HeaderRs/ns9:RequestDetails/ns9:ComponentID"/>
          </ns9:ComponentID>
          <ns9:TransactionName>
            <xsl:value-of select="$g_Invoke_queryProductStructure_OutputVariable.queryProductStructureRs/ns1:QueryProductStructureAddRs/ns9:HeaderRs/ns9:RequestDetails/ns9:TransactionName"/>
          </ns9:TransactionName>
          <ns9:Source>
            <xsl:value-of select="$g_Invoke_queryProductStructure_OutputVariable.queryProductStructureRs/ns1:QueryProductStructureAddRs/ns9:HeaderRs/ns9:RequestDetails/ns9:Source"/>
          </ns9:Source>
          <ns9:Target>
            <xsl:value-of select="$g_Invoke_queryProductStructure_OutputVariable.queryProductStructureRs/ns1:QueryProductStructureAddRs/ns9:HeaderRs/ns9:RequestDetails/ns9:Target"/>
          </ns9:Target>
          <ns9:HostName>RM2</ns9:HostName>
        </ns9:RequestDetails>
      </ns9:HeaderRs>
      <xsl:for-each select="$g_Invoke_queryProductStructure_OutputVariable.queryProductStructureRs/ns1:QueryProductStructureAddRs/ns7:ProductStructureDetails[number(/ns0:parameters/ns0:item[1]/ns0:value)]">
        <ns7:ProductStructureDetails>
          <xsl:if test="ns7:ListOfRecipe">
            <ns7:ListOfRecipe>
              <xsl:if test="ns7:ListOfRecipe/ns7:RecipeNumber">
                <ns7:RecipeNumber>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RecipeNumber"/>
                </ns7:RecipeNumber>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:RecipeVersion">
                <ns7:RecipeVersion>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RecipeVersion"/>
                </ns7:RecipeVersion>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:RecipeID">
                <ns7:RecipeID>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RecipeID"/>
                </ns7:RecipeID>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:RecipeDescription">
                <ns7:RecipeDescription>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RecipeDescription"/>
                </ns7:RecipeDescription>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:OwnerOrganization">
                <ns7:OwnerOrganization>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:OwnerOrganization"/>
                </ns7:OwnerOrganization>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:CreationOrganization">
                <ns7:CreationOrganization>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:CreationOrganization"/>
                </ns7:CreationOrganization>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:Product">
                <ns7:Product>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:Product"/>
                </ns7:Product>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:FormulaNumber">
                <ns7:FormulaNumber>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:FormulaNumber"/>
                </ns7:FormulaNumber>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:FormulaVersion">
                <ns7:FormulaVersion>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:FormulaVersion"/>
                </ns7:FormulaVersion>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:FormulaID">
                <ns7:FormulaID>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:FormulaID"/>
                </ns7:FormulaID>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:RountingID">
                <ns7:RountingID>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RountingID"/>
                </ns7:RountingID>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:RoutingNumber">
                <ns7:RoutingNumber>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RoutingNumber"/>
                </ns7:RoutingNumber>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:RoutingVersion">
                <ns7:RoutingVersion>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RoutingVersion"/>
                </ns7:RoutingVersion>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:RecipeStatus">
                <ns7:RecipeStatus>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RecipeStatus"/>
                </ns7:RecipeStatus>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:PlannedProcessLoss">
                <ns7:PlannedProcessLoss>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:PlannedProcessLoss"/>
                </ns7:PlannedProcessLoss>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:CalculateStepQuantity">
                <ns7:CalculateStepQuantity>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:CalculateStepQuantity"/>
                </ns7:CalculateStepQuantity>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:OrganizationCode">
                <ns7:OrganizationCode>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:OrganizationCode"/>
                </ns7:OrganizationCode>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:ProcessLoss">
                <ns7:ProcessLoss>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:ProcessLoss"/>
                </ns7:ProcessLoss>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:RoutingStep">
                <ns7:RoutingStep>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:RoutingStep"/>
                </ns7:RoutingStep>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:Line">
                <ns7:Line>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:Line"/>
                </ns7:Line>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:Attribute">
                <ns7:Attribute>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:AttributeCategory">
                    <ns7:AttributeCategory>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:AttributeCategory"/>
                    </ns7:AttributeCategory>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute1">
                    <ns7:Attribute1>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute1"/>
                    </ns7:Attribute1>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute2">
                    <ns7:Attribute2>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute2"/>
                    </ns7:Attribute2>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute3">
                    <ns7:Attribute3>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute3"/>
                    </ns7:Attribute3>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute4">
                    <ns7:Attribute4>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute4"/>
                    </ns7:Attribute4>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute5">
                    <ns7:Attribute5>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute5"/>
                    </ns7:Attribute5>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute6">
                    <ns7:Attribute6>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute6"/>
                    </ns7:Attribute6>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute7">
                    <ns7:Attribute7>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute7"/>
                    </ns7:Attribute7>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute8">
                    <ns7:Attribute8>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute8"/>
                    </ns7:Attribute8>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute9">
                    <ns7:Attribute9>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute9"/>
                    </ns7:Attribute9>
                  </xsl:if>
                  <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute10">
                    <ns7:Attribute10>
                      <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute10"/>
                    </ns7:Attribute10>
                  </xsl:if>
                </ns7:Attribute>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:ListOfFormulas">
                <ns7:ListOfFormulas>
                  <xsl:for-each select="ns7:ListOfRecipe/ns7:ListOfFormulas/ns7:Formulas">
                    <ns7:Formulas>
                      <xsl:if test="ns7:FormulaNumber">
                        <ns7:FormulaNumber>
                          <xsl:value-of select="ns7:FormulaNumber"/>
                        </ns7:FormulaNumber>
                      </xsl:if>
                      <xsl:if test="ns7:FormulaVersion">
                        <ns7:FormulaVersion>
                          <xsl:value-of select="ns7:FormulaVersion"/>
                        </ns7:FormulaVersion>
                      </xsl:if>
                      <xsl:if test="ns7:FormulaID">
                        <ns7:FormulaID>
                          <xsl:value-of select="ns7:FormulaID"/>
                        </ns7:FormulaID>
                      </xsl:if>
                      <xsl:if test="ns7:FormulaType">
                        <ns7:FormulaType>
                          <xsl:value-of select="ns7:FormulaType"/>
                        </ns7:FormulaType>
                      </xsl:if>
                      <xsl:if test="ns7:FormulaDescription">
                        <ns7:FormulaDescription>
                          <xsl:value-of select="ns7:FormulaDescription"/>
                        </ns7:FormulaDescription>
                      </xsl:if>
                      <xsl:if test="ns7:FormulaClass">
                        <ns7:FormulaClass>
                          <xsl:value-of select="ns7:FormulaClass"/>
                        </ns7:FormulaClass>
                      </xsl:if>
                      <xsl:if test="ns7:Comments">
                        <ns7:Comments>
                          <xsl:value-of select="ns7:Comments"/>
                        </ns7:Comments>
                      </xsl:if>
                      <xsl:if test="ns7:OrganizationCode">
                        <ns7:OrganizationCode>
                          <xsl:value-of select="ns7:OrganizationCode"/>
                        </ns7:OrganizationCode>
                      </xsl:if>
                      <xsl:if test="ns7:OwnerName">
                        <ns7:OwnerName>
                          <xsl:value-of select="ns7:OwnerName"/>
                        </ns7:OwnerName>
                      </xsl:if>
                      <xsl:if test="ns7:FormulaStatus">
                        <ns7:FormulaStatus>
                          <xsl:value-of select="ns7:FormulaStatus"/>
                        </ns7:FormulaStatus>
                      </xsl:if>
                      <xsl:if test="ns7:ScaleTypeHeader">
                        <ns7:ScaleTypeHeader>
                          <xsl:value-of select="ns7:ScaleTypeHeader"/>
                        </ns7:ScaleTypeHeader>
                      </xsl:if>
                      <xsl:if test="ns7:CalcProductQty">
                        <ns7:CalcProductQty>
                          <xsl:value-of select="ns7:CalcProductQty"/>
                        </ns7:CalcProductQty>
                      </xsl:if>
                      <xsl:if test="ns7:Attribute">
                        <ns7:Attribute>
                          <xsl:if test="ns7:Attribute/ns7:AttributeCategory">
                            <ns7:AttributeCategory>
                              <xsl:value-of select="ns7:Attribute/ns7:AttributeCategory"/>
                            </ns7:AttributeCategory>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute1">
                            <ns7:Attribute1>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute1"/>
                            </ns7:Attribute1>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute2">
                            <ns7:Attribute2>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute2"/>
                            </ns7:Attribute2>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute3">
                            <ns7:Attribute3>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute3"/>
                            </ns7:Attribute3>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute4">
                            <ns7:Attribute4>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute4"/>
                            </ns7:Attribute4>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute5">
                            <ns7:Attribute5>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute5"/>
                            </ns7:Attribute5>
                          </xsl:if>
                        </ns7:Attribute>
                      </xsl:if>
                      <xsl:if test="ns7:ListOfFormulaDetails">
                        <ns7:ListOfFormulaDetails>
                          <xsl:for-each select="ns7:ListOfFormulaDetails/ns7:FormulaDetails">
                            <ns7:FormulaDetails>
                              <xsl:if test="ns7:FormulaID">
                                <ns7:FormulaID>
                                  <xsl:value-of select="ns7:FormulaID"/>
                                </ns7:FormulaID>
                              </xsl:if>
                              <xsl:if test="ns7:LineNumber">
                                <ns7:LineNumber>
                                  <xsl:value-of select="ns7:LineNumber"/>
                                </ns7:LineNumber>
                              </xsl:if>
                              <xsl:if test="ns7:ItemType">
                                <ns7:ItemType>
                                  <xsl:value-of select="ns7:ItemType"/>
                                </ns7:ItemType>
                              </xsl:if>
                              <xsl:if test="ns7:FormulaItemType">
                                <ns7:FormulaItemType>
                                  <xsl:value-of select="ns7:FormulaItemType"/>
                                </ns7:FormulaItemType>
                              </xsl:if>
                              <xsl:if test="ns7:ItemNumber">
                                <ns7:ItemNumber>
                                  <xsl:value-of select="ns7:ItemNumber"/>
                                </ns7:ItemNumber>
                              </xsl:if>
                              <xsl:if test="ns7:Description">
                                <ns7:Description>
                                  <xsl:value-of select="ns7:Description"/>
                                </ns7:Description>
                              </xsl:if>
                              <xsl:if test="ns7:Quantity">
                                <ns7:Quantity>
                                  <xsl:value-of select="ns7:Quantity"/>
                                </ns7:Quantity>
                              </xsl:if>
                              <xsl:if test="ns7:ItemUOM">
                                <ns7:ItemUOM>
                                  <xsl:value-of select="ns7:ItemUOM"/>
                                </ns7:ItemUOM>
                              </xsl:if>
                              <xsl:if test="ns7:YieldConsumptionType">
                                <ns7:YieldConsumptionType>
                                  <xsl:value-of select="ns7:YieldConsumptionType"/>
                                </ns7:YieldConsumptionType>
                              </xsl:if>
                              <xsl:if test="ns7:ScrapFactor">
                                <ns7:ScrapFactor>
                                  <xsl:value-of select="ns7:ScrapFactor"/>
                                </ns7:ScrapFactor>
                              </xsl:if>
                              <xsl:if test="ns7:ScaleType">
                                <ns7:ScaleType>
                                  <xsl:value-of select="ns7:ScaleType"/>
                                </ns7:ScaleType>
                              </xsl:if>
                              <xsl:if test="ns7:ByProductType">
                                <ns7:ByProductType>
                                  <xsl:value-of select="ns7:ByProductType"/>
                                </ns7:ByProductType>
                              </xsl:if>
                              <xsl:if test="ns7:CostAllocation">
                                <ns7:CostAllocation>
                                  <xsl:value-of select="ns7:CostAllocation"/>
                                </ns7:CostAllocation>
                              </xsl:if>
                              <xsl:if test="ns7:ScaleMultiple">
                                <ns7:ScaleMultiple>
                                  <xsl:value-of select="ns7:ScaleMultiple"/>
                                </ns7:ScaleMultiple>
                              </xsl:if>
                              <xsl:if test="ns7:PhantomType">
                                <ns7:PhantomType>
                                  <xsl:value-of select="ns7:PhantomType"/>
                                </ns7:PhantomType>
                              </xsl:if>
                              <xsl:if test="ns7:ContributeToYield">
                                <ns7:ContributeToYield>
                                  <xsl:value-of select="ns7:ContributeToYield"/>
                                </ns7:ContributeToYield>
                              </xsl:if>
                              <xsl:if test="ns7:ContributeToStepQuantity">
                                <ns7:ContributeToStepQuantity>
                                  <xsl:value-of select="ns7:ContributeToStepQuantity"/>
                                </ns7:ContributeToStepQuantity>
                              </xsl:if>
                              <xsl:if test="ns7:ScaleRoundingVariance">
                                <ns7:ScaleRoundingVariance>
                                  <xsl:value-of select="ns7:ScaleRoundingVariance"/>
                                </ns7:ScaleRoundingVariance>
                              </xsl:if>
                              <xsl:if test="ns7:RoundingDirection">
                                <ns7:RoundingDirection>
                                  <xsl:value-of select="ns7:RoundingDirection"/>
                                </ns7:RoundingDirection>
                              </xsl:if>
                              <xsl:if test="ns7:Attribute">
                                <ns7:Attribute>
                                  <xsl:if test="ns7:Attribute/ns7:AttributeCategory">
                                    <ns7:AttributeCategory>
                                      <xsl:value-of select="ns7:Attribute/ns7:AttributeCategory"/>
                                    </ns7:AttributeCategory>
                                  </xsl:if>
                                  <xsl:if test="ns7:Attribute/ns7:Attribute1">
                                    <ns7:Attribute1>
                                      <xsl:value-of select="ns7:Attribute/ns7:Attribute1"/>
                                    </ns7:Attribute1>
                                  </xsl:if>
                                  <xsl:if test="ns7:Attribute/ns7:Attribute2">
                                    <ns7:Attribute2>
                                      <xsl:value-of select="ns7:Attribute/ns7:Attribute2"/>
                                    </ns7:Attribute2>
                                  </xsl:if>
                                  <xsl:if test="ns7:Attribute/ns7:Attribute3">
                                    <ns7:Attribute3>
                                      <xsl:value-of select="ns7:Attribute/ns7:Attribute3"/>
                                    </ns7:Attribute3>
                                  </xsl:if>
                                  <xsl:if test="ns7:Attribute/ns7:Attribute4">
                                    <ns7:Attribute4>
                                      <xsl:value-of select="ns7:Attribute/ns7:Attribute4"/>
                                    </ns7:Attribute4>
                                  </xsl:if>
                                  <xsl:if test="ns7:Attribute/ns7:Attribute5">
                                    <ns7:Attribute5>
                                      <xsl:value-of select="ns7:Attribute/ns7:Attribute5"/>
                                    </ns7:Attribute5>
                                  </xsl:if>
                                </ns7:Attribute>
                              </xsl:if>
                            </ns7:FormulaDetails>
                          </xsl:for-each>
                        </ns7:ListOfFormulaDetails>
                      </xsl:if>
                    </ns7:Formulas>
                  </xsl:for-each>
                </ns7:ListOfFormulas>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:ListOfRouting">
                <ns7:ListOfRouting>
                  <xsl:for-each select="ns7:ListOfRecipe/ns7:ListOfRouting/ns7:Routings">
                    <ns7:Routings>
                      <xsl:if test="ns7:RoutingNo">
                        <ns7:RoutingNo>
                          <xsl:value-of select="ns7:RoutingNo"/>
                        </ns7:RoutingNo>
                      </xsl:if>
                      <xsl:if test="ns7:RoutingID">
                        <ns7:RoutingID>
                          <xsl:value-of select="ns7:RoutingID"/>
                        </ns7:RoutingID>
                      </xsl:if>
                      <xsl:if test="ns7:RoutingVer">
                        <ns7:RoutingVer>
                          <xsl:value-of select="ns7:RoutingVer"/>
                        </ns7:RoutingVer>
                      </xsl:if>
                      <xsl:if test="ns7:RoutingQty">
                        <ns7:RoutingQty>
                          <xsl:value-of select="ns7:RoutingQty"/>
                        </ns7:RoutingQty>
                      </xsl:if>
                      <xsl:if test="ns7:ItemUOM">
                        <ns7:ItemUOM>
                          <xsl:value-of select="ns7:ItemUOM"/>
                        </ns7:ItemUOM>
                      </xsl:if>
                      <xsl:if test="ns7:RoutingDesc">
                        <ns7:RoutingDesc>
                          <xsl:value-of select="ns7:RoutingDesc"/>
                        </ns7:RoutingDesc>
                      </xsl:if>
                      <xsl:if test="ns7:OwnerOrgnCode">
                        <ns7:OwnerOrgnCode>
                          <xsl:value-of select="ns7:OwnerOrgnCode"/>
                        </ns7:OwnerOrgnCode>
                      </xsl:if>
                      <xsl:if test="ns7:RoutingClass">
                        <ns7:RoutingClass>
                          <xsl:value-of select="ns7:RoutingClass"/>
                        </ns7:RoutingClass>
                      </xsl:if>
                      <xsl:if test="ns7:EffectiveStartDate">
                        <ns7:EffectiveStartDate>
                          <xsl:value-of select="ns7:EffectiveStartDate"/>
                        </ns7:EffectiveStartDate>
                      </xsl:if>
                      <xsl:if test="ns7:EffectiveEndDate">
                        <ns7:EffectiveEndDate>
                          <xsl:value-of select="ns7:EffectiveEndDate"/>
                        </ns7:EffectiveEndDate>
                      </xsl:if>
                      <xsl:if test="ns7:ProcessLoss">
                        <ns7:ProcessLoss>
                          <xsl:value-of select="ns7:ProcessLoss"/>
                        </ns7:ProcessLoss>
                      </xsl:if>
                      <xsl:if test="ns7:RoutingStatus">
                        <ns7:RoutingStatus>
                          <xsl:value-of select="ns7:RoutingStatus"/>
                        </ns7:RoutingStatus>
                      </xsl:if>
                      <xsl:if test="ns7:EnforceStepDependency">
                        <ns7:EnforceStepDependency>
                          <xsl:value-of select="ns7:EnforceStepDependency"/>
                        </ns7:EnforceStepDependency>
                      </xsl:if>
                      <xsl:if test="ns7:RoutingstepNo">
                        <ns7:RoutingstepNo>
                          <xsl:value-of select="ns7:RoutingstepNo"/>
                        </ns7:RoutingstepNo>
                      </xsl:if>
                      <xsl:if test="ns7:OperationNO">
                        <ns7:OperationNO>
                          <xsl:value-of select="ns7:OperationNO"/>
                        </ns7:OperationNO>
                      </xsl:if>
                      <xsl:if test="ns7:OperationVER">
                        <ns7:OperationVER>
                          <xsl:value-of select="ns7:OperationVER"/>
                        </ns7:OperationVER>
                      </xsl:if>
                      <xsl:if test="ns7:OperationID">
                        <ns7:OperationID>
                          <xsl:value-of select="ns7:OperationID"/>
                        </ns7:OperationID>
                      </xsl:if>
                      <xsl:if test="ns7:StepQty">
                        <ns7:StepQty>
                          <xsl:value-of select="ns7:StepQty"/>
                        </ns7:StepQty>
                      </xsl:if>
                      <xsl:if test="ns7:StepreleaseType">
                        <ns7:StepreleaseType>
                          <xsl:value-of select="ns7:StepreleaseType"/>
                        </ns7:StepreleaseType>
                      </xsl:if>
                      <xsl:if test="ns7:DepRoutingstepNo">
                        <ns7:DepRoutingstepNo>
                          <xsl:value-of select="ns7:DepRoutingstepNo"/>
                        </ns7:DepRoutingstepNo>
                      </xsl:if>
                      <xsl:if test="ns7:DepType">
                        <ns7:DepType>
                          <xsl:value-of select="ns7:DepType"/>
                        </ns7:DepType>
                      </xsl:if>
                      <xsl:if test="ns7:StandardDelay">
                        <ns7:StandardDelay>
                          <xsl:value-of select="ns7:StandardDelay"/>
                        </ns7:StandardDelay>
                      </xsl:if>
                      <xsl:if test="ns7:TransferQty">
                        <ns7:TransferQty>
                          <xsl:value-of select="ns7:TransferQty"/>
                        </ns7:TransferQty>
                      </xsl:if>
                      <xsl:if test="ns7:TransferPct">
                        <ns7:TransferPct>
                          <xsl:value-of select="ns7:TransferPct"/>
                        </ns7:TransferPct>
                      </xsl:if>
                      <xsl:if test="ns7:Attribute">
                        <ns7:Attribute>
                          <xsl:if test="ns7:Attribute/ns7:AttributeCategory">
                            <ns7:AttributeCategory>
                              <xsl:value-of select="ns7:Attribute/ns7:AttributeCategory"/>
                            </ns7:AttributeCategory>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute1">
                            <ns7:Attribute1>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute1"/>
                            </ns7:Attribute1>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute2">
                            <ns7:Attribute2>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute2"/>
                            </ns7:Attribute2>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute3">
                            <ns7:Attribute3>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute3"/>
                            </ns7:Attribute3>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute4">
                            <ns7:Attribute4>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute4"/>
                            </ns7:Attribute4>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute5">
                            <ns7:Attribute5>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute5"/>
                            </ns7:Attribute5>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute6">
                            <ns7:Attribute6>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute6"/>
                            </ns7:Attribute6>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute7">
                            <ns7:Attribute7>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute7"/>
                            </ns7:Attribute7>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute8">
                            <ns7:Attribute8>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute8"/>
                            </ns7:Attribute8>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute9">
                            <ns7:Attribute9>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute9"/>
                            </ns7:Attribute9>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute10">
                            <ns7:Attribute10>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute10"/>
                            </ns7:Attribute10>
                          </xsl:if>
                        </ns7:Attribute>
                      </xsl:if>
                      <xsl:if test="ns7:ListOfOperartion">
                        <ns7:ListOfOperartion>
                          <xsl:for-each select="ns7:ListOfOperartion/ns7:Operartions">
                            <ns7:Operartions>
                              <xsl:if test="ns7:OperationNumber">
                                <ns7:OperationNumber>
                                  <xsl:value-of select="ns7:OperationNumber"/>
                                </ns7:OperationNumber>
                              </xsl:if>
                              <xsl:if test="ns7:OperationID">
                                <ns7:OperationID>
                                  <xsl:value-of select="ns7:OperationID"/>
                                </ns7:OperationID>
                              </xsl:if>
                              <xsl:if test="ns7:OperationDescription">
                                <ns7:OperationDescription>
                                  <xsl:value-of select="ns7:OperationDescription"/>
                                </ns7:OperationDescription>
                              </xsl:if>
                              <xsl:if test="ns7:OperationVersion">
                                <ns7:OperationVersion>
                                  <xsl:value-of select="ns7:OperationVersion"/>
                                </ns7:OperationVersion>
                              </xsl:if>
                              <xsl:if test="ns7:ProcessQtyUOM">
                                <ns7:ProcessQtyUOM>
                                  <xsl:value-of select="ns7:ProcessQtyUOM"/>
                                </ns7:ProcessQtyUOM>
                              </xsl:if>
                              <xsl:if test="ns7:OperationClass">
                                <ns7:OperationClass>
                                  <xsl:value-of select="ns7:OperationClass"/>
                                </ns7:OperationClass>
                              </xsl:if>
                              <xsl:if test="ns7:ValidFrom">
                                <ns7:ValidFrom>
                                  <xsl:value-of select="ns7:ValidFrom"/>
                                </ns7:ValidFrom>
                              </xsl:if>
                              <xsl:if test="ns7:ValidTo">
                                <ns7:ValidTo>
                                  <xsl:value-of select="ns7:ValidTo"/>
                                </ns7:ValidTo>
                              </xsl:if>
                              <xsl:if test="ns7:Status">
                                <ns7:Status>
                                  <xsl:value-of select="ns7:Status"/>
                                </ns7:Status>
                              </xsl:if>
                              <xsl:if test="ns7:OwnerOrganization">
                                <ns7:OwnerOrganization>
                                  <xsl:value-of select="ns7:OwnerOrganization"/>
                                </ns7:OwnerOrganization>
                              </xsl:if>
                              <xsl:if test="ns7:MinimumTransferQty">
                                <ns7:MinimumTransferQty>
                                  <xsl:value-of select="ns7:MinimumTransferQty"/>
                                </ns7:MinimumTransferQty>
                              </xsl:if>
                              <xsl:if test="ns7:Activity">
                                <ns7:Activity>
                                  <xsl:value-of select="ns7:Activity"/>
                                </ns7:Activity>
                              </xsl:if>
                              <xsl:if test="ns7:ActivityFactor">
                                <ns7:ActivityFactor>
                                  <xsl:value-of select="ns7:ActivityFactor"/>
                                </ns7:ActivityFactor>
                              </xsl:if>
                              <xsl:if test="ns7:SequenceDependency">
                                <ns7:SequenceDependency>
                                  <xsl:value-of select="ns7:SequenceDependency"/>
                                </ns7:SequenceDependency>
                              </xsl:if>
                              <xsl:if test="ns7:OffsetInterval">
                                <ns7:OffsetInterval>
                                  <xsl:value-of select="ns7:OffsetInterval"/>
                                </ns7:OffsetInterval>
                              </xsl:if>
                              <xsl:if test="ns7:Breakable">
                                <ns7:Breakable>
                                  <xsl:value-of select="ns7:Breakable"/>
                                </ns7:Breakable>
                              </xsl:if>
                              <xsl:if test="ns7:MaxBreak">
                                <ns7:MaxBreak>
                                  <xsl:value-of select="ns7:MaxBreak"/>
                                </ns7:MaxBreak>
                              </xsl:if>
                              <xsl:if test="ns7:MaterialScheduled">
                                <ns7:MaterialScheduled>
                                  <xsl:value-of select="ns7:MaterialScheduled"/>
                                </ns7:MaterialScheduled>
                              </xsl:if>
                              <xsl:if test="ns7:Resources">
                                <ns7:Resources>
                                  <xsl:value-of select="ns7:Resources"/>
                                </ns7:Resources>
                              </xsl:if>
                              <xsl:if test="ns7:ResourceUsage">
                                <ns7:ResourceUsage>
                                  <xsl:value-of select="ns7:ResourceUsage"/>
                                </ns7:ResourceUsage>
                              </xsl:if>
                              <xsl:if test="ns7:ResourceCount">
                                <ns7:ResourceCount>
                                  <xsl:value-of select="ns7:ResourceCount"/>
                                </ns7:ResourceCount>
                              </xsl:if>
                              <xsl:if test="ns7:UsageUOM">
                                <ns7:UsageUOM>
                                  <xsl:value-of select="ns7:UsageUOM"/>
                                </ns7:UsageUOM>
                              </xsl:if>
                              <xsl:if test="ns7:ProcessQuantity">
                                <ns7:ProcessQuantity>
                                  <xsl:value-of select="ns7:ProcessQuantity"/>
                                </ns7:ProcessQuantity>
                              </xsl:if>
                              <xsl:if test="ns7:PlanType">
                                <ns7:PlanType>
                                  <xsl:value-of select="ns7:PlanType"/>
                                </ns7:PlanType>
                              </xsl:if>
                              <xsl:if test="ns7:ScaleType">
                                <ns7:ScaleType>
                                  <xsl:value-of select="ns7:ScaleType"/>
                                </ns7:ScaleType>
                              </xsl:if>
                              <xsl:if test="ns7:OperationAttributeS">
                                <ns7:OperationAttributeS>
                                  <xsl:if test="ns7:OperationAttributeS/ns7:OperationAttributeCategory">
                                    <ns7:OperationAttributeCategory>
                                      <xsl:value-of select="ns7:OperationAttributeS/ns7:OperationAttributeCategory"/>
                                    </ns7:OperationAttributeCategory>
                                  </xsl:if>
                                  <xsl:if test="ns7:OperationAttributeS/ns7:OperationAttribute1">
                                    <ns7:OperationAttribute1>
                                      <xsl:value-of select="ns7:OperationAttributeS/ns7:OperationAttribute1"/>
                                    </ns7:OperationAttribute1>
                                  </xsl:if>
                                  <xsl:if test="ns7:OperationAttributeS/ns7:OperationAttribute2">
                                    <ns7:OperationAttribute2>
                                      <xsl:value-of select="ns7:OperationAttributeS/ns7:OperationAttribute2"/>
                                    </ns7:OperationAttribute2>
                                  </xsl:if>
                                  <xsl:if test="ns7:OperationAttributeS/ns7:OperationAttribute3">
                                    <ns7:OperationAttribute3>
                                      <xsl:value-of select="ns7:OperationAttributeS/ns7:OperationAttribute3"/>
                                    </ns7:OperationAttribute3>
                                  </xsl:if>
                                  <xsl:if test="ns7:OperationAttributeS/ns7:OperationAttribute4">
                                    <ns7:OperationAttribute4>
                                      <xsl:value-of select="ns7:OperationAttributeS/ns7:OperationAttribute4"/>
                                    </ns7:OperationAttribute4>
                                  </xsl:if>
                                  <xsl:if test="ns7:OperationAttributeS/ns7:OperationAttribute5">
                                    <ns7:OperationAttribute5>
                                      <xsl:value-of select="ns7:OperationAttributeS/ns7:OperationAttribute5"/>
                                    </ns7:OperationAttribute5>
                                  </xsl:if>
                                </ns7:OperationAttributeS>
                              </xsl:if>
                              <xsl:if test="ns7:ActivityAttributeS">
                                <ns7:ActivityAttributeS>
                                  <xsl:if test="ns7:ActivityAttributeS/ns7:ActivityAttributeCategory">
                                    <ns7:ActivityAttributeCategory>
                                      <xsl:value-of select="ns7:ActivityAttributeS/ns7:ActivityAttributeCategory"/>
                                    </ns7:ActivityAttributeCategory>
                                  </xsl:if>
                                  <xsl:if test="ns7:ActivityAttributeS/ns7:ActivityAttribute1">
                                    <ns7:ActivityAttribute1>
                                      <xsl:value-of select="ns7:ActivityAttributeS/ns7:ActivityAttribute1"/>
                                    </ns7:ActivityAttribute1>
                                  </xsl:if>
                                  <xsl:if test="ns7:ActivityAttributeS/ns7:ActivityAttribute2">
                                    <ns7:ActivityAttribute2>
                                      <xsl:value-of select="ns7:ActivityAttributeS/ns7:ActivityAttribute2"/>
                                    </ns7:ActivityAttribute2>
                                  </xsl:if>
                                  <xsl:if test="ns7:ActivityAttributeS/ns7:ActivityAttribute3">
                                    <ns7:ActivityAttribute3>
                                      <xsl:value-of select="ns7:ActivityAttributeS/ns7:ActivityAttribute3"/>
                                    </ns7:ActivityAttribute3>
                                  </xsl:if>
                                  <xsl:if test="ns7:ActivityAttributeS/ns7:ActivityAttribute4">
                                    <ns7:ActivityAttribute4>
                                      <xsl:value-of select="ns7:ActivityAttributeS/ns7:ActivityAttribute4"/>
                                    </ns7:ActivityAttribute4>
                                  </xsl:if>
                                  <xsl:if test="ns7:ActivityAttributeS/ns7:ActivityAttribute5">
                                    <ns7:ActivityAttribute5>
                                      <xsl:value-of select="ns7:ActivityAttributeS/ns7:ActivityAttribute5"/>
                                    </ns7:ActivityAttribute5>
                                  </xsl:if>
                                </ns7:ActivityAttributeS>
                              </xsl:if>
                              <xsl:if test="ns7:ResourceAttributeS">
                                <ns7:ResourceAttributeS>
                                  <xsl:if test="ns7:ResourceAttributeS/ns7:ResourceAttributeCategory">
                                    <ns7:ResourceAttributeCategory>
                                      <xsl:value-of select="ns7:ResourceAttributeS/ns7:ResourceAttributeCategory"/>
                                    </ns7:ResourceAttributeCategory>
                                  </xsl:if>
                                  <xsl:if test="ns7:ResourceAttributeS/ns7:ResourceAttribute1">
                                    <ns7:ResourceAttribute1>
                                      <xsl:value-of select="ns7:ResourceAttributeS/ns7:ResourceAttribute1"/>
                                    </ns7:ResourceAttribute1>
                                  </xsl:if>
                                  <xsl:if test="ns7:ResourceAttributeS/ns7:ResourceAttribute2">
                                    <ns7:ResourceAttribute2>
                                      <xsl:value-of select="ns7:ResourceAttributeS/ns7:ResourceAttribute2"/>
                                    </ns7:ResourceAttribute2>
                                  </xsl:if>
                                  <xsl:if test="ns7:ResourceAttributeS/ns7:ResourceAttribute3">
                                    <ns7:ResourceAttribute3>
                                      <xsl:value-of select="ns7:ResourceAttributeS/ns7:ResourceAttribute3"/>
                                    </ns7:ResourceAttribute3>
                                  </xsl:if>
                                  <xsl:if test="ns7:ResourceAttributeS/ns7:ResourceAttribute4">
                                    <ns7:ResourceAttribute4>
                                      <xsl:value-of select="ns7:ResourceAttributeS/ns7:ResourceAttribute4"/>
                                    </ns7:ResourceAttribute4>
                                  </xsl:if>
                                  <xsl:if test="ns7:ResourceAttributeS/ns7:ResourceAttribute5">
                                    <ns7:ResourceAttribute5>
                                      <xsl:value-of select="ns7:ResourceAttributeS/ns7:ResourceAttribute5"/>
                                    </ns7:ResourceAttribute5>
                                  </xsl:if>
                                </ns7:ResourceAttributeS>
                              </xsl:if>
                            </ns7:Operartions>
                          </xsl:for-each>
                        </ns7:ListOfOperartion>
                      </xsl:if>
                    </ns7:Routings>
                  </xsl:for-each>
                </ns7:ListOfRouting>
              </xsl:if>
              <xsl:if test="ns7:ListOfRecipe/ns7:ListOfRecipeVRS">
                <ns7:ListOfRecipeVRS>
                  <xsl:for-each select="ns7:ListOfRecipe/ns7:ListOfRecipeVRS/ns7:RecipeVRS">
                    <ns7:RecipeVRS>
                      <xsl:if test="ns7:RecipeNumber">
                        <ns7:RecipeNumber>
                          <xsl:value-of select="ns7:RecipeNumber"/>
                        </ns7:RecipeNumber>
                      </xsl:if>
                      <xsl:if test="ns7:RecipeVersion">
                        <ns7:RecipeVersion>
                          <xsl:value-of select="ns7:RecipeVersion"/>
                        </ns7:RecipeVersion>
                      </xsl:if>
                      <xsl:if test="ns7:RecipeID">
                        <ns7:RecipeID>
                          <xsl:value-of select="ns7:RecipeID"/>
                        </ns7:RecipeID>
                      </xsl:if>
                      <xsl:if test="ns7:RecipeVRID">
                        <ns7:RecipeVRID>
                          <xsl:value-of select="ns7:RecipeVRID"/>
                        </ns7:RecipeVRID>
                      </xsl:if>
                      <xsl:if test="ns7:OrganizationCode">
                        <ns7:OrganizationCode>
                          <xsl:value-of select="ns7:OrganizationCode"/>
                        </ns7:OrganizationCode>
                      </xsl:if>
                      <xsl:if test="ns7:Product">
                        <ns7:Product>
                          <xsl:value-of select="ns7:Product"/>
                        </ns7:Product>
                      </xsl:if>
                      <xsl:if test="ns7:RecipeUse">
                        <ns7:RecipeUse>
                          <xsl:value-of select="ns7:RecipeUse"/>
                        </ns7:RecipeUse>
                      </xsl:if>
                      <xsl:if test="ns7:Preference">
                        <ns7:Preference>
                          <xsl:value-of select="ns7:Preference"/>
                        </ns7:Preference>
                      </xsl:if>
                      <xsl:if test="ns7:Startdate">
                        <ns7:Startdate>
                          <xsl:value-of select="ns7:Startdate"/>
                        </ns7:Startdate>
                      </xsl:if>
                      <xsl:if test="ns7:EndDate">
                        <ns7:EndDate>
                          <xsl:value-of select="ns7:EndDate"/>
                        </ns7:EndDate>
                      </xsl:if>
                      <xsl:if test="ns7:MinimumQuantity">
                        <ns7:MinimumQuantity>
                          <xsl:value-of select="ns7:MinimumQuantity"/>
                        </ns7:MinimumQuantity>
                      </xsl:if>
                      <xsl:if test="ns7:MaximumQuantity">
                        <ns7:MaximumQuantity>
                          <xsl:value-of select="ns7:MaximumQuantity"/>
                        </ns7:MaximumQuantity>
                      </xsl:if>
                      <xsl:if test="ns7:StandardQuantity">
                        <ns7:StandardQuantity>
                          <xsl:value-of select="ns7:StandardQuantity"/>
                        </ns7:StandardQuantity>
                      </xsl:if>
                      <xsl:if test="ns7:ItemUOM">
                        <ns7:ItemUOM>
                          <xsl:value-of select="ns7:ItemUOM"/>
                        </ns7:ItemUOM>
                      </xsl:if>
                      <xsl:if test="ns7:InventoryMinimumQuantity">
                        <ns7:InventoryMinimumQuantity>
                          <xsl:value-of select="ns7:InventoryMinimumQuantity"/>
                        </ns7:InventoryMinimumQuantity>
                      </xsl:if>
                      <xsl:if test="ns7:InventoryMaximumQuantity">
                        <ns7:InventoryMaximumQuantity>
                          <xsl:value-of select="ns7:InventoryMaximumQuantity"/>
                        </ns7:InventoryMaximumQuantity>
                      </xsl:if>
                      <xsl:if test="ns7:ValidityRuleStatus">
                        <ns7:ValidityRuleStatus>
                          <xsl:value-of select="ns7:ValidityRuleStatus"/>
                        </ns7:ValidityRuleStatus>
                      </xsl:if>
                      <xsl:if test="ns7:Attribute">
                        <ns7:Attribute>
                          <xsl:if test="ns7:Attribute/ns7:AttributeCategory">
                            <ns7:AttributeCategory>
                              <xsl:value-of select="ns7:Attribute/ns7:AttributeCategory"/>
                            </ns7:AttributeCategory>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute1">
                            <ns7:Attribute1>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute1"/>
                            </ns7:Attribute1>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute2">
                            <ns7:Attribute2>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute2"/>
                            </ns7:Attribute2>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute3">
                            <ns7:Attribute3>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute3"/>
                            </ns7:Attribute3>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute4">
                            <ns7:Attribute4>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute4"/>
                            </ns7:Attribute4>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute5">
                            <ns7:Attribute5>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute5"/>
                            </ns7:Attribute5>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute6">
                            <ns7:Attribute6>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute6"/>
                            </ns7:Attribute6>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute7">
                            <ns7:Attribute7>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute7"/>
                            </ns7:Attribute7>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute8">
                            <ns7:Attribute8>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute8"/>
                            </ns7:Attribute8>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute9">
                            <ns7:Attribute9>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute9"/>
                            </ns7:Attribute9>
                          </xsl:if>
                          <xsl:if test="ns7:Attribute/ns7:Attribute10">
                            <ns7:Attribute10>
                              <xsl:value-of select="ns7:Attribute/ns7:Attribute10"/>
                            </ns7:Attribute10>
                          </xsl:if>
                        </ns7:Attribute>
                      </xsl:if>
                    </ns7:RecipeVRS>
                  </xsl:for-each>
                </ns7:ListOfRecipeVRS>
              </xsl:if>
            </ns7:ListOfRecipe>
          </xsl:if>
        </ns7:ProductStructureDetails>
      </xsl:for-each>
    </ns1:QueryProductStructureAddRs>
  </xsl:template>
</xsl:stylesheet>
