<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext utl dvm socket"
                xmlns:ns1="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns6="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:tns="http://oracle.com/sca/soapservice/Application2/NUC_EBizProductStructure_ABS/EbizProductStructure"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/ProductStructureABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryProductStructureAddRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/ProductStructureABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryProductStructureAddRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE APR 26 08:22:08 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:QueryProductStructureAddRs>
      <ns6:HeaderRs>
        <ns6:RequestDetails>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:TransactionRequestID">
            <ns6:TransactionRequestID>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:TransactionRequestID"/>
            </ns6:TransactionRequestID>
          </xsl:if>
          <ns6:Language>
            <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:Language"/>
          </ns6:Language>
          <ns6:ComponentID>
            <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:ComponentID"/>
          </ns6:ComponentID>
          <ns6:ServiceName>
            <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:ServiceName"/>
          </ns6:ServiceName>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:TransactionIDREF">
            <ns6:TransactionIDREF>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:TransactionIDREF"/>
            </ns6:TransactionIDREF>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:TransactionName">
            <ns6:TransactionName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:TransactionName"/>
            </ns6:TransactionName>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:FileName">
            <ns6:FileName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:FileName"/>
            </ns6:FileName>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:FileInstanceID">
            <ns6:FileInstanceID>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:FileInstanceID"/>
            </ns6:FileInstanceID>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:Source">
            <ns6:Source>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:Source"/>
            </ns6:Source>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:Target">
            <ns6:Target>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:Target"/>
            </ns6:Target>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:HostName">
            <ns6:HostName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:HostName"/>
            </ns6:HostName>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:UserName">
            <ns6:UserName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:UserName"/>
            </ns6:UserName>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:UserRole">
            <ns6:UserRole>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:UserRole"/>
            </ns6:UserRole>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:AdminEmail">
            <ns6:AdminEmail>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:AdminEmail"/>
            </ns6:AdminEmail>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:ApplicationResponsibility">
            <ns6:ApplicationResponsibility>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:ApplicationResponsibility"/>
            </ns6:ApplicationResponsibility>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:EOFFlag">
            <ns6:EOFFlag>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:EOFFlag"/>
            </ns6:EOFFlag>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:SOFFlag">
            <ns6:SOFFlag>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:SOFFlag"/>
            </ns6:SOFFlag>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:FileRecordCount">
            <ns6:FileRecordCount>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:FileRecordCount"/>
            </ns6:FileRecordCount>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:TimeStamp">
            <ns6:TimeStamp>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:TimeStamp"/>
            </ns6:TimeStamp>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:MillName">
            <ns6:MillName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns6:HeaderRs/ns6:RequestDetails/ns6:MillName"/>
            </ns6:MillName>
          </xsl:if>
        </ns6:RequestDetails>
      </ns6:HeaderRs>
      <xsl:for-each select="/ns0:QueryProductStructureAddRs/ns4:ProductStructureDetails">
        <ns4:ProductStructureDetails>
          <xsl:if test="ns4:ListOfRecipe">
            <ns4:ListOfRecipe>
              <xsl:if test="ns4:ListOfRecipe/ns4:RecipeNumber">
                <ns4:RecipeNumber>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RecipeNumber"/>
                </ns4:RecipeNumber>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:RecipeVersion">
                <ns4:RecipeVersion>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RecipeVersion"/>
                </ns4:RecipeVersion>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:RecipeID">
                <ns4:RecipeID>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RecipeID"/>
                </ns4:RecipeID>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:RecipeDescription">
                <ns4:RecipeDescription>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RecipeDescription"/>
                </ns4:RecipeDescription>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:OwnerOrganization">
                <ns4:OwnerOrganization>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:OwnerOrganization"/>
                </ns4:OwnerOrganization>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:CreationOrganization">
                <ns4:CreationOrganization>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:CreationOrganization"/>
                </ns4:CreationOrganization>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:Product">
                <ns4:Product>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:Product"/>
                </ns4:Product>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:FormulaNumber">
                <ns4:FormulaNumber>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:FormulaNumber"/>
                </ns4:FormulaNumber>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:FormulaVersion">
                <ns4:FormulaVersion>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:FormulaVersion"/>
                </ns4:FormulaVersion>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:FormulaID">
                <ns4:FormulaID>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:FormulaID"/>
                </ns4:FormulaID>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:RountingID">
                <ns4:RountingID>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RountingID"/>
                </ns4:RountingID>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:RoutingNumber">
                <ns4:RoutingNumber>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RoutingNumber"/>
                </ns4:RoutingNumber>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:RoutingVersion">
                <ns4:RoutingVersion>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RoutingVersion"/>
                </ns4:RoutingVersion>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:RecipeStatus">
                <ns4:RecipeStatus>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RecipeStatus"/>
                </ns4:RecipeStatus>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:PlannedProcessLoss">
                <ns4:PlannedProcessLoss>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:PlannedProcessLoss"/>
                </ns4:PlannedProcessLoss>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:CalculateStepQuantity">
                <ns4:CalculateStepQuantity>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:CalculateStepQuantity"/>
                </ns4:CalculateStepQuantity>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:OrganizationCode">
                <ns4:OrganizationCode>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:OrganizationCode"/>
                </ns4:OrganizationCode>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:OrganizationName">
                <ns4:OrganizationName>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:OrganizationName"/>
                </ns4:OrganizationName>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:ProcessLoss">
                <ns4:ProcessLoss>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:ProcessLoss"/>
                </ns4:ProcessLoss>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:RoutingStep">
                <ns4:RoutingStep>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:RoutingStep"/>
                </ns4:RoutingStep>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:Line">
                <ns4:Line>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:Line"/>
                </ns4:Line>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:Attribute">
                <ns4:Attribute>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:AttributeCategory">
                    <ns4:AttributeCategory>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:AttributeCategory"/>
                    </ns4:AttributeCategory>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute1">
                    <ns4:Attribute1>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute1"/>
                    </ns4:Attribute1>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute2">
                    <ns4:Attribute2>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute2"/>
                    </ns4:Attribute2>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute3">
                    <ns4:Attribute3>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute3"/>
                    </ns4:Attribute3>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute4">
                    <ns4:Attribute4>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute4"/>
                    </ns4:Attribute4>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute5">
                    <ns4:Attribute5>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute5"/>
                    </ns4:Attribute5>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute6">
                    <ns4:Attribute6>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute6"/>
                    </ns4:Attribute6>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute7">
                    <ns4:Attribute7>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute7"/>
                    </ns4:Attribute7>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute8">
                    <ns4:Attribute8>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute8"/>
                    </ns4:Attribute8>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute9">
                    <ns4:Attribute9>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute9"/>
                    </ns4:Attribute9>
                  </xsl:if>
                  <xsl:if test="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute10">
                    <ns4:Attribute10>
                      <xsl:value-of select="ns4:ListOfRecipe/ns4:Attribute/ns4:Attribute10"/>
                    </ns4:Attribute10>
                  </xsl:if>
                </ns4:Attribute>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:ResourceName">
                <ns4:ResourceName>
                  <xsl:value-of select="ns4:ListOfRecipe/ns4:ResourceName"/>
                </ns4:ResourceName>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:ListOfFormulas">
                <ns4:ListOfFormulas>
                  <xsl:for-each select="ns4:ListOfRecipe/ns4:ListOfFormulas/ns4:Formulas">
                    <ns4:Formulas>
                      <xsl:if test="ns4:FormulaNumber">
                        <ns4:FormulaNumber>
                          <xsl:value-of select="ns4:FormulaNumber"/>
                        </ns4:FormulaNumber>
                      </xsl:if>
                      <xsl:if test="ns4:FormulaVersion">
                        <ns4:FormulaVersion>
                          <xsl:value-of select="ns4:FormulaVersion"/>
                        </ns4:FormulaVersion>
                      </xsl:if>
                      <xsl:if test="ns4:FormulaID">
                        <ns4:FormulaID>
                          <xsl:value-of select="ns4:FormulaID"/>
                        </ns4:FormulaID>
                      </xsl:if>
                      <xsl:if test="ns4:FormulaType">
                        <ns4:FormulaType>
                          <xsl:value-of select="ns4:FormulaType"/>
                        </ns4:FormulaType>
                      </xsl:if>
                      <xsl:if test="ns4:FormulaDescription">
                        <ns4:FormulaDescription>
                          <xsl:value-of select="ns4:FormulaDescription"/>
                        </ns4:FormulaDescription>
                      </xsl:if>
                      <xsl:if test="ns4:FormulaClass">
                        <ns4:FormulaClass>
                          <xsl:value-of select="ns4:FormulaClass"/>
                        </ns4:FormulaClass>
                      </xsl:if>
                      <xsl:if test="ns4:Comments">
                        <ns4:Comments>
                          <xsl:value-of select="ns4:Comments"/>
                        </ns4:Comments>
                      </xsl:if>
                      <xsl:if test="ns4:OrganizationCode">
                        <ns4:OrganizationCode>
                          <xsl:value-of select="ns4:OrganizationCode"/>
                        </ns4:OrganizationCode>
                      </xsl:if>
                      <xsl:if test="ns4:OwnerName">
                        <ns4:OwnerName>
                          <xsl:value-of select="ns4:OwnerName"/>
                        </ns4:OwnerName>
                      </xsl:if>
                      <xsl:if test="ns4:FormulaStatus">
                        <ns4:FormulaStatus>
                          <xsl:value-of select="ns4:FormulaStatus"/>
                        </ns4:FormulaStatus>
                      </xsl:if>
                      <xsl:if test="ns4:ScaleTypeHeader">
                        <ns4:ScaleTypeHeader>
                          <xsl:value-of select="ns4:ScaleTypeHeader"/>
                        </ns4:ScaleTypeHeader>
                      </xsl:if>
                      <xsl:if test="ns4:CalcProductQty">
                        <ns4:CalcProductQty>
                          <xsl:value-of select="ns4:CalcProductQty"/>
                        </ns4:CalcProductQty>
                      </xsl:if>
                      <xsl:if test="ns4:Attribute">
                        <ns4:Attribute>
                          <xsl:if test="ns4:Attribute/ns4:AttributeCategory">
                            <ns4:AttributeCategory>
                              <xsl:value-of select="ns4:Attribute/ns4:AttributeCategory"/>
                            </ns4:AttributeCategory>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute1">
                            <ns4:Attribute1>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute1"/>
                            </ns4:Attribute1>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute2">
                            <ns4:Attribute2>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute2"/>
                            </ns4:Attribute2>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute3">
                            <ns4:Attribute3>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute3"/>
                            </ns4:Attribute3>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute4">
                            <ns4:Attribute4>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute4"/>
                            </ns4:Attribute4>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute5">
                            <ns4:Attribute5>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute5"/>
                            </ns4:Attribute5>
                          </xsl:if>
                        </ns4:Attribute>
                      </xsl:if>
                      <xsl:if test="ns4:ListOfFormulaDetails">
                        <ns4:ListOfFormulaDetails>
                          <xsl:for-each select="ns4:ListOfFormulaDetails/ns4:FormulaDetails">
                            <ns4:FormulaDetails>
                              <xsl:if test="ns4:FormulaID">
                                <ns4:FormulaID>
                                  <xsl:value-of select="ns4:FormulaID"/>
                                </ns4:FormulaID>
                              </xsl:if>
                              <xsl:if test="ns4:LineNumber">
                                <ns4:LineNumber>
                                  <xsl:value-of select="ns4:LineNumber"/>
                                </ns4:LineNumber>
                              </xsl:if>
                              <xsl:if test="ns4:ItemType">
                                <ns4:ItemType>
                                  <xsl:value-of select="ns4:ItemType"/>
                                </ns4:ItemType>
                              </xsl:if>
                              <xsl:if test="ns4:FormulaItemType">
                                <ns4:FormulaItemType>
                                  <xsl:value-of select="ns4:FormulaItemType"/>
                                </ns4:FormulaItemType>
                              </xsl:if>
                              <xsl:if test="ns4:ItemNumber">
                                <ns4:ItemNumber>
                                  <xsl:value-of select="ns4:ItemNumber"/>
                                </ns4:ItemNumber>
                              </xsl:if>
                              <xsl:if test="ns4:Description">
                                <ns4:Description>
                                  <xsl:value-of select="ns4:Description"/>
                                </ns4:Description>
                              </xsl:if>
                              <xsl:if test="ns4:Quantity">
                                <ns4:Quantity>
                                  <xsl:value-of select="ns4:Quantity"/>
                                </ns4:Quantity>
                              </xsl:if>
                              <xsl:if test="ns4:ItemUOM">
                                <ns4:ItemUOM>
                                  <xsl:value-of select="ns4:ItemUOM"/>
                                </ns4:ItemUOM>
                              </xsl:if>
                              <xsl:if test="ns4:YieldConsumptionType">
                                <ns4:YieldConsumptionType>
                                  <xsl:value-of select="ns4:YieldConsumptionType"/>
                                </ns4:YieldConsumptionType>
                              </xsl:if>
                              <xsl:if test="ns4:ScrapFactor">
                                <ns4:ScrapFactor>
                                  <xsl:value-of select="ns4:ScrapFactor"/>
                                </ns4:ScrapFactor>
                              </xsl:if>
                              <xsl:if test="ns4:ScaleType">
                                <ns4:ScaleType>
                                  <xsl:value-of select="ns4:ScaleType"/>
                                </ns4:ScaleType>
                              </xsl:if>
                              <xsl:if test="ns4:ByProductType">
                                <ns4:ByProductType>
                                  <xsl:value-of select="ns4:ByProductType"/>
                                </ns4:ByProductType>
                              </xsl:if>
                              <xsl:if test="ns4:CostAllocation">
                                <ns4:CostAllocation>
                                  <xsl:value-of select="ns4:CostAllocation"/>
                                </ns4:CostAllocation>
                              </xsl:if>
                              <xsl:if test="ns4:ScaleMultiple">
                                <ns4:ScaleMultiple>
                                  <xsl:value-of select="ns4:ScaleMultiple"/>
                                </ns4:ScaleMultiple>
                              </xsl:if>
                              <xsl:if test="ns4:PhantomType">
                                <ns4:PhantomType>
                                  <xsl:value-of select="ns4:PhantomType"/>
                                </ns4:PhantomType>
                              </xsl:if>
                              <xsl:if test="ns4:ContributeToYield">
                                <ns4:ContributeToYield>
                                  <xsl:value-of select="ns4:ContributeToYield"/>
                                </ns4:ContributeToYield>
                              </xsl:if>
                              <xsl:if test="ns4:ContributeToStepQuantity">
                                <ns4:ContributeToStepQuantity>
                                  <xsl:value-of select="ns4:ContributeToStepQuantity"/>
                                </ns4:ContributeToStepQuantity>
                              </xsl:if>
                              <xsl:if test="ns4:ScaleRoundingVariance">
                                <ns4:ScaleRoundingVariance>
                                  <xsl:value-of select="ns4:ScaleRoundingVariance"/>
                                </ns4:ScaleRoundingVariance>
                              </xsl:if>
                              <xsl:if test="ns4:RoundingDirection">
                                <ns4:RoundingDirection>
                                  <xsl:value-of select="ns4:RoundingDirection"/>
                                </ns4:RoundingDirection>
                              </xsl:if>
                              <xsl:if test="ns4:Attribute">
                                <ns4:Attribute>
                                  <xsl:if test="ns4:Attribute/ns4:AttributeCategory">
                                    <ns4:AttributeCategory>
                                      <xsl:value-of select="ns4:Attribute/ns4:AttributeCategory"/>
                                    </ns4:AttributeCategory>
                                  </xsl:if>
                                  <xsl:if test="ns4:Attribute/ns4:Attribute1">
                                    <ns4:Attribute1>
                                      <xsl:value-of select="ns4:Attribute/ns4:Attribute1"/>
                                    </ns4:Attribute1>
                                  </xsl:if>
                                  <xsl:if test="ns4:Attribute/ns4:Attribute2">
                                    <ns4:Attribute2>
                                      <xsl:value-of select="ns4:Attribute/ns4:Attribute2"/>
                                    </ns4:Attribute2>
                                  </xsl:if>
                                  <xsl:if test="ns4:Attribute/ns4:Attribute3">
                                    <ns4:Attribute3>
                                      <xsl:value-of select="ns4:Attribute/ns4:Attribute3"/>
                                    </ns4:Attribute3>
                                  </xsl:if>
                                  <xsl:if test="ns4:Attribute/ns4:Attribute4">
                                    <ns4:Attribute4>
                                      <xsl:value-of select="ns4:Attribute/ns4:Attribute4"/>
                                    </ns4:Attribute4>
                                  </xsl:if>
                                  <xsl:if test="ns4:Attribute/ns4:Attribute5">
                                    <ns4:Attribute5>
                                      <xsl:value-of select="ns4:Attribute/ns4:Attribute5"/>
                                    </ns4:Attribute5>
                                  </xsl:if>
                                </ns4:Attribute>
                              </xsl:if>
                            </ns4:FormulaDetails>
                          </xsl:for-each>
                        </ns4:ListOfFormulaDetails>
                      </xsl:if>
                    </ns4:Formulas>
                  </xsl:for-each>
                </ns4:ListOfFormulas>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:ListOfRouting">
                <ns4:ListOfRouting>
                  <xsl:for-each select="ns4:ListOfRecipe/ns4:ListOfRouting/ns4:Routings">
                    <ns4:Routings>
                      <xsl:if test="ns4:RoutingNo">
                        <ns4:RoutingNo>
                          <xsl:value-of select="ns4:RoutingNo"/>
                        </ns4:RoutingNo>
                      </xsl:if>
                      <xsl:if test="ns4:RoutingID">
                        <ns4:RoutingID>
                          <xsl:value-of select="ns4:RoutingID"/>
                        </ns4:RoutingID>
                      </xsl:if>
                      <xsl:if test="ns4:RoutingVer">
                        <ns4:RoutingVer>
                          <xsl:value-of select="ns4:RoutingVer"/>
                        </ns4:RoutingVer>
                      </xsl:if>
                      <xsl:if test="ns4:RoutingQty">
                        <ns4:RoutingQty>
                          <xsl:value-of select="ns4:RoutingQty"/>
                        </ns4:RoutingQty>
                      </xsl:if>
                      <xsl:if test="ns4:ItemUOM">
                        <ns4:ItemUOM>
                          <xsl:value-of select="ns4:ItemUOM"/>
                        </ns4:ItemUOM>
                      </xsl:if>
                      <xsl:if test="ns4:RoutingDesc">
                        <ns4:RoutingDesc>
                          <xsl:value-of select="ns4:RoutingDesc"/>
                        </ns4:RoutingDesc>
                      </xsl:if>
                      <xsl:if test="ns4:OwnerOrgnCode">
                        <ns4:OwnerOrgnCode>
                          <xsl:value-of select="ns4:OwnerOrgnCode"/>
                        </ns4:OwnerOrgnCode>
                      </xsl:if>
                      <xsl:if test="ns4:RoutingClass">
                        <ns4:RoutingClass>
                          <xsl:value-of select="ns4:RoutingClass"/>
                        </ns4:RoutingClass>
                      </xsl:if>
                      <xsl:if test="ns4:EffectiveStartDate">
                        <ns4:EffectiveStartDate>
                          <xsl:value-of select="ns4:EffectiveStartDate"/>
                        </ns4:EffectiveStartDate>
                      </xsl:if>
                      <xsl:if test="ns4:EffectiveEndDate">
                        <ns4:EffectiveEndDate>
                          <xsl:value-of select="ns4:EffectiveEndDate"/>
                        </ns4:EffectiveEndDate>
                      </xsl:if>
                      <xsl:if test="ns4:ProcessLoss">
                        <ns4:ProcessLoss>
                          <xsl:value-of select="ns4:ProcessLoss"/>
                        </ns4:ProcessLoss>
                      </xsl:if>
                      <xsl:if test="ns4:RoutingStatus">
                        <ns4:RoutingStatus>
                          <xsl:value-of select="ns4:RoutingStatus"/>
                        </ns4:RoutingStatus>
                      </xsl:if>
                      <xsl:if test="ns4:EnforceStepDependency">
                        <ns4:EnforceStepDependency>
                          <xsl:value-of select="ns4:EnforceStepDependency"/>
                        </ns4:EnforceStepDependency>
                      </xsl:if>
                      <xsl:if test="ns4:RoutingstepNo">
                        <ns4:RoutingstepNo>
                          <xsl:value-of select="ns4:RoutingstepNo"/>
                        </ns4:RoutingstepNo>
                      </xsl:if>
                      <xsl:if test="ns4:OperationNO">
                        <ns4:OperationNO>
                          <xsl:value-of select="ns4:OperationNO"/>
                        </ns4:OperationNO>
                      </xsl:if>
                      <xsl:if test="ns4:OperationVER">
                        <ns4:OperationVER>
                          <xsl:value-of select="ns4:OperationVER"/>
                        </ns4:OperationVER>
                      </xsl:if>
                      <xsl:if test="ns4:OperationID">
                        <ns4:OperationID>
                          <xsl:value-of select="ns4:OperationID"/>
                        </ns4:OperationID>
                      </xsl:if>
                      <xsl:if test="ns4:StepQty">
                        <ns4:StepQty>
                          <xsl:value-of select="ns4:StepQty"/>
                        </ns4:StepQty>
                      </xsl:if>
                      <xsl:if test="ns4:StepreleaseType">
                        <ns4:StepreleaseType>
                          <xsl:value-of select="ns4:StepreleaseType"/>
                        </ns4:StepreleaseType>
                      </xsl:if>
                      <xsl:if test="ns4:DepRoutingstepNo">
                        <ns4:DepRoutingstepNo>
                          <xsl:value-of select="ns4:DepRoutingstepNo"/>
                        </ns4:DepRoutingstepNo>
                      </xsl:if>
                      <xsl:if test="ns4:DepType">
                        <ns4:DepType>
                          <xsl:value-of select="ns4:DepType"/>
                        </ns4:DepType>
                      </xsl:if>
                      <xsl:if test="ns4:StandardDelay">
                        <ns4:StandardDelay>
                          <xsl:value-of select="ns4:StandardDelay"/>
                        </ns4:StandardDelay>
                      </xsl:if>
                      <xsl:if test="ns4:TransferQty">
                        <ns4:TransferQty>
                          <xsl:value-of select="ns4:TransferQty"/>
                        </ns4:TransferQty>
                      </xsl:if>
                      <xsl:if test="ns4:TransferPct">
                        <ns4:TransferPct>
                          <xsl:value-of select="ns4:TransferPct"/>
                        </ns4:TransferPct>
                      </xsl:if>
                      <xsl:if test="ns4:Attribute">
                        <ns4:Attribute>
                          <xsl:if test="ns4:Attribute/ns4:AttributeCategory">
                            <ns4:AttributeCategory>
                              <xsl:value-of select="ns4:Attribute/ns4:AttributeCategory"/>
                            </ns4:AttributeCategory>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute1">
                            <ns4:Attribute1>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute1"/>
                            </ns4:Attribute1>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute2">
                            <ns4:Attribute2>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute2"/>
                            </ns4:Attribute2>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute3">
                            <ns4:Attribute3>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute3"/>
                            </ns4:Attribute3>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute4">
                            <ns4:Attribute4>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute4"/>
                            </ns4:Attribute4>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute5">
                            <ns4:Attribute5>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute5"/>
                            </ns4:Attribute5>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute6">
                            <ns4:Attribute6>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute6"/>
                            </ns4:Attribute6>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute7">
                            <ns4:Attribute7>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute7"/>
                            </ns4:Attribute7>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute8">
                            <ns4:Attribute8>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute8"/>
                            </ns4:Attribute8>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute9">
                            <ns4:Attribute9>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute9"/>
                            </ns4:Attribute9>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute10">
                            <ns4:Attribute10>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute10"/>
                            </ns4:Attribute10>
                          </xsl:if>
                        </ns4:Attribute>
                      </xsl:if>
                      <xsl:if test="ns4:ListOfOperartion">
                        <ns4:ListOfOperartion>
                          <xsl:for-each select="ns4:ListOfOperartion/ns4:Operartions">
                            <ns4:Operartions>
                              <xsl:if test="ns4:OperationNumber">
                                <ns4:OperationNumber>
                                  <xsl:value-of select="ns4:OperationNumber"/>
                                </ns4:OperationNumber>
                              </xsl:if>
                              <xsl:if test="ns4:OperationID">
                                <ns4:OperationID>
                                  <xsl:value-of select="ns4:OperationID"/>
                                </ns4:OperationID>
                              </xsl:if>
                              <xsl:if test="ns4:OperationDescription">
                                <ns4:OperationDescription>
                                  <xsl:value-of select="ns4:OperationDescription"/>
                                </ns4:OperationDescription>
                              </xsl:if>
                              <xsl:if test="ns4:OperationVersion">
                                <ns4:OperationVersion>
                                  <xsl:value-of select="ns4:OperationVersion"/>
                                </ns4:OperationVersion>
                              </xsl:if>
                              <xsl:if test="ns4:ProcessQtyUOM">
                                <ns4:ProcessQtyUOM>
                                  <xsl:value-of select="ns4:ProcessQtyUOM"/>
                                </ns4:ProcessQtyUOM>
                              </xsl:if>
                              <xsl:if test="ns4:OperationClass">
                                <ns4:OperationClass>
                                  <xsl:value-of select="ns4:OperationClass"/>
                                </ns4:OperationClass>
                              </xsl:if>
                              <xsl:if test="ns4:ValidFrom">
                                <ns4:ValidFrom>
                                  <xsl:value-of select="ns4:ValidFrom"/>
                                </ns4:ValidFrom>
                              </xsl:if>
                              <xsl:if test="ns4:ValidTo">
                                <ns4:ValidTo>
                                  <xsl:value-of select="ns4:ValidTo"/>
                                </ns4:ValidTo>
                              </xsl:if>
                              <xsl:if test="ns4:Status">
                                <ns4:Status>
                                  <xsl:value-of select="ns4:Status"/>
                                </ns4:Status>
                              </xsl:if>
                              <xsl:if test="ns4:OwnerOrganization">
                                <ns4:OwnerOrganization>
                                  <xsl:value-of select="ns4:OwnerOrganization"/>
                                </ns4:OwnerOrganization>
                              </xsl:if>
                              <xsl:if test="ns4:MinimumTransferQty">
                                <ns4:MinimumTransferQty>
                                  <xsl:value-of select="ns4:MinimumTransferQty"/>
                                </ns4:MinimumTransferQty>
                              </xsl:if>
                              <xsl:if test="ns4:Activity">
                                <ns4:Activity>
                                  <xsl:value-of select="ns4:Activity"/>
                                </ns4:Activity>
                              </xsl:if>
                              <xsl:if test="ns4:ActivityFactor">
                                <ns4:ActivityFactor>
                                  <xsl:value-of select="ns4:ActivityFactor"/>
                                </ns4:ActivityFactor>
                              </xsl:if>
                              <xsl:if test="ns4:SequenceDependency">
                                <ns4:SequenceDependency>
                                  <xsl:value-of select="ns4:SequenceDependency"/>
                                </ns4:SequenceDependency>
                              </xsl:if>
                              <xsl:if test="ns4:OffsetInterval">
                                <ns4:OffsetInterval>
                                  <xsl:value-of select="ns4:OffsetInterval"/>
                                </ns4:OffsetInterval>
                              </xsl:if>
                              <xsl:if test="ns4:Breakable">
                                <ns4:Breakable>
                                  <xsl:value-of select="ns4:Breakable"/>
                                </ns4:Breakable>
                              </xsl:if>
                              <xsl:if test="ns4:MaxBreak">
                                <ns4:MaxBreak>
                                  <xsl:value-of select="ns4:MaxBreak"/>
                                </ns4:MaxBreak>
                              </xsl:if>
                              <xsl:if test="ns4:MaterialScheduled">
                                <ns4:MaterialScheduled>
                                  <xsl:value-of select="ns4:MaterialScheduled"/>
                                </ns4:MaterialScheduled>
                              </xsl:if>
                              <xsl:if test="ns4:Resources">
                                <ns4:Resources>
                                  <xsl:value-of select="ns4:Resources"/>
                                </ns4:Resources>
                              </xsl:if>
                              <xsl:if test="ns4:ResourceUsage">
                                <ns4:ResourceUsage>
                                  <xsl:value-of select="ns4:ResourceUsage"/>
                                </ns4:ResourceUsage>
                              </xsl:if>
                              <xsl:if test="ns4:ResourceCount">
                                <ns4:ResourceCount>
                                  <xsl:value-of select="ns4:ResourceCount"/>
                                </ns4:ResourceCount>
                              </xsl:if>
                              <xsl:if test="ns4:UsageUOM">
                                <ns4:UsageUOM>
                                  <xsl:value-of select="ns4:UsageUOM"/>
                                </ns4:UsageUOM>
                              </xsl:if>
                              <xsl:if test="ns4:ProcessQuantity">
                                <ns4:ProcessQuantity>
                                  <xsl:value-of select="ns4:ProcessQuantity"/>
                                </ns4:ProcessQuantity>
                              </xsl:if>
                              <xsl:if test="ns4:PlanType">
                                <ns4:PlanType>
                                  <xsl:value-of select="ns4:PlanType"/>
                                </ns4:PlanType>
                              </xsl:if>
                              <xsl:if test="ns4:ScaleType">
                                <ns4:ScaleType>
                                  <xsl:value-of select="ns4:ScaleType"/>
                                </ns4:ScaleType>
                              </xsl:if>
                              <xsl:if test="ns4:OperationAttributeS">
                                <ns4:OperationAttributeS>
                                  <xsl:if test="ns4:OperationAttributeS/ns4:OperationAttributeCategory">
                                    <ns4:OperationAttributeCategory>
                                      <xsl:value-of select="ns4:OperationAttributeS/ns4:OperationAttributeCategory"/>
                                    </ns4:OperationAttributeCategory>
                                  </xsl:if>
                                  <xsl:if test="ns4:OperationAttributeS/ns4:OperationAttribute1">
                                    <ns4:OperationAttribute1>
                                      <xsl:value-of select="ns4:OperationAttributeS/ns4:OperationAttribute1"/>
                                    </ns4:OperationAttribute1>
                                  </xsl:if>
                                  <xsl:if test="ns4:OperationAttributeS/ns4:OperationAttribute2">
                                    <ns4:OperationAttribute2>
                                      <xsl:value-of select="ns4:OperationAttributeS/ns4:OperationAttribute2"/>
                                    </ns4:OperationAttribute2>
                                  </xsl:if>
                                  <xsl:if test="ns4:OperationAttributeS/ns4:OperationAttribute3">
                                    <ns4:OperationAttribute3>
                                      <xsl:value-of select="ns4:OperationAttributeS/ns4:OperationAttribute3"/>
                                    </ns4:OperationAttribute3>
                                  </xsl:if>
                                  <xsl:if test="ns4:OperationAttributeS/ns4:OperationAttribute4">
                                    <ns4:OperationAttribute4>
                                      <xsl:value-of select="ns4:OperationAttributeS/ns4:OperationAttribute4"/>
                                    </ns4:OperationAttribute4>
                                  </xsl:if>
                                  <xsl:if test="ns4:OperationAttributeS/ns4:OperationAttribute5">
                                    <ns4:OperationAttribute5>
                                      <xsl:value-of select="ns4:OperationAttributeS/ns4:OperationAttribute5"/>
                                    </ns4:OperationAttribute5>
                                  </xsl:if>
                                </ns4:OperationAttributeS>
                              </xsl:if>
                              <xsl:if test="ns4:ActivityAttributeS">
                                <ns4:ActivityAttributeS>
                                  <xsl:if test="ns4:ActivityAttributeS/ns4:ActivityAttributeCategory">
                                    <ns4:ActivityAttributeCategory>
                                      <xsl:value-of select="ns4:ActivityAttributeS/ns4:ActivityAttributeCategory"/>
                                    </ns4:ActivityAttributeCategory>
                                  </xsl:if>
                                  <xsl:if test="ns4:ActivityAttributeS/ns4:ActivityAttribute1">
                                    <ns4:ActivityAttribute1>
                                      <xsl:value-of select="ns4:ActivityAttributeS/ns4:ActivityAttribute1"/>
                                    </ns4:ActivityAttribute1>
                                  </xsl:if>
                                  <xsl:if test="ns4:ActivityAttributeS/ns4:ActivityAttribute2">
                                    <ns4:ActivityAttribute2>
                                      <xsl:value-of select="ns4:ActivityAttributeS/ns4:ActivityAttribute2"/>
                                    </ns4:ActivityAttribute2>
                                  </xsl:if>
                                  <xsl:if test="ns4:ActivityAttributeS/ns4:ActivityAttribute3">
                                    <ns4:ActivityAttribute3>
                                      <xsl:value-of select="ns4:ActivityAttributeS/ns4:ActivityAttribute3"/>
                                    </ns4:ActivityAttribute3>
                                  </xsl:if>
                                  <xsl:if test="ns4:ActivityAttributeS/ns4:ActivityAttribute4">
                                    <ns4:ActivityAttribute4>
                                      <xsl:value-of select="ns4:ActivityAttributeS/ns4:ActivityAttribute4"/>
                                    </ns4:ActivityAttribute4>
                                  </xsl:if>
                                  <xsl:if test="ns4:ActivityAttributeS/ns4:ActivityAttribute5">
                                    <ns4:ActivityAttribute5>
                                      <xsl:value-of select="ns4:ActivityAttributeS/ns4:ActivityAttribute5"/>
                                    </ns4:ActivityAttribute5>
                                  </xsl:if>
                                </ns4:ActivityAttributeS>
                              </xsl:if>
                              <xsl:if test="ns4:ResourceAttributeS">
                                <ns4:ResourceAttributeS>
                                  <xsl:if test="ns4:ResourceAttributeS/ns4:ResourceAttributeCategory">
                                    <ns4:ResourceAttributeCategory>
                                      <xsl:value-of select="ns4:ResourceAttributeS/ns4:ResourceAttributeCategory"/>
                                    </ns4:ResourceAttributeCategory>
                                  </xsl:if>
                                  <xsl:if test="ns4:ResourceAttributeS/ns4:ResourceAttribute1">
                                    <ns4:ResourceAttribute1>
                                      <xsl:value-of select="ns4:ResourceAttributeS/ns4:ResourceAttribute1"/>
                                    </ns4:ResourceAttribute1>
                                  </xsl:if>
                                  <xsl:if test="ns4:ResourceAttributeS/ns4:ResourceAttribute2">
                                    <ns4:ResourceAttribute2>
                                      <xsl:value-of select="ns4:ResourceAttributeS/ns4:ResourceAttribute2"/>
                                    </ns4:ResourceAttribute2>
                                  </xsl:if>
                                  <xsl:if test="ns4:ResourceAttributeS/ns4:ResourceAttribute3">
                                    <ns4:ResourceAttribute3>
                                      <xsl:value-of select="ns4:ResourceAttributeS/ns4:ResourceAttribute3"/>
                                    </ns4:ResourceAttribute3>
                                  </xsl:if>
                                  <xsl:if test="ns4:ResourceAttributeS/ns4:ResourceAttribute4">
                                    <ns4:ResourceAttribute4>
                                      <xsl:value-of select="ns4:ResourceAttributeS/ns4:ResourceAttribute4"/>
                                    </ns4:ResourceAttribute4>
                                  </xsl:if>
                                  <xsl:if test="ns4:ResourceAttributeS/ns4:ResourceAttribute5">
                                    <ns4:ResourceAttribute5>
                                      <xsl:value-of select="ns4:ResourceAttributeS/ns4:ResourceAttribute5"/>
                                    </ns4:ResourceAttribute5>
                                  </xsl:if>
                                </ns4:ResourceAttributeS>
                              </xsl:if>
                            </ns4:Operartions>
                          </xsl:for-each>
                        </ns4:ListOfOperartion>
                      </xsl:if>
                    </ns4:Routings>
                  </xsl:for-each>
                </ns4:ListOfRouting>
              </xsl:if>
              <xsl:if test="ns4:ListOfRecipe/ns4:ListOfRecipeVRS">
                <ns4:ListOfRecipeVRS>
                  <xsl:for-each select="ns4:ListOfRecipe/ns4:ListOfRecipeVRS/ns4:RecipeVRS">
                    <ns4:RecipeVRS>
                      <xsl:if test="ns4:RecipeNumber">
                        <ns4:RecipeNumber>
                          <xsl:value-of select="ns4:RecipeNumber"/>
                        </ns4:RecipeNumber>
                      </xsl:if>
                      <xsl:if test="ns4:RecipeVersion">
                        <ns4:RecipeVersion>
                          <xsl:value-of select="ns4:RecipeVersion"/>
                        </ns4:RecipeVersion>
                      </xsl:if>
                      <xsl:if test="ns4:RecipeID">
                        <ns4:RecipeID>
                          <xsl:value-of select="ns4:RecipeID"/>
                        </ns4:RecipeID>
                      </xsl:if>
                      <xsl:if test="ns4:RecipeVRID">
                        <ns4:RecipeVRID>
                          <xsl:value-of select="ns4:RecipeVRID"/>
                        </ns4:RecipeVRID>
                      </xsl:if>
                      <xsl:if test="ns4:OrganizationCode">
                        <ns4:OrganizationCode>
                          <xsl:value-of select="ns4:OrganizationCode"/>
                        </ns4:OrganizationCode>
                      </xsl:if>
                      <xsl:if test="ns4:Product">
                        <ns4:Product>
                          <xsl:value-of select="ns4:Product"/>
                        </ns4:Product>
                      </xsl:if>
                      <xsl:if test="ns4:RecipeUse">
                        <ns4:RecipeUse>
                          <xsl:value-of select="ns4:RecipeUse"/>
                        </ns4:RecipeUse>
                      </xsl:if>
                      <xsl:if test="ns4:Preference">
                        <ns4:Preference>
                          <xsl:value-of select="ns4:Preference"/>
                        </ns4:Preference>
                      </xsl:if>
                      <xsl:if test="ns4:Startdate">
                        <ns4:Startdate>
                          <xsl:value-of select="ns4:Startdate"/>
                        </ns4:Startdate>
                      </xsl:if>
                      <xsl:if test="ns4:EndDate">
                        <ns4:EndDate>
                          <xsl:value-of select="ns4:EndDate"/>
                        </ns4:EndDate>
                      </xsl:if>
                      <xsl:if test="ns4:MinimumQuantity">
                        <ns4:MinimumQuantity>
                          <xsl:value-of select="ns4:MinimumQuantity"/>
                        </ns4:MinimumQuantity>
                      </xsl:if>
                      <xsl:if test="ns4:MaximumQuantity">
                        <ns4:MaximumQuantity>
                          <xsl:value-of select="ns4:MaximumQuantity"/>
                        </ns4:MaximumQuantity>
                      </xsl:if>
                      <xsl:if test="ns4:StandardQuantity">
                        <ns4:StandardQuantity>
                          <xsl:value-of select="ns4:StandardQuantity"/>
                        </ns4:StandardQuantity>
                      </xsl:if>
                      <xsl:if test="ns4:ItemUOM">
                        <ns4:ItemUOM>
                          <xsl:value-of select="ns4:ItemUOM"/>
                        </ns4:ItemUOM>
                      </xsl:if>
                      <xsl:if test="ns4:InventoryMinimumQuantity">
                        <ns4:InventoryMinimumQuantity>
                          <xsl:value-of select="ns4:InventoryMinimumQuantity"/>
                        </ns4:InventoryMinimumQuantity>
                      </xsl:if>
                      <xsl:if test="ns4:InventoryMaximumQuantity">
                        <ns4:InventoryMaximumQuantity>
                          <xsl:value-of select="ns4:InventoryMaximumQuantity"/>
                        </ns4:InventoryMaximumQuantity>
                      </xsl:if>
                      <xsl:if test="ns4:ValidityRuleStatus">
                        <ns4:ValidityRuleStatus>
                          <xsl:value-of select="ns4:ValidityRuleStatus"/>
                        </ns4:ValidityRuleStatus>
                      </xsl:if>
                      <xsl:if test="ns4:Attribute">
                        <ns4:Attribute>
                          <xsl:if test="ns4:Attribute/ns4:AttributeCategory">
                            <ns4:AttributeCategory>
                              <xsl:value-of select="ns4:Attribute/ns4:AttributeCategory"/>
                            </ns4:AttributeCategory>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute1">
                            <ns4:Attribute1>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute1"/>
                            </ns4:Attribute1>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute2">
                            <ns4:Attribute2>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute2"/>
                            </ns4:Attribute2>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute3">
                            <ns4:Attribute3>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute3"/>
                            </ns4:Attribute3>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute4">
                            <ns4:Attribute4>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute4"/>
                            </ns4:Attribute4>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute5">
                            <ns4:Attribute5>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute5"/>
                            </ns4:Attribute5>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute6">
                            <ns4:Attribute6>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute6"/>
                            </ns4:Attribute6>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute7">
                            <ns4:Attribute7>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute7"/>
                            </ns4:Attribute7>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute8">
                            <ns4:Attribute8>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute8"/>
                            </ns4:Attribute8>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute9">
                            <ns4:Attribute9>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute9"/>
                            </ns4:Attribute9>
                          </xsl:if>
                          <xsl:if test="ns4:Attribute/ns4:Attribute10">
                            <ns4:Attribute10>
                              <xsl:value-of select="ns4:Attribute/ns4:Attribute10"/>
                            </ns4:Attribute10>
                          </xsl:if>
                        </ns4:Attribute>
                      </xsl:if>
                    </ns4:RecipeVRS>
                  </xsl:for-each>
                </ns4:ListOfRecipeVRS>
              </xsl:if>
            </ns4:ListOfRecipe>
          </xsl:if>
        </ns4:ProductStructureDetails>
      </xsl:for-each>
    </ns0:QueryProductStructureAddRs>
  </xsl:template>
</xsl:stylesheet>
