import { OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Router } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { DJJAPIService } from '../../services/DJJAPI.service';
import { ConfirmationService } from 'primeng/primeng';
import { ItemMapping } from './item-mapping';
export declare class ItemMappingsComponent implements OnInit {
    private _router;
    private _service;
    private _confirmService;
    selectedAPI: string;
    form: FormGroup;
    displayDialog: boolean;
    itemMapping: ItemMapping;
    newItemMapping: boolean;
    selectedItemMapping: ItemMapping;
    itemMappings: ItemMapping[];
    AddressBookNums: SelectItem[];
    loading: any;
    constructor(fb: FormBuilder, _router: Router, _service: DJJAPIService, _confirmService: ConfirmationService);
    ngOnInit(): void;
    refreshPage(): void;
    showDialogToAdd(): void;
    save(value: string): void;
    delete(): void;
    cancel(): void;
    onRowSelect(event: any): void;
    cloneItemMapping(i: ItemMapping): ItemMapping;
    findSelectedItemMappingIndex(): number;
    routerCanDeactivate(): boolean;
}
