<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/JDAPlanInvAssignmentsTransition/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_ExtractJDA_TRN_INV"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_ExtractJDA_TRN_INV"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WritePlanInvAssignmentsTransitionFile">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_ExtractJDA_TRN_INV.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaTrnInvStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_ExtractJDA_TRN_INV"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_WritePlanInvAssignmentsTransitionFile.wsdl"/>
        <oracle-xsl-mapper:rootElement name="JDAPlanInvAssignmentsList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/JDAPlanInvAssignmentsTransition/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAY 26 10:23:57 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:JDAPlanInvAssignmentsList>
      <tns:PlanInvAssignmentsHeader>
        <tns:assigned_part/>
       
<tns:assigned_quantity/>
<tns:assigned_quantity_format/>
<tns:assigned_quantity_uom/>
<tns:demand_or_mfg_order_id/>
<tns:demand_pst/>
<tns:demand_shipment_code/>
<tns:formatted_assigned_quantity/>
<tns:formatted_pre_potency_assigned_quantity/>
<tns:operation_id/>
<tns:part_number_type/>
<tns:part_source/>
<tns:pre_potency_assigned_quantity/>
<tns:purchase_order_id/>
<tns:reservation_locked/>
<tns:step_number/>
<tns:supply_boh/>
<tns:supply_time_needed/>
<tns:time_available/>
<tns:time_available_format/>
<tns:time_needed/>
<tns:time_needed_format/>
<tns:time_previously_reserved/>
<tns:vendor_p/>
      </tns:PlanInvAssignmentsHeader>
      <xsl:for-each select="/ns0:XxnucGmeJdaTrnInvStgCollection/ns0:XxnucGmeJdaTrnInvStg">
        <tns:JDAPlanInvAssignments>
          <tns:assigned_part>
            <xsl:value-of select="ns0:assignedPart"/>
          </tns:assigned_part>
          <tns:assigned_quantity>
            <xsl:value-of select="ns0:assignedQuantity"/>
          </tns:assigned_quantity>
          <tns:assigned_quantity_format>
            <xsl:value-of select="ns0:assignedQuantityFormat"/>
          </tns:assigned_quantity_format>
          <tns:assigned_quantity_uom>
            <xsl:value-of select="ns0:assignedQuantityUom"/>
          </tns:assigned_quantity_uom>
          <tns:demand_or_mfg_order_id>
            <xsl:value-of select="ns0:demandOrMfgOrderId"/>
          </tns:demand_or_mfg_order_id>
          <tns:demand_pst>
            <xsl:value-of select="ns0:demandPst"/>
          </tns:demand_pst>
          <tns:demand_shipment_code>
            <xsl:value-of select="ns0:demandShipmentCode"/>
          </tns:demand_shipment_code>
          <tns:formatted_assigned_quantity>
            <xsl:value-of select="ns0:formattedAssignedQuantity"/>
          </tns:formatted_assigned_quantity>
          <tns:formatted_pre_potency_assigned_quantity>
            <xsl:value-of select="ns0:formattedPrePotencyAssign"/>
          </tns:formatted_pre_potency_assigned_quantity>
          <tns:operation_id>
            <xsl:value-of select="ns0:operationId"/>
          </tns:operation_id>
          <tns:part_number_type>
            <xsl:value-of select="ns0:partNumberType"/>
          </tns:part_number_type>
          <tns:part_source>
            <xsl:value-of select="ns0:partSource"/>
          </tns:part_source>
          <tns:pre_potency_assigned_quantity>
            <xsl:value-of select="ns0:prePotencyAssignedQty"/>
          </tns:pre_potency_assigned_quantity>
          <tns:purchase_order_id>
            <xsl:value-of select="ns0:purchaseOrderId"/>
          </tns:purchase_order_id>
          <tns:reservation_locked>
            <xsl:value-of select="ns0:reservationLocked"/>
          </tns:reservation_locked>
          <tns:step_number>
            <xsl:value-of select="ns0:stepNumber"/>
          </tns:step_number>
          <tns:supply_boh>
            <xsl:value-of select="ns0:supplyBoh"/>
          </tns:supply_boh>
          <tns:supply_time_needed>
            <xsl:value-of select="ns0:supplyTimeNeeded"/>
          </tns:supply_time_needed>
          <tns:time_available>
            <xsl:value-of select="ns0:timeAvailable"/>
          </tns:time_available>
          <tns:time_available_format>
            <xsl:value-of select="ns0:timeAvailableFormat"/>
          </tns:time_available_format>
          <tns:time_needed>
            <xsl:value-of select="ns0:timeNeeded"/>
          </tns:time_needed>
          <tns:time_needed_format>
            <xsl:value-of select="ns0:timeNeededFormat"/>
          </tns:time_needed_format>
          <tns:time_previously_reserved>
            <xsl:value-of select="ns0:timePreviouslyReserved"/>
          </tns:time_previously_reserved>
          <tns:vendor_p>
            <xsl:value-of select="ns0:vendorP"/>
          </tns:vendor_p>
        </tns:JDAPlanInvAssignments>
      </xsl:for-each>
    </tns:JDAPlanInvAssignmentsList>
  </xsl:template>
</xsl:stylesheet>
