<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/Routing/1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_Extract_EBIZ_Batch_Details"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:FILEAPP="http://xmlns.oracle.com/pcbpel/adapter/file/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WriteRoutingRecord">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Extract_EBIZ_Batch_Details.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaBatchExtVCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_WriteRoutingRecord.wsdl"/>
        <oracle-xsl-mapper:rootElement name="RoutingList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/Routing/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 02 15:36:45 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:RoutingList>
      <tns:RoutingHeader>
        <tns:base_machine_resource/>
        <tns:base_yield/>
        <tns:display_quantity_uom/>
        <tns:early_setup/>
        <tns:interruptible/>
        <tns:min_operation_time/>
        <tns:min_operation_time_uom/>
        <tns:operation/>
        <tns:preop_time/>
        <tns:preop_time_uom/>
        <tns:routing/>
        <tns:run_rate/>
        <tns:run_rate_per/>
        <tns:run_rate_uom/>
        <tns:same_demand_same_setup_run/>
        <tns:sequence_dependent_setup_type/>
        <tns:sequence_dependent_setup_type2/>
        <tns:sequence_dependent_setup_type3/>
        <tns:step_number/>
        <tns:unit_runtime/>
        <tns:unit_runtime_uom/>
      </tns:RoutingHeader>
      <xsl:for-each-group select="/ns0:XxnucGmeJdaBatchExtVCollection/ns0:XxnucGmeJdaBatchExtV/ns0:xxnucGmeJdaRoutingsExtVCollection/ns0:XxnucGmeJdaRoutingsExtV"
                          group-by="ns0:routing">
        <xsl:for-each-group select="current-group()" group-by="ns0:operation">
          <tns:Routing>
            <tns:base_machine_resource>
              <xsl:value-of select="ns0:baseMachineResource"/>
            </tns:base_machine_resource>
            <tns:base_yield>
              <xsl:value-of select="ns0:baseYield"/>
            </tns:base_yield>
            <tns:display_quantity_uom>
              <xsl:value-of select="ns0:displayQuantityUom"/>
            </tns:display_quantity_uom>
            <tns:early_setup>
              <xsl:value-of select="ns0:earlySetup"/>
            </tns:early_setup>
            <tns:interruptible>
              <xsl:value-of select="ns0:interruptible"/>
            </tns:interruptible>
            <tns:min_operation_time>
              <xsl:value-of select="ns0:minOperationTime"/>
            </tns:min_operation_time>
            <tns:min_operation_time_uom>
              <xsl:value-of select="ns0:minOperationTimeUom"/>
            </tns:min_operation_time_uom>
            <tns:operation>
              <xsl:value-of select="ns0:operation"/>
            </tns:operation>
            <tns:preop_time>
              <xsl:value-of select="ns0:preopTime"/>
            </tns:preop_time>
            <tns:preop_time_uom>
              <xsl:value-of select="ns0:preopTimeUom"/>
            </tns:preop_time_uom>
            <tns:routing>
              <xsl:value-of select="ns0:routing"/>
            </tns:routing>
            <tns:run_rate>
              <xsl:value-of select="ns0:runRate"/>
            </tns:run_rate>
            <tns:run_rate_per>
              <xsl:value-of select="ns0:runRatePer"/>
            </tns:run_rate_per>
            <tns:run_rate_uom>
              <xsl:value-of select="ns0:runRateUom"/>
            </tns:run_rate_uom>
            <tns:same_demand_same_setup_run>
              <xsl:value-of select="ns0:sameDemandSameSetupRun"/>
            </tns:same_demand_same_setup_run>
            <tns:sequence_dependent_setup_type>
              <xsl:value-of select="ns0:sequenceDependentSetupType"/>
            </tns:sequence_dependent_setup_type>
            <tns:sequence_dependent_setup_type2>
              <xsl:value-of select="ns0:sequenceDependentSetupType2"/>
            </tns:sequence_dependent_setup_type2>
            <tns:sequence_dependent_setup_type3>
              <xsl:value-of select="ns0:sequenceDependentSetupType3"/>
            </tns:sequence_dependent_setup_type3>
            <tns:step_number>
              <xsl:value-of select="ns0:stepNumber"/>
            </tns:step_number>
            <tns:unit_runtime>
              <xsl:value-of select="ns0:unitRuntime"/>
            </tns:unit_runtime>
            <tns:unit_runtime_uom>
              <xsl:value-of select="ns0:unitRuntimeUom"/>
            </tns:unit_runtime_uom>
          </tns:Routing>
        </xsl:for-each-group>
      </xsl:for-each-group>
    </tns:RoutingList>
  </xsl:template>
</xsl:stylesheet>
