<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/MOP/1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_Extract_EBIZ_Batch_Details"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WriteMfgOrderPeggingRecord"
                xmlns:FILEAPP="http://xmlns.oracle.com/pcbpel/adapter/file/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Extract_EBIZ_Batch_Details.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaBatchExtVCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_WriteMfgOrderPeggingRecord.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MOPList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/MOP/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 02 16:38:25 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:MOPList>
      <tns:MOPHeader>
        <tns:operation/>
        <tns:step_number/>
        <tns:stock_order/>
        <tns:consumed_order/>
        <tns:consumed_part/>
        <tns:demand_order_p/>
        <tns:actual_quantity_fed/>
        <tns:demands_locked_p/>
        <tns:produced_order/>
        <tns:quantity_fed/>
        <tns:surplus/>
      </tns:MOPHeader>
      <xsl:for-each-group select="/ns0:XxnucGmeJdaBatchExtVCollection/ns0:XxnucGmeJdaBatchExtV/ns0:xxnucGmeJdaMopExtVCollection/ns0:XxnucGmeJdaMopExtV"
                          group-by="ns0:consumedOrder">
        <xsl:for-each-group select="current-group()" group-by="ns0:producedOrder">
        <tns:MOP>
          <tns:operation>
            <xsl:value-of select="ns0:operation"/>
          </tns:operation>
          <tns:step_number>
            <xsl:value-of select="ns0:consumedOrder"/>
          </tns:step_number>
          <tns:stock_order>
            <xsl:value-of select="ns0:stockOrder"/>
          </tns:stock_order>
          <tns:consumed_order>
            <xsl:value-of select="ns0:consumedOrder"/>
          </tns:consumed_order>
          <tns:consumed_part>
            <xsl:value-of select="ns0:consumedPart"/>
          </tns:consumed_part>
          <tns:demand_order_p>
            <xsl:value-of select="ns0:demandOrderP"/>
          </tns:demand_order_p>
          <tns:actual_quantity_fed>
            <xsl:value-of select="ns0:actualQuantityFed"/>
          </tns:actual_quantity_fed>
          <tns:demands_locked_p>
            <xsl:value-of select="ns0:demandsLockedP"/>
          </tns:demands_locked_p>
          <tns:produced_order>
            <xsl:value-of select="ns0:producedOrder"/>
          </tns:produced_order>
          <tns:quantity_fed>
            <xsl:value-of select="ns0:quantityFed"/>
          </tns:quantity_fed>
          <tns:surplus>
            <xsl:value-of select="ns0:surplus"/>
          </tns:surplus>
        </tns:MOP>
      </xsl:for-each-group>
       </xsl:for-each-group>
    </tns:MOPList>
  </xsl:template>
</xsl:stylesheet>
