<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/WIP/1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_Extract_EBIZ_Batch_Details"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:FILEAPP="http://xmlns.oracle.com/pcbpel/adapter/file/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/file/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WriteWIPRecord"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WriteWIPRecord">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Extract_EBIZ_Batch_Details.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaBatchExtVCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_WriteWIPRecord.wsdl"/>
        <oracle-xsl-mapper:rootElement name="WIPRecordList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/WIP/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 02 16:59:14 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:WIPRecordList>
      <tns:WIPHeader>
        <tns:completion_time/>
        <tns:completion_time_format/>
        <tns:elapsed_runtime/>
        <tns:elapsed_runtime_uom/>
        <tns:finished_quantity/>
        <tns:finished_quantity_uom/>
        <tns:finished_part_number/>
        <tns:manufacturing_order/>
        <tns:operation/>
        <tns:operation_complete/>
        <tns:routing/>
        <tns:set_task_to_epst_p/>
        <tns:start_time/>
        <tns:start_time_format/>
        <tns:step_number/>
        <tns:unfinished_quantity/>
        <tns:unfinished_quantity_uom/>
        <tns:unfinished_part_number/>
      </tns:WIPHeader>
      <xsl:for-each select="/ns0:XxnucGmeJdaBatchExtVCollection/ns0:XxnucGmeJdaBatchExtV/ns0:xxnucGmeJdaWipDataExtVCollection/ns0:XxnucGmeJdaWipDataExtV">
        <tns:WIPRecord>
          <tns:completion_time>
            <xsl:value-of select="ns0:completionTime"/>
          </tns:completion_time>
          <tns:completion_time_format>
            <xsl:value-of select="ns0:completionTimeFormat"/>
          </tns:completion_time_format>
          <tns:elapsed_runtime>
            <xsl:value-of select="ns0:elapsedRuntime"/>
          </tns:elapsed_runtime>
          <tns:elapsed_runtime_uom>
            <xsl:value-of select="ns0:elapsedRuntimeUom"/>
          </tns:elapsed_runtime_uom>
          <tns:finished_quantity>
            <xsl:value-of select="ns0:finishedQuantity"/>
          </tns:finished_quantity>
          <tns:finished_quantity_uom>
            <xsl:value-of select="ns0:finishedQuantityUom"/>
          </tns:finished_quantity_uom>
          <tns:finished_part_number>
            <xsl:value-of select="ns0:finishedPartNumber"/>
          </tns:finished_part_number>
          <tns:manufacturing_order>
            <xsl:value-of select="ns0:manufacturingOrder"/>
          </tns:manufacturing_order>
          <tns:operation>
            <xsl:value-of select="ns0:operation"/>
          </tns:operation>
          <tns:operation_complete>
            <xsl:value-of select="ns0:operationComplete"/>
          </tns:operation_complete>
          <tns:routing>
            <xsl:value-of select="ns0:routing"/>
          </tns:routing>
          <tns:set_task_to_epst_p>
            <xsl:value-of select="ns0:setTaskToEpstP"/>
          </tns:set_task_to_epst_p>
          <tns:start_time>
            <xsl:value-of select="ns0:startTime"/>
          </tns:start_time>
          <tns:start_time_format>
            <xsl:value-of select="ns0:startTimeFormat"/>
          </tns:start_time_format>
          <tns:step_number>
            <xsl:value-of select="ns0:stepNumber"/>
          </tns:step_number>
          <tns:unfinished_quantity>
            <xsl:value-of select="ns0:unfinishedQuantity"/>
          </tns:unfinished_quantity>
          <tns:unfinished_quantity_uom>
            <xsl:value-of select="ns0:unfinishedQuantityUom"/>
          </tns:unfinished_quantity_uom>
          <tns:unfinished_part_number>
            <xsl:value-of select="ns0:unfinishedPartNumber"/>
          </tns:unfinished_part_number>
        </tns:WIPRecord>
      </xsl:for-each>
    </tns:WIPRecordList>
  </xsl:template>
</xsl:stylesheet>
