<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/OnHandInventory/1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_Extract_EBIZ_Batch_Details"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/file/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WriteUnassignedInvRecord"
                xmlns:FILEAPP="http://xmlns.oracle.com/pcbpel/adapter/file/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WriteUnassignedInvRecord">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Extract_EBIZ_Batch_Details.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaBatchExtVCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_WriteUnassignedInvRecord.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OnHandItemList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/OnHandInventory/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 02 16:43:33 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:OnHandItemList>
      <tns:OnHandItemHeader>
        <tns:part_quantity/>
        <tns:part_quantity_uom/>
        <tns:part_number/>
        <tns:priority/>
        <tns:purchase_order_number/>
        <tns:vendor/>
        <tns:arrival_time/>
        <tns:arrival_time_format/>
        <tns:expiration_time/>
      </tns:OnHandItemHeader>
      <xsl:for-each-group select="/ns0:XxnucGmeJdaBatchExtVCollection/ns0:XxnucGmeJdaBatchExtV/ns0:xxnucGmeJdaOnhandExtVCollection/ns0:XxnucGmeJdaOnhandExtV"
                          group-by="ns0:partNumber">
        <tns:OnHandItem>
          <tns:part_quantity>9999999999</tns:part_quantity>
          <tns:part_quantity_uom>
            <xsl:value-of select="ns0:partQuantityUom"/>
          </tns:part_quantity_uom>
          <tns:part_number>
            <xsl:value-of select="ns0:partNumber"/>
          </tns:part_number>
          <tns:priority>
            <xsl:value-of select="ns0:priority"/>
          </tns:priority>
          <tns:purchase_order_number>
            <xsl:value-of select="ns0:purchaseOrderNumber"/>
          </tns:purchase_order_number>
          <tns:vendor>
            <xsl:value-of select="ns0:vendor"/>
          </tns:vendor>
          <tns:arrival_time/>
          <tns:arrival_time_format/>
          <tns:expiration_time/>
        </tns:OnHandItem>
      </xsl:for-each-group>
    </tns:OnHandItemList>
  </xsl:template>
</xsl:stylesheet>
