<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_ExtractJDA_TRN_Plan"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/JDAPlanTransition/1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_ExtractJDA_TRN_Plan"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WriteJDAPlanTransitionFile">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_ExtractJDA_TRN_Plan.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaTrnPlanStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_ExtractJDA_TRN_Plan"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_WriteJDAPlanTransitionFile.wsdl"/>
        <oracle-xsl-mapper:rootElement name="PlanList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/JDAPlanTransition/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAY 26 08:43:18 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:PlanList>
      <tns:PlanHeader>
<tns:bal_cooldown_time />
<tns:bal_cooldown_time_uom />
<tns:bal_queue_time />
<tns:bal_queue_time_uom />
<tns:bal_transport_time />
<tns:bal_transport_time_uom />
<tns:cao_priority />
<tns:cao_priority_format />
<tns:category />
<tns:cest />
<tns:cest_format />
<tns:clst />
<tns:clst_format />
<tns:demand_order_id />
<tns:epst />
<tns:epst_format />
<tns:formatted_planned_input_qty />
<tns:formatted_planned_output_qty />
<tns:formatted_planned_runtime />
<tns:formatted_stretched_runtime />
<tns:lock_count />
<tns:lpst />
<tns:lpst_format />
<tns:mfg_order_id />
<tns:num_operators />
<tns:operation_id />
<tns:operators />
<tns:planned_end_time />
<tns:planned_end_time_format />
<tns:planned_end_time_sec />
<tns:planned_input_qty />
<tns:planned_input_qty_uom />
<tns:planned_output_qty />
<tns:planned_output_qty_uom />
<tns:planned_runtime />
<tns:planned_runtime_format />
<tns:planned_runtime_uom />
<tns:planned_start_time />
<tns:planned_start_time_format />
<tns:planned_start_time_sec />
<tns:planned_transit_ready_time />
<tns:planned_transit_ready_time_format />
<tns:primary_output_part />
<tns:primary_resource />
<tns:priority />
<tns:qty_format />
<tns:remaining_pulls />
<tns:remaining_pushes />
<tns:schedule_task_priority />
<tns:step_number />
<tns:stretched_runtime />
<tns:stretched_runtime_format />
<tns:task_priority/>
      </tns:PlanHeader>
      <xsl:for-each select="/ns0:XxnucGmeJdaTrnPlanStgCollection/ns0:XxnucGmeJdaTrnPlanStg">
        <tns:Plan>
          <tns:bal_cooldown_time>
            <xsl:value-of select="ns0:balCooldownTime"/>
          </tns:bal_cooldown_time>
          <tns:bal_cooldown_time_uom>
            <xsl:value-of select="ns0:balCooldownTimeUom"/>
          </tns:bal_cooldown_time_uom>
          <tns:bal_queue_time>
            <xsl:value-of select="ns0:balQueueTime"/>
          </tns:bal_queue_time>
          <tns:bal_queue_time_uom>
            <xsl:value-of select="ns0:balQueueTimeUom"/>
          </tns:bal_queue_time_uom>
          <tns:bal_transport_time>
            <xsl:value-of select="ns0:balTransportTime"/>
          </tns:bal_transport_time>
          <tns:bal_transport_time_uom>
            <xsl:value-of select="ns0:balTransportTimeUom"/>
          </tns:bal_transport_time_uom>
          <tns:cao_priority>
            <xsl:value-of select="ns0:caoPriority"/>
          </tns:cao_priority>
          <tns:cao_priority_format>
            <xsl:value-of select="ns0:caoPriorityFormat"/>
          </tns:cao_priority_format>
          <tns:category>
            <xsl:value-of select="ns0:category"/>
          </tns:category>
          <tns:cest>
            <xsl:value-of select="ns0:cest"/>
          </tns:cest>
          <tns:cest_format>
            <xsl:value-of select="ns0:cestFormat"/>
          </tns:cest_format>
          <tns:clst>
            <xsl:value-of select="ns0:clst"/>
          </tns:clst>
          <tns:clst_format>
            <xsl:value-of select="ns0:clstFormat"/>
          </tns:clst_format>
          <tns:demand_order_id>
            <xsl:value-of select="ns0:demandOrderId"/>
          </tns:demand_order_id>
          <tns:epst>
            <xsl:value-of select="ns0:epst"/>
          </tns:epst>
          <tns:epst_format>
            <xsl:value-of select="ns0:epstFormat"/>
          </tns:epst_format>
          <tns:formatted_planned_input_qty>
            <xsl:value-of select="ns0:formattedPlannedInputQty"/>
          </tns:formatted_planned_input_qty>
          <tns:formatted_planned_output_qty>
            <xsl:value-of select="ns0:formattedPlannedOutputQty"/>
          </tns:formatted_planned_output_qty>
          <tns:formatted_planned_runtime>
            <xsl:value-of select="ns0:formattedPlannedRuntime"/>
          </tns:formatted_planned_runtime>
          <tns:formatted_stretched_runtime>
            <xsl:value-of select="ns0:formattedStretchedRuntime"/>
          </tns:formatted_stretched_runtime>
          <tns:lock_count>
            <xsl:value-of select="ns0:lockCount"/>
          </tns:lock_count>
          <tns:lpst>
            <xsl:value-of select="ns0:lpst"/>
          </tns:lpst>
          <tns:lpst_format>
            <xsl:value-of select="ns0:lpstFormat"/>
          </tns:lpst_format>
          <tns:mfg_order_id>
            <xsl:value-of select="ns0:mfgOrderId"/>
          </tns:mfg_order_id>
          <tns:num_operators>
            <xsl:value-of select="ns0:numOperators"/>
          </tns:num_operators>
          <tns:operation_id>
            <xsl:value-of select="ns0:operationId"/>
          </tns:operation_id>
          <tns:operators>
            <xsl:value-of select="ns0:operators"/>
          </tns:operators>
          <tns:planned_end_time>
            <xsl:value-of select="ns0:plannedEndTime"/>
          </tns:planned_end_time>
          <tns:planned_end_time_format>
            <xsl:value-of select="ns0:plannedEndTimeFormat"/>
          </tns:planned_end_time_format>
          <tns:planned_end_time_sec>
            <xsl:value-of select="ns0:plannedEndTimeSec"/>
          </tns:planned_end_time_sec>
          <tns:planned_input_qty>
            <xsl:value-of select="ns0:plannedInputQty"/>
          </tns:planned_input_qty>
          <tns:planned_input_qty_uom>
            <xsl:value-of select="ns0:plannedInputQtyUom"/>
          </tns:planned_input_qty_uom>
          <tns:planned_output_qty>
            <xsl:value-of select="ns0:plannedOutputQty"/>
          </tns:planned_output_qty>
          <tns:planned_output_qty_uom>
            <xsl:value-of select="ns0:plannedOutputQtyUom"/>
          </tns:planned_output_qty_uom>
          <tns:planned_runtime>
            <xsl:value-of select="ns0:plannedRuntime"/>
          </tns:planned_runtime>
          <tns:planned_runtime_format>
            <xsl:value-of select="ns0:plannedRuntimeFormat"/>
          </tns:planned_runtime_format>
          <tns:planned_runtime_uom>
            <xsl:value-of select="ns0:plannedRuntimeUom"/>
          </tns:planned_runtime_uom>
          <tns:planned_start_time>
            <xsl:value-of select="ns0:plannedStartTime"/>
          </tns:planned_start_time>
          <tns:planned_start_time_format>
            <xsl:value-of select="ns0:plannedStartTimeFormat"/>
          </tns:planned_start_time_format>
          <tns:planned_start_time_sec>
            <xsl:value-of select="ns0:plannedStartTimeSec"/>
          </tns:planned_start_time_sec>
          <tns:planned_transit_ready_time>
            <xsl:value-of select="ns0:plannedTransitReadyTime"/>
          </tns:planned_transit_ready_time>
          <tns:planned_transit_ready_time_format>
            <xsl:value-of select="ns0:plannedTransitReadyTimeF"/>
          </tns:planned_transit_ready_time_format>
          <tns:primary_output_part>
            <xsl:value-of select="ns0:primaryOutputPart"/>
          </tns:primary_output_part>
          <tns:primary_resource>
            <xsl:value-of select="ns0:primaryResource"/>
          </tns:primary_resource>
          <tns:priority>
            <xsl:value-of select="ns0:priority"/>
          </tns:priority>
          <tns:qty_format>
            <xsl:value-of select="ns0:qtyFormat"/>
          </tns:qty_format>
          <tns:remaining_pulls>
            <xsl:value-of select="ns0:remainingPulls"/>
          </tns:remaining_pulls>
          <tns:remaining_pushes>
            <xsl:value-of select="ns0:remainingPushes"/>
          </tns:remaining_pushes>
          <tns:schedule_task_priority>
            <xsl:value-of select="ns0:scheduleTaskPriority"/>
          </tns:schedule_task_priority>
          <tns:step_number>
            <xsl:value-of select="ns0:stepNumber"/>
          </tns:step_number>
          <tns:stretched_runtime>
            <xsl:value-of select="ns0:stretchedRuntime"/>
          </tns:stretched_runtime>
          <tns:stretched_runtime_format>
            <xsl:value-of select="ns0:stretchedRuntimeFormat"/>
          </tns:stretched_runtime_format>
          <tns:task_priority>
            <xsl:value-of select="ns0:taskPriority"/>
          </tns:task_priority>
        </tns:Plan>
      </xsl:for-each>
    </tns:PlanList>
  </xsl:template>
</xsl:stylesheet>
