<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/Item/1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_Extract_EBIZ_Batch_Details"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/file/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WritePartNumberData"
                xmlns:FILEAPP="http://xmlns.oracle.com/pcbpel/adapter/file/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WritePartNumberData"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Extract_EBIZ_Batch_Details.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaBatchExtVCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_WritePartNumberData.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ItemList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/Item/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 09 10:59:10 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ItemList>
      <tns:ItemHeader>
        <tns:create_auto_ato/>
        <tns:customer_name/>
        <tns:demand_part_number/>
        <tns:description/>
        <tns:part_buffer_style/>
        <tns:part_number/>
        <tns:part_number_type/>
        <tns:plan_time_interval/>
        <tns:plan_time_interval_uom/>
        <tns:product_family/>
        <tns:sellable/>
        <tns:stock_part/>
        <tns:shape/>
        <tns:grade/>
        <tns:size/>
        <tns:thickness/>
        <tns:width/>
        <tns:L1/>
        <tns:L2/>
        <tns:sizeX/>
        <tns:sizeY/>
        <tns:sizeZ/>
        <tns:radius/>
        <tns:size_pos_tol/>
        <tns:size_neg_tol/>
        <tns:thickness_pos_tol/>
        <tns:thickness_neg_tol/>
        <tns:width_pos_tol/>
        <tns:width_neg_tol/>
        <tns:weight_per_foot/>
        <tns:length/>
        <tns:length_pos_tol/>
        <tns:length_neg_tol/>
        <tns:thread_dir/>
        <tns:coil_weight/>
        <tns:gauge/>
        <tns:class/>
        <tns:min_bundle_weight/>
        <tns:max_bundle_weight/>
        <tns:piece_count/>
        <tns:chamfer_ends/>
        <tns:chamfer_amount/>
        <tns:chamfer_angle/>
        <tns:coating/>
        <tns:base_coat/>
        <tns:tip_coat/>
        <tns:product_type/>
      </tns:ItemHeader>
      <xsl:for-each-group select="/ns0:XxnucGmeJdaBatchExtVCollection/ns0:XxnucGmeJdaBatchExtV/ns0:xxnucGmeJdaPartExtVCollection/ns0:XxnucGmeJdaPartExtV"
                          group-by="ns0:demandPartNumber">
        <xsl:variable name="attrXMLData" select="oraext:parseXML(ns0:attrXml)"/>
        <tns:Item>
          <tns:create_auto_ato>
            <xsl:value-of select="ns0:createAutoAto"/>
          </tns:create_auto_ato>
          <tns:customer_name>
            <xsl:value-of select="ns0:customerName"/>
          </tns:customer_name>
          <tns:demand_part_number>
            <xsl:value-of select="ns0:demandPartNumber"/>
          </tns:demand_part_number>
          <tns:description>
            <xsl:value-of select="ns0:description"/>
          </tns:description>
          <tns:part_buffer_style>
            <xsl:value-of select="ns0:partBufferStyle"/>
          </tns:part_buffer_style>
          <tns:part_number>
            <xsl:value-of select="ns0:partNumber"/>
          </tns:part_number>
          <tns:part_number_type>
            <xsl:value-of select="ns0:partNumberType"/>
          </tns:part_number_type>
          <tns:plan_time_interval>
            <xsl:value-of select="ns0:planTimeInterval"/>
          </tns:plan_time_interval>
          <tns:plan_time_interval_uom>
            <xsl:value-of select="ns0:planTimeIntervalUom"/>
          </tns:plan_time_interval_uom>
          <tns:product_family>
            <xsl:call-template name="string-replace-all">
              <xsl:with-param name="text" select="ns0:productFamily"/>
              <xsl:with-param name="replace" select='";"'/>
              <xsl:with-param name="by" select='","'/>
            </xsl:call-template>
          </tns:product_family>
          <tns:sellable>
            <xsl:value-of select="ns0:sellable"/>
          </tns:sellable>
          <tns:stock_part>
            <xsl:value-of select="ns0:stockPart"/>
          </tns:stock_part>
          <tns:shape>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='SHAPE']/ATTR_DISP_VALUE"/>
          </tns:shape>
          <tns:grade>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='GRADE']/ATTR_DISP_VALUE"/>
          </tns:grade>
          <tns:size>
            <xsl:value-of select="ns0:dimension"/>
          </tns:size>
          <tns:thickness>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE1']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:thickness>
          <tns:width>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE2']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:width>
          <tns:L1>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE_ANGLE1']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:L1>
          <tns:L2>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE_ANGLE2']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:L2>
          <tns:sizeX>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE_X']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:sizeX>
          <tns:sizeY>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE_Y']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:sizeY>
          <tns:sizeZ>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE_Z']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:sizeZ>
          <tns:radius>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='RADIUS']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:radius>
          <tns:size_pos_tol>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE_POS']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:size_pos_tol>
          <tns:size_neg_tol>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE_NEG']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:size_neg_tol>
          <tns:thickness_pos_tol>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE2_TPOS']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:thickness_pos_tol>
          <tns:thickness_neg_tol>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE1_TNEG']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:thickness_neg_tol>
          <tns:width_pos_tol>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE4_WPOS']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:width_pos_tol>
          <tns:width_neg_tol>
            <xsl:value-of select="translate ($attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE3_WNEG']/ATTR_DISP_VALUE, '&quot;', '' )"/>
          </tns:width_neg_tol>
          <tns:weight_per_foot>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_SIZE_WPF']/ATTR_DISP_VALUE"/>
          </tns:weight_per_foot>
          <tns:length>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='LENGTH']/ATTR_DISP_VALUE"/>
          </tns:length>
          <tns:length_pos_tol>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='LENGTH_POS']/ATTR_DISP_VALUE"/>
          </tns:length_pos_tol>
          <tns:length_neg_tol>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='LENGTH_NEG']/ATTR_DISP_VALUE"/>
          </tns:length_neg_tol>
          <tns:thread_dir>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='NUC_THREAD_DIR']/ATTR_DISP_VALUE"/>
          </tns:thread_dir>
          <tns:coil_weight>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='WEIGHT']/ATTR_DISP_VALUE"/>
          </tns:coil_weight>
          <tns:gauge>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='WEIGHT']/ATTR_DISP_VALUE"/>
          </tns:gauge>
          <tns:class>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='CLASS']/ATTR_DISP_VALUE"/>
          </tns:class>
          <tns:min_bundle_weight>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='BNDL_WEIGHT_MIN']/ATTR_DISP_VALUE"/>
          </tns:min_bundle_weight>
          <tns:max_bundle_weight>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='BNDL_WEIGHT_MAX']/ATTR_DISP_VALUE"/>
          </tns:max_bundle_weight>
          <tns:piece_count>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='PIECE_COUNT']/ATTR_DISP_VALUE"/>
          </tns:piece_count>
          <tns:chamfer_ends>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='CHMF_END']/ATTR_DISP_VALUE"/>
          </tns:chamfer_ends>
          <tns:chamfer_amount>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='CHMF_AMT']/ATTR_DISP_VALUE"/>
          </tns:chamfer_amount>
          <tns:chamfer_angle>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='CHMF_ANGLE']/ATTR_DISP_VALUE"/>
          </tns:chamfer_angle>
          <tns:coating>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='COAT']/ATTR_DISP_VALUE"/>
          </tns:coating>
          <tns:base_coat>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='BASE_COAT']/ATTR_DISP_VALUE"/>
          </tns:base_coat>
          <tns:tip_coat>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='TIP_COAT']/ATTR_DISP_VALUE"/>
          </tns:tip_coat>
          <tns:product_type>
            <xsl:value-of select="$attrXMLData/XXNUC_EGO_ITEM_UDA_OBJ_TYPE/ATTRIBUTE_DATA_LIST/EGO_USER_ATTR_DATA_OBJ[ATTR_NAME='PRODTYPE']/ATTR_DISP_VALUE"/>
          </tns:product_type>
        </tns:Item>
      </xsl:for-each-group>
    </tns:ItemList>
  </xsl:template>
  <xsl:template name="string-replace-all">
    <xsl:param name="text"/>
    <xsl:param name="replace"/>
    <xsl:param name="by"/>
    <xsl:choose>
      <xsl:when test="contains($text, $replace)">
        <xsl:value-of select="substring-before($text,$replace)"/>
        <xsl:value-of select="$by"/>
        <xsl:call-template name="string-replace-all">
          <xsl:with-param name="text" select="substring-after($text,$replace)"/>
          <xsl:with-param name="replace" select="$replace"/>
          <xsl:with-param name="by" select="$by"/>
        </xsl:call-template>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$text"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
