<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/JDAPRodScheduleTransition/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_ExtractJDA_TRN_Schedule"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_ExtractJDA_TRN_Schedule"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/FTP_WriteJDAPRodScheduleTransitionFile"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_ExtractJDA_TRN_Schedule.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaTrnScheduleStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_ExtractJDA_TRN_Schedule"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_WriteJDAPRodScheduleTransitionFile.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ProdScheduleList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/JDAPRodScheduleTransition/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAY 26 11:14:21 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ProdScheduleList>
      <tns:ProdScheduleHeader>
        <tns:formatted_mfg_order_output_qty/>
        <tns:formatted_planned_input_qty/>
        <tns:formatted_planned_output_qty/>
        <tns:keep_user_scheduled_start/>
        <tns:mfg_order_id/>
        <tns:mfg_order_output_qty/>
        <tns:mfg_order_output_qty_format/>
        <tns:mfg_order_output_qty_uom/>
        <tns:operation_id/>
        <tns:original_scheduled_start_time/>
        <tns:original_scheduled_start_time_format/>
        <tns:parallel_index/>
        <tns:planned_end_time/>
        <tns:planned_end_time_format/>
        <tns:planned_input_qty/>
        <tns:planned_input_qty_format/>
        <tns:planned_input_qty_uom/>
        <tns:planned_output_qty/>
        <tns:planned_output_qty_format/>
        <tns:planned_output_qty_uom/>
        <tns:planned_start_time/>
        <tns:planned_start_time_format/>
        <tns:planned_transit_ready_time/>
        <tns:planned_transit_ready_time_format/>
        <tns:primary_output_part/>
        <tns:resource/>
        <tns:routing/>
        <tns:scheduler_comments/>
        <tns:scheduling_position/>
        <tns:setup_end_time/>
        <tns:setup_start_time/>
        <tns:setup_time_format/>
        <tns:setup_time/>
        <tns:setup_time_uom/>
        <tns:step_number/>
      </tns:ProdScheduleHeader>
      <xsl:for-each select="/ns0:XxnucGmeJdaTrnScheduleStgCollection/ns0:XxnucGmeJdaTrnScheduleStg">
        <xsl:sort select="number (ns0:schedulingPosition) " data-type="number" order="ascending"/>
        <tns:ProdSchedule>
          <tns:formatted_mfg_order_output_qty>
            <xsl:value-of select="ns0:formattedMfgOrderOutQty"/>
          </tns:formatted_mfg_order_output_qty>
          <tns:formatted_planned_input_qty>
            <xsl:value-of select="ns0:formattedPlannedInQty"/>
          </tns:formatted_planned_input_qty>
          <tns:formatted_planned_output_qty>
            <xsl:value-of select="ns0:formattedPlannedOutQty"/>
          </tns:formatted_planned_output_qty>
          <tns:keep_user_scheduled_start>
            <xsl:value-of select="ns0:keepUserScheduledStart"/>
          </tns:keep_user_scheduled_start>
          <tns:mfg_order_id>
            <xsl:value-of select="ns0:mfgOrderId"/>
          </tns:mfg_order_id>
          <tns:mfg_order_output_qty>
            <xsl:value-of select="ns0:mfgOrderOutputQty"/>
          </tns:mfg_order_output_qty>
          <tns:mfg_order_output_qty_format>
            <xsl:value-of select="ns0:mfgOrderOutputQtyFormat"/>
          </tns:mfg_order_output_qty_format>
          <tns:mfg_order_output_qty_uom>
            <xsl:value-of select="ns0:mfgOrderOutputQtyUom"/>
          </tns:mfg_order_output_qty_uom>
          <tns:operation_id>
            <xsl:value-of select="ns0:operationId"/>
          </tns:operation_id>
          <tns:original_scheduled_start_time>
            <xsl:value-of select="ns0:originalSchedStartTime"/>
          </tns:original_scheduled_start_time>
          <tns:original_scheduled_start_time_format>
            <xsl:value-of select="ns0:originalSchedStartTimeF"/>
          </tns:original_scheduled_start_time_format>
          <tns:parallel_index>
            <xsl:value-of select="ns0:parallelInd"/>
          </tns:parallel_index>
          <tns:planned_end_time>
            <xsl:value-of select="ns0:plannedEndTime"/>
          </tns:planned_end_time>
          <tns:planned_end_time_format>
            <xsl:value-of select="ns0:plannedEndTimeFormat"/>
          </tns:planned_end_time_format>
          <tns:planned_input_qty>
            <xsl:value-of select="ns0:plannedInputQty"/>
          </tns:planned_input_qty>
          <tns:planned_input_qty_format>
            <xsl:value-of select="ns0:plannedInputQtyFormat"/>
          </tns:planned_input_qty_format>
          <tns:planned_input_qty_uom>
            <xsl:value-of select="ns0:plannedInputQtyUom"/>
          </tns:planned_input_qty_uom>
          <tns:planned_output_qty>
            <xsl:value-of select="ns0:plannedOutputQty"/>
          </tns:planned_output_qty>
          <tns:planned_output_qty_format>
            <xsl:value-of select="ns0:plannedOutputQtyFormat"/>
          </tns:planned_output_qty_format>
          <tns:planned_output_qty_uom>
            <xsl:value-of select="ns0:plannedOutputQtyUom"/>
          </tns:planned_output_qty_uom>
          <tns:planned_start_time>
            <xsl:value-of select="ns0:plannedStartTime"/>
          </tns:planned_start_time>
          <tns:planned_start_time_format>
            <xsl:value-of select="ns0:plannedStartTimeFormat"/>
          </tns:planned_start_time_format>
          <tns:planned_transit_ready_time>
            <xsl:value-of select="ns0:plannedTransitReadyTime"/>
          </tns:planned_transit_ready_time>
          <tns:planned_transit_ready_time_format>
            <xsl:value-of select="ns0:plannedTransitReadyTimeF"/>
          </tns:planned_transit_ready_time_format>
          <tns:primary_output_part>
            <xsl:value-of select="ns0:primaryOutputPart"/>
          </tns:primary_output_part>
          <tns:resource>
            <xsl:value-of select="ns0:resourc"/>
          </tns:resource>
          <tns:routing>
            <xsl:value-of select="ns0:routing"/>
          </tns:routing>
          <tns:scheduler_comments>
            <xsl:value-of select="ns0:schedulerComments"/>
          </tns:scheduler_comments>
          <tns:scheduling_position>
            <xsl:value-of select="ns0:schedulingPosition"/>
          </tns:scheduling_position>
          <tns:setup_end_time>
            <xsl:value-of select="ns0:setupEndTime"/>
          </tns:setup_end_time>
          <tns:setup_start_time>
            <xsl:value-of select="ns0:setupStartTime"/>
          </tns:setup_start_time>
          <tns:setup_time_format>
            <xsl:value-of select="ns0:setupTimeFormat"/>
          </tns:setup_time_format>
          <tns:setup_time>
            <xsl:value-of select="ns0:setupTime"/>
          </tns:setup_time>
          <tns:setup_time_uom>
            <xsl:value-of select="ns0:setupTimeUom"/>
          </tns:setup_time_uom>
          <tns:step_number>
            <xsl:value-of select="ns0:stepNumber"/>
          </tns:step_number>
        </tns:ProdSchedule>
      </xsl:for-each>
    </tns:ProdScheduleList>
  </xsl:template>
</xsl:stylesheet>
