<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/Batch/1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_EBiz_JDA_Batch_ABF/DB_Extract_EBIZ_Batch_Details"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_EBiz_JDA_Batch_ABF/Write_JDA_Manufacturing_Order_Record"
                xmlns:FTPAPP="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Extract_EBIZ_Batch_Details.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaBatchExtVCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Extract_EBIZ_Batch_Details"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Write_JDA_Manufacturing_Order_Record.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ListOfBatches"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/Batch/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU APR 27 15:40:27 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ListOfBatches>
      <tns:BatchHeader>
        <tns:epst_format/>
        <tns:feeds_locked/>
        <tns:first_operation_epst/>
        <tns:first_operation_pst/>
        <tns:future_operation_for_hold/>
        <tns:last_operation_lpst/>
        <tns:last_operation_pst/>
        <tns:lpst_format/>
        <tns:maintain_quantity_locked/>
        <tns:manufacturing_order/>
        <tns:mfg_hold_date/>
        <tns:mfg_hold_date_format/>
        <tns:mfg_plant_id/>
        <tns:order_quantity_satisfied/>
        <tns:routing/>
        <tns:pst_format/>
        <tns:quantity_locked/>
        <tns:quantity_produced/>
        <tns:previous_quantity_produced/>
        <tns:routing_locked/>
        <tns:sort_priority/>
        <tns:specific_routing_id/>
        <tns:split_quantity/>
        <tns:step_number/>
        <tns:origScheduleDate/>
        <tns:create_auto_ato/>
      </tns:BatchHeader>
      <xsl:for-each select="/ns0:XxnucGmeJdaBatchExtVCollection/ns0:XxnucGmeJdaBatchExtV">
        <tns:Batch>
          <tns:epst_format>
            <xsl:value-of select="ns0:epstFormat"/>
          </tns:epst_format>
          <tns:feeds_locked>
            <xsl:value-of select="ns0:feedsLocked"/>
          </tns:feeds_locked>
          <tns:first_operation_epst>
            <xsl:value-of select="ns0:firstOperationEpst"/>
          </tns:first_operation_epst>
          <tns:first_operation_pst>
            <xsl:value-of select="ns0:firstOperationPst"/>
          </tns:first_operation_pst>
          <tns:future_operation_for_hold>
            <xsl:value-of select="ns0:futureOperationForHold"/>
          </tns:future_operation_for_hold>
          <tns:last_operation_lpst>
            <xsl:value-of select="ns0:lastOperationLpst"/>
          </tns:last_operation_lpst>
          <tns:last_operation_pst>
            <xsl:value-of select="ns0:lastOperationPst"/>
          </tns:last_operation_pst>
          <tns:lpst_format>
            <xsl:value-of select="ns0:lpstFormat"/>
          </tns:lpst_format>
          <tns:maintain_quantity_locked>
            <xsl:value-of select="ns0:maintainQuantityLocked"/>
          </tns:maintain_quantity_locked>
          <tns:manufacturing_order>
            <xsl:value-of select="ns0:manufacturingOrder"/>
          </tns:manufacturing_order>
          <tns:mfg_hold_date>
            <xsl:value-of select="ns0:mfgHoldDate"/>
          </tns:mfg_hold_date>
          <tns:mfg_hold_date_format>
            <xsl:value-of select="ns0:mfgHoldDateFormat"/>
          </tns:mfg_hold_date_format>
          <tns:mfg_plant_id>
            <xsl:value-of select="ns0:mfgPlantId"/>
          </tns:mfg_plant_id>
          <tns:order_quantity_satisfied>
            <xsl:value-of select="ns0:orderQuantitySatisfied"/>
          </tns:order_quantity_satisfied>
          <tns:routing>
            <xsl:value-of select="ns0:routing"/>
          </tns:routing>
          <tns:pst_format>
            <xsl:value-of select="ns0:pstFormat"/>
          </tns:pst_format>
          <tns:quantity_locked>
            <xsl:value-of select="ns0:quantityLocked"/>
          </tns:quantity_locked>
          <tns:quantity_produced>
            <xsl:value-of select="ns0:quantityProduced"/>
          </tns:quantity_produced>
          <tns:previous_quantity_produced>
            <xsl:value-of select="ns0:previousQuantityProduced"/>
          </tns:previous_quantity_produced>
          <tns:routing_locked>
            <xsl:value-of select="ns0:routingLocked"/>
          </tns:routing_locked>
          <tns:sort_priority>
            <xsl:value-of select="ns0:sortPriority"/>
          </tns:sort_priority>
          <tns:specific_routing_id>
            <xsl:value-of select="ns0:xxnucGmeJdaPartExtVCollection/ns0:XxnucGmeJdaPartExtV[ns0:lineType = '1'][1]/ns0:partNumber"/>
          </tns:specific_routing_id>
          <tns:split_quantity>
            <xsl:value-of select="ns0:splitQuantity"/>
          </tns:split_quantity>
          <tns:step_number>
            <xsl:value-of select="ns0:stepNumber"/>
          </tns:step_number>
          <tns:origScheduleDate>
            <xsl:value-of select="ns0:origScheduleDate"/>
          </tns:origScheduleDate>
          <tns:create_auto_ato>
            <xsl:value-of select="ns0:createAutoAto"/>
          </tns:create_auto_ato>
        </tns:Batch>
      </xsl:for-each>
    </tns:ListOfBatches>
  </xsl:template>
</xsl:stylesheet>
