<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAM/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_API_SPEC"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm utl oraxsl"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/NextGen1.1/NSUT_SubscribeQualitySpecs_QMOS_ABF/JMS_DEQ_NextGen_DistributedTopic"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns7="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAO/1.0"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns2="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:ns13="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSUT_SubscribeQualitySpecs_QMOS_ABF/DB_API_SPEC">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_DEQ_NextGen_DistributedTopic.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualitySpecsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_API_SPEC.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiSpecCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_API_SPEC"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE SEP 05 09:48:37 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ApiSpecCollection>
      <xsl:for-each select="/ns0:QualitySpecsAddRq/ns7:QualitySpecsDetails/ns7:QualitySpecsTest/ns7:QualitySpecsTest">
        <xsl:if test='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_QMOS_NSNE_ITEM_TYPE_MAP.dvm", "ITEMTYPE", ../../ns7:Item/ns3:ItemType, "BUNDLE", "" ) = "Y" and ns7:TestClass = "Mechanical"'>
          <tns:ApiSpec>
            <tns:seqNo>
              <xsl:value-of select='oraext:sequence-next-val ("SEQ_API_SPEC_SEQ_NO", "jdbc/nsseaqmos" )'/>
            </tns:seqNo>
            <tns:testElement>
              <xsl:value-of select="ns7:TestName"/>
            </tns:testElement>
            <tns:min>
              <xsl:value-of select="ns7:MinimumValue"/>
            </tns:min>
            <tns:max>
              <xsl:value-of select="ns7:MaximumValue"/>
            </tns:max>
            <tns:aim>
              <xsl:value-of select="ns7:TargetValue"/>
            </tns:aim>
            <tns:effectiveDate>
              <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:effectiveDate>
            <tns:workCenter>1</tns:workCenter>
            <tns:critical>1</tns:critical>
            <tns:numberOfTest>
              <xsl:value-of select="ns7:TestReplicate"/>
            </tns:numberOfTest>
            <tns:processed>N</tns:processed>
            <tns:prodCode>
              <xsl:value-of select="/ns0:QualitySpecsAddRq/ns7:QualitySpecsDetails/ns7:Item/ns3:Item"/>
            </tns:prodCode>
            <tns:specDescription>
              <xsl:value-of select="substring (/ns0:QualitySpecsAddRq/ns7:QualitySpecsDetails/ns7:Item/ns3:Description, 1, 25 )"/>
            </tns:specDescription>
            <tns:testClass>MECH</tns:testClass>
          </tns:ApiSpec>
        </xsl:if>
      </xsl:for-each>
    </tns:ApiSpecCollection>
  </xsl:template>
</xsl:stylesheet>
