<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.eia.com/AO/EBiz/O2C/SalesOrderAM/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://www.nucor.com/scmschemas/CorpXMLOrder.xsd"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://xmlns.eia.com/ABF/CreateSalesOrder_ABF/1.0/SalesOrder"
                xmlns:client="http://xmlns.eia.com/NucorSOA/NUC_SalesOrder_Corporate_EBS_ABF/CreateSalesOrderABF/1.0"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns3="cica"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/O2C/SalesOrderAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns4="http://xmlns.eia.com/Implementation/ABS/EBiz/O2C/SalesOrderABS/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns10="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/CreateSalesOrderABF.wsdl"/>
        <oracle-xsl-mapper:rootElement name="orders" namespace="http://www.nucor.com/scmschemas/CorpXMLOrder.xsd"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/SalesOrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SalesOrderAddRq"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/SalesOrderAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE OCT 20 09:27:35 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:variable name="varOrgId"
                  select="oraext:query-database(concat(&quot;select org_id from hz_cust_site_uses_all where site_use_id ='&quot;,/ns0:orders/order/shiptoinformation/@custlocid,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
    <xsl:variable name="varOrgId_secondary">
      <xsl:choose>
        <xsl:when test="string-length($varOrgId) > 0">
          <xsl:value-of select="'Dummy'"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="oraext:query-database(concat(&quot;SELECT xxom.EBS_ORG_ID FROM mtl_parameters mp,xxnuc_xf_orgid_millid xxom WHERE mp.organization_id = xxom.ebs_organization_id AND mp.attribute11 IS NULL AND ods_mill_id = '&quot;,/ns0:orders/order/@ordermillid,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:variable name="varInventoryOrgId"
                  select="oraext:query-database(concat(&quot;SELECT mp.organization_id FROM mtl_parameters mp,xxnuc_xf_orgid_millid xxom WHERE mp.organization_id = xxom.ebs_organization_id AND mp.attribute11 IS NULL AND ods_mill_id = '&quot;,/ns0:orders/order/@ordermillid,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
    <tns:SalesOrderAddRq>
      <ns9:HeaderRq>
        <ns9:TransactionRequestID>temp</ns9:TransactionRequestID>
        <ns9:Language>ENG</ns9:Language>
        <ns9:ComponentID>I038</ns9:ComponentID>
        <ns9:ServiceName>temp</ns9:ServiceName>
        <ns9:TransactionIDREF>temp</ns9:TransactionIDREF>
        <ns9:TransactionName>SalesOrder</ns9:TransactionName>
        <ns9:Source>26</ns9:Source>
        <ns9:Target>2</ns9:Target>
        <ns9:TimeStamp>
          <xsl:value-of select="xp20:current-date ( )"/>
        </ns9:TimeStamp>
      </ns9:HeaderRq>
      <ns5:SalesOrderDetails>
        <xsl:if test="/ns0:orders/order/@scporderid">
          <ns5:ORIG_SYS_DOCUMENT_REF>
            <xsl:value-of select="/ns0:orders/order/@scporderid"/>
          </ns5:ORIG_SYS_DOCUMENT_REF>
        </xsl:if>
        <!--xsl:if test="/ns0:orders/order/@OrderMillID"-->
        <xsl:choose>
          <xsl:when test="$varOrgId != ''">
            <ns5:ORG_ID>
              <xsl:value-of select="$varOrgId"/>
            </ns5:ORG_ID>
          </xsl:when>
          <xsl:otherwise>
            <ns5:ORG_ID>
              <xsl:value-of select="$varOrgId_secondary"/>
            </ns5:ORG_ID>
          </xsl:otherwise>
        </xsl:choose>
        <!--/xsl:if-->
        <!--ns5:VERSION_NUMBER>
          <xsl:value-of select="/ns0:orders/@Version"/>
        </ns5:VERSION_NUMBER-->
        <xsl:if test="/ns0:orders/order/@orderdatetime">
          <ns5:ORDERED_DATE>
            <xsl:value-of select="/ns0:orders/order/@orderdatetime"/>
          </ns5:ORDERED_DATE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/@ordertype">
          <ns5:ORDER_TYPE>
            <xsl:value-of select="/ns0:orders/order/@ordertype"/>
          </ns5:ORDER_TYPE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/@currency">
          <ns5:TRANSACTIONAL_CURR_CODE>
            <xsl:value-of select="/ns0:orders/order/@currency"/>
          </ns5:TRANSACTIONAL_CURR_CODE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/@customerponumber">
          <ns5:CUSTOMER_PO_NUMBER>
            <xsl:value-of select="/ns0:orders/order/@customerponumber"/>
          </ns5:CUSTOMER_PO_NUMBER>
        </xsl:if>
        <!-- Removed as part of defect#1900
        <xsl:if test="/ns0:orders/order/soldto/@siteuseid">
          <ns5:SOLD_TO_ORG_ID>
            <xsl:value-of select="/ns0:orders/order/soldto/@siteuseid"/>
          </ns5:SOLD_TO_ORG_ID>
        </xsl:if> -->
        <!--xsl:if test="/ns0:orders/order/soldto/@company">
          <ns5:SOLD_TO_ORG>
            <xsl:value-of select="/ns0:orders/order/soldto/@company"/>
          </ns5:SOLD_TO_ORG>
        </xsl:if-->
        <!-- Modified as a part of Defect#1900 
        <xsl:if test="/ns0:orders/order/shiptoinformation/@siteuseid">
          <ns5:SHIP_TO_ORG_ID>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@siteuseid"/>
          </ns5:SHIP_TO_ORG_ID>
        </xsl:if> -->
        <xsl:if test="/ns0:orders/order/shiptoinformation/@custlocid">
          <ns5:SHIP_TO_ORG_ID>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@custlocid"/>
          </ns5:SHIP_TO_ORG_ID>
        </xsl:if>
        <!--xsl:if test="/ns0:orders/order/shiptoinformation/@company">
          <ns5:SHIP_TO_ORG>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@company"/>
          </ns5:SHIP_TO_ORG>
        </xsl:if-->
        <!-- Removed as apart of Defect#1900
        <xsl:if test="/ns0:orders/order/billto/@siteuseid">
          <ns5:INVOICE_TO_ORG_ID>
            <xsl:value-of select="/ns0:orders/order/billto/@siteuseid"/>
          </ns5:INVOICE_TO_ORG_ID>
        </xsl:if> -->
        <!--xsl:if test="/ns0:orders/order/billto/@company">
          <ns5:INVOICE_TO_ORG>
            <xsl:value-of select="/ns0:orders/order/billto/@company"/>
          </ns5:INVOICE_TO_ORG>
        </xsl:if-->
        <!--xsl:if test="/ns0:orders/order/soldto/@contactname">
          <ns5:SOLD_TO_CONTACT>
            <xsl:value-of select="/ns0:orders/order/soldto/@contactname"/>
          </ns5:SOLD_TO_CONTACT>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/shiptoinformation/@contactname">
          <ns5:SHIP_TO_CONTACT>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@contactname"/>
          </ns5:SHIP_TO_CONTACT>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/billto/@contactname">
          <ns5:INVOICE_TO_CONTACT>
            <xsl:value-of select="/ns0:orders/order/billto/@contactname"/>
          </ns5:INVOICE_TO_CONTACT>
        </xsl:if-->
        <!-- Removed as part of Defect#1900
        <xsl:if test="/ns0:orders/order/@customerid">
          <ns5:CUSTOMER_ID>
            <xsl:value-of select="/ns0:orders/order/@customerid"/>
          </ns5:CUSTOMER_ID>
        </xsl:if>
        -->
        <!--xsl:if test="/ns0:orders/order/shiptoinformation/@address">
          <ns5:SHIP_TO_ADDRESS1>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@address"/>
          </ns5:SHIP_TO_ADDRESS1>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/shiptoinformation/@address2">
          <ns5:SHIP_TO_ADDRESS2>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@address2"/>
          </ns5:SHIP_TO_ADDRESS2>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/shiptoinformation/@city">
          <ns5:SHIP_TO_CITY>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@city"/>
          </ns5:SHIP_TO_CITY>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/shiptoinformation/@zip">
          <ns5:SHIP_TO_POSTAL_CODE>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@zip"/>
          </ns5:SHIP_TO_POSTAL_CODE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/shiptoinformation/@state">
          <ns5:SHIP_TO_STATE>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@state"/>
          </ns5:SHIP_TO_STATE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/shiptoinformation/@country">
          <ns5:SHIP_TO_COUNTRY>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@country"/>
          </ns5:SHIP_TO_COUNTRY>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/billto/@address">
          <ns5:INVOICE_ADDRESS1>
            <xsl:value-of select="/ns0:orders/order/billto/@address"/>
          </ns5:INVOICE_ADDRESS1>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/billto/@address2">
          <ns5:INVOICE_ADDRESS2>
            <xsl:value-of select="/ns0:orders/order/billto/@address2"/>
          </ns5:INVOICE_ADDRESS2>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/billto/@city">
          <ns5:INVOICE_CITY>
            <xsl:value-of select="/ns0:orders/order/billto/@city"/>
          </ns5:INVOICE_CITY>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/billto/@country">
          <ns5:INVOICE_COUNTRY>
            <xsl:value-of select="/ns0:orders/order/billto/@country"/>
          </ns5:INVOICE_COUNTRY>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/billto/@zip">
          <ns5:INVOICE_POSTAL_CODE>
            <xsl:value-of select="/ns0:orders/order/billto/@zip"/>
          </ns5:INVOICE_POSTAL_CODE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/billto/@state">
          <ns5:INVOICE_STATE>
            <xsl:value-of select="/ns0:orders/order/billto/@state"/>
          </ns5:INVOICE_STATE>
        </xsl:if-->
        <xsl:if test="/ns0:orders/@createdate">
          <ns5:CREATION_DATE>
            <xsl:value-of select="/ns0:orders/@createdate"/>
          </ns5:CREATION_DATE>
        </xsl:if>
        <xsl:if test="/ns0:orders/@opmode">
          <ns5:OPERATION_CODE>
            <xsl:value-of select="/ns0:orders/@opmode"/>
          </ns5:OPERATION_CODE>
        </xsl:if>
        <!-- Removed as a part of Defect#1900
        <xsl:if test="/ns0:orders/order/shiptoinformation/@customerid">
          <ns5:SHIP_TO_CUSTOMER_ID>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@customerid"/>
          </ns5:SHIP_TO_CUSTOMER_ID>
        </xsl:if> -->
        <!-- Removed as a part of Defect#1900
        <xsl:if test="/ns0:orders/order/billto/@customerid">
          <ns5:INVOICE_CUSTOMER_ID>
            <xsl:value-of select="/ns0:orders/order/billto/@customerid"/>
          </ns5:INVOICE_CUSTOMER_ID>
        </xsl:if> -->
        <!--xsl:if test="/ns0:orders/order/@nucorglobalcustomerid">
          <ns5:END_CUSTOMER_ID>
            <xsl:value-of select="/ns0:orders/order/@nucorglobalcustomerid"/>
          </ns5:END_CUSTOMER_ID>
        </xsl:if-->
        <!--xsl:if test="/ns0:orders/order/soldto/@address">
          <ns5:SOLD_TO_LOCATION_ADDRESS1>
            <xsl:value-of select="/ns0:orders/order/soldto/@address"/>
          </ns5:SOLD_TO_LOCATION_ADDRESS1>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/soldto/@address2">
          <ns5:SOLD_TO_LOCATION_ADDRESS2>
            <xsl:value-of select="/ns0:orders/order/soldto/@address2"/>
          </ns5:SOLD_TO_LOCATION_ADDRESS2>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/soldto/@city">
          <ns5:SOLD_TO_LOCATION_CITY>
            <xsl:value-of select="/ns0:orders/order/soldto/@city"/>
          </ns5:SOLD_TO_LOCATION_CITY>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/soldto/@zip">
          <ns5:SOLD_TO_LOCATION_POSTAL_CODE>
            <xsl:value-of select="/ns0:orders/order/soldto/@zip"/>
          </ns5:SOLD_TO_LOCATION_POSTAL_CODE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/soldto/@country">
          <ns5:SOLD_TO_LOCATION_COUNTRY>
            <xsl:value-of select="/ns0:orders/order/soldto/@country"/>
          </ns5:SOLD_TO_LOCATION_COUNTRY>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/soldto/@state">
          <ns5:SOLD_TO_LOCATION_STATE>
            <xsl:value-of select="/ns0:orders/order/soldto/@state"/>
          </ns5:SOLD_TO_LOCATION_STATE>
        </xsl:if-->
        <xsl:if test="/ns0:orders/order/@scpproducttype">
          <ns5:SCP_PRODUCT_TYPE>
            <xsl:value-of select="/ns0:orders/order/@scpproducttype"/>
          </ns5:SCP_PRODUCT_TYPE>
        </xsl:if>
        <!--xsl:if test="/ns0:orders/order/shiptoinformation/@custlocid">
          <ns5:CUST_LOC_ID>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@custlocid"/>
          </ns5:CUST_LOC_ID>
        </xsl:if-->
        <xsl:if test="/ns0:orders/order/shiptoinformation/shippinginstructions">
          <ns5:SHIPPING_INSTR_DESC>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/shippinginstructions"/>
          </ns5:SHIPPING_INSTR_DESC>
        </xsl:if>
        <!--xsl:if test="/ns0:orders/order/soldto/@contactphone">
          <ns5:SOLD_TO_CONTACT_PHONE>
            <xsl:value-of select="/ns0:orders/order/soldto/@contactphone"/>
          </ns5:SOLD_TO_CONTACT_PHONE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/shiptoinformation/@contactphone">
          <ns5:SHIP_TO_CONTACT_PHONE>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@contactphone"/>
          </ns5:SHIP_TO_CONTACT_PHONE>
        </xsl:if>
        <xsl:if test="/ns0:orders/order/shiptoinformation/@contactphone">
          <ns5:INVOICE_TO_CONTACT_PHONE>
            <xsl:value-of select="/ns0:orders/order/shiptoinformation/@contactphone"/>
          </ns5:INVOICE_TO_CONTACT_PHONE>
        </xsl:if-->
        <ns5:SalesOrderLines>
          <xsl:for-each select="/ns0:orders/order/lineitems/lineitem">
           <xsl:sort select="@customerlinenumber" order="ascending"/>
            <ns5:LineItem>
              <xsl:choose>
                <xsl:when test="$varOrgId != ''">
                  <ns5:ORG_ID>
                    <xsl:value-of select="$varOrgId"/>
                  </ns5:ORG_ID>
                </xsl:when>
                <xsl:otherwise>
                  <ns5:ORG_ID>
                    <xsl:value-of select="$varOrgId_secondary"/>
                  </ns5:ORG_ID>
                </xsl:otherwise>
              </xsl:choose>
              <xsl:variable name="varInventoryItemId"
                            select="oraext:query-database(concat(&quot;SELECT inventory_item_id FROM mtl_system_items_b WHERE organization_id = '&quot;,$varInventoryOrgId,&quot;' AND segment1 = '&quot;,@productid,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
              <!--xsl:if test="@productid"-->
              <ns5:INVENTORY_ITEM_ID>
                <xsl:value-of select="$varInventoryItemId"/>
              </ns5:INVENTORY_ITEM_ID>
              <!--/xsl:if-->
              <ns5:INVENTORY_ITEM>
                <xsl:value-of select="@productid"/>
              </ns5:INVENTORY_ITEM>
              <xsl:if test="tonsanddates/tonsanddate/@tonsordered">
                <ns5:ORDERED_QUANTITY>
                  <xsl:value-of select="tonsanddates/tonsanddate/@tonsordered"/>
                </ns5:ORDERED_QUANTITY>
              </xsl:if>
              <!-- modified as part of Defect# 1900xsl:if test="tonsanddates/tonsanddate/@uom">
                <ns5:ORDER_QUANTITY_UOM>
                  <xsl:value-of select="tonsanddates/tonsanddate/@uom"/>
                </ns5:ORDER_QUANTITY_UOM>
              </xsl:if -->
              <ns5:ORIG_SYS_LINE_REF>
                <xsl:value-of select="oraext:sequence-next-val('OE_ORDER_LINES_S','jdbc/ebsapps')"/>
              </ns5:ORIG_SYS_LINE_REF>
              <xsl:if test="tonsanddates/tonsanddate/@uom">
                <ns5:ORDER_QUANTITY_UOM>
                  <xsl:value-of select="oraext:query-database(concat(&quot;SELECT uom_code FROM mtl_units_of_measure WHERE source_lang = 'US' and language= 'US' and attribute14 = '&quot;,tonsanddates/tonsanddate/@uom,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
                </ns5:ORDER_QUANTITY_UOM>
              </xsl:if>
              <!-- Removed as part of Defect#1900
              <xsl:if test="/ns0:orders/order/soldto/@siteuseid">
                <ns5:SOLD_TO_ORG_ID>
                  <xsl:value-of select="/ns0:orders/order/soldto/@siteuseid"/>
                </ns5:SOLD_TO_ORG_ID>
              </xsl:if> -->
              <!-- Modified as apart of Defect#1900
              <xsl:if test="/ns0:orders/order/shiptoinformation/@siteuseid">
                <ns5:SHIP_TO_ORG_ID>
                  <xsl:value-of select="/ns0:orders/order/shiptoinformation/@siteuseid"/>
                </ns5:SHIP_TO_ORG_ID>
              </xsl:if> -->
              <xsl:if test="/ns0:orders/order/shiptoinformation/@custlocid">
                <ns5:SHIP_TO_ORG_ID>
                  <xsl:value-of select="/ns0:orders/order/shiptoinformation/@custlocid"/>
                </ns5:SHIP_TO_ORG_ID>
              </xsl:if>
              <!-- Removed as a part of Defect#1900
              <xsl:if test="/ns0:orders/order/billto/@siteuseid">
                <ns5:INVOICE_TO_ORG_ID>
                  <xsl:value-of select="/ns0:orders/order/billto/@siteuseid"/>
                </ns5:INVOICE_TO_ORG_ID>
              </xsl:if> -->
              <!-- Modified as a part of Defect#1900xsl:if test="@transportmode">
                <ns5:SHIPPING_METHOD_CODE>
                  <xsl:value-of select="@transportmode"/>
                </ns5:SHIPPING_METHOD_CODE>
              </xsl:if-->
              <xsl:if test="@transportmode">
                <ns5:INDUSTRY_ATTRIBUTE1>
                  <xsl:value-of select="@transportmode"/>
                </ns5:INDUSTRY_ATTRIBUTE1>
              </xsl:if>
              <xsl:if test="@customerlinenumber">
                <ns5:CUSTOMER_LINE_NUMBER>
                  <xsl:value-of select="@customerlinenumber"/>
                </ns5:CUSTOMER_LINE_NUMBER>
              </xsl:if>
              <xsl:if test="tonsanddates/tonsanddate/@dateneeded">
                <ns5:REQUEST_DATE>
                  <xsl:value-of select="tonsanddates/tonsanddate/@dateneeded"/>
                </ns5:REQUEST_DATE>
              </xsl:if>
              <xsl:if test="@productdescription">
                <ns5:USER_ITEM_DESCRIPTION>
                  <xsl:value-of select="@productdescription"/>
                </ns5:USER_ITEM_DESCRIPTION>
              </xsl:if>
              <xsl:if test="@size">
                <ns5:SIZE_PRODUCT>
                  <xsl:value-of select="@size"/>
                </ns5:SIZE_PRODUCT>
              </xsl:if>
              <xsl:if test="@grade">
                <ns5:GRADE>
                  <xsl:value-of select="@grade"/>
                </ns5:GRADE>
              </xsl:if>
              <xsl:if test="@lengthinches">
                <ns5:LENGTH_INCHES>
                  <xsl:value-of select="@lengthinches"/>
                </ns5:LENGTH_INCHES>
              </xsl:if>
              <xsl:if test="@customerpartnumber">
                <ns5:CUSTOMER_PART_NUMBER>
                  <xsl:value-of select="@customerpartnumber"/>
                </ns5:CUSTOMER_PART_NUMBER>
              </xsl:if>
            </ns5:LineItem>
          </xsl:for-each>
        </ns5:SalesOrderLines>
      </ns5:SalesOrderDetails>
    </tns:SalesOrderAddRq>
  </xsl:template>
</xsl:stylesheet>
