<wsdl:definitions
     name="DB_Update_HeatSchedule"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_CastBatch_L2_EBS_ABF/DB_Update_HeatSchedule"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_CastBatch_L2_EBS_ABF/DB_Update_HeatSchedule"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_HeatSchedule"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Update_HeatSchedule_plt" >
    <plt:role name="DB_Update_HeatSchedule_role" >
      <plt:portType name="tns:DB_Update_HeatSchedule_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_HeatSchedule" schemaLocation="../Schemas/DB_Update_HeatSchedule_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Cast_Heat_Trans_EventsCollection_msg">
        <wsdl:part name="Cast_Heat_Trans_EventsCollection" element="top:Cast_Heat_Trans_EventsCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Update_HeatSchedule_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:Cast_Heat_Trans_EventsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
