<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://xmlns.eia.com/ABS/EBiz/A2R/JournalABS/1.0"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.eia.com/ABS/EBiz/A2R/JournalABS/1.0"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="JournalABS">
        <plnk:role name="SyncPortType" portType="tns:SyncPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.eia.com/ABS/EBiz/A2R/JournalABS/1.0" location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/A2R/JournalABS.wsdl"/>
</wsdl:definitions>
