<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/O2C/ShipDocumentAM/1.0"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:ns3="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:tns="http://xmlns.eia.com/ABS/EBiz/O2C/ShipDocumentABS/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns1="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns2="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/O2C/ShipDocumentAO/1.0">
  <oracle-xsl-mapper:schema xml:id="id_2">
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources xml:id="id_3">
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/ShipDocumentABS.wsdl"
                                  xml:id="id_5"/>
        <oracle-xsl-mapper:rootElement name="QueryShipDocumentRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/ShipDocumentAM/1.0" xml:id="id_6"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets xml:id="id_7">
      <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/ShipDocumentABS.wsdl"
                                  xml:id="id_9"/>
        <oracle-xsl-mapper:rootElement name="QueryShipDocumentResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/ShipDocumentAM/1.0" xml:id="id_10"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU AUG 31 14:15:36 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/" xml:id="id_11">
    <ns0:QueryShipDocumentResponseMessage xml:id="id_12">
      <xsl:choose xml:id="id_13">
        <xsl:when xml:id="id_14" test="count(/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:TransactionRequestID) > 0">
          <ns3:HeaderRs xml:id="id_15">
            <ns3:TransactionID xml:id="id_16">
              <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:TransactionIDREF"
                            xml:id="id_17"/>
            </ns3:TransactionID>
            <ns3:RequestDetails xml:id="id_18">
              <ns3:TransactionRequestID xml:id="id_19">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:TransactionRequestID"
                              xml:id="id_20"/>
              </ns3:TransactionRequestID>
              <ns3:Language xml:id="id_21">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:Language" xml:id="id_22"/>
              </ns3:Language>
              <ns3:ComponentID xml:id="id_23">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:ComponentID"
                              xml:id="id_24"/>
              </ns3:ComponentID>
              <ns3:ServiceName xml:id="id_25">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:ServiceName"
                              xml:id="id_26"/>
              </ns3:ServiceName>
              <ns3:TransactionIDREF xml:id="id_27">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:TransactionIDREF"
                              xml:id="id_28"/>
              </ns3:TransactionIDREF>
              <ns3:TransactionName xml:id="id_29">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:TransactionName"
                              xml:id="id_30"/>
              </ns3:TransactionName>
              <ns3:FileName xml:id="id_31">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:FileName" xml:id="id_32"/>
              </ns3:FileName>
              <ns3:FileInstanceID xml:id="id_33">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:FileInstanceID"
                              xml:id="id_34"/>
              </ns3:FileInstanceID>
              <ns3:Source xml:id="id_35">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:Source" xml:id="id_36"/>
              </ns3:Source>
              <ns3:Target xml:id="id_37">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:Target" xml:id="id_38"/>
              </ns3:Target>
              <ns3:HostName xml:id="id_39">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:HostName" xml:id="id_40"/>
              </ns3:HostName>
              <ns3:UserName xml:id="id_41">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:UserName" xml:id="id_42"/>
              </ns3:UserName>
              <ns3:UserRole xml:id="id_43">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:UserRole" xml:id="id_44"/>
              </ns3:UserRole>
              <ns3:AdminEmail xml:id="id_45">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:AdminEmail" xml:id="id_46"/>
              </ns3:AdminEmail>
              <ns3:ApplicationResponsibility xml:id="id_47">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:ApplicationResponsibility"
                              xml:id="id_48"/>
              </ns3:ApplicationResponsibility>
              <ns3:EOFFlag xml:id="id_49">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:EOFFlag" xml:id="id_50"/>
              </ns3:EOFFlag>
              <ns3:SOFFlag xml:id="id_51">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:SOFFlag" xml:id="id_52"/>
              </ns3:SOFFlag>
              <ns3:FileRecordCount xml:id="id_53">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:FileRecordCount"
                              xml:id="id_54"/>
              </ns3:FileRecordCount>
              <ns3:TimeStamp xml:id="id_55">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:TimeStamp" xml:id="id_56"/>
              </ns3:TimeStamp>
              <ns3:MillName xml:id="id_57">
                <xsl:value-of select="/ns0:QueryShipDocumentRequestMessage/ns3:HeaderRq/ns3:MillName" xml:id="id_58"/>
              </ns3:MillName>
            </ns3:RequestDetails>
            <ns3:Status xml:id="id_61">
              <ns3:Status xml:id="id_62">E</ns3:Status>
            </ns3:Status>
          </ns3:HeaderRs>
        </xsl:when>
      </xsl:choose>
      <ns0:OperationResult xml:id="id_59">
        <ns7:Stats xml:id="id_60">E</ns7:Stats>
        <ns7:Errors xml:id="id_63">
          <ns7:OperationResultError xml:id="id_64">''</ns7:OperationResultError>
        </ns7:Errors>
      </ns0:OperationResult>
    </ns0:QueryShipDocumentResponseMessage>
  </xsl:template>
</xsl:stylesheet>
