<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="B2B_EbizOutboundThread"
     targetNamespace="http://oracle.com/sca/soapservice/SMG-nuc/NUC_B2B_Ebiz_Outbound_ABF/B2B_EbizOutboundThread"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://oracle.com/sca/soapservice/SMG-nuc/NUC_B2B_Ebiz_Outbound_ABF/B2B_EbizOutboundThread"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="B2B_EbizOutboundThread">
        <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://oracle.com/sca/soapservice/SMG-nuc/NUC_B2B_Ebiz_Outbound_ABF/B2B_EbizOutboundThread"
         location="B2B_EbizOutboundThread.wsdl"/>
</wsdl:definitions>
