<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Get_ProductStructure"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:ns8="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/NUC_EBizProductStructure_ABS/DB_Get_ProductStructure"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:tns="http://oracle.com/sca/soapservice/Application2/NUC_EBizProductStructure_ABS/EbizProductStructure"
                xmlns:ns7="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns3="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns5="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAO/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/EbizProductStructure.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryProductStructureAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Get_ProductStructure.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Get_ProductStructure"/>
        <oracle-xsl-mapper:param name="g_Invoke_DB_Get_ProductStructure_OutputVariable.OutputParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/EbizProductStructure.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryProductStructureAddRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE APR 26 07:02:16 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_Invoke_DB_Get_ProductStructure_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <ns0:QueryProductStructureAddRs>
      <ns7:HeaderRs>
        <ns7:RequestDetails>
          <ns7:TransactionRequestID>
            <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:TransactionRequestID"/>
          </ns7:TransactionRequestID>
          <ns7:Language>
            <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:Language"/>
          </ns7:Language>
          <ns7:ComponentID>
            <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:ComponentID"/>
          </ns7:ComponentID>
          <ns7:ServiceName>
            <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:ServiceName"/>
          </ns7:ServiceName>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:TransactionIDREF">
            <ns7:TransactionIDREF>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:TransactionIDREF"/>
            </ns7:TransactionIDREF>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:TransactionName">
            <ns7:TransactionName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:TransactionName"/>
            </ns7:TransactionName>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:FileName">
            <ns7:FileName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:FileName"/>
            </ns7:FileName>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:FileInstanceID">
            <ns7:FileInstanceID>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:FileInstanceID"/>
            </ns7:FileInstanceID>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:Source">
            <ns7:Source>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:Source"/>
            </ns7:Source>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:Target">
            <ns7:Target>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:Target"/>
            </ns7:Target>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:HostName">
            <ns7:HostName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:HostName"/>
            </ns7:HostName>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:UserName">
            <ns7:UserName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:UserName"/>
            </ns7:UserName>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:UserRole">
            <ns7:UserRole>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:UserRole"/>
            </ns7:UserRole>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:AdminEmail">
            <ns7:AdminEmail>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:AdminEmail"/>
            </ns7:AdminEmail>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:ApplicationResponsibility">
            <ns7:ApplicationResponsibility>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:ApplicationResponsibility"/>
            </ns7:ApplicationResponsibility>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:EOFFlag">
            <ns7:EOFFlag>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:EOFFlag"/>
            </ns7:EOFFlag>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:SOFFlag">
            <ns7:SOFFlag>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:SOFFlag"/>
            </ns7:SOFFlag>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:FileRecordCount">
            <ns7:FileRecordCount>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:FileRecordCount"/>
            </ns7:FileRecordCount>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:TimeStamp">
            <ns7:TimeStamp>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:TimeStamp"/>
            </ns7:TimeStamp>
          </xsl:if>
          <xsl:if test="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:MillName">
            <ns7:MillName>
              <xsl:value-of select="/ns0:QueryProductStructureAddRq/ns7:HeaderRq/ns7:MillName"/>
            </ns7:MillName>
          </xsl:if>
        </ns7:RequestDetails>
        <ns7:Status>
          <ns7:Status>Success</ns7:Status>
        </ns7:Status>
      </ns7:HeaderRs>
      <xsl:for-each select="$g_Invoke_DB_Get_ProductStructure_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_RECIPE_PAYLOAD/ns1:P_RECIPE_PAYLOAD_ITEM">
        <ns5:ProductStructureDetails>
          <ns5:ListOfRecipe>
            <ns5:RecipeNumber>
              <xsl:value-of select="ns1:RECIPE_NO"/>
            </ns5:RecipeNumber>
            <ns5:RecipeVersion>
              <xsl:value-of select="ns1:RECIPE_VERS"/>
            </ns5:RecipeVersion>
            <ns5:RecipeID>
              <xsl:value-of select="ns1:RECIPE_ID"/>
            </ns5:RecipeID>
            <ns5:RecipeDescription>
              <xsl:value-of select="ns1:RECIPE_DESC"/>
            </ns5:RecipeDescription>
            <ns5:OwnerOrganization>
              <xsl:value-of select="ns1:ORGN_CODE"/>
            </ns5:OwnerOrganization>
            <ns5:CreationOrganization>
              <xsl:value-of select="ns1:CRE_ORGN_CODE"/>
            </ns5:CreationOrganization>
            <ns5:Product>
              <xsl:value-of select="ns1:PRODUCT"/>
            </ns5:Product>
            <ns5:FormulaID>
              <xsl:value-of select="ns1:FORMULA_ID"/>
            </ns5:FormulaID>
            <ns5:RountingID>
              <xsl:value-of select="ns1:ROUTING_ID"/>
            </ns5:RountingID>
            <ns5:RecipeStatus>
              <xsl:value-of select="ns1:RECIPE_STATUS"/>
            </ns5:RecipeStatus>
            <ns5:PlannedProcessLoss>
              <xsl:value-of select="ns1:PLANNED_PROCESS_LOSS"/>
            </ns5:PlannedProcessLoss>
            <ns5:CalculateStepQuantity>
              <xsl:value-of select="ns1:CALCULATE_STEP_QTY"/>
            </ns5:CalculateStepQuantity>
            <ns5:OrganizationCode>
              <xsl:value-of select="ns1:ORGN_CODE"/>
            </ns5:OrganizationCode>
            <ns5:OrganizationName>
              <xsl:value-of select="ns1:ORGN_NAME"/>
            </ns5:OrganizationName>
            <ns5:Attribute>
              <ns5:AttributeCategory>
                <xsl:value-of select="ns1:ATTRIBUTE_CATEGORY"/>
              </ns5:AttributeCategory>
              <ns5:Attribute1>
                <xsl:value-of select="ns1:ATTRIBUTE1"/>
              </ns5:Attribute1>
              <ns5:Attribute2>
                <xsl:value-of select="ns1:ATTRIBUTE2"/>
              </ns5:Attribute2>
              <ns5:Attribute3>
                <xsl:value-of select="ns1:ATTRIBUTE3"/>
              </ns5:Attribute3>
              <ns5:Attribute4>
                <xsl:value-of select="ns1:ATTRIBUTE4"/>
              </ns5:Attribute4>
              <ns5:Attribute5>
                <xsl:value-of select="ns1:ATTRIBUTE5"/>
              </ns5:Attribute5>
            </ns5:Attribute>
            <ns5:ResourceName>
              <xsl:value-of select="ns1:RESOURCE_NAME"/>
            </ns5:ResourceName>
            <ns5:ListOfFormulas>
              <xsl:for-each select="ns1:FORMULA_DTLS/ns1:FORMULA_DTLS_ITEM">
                <ns5:Formulas>
                  <ns5:FormulaNumber>
                    <xsl:value-of select="ns1:FORMULA_NO"/>
                  </ns5:FormulaNumber>
                  <ns5:FormulaVersion>
                    <xsl:value-of select="ns1:FORMULA_VERS"/>
                  </ns5:FormulaVersion>
                  <ns5:FormulaID>
                    <xsl:value-of select="ns1:FORMULA_ID"/>
                  </ns5:FormulaID>
                  <ns5:FormulaType>
                    <xsl:value-of select="ns1:PACKAGING"/>
                  </ns5:FormulaType>
                  <xsl:if test="ns1:FORMULA_DESC">
                    <ns5:FormulaDescription>
                      <xsl:value-of select="ns1:FORMULA_DESC"/>
                    </ns5:FormulaDescription>
                  </xsl:if>
                  <ns5:FormulaClass>
                    <xsl:value-of select="ns1:FORMULA_CLASS"/>
                  </ns5:FormulaClass>
                  <xsl:if test="ns1:COMMENTS">
                    <ns5:Comments>
                      <xsl:value-of select="ns1:COMMENTS"/>
                    </ns5:Comments>
                  </xsl:if>
                  <ns5:OrganizationCode>
                    <xsl:value-of select="ns1:ORGN_CODE"/>
                  </ns5:OrganizationCode>
                  <ns5:OwnerName>
                    <xsl:value-of select="ns1:FORMULA_OWNER"/>
                  </ns5:OwnerName>
                  <ns5:FormulaStatus>
                    <xsl:value-of select="ns1:FORMULA_STATUS"/>
                  </ns5:FormulaStatus>
                  <ns5:ScaleTypeHeader>
                    <xsl:value-of select="ns1:SCALLING_ALLOWED"/>
                  </ns5:ScaleTypeHeader>
                  <ns5:CalcProductQty>
                    <xsl:value-of select="ns1:CALC_PRODUCT_QTY"/>
                  </ns5:CalcProductQty>
                  <ns5:Attribute>
                    <ns5:AttributeCategory>
                      <xsl:value-of select="ns1:ATTRIBUTE_CATEGORY"/>
                    </ns5:AttributeCategory>
                    <ns5:Attribute1>
                      <xsl:value-of select="ns1:ATTRIBUTE1"/>
                    </ns5:Attribute1>
                    <ns5:Attribute2>
                      <xsl:value-of select="ns1:ATTRIBUTE2"/>
                    </ns5:Attribute2>
                    <ns5:Attribute3>
                      <xsl:value-of select="ns1:ATTRIBUTE3"/>
                    </ns5:Attribute3>
                    <ns5:Attribute4>
                      <xsl:value-of select="ns1:ATTRIBUTE4"/>
                    </ns5:Attribute4>
                    <ns5:Attribute5>
                      <xsl:value-of select="ns1:ATTRIBUTE5"/>
                    </ns5:Attribute5>
                  </ns5:Attribute>
                  <ns5:ListOfFormulaDetails>
                    <xsl:for-each select="ns1:FRM_DTLS/ns1:FRM_DTLS_ITEM">
                      <xsl:if test="$g_Invoke_DB_Get_ProductStructure_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_RECIPE_PAYLOAD/ns1:P_RECIPE_PAYLOAD_ITEM/ns1:FORMULA_DTLS/ns1:FORMULA_DTLS_ITEM/ns1:FRM_DTLS/ns1:FRM_DTLS_ITEM">
                        <ns5:FormulaDetails>
                          <ns5:FormulaID>
                            <xsl:value-of select="ns1:FORMULA_ID"/>
                          </ns5:FormulaID>
                          <ns5:LineNumber>
                            <xsl:value-of select="ns1:LINE_NO"/>
                          </ns5:LineNumber>
                          <ns5:ItemType>
                            <xsl:value-of select="ns1:ITEM_TYPE"/>
                          </ns5:ItemType>
                          <ns5:FormulaItemType>
                            <xsl:value-of select="ns1:FRM_ITEM_TYPE"/>
                          </ns5:FormulaItemType>
                          <ns5:ItemNumber>
                            <xsl:value-of select="ns1:ITEM_NUMBER"/>
                          </ns5:ItemNumber>
                          <xsl:if test="ns1:DESCRIPTION">
                            <ns5:Description>
                              <xsl:value-of select="ns1:DESCRIPTION"/>
                            </ns5:Description>
                          </xsl:if>
                          <xsl:if test="ns1:QUANTITY">
                            <ns5:Quantity>
                              <xsl:value-of select="ns1:QUANTITY"/>
                            </ns5:Quantity>
                          </xsl:if>
                          <ns5:ItemUOM>
                            <xsl:value-of select="ns1:ITEM_UOM"/>
                          </ns5:ItemUOM>
                          <ns5:YieldConsumptionType>
                            <xsl:value-of select="ns1:YIELD_CONSUMPTION_TYPE"/>
                          </ns5:YieldConsumptionType>
                          <ns5:ScrapFactor>
                            <xsl:value-of select="ns1:SCRAP_FACTOR"/>
                          </ns5:ScrapFactor>
                          <ns5:ScaleType>
                            <xsl:value-of select="ns1:SCALE_TYPE"/>
                          </ns5:ScaleType>
                          <ns5:ByProductType>
                            <xsl:value-of select="ns1:BYPRODUCT_TYPE"/>
                          </ns5:ByProductType>
                          <ns5:CostAllocation>
                            <xsl:value-of select="ns1:COST_ALLOCATION"/>
                          </ns5:CostAllocation>
                          <ns5:ScaleMultiple>
                            <xsl:value-of select="ns1:SCALE_MULTIPLE"/>
                          </ns5:ScaleMultiple>
                          <ns5:PhantomType>
                            <xsl:value-of select="ns1:PHANTOM_TYPE"/>
                          </ns5:PhantomType>
                          <ns5:ContributeToYield>
                            <xsl:value-of select="ns1:CONTRIBUTE_TO_YIELD"/>
                          </ns5:ContributeToYield>
                          <ns5:ContributeToStepQuantity>
                            <xsl:value-of select="ns1:CONTRIBUTE_TO_STEP_QTY"/>
                          </ns5:ContributeToStepQuantity>
                          <ns5:ScaleRoundingVariance>
                            <xsl:value-of select="ns1:SCALE_ROUNDING_VARIANCE"/>
                          </ns5:ScaleRoundingVariance>
                          <ns5:RoundingDirection>
                            <xsl:value-of select="ns1:ROUNDING_DIRECTION"/>
                          </ns5:RoundingDirection>
                          <ns5:Attribute>
                            <ns5:AttributeCategory>
                              <xsl:value-of select="ns1:ATTRIBUTE_CATEGORY"/>
                            </ns5:AttributeCategory>
                            <ns5:Attribute1>
                              <xsl:value-of select="ns1:ATTRIBUTE1"/>
                            </ns5:Attribute1>
                            <ns5:Attribute2>
                              <xsl:value-of select="ns1:ATTRIBUTE2"/>
                            </ns5:Attribute2>
                            <ns5:Attribute3>
                              <xsl:value-of select="ns1:ATTRIBUTE3"/>
                            </ns5:Attribute3>
                            <ns5:Attribute4>
                              <xsl:value-of select="ns1:ATTRIBUTE4"/>
                            </ns5:Attribute4>
                            <ns5:Attribute5>
                              <xsl:value-of select="ns1:ATTRIBUTE5"/>
                            </ns5:Attribute5>
                          </ns5:Attribute>
                        </ns5:FormulaDetails>
                      </xsl:if>
                    </xsl:for-each>
                  </ns5:ListOfFormulaDetails>
                </ns5:Formulas>
              </xsl:for-each>
            </ns5:ListOfFormulas>
            <!--
            <ns5:ListOfFormula>
              <xsl:for-each select="ns1:FORMULA_DTLS/ns1:FORMULA_DTLS_ITEM">
                <xsl:if test=".">
                  <ns5:Formulas>
                    <ns5:FormulaNumber>
                      <xsl:value-of select="ns1:FORMULA_NO"/>
                    </ns5:FormulaNumber>
                    <ns5:FormulaID>
                      <xsl:value-of select="ns1:FORMULA_ID"/>
                    </ns5:FormulaID>
                    <xsl:if test="ns1:DESCRIPTION">
                      <ns5:FormulaDescription>
                        <xsl:value-of select="ns1:DESCRIPTION"/>
                      </ns5:FormulaDescription>
                    </xsl:if>
                    <ns5:FormulaClass>
                      <xsl:value-of select="ns1:FORMULA_CLASS"/>
                    </ns5:FormulaClass>
                    <xsl:if test="ns1:COMMENTS">
                      <ns5:Comments>
                        <xsl:value-of select="ns1:COMMENTS"/>
                      </ns5:Comments>
                    </xsl:if>
                    <ns5:OrganizationCode>
                      <xsl:value-of select="ns1:ORGN_CODE"/>
                    </ns5:OrganizationCode>
                    <ns5:FormulaStatus>
                      <xsl:value-of select="ns1:FORMULA_STATUS"/>
                    </ns5:FormulaStatus>
                    <ns5:LineNumber>
                      <xsl:value-of select="ns1:LINE_NO"/>
                    </ns5:LineNumber>
                    <ns5:ItemNumber>
                      <xsl:value-of select="ns1:ITEM_NUMBER"/>
                    </ns5:ItemNumber>
                    <ns5:ItemUOM>
                      <xsl:value-of select="ns1:ITEM_UOM"/>
                    </ns5:ItemUOM>
                    <ns5:ConsumptionType>
                      <xsl:value-of select="ns1:YIELD_CONSUMPTION_TYPE"/>
                    </ns5:ConsumptionType>
                    <ns5:ScrapFactor>
                      <xsl:value-of select="ns1:SCRAP_FACTOR"/>
                    </ns5:ScrapFactor>
                    <ns5:ScaleType>
                      <xsl:value-of select="ns1:SCALE_TYPE"/>
                    </ns5:ScaleType>
                    <ns5:CostAllocation>
                      <xsl:value-of select="ns1:COST_ALLOCATION"/>
                    </ns5:CostAllocation>
                    <ns5:PhantomType>
                      <xsl:value-of select="ns1:PHANTOM_TYPE"/>
                    </ns5:PhantomType>
                    <ns5:ScaleMultiple>
                      <xsl:value-of select="ns1:SCALE_MULTIPLE"/>
                    </ns5:ScaleMultiple>
                    <ns5:ContributeToYield>
                      <xsl:value-of select="ns1:CONTRIBUTE_TO_YIELD"/>
                    </ns5:ContributeToYield>
                    <xsl:if test="ns1:QUANTITY">
                      <ns5:ContributeToStepQuantity>
                        <xsl:value-of select="ns1:QUANTITY"/>
                      </ns5:ContributeToStepQuantity>
                    </xsl:if>
                    <ns5:ScaleRoundingVariance>
                      <xsl:value-of select="ns1:SCALE_ROUNDING_VARIANCE"/>
                    </ns5:ScaleRoundingVariance>
                    <ns5:RoundingDirection>
                      <xsl:value-of select="ns1:ROUNDING_DIRECTION"/>
                    </ns5:RoundingDirection>
                    <ns5:Attribute>
                      <ns5:AttributeCategory>
                        <xsl:value-of select="ns1:ATTRIBUTE_CATEGORY"/>
                      </ns5:AttributeCategory>
                      <ns5:Attribute1>
                        <xsl:value-of select="ns1:ATTRIBUTE1"/>
                      </ns5:Attribute1>
                      <ns5:Attribute2>
                        <xsl:value-of select="ns1:ATTRIBUTE2"/>
                      </ns5:Attribute2>
                      <ns5:Attribute3>
                        <xsl:value-of select="ns1:ATTRIBUTE3"/>
                      </ns5:Attribute3>
                      <ns5:Attribute4>
                        <xsl:value-of select="ns1:ATTRIBUTE4"/>
                      </ns5:Attribute4>
                      <ns5:Attribute5>
                        <xsl:value-of select="ns1:ATTRIBUTE5"/>
                      </ns5:Attribute5>
                    </ns5:Attribute>
                    <ns5:DTLAttribute>
                      <ns5:DTLAttributeCategory>
                        <xsl:value-of select="ns1:DTLS_ATTR_CATEGORY"/>
                      </ns5:DTLAttributeCategory>
                      <ns5:DTLAttribute1>
                        <xsl:value-of select="ns1:DTLS_ATTRIBUTE1"/>
                      </ns5:DTLAttribute1>
                      <ns5:DTLAttribute2>
                        <xsl:value-of select="ns1:DTLS_ATTRIBUTE2"/>
                      </ns5:DTLAttribute2>
                      <ns5:DTLAttribute3>
                        <xsl:value-of select="ns1:DTLS_ATTRIBUTE3"/>
                      </ns5:DTLAttribute3>
                      <ns5:DTLAttribute4>
                        <xsl:value-of select="ns1:DTLS_ATTRIBUTE4"/>
                      </ns5:DTLAttribute4>
                      <ns5:DTLAttribute5>
                        <xsl:value-of select="ns1:DTLS_ATTRIBUTE5"/>
                      </ns5:DTLAttribute5>
                    </ns5:DTLAttribute>
                  </ns5:Formulas>
                </xsl:if>
              </xsl:for-each>
            </ns5:ListOfFormula>
            -->
            <ns5:ListOfRouting>
              <xsl:for-each select="ns1:ROUTING_DTLS/ns1:ROUTING_DTLS_ITEM">
                <ns5:Routings>
                  <ns5:RoutingNo>
                    <xsl:value-of select="ns1:ROUTING_NO"/>
                  </ns5:RoutingNo>
                  <ns5:RoutingID>
                    <xsl:value-of select="ns1:ROUTING_ID"/>
                  </ns5:RoutingID>
                  <ns5:RoutingVer>
                    <xsl:value-of select="ns1:ROUTING_VERS"/>
                  </ns5:RoutingVer>
                  <ns5:RoutingQty>
                    <xsl:value-of select="ns1:ROUTING_QTY"/>
                  </ns5:RoutingQty>
                  <ns5:ItemUOM>
                    <xsl:value-of select="ns1:ROUTING_UOM"/>
                  </ns5:ItemUOM>
                  <ns5:RoutingDesc>
                    <xsl:value-of select="ns1:ROUTING_DESC"/>
                  </ns5:RoutingDesc>
                  <ns5:OwnerOrgnCode>
                    <xsl:value-of select="ns1:ORGN_CODE"/>
                  </ns5:OwnerOrgnCode>
                  <ns5:RoutingClass>
                    <xsl:value-of select="ns1:ROUTING_CLASS"/>
                  </ns5:RoutingClass>
                  <ns5:EffectiveStartDate>
                    <xsl:value-of select="ns1:ROUT_VALID_FROM"/>
                  </ns5:EffectiveStartDate>
                  <ns5:EffectiveEndDate>
                    <xsl:value-of select="ns1:ROUT_VALID_TO"/>
                  </ns5:EffectiveEndDate>
                  <ns5:ProcessLoss>
                    <xsl:value-of select="ns1:PROCESS_LOSS"/>
                  </ns5:ProcessLoss>
                  <ns5:RoutingStatus>
                    <xsl:value-of select="ns1:ROUTING_STATUS"/>
                  </ns5:RoutingStatus>
                  <ns5:EnforceStepDependency>
                    <xsl:value-of select="ns1:ENFORCE_STEP_DEPENDENCY"/>
                  </ns5:EnforceStepDependency>
                  <ns5:RoutingstepNo>
                    <xsl:value-of select="ns1:ROUTINGSTEP_NO"/>
                  </ns5:RoutingstepNo>
                  <ns5:OperationNO/>
                  <ns5:OperationVER>
                    <xsl:value-of select="ns1:OPRN_DTLS/ns1:OPRN_DTLS_ITEM/ns1:OPRN_VERS"/>
                  </ns5:OperationVER>
                  <ns5:OperationID>
                    <xsl:value-of select="ns1:OPRN_ID"/>
                  </ns5:OperationID>
                  <ns5:StepQty>
                    <xsl:value-of select="ns1:STEP_QTY"/>
                  </ns5:StepQty>
                  <ns5:StepreleaseType>
                    <xsl:value-of select="ns1:STEP_RELEASE_TYPE"/>
                  </ns5:StepreleaseType>
                  <ns5:DepRoutingstepNo>
                    <xsl:value-of select="ns1:DEPENDENT_ROUTSTEP_NO"/>
                  </ns5:DepRoutingstepNo>
                  <ns5:DepType>
                    <xsl:value-of select="ns1:DEPENDENCY_TYPE"/>
                  </ns5:DepType>
                  <ns5:StandardDelay>
                    <xsl:value-of select="ns1:STANDARD_DELAY"/>
                  </ns5:StandardDelay>
                  <ns5:TransferQty>
                    <xsl:value-of select="ns1:TRANSFER_QTY"/>
                  </ns5:TransferQty>
                  <ns5:TransferPct>
                    <xsl:value-of select="ns1:TRANSFER_PCT"/>
                  </ns5:TransferPct>
                  <ns5:Attribute>
                    <ns5:AttributeCategory>
                      <xsl:value-of select="ns1:ATTRIBUTE_CATEGORY"/>
                    </ns5:AttributeCategory>
                    <ns5:Attribute1>
                      <xsl:value-of select="ns1:ATTRIBUTE1"/>
                    </ns5:Attribute1>
                    <ns5:Attribute2>
                      <xsl:value-of select="ns1:ATTRIBUTE2"/>
                    </ns5:Attribute2>
                    <ns5:Attribute3>
                      <xsl:value-of select="ns1:ATTRIBUTE3"/>
                    </ns5:Attribute3>
                    <ns5:Attribute4>
                      <xsl:value-of select="ns1:ATTRIBUTE4"/>
                    </ns5:Attribute4>
                    <ns5:Attribute5>
                      <xsl:value-of select="ns1:ATTRIBUTE5"/>
                    </ns5:Attribute5>
                    <ns5:Attribute6>
                      <xsl:value-of select="ns1:ATTRIBUTE6"/>
                    </ns5:Attribute6>
                    <ns5:Attribute7>
                      <xsl:value-of select="ns1:ATTRIBUTE7"/>
                    </ns5:Attribute7>
                    <ns5:Attribute8>
                      <xsl:value-of select="ns1:ATTRIBUTE8"/>
                    </ns5:Attribute8>
                    <ns5:Attribute9>
                      <xsl:value-of select="ns1:ATTRIBUTE9"/>
                    </ns5:Attribute9>
                    <ns5:Attribute10>
                      <xsl:value-of select="ns1:ATTRIBUTE10"/>
                    </ns5:Attribute10>
                  </ns5:Attribute>
                  <ns5:ListOfOperartion>
                    <xsl:for-each select="ns1:OPRN_DTLS/ns1:OPRN_DTLS_ITEM">
                      <!-- <xsl:if test=""> -->
                      <ns5:Operartions>
                        <ns5:OperationNumber>
                          <xsl:value-of select="ns1:OPRN_NO"/>
                        </ns5:OperationNumber>
                        <ns5:OperationID>
                          <xsl:value-of select="ns1:OPRN_ID"/>
                        </ns5:OperationID>
                        <ns5:OperationDescription>
                          <xsl:value-of select="ns1:OPRN_DESC"/>
                        </ns5:OperationDescription>
                        <ns5:OperationVersion>
                          <xsl:value-of select="ns1:OPRN_VERS"/>
                        </ns5:OperationVersion>
                        <ns5:ProcessQtyUOM>
                          <xsl:value-of select="ns1:PROCESS_QTY_UOM"/>
                        </ns5:ProcessQtyUOM>
                        <ns5:OperationClass>
                          <xsl:value-of select="ns1:OPRN_CLASS"/>
                        </ns5:OperationClass>
                        <ns5:ValidFrom>
                          <xsl:value-of select="ns1:OPRN_VALID_FROM"/>
                        </ns5:ValidFrom>
                        <ns5:ValidTo>
                          <xsl:value-of select="ns1:OPRN_VALID_TO"/>
                        </ns5:ValidTo>
                        <xsl:if test="ns1:OPRN_STATUS">
                          <ns5:Status>
                            <xsl:value-of select="ns1:OPRN_STATUS"/>
                          </ns5:Status>
                        </xsl:if>
                        <ns5:OwnerOrganization>
                          <xsl:value-of select="ns1:ORGN_CODE"/>
                        </ns5:OwnerOrganization>
                        <ns5:MinimumTransferQty>
                          <xsl:value-of select="ns1:MINIMUM_TRANSFER_QTY"/>
                        </ns5:MinimumTransferQty>
                        <xsl:if test="ns1:ACTIVITY">
                          <ns5:Activity>
                            <xsl:value-of select="ns1:ACTIVITY"/>
                          </ns5:Activity>
                        </xsl:if>
                        <xsl:if test="ns1:ACTIVITY_FACTOR">
                          <ns5:ActivityFactor>
                            <xsl:value-of select="ns1:ACTIVITY_FACTOR"/>
                          </ns5:ActivityFactor>
                        </xsl:if>
                        <ns5:SequenceDependency>
                          <xsl:value-of select="ns1:SEQ_DEPENDENT_IND"/>
                        </ns5:SequenceDependency>
                        <ns5:OffsetInterval>
                          <xsl:value-of select="ns1:ACTIVITY_OFFSET_INTERVAL"/>
                        </ns5:OffsetInterval>
                        <ns5:Breakable>
                          <xsl:value-of select="ns1:BREAK_IND"/>
                        </ns5:Breakable>
                        <ns5:MaxBreak>
                          <xsl:value-of select="ns1:MAX_BREAK"/>
                        </ns5:MaxBreak>
                        <ns5:MaterialScheduled>
                          <xsl:value-of select="ns1:MATERIAL_SCHEDULED"/>
                        </ns5:MaterialScheduled>
                        <xsl:if test="ns1:RESOURCES">
                          <ns5:Resources>
                            <xsl:value-of select="ns1:RESOURCES"/>
                          </ns5:Resources>
                        </xsl:if>
                        <ns5:ResourceUsage>
                          <xsl:value-of select="ns1:RESOURCE_USUAGE"/>
                        </ns5:ResourceUsage>
                        <ns5:ResourceCount>
                          <xsl:value-of select="ns1:RESOURCE_CNT"/>
                        </ns5:ResourceCount>
                        <ns5:ProcessQuantity>
                          <xsl:value-of select="ns1:PROCESS_QTY"/>
                        </ns5:ProcessQuantity>
                        <ns5:PlanType>
                          <xsl:value-of select="ns1:PLAN_TYPE"/>
                        </ns5:PlanType>
                        <ns5:ScaleType>
                          <xsl:value-of select="ns1:SCALE_TYPE"/>
                        </ns5:ScaleType>
                        <ns5:OperationAttributeS>
                          <ns5:OperationAttributeCategory>
                            <xsl:value-of select="ns1:OPRN_ATTR_CATEGORY"/>
                          </ns5:OperationAttributeCategory>
                          <ns5:OperationAttribute1>
                            <xsl:value-of select="ns1:OPRN_ATTRIBUTE1"/>
                          </ns5:OperationAttribute1>
                          <ns5:OperationAttribute2>
                            <xsl:value-of select="ns1:OPRN_ATTRIBUTE2"/>
                          </ns5:OperationAttribute2>
                          <ns5:OperationAttribute3>
                            <xsl:value-of select="ns1:OPRN_ATTRIBUTE3"/>
                          </ns5:OperationAttribute3>
                          <ns5:OperationAttribute4>
                            <xsl:value-of select="ns1:OPRN_ATTRIBUTE4"/>
                          </ns5:OperationAttribute4>
                          <ns5:OperationAttribute5>
                            <xsl:value-of select="ns1:OPRN_ATTRIBUTE5"/>
                          </ns5:OperationAttribute5>
                        </ns5:OperationAttributeS>
                        <ns5:ActivityAttributeS>
                          <ns5:ActivityAttributeCategory>
                            <xsl:value-of select="ns1:ACTIVITY_ATTR_CATEGORY"/>
                          </ns5:ActivityAttributeCategory>
                          <ns5:ActivityAttribute1>
                            <xsl:value-of select="ns1:ACTIVITY_ATTRIBUTE1"/>
                          </ns5:ActivityAttribute1>
                          <ns5:ActivityAttribute2>
                            <xsl:value-of select="ns1:ACTIVITY_ATTRIBUTE2"/>
                          </ns5:ActivityAttribute2>
                          <ns5:ActivityAttribute3>
                            <xsl:value-of select="ns1:ACTIVITY_ATTRIBUTE3"/>
                          </ns5:ActivityAttribute3>
                          <ns5:ActivityAttribute4>
                            <xsl:value-of select="ns1:ACTIVITY_ATTRIBUTE4"/>
                          </ns5:ActivityAttribute4>
                          <ns5:ActivityAttribute5>
                            <xsl:value-of select="ns1:ACTIVITY_ATTRIBUTE5"/>
                          </ns5:ActivityAttribute5>
                        </ns5:ActivityAttributeS>
                        <ns5:ResourceAttributeS>
                          <ns5:ResourceAttributeCategory>
                            <xsl:value-of select="ns1:RSRC_ATTR_CATEGORY"/>
                          </ns5:ResourceAttributeCategory>
                          <ns5:ResourceAttribute1>
                            <xsl:value-of select="ns1:RSRC_ATTRIBUTE1"/>
                          </ns5:ResourceAttribute1>
                          <ns5:ResourceAttribute2>
                            <xsl:value-of select="ns1:RSRC_ATTRIBUTE2"/>
                          </ns5:ResourceAttribute2>
                          <ns5:ResourceAttribute3>
                            <xsl:value-of select="ns1:RSRC_ATTRIBUTE3"/>
                          </ns5:ResourceAttribute3>
                          <ns5:ResourceAttribute4>
                            <xsl:value-of select="ns1:RSRC_ATTRIBUTE4"/>
                          </ns5:ResourceAttribute4>
                          <ns5:ResourceAttribute5>
                            <xsl:value-of select="ns1:RSRC_ATTRIBUTE5"/>
                          </ns5:ResourceAttribute5>
                        </ns5:ResourceAttributeS>
                      </ns5:Operartions>
                      <!-- </xsl:if> -->
                    </xsl:for-each>
                  </ns5:ListOfOperartion>
                </ns5:Routings>
              </xsl:for-each>
            </ns5:ListOfRouting>
            <ns5:ListOfRecipeVRS>
              <xsl:for-each select="ns1:RECIPE_VR/ns1:RECIPE_VR_ITEM">
                <xsl:if test=".">
                  <ns5:RecipeVRS>
                    <ns5:RecipeNumber>
                      <xsl:value-of select="../../ns1:RECIPE_NO"/>
                    </ns5:RecipeNumber>
                    <ns5:RecipeVersion>
                      <xsl:value-of select="../../ns1:RECIPE_VERS"/>
                    </ns5:RecipeVersion>
                    <ns5:RecipeID>
                      <xsl:value-of select="ns1:RECIPE_ID"/>
                    </ns5:RecipeID>
                    <ns5:RecipeVRID>
                      <xsl:value-of select="ns1:RECIPE_VR_ID"/>
                    </ns5:RecipeVRID>
                    <ns5:OrganizationCode>
                      <xsl:value-of select="ns1:ORGN_CODE"/>
                    </ns5:OrganizationCode>
                    <xsl:if test="ns1:PRODUCT">
                      <ns5:Product>
                        <xsl:value-of select="ns1:PRODUCT"/>
                      </ns5:Product>
                    </xsl:if>
                    <ns5:RecipeUse>
                      <xsl:value-of select="ns1:RECIPE_USE"/>
                    </ns5:RecipeUse>
                    <xsl:if test="ns1:PREFERENCE">
                      <ns5:Preference>
                        <xsl:value-of select="ns1:PREFERENCE"/>
                      </ns5:Preference>
                    </xsl:if>
                    <ns5:Startdate>
                      <xsl:value-of select="ns1:START_DATE"/>
                    </ns5:Startdate>
                    <ns5:EndDate>
                      <xsl:value-of select="ns1:END_DATE"/>
                    </ns5:EndDate>
                    <ns5:MinimumQuantity>
                      <xsl:value-of select="ns1:MINIMUM_QTY"/>
                    </ns5:MinimumQuantity>
                    <ns5:MaximumQuantity>
                      <xsl:value-of select="ns1:MAXIMUM_QTY"/>
                    </ns5:MaximumQuantity>
                    <ns5:StandardQuantity>
                      <xsl:value-of select="ns1:STANDARD_QTY"/>
                    </ns5:StandardQuantity>
                    <ns5:ItemUOM>
                      <xsl:value-of select="ns1:QTY_UOM"/>
                    </ns5:ItemUOM>
                    <ns5:InventoryMinimumQuantity>
                      <xsl:value-of select="ns1:INV_MIN_QTY"/>
                    </ns5:InventoryMinimumQuantity>
                    <ns5:InventoryMaximumQuantity>
                      <xsl:value-of select="ns1:INV_MAX_QTY"/>
                    </ns5:InventoryMaximumQuantity>
                    <ns5:ValidityRuleStatus>
                      <xsl:value-of select="ns1:VR_STATUS"/>
                    </ns5:ValidityRuleStatus>
                    <ns5:Attribute>
                      <ns5:AttributeCategory>
                        <xsl:value-of select="ns1:ATTRIBUTE_CATEGORY"/>
                      </ns5:AttributeCategory>
                      <ns5:Attribute1>
                        <xsl:value-of select="ns1:ATTRIBUTE1"/>
                      </ns5:Attribute1>
                      <ns5:Attribute2>
                        <xsl:value-of select="ns1:ATTRIBUTE2"/>
                      </ns5:Attribute2>
                      <ns5:Attribute3>
                        <xsl:value-of select="ns1:ATTRIBUTE3"/>
                      </ns5:Attribute3>
                      <ns5:Attribute4>
                        <xsl:value-of select="ns1:ATTRIBUTE4"/>
                      </ns5:Attribute4>
                      <ns5:Attribute5>
                        <xsl:value-of select="ns1:ATTRIBUTE5"/>
                      </ns5:Attribute5>
                    </ns5:Attribute>
                  </ns5:RecipeVRS>
                </xsl:if>
              </xsl:for-each>
            </ns5:ListOfRecipeVRS>
          </ns5:ListOfRecipe>
        </ns5:ProductStructureDetails>
      </xsl:for-each>
    </ns0:QueryProductStructureAddRs>
  </xsl:template>
</xsl:stylesheet>
