<wsdl:definitions
     name="JMS_ConsumeEIAErrorTopic"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/NucorSOAMacBranches/EIAJMSErroHandlingBPELProcess/JMS_ConsumeEIAErrorTopic"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/NucorSOAMacBranches/EIAJMSErroHandlingBPELProcess/JMS_ConsumeEIAErrorTopic"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://xmlns.eia.com/EO/Common/1.0"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="Consume_Message_plt" >
    <plt:role name="Consume_Message_role" >
      <plt:portType name="tns:Consume_Message_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.eia.com/EO/Common/1.0" schemaLocation="oramds:/apps/EIAMetadata/EO/common/Common.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Consume_Message_msg">
        <wsdl:part name="body" element="imp1:Fault"/>
    </wsdl:message>
    <wsdl:portType name="Consume_Message_ptt">
        <wsdl:operation name="Consume_Message">
            <wsdl:input message="tns:Consume_Message_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
