<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/O2C/TripsAM/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_Pick_Del_Confirmation"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/O2C/TripsAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns2="http://schemas.oracle.com/service/bpel/common"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:ns7="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/I028NewDesign/NUC_SubscribeTrips_CP_ABS/JMS_SubscribeTrips"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns9="http://xmlns.oracle.com/pcbpel/adapter/db/I028NewDesign/NUC_SubscribeTrips_CP_ABS/DB_Insert_Pick_Del_Confirmation">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_SubscribeTrips.wsdl"/>
        <oracle-xsl-mapper:rootElement name="TripsAddRq" namespace="http://xmlns.eia.com/AO/EBiz/O2C/TripsAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Insert_Pick_Del_Confirmation.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OperationCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_Pick_Del_Confirmation"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED DEC 09 07:52:20 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:OperationCollection>
      <xsl:for-each select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips[ns3:attribute2 = 2100]">
        <xsl:for-each select="ns3:WshTripStps/ns3:Wsh_TripStps[ns3:stopType = 'Drop-off']">
          <xsl:variable name="signingDate">
            <xsl:value-of select="concat(substring(/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:WshTripStps/ns3:Wsh_TripStps[ns3:stopType = 'Picked-up' or ns3:stopType = 'Pick-up']/ns3:attribute6,1,4),'-',substring(/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:WshTripStps/ns3:Wsh_TripStps[ns3:stopType = 'Picked-up' or ns3:stopType = 'Pick-up']/ns3:attribute6,6,2),'-',substring(/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:WshTripStps/ns3:Wsh_TripStps[ns3:stopType = 'Picked-up' or ns3:stopType = 'Pick-up']/ns3:attribute6,9,2),'T',substring(/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:WshTripStps/ns3:Wsh_TripStps[ns3:stopType = 'Picked-up' or ns3:stopType = 'Pick-up']/ns3:attribute6,12,8))"/>
          </xsl:variable>
          <!-- <a>
        <xsl:value-of select ="$signingDate"/>
        </a>-->
          <tns:Operation>
            <tns:operationId>
              <xsl:value-of select="oraext:sequence-next-val('OPERATION_SEQ','jdbc/omsi')"/>
            </tns:operationId>
            <tns:operation>
              <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:attribute2"/>
            </tns:operation>
            <tns:isReady>1</tns:isReady>
            <tns:isRead>0</tns:isRead>
            <tns:resultCode>0</tns:resultCode>
            <tns:creationTimestamp>
              <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:creationTimestamp>
            <!--<tns:pickupConfirmationCollection>
              <tns:PickupConfirmation>
                <tns:clientKey1>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:name"/>
                </tns:clientKey1>
                <tns:clientKey2>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:tripId"/>
                </tns:clientKey2>
                <tns:clientKey4>EBS</tns:clientKey4>
                <tns:stopSequenceNumber>
                  <xsl:value-of select="ns3:stopSequenceNumber"/>
                </tns:stopSequenceNumber>
                <tns:signingDate> <xsl:value-of select="xp20:current-date ( )"/></tns:signingDate>
                <tns:notes>12</tns:notes>
              </tns:PickupConfirmation>
            </tns:pickupConfirmationCollection>-->
            <tns:deliveryConfirmationCollection>
              <tns:DeliveryConfirmation>
                <tns:clientKey1>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:clientKey1"/>
                </tns:clientKey1>
                <tns:clientKey2>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:tripId"/>
                </tns:clientKey2>
                <tns:clientKey3>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:name"/>
                </tns:clientKey3>
                <tns:clientKey4>EBS</tns:clientKey4>
                <tns:stopSequenceNumber>
                  <xsl:value-of select="ns3:stopSequenceNumber"/>
                </tns:stopSequenceNumber>
                <tns:signer>12</tns:signer>
                <!-- <xsl:choose>
                  <xsl:when test="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:freightTermsCode = &quot;COL&quot; or /ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:freightTermsCode = &quot;CPU&quot; or /ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:freightTermsCode = &quot;COL&quot; or /ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:freightTermsCode = &quot;CPU&quot; or /ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:freightTermsCode = &quot;COL&quot; or /ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:freightTermsCode = &quot;CPU&quot;">
                <tns:signingDate>
                  <xsl:value-of select="xp20:add-dayTimeDuration-to-dateTime (xsd:dateTime($signingDate), xsd:dayTimeDuration('PT1M'))"/>
                </tns:signingDate>
                </xsl:when>
                 <xsl:otherwise>-->
                <tns:signingDate>
                  <xsl:value-of select="xp20:add-dayTimeDuration-to-dateTime (xsd:dateTime($signingDate), xsd:dayTimeDuration('PT1M'))"/>
                </tns:signingDate>
                <!-- </xsl:otherwise>
                </xsl:choose>-->
              </tns:DeliveryConfirmation>
            </tns:deliveryConfirmationCollection>
          </tns:Operation>
        </xsl:for-each>
      </xsl:for-each>
      <xsl:for-each select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips[ns3:attribute2 = 2200]">
        <xsl:for-each select="ns3:WshTripStps/ns3:Wsh_TripStps[ns3:stopType = 'Picked-up' or ns3:stopType = 'Pick-up']">
          <tns:Operation>
            <tns:operationId>
              <xsl:value-of select="oraext:sequence-next-val('OPERATION_SEQ','jdbc/omsi')"/>
            </tns:operationId>
            <tns:operation>
              <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:attribute2"/>
            </tns:operation>
            <tns:isReady>1</tns:isReady>
            <tns:isRead>0</tns:isRead>
            <tns:resultCode>0</tns:resultCode>
            <tns:creationTimestamp>
              <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:creationTimestamp>
            <!--<tns:deliveryConfirmationCollection>
              <tns:DeliveryConfirmation>
                <tns:clientKey1>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:name"/>
                </tns:clientKey1>
                <tns:clientKey2>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:tripId"/>
                </tns:clientKey2>
                <tns:clientKey4>EBS</tns:clientKey4>
                <tns:stopSequenceNumber>
                  <xsl:value-of select="ns3:stopSequenceNumber"/>
                </tns:stopSequenceNumber>
                <tns:signer>12</tns:signer>
                <tns:signingDate>
                  <xsl:value-of select="xp20:current-dateTime ( )"/>
                </tns:signingDate>
              </tns:DeliveryConfirmation>
            </tns:deliveryConfirmationCollection>-->
            <tns:pickupConfirmationCollection>
              <tns:PickupConfirmation>
                <tns:clientKey1>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:clientKey1"/>
                </tns:clientKey1>
                <tns:clientKey2>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:tripId"/>
                </tns:clientKey2>
                <tns:clientKey3>
                  <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:name"/>
                </tns:clientKey3>
                <tns:clientKey4>EBS</tns:clientKey4>
                <tns:stopSequenceNumber>
                  <xsl:value-of select="ns3:stopSequenceNumber"/>
                </tns:stopSequenceNumber>
                <tns:signingDate>
                  <xsl:value-of select="concat(substring(ns3:attribute6,1,4),'-',substring(ns3:attribute6,6,2),'-',substring(ns3:attribute6,9,2),'T',substring(ns3:attribute6,12,8))"/>
                </tns:signingDate>
              </tns:PickupConfirmation>
            </tns:pickupConfirmationCollection>
          </tns:Operation>
        </xsl:for-each>
      </xsl:for-each>
    </tns:OperationCollection>
  </xsl:template>
</xsl:stylesheet>
