<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://www.example.org"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns="http://xmlns.eia.com/ABS/EBiz/ReceiptABS/1.0"
                xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:cor="http:/xmlns.eia.com/Implementation/ABF/NSNE_ASNQualityResults_Suppliers_EBS_ABF/ASNQualityResults_Suppliers/1.0/correlationset"
                xmlns:ns3="http://xmlns.eia.com/EDN/1.0/Event"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/I109byManish/NSNE_ASNQualityResults_Suppliers_EBS_ABF/FTP_ReadASNSupplier"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http:/xmlns.eia.com/Implementation/ABS/NUC_NUC_EBizQualityResults_ABS/QualityResults/1.0"
                xmlns:ns4="http:/xmlns.eia.com/Implementation/ABS/NUC_EBizLot_ABS/EBizLotABS/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns10="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns13="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns8="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns12="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadASNSupplier.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadASNSupplier.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Envelope" namespace="http://www.example.org"/>
        <oracle-xsl-mapper:param name="Receive_ASN_Suppliers_Get_InputVariable.body"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JUN 28 06:03:55 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="Receive_ASN_Suppliers_Get_InputVariable.body"/>
  <xsl:template match="/">
    <tns:QualityResultsAddRq>
      <ns8:GmdResultsPub>
        <xsl:for-each-group select="/ns0:parameters/ns0:item" group-by="ns0:value">
          <xsl:variable name="currentLotNum">
            <xsl:value-of select="current-grouping-key()"/>
          </xsl:variable>
          <xsl:variable name="currentBundle">
            <xsl:value-of select="./ns0:name"/>
          </xsl:variable>
          <ns8:GmdResultPub>
            <ns8:LotNo>
              <xsl:value-of select="$currentLotNum"/>
            </ns8:LotNo>
            <ns8:Test_results>
              <xsl:for-each select="$Receive_ASN_Suppliers_Get_InputVariable.body/Envelope/PropertyTestSets/PropertyTestSet[Bundles/BundleNum = $currentBundle]/Jominy/JominyTestPoint">
                <xsl:variable name="rossCode">
                  <xsl:value-of select="normalize-space(@Dist)"/>
                </xsl:variable>
                <xsl:variable name="simulated">
                  <xsl:value-of select="$Receive_ASN_Suppliers_Get_InputVariable.body/Envelope/PropertyTestSets/PropertyTestSet[Bundles/BundleNum = $currentBundle]/Jominy/@Simulated"/>
                </xsl:variable>
                <!-- Create string JominyTestPoint Dist=1 Simulated=0 to look-up values from DVM -->
                <ns8:Test_results>
                  <ns8:TestCode>
                    <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE',concat('JominyTestPoint Dist=',$rossCode,' Simulated=',$simulated),'EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                  </ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="normalize-space(.)"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:for-each>
              <xsl:for-each select="$Receive_ASN_Suppliers_Get_InputVariable.body/Envelope/PropertyTestSets/PropertyTestSet[Bundles/BundleNum = $currentBundle]/Inclusions/Inclusion">
                <xsl:variable name="typeResult">
                  <xsl:value-of select="concat(@Type,@Result)"/>
                </xsl:variable>
                <ns8:Test_results>
                  <ns8:TestCode>
                    <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE',$typeResult,'EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                  </ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="normalize-space(.)"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:for-each>
              <xsl:for-each select="$Receive_ASN_Suppliers_Get_InputVariable.body/Envelope/PropertyTestSets/PropertyTestSet[Bundles/BundleNum = $currentBundle]">
                <xsl:if test="Elongation">
                  <xsl:variable name="elong28">
                    <xsl:value-of select="concat('ElongationGageLen',Elongation/@GageLen)"/>
                  </xsl:variable>
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE',$elong28,'EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(Elongation)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>
                <!-- <xsl:if test="&quot;Elongation&quot; and &quot;@GageLen =8&quot;">
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE','ElongationGageLen8','EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(Elongation[@GageLen=8])"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>-->
                <xsl:if test="Hardness">
                  <ns8:Test_results>
                    <xsl:variable name="hardnessRockwell">
                      <xsl:value-of select="concat('Hardness',Hardness/@Scale)"/>
                    </xsl:variable>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE',$hardnessRockwell,'EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(Hardness)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>
                <xsl:if test="GrainSize">
                  <xsl:variable name="grainSizeType">
                    <xsl:value-of select="concat('GrainSize Type=',GrainSize/@Type)"/>
                  </xsl:variable>
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE',$grainSizeType,'EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(GrainSize)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>
                <xsl:if test="ReductionRatio">
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE','ReductionRatio','EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(ReductionRatio)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>
                <xsl:if test="DI">
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE','DI','EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(DI)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>
                <xsl:if test="ReductionInArea">
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE','ReductionInArea','EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(ReductionInArea)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>
                <xsl:if test="Yield">
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE','Yield','EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(Yield)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>
                <xsl:if test="Tensile">
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE','Tensile','EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(Tensile)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>				
				<xsl:if test="GrainPractice">
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE','GrainPractice','EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(GrainPractice)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if>				
                <!--xsl:if test="Elongation">
                  <ns8:Test_results>
                    <ns8:TestCode>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/LEGACY_EBS_TEST_CODE_MAP.dvm','LEGACY_TEST_CODE','ElongationGageLen2','EBS_TEST_CODE','','TEST_TYPE','Physical','SYSTEM','CFNE')"/>
                    </ns8:TestCode>
                    <ns8:Tester>SOAUSER</ns8:Tester>
                    <ns8:ResultValue>
                      <xsl:value-of select="normalize-space(Elongation)"/>
                    </ns8:ResultValue>
                    <ns8:ResultDate>
                      <xsl:value-of select="xp20:current-date ( )"/>
                    </ns8:ResultDate>
                  </ns8:Test_results>
                </xsl:if-->
              </xsl:for-each>
            </ns8:Test_results>
          </ns8:GmdResultPub>
        </xsl:for-each-group>
      </ns8:GmdResultsPub>
    </tns:QualityResultsAddRq>
  </xsl:template>
</xsl:stylesheet>
