<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://xmlns.eia.com/AM/EBiz/P2P/LotAM/1.0"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/P2P/LpnAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns3="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABS/NUC_NUC_EBizQualityResults_ABS/QualityResults/1.0"
                xmlns:ns10="http:/xmlns.eia.com/Implementation/ABS/NUC_EBizLPN_ABS/EBizLPNABS/1.0"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/LpnABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateLpnResp" namespace="http://xmlns.eia.com/AM/EBiz/P2P/LotAM/1.0"/>
        <oracle-xsl-mapper:param name="InvokeCreateLPN_OutputVariable.payload"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
        <oracle-xsl-mapper:param name="GetPropertyTestSetsPerHeatNum.payload"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED JUN 29 06:21:07 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="InvokeCreateLPN_OutputVariable.payload"/>
  <xsl:param name="GetPropertyTestSetsPerHeatNum.payload"/>
  <xsl:template match="/">
    <ns0:QualityResultsAddRq>
      <ns9:HeaderRq>
        <ns9:TransactionRequestID>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:TransactionRequestID"/>
        </ns9:TransactionRequestID>
        <ns9:Language>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:Language"/>
        </ns9:Language>
        <ns9:ComponentID>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:ComponentID"/>
        </ns9:ComponentID>
        <ns9:ServiceName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:ServiceName"/>
        </ns9:ServiceName>
        <ns9:TransactionIDREF>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:TransactionIDREF"/>
        </ns9:TransactionIDREF>
        <ns9:TransactionName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:TransactionName"/>
        </ns9:TransactionName>
        <ns9:FileName/>
        <ns9:Source>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:Source"/>
        </ns9:Source>
        <ns9:Target>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:Target"/>
        </ns9:Target>
        <ns9:MillName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns9:HeaderRq/ns9:MillName"/>
        </ns9:MillName>
      </ns9:HeaderRq>
      <ns0:AppsContext>
        <ns7:UserName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns0:AppsContext/ns7:UserName"/>
        </ns7:UserName>
        <ns7:UserId>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns0:AppsContext/ns7:UserId"/>
        </ns7:UserId>
        <ns7:ResponsibilityName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns0:AppsContext/ns7:ResponsibilityName"/>
        </ns7:ResponsibilityName>
        <ns7:OrgId>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns0:AppsContext/ns7:OrgId"/>
        </ns7:OrgId>
      </ns0:AppsContext>
      <ns4:GmdResultsPub>
        <xsl:for-each select="/ns0:QualityResultsAddRq/ns4:GmdResultsPub/ns4:GmdResultPub">
          <xsl:variable name="LpnNo" select="ns4:LpnNO"/>
          <xsl:variable name="LotNo" select="ns4:LotNo"/>
          <ns4:GmdResultPub>
            <ns4:TxnID>
              <xsl:value-of select="ns4:TxnID"/>
            </ns4:TxnID>
            <ns4:OrganizationId>
              <xsl:value-of select="ns4:OrganizationId"/>
            </ns4:OrganizationId>
            <ns4:SampleSource>
              <xsl:value-of select="ns4:SampleSource"/>
            </ns4:SampleSource>
            <ns4:item_id>
              <xsl:value-of select="ns4:item_id"/>
            </ns4:item_id>
            <ns4:item_no>
              <xsl:value-of select="ns4:item_no"/>
            </ns4:item_no>
            <ns4:ParentLotNO>
              <xsl:value-of select="ns4:ParentLotNO"/>
            </ns4:ParentLotNO>
            <ns4:LotNo>
              <xsl:value-of select="ns4:LotNo"/>
            </ns4:LotNo>
            <ns4:LpnNO>
              <xsl:value-of select="$InvokeCreateLPN_OutputVariable.payload/ns1:CreateLpnResp/ns11:CreateLpnResp/ns11:LpnStatus/ns11:LpnStatusItem[ns11:BUNDLE_NUM = $LpnNo]/ns11:LPN_NUMBER"/>
            </ns4:LpnNO>
            <ns4:SampleQTY>
              <xsl:value-of select="ns4:SampleQTY"/>
            </ns4:SampleQTY>
            <ns4:SampleQtyUnitOfMeasure>
              <xsl:value-of select="ns4:SampleQtyUnitOfMeasure"/>
            </ns4:SampleQtyUnitOfMeasure>
            <ns4:dateDrawn>
              <xsl:value-of select="ns4:dateDrawn"/>
            </ns4:dateDrawn>
            <ns4:Sampler>
              <xsl:value-of select="ns4:Sampler"/>
            </ns4:Sampler>
            <ns4:Test_results>
              <xsl:for-each select="ns4:Test_results/ns4:Test_results">
                <ns4:Test_results>
                  <ns4:TestCode>
                    <xsl:value-of select="ns4:TestCode"/>
                  </ns4:TestCode>
                  <ns4:Tester>
                    <xsl:value-of select="ns4:Tester"/>
                  </ns4:Tester>
                  <ns4:ResultValue>
                    <xsl:value-of select="ns4:ResultValue"/>
                  </ns4:ResultValue>
                  <ns4:ResultDate>
                    <xsl:value-of select="ns4:ResultDate"/>
                  </ns4:ResultDate>
                </ns4:Test_results>
              </xsl:for-each>
              <xsl:for-each select="$GetPropertyTestSetsPerHeatNum.payload/ns0:QualityResultsAddRq/ns4:GmdResultsPub/ns4:GmdResultPub[ns4:LotNo = $LotNo]/ns4:Test_results/ns4:Test_results">
                <ns4:Test_results>
                  <ns4:TestCode>
                    <xsl:value-of select="ns4:TestCode"/>
                  </ns4:TestCode>
                  <ns4:Tester>
                    <xsl:value-of select="ns4:Tester"/>
                  </ns4:Tester>
                  <ns4:ResultValue>
                    <xsl:value-of select="ns4:ResultValue"/>
                  </ns4:ResultValue>
                  <ns4:ResultDate>
                    <xsl:value-of select="ns4:ResultDate"/>
                  </ns4:ResultDate>
                </ns4:Test_results>
              </xsl:for-each>
            </ns4:Test_results>
          </ns4:GmdResultPub>
        </xsl:for-each>
      </ns4:GmdResultsPub>
    </ns0:QualityResultsAddRq>
  </xsl:template>
</xsl:stylesheet>
