<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://www.example.org" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns3="http://schemas.oracle.com/service/bpel/common"
                xmlns:ns="http://xmlns.eia.com/ABS/EBiz/ReceiptABS/1.0"
                xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:cor="http:/xmlns.eia.com/Implementation/ABF/NSNE_ASNQualityResults_Suppliers_EBS_ABF/ASNQualityResults_Suppliers/1.0/correlationset"
                xmlns:ns2="http://xmlns.eia.com/EDN/1.0/Event"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/ftp/I109byManish/NSNE_ASNQualityResults_Suppliers_EBS_ABF/FTP_ReadASNSupplier"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptAO/1.0"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:ns14="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns21="http://xmlns.eia.com/AO/EBiz/common/CategoryAO/1.0"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns9="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns17="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns16="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns15="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns19="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0"
                xmlns:ns18="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns20="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadASNSupplier.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Envelope" namespace="http://www.example.org"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/ReceiptABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateReceiptRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JAN 19 06:36:02 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CreateReceiptRequestMessage>
      <ns12:HeaderRq>
        <ns12:TransactionRequestID></ns12:TransactionRequestID>
        <ns12:Language></ns12:Language>
        <ns12:ComponentID></ns12:ComponentID>
        <ns12:ServiceName></ns12:ServiceName>
        <ns12:TransactionIDREF></ns12:TransactionIDREF>
        <ns12:TransactionName></ns12:TransactionName>
        <ns12:Source></ns12:Source>
        <ns12:Target></ns12:Target>
      </ns12:HeaderRq>
      <tns:AppsContext>
        <ns13:UserName></ns13:UserName>
        <!--<ns13:UserId>1906</ns13:UserId>-->
        <ns13:ResponsibilityName></ns13:ResponsibilityName>
        <ns13:OrgId></ns13:OrgId>
      </tns:AppsContext>
      <tns:Receipt>
        <ns8:BasicReceipt>
          <ns8:IndentfierID>1</ns8:IndentfierID>
         <!-- <ns8:ReceiptNumber>
            <xsl:value-of select="/Envelope/Waybills/Waybill/WaybillNum"/>
          </ns8:ReceiptNumber>-->
          <ns8:ShipmentNumber>
            <xsl:value-of select="/Envelope/Waybills/Waybill/WaybillNum"/>
          </ns8:ShipmentNumber>
          <ns8:BillOfLAdding>
            <xsl:value-of select="/Envelope/Waybills/Waybill/WaybillNum"/>
          </ns8:BillOfLAdding>
        </ns8:BasicReceipt>
        <!-- <ns8:OperatingUnit>1</ns8:OperatingUnit>-->
         <ns8:Asntype></ns8:Asntype>
         <ns8:Autotransactcode>RECEIVE</ns8:Autotransactcode>
        <ns8:Carriermethod>
          <xsl:value-of select="/Envelope/FreightInfo/ShipMode"/>
        </ns8:Carriermethod>
        <!--<ns8:Createdby>-1</ns8:Createdby>-->
        <ns8:Expectedreceiptdate>  <xsl:value-of select="xp20:add-dayTimeDuration-to-dateTime (/Envelope/FreightInfo/ShipDate, 'P1DT0H0M' )"/></ns8:Expectedreceiptdate>
        <ns8:Freightterms>
          <xsl:value-of select="/Envelope/FreightInfo/FreightTerm"/>
        </ns8:Freightterms>
        <ns8:Grossweight>
          <xsl:value-of select="sum(Envelope/Waybills/Waybill/WaybillLines/WaybillLine/LineWgtTtl)"/>
        </ns8:Grossweight>
      <ns8:Groupid>AssignLater</ns8:Groupid>

        <ns8:Lastupdatedby>-1</ns8:Lastupdatedby>
        <ns8:Lastupdatedate> <xsl:value-of select="xp20:current-date()"/></ns8:Lastupdatedate>
        <ns8:Netweight>
          <xsl:value-of select="sum(Envelope/Waybills/Waybill/WaybillLines/WaybillLine/LineWgtTtl)"/>
        </ns8:Netweight>
        <ns8:Orgid>ORG_ID</ns8:Orgid>
        <ns8:Processingstatuscode>PENDING</ns8:Processingstatuscode>
         <ns8:Receiptsourcecode>VENDOR</ns8:Receiptsourcecode>
         <ns8:Shippeddate><xsl:value-of select="/Envelope/FreightInfo/ShipDate"/></ns8:Shippeddate>
        <ns8:Transactiontype>NEW</ns8:Transactiontype>
        <ns8:Vendorid>Vendor_Id</ns8:Vendorid> 
  <ns8:Vendorsiteid>Vendor_Site_Id</ns8:Vendorsiteid> 

        <ns8:ListOfTransactions>
          <xsl:for-each select="/Envelope/Waybills/Waybill/WaybillLines/WaybillLine">
           <xsl:variable name="lastIndexE" select="oraext:last-index-within-string (CustPO,'-')"></xsl:variable>
          
           <xsl:variable name="lastIndexEHifen">
           <xsl:value-of select="number($lastIndexE)+ 2"/>
           </xsl:variable>
            
            <xsl:variable name="custPOTagLen" select="string-length (CustPO)"></xsl:variable>
        
      
           <xsl:variable name = "CustPO">
          <xsl:value-of select="substring(CustPO,1,$lastIndexE)"/>
         
          </xsl:variable>
           <xsl:variable name = "LineNumber">
          <xsl:value-of select="substring(CustPO,$lastIndexEHifen,$custPOTagLen)"/>
         
          </xsl:variable>
          
            <ns8:Transaction>
              <ns8:BasicTransaction>
                <ns8:TransactionType>RECEIVE</ns8:TransactionType>
                <ns8:TransactionDate> <xsl:value-of select="xp20:current-date()"/></ns8:TransactionDate>
              </ns8:BasicTransaction>
               <ns8:AutoTransactCode>RECEIVE</ns8:AutoTransactCode>
            <!--  <ns8:CustomerId>
                <xsl:value-of select="CustPartNum"/>
              </ns8:CustomerId>-->
              <ns8:DestinationTypeCode>RECEIVING</ns8:DestinationTypeCode>
              <ns8:DocumentLineNum>
                <xsl:value-of select="$LineNumber"/>
              </ns8:DocumentLineNum>
              <ns8:DocumentNum>
                <xsl:value-of select="$CustPO"/>
              </ns8:DocumentNum>
              <ns8:GroupId>AssignLater</ns8:GroupId>
              <ns8:Item>
              <ns14:Identifier>
              <xsl:value-of select="CustPartNum"/>
              </ns14:Identifier>
              </ns8:Item>
               <ns8:OrgId>Org_Id</ns8:OrgId> 
               <ns8:Quantity><xsl:value-of select="sum(Bundles/Bundle/QtyPcs)"/></ns8:Quantity>
  
              <!--<ns8:PoUnitPrice>0</ns8:PoUnitPrice>-->
              <ns8:ProcessingModeCode>BATCH</ns8:ProcessingModeCode>
              <ns8:ProcessingStatusCode>PENDING</ns8:ProcessingStatusCode>
               <ns8:ReceiptSourceCode>VENDOR</ns8:ReceiptSourceCode>
               <ns8:SourceDocumentCode>PO</ns8:SourceDocumentCode>
              <ns8:ToOrganizationId>ToOrgId</ns8:ToOrganizationId>
              <ns8:TransactionDate><xsl:value-of select="xp20:current-date()"/></ns8:TransactionDate>
              <ns8:TransactionStatusCode>PENDING</ns8:TransactionStatusCode>
              <ns8:TransactionType>SHIP</ns8:TransactionType>
              <ns8:TruckNum>
                <xsl:value-of select="/Envelope/FreightInfo/Carrier/VehicleID"/>
              </ns8:TruckNum>
              <ns8:UnitOfMeasure>UOM</ns8:UnitOfMeasure>
              <ns8:ValidationFlag>Y</ns8:ValidationFlag>
              <ns8:WaybillAirbillNum>206650</ns8:WaybillAirbillNum>
              <ns8:Transaction>
                <ns8:Item>
                  <ns14:Description/>
                </ns8:Item>
              </ns8:Transaction>
            </ns8:Transaction></xsl:for-each>
        </ns8:ListOfTransactions>
      </tns:Receipt>
    </tns:CreateReceiptRequestMessage>
  </xsl:template>
</xsl:stylesheet>
