<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://www.nucor.com/scmschemas/label.xsd"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Nucor/NYS_TransferLabel_NiceLable_ABF/File_Write_LabelInput">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/File_Write_LabelInput.wsdl"/>
        <oracle-xsl-mapper:rootElement name="labels" namespace="http://www.nucor.com/scmschemas/label.xsd"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/File_Write_LabelInput.wsdl"/>
        <oracle-xsl-mapper:rootElement name="labels" namespace="http://www.nucor.com/scmschemas/label.xsd"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU OCT 01 07:51:05 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:labels>
      <xsl:if test="/ns0:labels/@_FORMAT">
        <xsl:attribute name="_FORMAT">
          <xsl:value-of select="/ns0:labels/@_FORMAT"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:labels/@_QUANTITY">
        <xsl:attribute name="_QUANTITY">
          <xsl:value-of select="/ns0:labels/@_QUANTITY"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:labels/@_PRINTERNAME">
        <xsl:attribute name="_PRINTERNAME">
          <xsl:value-of select="/ns0:labels/@_PRINTERNAME"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:labels/@_JOBNAME">
        <xsl:attribute name="_JOBNAME">
          <xsl:value-of select="/ns0:labels/@_JOBNAME"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:for-each select="/ns0:labels/ns0:label">
        <ns0:label>
          <xsl:if test="@_FORMAT">
            <xsl:attribute name="_FORMAT">
              <xsl:value-of select="@_FORMAT"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:for-each select="ns0:variable">
            <ns0:variable>
              <xsl:if test="@name">
                <xsl:for-each select="/ns0:labels/ns0:label/ns0:variable/@name">
                  <xsl:attribute name="name">
                    <xsl:value-of select="/ns0:labels/ns0:label/ns0:variable/@name"/>
                  </xsl:attribute>
                </xsl:for-each>
              </xsl:if>
              <xsl:value-of select="@name"/>
            </ns0:variable>
          </xsl:for-each>
        </ns0:label>
      </xsl:for-each>
    </ns0:labels>
  </xsl:template>
</xsl:stylesheet>
