<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns0="http://xmlns.oracle.com/apps/otm"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/I135/NUC_ReadBOLAck_Transentric_OTM_ABF/FTP_ReadFile_Transentric"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadFile_Transentric.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadFile_Transentric.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE DEC 29 06:49:39 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:Transmission>
      <ns0:TransmissionHeader>
        <ns0:Version>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:Version"/>
        </ns0:Version>
        <ns0:TransmissionType>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:TransmissionType"/>
        </ns0:TransmissionType>
        <ns0:QueryReplyFormat>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:QueryReplyFormat"/>
        </ns0:QueryReplyFormat>
        <ns0:StagingInfo>
          <ns0:StagingQuery>
            <ns0:IntSavedQuery>
              <ns0:IntSavedQueryGid>
                <ns0:Gid>
                  <ns0:DomainName>
                    <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingQuery/ns0:IntSavedQuery/ns0:IntSavedQueryGid/ns0:Gid/ns0:DomainName"/>
                  </ns0:DomainName>
                  <ns0:Xid>
                    <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingQuery/ns0:IntSavedQuery/ns0:IntSavedQueryGid/ns0:Gid/ns0:Xid"/>
                  </ns0:Xid>
                </ns0:Gid>
              </ns0:IntSavedQueryGid>
              <xsl:for-each select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingQuery/ns0:IntSavedQuery/ns0:IntSavedQueryArg">
                <ns0:IntSavedQueryArg>
                  <ns0:ArgName>
                    <xsl:value-of select="ns0:ArgName"/>
                  </ns0:ArgName>
                  <ns0:ArgValue>
                    <xsl:value-of select="ns0:ArgValue"/>
                  </ns0:ArgValue>
                </ns0:IntSavedQueryArg>
              </xsl:for-each>
              <ns0:IsMultiMatch>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingQuery/ns0:IntSavedQuery/ns0:IsMultiMatch"/>
              </ns0:IsMultiMatch>
              <ns0:MaximumMatch>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingQuery/ns0:IntSavedQuery/ns0:MaximumMatch"/>
              </ns0:MaximumMatch>
              <ns0:NoDataFoundAction>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingQuery/ns0:IntSavedQuery/ns0:NoDataFoundAction"/>
              </ns0:NoDataFoundAction>
            </ns0:IntSavedQuery>
          </ns0:StagingQuery>
          <ns0:StagingProcess>
            <ns0:IntSavedQuery>
              <ns0:IntSavedQueryGid>
                <ns0:Gid>
                  <ns0:DomainName>
                    <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingProcess/ns0:IntSavedQuery/ns0:IntSavedQueryGid/ns0:Gid/ns0:DomainName"/>
                  </ns0:DomainName>
                  <ns0:Xid>
                    <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingProcess/ns0:IntSavedQuery/ns0:IntSavedQueryGid/ns0:Gid/ns0:Xid"/>
                  </ns0:Xid>
                </ns0:Gid>
              </ns0:IntSavedQueryGid>
              <xsl:for-each select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingProcess/ns0:IntSavedQuery/ns0:IntSavedQueryArg">
                <ns0:IntSavedQueryArg>
                  <ns0:ArgName>
                    <xsl:value-of select="ns0:ArgName"/>
                  </ns0:ArgName>
                  <ns0:ArgValue>
                    <xsl:value-of select="ns0:ArgValue"/>
                  </ns0:ArgValue>
                </ns0:IntSavedQueryArg>
              </xsl:for-each>
              <ns0:IsMultiMatch>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingProcess/ns0:IntSavedQuery/ns0:IsMultiMatch"/>
              </ns0:IsMultiMatch>
              <ns0:MaximumMatch>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingProcess/ns0:IntSavedQuery/ns0:MaximumMatch"/>
              </ns0:MaximumMatch>
              <ns0:NoDataFoundAction>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StagingInfo/ns0:StagingProcess/ns0:IntSavedQuery/ns0:NoDataFoundAction"/>
              </ns0:NoDataFoundAction>
            </ns0:IntSavedQuery>
          </ns0:StagingProcess>
        </ns0:StagingInfo>
        <ns0:TransmissionCreateDt>
          <ns0:GLogDate>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:TransmissionCreateDt/ns0:GLogDate"/>
          </ns0:GLogDate>
          <ns0:TZId>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:TransmissionCreateDt/ns0:TZId"/>
          </ns0:TZId>
          <ns0:TZOffset>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:TransmissionCreateDt/ns0:TZOffset"/>
          </ns0:TZOffset>
        </ns0:TransmissionCreateDt>
        <ns0:TransactionCount>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:TransactionCount"/>
        </ns0:TransactionCount>
        <ns0:SenderHostName>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:SenderHostName"/>
        </ns0:SenderHostName>
        <ns0:ReceiverHostName>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:ReceiverHostName"/>
        </ns0:ReceiverHostName>
        <ns0:SenderSystemID>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:SenderSystemID"/>
        </ns0:SenderSystemID>
        <ns0:UserName>SMG.INTEGRATION</ns0:UserName>
        <ns0:Password Type="{/ns0:Transmission/ns0:TransmissionHeader/ns0:Password/@Type}">Nuc0rxyz</ns0:Password>
        <ns0:SenderTransmissionNo>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:SenderTransmissionNo"/>
        </ns0:SenderTransmissionNo>
        <ns0:ReferenceTransmissionNo>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:ReferenceTransmissionNo"/>
        </ns0:ReferenceTransmissionNo>
        <ns0:SuppressTransmissionAck>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:SuppressTransmissionAck"/>
        </ns0:SuppressTransmissionAck>
        <ns0:AckSpec>
          <ns0:ComMethodGid>
            <ns0:Gid>
              <ns0:DomainName>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:AckSpec/ns0:ComMethodGid/ns0:Gid/ns0:DomainName"/>
              </ns0:DomainName>
              <ns0:Xid>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:AckSpec/ns0:ComMethodGid/ns0:Gid/ns0:Xid"/>
              </ns0:Xid>
            </ns0:Gid>
          </ns0:ComMethodGid>
          <ns0:EmailAddress>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:AckSpec/ns0:EmailAddress"/>
          </ns0:EmailAddress>
          <ns0:SmtpHost>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:AckSpec/ns0:SmtpHost"/>
          </ns0:SmtpHost>
          <ns0:ServletURL>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:AckSpec/ns0:ServletURL"/>
          </ns0:ServletURL>
          <ns0:AckOption>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:AckSpec/ns0:AckOption"/>
          </ns0:AckOption>
          <ns0:ContactGid>
            <ns0:Gid>
              <ns0:DomainName>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:AckSpec/ns0:ContactGid/ns0:Gid/ns0:DomainName"/>
              </ns0:DomainName>
              <ns0:Xid>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:AckSpec/ns0:ContactGid/ns0:Gid/ns0:Xid"/>
              </ns0:Xid>
            </ns0:Gid>
          </ns0:ContactGid>
        </ns0:AckSpec>
        <ns0:IsProcessInSequence>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:IsProcessInSequence"/>
        </ns0:IsProcessInSequence>
        <ns0:StopProcessOnError>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:StopProcessOnError"/>
        </ns0:StopProcessOnError>
        <ns0:GLogXMLElementName>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:GLogXMLElementName"/>
        </ns0:GLogXMLElementName>
        <xsl:for-each select="/ns0:Transmission/ns0:TransmissionHeader/ns0:ProcessGrouping">
          <ns0:ProcessGrouping>
            <ns0:ProcessGroup>
              <xsl:value-of select="ns0:ProcessGroup"/>
            </ns0:ProcessGroup>
            <ns0:ProcessGroupOwner>
              <xsl:value-of select="ns0:ProcessGroupOwner"/>
            </ns0:ProcessGroupOwner>
            <ns0:InSequence>
              <xsl:value-of select="ns0:InSequence"/>
            </ns0:InSequence>
            <ns0:StopProcessOnError>
              <xsl:value-of select="ns0:StopProcessOnError"/>
            </ns0:StopProcessOnError>
          </ns0:ProcessGrouping>
        </xsl:for-each>
        <ns0:NotifyInfo>
          <ns0:ContactGid>
            <ns0:Gid>
              <ns0:DomainName>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:NotifyInfo/ns0:ContactGid/ns0:Gid/ns0:DomainName"/>
              </ns0:DomainName>
              <ns0:Xid>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:NotifyInfo/ns0:ContactGid/ns0:Gid/ns0:Xid"/>
              </ns0:Xid>
            </ns0:Gid>
          </ns0:ContactGid>
          <ns0:ExternalSystemGid>
            <ns0:Gid>
              <ns0:DomainName>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:NotifyInfo/ns0:ExternalSystemGid/ns0:Gid/ns0:DomainName"/>
              </ns0:DomainName>
              <ns0:Xid>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:NotifyInfo/ns0:ExternalSystemGid/ns0:Gid/ns0:Xid"/>
              </ns0:Xid>
            </ns0:Gid>
          </ns0:ExternalSystemGid>
          <ns0:MessageText>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionHeader/ns0:NotifyInfo/ns0:MessageText"/>
          </ns0:MessageText>
        </ns0:NotifyInfo>
        <xsl:for-each select="/ns0:Transmission/ns0:TransmissionHeader/ns0:Refnum">
          <ns0:Refnum>
            <ns0:RefnumQualifierGid>
              <ns0:Gid>
                <ns0:DomainName>
                  <xsl:value-of select="ns0:RefnumQualifierGid/ns0:Gid/ns0:DomainName"/>
                </ns0:DomainName>
                <ns0:Xid>
                  <xsl:value-of select="ns0:RefnumQualifierGid/ns0:Gid/ns0:Xid"/>
                </ns0:Xid>
              </ns0:Gid>
            </ns0:RefnumQualifierGid>
            <ns0:RefnumValue>
              <xsl:value-of select="ns0:RefnumValue"/>
            </ns0:RefnumValue>
          </ns0:Refnum>
        </xsl:for-each>
      </ns0:TransmissionHeader>
    </ns0:Transmission>
  </xsl:template>
</xsl:stylesheet>
