<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/WSH_OTM_REF_DATA_GEN_PKG/SEND_LOCATIONS/"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/apps/wsh/outbound/ref/WshSendLocRefDataToOtm"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns2="http://xmlns.oracle.com/apps/otm"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ref="http://xmlns.oracle.com/apps/wsh/outbound/util/WshOtmGlobalOutbound"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/WshGenLocRefData/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WshSendLocRefDataToOtm.wsdl"/>
        <oracle-xsl-mapper:rootElement name="WshSendLocRefDataToOtmProcessRequest"
                                       namespace="http://xmlns.oracle.com/apps/wsh/outbound/ref/WshSendLocRefDataToOtm"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WshSendLocRefDataToOtm.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="L_Parameter"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../partnerWsdls/WshGenLocRefData.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/WSH_OTM_REF_DATA_GEN_PKG/SEND_LOCATIONS/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED MAR 08 23:40:14 PST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="L_Parameter"/>
  <xsl:template match="/">
    <tns:InputParameters>
      <P_ENTITY_IN_REC>
        <ENTITY_TYPE>
          <xsl:value-of select="/ns0:WshSendLocRefDataToOtmProcessRequest/ns0:input/ref:entityType"/>
        </ENTITY_TYPE>
        <OPERATION>
          <xsl:value-of select="/ns0:WshSendLocRefDataToOtmProcessRequest/ns0:input/ref:securityContext/ref:opCode"/>
        </OPERATION>
        <ARGUMENT>
          <xsl:value-of select="/ns0:WshSendLocRefDataToOtmProcessRequest/ns0:input/ref:securityContext/ref:argKey"/>
        </ARGUMENT>
        <TICKET>
          <xsl:value-of select="/ns0:WshSendLocRefDataToOtmProcessRequest/ns0:input/ref:securityContext/ref:ticket"/>
        </TICKET>
        <ENTITY_ID_TBL>
          <ENTITY_ID_TBL_ITEM>
            <xsl:value-of select="/ns0:WshSendLocRefDataToOtmProcessRequest/ns0:input/ref:entityIdList/ref:entityId[number($L_Parameter/ns1:parameters/ns1:item/ns1:value)]"/>
          </ENTITY_ID_TBL_ITEM>
        </ENTITY_ID_TBL>
        <PARENT_ENTITY_ID_TBL>
          <ENTITY_ID_TBL_ITEM>
            <xsl:value-of select="/ns0:WshSendLocRefDataToOtmProcessRequest/ns0:input/ref:parentIdList/ref:entityId[number($L_Parameter/ns1:parameters/ns1:item/ns1:value)]"/>
          </ENTITY_ID_TBL_ITEM>
        </PARENT_ENTITY_ID_TBL>
      </P_ENTITY_IN_REC>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
