<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:ref="http://xmlns.oracle.com/apps/wsh/outbound/util/WshOtmGlobalOutbound"
                xmlns:client="http://xmlns.oracle.com/apps/wsh/outbound/ref/WshSendLocRefDataToOtm"
                xmlns:ns1="http://xmlns.oracle.com/apps/otm"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/WSH_OTM_REF_DATA_GEN_PKG/SEND_LOCATIONS/"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl plnk ns0 ref client ns1 db ldap xp20 bpws ora orcl"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns2="http://schemas.oracle.com/service/bpel/common">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WshSendLocRefDataToOtm.wsdl"/>
        <oracle-xsl-mapper:rootElement name="WshSendLocRefDataToOtmProcessRequest"
                                       namespace="http://xmlns.oracle.com/apps/wsh/outbound/ref/WshSendLocRefDataToOtm"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/APPS_WSH_OTM_REF_DATA_GEN_PKG_SEND_LOCATIONS.xsd"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/WSH_OTM_REF_DATA_GEN_PKG/SEND_LOCATIONS/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU NOV 05 07:59:01 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <db:InputParameters>
      <P_ENTITY_IN_REC>
        <ENTITY_TYPE>
          <xsl:value-of select="/client:WshSendLocRefDataToOtmProcessRequest/client:input/ref:entityType"/>
        </ENTITY_TYPE>
        <OPERATION>
          <xsl:value-of select="/client:WshSendLocRefDataToOtmProcessRequest/client:input/ref:securityContext/ref:opCode"/>
        </OPERATION>
        <ARGUMENT>
          <xsl:value-of select="/client:WshSendLocRefDataToOtmProcessRequest/client:input/ref:securityContext/ref:argKey"/>
        </ARGUMENT>
        <TICKET>
          <xsl:value-of select="/client:WshSendLocRefDataToOtmProcessRequest/client:input/ref:securityContext/ref:ticket"/>
        </TICKET>
        <ENTITY_ID_TBL>
          <xsl:for-each select="/client:WshSendLocRefDataToOtmProcessRequest/client:input/ref:entityIdList/ref:entityId">
            <ENTITY_ID_TBL_ITEM>
              <xsl:value-of select="."/>
            </ENTITY_ID_TBL_ITEM>
          </xsl:for-each>
        </ENTITY_ID_TBL>
        <PARENT_ENTITY_ID_TBL>
          <xsl:for-each select="/client:WshSendLocRefDataToOtmProcessRequest/client:input/ref:parentIdList/ref:entityId">
          
            <ENTITY_ID_TBL_ITEM>
              <xsl:value-of select="."/>
            </ENTITY_ID_TBL_ITEM>
          </xsl:for-each>
        </PARENT_ENTITY_ID_TBL>
      </P_ENTITY_IN_REC>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>