<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DbInsertXXNUC_WSH_CP_FREINV_HDR_STG"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://www.xmlns.nucor.com/NameValuePair/NUC_FreightandInvoice_CP_EBS_ABF"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DbCallXXNUC_OMSI_EXTRACTS_PKG"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBSCallXXNUC_WSH_FRECOST_INV_WRAP_PKG"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/DV1Application/NUC_FreightandInvoice_CP_EBS_ABF/DbCallXXNUC_OMSI_EXTRACTS_PKG"
                xmlns:client="http://xmlns.oracle.com/DV1Application/NUC_FreightandInvoice_CP_EBS_ABF/FreightandInvoice_CP_EBS_Impl/1.0"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/DV1Application/NUC_FreightandInvoice_CP_EBS_ABF/DbInsertXXNUC_WSH_CP_FREINV_HDR_STG"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FreightandInvoice_CP_EBS_Impl.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters"
                                       namespace="http://www.xmlns.nucor.com/NameValuePair/NUC_FreightandInvoice_CP_EBS_ABF"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DbCallXXNUC_OMSI_EXTRACTS_PKG.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DbCallXXNUC_OMSI_EXTRACTS_PKG"/>
        <oracle-xsl-mapper:param name="InvokeDbCallXXNUC_OMSI_EXTRACTS_PKG_OutputVariable.OutputParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DbInsertXXNUC_WSH_CP_FREINV_HDR_STG.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucWshCpFreinvHdrStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DbInsertXXNUC_WSH_CP_FREINV_HDR_STG"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE NOV 03 01:02:08 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="InvokeDbCallXXNUC_OMSI_EXTRACTS_PKG_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <!--xsl:variable name="parentLogId"
                  select="$InvokeDbCallXXNUC_OMSI_EXTRACTS_PKG_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_LOG_ENTRY/ns1:P_LOG_ENTRY_ITEM/ns1:LOG_ENTRY_ID"/-->
    <tns:XxnucWshCpFreinvHdrStgCollection>
      <xsl:for-each select="$InvokeDbCallXXNUC_OMSI_EXTRACTS_PKG_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_LOG_ENTRY/ns1:P_LOG_ENTRY_ITEM">
        <xsl:variable name="parentLogId" select="ns1:LOG_ENTRY_ID"/>
        <tns:XxnucWshCpFreinvHdrStg>
          <tns:logEntryId>
            <xsl:value-of select="ns1:LOG_ENTRY_ID"/>
          </tns:logEntryId>
          <tns:operationId>
            <xsl:value-of select="ns1:OPERATION_ID"/>
          </tns:operationId>
          <tns:operation>
            <xsl:value-of select="ns1:OPERATION"/>
          </tns:operation>
          <tns:resultCode>
            <xsl:value-of select="ns1:RESULT_CODE"/>
          </tns:resultCode>
          <tns:resultMessage>
            <xsl:value-of select="ns1:RESULT_MESSAGE"/>
          </tns:resultMessage>
          <tns:isRead>
            <xsl:value-of select="ns1:IS_READ"/>
          </tns:isRead>
          <tns:processTime>
            <xsl:value-of select="ns1:PROCESS_TIME"/>
          </tns:processTime>
          <tns:createdBy>-1</tns:createdBy>
          <tns:creationDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:creationDate>
          <tns:lastUpdatedBy>-1</tns:lastUpdatedBy>
          <tns:lastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:lastUpdateDate>
          <tns:lastUpdateLogin>-1</tns:lastUpdateLogin>
          <tns:transactionId>
            <xsl:value-of select="/ns0:parameters/ns0:item/ns0:value"/>
          </tns:transactionId>
          <tns:xxnucWshCpFreinvLnsStgCollection>
            <xsl:for-each select="$InvokeDbCallXXNUC_OMSI_EXTRACTS_PKG_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_FREIGHT_LOG_ENTRY/ns1:P_FREIGHT_LOG_ENTRY_ITEM">
              <xsl:choose>
                <xsl:when test="$parentLogId = ns1:LOG_ENTRY_ID">
                  <tns:XxnucWshCpFreinvLnsStg>
                    <tns:clientKey1>
                      <xsl:value-of select="ns1:CLIENT_KEY_1"/>
                    </tns:clientKey1>
                    <tns:clientKey2>
                      <xsl:value-of select="ns1:CLIENT_KEY_2"/>
                    </tns:clientKey2>
                    <tns:clientKey3>
                      <xsl:value-of select="ns1:CLIENT_KEY_3"/>
                    </tns:clientKey3>
                    <tns:clientKey4>
                      <xsl:value-of select="ns1:CLIENT_KEY_4"/>
                    </tns:clientKey4>
                    <tns:stopSequenceNumber>
                      <xsl:value-of select="ns1:STOP_SEQUENCE_NUMBER"/>
                    </tns:stopSequenceNumber>
                    <tns:dsmId>
                      <xsl:value-of select="ns1:DSM_ID"/>
                    </tns:dsmId>
                    <tns:shipperRefNumber>
                      <xsl:value-of select="ns1:SHIPPER_REF_NUMBER"/>
                    </tns:shipperRefNumber>
                    <tns:carrierName>
                      <xsl:value-of select="ns1:CARRIER_NAME"/>
                    </tns:carrierName>
                    <tns:carrierScac>
                      <xsl:value-of select="ns1:CARRIER_SCAC"/>
                    </tns:carrierScac>
                    <tns:vendorId>
                      <xsl:value-of select="ns1:VENDOR_ID"/>
                    </tns:vendorId>
                    <tns:lineHaulCharge>
                      <xsl:value-of select="ns1:LINE_HAUL_CHARGE"/>
                    </tns:lineHaulCharge>
                    <tns:fuelSurcharge>
                      <xsl:value-of select="ns1:FUEL_SURCHARGE"/>
                    </tns:fuelSurcharge>
                    <tns:customerNumber>
                      <xsl:value-of select="ns1:CUSTOMER_NUMBER"/>
                    </tns:customerNumber>
                    <tns:customerOrderNumber>
                      <xsl:value-of select="ns1:CUSTOMER_ORDER_NUMBER"/>
                    </tns:customerOrderNumber>
                    <tns:poNumber>
                      <xsl:value-of select="ns1:PO_NUMBER"/>
                    </tns:poNumber>
                    <tns:bolNumber>
                      <xsl:value-of select="ns1:BOL_NUMBER"/>
                    </tns:bolNumber>
                    <tns:accessorialCode>
                      <xsl:value-of select="ns1:ACCESSORIAL_CODE"/>
                    </tns:accessorialCode>
                    <tns:ediCode>
                      <xsl:value-of select="ns1:EDI_CODE"/>
                    </tns:ediCode>
                    <tns:accessorialCharge>
                      <xsl:value-of select="ns1:ACCESSORIAL_CHARGE"/>
                    </tns:accessorialCharge>
                    <tns:shipperComment>
                      <xsl:value-of select="ns1:SHIPPER_COMMENT"/>
                    </tns:shipperComment>
                    <tns:carrierClaim>
                      <xsl:value-of select="ns1:CARRIER_CLAIM"/>
                    </tns:carrierClaim>
                    <tns:carrierComment>
                      <xsl:value-of select="ns1:CARRIER_COMMENT"/>
                    </tns:carrierComment>
                    <tns:isDelivered>
                      <xsl:value-of select="ns1:IS_DELIVERED"/>
                    </tns:isDelivered>
                    <tns:auditStatus>
                      <xsl:value-of select="ns1:AUDIT_STATUS"/>
                    </tns:auditStatus>
                    <tns:deliveringCarrierName>
                      <xsl:value-of select="ns1:DELIVERING_CARRIER_NAME"/>
                    </tns:deliveringCarrierName>
                    <tns:deliveringCarrierScac>
                      <xsl:value-of select="ns1:DELIVERING_CARRIER_SCAC"/>
                    </tns:deliveringCarrierScac>
                    <tns:deliveringCarrierVendorId>
                      <xsl:value-of select="ns1:DELIVERING_CARRIER_VENDOR_ID"/>
                    </tns:deliveringCarrierVendorId>
                    <tns:glItemCode>
                      <xsl:value-of select="ns1:GL_ITEM_CODE"/>
                    </tns:glItemCode>
                    <tns:proNumber>
                      <xsl:value-of select="ns1:PRO_NUMBER"/>
                    </tns:proNumber>
                    <tns:popuSigningDate>
                      <xsl:value-of select="ns1:POPU_SIGNING_DATE"/>
                    </tns:popuSigningDate>
                    <tns:podSigningDate>
                      <xsl:value-of select="ns1:POD_SIGNING_DATE"/>
                    </tns:podSigningDate>
                    <tns:createdBy>-1</tns:createdBy>
                    <tns:creationDate>
                      <xsl:value-of select="xp20:current-dateTime ( )"/>
                    </tns:creationDate>
                    <tns:lastUpdatedBy>-1</tns:lastUpdatedBy>
                    <tns:lastUpdateDate>
                      <xsl:value-of select="xp20:current-dateTime ( )"/>
                    </tns:lastUpdateDate>
                    <tns:lastUpdateLogin>-1</tns:lastUpdateLogin>
                    <tns:transactionId>
                      <xsl:value-of select="/ns0:parameters/ns0:item/ns0:value"/>
                    </tns:transactionId>
                  </tns:XxnucWshCpFreinvLnsStg>
                </xsl:when>
              </xsl:choose>
            </xsl:for-each>
          </tns:xxnucWshCpFreinvLnsStgCollection>
        </tns:XxnucWshCpFreinvHdrStg>
      </xsl:for-each>
    </tns:XxnucWshCpFreinvHdrStgCollection>
  </xsl:template>
</xsl:stylesheet>
