<wsdl:definitions
     name="DB_QMOS_DATA"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NSNE_SubscribeQualitySpecs_QMOS_ABFApplication/NSUT_QualityData_QMOS_EBS_ABF/DB_QMOS_DATA"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NSNE_SubscribeQualitySpecs_QMOS_ABFApplication/NSUT_QualityData_QMOS_EBS_ABF/DB_QMOS_DATA"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QMOS_DATA"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_QMOS_DATA_plt" >
    <plt:role name="DB_QMOS_DATA_role" >
      <plt:portType name="tns:DB_QMOS_DATA_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QMOS_DATA" schemaLocation="../Schemas/DB_QMOS_DATA_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_QMOS_DATASelect_inputParameters">
        <wsdl:part name="DB_QMOS_DATASelect_inputParameters" element="top:DB_QMOS_DATASelect_rownumValueInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ApiMetTransCollection_msg">
        <wsdl:part name="ApiMetTransCollection" element="top:ApiMetTransCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_QMOS_DATA_ptt">
        <wsdl:operation name="DB_QMOS_DATASelect">
            <wsdl:input message="tns:DB_QMOS_DATASelect_inputParameters"/>
            <wsdl:output message="tns:ApiMetTransCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
