DROP TABLE EBS_INTF.XXNUC_SUPPLIERS_IN CASCADE CONSTRAINTS;

CREATE TABLE EBS_INTF.XXNUC_SUPPLIERS_IN
(
  SUPPLIER_IN_KEY                NUMBER,
  PAY_SITE_FLAG                  VARCHAR2(100 BYTE),
  PURCHASING_SITE_FLAG           VARCHAR2(100 BYTE),
  EMAIL_ADDRESS                  VARCHAR2(100 BYTE),
  FAX_NUMBER                     VARCHAR2(100 BYTE),
  FAX_AREA_CODE                  VARCHAR2(100 BYTE),
  PHONE_NUMBER                   VARCHAR2(100 BYTE),
  PHONE_AREA_CODE                VARCHAR2(100 BYTE),
  ACTIVE                         VARCHAR2(100 BYTE),
  ADDRESS_NAME                   VARCHAR2(300 BYTE),
  COUNTRY                        VARCHAR2(100 BYTE),
  COUNTY                         VARCHAR2(100 BYTE),
  POSTAL_CODE                    VARCHAR2(100 BYTE),
  STATE                          VARCHAR2(100 BYTE),
  CITY                           VARCHAR2(100 BYTE),
  ADDRESS_LINE4                  VARCHAR2(300 BYTE),
  ADDRESS_LINE3                  VARCHAR2(300 BYTE),
  ADDRESS_LINE2                  VARCHAR2(300 BYTE),
  ADDRESS_LINE1                  VARCHAR2(300 BYTE),
  SHIP_TO_ADDRESS                VARCHAR2(200 BYTE),
  CONFIRMATION_REQUIRED          VARCHAR2(100 BYTE),
  BANK_NUMBER                    VARCHAR2(100 BYTE),
  CREDIT_LIMIT                   VARCHAR2(100 BYTE),
  VENDOR_SORT_NAME               VARCHAR2(300 BYTE),
  TAX_CLASSIFICATION             VARCHAR2(100 BYTE),
  FREIGHT_TERMS                  VARCHAR2(100 BYTE),
  RMA_REQUIRED                   VARCHAR2(100 BYTE),
  TERMS_NAME                     VARCHAR2(100 BYTE),
  SINGLE_INVOICE_PROCESSOR       VARCHAR2(100 BYTE),
  SUPPLIER_GROUP                 VARCHAR2(100 BYTE),
  SUPPLIER_TYPE                  VARCHAR2(100 BYTE),
  TAXPAYER_ID                    VARCHAR2(100 BYTE),
  EMPLOYEES_TOTAL                VARCHAR2(100 BYTE),
  INCORP_YEAR                    VARCHAR2(100 BYTE),
  YEAR_ESTABLISHED               VARCHAR2(100 BYTE),
  DUNS_NUMBER                    VARCHAR2(100 BYTE),
  URL                            VARCHAR2(100 BYTE),
  END_DATE_ACTIVE                VARCHAR2(100 BYTE),
  SIC_CODE                       VARCHAR2(100 BYTE),
  VENDOR_NUMBER                  VARCHAR2(100 BYTE),
  VENDOR_NAME                    VARCHAR2(100 BYTE),
  OPERATING_UNIT                 VARCHAR2(100 BYTE),
  ACTION                         VARCHAR2(100 BYTE),
  STATUS                         VARCHAR2(100 BYTE),
  PARTY_ID                       VARCHAR2(100 BYTE),
  ADDRESS_NUMBER                 VARCHAR2(100 BYTE),
  TAX_REPORTING_NAME             VARCHAR2(100 BYTE),
  PAYMENT_METHOD                 VARCHAR2(100 BYTE),
  INVOICE_CURRENCY_CODE          VARCHAR2(100 BYTE),
  EXCLUDE_FREIGHT_FROM_DISCOUNT  VARCHAR2(100 BYTE),
  TYPE_1099                      VARCHAR2(100 BYTE),
  VENDOR_1099_FLAG               VARCHAR2(100 BYTE),
  MINORITY_GROUP_CODE            VARCHAR2(100 BYTE),
  SHIP_VIA                       VARCHAR2(100 BYTE),
  HOLD_PAYMENT                   VARCHAR2(100 BYTE),
  AP_CLERK                       VARCHAR2(100 BYTE),
  FOB_LOOKUP_CODE                VARCHAR2(100 BYTE),
  STOP_PAYMENT                   VARCHAR2(100 BYTE),
  STATE_TAX_ID                   VARCHAR2(100 BYTE),
  RECEPIENT                      VARCHAR2(100 BYTE),
  NOTES                          VARCHAR2(100 BYTE),
  NOTIFICATION_METHOD            VARCHAR2(100 BYTE),
  P_CARD_SITE_FLAG               VARCHAR2(100 BYTE),
  REF_SUPPLIER_SITE_ID           VARCHAR2(100 BYTE),
  REF_SUPPLIER_ID                VARCHAR2(100 BYTE),
  REF_PARTY_ID                   VARCHAR2(100 BYTE),
  REF_PARTY_SITE_ID              VARCHAR2(100 BYTE),
  REF_LOCATION_ID                VARCHAR2(100 BYTE),
  CREATION_DATE                  DATE,
  LAST_UPDATE_DATE               DATE,
  CREATED_BY                     VARCHAR2(240 BYTE),
  LAST_UPDATED_BY                VARCHAR2(240 BYTE),
  PROCESS_DATE                   VARCHAR2(100 BYTE),
  PROCESS_STATUS                 VARCHAR2(100 BYTE),
  ERROR_MSG                      VARCHAR2(2000 BYTE),
  REQUEST_ID                     VARCHAR2(100 BYTE),
  ATTRIBUTE_CATEGORY             VARCHAR2(30 BYTE),
  ATTRIBUTE1                     VARCHAR2(150 BYTE),
  ATTRIBUTE2                     VARCHAR2(150 BYTE),
  ATTRIBUTE3                     VARCHAR2(150 BYTE),
  ATTRIBUTE4                     VARCHAR2(150 BYTE),
  ATTRIBUTE5                     VARCHAR2(150 BYTE),
  ATTRIBUTE6                     VARCHAR2(150 BYTE),
  ATTRIBUTE7                     VARCHAR2(150 BYTE),
  ATTRIBUTE8                     VARCHAR2(150 BYTE),
  ATTRIBUTE9                     VARCHAR2(150 BYTE),
  ATTRIBUTE10                    VARCHAR2(150 BYTE),
  ATTRIBUTE11                    VARCHAR2(150 BYTE),
  ATTRIBUTE12                    VARCHAR2(150 BYTE),
  ATTRIBUTE13                    VARCHAR2(150 BYTE),
  ATTRIBUTE14                    VARCHAR2(150 BYTE),
  ATTRIBUTE15                    VARCHAR2(150 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EBS_INTF.XXNUC_SUPPLIERS_IN_U1 ON EBS_INTF.XXNUC_SUPPLIERS_IN
(SUPPLIER_IN_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EBS_INTF.XXNUC_SUPPLIERS_IN TO NUCOR_DEV;
