DROP TABLE EBS_INTF.XXNUC_AR_TRANS_LINES CASCADE CONSTRAINTS;

CREATE TABLE EBS_INTF.XXNUC_AR_TRANS_LINES
(
  AR_LINE_KEY                     NUMBER,
  TRX_NUMBER                      VARCHAR2(30 BYTE),
  TRX_DATE                        DATE,
  GL_DATE                         DATE,
  BATCH_SOURCE_NAME               VARCHAR2(50 BYTE),
  BATCH_NAME                      VARCHAR2(40 BYTE),
  CONVERSION_TYPE                 VARCHAR2(30 BYTE),
  CONVERSION_DATE                 DATE,
  CONVERSION_RATE                 NUMBER,
  COMMENTS                        VARCHAR2(240 BYTE),
  INTERNAL_NOTES                  VARCHAR2(240 BYTE),
  CUST_TRX_TYPE_NAME              VARCHAR2(20 BYTE),
  TERM_NAME                       VARCHAR2(15 BYTE),
  ORIG_SYSTEM_BILL_ADDRESS_REF    VARCHAR2(240 BYTE),
  ORIG_SYSTEM_BILL_CUSTOMER_REF   VARCHAR2(240 BYTE),
  HEADER_ATTRIBUTE12              VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE13              VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE14              VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE15              VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE1               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE2               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE3               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE4               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE5               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE6               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE7               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE8               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE9               VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE10              VARCHAR2(150 BYTE),
  HEADER_ATTRIBUTE11              VARCHAR2(150 BYTE),
  PURCHASE_ORDER                  VARCHAR2(50 BYTE),
  OPERATING_UNIT                  VARCHAR2(240 BYTE),
  INTERFACE_LINE_CONTEXT          VARCHAR2(30 BYTE),
  INTERFACE_LINE_ATTRIBUTE1       VARCHAR2(150 BYTE),
  INTERFACE_LINE_ATTRIBUTE2       VARCHAR2(150 BYTE),
  INTERFACE_LINE_ATTRIBUTE3       VARCHAR2(150 BYTE),
  INTERFACE_LINE_ATTRIBUTE4       VARCHAR2(150 BYTE),
  INTERFACE_LINE_ATTRIBUTE5       VARCHAR2(150 BYTE),
  INTERFACE_LINE_ATTRIBUTE6       VARCHAR2(150 BYTE),
  INTERFACE_LINE_ATTRIBUTE7       VARCHAR2(150 BYTE),
  INTERFACE_LINE_ATTRIBUTE8       VARCHAR2(150 BYTE),
  LINE_TYPE                       VARCHAR2(20 BYTE),
  LINE_NUMBER                     NUMBER,
  DESCRIPTION                     VARCHAR2(240 BYTE),
  UOM_CODE                        VARCHAR2(3 BYTE),
  QUANTITY                        NUMBER,
  UNIT_SELLING_PRICE              NUMBER,
  AMOUNT                          NUMBER,
  LINK_TO_LINE_CONTEXT            VARCHAR2(30 BYTE),
  LINK_TO_LINE_ATTRIBUTE1         VARCHAR2(150 BYTE),
  LINK_TO_LINE_ATTRIBUTE2         VARCHAR2(150 BYTE),
  LINK_TO_LINE_ATTRIBUTE3         VARCHAR2(150 BYTE),
  LINK_TO_LINE_ATTRIBUTE4         VARCHAR2(150 BYTE),
  LINK_TO_LINE_ATTRIBUTE5         VARCHAR2(150 BYTE),
  LINK_TO_LINE_ATTRIBUTE6         VARCHAR2(150 BYTE),
  LINK_TO_LINE_ATTRIBUTE7         VARCHAR2(150 BYTE),
  TAXABLE_FLAG                    VARCHAR2(1 BYTE),
  TAX_EXEMPT_FLAG                 VARCHAR2(1 BYTE),
  TAX_EXEMPT_REASON_CODE_MEANING  VARCHAR2(80 BYTE),
  TAX_EXEMPT_NUMBER               VARCHAR2(80 BYTE),
  TAX_REGIME_CODE                 VARCHAR2(30 BYTE),
  TAX                             VARCHAR2(30 BYTE),
  TAX_STATUS_CODE                 VARCHAR2(30 BYTE),
  TAX_RATE_CODE                   VARCHAR2(30 BYTE),
  TAX_JURISDICTION_CODE           VARCHAR2(30 BYTE),
  TAX_RATE                        NUMBER,
  TAX_CODE                        VARCHAR2(50 BYTE),
  TAX_AMOUNT                      NUMBER,
  ATTRIBUTE1                      VARCHAR2(150 BYTE),
  ATTRIBUTE2                      VARCHAR2(150 BYTE),
  ATTRIBUTE3                      VARCHAR2(150 BYTE),
  ATTRIBUTE4                      VARCHAR2(150 BYTE),
  ATTRIBUTE5                      VARCHAR2(150 BYTE),
  ATTRIBUTE6                      VARCHAR2(150 BYTE),
  ATTRIBUTE7                      VARCHAR2(150 BYTE),
  ATTRIBUTE8                      VARCHAR2(150 BYTE),
  ATTRIBUTE9                      VARCHAR2(150 BYTE),
  ATTRIBUTE10                     VARCHAR2(150 BYTE),
  ATTRIBUTE11                     VARCHAR2(150 BYTE),
  ATTRIBUTE12                     VARCHAR2(150 BYTE),
  ATTRIBUTE13                     VARCHAR2(150 BYTE),
  ATTRIBUTE14                     VARCHAR2(150 BYTE),
  ATTRIBUTE15                     VARCHAR2(150 BYTE),
  SALES_ORDER                     VARCHAR2(50 BYTE),
  SALES_ORDER_LINE                VARCHAR2(30 BYTE),
  SALES_ORDER_DATE                DATE,
  SALES_ORDER_SOURCE              VARCHAR2(50 BYTE),
  SHIP_DATE_ACTUAL                DATE,
  SHIP_VIA                        VARCHAR2(25 BYTE),
  FOB_POINT                       VARCHAR2(30 BYTE),
  REFERENCE_LINE_CONTEXT          VARCHAR2(30 BYTE),
  REFERENCE_LINE_ATTRIBUTE1       VARCHAR2(150 BYTE),
  REFERENCE_LINE_ATTRIBUTE2       VARCHAR2(150 BYTE),
  REFERENCE_LINE_ATTRIBUTE3       VARCHAR2(150 BYTE),
  REFERENCE_LINE_ATTRIBUTE4       VARCHAR2(150 BYTE),
  REFERENCE_LINE_ATTRIBUTE5       VARCHAR2(150 BYTE),
  IMPERIAL1                       VARCHAR2(240 BYTE),
  IMPERIAL2                       VARCHAR2(240 BYTE),
  IMPERIAL3                       VARCHAR2(240 BYTE),
  IMPERIAL4                       VARCHAR2(240 BYTE),
  IMPERIAL5                       VARCHAR2(240 BYTE),
  IMPERIAL6                       VARCHAR2(240 BYTE),
  IMPERIAL7                       VARCHAR2(240 BYTE),
  IMPERIAL8                       VARCHAR2(240 BYTE),
  IMPERIAL9                       VARCHAR2(240 BYTE),
  IMPERIAL10                      VARCHAR2(240 BYTE),
  IMPERIAL11                      VARCHAR2(240 BYTE),
  IMPERIAL12                      VARCHAR2(240 BYTE),
  METRIC1                         VARCHAR2(240 BYTE),
  METRIC2                         VARCHAR2(240 BYTE),
  METRIC3                         VARCHAR2(240 BYTE),
  CREATION_DATE                   DATE,
  LAST_UPDATE_DATE                DATE,
  CREATED_BY                      VARCHAR2(240 BYTE),
  LAST_UPDATED_BY                 VARCHAR2(240 BYTE),
  PROCESS_DATE                    DATE,
  PROCESS_STATUS                  VARCHAR2(100 BYTE),
  ERROR_MSG                       VARCHAR2(2000 BYTE),
  REQUEST_ID                      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EBS_INTF.XXNUC_AR_TRANS_LINES_U1 ON EBS_INTF.XXNUC_AR_TRANS_LINES
(AR_LINE_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER EBS_INTF.INS_XXNUC_AR_TRANS_LINES  
/******************************************************************************
   NAME:    INS_SYS_HELP_CONTEXT
   PURPOSE: Ensure ID is filled

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        10/09/2013  Gustave Massong            Created this trigger.

******************************************************************************/
BEFORE INSERT
ON EBS_INTF.XXNUC_AR_TRANS_LINES REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
   IF (:NEW.AR_LINE_KEY IS NULL) THEN
     SELECT XXNUC_AR_TRANS_LINES_S.NEXTVAL INTO :NEW.AR_LINE_KEY FROM dual;
   END IF;
END;
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EBS_INTF.XXNUC_AR_TRANS_LINES TO NUCOR_DEV;
