DROP TABLE EBS_INTF.XXNUC_GL_INTERFACE CASCADE CONSTRAINTS;

CREATE TABLE EBS_INTF.XXNUC_GL_INTERFACE
(
  GL_INT_KEY             NUMBER,
  BATCH_NAME             VARCHAR2(120 BYTE),
  LEDGER                 VARCHAR2(30 BYTE),
  USER_JE_CATEGORY_NAME  VARCHAR2(25 BYTE),
  USER_JE_SOURCE_NAME    VARCHAR2(25 BYTE),
  ACCOUNTED_DR           NUMBER,
  ACCOUNTED_CR           NUMBER,
  REFERENCE1             VARCHAR2(100 BYTE),
  REFERENCE2             VARCHAR2(240 BYTE),
  REFERENCE4             VARCHAR2(100 BYTE),
  REFERENCE5             VARCHAR2(240 BYTE),
  REFERENCE7             VARCHAR2(240 BYTE),
  REFERENCE8             VARCHAR2(240 BYTE),
  REFERENCE10            VARCHAR2(240 BYTE),
  PERIOD_NAME            VARCHAR2(15 BYTE),
  ACCOUNT                VARCHAR2(240 BYTE),
  ATTRIBUTE1             VARCHAR2(240 BYTE),
  ACTUAL_FLAG            VARCHAR2(2 BYTE),
  ACCOUNTING_DATE        DATE,
  CREATION_DATE          DATE,
  LAST_UPDATE_DATE       DATE,
  CREATED_BY             VARCHAR2(240 BYTE),
  LAST_UPDATED_BY        VARCHAR2(240 BYTE),
  PROCESS_DATE           DATE,
  PROCESS_STATUS         VARCHAR2(100 BYTE),
  ERROR_MSG              VARCHAR2(2000 BYTE),
  REQUEST_ID             VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EBS_INTF.XXNUC_GL_INTERFACE_N1 ON EBS_INTF.XXNUC_GL_INTERFACE
(GL_INT_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
