DROP TABLE EBS_INTF.XXNUC_AP_INVOICE_LINES CASCADE CONSTRAINTS;

CREATE TABLE EBS_INTF.XXNUC_AP_INVOICE_LINES
(
  INVOICE_LINE_KEY          NUMBER,
  INVOICE_HEADER_KEY        NUMBER,
  INVOICE_NUM               VARCHAR2(50 BYTE),
  LINE_NUMBER               NUMBER,
  GL_CONCATENATED_SEGMENTS  VARCHAR2(2000 BYTE),
  LINE_TYPE_LOOKUP_CODE     VARCHAR2(25 BYTE),
  AMOUNT                    NUMBER,
  ACCOUNTING_DATE           DATE,
  DESCRIPTION               VARCHAR2(240 BYTE),
  TYPE_1099                 VARCHAR2(10 BYTE),
  INCOME_TAX_REGION         VARCHAR2(10 BYTE),
  PO_NUMBER                 VARCHAR2(100 BYTE),
  ATTRIBUTE_CATEGORY        VARCHAR2(30 BYTE),
  ATTRIBUTE1                VARCHAR2(150 BYTE),
  ATTRIBUTE2                VARCHAR2(150 BYTE),
  ATTRIBUTE3                VARCHAR2(150 BYTE),
  ATTRIBUTE4                VARCHAR2(150 BYTE),
  ATTRIBUTE5                VARCHAR2(150 BYTE),
  ATTRIBUTE6                VARCHAR2(150 BYTE),
  ATTRIBUTE7                VARCHAR2(150 BYTE),
  ATTRIBUTE8                VARCHAR2(150 BYTE),
  ATTRIBUTE9                VARCHAR2(150 BYTE),
  ATTRIBUTE10               VARCHAR2(150 BYTE),
  ATTRIBUTE11               VARCHAR2(150 BYTE),
  ATTRIBUTE12               VARCHAR2(150 BYTE),
  ATTRIBUTE13               VARCHAR2(150 BYTE),
  ATTRIBUTE14               VARCHAR2(150 BYTE),
  ATTRIBUTE15               VARCHAR2(150 BYTE),
  OPERATING_UNIT            VARCHAR2(240 BYTE),
  VENDOR_NUM                VARCHAR2(30 BYTE),
  TAX_CODE                  VARCHAR2(30 BYTE),
  BATCH_NAME                VARCHAR2(120 BYTE),
  CREATION_DATE             DATE,
  LAST_UPDATE_DATE          DATE,
  CREATED_BY                VARCHAR2(240 BYTE),
  LAST_UPDATED_BY           VARCHAR2(240 BYTE),
  PROCESS_DATE              DATE,
  PROCESS_STATUS            VARCHAR2(100 BYTE),
  ERROR_MSG                 VARCHAR2(2000 BYTE),
  REQUEST_ID                VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX EBS_INTF.XXNUC_AP_INVOICE_LINES_N2 ON EBS_INTF.XXNUC_AP_INVOICE_LINES
(INVOICE_HEADER_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EBS_INTF.XXNUC_AP_INVOICE_LINES_U1 ON EBS_INTF.XXNUC_AP_INVOICE_LINES
(INVOICE_LINE_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EBS_INTF.XXNUC_AP_INVOICE_LINES TO NUCOR_DEV;
