DROP TABLE EBS_INTF.XXNUC_SUPPLIER_CONTACTS_OUT CASCADE CONSTRAINTS;

CREATE TABLE EBS_INTF.XXNUC_SUPPLIER_CONTACTS_OUT
(
  SUPPLIER_CONTACT_KEY  NUMBER,
  LEGACY_VENDOR_NUMBER  VARCHAR2(100 BYTE),
  REF_PARTY_ID          NUMBER,
  REF_PERSON_ID         NUMBER,
  REF_CONTACT_ID        NUMBER,
  CREATION_DATE         DATE,
  LAST_UPDATE_DATE      DATE,
  CREATED_BY            VARCHAR2(240 BYTE),
  LAST_UPDATED_BY       VARCHAR2(240 BYTE),
  PROCESS_DATE          DATE,
  PROCESS_STATUS        VARCHAR2(10 BYTE),
  ERROR_MSG             VARCHAR2(2000 BYTE),
  ATTRIBUTE_CATEGORY    VARCHAR2(30 BYTE),
  ATTRIBUTE1            VARCHAR2(150 BYTE),
  ATTRIBUTE2            VARCHAR2(150 BYTE),
  ATTRIBUTE3            VARCHAR2(150 BYTE),
  ATTRIBUTE4            VARCHAR2(150 BYTE),
  ATTRIBUTE5            VARCHAR2(150 BYTE),
  ATTRIBUTE6            VARCHAR2(150 BYTE),
  ATTRIBUTE7            VARCHAR2(150 BYTE),
  ATTRIBUTE8            VARCHAR2(150 BYTE),
  ATTRIBUTE9            VARCHAR2(150 BYTE),
  ATTRIBUTE10           VARCHAR2(150 BYTE),
  ATTRIBUTE11           VARCHAR2(150 BYTE),
  ATTRIBUTE12           VARCHAR2(150 BYTE),
  ATTRIBUTE13           VARCHAR2(150 BYTE),
  ATTRIBUTE14           VARCHAR2(150 BYTE),
  ATTRIBUTE15           VARCHAR2(150 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EBS_INTF.XXNUC_SUPPLIER_CONTACTS_OUT_U1 ON EBS_INTF.XXNUC_SUPPLIER_CONTACTS_OUT
(SUPPLIER_CONTACT_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT SELECT ON EBS_INTF.XXNUC_SUPPLIER_CONTACTS_OUT TO NUCOR_DEV;
