DROP TABLE EBS_INTF.XXNUC_AP_INVOICE_HEADERS CASCADE CONSTRAINTS;

CREATE TABLE EBS_INTF.XXNUC_AP_INVOICE_HEADERS
(
  INVOICE_HEADER_KEY           NUMBER,
  INVOICE_NUM                  VARCHAR2(50 BYTE),
  INVOICE_TYPE_LOOKUP_CODE     VARCHAR2(25 BYTE),
  INVOICE_DATE                 DATE,
  VENDOR_NUM                   VARCHAR2(30 BYTE),
  VENDOR_NAME                  VARCHAR2(240 BYTE),
  VENDOR_SITE_CODE             VARCHAR2(15 BYTE),
  INVOICE_AMOUNT               NUMBER,
  INVOICE_CURRENCY_CODE        VARCHAR2(15 BYTE),
  TERMS_NAME                   VARCHAR2(50 BYTE),
  DESCRIPTION                  VARCHAR2(240 BYTE),
  SOURCE                       VARCHAR2(80 BYTE),
  PAYMENT_CURRENCY_CODE        VARCHAR2(15 BYTE),
  DOC_CATEGORY_CODE            VARCHAR2(30 BYTE),
  PAYMENT_METHOD_LOOKUP_CODE   VARCHAR2(25 BYTE),
  PAY_GROUP_LOOKUP_CODE        VARCHAR2(25 BYTE),
  GL_DATE                      DATE,
  EXCLUSIVE_PAYMENT_FLAG       VARCHAR2(1 BYTE),
  TERMS_DATE                   DATE,
  INVOICE_RECEIVED_DATE        DATE,
  OPERATING_UNIT               VARCHAR2(240 BYTE),
  ACCTS_PAY_CODE_CONCATENATED  VARCHAR2(250 BYTE),
  VOUCHER_NUMBER               VARCHAR2(50 BYTE),
  ATTRIBUTE_CATEGORY           VARCHAR2(30 BYTE),
  ATTRIBUTE1                   VARCHAR2(150 BYTE),
  ATTRIBUTE2                   VARCHAR2(150 BYTE),
  ATTRIBUTE3                   VARCHAR2(150 BYTE),
  ATTRIBUTE4                   VARCHAR2(150 BYTE),
  ATTRIBUTE5                   VARCHAR2(150 BYTE),
  ATTRIBUTE6                   VARCHAR2(150 BYTE),
  ATTRIBUTE7                   VARCHAR2(150 BYTE),
  ATTRIBUTE8                   VARCHAR2(150 BYTE),
  ATTRIBUTE9                   VARCHAR2(150 BYTE),
  ATTRIBUTE10                  VARCHAR2(150 BYTE),
  ATTRIBUTE11                  VARCHAR2(150 BYTE),
  ATTRIBUTE12                  VARCHAR2(150 BYTE),
  ATTRIBUTE13                  VARCHAR2(150 BYTE),
  ATTRIBUTE14                  VARCHAR2(150 BYTE),
  ATTRIBUTE15                  VARCHAR2(150 BYTE),
  BATCH_NAME                   VARCHAR2(120 BYTE),
  CREATION_DATE                DATE,
  LAST_UPDATE_DATE             DATE,
  CREATED_BY                   VARCHAR2(240 BYTE),
  LAST_UPDATED_BY              VARCHAR2(240 BYTE),
  PROCESS_DATE                 DATE,
  PROCESS_STATUS               VARCHAR2(100 BYTE),
  ERROR_MSG                    VARCHAR2(2000 BYTE),
  REQUEST_ID                   VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EBS_INTF.XXNUC_AP_INVOICE_HEADERS_N1 ON EBS_INTF.XXNUC_AP_INVOICE_HEADERS
(INVOICE_HEADER_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EBS_INTF.XXNUC_AP_INVOICE_HEADERS TO NUCOR_DEV;
