DROP TABLE EBS_INTF.XXNUC_SUPPLIER_CONTACTS_IN CASCADE CONSTRAINTS;

CREATE TABLE EBS_INTF.XXNUC_SUPPLIER_CONTACTS_IN
(
  SUPPLIER_CONTACT_KEY    NUMBER,
  OPERATING_UNIT          VARCHAR2(100 BYTE),
  PARTY_ID                NUMBER,
  RECORD_ID               NUMBER,
  STATUS                  VARCHAR2(100 BYTE),
  SOURCE_SYSTEM           VARCHAR2(100 BYTE),
  ROLE_PRIMARY_FLAG       VARCHAR2(100 BYTE),
  ROLE_TYPE               VARCHAR2(100 BYTE),
  RELATIONSHIP_TYPE       VARCHAR2(100 BYTE),
  RELATIONSHIP_CODE       VARCHAR2(100 BYTE),
  RANK                    VARCHAR2(100 BYTE),
  REFERENCE_USE_FLAG      VARCHAR2(100 BYTE),
  JOB_TITLE_CODE          VARCHAR2(100 BYTE),
  DECISION_MAKER_FLAG     VARCHAR2(100 BYTE),
  JOB_TITLE               VARCHAR2(100 BYTE),
  DEPARTMENT              VARCHAR2(100 BYTE),
  DEPARTMENT_CODE         VARCHAR2(100 BYTE),
  PRIMARY_BY_PURPOSE      VARCHAR2(100 BYTE),
  CONTACT_POINT_PURPOSE   VARCHAR2(100 BYTE),
  URL                     VARCHAR2(100 BYTE),
  WEB_TYPE                VARCHAR2(100 BYTE),
  FAX_NUMBER              VARCHAR2(100 BYTE),
  FAX_AREA_CODE           VARCHAR2(100 BYTE),
  FAX_COUNTRY_CODE        VARCHAR2(100 BYTE),
  ALT_PHONE_LINE_TYPE     VARCHAR2(100 BYTE),
  ALT_PHONE_EXTENSION     VARCHAR2(100 BYTE),
  ALT_PHONE_NUMBER        VARCHAR2(100 BYTE),
  ALT_PHONE_AREA_CODE     VARCHAR2(100 BYTE),
  ALT_PHONE_COUNTRY_CODE  VARCHAR2(100 BYTE),
  PHONE_LINE_TYPE         VARCHAR2(100 BYTE),
  PHONE_EXTENSION         VARCHAR2(100 BYTE),
  PHONE_NUMBER            VARCHAR2(100 BYTE),
  PHONE_AREA_CODE         VARCHAR2(100 BYTE),
  PHONE_COUNTRY_CODE      VARCHAR2(100 BYTE),
  EMAIL_ADDRESS           VARCHAR2(200 BYTE),
  EMAIL_FORMAT            VARCHAR2(100 BYTE),
  PRIMARY_FLAG            VARCHAR2(100 BYTE),
  CONTACT_LAST_NAME       VARCHAR2(200 BYTE),
  CONTACT_FIRST_NAME      VARCHAR2(200 BYTE),
  CONTACT_NUMBER          VARCHAR2(100 BYTE),
  VENDOR_NUMBER           VARCHAR2(100 BYTE),
  PARTY_NAME              VARCHAR2(500 BYTE),
  CONTACT_POINT_LEVEL     VARCHAR2(100 BYTE),
  CONTACT_POINT_TYPE      VARCHAR2(100 BYTE),
  REF_PERSON_ID           NUMBER,
  REF_PARTY_ID            NUMBER,
  REF_ORG_CONTACT_ID      NUMBER,
  CREATION_DATE           DATE,
  LAST_UPDATE_DATE        DATE,
  CREATED_BY              VARCHAR2(240 BYTE),
  LAST_UPDATED_BY         VARCHAR2(240 BYTE),
  REQUEST_ID              VARCHAR2(100 BYTE),
  PROCESS_DATE            DATE,
  PROCESS_STATUS          VARCHAR2(100 BYTE),
  ERROR_MSG               VARCHAR2(2000 BYTE),
  ATTRIBUTE_CATEGORY      VARCHAR2(30 BYTE),
  ATTRIBUTE1              VARCHAR2(150 BYTE),
  ATTRIBUTE2              VARCHAR2(150 BYTE),
  ATTRIBUTE3              VARCHAR2(150 BYTE),
  ATTRIBUTE4              VARCHAR2(150 BYTE),
  ATTRIBUTE5              VARCHAR2(150 BYTE),
  ATTRIBUTE6              VARCHAR2(150 BYTE),
  ATTRIBUTE7              VARCHAR2(150 BYTE),
  ATTRIBUTE8              VARCHAR2(150 BYTE),
  ATTRIBUTE9              VARCHAR2(150 BYTE),
  ATTRIBUTE10             VARCHAR2(150 BYTE),
  ATTRIBUTE11             VARCHAR2(150 BYTE),
  ATTRIBUTE12             VARCHAR2(150 BYTE),
  ATTRIBUTE13             VARCHAR2(150 BYTE),
  ATTRIBUTE14             VARCHAR2(150 BYTE),
  ATTRIBUTE15             VARCHAR2(150 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EBS_INTF.XXNUC_SUPPLIER_CONTACTS_IN_U1 ON EBS_INTF.XXNUC_SUPPLIER_CONTACTS_IN
(SUPPLIER_CONTACT_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
