DROP TABLE EBS_INTF.XXNUC_AP_PAYMENTS_IN CASCADE CONSTRAINTS;

CREATE TABLE EBS_INTF.XXNUC_AP_PAYMENTS_IN
(
  PAYMENT_IN_KEY            NUMBER,
  PAYMENT_REFERENCE_NUMBER  VARCHAR2(240 BYTE),
  PAYMENT_DATE              DATE,
  PAYMENT_METHOD            VARCHAR2(100 BYTE),
  PAYMENT_AMOUNT            NUMBER,
  PAYMENT_STATUS            VARCHAR2(40 BYTE),
  INVOICE_NUM               VARCHAR2(240 BYTE),
  INVOICE_DATE              DATE,
  INVOICE_AMOUNT            NUMBER,
  EBS_VENDOR_NUM            VARCHAR2(40 BYTE),
  LEGACY_VENDOR_NUM         VARCHAR2(40 BYTE),
  VENDOR_NAME               VARCHAR2(240 BYTE),
  EBS_PAYMENT_ID            NUMBER,
  CREATION_DATE             DATE,
  LAST_UPDATE_DATE          DATE,
  CREATED_BY                VARCHAR2(240 BYTE),
  LAST_UPDATED_BY           VARCHAR2(240 BYTE),
  PROCESS_DATE              DATE,
  PROCESS_STATUS            VARCHAR2(100 BYTE),
  ERROR_MSG                 VARCHAR2(2000 BYTE),
  REQUEST_ID                VARCHAR2(100 BYTE),
  ATTRIBUTE_CATEGORY        VARCHAR2(30 BYTE),
  ATTRIBUTE1                VARCHAR2(150 BYTE),
  ATTRIBUTE2                VARCHAR2(150 BYTE),
  ATTRIBUTE3                VARCHAR2(150 BYTE),
  ATTRIBUTE4                VARCHAR2(150 BYTE),
  ATTRIBUTE5                VARCHAR2(150 BYTE),
  ATTRIBUTE6                VARCHAR2(150 BYTE),
  ATTRIBUTE7                VARCHAR2(150 BYTE),
  ATTRIBUTE8                VARCHAR2(150 BYTE),
  ATTRIBUTE9                VARCHAR2(150 BYTE),
  ATTRIBUTE10               VARCHAR2(150 BYTE),
  ATTRIBUTE11               VARCHAR2(150 BYTE),
  ATTRIBUTE12               VARCHAR2(150 BYTE),
  ATTRIBUTE13               VARCHAR2(150 BYTE),
  ATTRIBUTE14               VARCHAR2(150 BYTE),
  ATTRIBUTE15               VARCHAR2(150 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EBS_INTF.XXNUC_AP_PAYMENTS_IN_N1 ON EBS_INTF.XXNUC_AP_PAYMENTS_IN
(PAYMENT_IN_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
