<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_NSNE_QualitySpec_Stg"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAM/1.0"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext utl dvm socket"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns3="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAO/1.0"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/Manish/NSNE_SubscribeQualitySpecs_QMOS_ABF/JMS_DEQ_NextGen_DistributedTopic"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns7="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns8="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_SubscribeQualitySpecs_QMOS_ABF/DB_NSNE_QualitySpec_Stg">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_DEQ_NextGen_DistributedTopic.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualitySpecsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_NSNE_QualitySpec_Stg.wsdl"/>
        <oracle-xsl-mapper:rootElement name="L2XxnucQualitySpecsStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_NSNE_QualitySpec_Stg"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON NOV 16 03:49:30 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:L2XxnucQualitySpecsStgCollection>
      <xsl:for-each select="/ns0:QualitySpecsAddRq/ns3:QualitySpecsDetails">
        <tns:L2XxnucQualitySpecsStg>
          <xsl:if test="ns3:SPEC_ID">
            <tns:specId>
              <xsl:value-of select="ns3:SPEC_ID"/>
            </tns:specId>
          </xsl:if>
          <xsl:if test="ns3:SPEC_NAME">
            <tns:specName>
              <xsl:value-of select="ns3:SPEC_NAME"/>
            </tns:specName>
          </xsl:if>
          <xsl:if test="ns3:SPEC_VERS">
            <tns:specVers>
              <xsl:value-of select="ns3:SPEC_VERS"/>
            </tns:specVers>
          </xsl:if>
          <xsl:if test="ns3:SPEC_STATUS">
            <tns:specStatus>
              <xsl:value-of select="ns3:SPEC_STATUS"/>
            </tns:specStatus>
          </xsl:if>
          <xsl:if test="ns3:DESCRIPTION">
            <tns:description>
              <xsl:value-of select="ns3:DESCRIPTION"/>
            </tns:description>
          </xsl:if>
          <xsl:if test="ns3:SPEC_TYPE">
            <tns:specType>
              <xsl:value-of select="ns3:SPEC_TYPE"/>
            </tns:specType>
          </xsl:if>
          <xsl:if test="ns3:OVERLAY_IND">
          <tns:overlayInd>
            <xsl:value-of select="ns3:OVERLAY_IND"/>
          </tns:overlayInd>
          </xsl:if>
          <xsl:if test="ns3:BASE_SPEC">
          <tns:baseSpec>
            <xsl:value-of select="ns3:BASE_SPEC"/>
          </tns:baseSpec>
          </xsl:if>
          <xsl:if test="ns3:BASE_SPEC_VERSION">
          <tns:baseSpecVersion>
            <xsl:value-of select="ns3:BASE_SPEC_VERSION"/>
          </tns:baseSpecVersion>
          </xsl:if>
          <xsl:if test="ns3:INV_ITEM">
          <tns:invItem>
            <xsl:value-of select="ns3:INV_ITEM"/>
          </tns:invItem>
          </xsl:if>
          <xsl:if test="ns3:GRADE">
            <tns:grade>
              <xsl:value-of select="ns3:GRADE"/>
            </tns:grade>
          </xsl:if>
          <tns:ownerOrganizationCode>
            <xsl:value-of select="ns3:OWNER_ORGANIZATION_CODE"/>
          </tns:ownerOrganizationCode>
          <tns:ownerOrganizationName>
            <xsl:value-of select="ns3:OWNER_ORGANIZATION_NAME"/>
          </tns:ownerOrganizationName>
          <tns:ownerName>
            <xsl:value-of select="ns3:OWNER_NAME"/>
          </tns:ownerName>
          <tns:attributeCategory>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTECATEGORY"/>
          </tns:attributeCategory>
          <tns:attribute1>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE1"/>
          </tns:attribute1>
          <tns:attribute2>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE2"/>
          </tns:attribute2>
          <tns:attribute3>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE3"/>
          </tns:attribute3>
          <tns:attribute4>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE4"/>
          </tns:attribute4>
          <tns:attribute5>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE5"/>
          </tns:attribute5>
          <tns:attribute6>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE6"/>
          </tns:attribute6>
          <tns:attribute7>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE7"/>
          </tns:attribute7>
          <tns:attribute8>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE8"/>
          </tns:attribute8>
          <tns:attribute9>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE9"/>
          </tns:attribute9>
          <tns:attribute10>
            <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE10"/>
          </tns:attribute10>
          <tns:l2XxnucQspecTestsStgCollection>
            <xsl:for-each select="ns3:QUALITY_SPECS_TEST/ns3:QUALITY_SPECS_TEST">
              <xsl:if test=".">
                <tns:L2XxnucQspecTestsStg>
                  <xsl:if test="ns3:SEQ">
                    <tns:seq>
                      <xsl:value-of select="ns3:SEQ"/>
                    </tns:seq>
                  </xsl:if>
                  <tns:testName>
                    <xsl:value-of select="ns3:TEST_NAME"/>
                  </tns:testName>
                  <tns:testClass>
                    <xsl:value-of select="ns3:TEST_CLASS"/>
                  </tns:testClass>
                  <tns:testMethod>
                    <xsl:value-of select="ns3:TEST_METHOD"/>
                  </tns:testMethod>
                  <tns:targetValue>
                    <xsl:value-of select="ns3:TARGET_VALUE"/>
                  </tns:targetValue>
                  <tns:minimumValue>
                    <xsl:value-of select="ns3:MINIMUM_VALUE"/>
                  </tns:minimumValue>
                  <tns:maximumValue>
                    <xsl:value-of select="ns3:MAXIMUM_VALUE"/>
                  </tns:maximumValue>
                  <tns:testQty>
                    <xsl:value-of select="ns3:TEST_QTY"/>
                  </tns:testQty>
                  <tns:testQtyUom>
                    <xsl:value-of select="ns3:TEST_QTY_UOM"/>
                  </tns:testQtyUom>
                  <tns:testReplicate>
                    <xsl:value-of select="ns3:TEST_REPLICATE"/>
                  </tns:testReplicate>
                  <tns:testPriority>
                    <xsl:value-of select="ns3:TEST_PRIORITY"/>
                  </tns:testPriority>
                  <tns:optionalInd>
                    <xsl:value-of select="ns3:OPTIONAL_IND"/>
                  </tns:optionalInd>
                  <tns:retestLotExpiryInd>
                    <xsl:value-of select="ns3:RETEST_LOT_EXPIRY_IND"/>
                  </tns:retestLotExpiryInd>
                  <tns:outOfSpecAction>
                    <xsl:value-of select="ns3:OUT_OF_SPEC_ACTION"/>
                  </tns:outOfSpecAction>
                  <tns:checkResultInterval>
                    <xsl:value-of select="ns3:CHECK_RESULT_INTERVAL"/>
                  </tns:checkResultInterval>
                  <tns:belowSpecMin>
                    <xsl:value-of select="ns3:BELOW_SPEC_MIN"/>
                  </tns:belowSpecMin>
                  <tns:belowMinActionCode>
                    <xsl:value-of select="ns3:BELOW_MIN_ACTION_CODE"/>
                  </tns:belowMinActionCode>
                  <tns:aboveSpecMin>
                    <xsl:value-of select="ns3:ABOVE_SPEC_MIN"/>
                  </tns:aboveSpecMin>
                  <tns:aboveMinActionCode>
                    <xsl:value-of select="ns3:ABOVE_MIN_ACTION_CODE"/>
                  </tns:aboveMinActionCode>
                  <tns:belowSpecMax>
                    <xsl:value-of select="ns3:BELOW_SPEC_MAX"/>
                  </tns:belowSpecMax>
                  <tns:belowMaxActionCode>
                    <xsl:value-of select="ns3:BELOW_MAX_ACTION_CODE"/>
                  </tns:belowMaxActionCode>
                  <tns:aboveSpecMax>
                    <xsl:value-of select="ns3:ABOVE_SPEC_MAX"/>
                  </tns:aboveSpecMax>
                  <tns:aboveMaxActionCode>
                    <xsl:value-of select="ns3:ABOVE_MAX_ACTION_CODE"/>
                  </tns:aboveMaxActionCode>
                  <tns:testDisplay>
                    <xsl:value-of select="ns3:TEST_DISPLAY"/>
                  </tns:testDisplay>
                  <tns:printSpecInd>
                    <xsl:value-of select="ns3:PRINT_SPEC_IND"/>
                  </tns:printSpecInd>
                  <tns:printResultInd>
                    <xsl:value-of select="ns3:PRINT_RESULT_IND"/>
                  </tns:printResultInd>
                  <tns:displayPrecision>
                    <xsl:value-of select="ns3:DISPLAY_PRECISION"/>
                  </tns:displayPrecision>
                  <tns:reportPrecision>
                    <xsl:value-of select="ns3:REPORT_PRECISION"/>
                  </tns:reportPrecision>
                  <xsl:if test="ns3:DAYS">
                    <tns:days>
                      <xsl:value-of select="ns3:DAYS"/>
                    </tns:days>
                  </xsl:if>
                  <xsl:if test="ns3:HOURS">
                    <tns:hours>
                      <xsl:value-of select="ns3:HOURS"/>
                    </tns:hours>
                  </xsl:if>
                  <xsl:if test="ns3:MINUTES">
                    <tns:minutes>
                      <xsl:value-of select="ns3:MINUTES"/>
                    </tns:minutes>
                  </xsl:if>
                  <xsl:if test="ns3:SECONDS">
                    <tns:seconds>
                      <xsl:value-of select="ns3:SECONDS"/>
                    </tns:seconds>
                  </xsl:if>
                  <tns:attributeCategory>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTECATEGORY"/>
                  </tns:attributeCategory>
                  <tns:attribute1>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE1"/>
                  </tns:attribute1>
                  <tns:attribute2>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE2"/>
                  </tns:attribute2>
                  <tns:attribute3>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE3"/>
                  </tns:attribute3>
                  <tns:attribute4>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE4"/>
                  </tns:attribute4>
                  <tns:attribute5>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE5"/>
                  </tns:attribute5>
                  <tns:attribute6>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE6"/>
                  </tns:attribute6>
                  <tns:attribute7>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE7"/>
                  </tns:attribute7>
                  <tns:attribute8>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE8"/>
                  </tns:attribute8>
                  <tns:attribute9>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE9"/>
                  </tns:attribute9>
                  <tns:attribute10>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE10"/>
                  </tns:attribute10>
                  
                </tns:L2XxnucQspecTestsStg>
              </xsl:if>
            </xsl:for-each>
          </tns:l2XxnucQspecTestsStgCollection>
          <tns:l2XxnucQspecVrsStgCollection>
            <xsl:for-each select="ns3:QLTY_SPECS_VRS/ns3:QLTY_SPECS_VRS">
              <xsl:if test=".">
                <tns:L2XxnucQspecVrsStg>
                  <tns:specVrId>
                    <xsl:value-of select="ns3:SPEC_VR_ID"/>
                  </tns:specVrId>
                  <tns:organizationCode>
                    <xsl:value-of select="ns3:ORGANIZATION_CODE"/>
                  </tns:organizationCode>
                  <tns:specVrType>
                    <xsl:value-of select="ns3:SPEC_VR_TYPE"/>
                  </tns:specVrType>
                  <tns:specVrStatus>
                    <xsl:value-of select="ns3:SPEC_VR_STATUS"/>
                  </tns:specVrStatus>
                  <tns:startDate>
                    <xsl:value-of select="ns3:START_DATE"/>
                  </tns:startDate>
                  <tns:endDate>
                    <xsl:value-of select="ns3:END_DATE"/>
                  </tns:endDate>
                  <tns:samplingPlanName>
                    <xsl:value-of select="ns3:SAMPLING_PLAN_NAME"/>
                  </tns:samplingPlanName>
                  <tns:coaType>
                    <xsl:value-of select="ns3:COA_TYPE"/>
                  </tns:coaType>
                  <tns:coaAtShipInd>
                    <xsl:value-of select="ns3:COA_AT_SHIP_IND"/>
                  </tns:coaAtShipInd>
                  <tns:coaAtInvoiceInd>
                    <xsl:value-of select="ns3:COA_AT_INVOICE_IND"/>
                  </tns:coaAtInvoiceInd>
                  <tns:coaFromSupplierInd>
                    <xsl:value-of select="ns3:COA_FROM_SUPPLIER_IND"/>
                  </tns:coaFromSupplierInd>
                  <tns:lotOptionalOnSample>
                    <xsl:value-of select="ns3:LOT_OPTIONAL_ON_SAMPLE"/>
                  </tns:lotOptionalOnSample>
                  <tns:autoSampleInd>
                    <xsl:value-of select="ns3:AUTO_SAMPLE_IND"/>
                  </tns:autoSampleInd>
                  <tns:delayedLotEntry>
                    <xsl:value-of select="ns3:DELAYED_LOT_ENTRY"/>
                  </tns:delayedLotEntry>
                  <tns:delayedLpnEntry>
                    <xsl:value-of select="ns3:DELAYED_LPN_ENTRY"/>
                  </tns:delayedLpnEntry>
                  <tns:controlLotAttrbInd>
                    <xsl:value-of select="ns3:CONTROL_LOT_ATTRB_IND"/>
                  </tns:controlLotAttrbInd>
                  <tns:inSpecLotStatus>
                    <xsl:value-of select="ns3:IN_SPEC_LOT_STATUS"/>
                  </tns:inSpecLotStatus>
                  <tns:outOfSpecLotStatus>
                    <xsl:value-of select="ns3:OUT_OF_SPEC_LOT_STATUS"/>
                  </tns:outOfSpecLotStatus>
                  <tns:sampleInvTransInd>
                    <xsl:value-of select="ns3:SAMPLE_INV_TRANS_IND"/>
                  </tns:sampleInvTransInd>
                  <tns:operatingUnit>
                    <xsl:value-of select="ns3:OPERATING_UNIT"/>
                  </tns:operatingUnit>
                  <tns:parentLotNumber>
                    <xsl:value-of select="ns3:PARENT_LOT_NUMBER"/>
                  </tns:parentLotNumber>
                  <tns:lotNumber>
                    <xsl:value-of select="ns3:LOT_NUMBER"/>
                  </tns:lotNumber>
                  <xsl:if test="ns3:SUBINVENTORY">
                    <tns:subinventory>
                      <xsl:value-of select="ns3:SUBINVENTORY"/>
                    </tns:subinventory>
                  </xsl:if>
                  <tns:itemLocator>
                    <xsl:value-of select="ns3:ITEM_LOCATOR"/>
                  </tns:itemLocator>
                  <tns:batchNo>
                    <xsl:value-of select="ns3:BATCH_NO"/>
                  </tns:batchNo>
                  <tns:recipeNo>
                    <xsl:value-of select="ns3:RECIPE_NO"/>
                  </tns:recipeNo>
                  <tns:recipeVers>
                    <xsl:value-of select="ns3:RECIPE_VERS"/>
                  </tns:recipeVers>
                  <tns:formulaNo>
                    <xsl:value-of select="ns3:FORMULA_NO"/>
                  </tns:formulaNo>
                  <tns:formulaVers>
                    <xsl:value-of select="ns3:FORMULA_VERS"/>
                  </tns:formulaVers>
                  <tns:formulalineNo>
                    <xsl:value-of select="ns3:FORMULALINE_NO"/>
                  </tns:formulalineNo>
                  <tns:routingNo>
                    <xsl:value-of select="ns3:ROUTING_NO"/>
                  </tns:routingNo>
                  <tns:routingVers>
                    <xsl:value-of select="ns3:ROUTING_VERS"/>
                  </tns:routingVers>
                  <tns:stepNo>
                    <xsl:value-of select="ns3:STEP_NO"/>
                  </tns:stepNo>
                  <xsl:if test="ns3:CHARGE">
                    <tns:charge>
                      <xsl:value-of select="ns3:CHARGE"/>
                    </tns:charge>
                  </xsl:if>
                  <tns:oprnNo>
                    <xsl:value-of select="ns3:OPRN_NO"/>
                  </tns:oprnNo>
                  <tns:oprnVers>
                    <xsl:value-of select="ns3:OPRN_VERS"/>
                  </tns:oprnVers>
                  <tns:controlBatchStepInd>
                    <xsl:value-of select="ns3:CONTROL_BATCH_STEP_IND"/>
                  </tns:controlBatchStepInd>
                  <tns:autoCompleteBatchStep>
                    <xsl:value-of select="ns3:AUTO_COMPLETE_BATCH_STEP"/>
                  </tns:autoCompleteBatchStep>
                  <tns:customerNumber>
                    <xsl:value-of select="ns3:CUSTOMER_NUMBER"/>
                  </tns:customerNumber>
                  <tns:shiptoLocation>
                    <xsl:value-of select="ns3:SHIPTO_LOCATION"/>
                  </tns:shiptoLocation>
                  <tns:orderNumber>
                    <xsl:value-of select="ns3:ORDER_NUMBER"/>
                  </tns:orderNumber>
                  <tns:orderType>
                    <xsl:value-of select="ns3:ORDER_TYPE"/>
                  </tns:orderType>
                  <tns:orderLineNum>
                    <xsl:value-of select="ns3:ORDER_LINE_NUM"/>
                  </tns:orderLineNum>
                  <tns:supplierNo>
                    <xsl:value-of select="ns3:SUPPLIER_NO"/>
                  </tns:supplierNo>
                  <tns:supplierSite>
                    <xsl:value-of select="ns3:SUPPLIER_SITE"/>
                  </tns:supplierSite>
                  <tns:poNumber>
                    <xsl:value-of select="ns3:PO_NUMBER"/>
                  </tns:poNumber>
                  <tns:poLineNum>
                    <xsl:value-of select="ns3:PO_LINE_NUM"/>
                  </tns:poLineNum>
                  <tns:attributreCategory>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTECATEGORY"/>
                  </tns:attributreCategory>
                  <tns:attribute1>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE1"/>
                  </tns:attribute1>
                  <tns:attribute2>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE2"/>
                  </tns:attribute2>
                  <tns:attribute3>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE3"/>
                  </tns:attribute3>
                  <tns:attribute4>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE4"/>
                  </tns:attribute4>
                  <tns:attribute5>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE5"/>
                  </tns:attribute5>
                  <tns:attribute6>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE6"/>
                  </tns:attribute6>
                  <tns:attribute7>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE7"/>
                  </tns:attribute7>
                  <tns:attribute8>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE8"/>
                  </tns:attribute8>
                  <tns:attribute9>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE9"/>
                  </tns:attribute9>
                  <tns:attribute10>
                    <xsl:value-of select="ns3:ATTRIBUTE/ns3:ATTRIBUTE10"/>
                  </tns:attribute10>
                </tns:L2XxnucQspecVrsStg>
              </xsl:if>
            </xsl:for-each>
          </tns:l2XxnucQspecVrsStgCollection>
        </tns:L2XxnucQualitySpecsStg>
      </xsl:for-each>
    </tns:L2XxnucQualitySpecsStgCollection>
  </xsl:template>
</xsl:stylesheet>
