<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_EBS_Billet"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Billet_Trans"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_Billet_EBSMTLTrxImp_ABF/DB_EBS_Billet"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_Billet_EBSMTLTrxImp_ABF/DB_Update_Billet_Trans">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_EBS_Billet.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_EBS_Billet"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Update_Billet_Trans.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiBilletTransCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Billet_Trans"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAY 13 10:15:20 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ApiBilletTransCollection>
      <xsl:for-each select="/ns0:OutputParameters/ns0:P_RESULT_TAB/ns0:P_RESULT_TAB_ITEM">
        <tns:ApiBilletTrans>
          <tns:id>
            <xsl:value-of select="ns0:TRX_ID"/>
          </tns:id>
          <xsl:choose>
            <!--xsl:when test='xp20:compare (ns0:RESULT_CODE, "S" ) = 0 '-->
            <xsl:when test='ns0:RESULT_CODE="S"'>
              <tns:processed>C</tns:processed>
            </xsl:when>
            <xsl:otherwise>
              <tns:processed>E</tns:processed>
            </xsl:otherwise>
          </xsl:choose>
          <tns:processDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:processDate>
          <tns:errorMessage>
            <xsl:value-of select="ns0:RESULT_MESSAGE"/>
          </tns:errorMessage>
        </tns:ApiBilletTrans>
      </xsl:for-each>
    </tns:ApiBilletTransCollection>
  </xsl:template>
</xsl:stylesheet>
