<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:tns="http://xmlns.eia.com/ABS/EBiz/O2C/OrderABS/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/O2C/OrderAO/1.0"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns1="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns2="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/OrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryBasicSalesOrderRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/OrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryBasicSalesOrderResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU AUG 31 10:31:50 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:QueryBasicSalesOrderResponseMessage>
      <xsl:choose>
        <xsl:when test="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:TransactionRequestID !=''">
          <ns7:HeaderRs>
            <xsl:if test="not(/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:TransactionRequestID) and /ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:TransactionRequestID=''">
              <ns7:TransactionID>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:TransactionRequestID"/>
              </ns7:TransactionID>
            </xsl:if>
            <ns7:RequestDetails>
              <ns7:TransactionRequestID>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:TransactionRequestID"/>
              </ns7:TransactionRequestID>
              <ns7:Language>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:Language"/>
              </ns7:Language>
              <ns7:ComponentID>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:ComponentID"/>
              </ns7:ComponentID>
              <ns7:ServiceName>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:ServiceName"/>
              </ns7:ServiceName>
              <ns7:TransactionIDREF>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:TransactionIDREF"/>
              </ns7:TransactionIDREF>
              <ns7:TransactionName>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:TransactionName"/>
              </ns7:TransactionName>
              <ns7:FileName>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:FileName"/>
              </ns7:FileName>
              <ns7:FileInstanceID>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:FileInstanceID"/>
              </ns7:FileInstanceID>
              <ns7:Source>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:Source"/>
              </ns7:Source>
              <ns7:Target>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:Target"/>
              </ns7:Target>
              <ns7:HostName>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:HostName"/>
              </ns7:HostName>
              <ns7:UserName>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:UserName"/>
              </ns7:UserName>
              <ns7:UserRole>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:UserRole"/>
              </ns7:UserRole>
              <ns7:AdminEmail>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:AdminEmail"/>
              </ns7:AdminEmail>
              <ns7:ApplicationResponsibility>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:ApplicationResponsibility"/>
              </ns7:ApplicationResponsibility>
              <ns7:EOFFlag>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:EOFFlag"/>
              </ns7:EOFFlag>
              <ns7:SOFFlag>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:SOFFlag"/>
              </ns7:SOFFlag>
              <ns7:FileRecordCount>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:FileRecordCount"/>
              </ns7:FileRecordCount>
              <ns7:TimeStamp>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:TimeStamp"/>
              </ns7:TimeStamp>
              <ns7:MillName>
                <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns7:HeaderRq/ns7:MillName"/>
              </ns7:MillName>
            </ns7:RequestDetails>
            <ns7:ResultCount>0</ns7:ResultCount>
            <ns7:Status>E</ns7:Status>
          </ns7:HeaderRs>
        </xsl:when>
      </xsl:choose>
      <ns0:OperationResult>
        <ns1:Stats>E</ns1:Stats>
        <ns1:Errors>
          <ns1:OperationResultError>Either Organization Id or Organization Code should passed</ns1:OperationResultError>
        </ns1:Errors>
        <ns1:Warnings>
          <ns1:OperationResultWarning>Either Organization Id or Organization Code should passed</ns1:OperationResultWarning>
        </ns1:Warnings>
      </ns0:OperationResult>
    </ns0:QueryBasicSalesOrderResponseMessage>
  </xsl:template>
</xsl:stylesheet>
