<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_GetOrderDetails"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/SMG-nuc/NUC_EBizSalesOrder_ABS/DB_GetOrderDetails"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://xmlns.eia.com/ABS/EBiz/O2C/OrderABS/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/O2C/OrderAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_GetOrderDetails.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OeOrderHeadersAllCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_GetOrderDetails"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/OrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryBasicSalesOrderRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"/>
        <oracle-xsl-mapper:param name="QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/OrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryBasicSalesOrderResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED AUG 30 14:37:42 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage"/>
  <xsl:template match="/">
    <tns:QueryBasicSalesOrderResponseMessage>
      <xsl:variable name="varNumOfRecords" select="count (/ns0:OeOrderHeadersAllCollection/ns0:OeOrderHeadersAll )"/>
      <xsl:choose>
        <xsl:when test="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:TransactionRequestID !=''">
          <ns9:HeaderRs>
            <ns9:TransactionID>
              <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:TransactionRequestID"/>
            </ns9:TransactionID>
            <ns9:RequestDetails>
              <ns9:TransactionRequestID>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:TransactionRequestID"/>
              </ns9:TransactionRequestID>
              <ns9:Language>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:Language"/>
              </ns9:Language>
              <ns9:ComponentID>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:ComponentID"/>
              </ns9:ComponentID>
              <ns9:ServiceName>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:ServiceName"/>
              </ns9:ServiceName>
              <ns9:TransactionIDREF>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:TransactionIDREF"/>
              </ns9:TransactionIDREF>
              <ns9:TransactionName>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:TransactionName"/>
              </ns9:TransactionName>
              <ns9:FileName>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:FileName"/>
              </ns9:FileName>
              <ns9:FileInstanceID>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:FileInstanceID"/>
              </ns9:FileInstanceID>
              <ns9:Source>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:Source"/>
              </ns9:Source>
              <ns9:Target>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:Target"/>
              </ns9:Target>
              <ns9:HostName>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:HostName"/>
              </ns9:HostName>
              <ns9:UserName>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:UserName"/>
              </ns9:UserName>
              <ns9:UserRole>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:UserRole"/>
              </ns9:UserRole>
              <ns9:AdminEmail>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:AdminEmail"/>
              </ns9:AdminEmail>
              <ns9:ApplicationResponsibility>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:ApplicationResponsibility"/>
              </ns9:ApplicationResponsibility>
              <ns9:EOFFlag>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:EOFFlag"/>
              </ns9:EOFFlag>
              <ns9:SOFFlag>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:SOFFlag"/>
              </ns9:SOFFlag>
              <ns9:FileRecordCount>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:FileRecordCount"/>
              </ns9:FileRecordCount>
              <ns9:TimeStamp>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:TimeStamp"/>
              </ns9:TimeStamp>
              <ns9:MillName>
                <xsl:value-of select="$QueryBasicSalesOrderSyncReqMsg.QueryBasicSalesOrderRequestMessage/tns:QueryBasicSalesOrderRequestMessage/ns9:HeaderRq/ns9:MillName"/>
              </ns9:MillName>
            </ns9:RequestDetails>
            <ns9:ResultCount>
              <xsl:value-of select="$varNumOfRecords"/>
            </ns9:ResultCount>
            <xsl:choose>
              <xsl:when test="$varNumOfRecords=0">
                <ns9:Status>W</ns9:Status>
              </xsl:when>
              <xsl:otherwise>
                <ns9:Status>S</ns9:Status>
              </xsl:otherwise>
            </xsl:choose>
          </ns9:HeaderRs>
        </xsl:when>
      </xsl:choose>
      <tns:OperationResult>
        <xsl:choose>
          <xsl:when test="$varNumOfRecords=0">
            <ns3:Stats>W</ns3:Stats>
          </xsl:when>
          <xsl:otherwise>
            <ns3:Stats>S</ns3:Stats>
          </xsl:otherwise>
        </xsl:choose>
        <ns3:Errors>
          <xsl:choose>
            <xsl:when test="$varNumOfRecords=0">
              <ns3:OperationResultError>No data found for the parameters passed.</ns3:OperationResultError>
            </xsl:when>
          </xsl:choose>
        </ns3:Errors>
        <ns3:Warnings>
          <xsl:choose>
            <xsl:when test="$varNumOfRecords=0">
              <ns3:OperationResultWarning>No data found for the parameters passed.</ns3:OperationResultWarning>
            </xsl:when>
          </xsl:choose>
        </ns3:Warnings>
      </tns:OperationResult>
      <tns:ListOfBasicOrders>
        <xsl:for-each select="/ns0:OeOrderHeadersAllCollection/ns0:OeOrderHeadersAll">
          <tns:BasicOrder>
            <ns5:OrganizationId>
              <xsl:value-of select="ns0:OrderOrgInfo/ns0:organizationId"/>
            </ns5:OrganizationId>
            <ns5:OrganizationCode>
              <xsl:value-of select="ns0:OrderOrgInfo/ns0:shortCode"/>
            </ns5:OrganizationCode>
            <ns5:OrderNumber>
              <xsl:value-of select="ns0:orderNumber"/>
            </ns5:OrderNumber>
            <ns5:SoldToCustomerNumber>
              <xsl:value-of select="ns0:SoldToCustomer/ns0:accountNumber"/>
            </ns5:SoldToCustomerNumber>
            <ns5:SoldToCustomerName>
              <xsl:value-of select="ns0:SoldToCustomer/ns0:hzParties/ns0:partyName"/>
            </ns5:SoldToCustomerName>
            <ns5:HeaderId>
              <xsl:value-of select="ns0:headerId"/>
            </ns5:HeaderId>
            <ns5:OrderedDate>
              <xsl:value-of select="ns0:orderedDate"/>
            </ns5:OrderedDate>
            <ns5:OrigSysDocumentRef>
              <xsl:value-of select="ns0:origSysDocumentRef"/>
            </ns5:OrigSysDocumentRef>
            <ns5:CustomerPONumber>
              <xsl:value-of select="ns0:custPoNumber"/>
            </ns5:CustomerPONumber>
            <ns5:BillToCustomerName>
              <xsl:value-of select="ns0:BillToSiteInfo/ns0:hzCustAcctSitesAll/ns0:hzCustAccounts/ns0:hzParties/ns0:partyName"/>
            </ns5:BillToCustomerName>
            <ns5:BillToCustomerNumber>
              <xsl:value-of select="ns0:BillToSiteInfo/ns0:hzCustAcctSitesAll/ns0:hzCustAccounts/ns0:accountNumber"/>
            </ns5:BillToCustomerNumber>
            <ns5:ShipToCustomerNumber>
              <xsl:value-of select="ns0:ShipToSiteInfo/ns0:hzCustAcctSitesAll/ns0:hzCustAccounts/ns0:accountNumber"/>
            </ns5:ShipToCustomerNumber>
            <ns5:ShipToCustomerName>
              <xsl:value-of select="ns0:ShipToSiteInfo/ns0:hzCustAcctSitesAll/ns0:hzCustAccounts/ns0:hzParties/ns0:partyName"/>
            </ns5:ShipToCustomerName>
            <ns5:PriceListName>
              <xsl:value-of select="ns0:oePriceListsV/ns0:name"/>
            </ns5:PriceListName>
            <ns5:SalesRep>
              <xsl:value-of select="ns0:raSalesrepsAll/ns0:name"/>
            </ns5:SalesRep>
            <ns5:OrderSource>
              <xsl:value-of select="ns0:oeOrderSources/ns0:name"/>
            </ns5:OrderSource>
            <ns5:OrderTypeName>
              <xsl:value-of select="ns0:HeaderTransactionType/ns0:oeTransactionTypesTl/ns0:name"/>
            </ns5:OrderTypeName>
            <ns5:ShipFromOrg>
              <xsl:value-of select="ns0:OrderOrgInfo/ns0:shortCode"/>
            </ns5:ShipFromOrg>
            <ns5:FlowStatusCode>
              <xsl:value-of select="ns0:flowStatusCode"/>
            </ns5:FlowStatusCode>
            <ns5:TransactionalCurrencyCode>
              <xsl:value-of select="ns0:transactionalCurrCode"/>
            </ns5:TransactionalCurrencyCode>
            <tns:ListOfBasicOrderLines>
              <xsl:for-each select="ns0:oeOrderLinesAllCollection/ns0:OeOrderLinesAll">
                <ns5:BasicOrderLines>
                  <ns5:OrganizationId>
                    <xsl:value-of select="../../ns0:OrderOrgInfo/ns0:organizationId"/>
                  </ns5:OrganizationId>
                  <ns5:OrganizationCode>
                    <xsl:value-of select="../../ns0:OrderOrgInfo/ns0:shortCode"/>
                  </ns5:OrganizationCode>
                  <ns5:OrderNumber>
                    <xsl:value-of select="../../ns0:orderNumber"/>
                  </ns5:OrderNumber>
                  <ns5:OrderLineNumber>
                    <xsl:value-of select="ns0:lineNumber"/>
                  </ns5:OrderLineNumber>
                  <ns5:ShipmentNumber>
                    <xsl:value-of select="ns0:shipmentNumber"/>
                  </ns5:ShipmentNumber>
                  <ns5:OrderedItem>
                    <xsl:value-of select="ns0:orderedItem"/>
                  </ns5:OrderedItem>
                  <ns5:ItemIdentifierType>
                    <xsl:value-of select="ns0:itemIdentifierType"/>
                  </ns5:ItemIdentifierType>
                  <ns5:OrderLineType>
                    <xsl:value-of select="ns0:LineTransactionType/ns0:transactionTypeCode"/>
                  </ns5:OrderLineType>
                  <ns5:OriginalOrderedItem>
                    <xsl:value-of select="ns0:originalOrderedItem"/>
                  </ns5:OriginalOrderedItem>
                  <ns5:OriginalItemIdentifierType>
                    <xsl:value-of select="ns0:originalItemIdentifierType"/>
                  </ns5:OriginalItemIdentifierType>
                  <ns5:RequestDate>
                    <xsl:value-of select="ns0:requestDate"/>
                  </ns5:RequestDate>
                  <ns5:ScheduledShipDate>
                    <xsl:value-of select="ns0:scheduleShipDate"/>
                  </ns5:ScheduledShipDate>
                  <ns5:OrderedQuantityUOM>
                    <xsl:value-of select="ns0:orderQuantityUom"/>
                  </ns5:OrderedQuantityUOM>
                  <ns5:OrderedQuantity>
                    <xsl:value-of select="ns0:orderedQuantity"/>
                  </ns5:OrderedQuantity>
                  <ns5:OrderedQuantityUOM2>
                    <xsl:value-of select="ns0:orderedQuantityUom2"/>
                  </ns5:OrderedQuantityUOM2>
                  <ns5:OrderedQuantity2>
                    <xsl:value-of select="ns0:orderedQuantity2"/>
                  </ns5:OrderedQuantity2>
                  <ns5:UnitListPrice>
                    <xsl:value-of select="ns0:unitListPrice"/>
                  </ns5:UnitListPrice>
                  <ns5:UnitSellingPrice>
                    <xsl:value-of select="ns0:unitSellingPrice"/>
                  </ns5:UnitSellingPrice>
                  <ns5:TotalAmount>
                    <xsl:value-of select="(ns0:orderedQuantity * ns0:unitSellingPrice)"/>
                  </ns5:TotalAmount>
                  <ns5:TransactionalCurrencyCode>
                    <xsl:value-of select="../../ns0:transactionalCurrCode"/>
                  </ns5:TransactionalCurrencyCode>
                  <ns5:ShippingMethod>
                    <xsl:value-of select="ns0:shippingMethodCode"/>
                  </ns5:ShippingMethod>
                  <ns5:HeaderId>
                    <xsl:value-of select="../../ns0:headerId"/>
                  </ns5:HeaderId>
                  <ns5:LineId>
                    <xsl:value-of select="ns0:lineId"/>
                  </ns5:LineId>
                  <ns5:FlowStatusCode>
                    <xsl:value-of select="ns0:flowStatusCode"/>
                  </ns5:FlowStatusCode>
                  <ns5:ScheduleStatusCode>
                    <xsl:value-of select="ns0:scheduleStatusCode"/>
                  </ns5:ScheduleStatusCode>
                  <ns5:OrigSysLineRef>
                    <xsl:value-of select="ns0:origSysLineRef"/>
                  </ns5:OrigSysLineRef>
                  <ns5:LineCategoryCode>
                    <xsl:value-of select="ns0:lineCategoryCode"/>
                  </ns5:LineCategoryCode>
                </ns5:BasicOrderLines>
              </xsl:for-each>
            </tns:ListOfBasicOrderLines>
          </tns:BasicOrder>
        </xsl:for-each>
      </tns:ListOfBasicOrders>
    </tns:QueryBasicSalesOrderResponseMessage>
  </xsl:template>
</xsl:stylesheet>
