<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_GetOrderDetails"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:ns1="http://xmlns.eia.com/ABS/EBiz/O2C/OrderABS/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/O2C/OrderAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns3="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns8="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns10="http://xmlns.oracle.com/pcbpel/adapter/db/SMG-nuc/NUC_EBizSalesOrder_ABS/DB_GetOrderDetails"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/OrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryBasicSalesOrderRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_GetOrderDetails.wsdl"/>
        <oracle-xsl-mapper:rootElement name="DB_GetOrderDetailsParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_GetOrderDetails"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED AUG 30 14:26:59 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:DB_GetOrderDetailsParameters>
      <tns:pOrganizationId>
        <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrganizationId"/>
      </tns:pOrganizationId>
      <xsl:choose>
        <xsl:when test='contains (/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber, "-" )'>
          <tns:pOrderNumber>
            <xsl:value-of select="substring-before (/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber, '-' )"/>
          </tns:pOrderNumber>
        </xsl:when>
        <xsl:otherwise>
          <tns:pOrderNumber>
            <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber"/>
          </tns:pOrderNumber>
        </xsl:otherwise>
      </xsl:choose>
      <tns:pSoldToCustomerNumber>
        <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:SoldToCustomerNumber"/>
      </tns:pSoldToCustomerNumber>
      <tns:pSoldToCustomerName>
        <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:SoldToCustomerName"/>
      </tns:pSoldToCustomerName>
      <tns:pOrigSysDocumentRef>
        <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrigSysDocumentRef"/>
      </tns:pOrigSysDocumentRef>
      <tns:pHeaderId>
        <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:HeaderId"/>
      </tns:pHeaderId>
      <!--tns:pOrderedDate>
        <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderedDate"/>
      </tns:pOrderedDate-->
      <xsl:choose>
        <xsl:when test='contains (/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber, "-" )'>
          <tns:pLineNumber>
            <xsl:value-of select="substring-before(substring-after(/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber,'-'),'.')"/>
          </tns:pLineNumber>
        </xsl:when>
        <xsl:otherwise>
          <tns:pLineNumber/>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test='contains (/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber, "-" )'>
          <tns:pShipmentNumber>
            <xsl:value-of select="substring-after(substring-after(/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber,'-'),'.')"/>
          </tns:pShipmentNumber>
        </xsl:when>
        <xsl:otherwise>
          <tns:pShipmentNumber/>
        </xsl:otherwise>
      </xsl:choose>
      <tns:pOrganizationCode>
        <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrganizationCode"/>
      </tns:pOrganizationCode>
      <tns:pFlowStatusCode>
        <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:FlowStatusCode"/>
      </tns:pFlowStatusCode>
      <xsl:choose>
        <xsl:when test="/ns0:QueryBasicSalesOrderRequestMessage/@numRows !=''">
          <tns:pNumRows>
            <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/@numRows"/>
          </tns:pNumRows>
        </xsl:when>
        <xsl:otherwise>
          <tns:pNumRows>
            <xsl:value-of select="'10'"/>
          </tns:pNumRows>
        </xsl:otherwise>
      </xsl:choose>
    </tns:DB_GetOrderDetailsParameters>
  </xsl:template>
</xsl:stylesheet>
