<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:ns3="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/O2C/OrderAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns1="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns2="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:tns="http://xmlns.eia.com/ABS/EBiz/O2C/OrderABS/1.0"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/OrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryBasicSalesOrderRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/OrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryBasicSalesOrderRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/O2C/OrderAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI SEP 01 09:56:39 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:QueryBasicSalesOrderRequestMessage numRows="{/ns0:QueryBasicSalesOrderRequestMessage/@numRows}">
      <xsl:choose>
        <xsl:when test="count(/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:TransactionRequestID) >0">
          <ns3:HeaderRq>
            <ns3:TransactionRequestID>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:TransactionRequestID"/>
            </ns3:TransactionRequestID>
            <ns3:Language>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:Language"/>
            </ns3:Language>
            <ns3:ComponentID>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:ComponentID"/>
            </ns3:ComponentID>
            <ns3:ServiceName>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:ServiceName"/>
            </ns3:ServiceName>
            <ns3:TransactionIDREF>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:TransactionIDREF"/>
            </ns3:TransactionIDREF>
            <ns3:TransactionName>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:TransactionName"/>
            </ns3:TransactionName>
            <ns3:FileName>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:FileName"/>
            </ns3:FileName>
            <ns3:FileInstanceID>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:FileInstanceID"/>
            </ns3:FileInstanceID>
            <ns3:Source>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:Source"/>
            </ns3:Source>
            <ns3:Target>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:Target"/>
            </ns3:Target>
            <ns3:HostName>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:HostName"/>
            </ns3:HostName>
            <ns3:UserName>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:UserName"/>
            </ns3:UserName>
            <ns3:UserRole>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:UserRole"/>
            </ns3:UserRole>
            <ns3:AdminEmail>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:AdminEmail"/>
            </ns3:AdminEmail>
            <ns3:ApplicationResponsibility>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:ApplicationResponsibility"/>
            </ns3:ApplicationResponsibility>
            <ns3:EOFFlag>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:EOFFlag"/>
            </ns3:EOFFlag>
            <ns3:SOFFlag>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:SOFFlag"/>
            </ns3:SOFFlag>
            <ns3:FileRecordCount>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:FileRecordCount"/>
            </ns3:FileRecordCount>
            <ns3:TimeStamp>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:TimeStamp"/>
            </ns3:TimeStamp>
            <ns3:MillName>
              <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns3:HeaderRq/ns3:MillName"/>
            </ns3:MillName>
          </ns3:HeaderRq>
        </xsl:when>
      </xsl:choose>
      <ns0:AppsContext xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/@xsi:nil}">
        <ns6:UserName xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:UserName/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:UserName"/>
        </ns6:UserName>
        <ns6:UserId xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:UserId/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:UserId"/>
        </ns6:UserId>
        <ns6:ResponsibilityKey xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:ResponsibilityKey/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:ResponsibilityKey"/>
        </ns6:ResponsibilityKey>
        <ns6:ResponsibilityId xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:ResponsibilityId/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:ResponsibilityId"/>
        </ns6:ResponsibilityId>
        <ns6:ResponsibilityName xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:ResponsibilityName/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:ResponsibilityName"/>
        </ns6:ResponsibilityName>
        <ns6:ResponsibilityApplId xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:ResponsibilityApplId/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:ResponsibilityApplId"/>
        </ns6:ResponsibilityApplId>
        <ns6:SecurityGroup xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:SecurityGroup/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:SecurityGroup"/>
        </ns6:SecurityGroup>
        <ns6:SecurityGroupId xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:SecurityGroupId/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:SecurityGroupId"/>
        </ns6:SecurityGroupId>
        <ns6:Language xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:Language/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:Language"/>
        </ns6:Language>
        <ns6:OrganizationName xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:OrganizationName/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:OrganizationName"/>
        </ns6:OrganizationName>
        <ns6:OrgId xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:OrgId/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:OrgId"/>
        </ns6:OrgId>
        <ns6:MFGOrganizationId xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:MFGOrganizationId/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:AppsContext/ns6:MFGOrganizationId"/>
        </ns6:MFGOrganizationId>
      </ns0:AppsContext>
      <ns0:BasicOrder xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/@xsi:nil}">
        <ns0:OrganizationId xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrganizationId/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrganizationId"/>
        </ns0:OrganizationId>
        <ns0:OrganizationCode xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrganizationCode/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrganizationCode"/>
        </ns0:OrganizationCode>
        <ns0:OrderNumber xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderNumber"/>
        </ns0:OrderNumber>
        <ns0:SoldToCustomerNumber xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:SoldToCustomerNumber/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:SoldToCustomerNumber"/>
        </ns0:SoldToCustomerNumber>
        <ns0:SoldToCustomerName xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:SoldToCustomerName/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:SoldToCustomerName"/>
        </ns0:SoldToCustomerName>
        <ns0:SoldToContact xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:SoldToContact/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:SoldToContact"/>
        </ns0:SoldToContact>
        <ns0:HeaderId xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:HeaderId/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:HeaderId"/>
        </ns0:HeaderId>
        <ns0:OrderedDate xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderedDate/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:OrderedDate"/>
        </ns0:OrderedDate>
        <ns0:FlowStatusCode xsi:nil="{/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:FlowStatusCode/@xsi:nil}">
          <xsl:value-of select="/ns0:QueryBasicSalesOrderRequestMessage/ns0:BasicOrder/ns0:FlowStatusCode"/>
        </ns0:FlowStatusCode>
      </ns0:BasicOrder>
    </ns0:QueryBasicSalesOrderRequestMessage>
  </xsl:template>
</xsl:stylesheet>
