<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_API_RECIPE_ROUTING"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:ns3="http://nucor.eia.com/common"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/jms/Manish/NSUT_SubscribeProductStructure_EBiz_QMOS_ABF/JMS_DEQ_NextGenDistributedTopic"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns7="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAO/1.0"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns10="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSUT_SubscribeProductStructure_EBiz_QMOS_ABF/DB_Insert_API_RECIPE_ROUTING">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_DEQ_NextGenDistributedTopic.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryProductStructureAddRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/ProductStructureAM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_DEQ_NextGenDistributedTopic.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="g_ParamVar"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Insert_API_RECIPE_ROUTING.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiRecipeRoutingCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_API_RECIPE_ROUTING"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT FEB 06 05:20:06 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_ParamVar"/>
  <xsl:template match="/">
    <tns:ApiRecipeRoutingCollection>
      <xsl:for-each select="/ns0:QueryProductStructureAddRs/ns7:ProductStructureDetails">
        <xsl:if test="ns7:ListOfRecipe/ns7:ResourceName='RM1' or ns7:ListOfRecipe/ns7:ResourceName='RM2'">
          <tns:ApiRecipeRouting>
            <tns:id>
              <xsl:value-of select='oraext:sequence-next-val ("SEQ_API_RECIPE_ROUTING_ID", $g_ParamVar/ns1:parameters/ns1:item/ns1:value )'/>
            </tns:id>
            <xsl:choose>
              <xsl:when test="ns7:ListOfRecipe/ns7:ResourceName='RM1'">
                <tns:millId>
                  <xsl:value-of select="'PA'"/>
                </tns:millId>
              </xsl:when>
              <xsl:otherwise>
                <tns:millId>
                  <xsl:value-of select="'PB'"/>
                </tns:millId>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="ns7:ListOfRecipe/ns7:ListOfFormulas/ns7:Formulas/ns7:ListOfFormulaDetails/ns7:FormulaDetails[(ns7:FormulaItemType='Ingredient')]/ns7:ItemType = 'NUC_BILLET'">
                <tns:partCodeIn>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:ListOfFormulas/ns7:Formulas/ns7:ListOfFormulaDetails/ns7:FormulaDetails[(ns7:FormulaItemType='Ingredient') and (ns7:ItemType='NUC_BILLET')]/ns7:ItemNumber"/>
                </tns:partCodeIn>
              </xsl:when>
              <xsl:otherwise>
                <tns:partCodeIn>
                  <xsl:value-of select="ns7:ListOfRecipe/ns7:ListOfFormulas/ns7:Formulas/ns7:ListOfFormulaDetails/ns7:FormulaDetails[(ns7:FormulaItemType='Ingredient')]/ns7:ItemNumber"/>
                </tns:partCodeIn>
              </xsl:otherwise>
            </xsl:choose>
            <tns:partCodeOut>
              <xsl:value-of select="ns7:ListOfRecipe/ns7:Product"/>
            </tns:partCodeOut>
            <tns:mainBars>
              <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute1"/>
            </tns:mainBars>
            <xsl:if test=" ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute2 !='' and ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute2 != 'NaN' and  ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute2">
              <tns:bedLengthInches>
                <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute2 * 12"/>
              </tns:bedLengthInches>
            </xsl:if>
            <tns:shortBars>
              <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute4"/>
            </tns:shortBars>
            <xsl:if test="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute3 != '' and ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute3 != 'NaN' and ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute3">
              <tns:shortLengthInches>
                <xsl:value-of select="ns7:ListOfRecipe/ns7:Attribute/ns7:Attribute3 * 12"/>
              </tns:shortLengthInches>
            </xsl:if>
            <tns:billetCycleSeconds></tns:billetCycleSeconds>
            <tns:tonsPerHour>
              <xsl:value-of select="ns7:ListOfRecipe/ns7:ListOfRouting/ns7:Routings/ns7:ListOfOperartion/ns7:Operartions/ns7:ProcessQuantity"/>
            </tns:tonsPerHour>
            <xsl:for-each select="ns7:ListOfRecipe/ns7:ListOfRecipeVRS/ns7:RecipeVRS">
              <xsl:if test='xp20:compare (ns7:RecipeUse, "Production" ) = 0'>
                <tns:effectiveDate>
                  <xsl:value-of select="/ns0:QueryProductStructureAddRs/ns7:ProductStructureDetails/ns7:ListOfRecipe/ns7:ListOfRecipeVRS/ns7:RecipeVRS/ns7:Startdate"/>
                </tns:effectiveDate>
              </xsl:if>
            </xsl:for-each>
            <tns:userId>SOAUSER</tns:userId>
            <tns:processed>N</tns:processed>
            <tns:createDate>
              <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:createDate>
          </tns:ApiRecipeRouting>
        </xsl:if>
      </xsl:for-each>
    </tns:ApiRecipeRoutingCollection>
  </xsl:template>
</xsl:stylesheet>
