<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Billet_Trx"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Get_Billet_Trx"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSTX_Billet_EBSMTLTrxImp_ABF/DB_Get_Billet_Trx"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSTX_Billet_EBSMTLTrxImp_ABF/DB_Update_Billet_Trx">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Get_Billet_Trx.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiBilletTransCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Get_Billet_Trx"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Update_Billet_Trx.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiBilletTransCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Billet_Trx"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI APR 07 04:36:58 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ApiBilletTransCollection>
      <xsl:for-each select="/ns0:ApiBilletTransCollection/ns0:ApiBilletTrans">
        <tns:ApiBilletTrans>
          <tns:id>
            <xsl:value-of select="ns0:id"/>
          </tns:id>
          <tns:processed>R</tns:processed>
          <tns:apiBilletTransDtlsCollection>
            <xsl:for-each select="ns0:apiBilletTransDtlsCollection/ns0:ApiBilletTransDtls">
              <tns:ApiBilletTransDtls>
                <tns:id>
                  <xsl:value-of select="ns0:id"/>
                </tns:id>
                <tns:processed>R</tns:processed>
              </tns:ApiBilletTransDtls>
            </xsl:for-each>
          </tns:apiBilletTransDtlsCollection>
        </tns:ApiBilletTrans>
      </xsl:for-each>
    </tns:ApiBilletTransCollection>
  </xsl:template>
</xsl:stylesheet>
