<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://xmlns.eia.com/ABS/EBiz/A2R/AccountABS/1.0"
            xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.eia.com/ABS/EBiz/A2R/AccountABS/1.0"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
             xmlns:acctam="http://xmlns.eia.com/AO/EBiz/A2R/AccountAM/1.0">

  <wsdl:types>
  <xsd:schema>
    <xsd:import namespace="http://xmlns.eia.com/AO/EBiz/A2R/AccountAM/1.0" schemaLocation="../../../../AO/EBiz/A2R/V1.0/AccountAM.xsd"/>
    <xsd:import namespace="http://xmlns.eia.com/EO/Common/1.0" schemaLocation="../../../../EO/common/Common.xsd"/>
 </xsd:schema>
 </wsdl:types>


  <wsdl:message name="QueryByExampleSyncAccountRequestMessageType">
    <wsdl:part name="QueryByExampleSyncAccountRequestMessage" element="acctam:QueryByExampleAccountRequestMessage"/>
  </wsdl:message>

  <wsdl:message name="QueryByExampleAccountResponseMessageType">
    <wsdl:part name="QueryByExampleAccountResponseMessage" element="acctam:QueryByExampleAccountResponseMessage"/>
  </wsdl:message>

  <wsdl:message name="EIAFaultMsgType">
     <wsdl:part name="Fault" element="core:Fault"/>
  </wsdl:message>

  <wsdl:portType name="SyncPortType">
   
  
   
   <wsdl:operation name="QueryByExampleSyncAccount">
   <wsdl:input message="tns:QueryByExampleSyncAccountRequestMessageType"/>
   <wsdl:output message="tns:QueryByExampleAccountResponseMessageType"/>
   <wsdl:fault message="tns:EIAFaultMsgType" name="EIAFault"/>
   </wsdl:operation>
   
  
   
  </wsdl:portType>

  <wsdl:binding name="SyncPort" type="tns:SyncPortType">
    <soap:binding style="document"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
   
    
    
        <wsdl:operation name="QueryByExampleSyncAccount">
          <soap:operation style="document"
                          soapAction="http://xmlns.eia.com/ABS/EBiz/A2R/AccountABS/1.0/QueryByExampleSyncAccount"/>
          <wsdl:input>
            <soap:body use="literal" parts="QueryByExampleSyncAccountRequestMessage"/>
          </wsdl:input>
          <wsdl:output>
            <soap:body use="literal" parts="QueryByExampleAccountResponseMessage"/>
          </wsdl:output>
          <wsdl:fault name="EIAFault">
            <soap:fault name="EIAFault" use="literal"/>
          </wsdl:fault>
        </wsdl:operation>
        
       


    
    </wsdl:binding>
  
   <wsdl:service name="AccountABS">
    <wsdl:port name="SyncPort" binding="tns:SyncPort">
      <soap:address location="http://www.example.com"/>
    </wsdl:port>
   </wsdl:service>
  
</wsdl:definitions>
