<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:eia="http://xmlns.eia.com/extensions/1.0" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns1="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WI_Application/NUC_EBizSupplier_ABS/DB_QuerySupplierSitesEBS" xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0" xmlns:suplam="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAM/1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://xmlns.eia.com/ABS/EBiz/SupplierABS/1.0" xmlns:core="http://xmlns.eia.com/EO/Common/1.0" xmlns:ns7="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns5="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QuerySupplierSitesEBS" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0" xmlns:ns3="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0" xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns plt wsdl top xsd ns1 ns6 suplam soap12 soap mime ns0 core ns7 ns5 ns2 ns3 ns4 bpws xp20 eia bpel bpm utl ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../DB_QuerySupplierSitesEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxnucSupSiteOrigSysRefsVCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QuerySupplierSitesEBS"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/SupplierABS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="QueryByOrigSystemRef_BasicSupplierSiteResponseMessage" namespace="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAM/1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED SEP 09 14:06:58 CDT 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <suplam:QueryByOrigSystemRef_BasicSupplierSiteResponseMessage>
      <suplam:BasicSupplierSite>
        <ns2:Identifier>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:vendorSiteId"/>
        </ns2:Identifier>
        <ns2:SupplierSiteCode>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:vendorSiteCode"/>
        </ns2:SupplierSiteCode>
        <ns2:SupplierSiteCodeAlt>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:vendorSiteCodeAlt"/>
        </ns2:SupplierSiteCodeAlt>
        <ns2:SupplierTypeCode>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:poVendors/top:vendorTypeLookupCode"/>
        </ns2:SupplierTypeCode>
        <ns2:OrgName>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:poVendors/top:vendorName"/>
        </ns2:OrgName>
        <ns2:OrigSystem>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:origSystem"/>
        </ns2:OrigSystem>
        <ns2:OrigSystemReference>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:origSystemReference"/>
        </ns2:OrigSystemReference>
        <ns2:PaySiteFlag>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:paySiteFlag"/>
        </ns2:PaySiteFlag>
        <ns2:PurchasingSiteFlag>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:purchasingSiteFlag"/>
        </ns2:PurchasingSiteFlag>
        <ns2:RFQonlySiteFlag>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:rfqOnlySiteFlag"/>
        </ns2:RFQonlySiteFlag>
        <ns2:AttentionARFlag>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attentionArFlag"/>
        </ns2:AttentionARFlag>
        <ns2:OrgId>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:orgId"/>
        </ns2:OrgId>
        <ns2:VendorId>
          <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:vendorId"/>
        </ns2:VendorId>
        <ns2:Attributes>
          <ns4:Attribute1>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute1"/>
          </ns4:Attribute1>
          <ns4:Attribute2>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute2"/>
          </ns4:Attribute2>
          <ns4:Attribute3>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute3"/>
          </ns4:Attribute3>
          <ns4:Attribute4>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute4"/>
          </ns4:Attribute4>
          <ns4:Attribute5>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute5"/>
          </ns4:Attribute5>
          <ns4:Attribute6>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute6"/>
          </ns4:Attribute6>
          <ns4:Attribute7>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute7"/>
          </ns4:Attribute7>
          <ns4:Attribute8>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute8"/>
          </ns4:Attribute8>
          <ns4:Attribute9>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute9"/>
          </ns4:Attribute9>
          <ns4:Attribute10>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute10"/>
          </ns4:Attribute10>
          <ns4:Attribute11>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute11"/>
          </ns4:Attribute11>
          <ns4:Attribute12>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute12"/>
          </ns4:Attribute12>
          <ns4:Attribute13>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute13"/>
          </ns4:Attribute13>
          <ns4:Attribute14>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute14"/>
          </ns4:Attribute14>
          <ns4:Attribute15>
            <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:poVendorSitesAll/top:attribute15"/>
          </ns4:Attribute15>
        </ns2:Attributes>
        <ns2:ListOrigSystemReferences>
          <ns2:OrigSystem>
            <ns2:OrigSystem>
              <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:origSystem"/>
            </ns2:OrigSystem>
            <ns2:OrigSystemReference>
              <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:origSystemReference"/>
            </ns2:OrigSystemReference>
            <ns2:Status>
              <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:status"/>
            </ns2:Status>
            <ns2:StartDate>
              <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:startDateActive"/>
            </ns2:StartDate>
            <ns2:EndDate>
              <xsl:value-of select="/top:XxnucSupSiteOrigSysRefsVCollection/top:XxnucSupSiteOrigSysRefsV/top:endDateActive"/>
            </ns2:EndDate>
          </ns2:OrigSystem>
        </ns2:ListOrigSystemReferences>
      </suplam:BasicSupplierSite>
    </suplam:QueryByOrigSystemRef_BasicSupplierSiteResponseMessage>
  </xsl:template>
</xsl:stylesheet>