<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:eia="http://xmlns.eia.com/extensions/1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NUCOR/NUC_Emp_SAP_EBiz_ABF/DB_InsertSapSpsEmployee"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertSapSpsEmployee"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl xsd tns top plt wsdl eia xp20 bpws mhdr bpel oraext dvm hwf med ids bpm xdk xref utl ora socket ldap"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/NuePay_ReducedEmpDemo.xsd"/>
        <oracle-xsl-mapper:rootElement name="Envelope" namespace=""/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_InsertSapSpsEmployee.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucSapSpsEmployeeCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertSapSpsEmployee"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON SEP 28 14:53:32 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <top:XxnucSapSpsEmployeeCollection>
      <xsl:for-each select="/Envelope/Divisions/Division/ReducedPersons/ReducedPerson">
        <xsl:if test='(HireDate != "") and (Gender != "")'>
          <top:XxnucSapSpsEmployee>
            <top:sapEmpNum>
              <xsl:value-of select="SAPEmpNum"/>
            </top:sapEmpNum>
            <top:lastName>
              <xsl:value-of select="Name/Last"/>
            </top:lastName>
            <top:firstName>
              <xsl:value-of select="Name/First"/>
            </top:firstName>
            <top:middleInitial>
              <xsl:value-of select="Name/Middle"/>
            </top:middleInitial>
            <top:suffix>
              <xsl:value-of select="Name/Suffix"/>
            </top:suffix>
            <top:gender>
              <xsl:value-of select="Gender"/>
            </top:gender>
            <top:ledger>
              <xsl:value-of select='dvm:lookupValue("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_LEGACY_LEDGER_NAME_MAP.dvm","LEGACY_DIV_NUM",../../@DivCode,"EBS_LEDGER_NAME","")'/>
            </top:ledger>
            <xsl:choose>
              <xsl:when test="RehireDate > HireDate">
                <top:employmentDate>
                  <xsl:value-of select="RehireDate"/>
                </top:employmentDate>
              </xsl:when>
              <xsl:otherwise>
                <top:employmentDate>
                  <xsl:value-of select="HireDate"/>
                </top:employmentDate>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:if test='dvm:lookupValue("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_LEGACY_LEDGER_NAME_MAP.dvm","LEGACY_DIV_NUM",../../@DivCode,"LIVE_ON_ORACLE","N") = "Y"'>
              <xsl:choose>
                <xsl:when test="RehireDate > TerminationDate">
                  <top:employmentEndDate/>
                </xsl:when>
                <xsl:otherwise>
                  <top:employmentEndDate>
                    <xsl:value-of select="TerminationDate"/>
                  </top:employmentEndDate>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:if>
            <top:emailAddress>
              <xsl:value-of select="EMailAddress"/>
            </top:emailAddress>
            <top:addressLine1>
              <xsl:value-of select="Addresses/Address/Address1"/>
            </top:addressLine1>
            <top:addressLine2>
              <xsl:value-of select="Addresses/Address/Address2"/>
            </top:addressLine2>
            <top:city>
              <xsl:value-of select="Addresses/Address/City"/>
            </top:city>
            <top:state>
              <xsl:value-of select="Addresses/Address/State"/>
            </top:state>
            <top:zipCode>
              <xsl:value-of select="Addresses/Address/PostalCode"/>
            </top:zipCode>
            <top:country>
              <xsl:value-of select="Addresses/Address/Country"/>
            </top:country>
            <top:telephone>
              <xsl:value-of select="Addresses/Address/Phones/Phone"/>
            </top:telephone>
            <xsl:if test='Position/@PositionID != "99999999"'>
              <top:job>
                <xsl:value-of select="Position"/>
              </top:job>
            </xsl:if>
            <top:supervisorid>
              <xsl:value-of select="SupervisorName/@SAPEmpNum"/>
            </top:supervisorid>
            <xsl:choose>
              <xsl:when test='EmployeeGroup/@EmployeeGroupID = "3"'>
                <top:dept>
                  <xsl:text disable-output-escaping="no">Nucor Steel Business Group</xsl:text>
                </top:dept>
              </xsl:when>
              <xsl:otherwise>
                <top:dept>
                   <!--xsl:value-of select='xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_DEPT_NAME.xref","SAP",Department/@DepartmentID,"DEPT",false())'/-->
                   <xsl:text disable-output-escaping="no">Nucor Steel Business Group</xsl:text>
                </top:dept>
              </xsl:otherwise>
            </xsl:choose>
            <top:departmentid>
              <xsl:value-of select="Department/@DepartmentID"/>
            </top:departmentid>
            <top:personnelareaid>
              <xsl:value-of select="PersonnelArea/@PersonnelAreaID"/>
            </top:personnelareaid>
            <top:divNo>
              <xsl:value-of select="../../@DivCode"/>
            </top:divNo>
            <top:rehireDate>
              <xsl:value-of select="RehireDate"/>
            </top:rehireDate>
            <top:legacyEmployeeNumber>
              <xsl:value-of select="LegacyEmpNum"/>
            </top:legacyEmployeeNumber>
          </top:XxnucSapSpsEmployee>
        </xsl:if>
      </xsl:for-each>
    </top:XxnucSapSpsEmployeeCollection>
  </xsl:template>
</xsl:stylesheet>