<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertHrEmployee"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_EmpDataLoad"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/NUCOR/NUC_Emp_SAP_EBiz_ABF/DB_InsertHrEmployee"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/apps/NUCOR/NUC_Emp_SAP_EBiz_ABF/OA_EmpDataLoad"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_InsertHrEmployee.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucHrEmpIfaceStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertHrEmployee"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../OA_EmpDataLoad.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_EmpDataLoad"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI OCT 23 06:30:57 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:APPLICATION>XXNUC</tns:APPLICATION>
      <tns:PROGRAM>XXNUC_HR_EMP_IFACE</tns:PROGRAM>
      <tns:SUB_REQUEST/>
      <tns:p_mode>Interface</tns:p_mode>
      <tns:p_txn_id>
        <xsl:value-of select="/ns0:XxnucHrEmpIfaceStgCollection/ns0:XxnucHrEmpIfaceStg/ns0:txnId"/>
      </tns:p_txn_id>
      <tns:p_division>
        <xsl:value-of select="/ns0:XxnucHrEmpIfaceStgCollection/ns0:XxnucHrEmpIfaceStg/ns0:divisionNo"/>
      </tns:p_division>
      <tns:p_ledger_name>
        <xsl:value-of select="/ns0:XxnucHrEmpIfaceStgCollection/ns0:XxnucHrEmpIfaceStg/ns0:ledger"/>
      </tns:p_ledger_name>
      <tns:p_create_missing_Jobs>Y</tns:p_create_missing_Jobs>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
