<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:eia="http://xmlns.eia.com/extensions/1.0"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NucorPordSup/NUC_Emp_SAP_EBiz_ABF/DB_SelectUpdateEmpRecs"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_MergeSpsEmp"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/NUCOR/NUC_Emp_SAP_EBiz_ABF/DB_MergeSpsEmp"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns db plt wsdl xsd top ns0 bpws xp20 eia bpel bpm utl ora socket mhdr oraext dvm hwf med ids xdk xref ldap"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_SelectUpdateEmpRecs.wsdl"/>
        <oracle-xsl-mapper:rootElement name="DB_SelectUpdateEmpRecsOutputCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_MergeSpsEmp.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucSpsEmployeesCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_MergeSpsEmp"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON SEP 28 14:53:32 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <top:XxnucSpsEmployeesCollection>
      <xsl:for-each select="/db:DB_SelectUpdateEmpRecsOutputCollection/db:DB_SelectUpdateEmpRecsOutput">
        <top:XxnucSpsEmployees>
          <top:sapEmpNum>
            <xsl:value-of select="db:SAP_EMP_NUM"/>
          </top:sapEmpNum>
          <top:lastName>
            <xsl:value-of select="db:LAST_NAME"/>
          </top:lastName>
          <top:firstName>
            <xsl:value-of select="db:FIRST_NAME"/>
          </top:firstName>
          <top:middleInitial>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:MIDDLE_INITIAL/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:MIDDLE_INITIAL"/>
          </top:middleInitial>
          <top:suffix>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:SUFFIX/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:SUFFIX"/>
          </top:suffix>
          <top:gender>
            <xsl:value-of select="db:GENDER"/>
          </top:gender>
          <top:ledger>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:LEDGER/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:LEDGER"/>
          </top:ledger>
          <top:employmentDate>
            <xsl:value-of select="db:EMPLOYMENT_DATE"/>
          </top:employmentDate>
          <top:employmentEndDate>
            <xsl:value-of select="db:EMPLOYMENT_END_DATE"/>
          </top:employmentEndDate>
          <top:emailAddress>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:EMAIL_ADDRESS/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:EMAIL_ADDRESS"/>
          </top:emailAddress>
          <top:addressLine1>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:ADDRESS_LINE1/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:ADDRESS_LINE1"/>
          </top:addressLine1>
          <top:addressLine2>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:ADDRESS_LINE2/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:ADDRESS_LINE2"/>
          </top:addressLine2>
          <top:city>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:CITY/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:CITY"/>
          </top:city>
          <top:state>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:STATE/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:STATE"/>
          </top:state>
          <top:zipCode>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:ZIP_CODE/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:ZIP_CODE"/>
          </top:zipCode>
          <top:country>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:COUNTRY/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:COUNTRY"/>
          </top:country>
          <top:telephone>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:TELEPHONE/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:TELEPHONE"/>
          </top:telephone>
          <top:job>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:JOB/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:JOB"/>
          </top:job>
          <top:supervisorid>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:SUPERVISORID/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:SUPERVISORID"/>
          </top:supervisorid>
          <top:dept>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:DEPT/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:DEPT"/>
          </top:dept>
          <top:departmentid>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:DEPARTMENTID/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:DEPARTMENTID"/>
          </top:departmentid>
          <top:personnelareaid>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:PERSONNELAREAID/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:PERSONNELAREAID"/>
          </top:personnelareaid>
          <top:recordStatus>
            <xsl:text disable-output-escaping="no">SAVED</xsl:text>
          </top:recordStatus>
          <top:divNo>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="db:DIV_NO/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="db:DIV_NO"/>
          </top:divNo>
          <top:rehireDate>
            <xsl:value-of select="db:REHIRE_DATE"/>
          </top:rehireDate>
          <top:legacyEmployeeNumber>
            <xsl:value-of select="db:LEGACY_EMPLOYEE_NUMBER"/>
          </top:legacyEmployeeNumber>
        </top:XxnucSpsEmployees>
      </xsl:for-each>
    </top:XxnucSpsEmployeesCollection>
  </xsl:template>
</xsl:stylesheet>