<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://xmlns.eia.com/CommonLogging"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertHrEmployee"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/NucorPordSup/NUC_Emp_SAP_EBiz_ABF/DB_SelectUpdateEmpRecs"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/NUCOR/NUC_Emp_SAP_EBiz_ABF/DB_InsertHrEmployee"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_SelectUpdateEmpRecs.wsdl"/>
        <oracle-xsl-mapper:rootElement name="DB_SelectUpdateEmpRecsOutputCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/Infrastracture/wsdls/V1.0/CommonLogging.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Input" namespace="http://xmlns.eia.com/CommonLogging"/>
        <oracle-xsl-mapper:param name="g_Invoke_CommonLogging_PL_process_InputVariable.CommonLogging"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_InsertHrEmployee.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucHrEmpIfaceStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertHrEmployee"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE OCT 27 08:35:17 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_Invoke_CommonLogging_PL_process_InputVariable.CommonLogging"/>
  <xsl:template match="/">
    <tns:XxnucHrEmpIfaceStgCollection>
      <xsl:for-each select="/ns0:DB_SelectUpdateEmpRecsOutputCollection/ns0:DB_SelectUpdateEmpRecsOutput">
        <tns:XxnucHrEmpIfaceStg>
          <tns:lastName>
            <xsl:value-of select="xp20:upper-case(ns0:LAST_NAME)"/>
          </tns:lastName>
          <tns:firstName>
            <xsl:value-of select="xp20:upper-case(ns0:FIRST_NAME)"/>
          </tns:firstName>
          <tns:middleInitial>
            <xsl:value-of select="xp20:upper-case(ns0:MIDDLE_INITIAL)"/>
          </tns:middleInitial>
          <tns:suffix>
            <xsl:value-of select="xp20:upper-case(ns0:SUFFIX)"/>
          </tns:suffix>
          <tns:sourceSystemEmployeeNumber>
            <xsl:value-of select="ns0:SAP_EMP_NUM"/>
          </tns:sourceSystemEmployeeNumber>
          <tns:gender>
            <xsl:value-of select="xp20:upper-case(ns0:GENDER)"/>
          </tns:gender>
          <tns:ledger>
            <xsl:value-of select="ns0:LEDGER"/>
          </tns:ledger>
          <tns:employmentDate>
            <xsl:value-of select="ns0:employment_date"/>
          </tns:employmentDate>
          <tns:employmentEndDate>
            <xsl:value-of select="ns0:employment_end_date"/>
          </tns:employmentEndDate>
          <tns:emailAddress>
            <xsl:if test="ns0:EMAIL_ADDRESS/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="ns0:EMAIL_ADDRESS/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:EMAIL_ADDRESS"/>
          </tns:emailAddress>
          <tns:addressLine1>
            <xsl:value-of select="xp20:upper-case(ns0:ADDRESS_LINE1)"/>
          </tns:addressLine1>
          <tns:addressLine2>
            <xsl:value-of select="xp20:upper-case(ns0:ADDRESS_LINE2)"/>
          </tns:addressLine2>
          <tns:city>
            <xsl:value-of select="xp20:upper-case(ns0:CITY)"/>
          </tns:city>
          <tns:state>
            <xsl:value-of select="xp20:upper-case(ns0:STATE)"/>
          </tns:state>
          <tns:zipCode>
            <xsl:value-of select="ns0:ZIP_CODE"/>
          </tns:zipCode>
          <tns:country>
            <xsl:value-of select="ns0:COUNTRY"/>
          </tns:country>
          <tns:telephone>
            <xsl:value-of select="ns0:TELEPHONE"/>
          </tns:telephone>
          <xsl:if test='ns0:emp_status != "TERMINATE"'>
            <tns:job>
              <xsl:value-of select="ns0:JOB"/>
            </tns:job>
          </xsl:if>
          <xsl:if test='ns0:emp_status != "TERMINATE"'>
            <tns:supervisor>
              <xsl:value-of select="ns0:SUPERVISORID"/>
            </tns:supervisor>
          </xsl:if>
          <xsl:choose>
            <xsl:when test='ns0:EMP_STATUS = "TERMINATE"'>
              <tns:dept>
                <xsl:text disable-output-escaping="no">Nucor Steel Business Group</xsl:text>
              </tns:dept>
            </xsl:when>
            <xsl:otherwise>
              <tns:dept>
                <xsl:value-of select="ns0:DEPT"/>
              </tns:dept>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:if test='ns0:DEPARTMENTID != ""'>
            <tns:segment1>
              <xsl:value-of select='xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_DEPT_GL_SEG1.xref","SAP",ns0:DEPARTMENTID,"SEG1",false())'/>
            </tns:segment1>
          </xsl:if>
          <xsl:if test='ns0:DEPARTMENTID != ""'>
            <tns:segment2>
              <xsl:value-of select='xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_DEPT_GL_SEG2.xref","SAP",ns0:DEPARTMENTID,"SEG2",false())'/>
            </tns:segment2>
          </xsl:if>
          <xsl:if test='ns0:DEPARTMENTID != ""'>
            <tns:segment3>
              <xsl:value-of select='xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_DEPT_GL_SEG3.xref","SAP",ns0:DEPARTMENTID,"SEG3",false())'/>
            </tns:segment3>
          </xsl:if>
          <xsl:if test='ns0:DEPARTMENTID != ""'>
            <tns:segment4>
              <xsl:value-of select='xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_DEPT_GL_SEG4.xref","SAP",ns0:DEPARTMENTID,"SEG4",false())'/>
            </tns:segment4>
          </xsl:if>
          <tns:segment5>
            <xsl:text disable-output-escaping="no">0000</xsl:text>
          </tns:segment5>
          <tns:segment6>
            <xsl:text disable-output-escaping="no">0000</xsl:text>
          </tns:segment6>
          <tns:segment7>
            <xsl:text disable-output-escaping="no">0000</xsl:text>
          </tns:segment7>
          <!--
		  <tns:segment1>
            <xsl:value-of select='xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_DEPT_GL_SEG1.xref","SAP",ns0:DEPARTMENTID,"SEG1",false())'/>
          </tns:segment1>
          <tns:segment2>
            <xsl:text disable-output-escaping="no">00</xsl:text>
          </tns:segment2>
          <tns:segment3>
            <xsl:value-of select='xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_DEPT_GL_SEG3.xref","SAP",ns0:DEPARTMENTID,"SEG3",false())'/>
          </tns:segment3>
          <tns:segment4>
            <xsl:value-of select='xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_DEPT_GL_SEG4.xref","SAP",ns0:DEPARTMENTID,"SEG4",false())'/>
          </tns:segment4>
		  -->
          <tns:status>
            <xsl:value-of select="ns0:emp_status"/>
          </tns:status>
          <tns:requestId>
            <xsl:text disable-output-escaping="no">-1</xsl:text>
          </tns:requestId>
          <tns:processStatus>
            <xsl:text disable-output-escaping="no">New</xsl:text>
          </tns:processStatus>
          <tns:legacyEmployeeNumber>
            <xsl:value-of select="ns0:LEGACY_EMPLOYEE_NUMBER"/>
          </tns:legacyEmployeeNumber>
          <tns:divisionNo>
            <xsl:value-of select="ns0:DIV_NO"/>
          </tns:divisionNo>
          <tns:txnId>
            <xsl:value-of select="$g_Invoke_CommonLogging_PL_process_InputVariable.CommonLogging/ns1:Input/ns1:TransactionId"/></tns:txnId>
          <tns:lastDayWorked><xsl:value-of select="ns0:LAST_DAY_WORKED"/></tns:lastDayWorked>
        </tns:XxnucHrEmpIfaceStg>
      </xsl:for-each>
    </tns:XxnucHrEmpIfaceStgCollection>
  </xsl:template>
</xsl:stylesheet>
