<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_MergeSpsEmp"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/NucorPordSup/NUC_Emp_SAP_EBiz_ABF/DB_SelectUpdateEmpRecs"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/NUCOR/NUC_Emp_SAP_EBiz_ABF/DB_MergeSpsEmp">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_SelectUpdateEmpRecs.wsdl"/>
        <oracle-xsl-mapper:rootElement name="DB_SelectUpdateEmpRecsOutputCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_MergeSpsEmp.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucHrEmpBaseStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_MergeSpsEmp"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI OCT 23 05:54:22 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:XxnucHrEmpBaseStgCollection>
      <xsl:for-each select="/ns0:DB_SelectUpdateEmpRecsOutputCollection/ns0:DB_SelectUpdateEmpRecsOutput">
        <tns:XxnucHrEmpBaseStg>
          <tns:sapEmpNum>
            <xsl:value-of select="ns0:SAP_EMP_NUM"/>
          </tns:sapEmpNum>
          <tns:lastName>
            <xsl:value-of select="ns0:LAST_NAME"/>
          </tns:lastName>
          <tns:firstName>
            <xsl:value-of select="ns0:FIRST_NAME"/>
          </tns:firstName>
          <tns:middleInitial>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:MIDDLE_INITIAL/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:MIDDLE_INITIAL"/>
          </tns:middleInitial>
          <tns:suffix>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:SUFFIX/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:SUFFIX"/>
          </tns:suffix>
          <tns:gender>
            <xsl:value-of select="ns0:GENDER"/>
          </tns:gender>
          <tns:ledger>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:LEDGER/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:LEDGER"/>
          </tns:ledger>
          <tns:employmentDate>
            <xsl:value-of select="ns0:employment_date"/>
          </tns:employmentDate>
          <tns:employmentEndDate>
            <xsl:value-of select="ns0:employment_end_date"/>
          </tns:employmentEndDate>
          <tns:emailAddress>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:EMAIL_ADDRESS/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:EMAIL_ADDRESS"/>
          </tns:emailAddress>
          <tns:addressLine1>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:ADDRESS_LINE1/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:ADDRESS_LINE1"/>
          </tns:addressLine1>
          <tns:addressLine2>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:ADDRESS_LINE2/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:ADDRESS_LINE2"/>
          </tns:addressLine2>
          <tns:city>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:CITY/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:CITY"/>
          </tns:city>
          <tns:state>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:STATE/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:STATE"/>
          </tns:state>
          <tns:zipCode>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:ZIP_CODE/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:ZIP_CODE"/>
          </tns:zipCode>
          <tns:country>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:COUNTRY/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:COUNTRY"/>
          </tns:country>
          <tns:telephone>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:TELEPHONE/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:TELEPHONE"/>
          </tns:telephone>
          <tns:job>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:JOB/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:JOB"/>
          </tns:job>
          <tns:supervisorid>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:SUPERVISORID/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:SUPERVISORID"/>
          </tns:supervisorid>
          <tns:dept>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:DEPT/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:DEPT"/>
          </tns:dept>
          <tns:departmentid>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:DEPARTMENTID/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:DEPARTMENTID"/>
          </tns:departmentid>
          <tns:personnelareaid>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:PERSONNELAREAID/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:PERSONNELAREAID"/>
          </tns:personnelareaid>
          <tns:recordStatus>
            <xsl:text disable-output-escaping="no">SAVED</xsl:text>
          </tns:recordStatus>
          <tns:divNo>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="ns0:DIV_NO/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="ns0:DIV_NO"/>
          </tns:divNo>
          <tns:rehireDate>
            <xsl:value-of select="ns0:REHIRE_DATE"/>
          </tns:rehireDate>
          <tns:legacyEmployeeNumber>
            <xsl:value-of select="ns0:LEGACY_EMPLOYEE_NUMBER"/>
          </tns:legacyEmployeeNumber>
          <tns:lastDayWorked><xsl:value-of select="ns0:LAST_DAY_WORKED"/></tns:lastDayWorked>
        </tns:XxnucHrEmpBaseStg>
      </xsl:for-each>
    </tns:XxnucHrEmpBaseStgCollection>
  </xsl:template>
</xsl:stylesheet>
