<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 ns1 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptAO/1.0"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns12="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/DV1Application/NUC_SubscribeEBizPOReceipt_JMS_DJJ_ABF/JMSConsumePOReceipt"
                xmlns:ns19="http://xmlns.eia.com/AO/EBiz/common/CategoryAO/1.0"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns10="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns15="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns14="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns17="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0"
                xmlns:ns16="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns18="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns20="http://xmlns.oracle.com/DV1Application/NUC_SubscribeEBizPOReceipt_JMS_DJJ_ABF/Rest_DJJCreateReceipt"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMSConsumePOReceipt.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryReceiptResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMSConsumePOReceipt.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="tmp_Parameter"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Rest_DJJCreateReceipt.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MillShippingNotice" namespace=""/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE APR 26 03:08:46 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="tmp_Parameter"/>
  <xsl:template match="/">
    <xsl:variable name="RcptLineIdx"
                  select="number($tmp_Parameter/ns1:parameters/ns1:item[ns1:name = 'RcptLineIdx']/ns1:value)"/>
    <MillShippingNotice>
      <xsl:choose>
        <xsl:when test="(/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:Asnstatus = 'X') or (/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:Asnstatus = 'E')">
          <Active>false</Active>
        </xsl:when>
        <xsl:otherwise>
          <Active>true</Active>
        </xsl:otherwise>
      </xsl:choose>
      <!--       <CustomerContractLineId>
        <xsl:value-of select="/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:ListOfBasicReceiptLines/ns6:ReceiptLine[$RcptLineIdx]/ns6:BasicPurchaseOrderLine/ns17:PurchaseOrderNumber"/>
      </CustomerContractLineId> -->
      <ConsumerId>
        <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_CUSTOMERID_DEFAULTS.dvm", "EBS_OPERATING_UNIT_NAME", /ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:OperatingUnit, "DJJ_CUSTOMER_ID", "" )'/>
      </ConsumerId>
      <xsl:variable name="varShipToOrganization"
                    select="oraext:query-database (concat(&quot;SELECT ood.organization_code FROM po_lines_all pla, po_distributions_all pda, org_organization_definitions ood WHERE pla.po_line_id = pda.po_line_id AND pla.po_line_id = '&quot;,/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:ListOfBasicReceiptLines/ns6:ReceiptLine[$RcptLineIdx]/ns6:BasicPurchaseOrderLine/ns17:POIndentfierID,&quot;' AND ood.organization_id = pda.destination_organization_id AND rownum = 1&quot;), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
      <CustomerRefID>
        <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm", "EBS_SHIP_TO_ORGANIZATION", $varShipToOrganization, "CONSUMER_REF_ID", "" )'/>
      </CustomerRefID>
      <DateShipped>
        <xsl:value-of select='substring-before (/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:Shippeddate, "T" )'/>
      </DateShipped>
      <MethodOfTransport>
        <xsl:value-of select="oraext:query-database (concat (&quot;SELECT attribute2 from po_lines_all where po_line_id = '&quot;, /ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:ListOfBasicReceiptLines/ns6:ReceiptLine[$RcptLineIdx]/ns6:BasicPurchaseOrderLine/ns17:POIndentfierID, &quot;'&quot; ), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
      </MethodOfTransport>
      <MillContractNum>
        <xsl:value-of select="concat(/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:ListOfBasicReceiptLines/ns6:ReceiptLine[$RcptLineIdx]/ns6:BasicPurchaseOrder/ns17:PurchaseOrderNumber,'-',/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:ListOfBasicReceiptLines/ns6:ReceiptLine[$RcptLineIdx]/ns6:BasicPurchaseOrderLine/ns17:PurchaseOrderNumber)"/>
      </MillContractNum>
      <PackingList>
        <xsl:value-of select="/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:ListOfBasicReceiptLines/ns6:ReceiptLine[$RcptLineIdx]/ns6:PackingSlip"/>
      </PackingList>
      <ShipmentRefID>
        <xsl:value-of select="/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:BasicReceipt/ns6:ShipmentNumber"/>
      </ShipmentRefID>
      <ShippingNoticeRefID>
        <xsl:value-of select="/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:BasicReceipt/ns6:ShipmentNumber"/>
      </ShippingNoticeRefID>
      <VehicleID>
        <xsl:value-of select="/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:ListOfBasicReceiptLines/ns6:ReceiptLine[$RcptLineIdx]/ns6:TruckNum"/>
      </VehicleID>
      <WayBillNum>
        <xsl:value-of select="/ns0:QueryReceiptResponseMessage/ns0:ListOfReceipts/ns6:Receipt/ns6:Waybillairbillnum"/>
      </WayBillNum>
    </MillShippingNotice>
  </xsl:template>
</xsl:stylesheet>
