<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_L2"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext utl dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/I110/NSNE_SubscriberEBizJobDetails_JMS_L2_ABF/DB_Insert_L2"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Insert_L2.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Order_Schedule_StgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_L2"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Insert_L2.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Order_Schedule_StgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_L2"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE FEB 09 01:19:22 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:Order_Schedule_StgCollection>
      <xsl:for-each select="/ns0:Order_Schedule_StgCollection/ns0:Order_Schedule_Stg">
        <ns0:Order_Schedule_Stg>
          <xsl:if test="ns0:OrderNumber">
            <ns0:OrderNumber>
              <xsl:if test="ns0:OrderNumber/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:OrderNumber/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:OrderNumber"/>
            </ns0:OrderNumber>
          </xsl:if>
          <xsl:if test="ns0:PlannedTime">
            <ns0:PlannedTime>
              <xsl:if test="ns0:PlannedTime/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:PlannedTime/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:PlannedTime"/>
            </ns0:PlannedTime>
          </xsl:if>
          <xsl:choose>
            <xsl:when test="string-length (ns0:GradeID ) > 0">
              <ns0:GradeID>
                <xsl:value-of select="ns0:GradeID"/>
              </ns0:GradeID>
            </xsl:when>
            <xsl:otherwise>
              <ns0:GradeID>2</ns0:GradeID>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:if test="ns0:BilletSize">
            <ns0:BilletSize>
              <xsl:if test="ns0:BilletSize/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:BilletSize/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:BilletSize"/>
            </ns0:BilletSize>
          </xsl:if>
          <xsl:if test="ns0:TundishCode">
            <ns0:TundishCode>
              <xsl:if test="ns0:TundishCode/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:TundishCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:TundishCode"/>
            </ns0:TundishCode>
          </xsl:if>
          <xsl:if test="ns0:HeatComments">
            <ns0:HeatComments>
              <xsl:if test="ns0:HeatComments/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:HeatComments/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:HeatComments"/>
            </ns0:HeatComments>
          </xsl:if>
          <xsl:if test="ns0:HotInches">
            <ns0:HotInches>
              <xsl:if test="ns0:HotInches/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:HotInches/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:HotInches"/>
            </ns0:HotInches>
          </xsl:if>
          <ns0:BilletCount>
            <xsl:value-of select="ns0:BilletCount"/>
          </ns0:BilletCount>
          <xsl:if test="ns0:BilletComments">
            <ns0:BilletComments>
              <xsl:if test="ns0:BilletComments/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:BilletComments/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:BilletComments"/>
            </ns0:BilletComments>
          </xsl:if>
          <xsl:if test="ns0:SamplePractice">
            <ns0:SamplePractice>
              <xsl:if test="ns0:SamplePractice/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:SamplePractice/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:SamplePractice"/>
            </ns0:SamplePractice>
          </xsl:if>
          <ns0:OrderStatus>
            <xsl:value-of select="ns0:OrderStatus"/>
          </ns0:OrderStatus>
          <ns0:Produced>
            <xsl:value-of select="ns0:Produced"/>
          </ns0:Produced>
          <xsl:if test="ns0:HeatScheduleID">
            <ns0:HeatScheduleID>
              <xsl:if test="ns0:HeatScheduleID/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:HeatScheduleID/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:HeatScheduleID"/>
            </ns0:HeatScheduleID>
          </xsl:if>
          <xsl:if test="ns0:Pool">
            <ns0:Pool>
              <xsl:if test="ns0:Pool/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Pool/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Pool"/>
            </ns0:Pool>
          </xsl:if>
          <xsl:if test="ns0:OracleBatchID">
            <ns0:OracleBatchID>
              <xsl:if test="ns0:OracleBatchID/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:OracleBatchID/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:OracleBatchID"/>
            </ns0:OracleBatchID>
          </xsl:if>
          <xsl:if test="ns0:Process_Status">
            <ns0:Process_Status>
              <xsl:if test="ns0:Process_Status/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Process_Status/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Process_Status"/>
            </ns0:Process_Status>
          </xsl:if>
          <xsl:if test="ns0:Process_Date">
            <ns0:Process_Date>
              <xsl:if test="ns0:Process_Date/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Process_Date/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Process_Date"/>
            </ns0:Process_Date>
          </xsl:if>
          <xsl:if test="ns0:Error_Msg">
            <ns0:Error_Msg>
              <xsl:if test="ns0:Error_Msg/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Error_Msg/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Error_Msg"/>
            </ns0:Error_Msg>
          </xsl:if>
          <ns0:OrderWeight>
            <xsl:value-of select="ns0:OrderWeight"/>
          </ns0:OrderWeight>
          <ns0:OracleBatchNumber>
            <xsl:value-of select="ns0:OracleBatchNumber"/>
          </ns0:OracleBatchNumber>
          <ns0:EbsProductCode>
            <xsl:value-of select="ns0:EbsProductCode"/>
          </ns0:EbsProductCode>
        </ns0:Order_Schedule_Stg>
      </xsl:for-each>
    </ns0:Order_Schedule_StgCollection>
  </xsl:template>
</xsl:stylesheet>
