<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_L2"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAM/1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:ns7="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAO/1.0" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns3="http://nucor.eia.com"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/Nucor/NUC_SubscribeEBizJobDetails_JMS_L2_ABF/JMS_DEQ_NextGenDistributedTopic"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns10="http://xmlns.oracle.com/pcbpel/adapter/db/I110/NSNE_SubscriberEBizJobDetails_JMS_L2_ABF/DB_Insert_L2">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_DEQ_NextGenDistributedTopic.wsdl"/>
        <oracle-xsl-mapper:rootElement name="BatchJobAddRq"
                                       namespace="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Insert_L2.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Order_Schedule_StgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_L2"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU FEB 04 13:52:48 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Order_Schedule_StgCollection>
      <xsl:for-each select="/ns0:BatchJobAddRq/ns7:BatchJobDetails">
        <xsl:if test='not(ns7:BATCH_STATUS = "Completed" or ns7:BATCH_STATUS = "WIP")'>
          <tns:Order_Schedule_Stg>
            <tns:OrderNumber>0</tns:OrderNumber>
            <tns:PlannedTime>
              <xsl:value-of select="ns7:PLAN_START_DATE"/>
            </tns:PlannedTime>
            <xsl:variable name="varGradeId">
              <xsl:value-of select="oraext:query-database (concat (&quot;SELECT GradeID FROM dbo.Grade WHERE GradeName = '&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:UDA_GRADE, &quot;'&quot; ), false ( ), false ( ), &quot;jdbc/nsneL2&quot; )"/>
            </xsl:variable>
            <xsl:choose>
              <xsl:when test="string-length($varGradeId) > 0">
                <tns:GradeID>
                  <xsl:value-of select="$varGradeId"/>
                </tns:GradeID>
              </xsl:when>
              <xsl:otherwise>
                <tns:GradeID>
                  <xsl:value-of select="'2'"/>
                </tns:GradeID>
              </xsl:otherwise>
            </xsl:choose>
            <!--<tns:BilletSize>
            <xsl:value-of select="ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS/ns7:UDA_SIZE"/>
          </tns:BilletSize>-->
            <tns:BilletSize>0</tns:BilletSize>
            <tns:HotInches>
              <xsl:value-of select="ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:UDA_LENGTH"/>
            </tns:HotInches>
            <tns:BilletCount>
              <!--<xsl:value-of select="oraext:query-database (concat (&quot;SELECT ROUND (inv_convert.inv_um_convert_new (&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS/ns7:INVENTORY_ITEM_ID, &quot;&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS/ns7:PLAN_QTY, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS/ns7:DTL_UM, &quot;'EA'&quot;, &quot;&quot;, &quot;&quot;, &quot;'W')) secondary_quantity  FROM DUAL&quot; ), false(), false(), &quot;jdbc/ebsapps&quot; )"/>-->
              <xsl:value-of select="oraext:query-database (concat (&quot;SELECT ROUND ( inv_convert.inv_um_convert_new (&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:INVENTORY_ITEM_ID, &quot;,null,&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:PLAN_QTY, &quot;,'&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:DTL_UM, &quot;','EA',null,null, 'W')) result FROM DUAL&quot; ), false(), false(), &quot;jdbc/ebsapps&quot; )"/>
            </tns:BilletCount>
            <xsl:choose>
              <xsl:when test='(ns7:BATCH_STATUS = "Cancelled" or ns7:BATCH_STATUS = "Closed") or ns7:TERMINATED_IND = 1'>
                <tns:OrderStatus>1</tns:OrderStatus>
              </xsl:when>
              <xsl:otherwise>
                <tns:OrderStatus>0</tns:OrderStatus>
              </xsl:otherwise>
            </xsl:choose>
            <tns:Produced>0</tns:Produced>
            <tns:HeatScheduleID>0</tns:HeatScheduleID>
            <tns:OracleBatchID>
              <xsl:value-of select="ns7:BATCH_ID"/>
            </tns:OracleBatchID>
            <tns:OrderWeight>
              <!-- <xsl:value-of select="oraext:query-database (concat (&quot;SELECT ROUND (inv_convert.inv_um_convert_new (&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS/ns7:INVENTORY_ITEM_ID, &quot;null&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS/ns7:PLAN_QTY, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS/ns7:DTL_UM, &quot;LBS&quot;, &quot;null&quot;, &quot;null&quot;, &quot;'W')) secondary_quantity  FROM DUAL&quot; ), false(), false(), &quot;jdbc/ebsapps&quot; )"/> -->
              <xsl:value-of select="oraext:query-database (concat (&quot;SELECT ROUND ( inv_convert.inv_um_convert_new (&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:INVENTORY_ITEM_ID, &quot;,null,&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:PLAN_QTY, &quot;,'&quot;, ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:DTL_UM, &quot;','LBS',null,null, 'W')) result FROM DUAL&quot; ), false(), false(), &quot;jdbc/ebsapps&quot; )"/>
            </tns:OrderWeight>
            <tns:OracleBatchNumber>
              <xsl:value-of select="ns7:BATCH_NO"/>
            </tns:OracleBatchNumber>
            <tns:EBSProductCode>
              <xsl:value-of select="ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:ITEM_NO"/>
            </tns:EBSProductCode>
            <tns:EBSIngrdientCode>
              <xsl:value-of select="ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=-1][1]/ns7:ITEM_NO"/>
            </tns:EBSIngrdientCode>
          </tns:Order_Schedule_Stg>
        </xsl:if>
      </xsl:for-each>
    </tns:Order_Schedule_StgCollection>
  </xsl:template>
</xsl:stylesheet>
