<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAM/1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_HeatSchedule"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:ns7="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAO/1.0" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns3="http://nucor.eia.com"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/Nucor/NUC_SubscribeEBizJobDetails_JMS_L2_ABF/JMS_DEQ_NextGenDistributedTopic"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns10="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_SubscriberEBizJobDetails_EBiz_L2_ABF/DB_Insert_HeatSchedule">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_DEQ_NextGenDistributedTopic.wsdl"/>
        <oracle-xsl-mapper:rootElement name="BatchJobAddRq"
                                       namespace="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Insert_HeatSchedule.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Heat_Schedule_StgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_HeatSchedule"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU FEB 04 12:59:20 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Heat_Schedule_StgCollection>
      <xsl:for-each select="/ns0:BatchJobAddRq/ns7:BatchJobDetails">
        <tns:Heat_Schedule_Stg>
          <tns:id>0</tns:id>
          <xsl:choose>
            <xsl:when test='ns7:BATCH_STATUS = "Cancelled" or ns7:TERMINATED_IND = 1'>
              <tns:Status>1</tns:Status>
            </xsl:when>
            <xsl:otherwise>
              <tns:Status>0</tns:Status>
            </xsl:otherwise>
          </xsl:choose>
          <tns:PlannedTime>
            <xsl:value-of select="ns7:PLAN_START_DATE"/>
          </tns:PlannedTime>
          <tns:Tons>
            <xsl:value-of select=" round( ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:PLAN_QTY)"/>
          </tns:Tons>
          <tns:HeatStatus>Initial</tns:HeatStatus>
          <tns:EndProductSize>0</tns:EndProductSize>
          <tns:HeatSpec/>
          <tns:OracleBatchID>
            <xsl:value-of select="ns7:BATCH_ID"/>
          </tns:OracleBatchID>
          <tns:Process_Status/>
          <tns:EBS_Product_Code>
            <xsl:value-of select="ns7:GME_MATERIAL_DETAILS/ns7:GME_MATERIAL_DETAILS[ns7:LINE_TYPE=1][1]/ns7:ITEM_NO"/>
          </tns:EBS_Product_Code>
          <tns:OracleBatchNumber>
            <xsl:value-of select="ns7:BATCH_NO"/>
          </tns:OracleBatchNumber>
        </tns:Heat_Schedule_Stg>
      </xsl:for-each>
    </tns:Heat_Schedule_StgCollection>
  </xsl:template>
</xsl:stylesheet>
