--------------------------------------------------------
--  File created - Wednesday-September-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXNUC_AR_TRANS_HDR_STG
--------------------------------------------------------
DROP TABLE XXNUC_AR_TRANS_HDR_STG CASCADE CONSTRAINTS;
  CREATE TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" 
   (	"RECORD_ID" NUMBER, 
	"TRX_NUMBER" VARCHAR2(30 BYTE), 
	"INTERFACE_LINE_CONTEXT" VARCHAR2(30 BYTE), 
	"INTERFACE_HEADER_ATTRIBUTE1" VARCHAR2(30 BYTE), 
	"INTERFACE_HEADER_ATTRIBUTE2" VARCHAR2(30 BYTE), 
	"INTERFACE_HEADER_ATTRIBUTE3" VARCHAR2(30 BYTE), 
	"INTERFACE_HEADER_ATTRIBUTE4" VARCHAR2(30 BYTE), 
	"INTERFACE_HEADER_ATTRIBUTE5" VARCHAR2(30 BYTE), 
	"INTERFACE_HEADER_ATTRIBUTE6" VARCHAR2(30 BYTE), 
	"INTERFACE_HEADER_ATTRIBUTE7" VARCHAR2(30 BYTE), 
	"INTERFACE_HEADER_ATTRIBUTE8" VARCHAR2(30 BYTE), 
	"TRX_DATE" DATE, 
	"GL_DATE" DATE, 
	"BATCH_SOURCE_NAME" VARCHAR2(50 BYTE), 
	"ORIG_SYSTEM_BATCH_NAME" VARCHAR2(40 BYTE), 
	"CONVERSION_TYPE" VARCHAR2(30 BYTE), 
	"CONVERSION_DATE" DATE, 
	"CONVERSION_RATE" NUMBER, 
	"COMMENTS" VARCHAR2(240 BYTE), 
	"INTERNAL_NOTES" VARCHAR2(240 BYTE), 
	"CUST_TRX_TYPE_NAME" VARCHAR2(20 BYTE), 
	"TERM_NAME" VARCHAR2(15 BYTE), 
	"ORIG_SYSTEM_BILL_ADDRESS_REF" VARCHAR2(240 BYTE), 
	"ORIG_SYSTEM_BILL_CUSTOMER_REF" VARCHAR2(240 BYTE), 
	"HEADER_ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE15" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"HEADER_ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"PURCHASE_ORDER" VARCHAR2(50 BYTE), 
	"OPERATING_UNIT" VARCHAR2(240 BYTE), 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE)
   ) ;
--------------------------------------------------------
--  Constraints for Table XXNUC_AR_TRANS_HDR_STG
--------------------------------------------------------

  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("TRX_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("INTERFACE_LINE_CONTEXT" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("TRX_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("GL_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("BATCH_SOURCE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("CONVERSION_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("CUST_TRX_TYPE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("ORIG_SYSTEM_BILL_ADDRESS_REF" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("ORIG_SYSTEM_BILL_CUSTOMER_REF" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_HDR_STG" MODIFY ("OPERATING_UNIT" NOT NULL ENABLE);
  
  CREATE INDEX XXNUC_AR_TRANS_HDR_STG_N1 ON XXNUC_AR_TRANS_HDR_STG(TRX_NUMBER);
  CREATE INDEX XXNUC_AR_TRANS_HDR_STG_N2 ON XXNUC_AR_TRANS_HDR_STG(PROCESS_STATUS);



