--------------------------------------------------------
--  File created - Wednesday-September-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXNUC_GL_INT_STG
--------------------------------------------------------
 DROP TABLE XXNUC_GL_INT_STG CASCADE CONSTRAINTS;
  CREATE TABLE "XXNUC"."XXNUC_GL_INT_STG" 
   ( "GL_INT_KEY" NUMBER,	
     "BATCH_NAME" VARCHAR2(120 BYTE),
	 "LEDGER" VARCHAR2(30 BYTE), 
	"USER_JE_CATEGORY_NAME" VARCHAR2(25 BYTE), 
	"USER_JE_SOURCE_NAME" VARCHAR2(25 BYTE), 
	"ACCOUNTED_DR" NUMBER, 
	"ACCOUNTED_CR" NUMBER, 
	"REFERENCE1" VARCHAR2(100 BYTE), 
	"REFERENCE2" VARCHAR2(240 BYTE), 
	"REFERENCE4" VARCHAR2(100 BYTE), 
	"REFERENCE5" VARCHAR2(240 BYTE), 
	"REFERENCE7" VARCHAR2(240 BYTE), 
	"REFERENCE8" VARCHAR2(240 BYTE), 
	"REFERENCE10" VARCHAR2(240 BYTE), 
	"PERIOD_NAME" VARCHAR2(15 BYTE), 
	"ACCOUNT" VARCHAR2(240 BYTE), 
	"ATTRIBUTE1" VARCHAR2(240 BYTE), 
	"ACTUAL_FLAG" VARCHAR2(2 BYTE), 
	"ACCOUNTING_DATE" DATE, 
	"REQUEST_ID" NUMBER DEFAULT -1, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(2000 BYTE)
   )  ;
   
DROP SEQUENCE XXNUC_GL_INTERFACE_S ;

CREATE SEQUENCE  XXNUC_GL_INTERFACE_S  START WITH 1000 INCREMENT BY 1;

CREATE UNIQUE INDEX XXNUC_GL_INTERFACE_N1 ON XXNUC_GL_INT_STG ( GL_INT_KEY);
