--------------------------------------------------------
--  File created - Wednesday-September-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXNUC_AP_PAYMENTS_IN
--------------------------------------------------------
DROP TABLE XXNUC_AP_PAYMENTS_IN CASCADE CONSTRAINTS;
  CREATE TABLE "XXNUC"."XXNUC_AP_PAYMENTS_IN" 
   (	"PAYMENT_IN_KEY" NUMBER, 
	"PAYMENT_REFERENCE_NUMBER" VARCHAR2(240 BYTE), 
	"PAYMENT_DATE" DATE, 
	"PAYMENT_METHOD" VARCHAR2(100 BYTE), 
	"PAYMENT_AMOUNT" NUMBER, 
	"PAYMENT_STATUS" VARCHAR2(40 BYTE), 
	"INVOICE_NUM" VARCHAR2(240 BYTE), 
	"INVOICE_DATE" DATE, 
	"INVOICE_AMOUNT" NUMBER, 
	"EBS_VENDOR_NUM" VARCHAR2(40 BYTE), 
	"LEGACY_VENDOR_NUM" VARCHAR2(40 BYTE), 
	"VENDOR_NAME" VARCHAR2(240 BYTE), 
	"EBS_PAYMENT_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(240 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(240 BYTE), 
	"PROCESS_DATE" DATE, 
	"PROCESS_STATUS" VARCHAR2(100 BYTE), 
	"ERROR_MSG" VARCHAR2(2000 BYTE), 
	"REQUEST_ID" VARCHAR2(100 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE)
   )  ;
--------------------------------------------------------
--  DDL for Index XXNUC_AP_PAYMENTS_IN_N1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXNUC"."XXNUC_AP_PAYMENTS_IN_N1" ON "XXNUC"."XXNUC_AP_PAYMENTS_IN" ("PAYMENT_IN_KEY") ;
--------------------------------------------------------
--  SEQUENCE XXNUC_AP_PAYMENTS_IN_N1
--------------------------------------------------------

DROP SEQUENCE XXNUC_AP_PAYMENTS_IN_S ;

CREATE SEQUENCE  XXNUC_AP_PAYMENTS_IN_S  START WITH 1000 INCREMENT BY 1;

