--------------------------------------------------------
--  File created - Wednesday-September-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXNUC_SUPPLIER_CONTACTS_OUT
--------------------------------------------------------
DROP TABLE XXNUC_SUPPLIER_CONTACTS_OUT CASCADE CONSTRAINTS;

  CREATE TABLE "XXNUC"."XXNUC_SUPPLIER_CONTACTS_OUT" 
   (	"SUPPLIER_CONTACT_KEY" NUMBER, 
	"LEGACY_VENDOR_NUMBER" VARCHAR2(100 BYTE), 
	"REF_PARTY_ID" NUMBER, 
	"REF_PERSON_ID" NUMBER, 
	"REF_CONTACT_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(240 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(240 BYTE), 
	"PROCESS_DATE" DATE, 
	"PROCESS_STATUS" VARCHAR2(10 BYTE), 
	"ERROR_MSG" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Index XXNUC_SUPPLIER_CONTACTS_OUT_U1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXNUC"."XXNUC_SUPPLIER_CONTACTS_OUT_U1" ON "XXNUC"."XXNUC_SUPPLIER_CONTACTS_OUT" ("SUPPLIER_CONTACT_KEY");
--------------------------------------------------------
--  SEQUENCE XXNUC_SUPPLIER_CONTACTS_OUT_U1
--------------------------------------------------------
DROP SEQUENCE XXNUC_SUPPLIER_CONTACTS_OUT_S;
    
CREATE SEQUENCE  XXNUC_SUPPLIER_CONTACTS_OUT_S  START WITH 1000 INCREMENT BY 1;