--------------------------------------------------------
--  File created - Wednesday-September-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXNUC_AR_TRANS_LIN_STG
--------------------------------------------------------
DROP TABLE XXNUC_AR_TRANS_LIN_STG CASCADE CONSTRAINTS;
  CREATE TABLE "XXNUC"."XXNUC_AR_TRANS_LIN_STG" 
   (	"RECORD_ID" NUMBER, 
	"INTERFACE_LINE_CONTEXT" VARCHAR2(30 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"BATCH_SOURCE_NAME" VARCHAR2(50 BYTE), 
	"LINE_TYPE" VARCHAR2(20 BYTE), 
	"LINE_NUMBER" NUMBER, 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"UOM_CODE" VARCHAR2(3 BYTE), 
	"QUANTITY" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER, 
	"AMOUNT" NUMBER, 
	"LINK_TO_LINE_CONTEXT" VARCHAR2(30 BYTE), 
	"LINK_TO_LINE_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"LINK_TO_LINE_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"LINK_TO_LINE_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"LINK_TO_LINE_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"LINK_TO_LINE_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"LINK_TO_LINE_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"LINK_TO_LINE_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"TAXABLE_FLAG" VARCHAR2(1 BYTE), 
	"TAX_EXEMPT_FLAG" VARCHAR2(1 BYTE), 
	"TAX_EXEMPT_REASON_CODE_MEANING" VARCHAR2(80 BYTE), 
	"TAX_EXEMPT_NUMBER" VARCHAR2(80 BYTE), 
	"TAX_REGIME_CODE" VARCHAR2(30 BYTE), 
	"TAX" VARCHAR2(30 BYTE), 
	"TAX_STATUS_CODE" VARCHAR2(30 BYTE), 
	"TAX_RATE_CODE" VARCHAR2(30 BYTE), 
	"TAX_JURISDICTION_CODE" VARCHAR2(30 BYTE), 
	"TAX_RATE" NUMBER, 
	"TAX_CODE" VARCHAR2(50 BYTE), 
	"TAX_AMOUNT" NUMBER, 
	"OPERATING_UNIT" VARCHAR2(240 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE), 
	"SALES_ORDER" VARCHAR2(50 BYTE), 
	"SALES_ORDER_LINE" VARCHAR2(30 BYTE), 
	"SALES_ORDER_DATE" DATE, 
	"SALES_ORDER_SOURCE" VARCHAR2(50 BYTE), 
	"SHIP_DATE_ACTUAL" DATE, 
	"SHIP_VIA" VARCHAR2(25 BYTE), 
	"FOB_POINT" VARCHAR2(30 BYTE), 
	"REFERENCE_LINE_CONTEXT" VARCHAR2(30 BYTE), 
	"REFERENCE_LINE_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"REFERENCE_LINE_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"REFERENCE_LINE_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"IMPERIAL1" VARCHAR2(240 BYTE), 
	"IMPERIAL2" VARCHAR2(240 BYTE), 
	"IMPERIAL3" VARCHAR2(240 BYTE), 
	"IMPERIAL4" VARCHAR2(240 BYTE), 
	"IMPERIAL5" VARCHAR2(240 BYTE), 
	"IMPERIAL6" VARCHAR2(240 BYTE), 
	"IMPERIAL7" VARCHAR2(240 BYTE), 
	"IMPERIAL8" VARCHAR2(240 BYTE), 
	"IMPERIAL9" VARCHAR2(240 BYTE), 
	"IMPERIAL10" VARCHAR2(240 BYTE), 
	"IMPERIAL11" VARCHAR2(240 BYTE), 
	"IMPERIAL12" VARCHAR2(240 BYTE), 
	"METRIC1" VARCHAR2(240 BYTE), 
	"METRIC2" VARCHAR2(240 BYTE), 
	"METRIC3" VARCHAR2(240 BYTE), 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE)
   )  ;
--------------------------------------------------------
--  Constraints for Table XXNUC_AR_TRANS_LIN_STG
--------------------------------------------------------

  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_LIN_STG" MODIFY ("INTERFACE_LINE_CONTEXT" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_LIN_STG" MODIFY ("BATCH_SOURCE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_LIN_STG" MODIFY ("LINE_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_LIN_STG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_LIN_STG" MODIFY ("AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_LIN_STG" MODIFY ("OPERATING_UNIT" NOT NULL ENABLE);
  
  CREATE INDEX XXNUC_AR_TRANS_LIN_STG_N1 ON XXNUC_AR_TRANS_LIN_STG(interface_line_Attribute1);
