--------------------------------------------------------
--  File created - Wednesday-September-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXNUC_AP_HDR_TRANS_STG
--------------------------------------------------------
DROP TABLE XXNUC_AP_HDR_TRANS_STG CASCADE CONSTRAINTS;
  CREATE TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" 
   ("INVOICE_HEADER_KEY" NUMBER,
   "INVOICE_NUM" VARCHAR2(50 BYTE), 
	"INVOICE_TYPE_LOOKUP_CODE" VARCHAR2(25 BYTE), 
	"INVOICE_DATE" DATE, 
	"VENDOR_NUM" VARCHAR2(30 BYTE), 
	"VENDOR_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_SITE_CODE" VARCHAR2(15 BYTE), 
	"INVOICE_AMOUNT" NUMBER, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"TERMS_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"SOURCE" VARCHAR2(80 BYTE), 
	"PAYMENT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"DOC_CATEGORY_CODE" VARCHAR2(30 BYTE), 
	"VOUCHER_NUM" VARCHAR2(50 BYTE), 
	"PAYMENT_METHOD_LOOKUP_CODE" VARCHAR2(25 BYTE), 
	"PAY_GROUP_LOOKUP_CODE" VARCHAR2(25 BYTE), 
	"GL_DATE" DATE, 
	"EXCLUSIVE_PAYMENT_FLAG" VARCHAR2(1 BYTE), 
	"TERMS_DATE" DATE, 
	"INVOICE_RECEIVED_DATE" DATE, 
	"OPERATING_UNIT" VARCHAR2(240 BYTE), 
	"ACCTS_PAY_CODE_CONCATENATED" VARCHAR2(250 BYTE), 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE), 
	"BATCH_NAME" VARCHAR2(120 BYTE)
   ) ;
   
-------------------------------------------------------------
--  SEQUENCE for Table XXNUC_AP_HDR_TRANS_STG
--------------------------------------------------------
DROP SEQUENCE XXNUC_AP_HDR_TRANS_STG_S ;

CREATE SEQUENCE  XXNUC_AP_HDR_TRANS_STG_S  START WITH 1000 INCREMENT BY 1;

CREATE UNIQUE INDEX XXNUC_AP_HDR_TRANS_STG_N1 ON XXNUC_AP_HDR_TRANS_STG ( INVOICE_HEADER_KEY);

CREATE INDEX XXNUC_AP_HDR_TRANS_STG_N2 ON XXNUC_AP_HDR_TRANS_STG(INVOICE_NUM);
CREATE INDEX XXNUC_AP_HDR_TRANS_STG_N3 ON XXNUC_AP_HDR_TRANS_STG(VENDOR_NUM);
CREATE INDEX XXNUC_AP_HDR_TRANS_STG_N4 ON XXNUC_AP_HDR_TRANS_STG(PROCESS_STATUS);

--------------------------------------------------------
--  Constraints for Table XXNUC_AP_HDR_TRANS_STG
--------------------------------------------------------

  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("INVOICE_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("INVOICE_TYPE_LOOKUP_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("VENDOR_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("VENDOR_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("VENDOR_SITE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("INVOICE_AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("INVOICE_CURRENCY_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("SOURCE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" MODIFY ("OPERATING_UNIT" NOT NULL ENABLE);
