--------------------------------------------------------
--  File created - Wednesday-September-10-2014  
--  Updated on 11/12/2014 
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXNUC_AP_LIN_TRANS_STG
--------------------------------------------------------
DROP TABLE XXNUC_AP_LIN_TRANS_STG CASCADE CONSTRAINTS;
  CREATE TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" 
   ("INVOICE_LINE_KEY"          NUMBER, -- Added for Primary Key
    "INVOICE_HEADER_KEY"        NUMBER,	-- Added as a references for main HDR table
   "INVOICE_NUM" VARCHAR2(50 BYTE), 
	"LINE_NUMBER" NUMBER, 
	"DIST_CODE_COMBINATION_ID" VARCHAR2(240 BYTE), 
	"LINE_TYPE_LOOKUP_CODE" VARCHAR2(25 BYTE), 
	"AMOUNT" NUMBER, 
	"ACCOUNTING_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"TYPE_1099" VARCHAR2(10 BYTE), 
	"INCOME_TAX_REGION" VARCHAR2(10 BYTE), 
	"PO" VARCHAR2(100 BYTE), 
	"OPERATING_UNIT" VARCHAR2(240 BYTE), 
	"VENDOR_NUM" VARCHAR2(30 BYTE), 
	"TAX_CODE" VARCHAR2(30 BYTE), 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE)
   ) ;
--------------------------------------------------------
--  Constraints for Table XXNUC_AP_LIN_TRANS_STG
--------------------------------------------------------

  ALTER TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" MODIFY ("INVOICE_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" MODIFY ("DIST_CODE_COMBINATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" MODIFY ("LINE_TYPE_LOOKUP_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" MODIFY ("AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" MODIFY ("ACCOUNTING_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" MODIFY ("OPERATING_UNIT" NOT NULL ENABLE);
  
 -------------------------------------------------------------
--  SEQUENCE for Table XXNUC_AP_LIN_TRANS_STG
--------------------------------------------------------
 DROP SEQUENCE XXNUC_AP_INVOICE_LINES_S ;

CREATE SEQUENCE  XXNUC_AP_INVOICE_LINES_S  START WITH 1000 INCREMENT BY 1;

CREATE UNIQUE INDEX XXNUC_AP_INVOICE_LINES_U1 ON XXNUC_AP_LIN_TRANS_STG ( INVOICE_LINE_KEY);

CREATE INDEX XXNUC_AP_INVOICE_LINES_N2 ON XXNUC_AP_LIN_TRANS_STG (INVOICE_HEADER_KEY);

CREATE INDEX XXNUC_AP_INVOICE_LINES_N3 ON XXNUC_AP_LIN_TRANS_STG(INVOICE_NUM);
CREATE INDEX XXNUC_AP_INVOICE_LINES_N4 ON XXNUC_AP_LIN_TRANS_STG(VENDOR_NUM);
CREATE INDEX XXNUC_AP_INVOICE_LINES_N5 ON XXNUC_AP_LIN_TRANS_STG(LINE_NUMBER);
