--------------------------------------------------------
--  File created - Wednesday-September-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXNUC_AR_TRANS_DIST_STG
--------------------------------------------------------
DROP TABLE XXNUC_AR_TRANS_DIST_STG CASCADE CONSTRAINTS;
  CREATE TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" 
   (	"RECORD_ID" NUMBER, 
	"INTERFACE_LINE_CONTEXT" VARCHAR2(30 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ACCOUNT_CLASS" VARCHAR2(10 BYTE), 
	"AMOUNT" NUMBER, 
	"PERCENT" NUMBER, 
	"OPERATING_UNIT" VARCHAR2(240 BYTE), 
	"SEGMENT1" VARCHAR2(50 BYTE), 
	"SEGMENT2" VARCHAR2(50 BYTE), 
	"SEGMENT3" VARCHAR2(50 BYTE), 
	"SEGMENT4" VARCHAR2(50 BYTE), 
	"SEGMENT5" VARCHAR2(50 BYTE), 
	"SEGMENT6" VARCHAR2(50 BYTE), 
	"SEGMENT7" VARCHAR2(50 BYTE), 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE)
   ) ;
--------------------------------------------------------
--  Constraints for Table XXNUC_AR_TRANS_DIST_STG
--------------------------------------------------------

  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("INTERFACE_LINE_CONTEXT" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("ACCOUNT_CLASS" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("OPERATING_UNIT" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("SEGMENT1" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("SEGMENT2" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("SEGMENT3" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("SEGMENT4" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("SEGMENT5" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("SEGMENT6" NOT NULL ENABLE);
 
  ALTER TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" MODIFY ("SEGMENT7" NOT NULL ENABLE);

  CREATE INDEX XXNUC_AR_TRANS_DIST_STG_N1 ON XXNUC_AR_TRANS_DIST_STG(interface_line_Attribute1);