<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/P2P/InvoiceABM/1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_LaunchAutoInvoiceAPI"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 ns1 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns16="http://xmlns.oracle.com/pcbpel/adapter/db/Test/NUC_EBizAPInvoice_ABS/OA_LaunchAutoInvoiceAPI"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.eia.com/ABS/EBiz/InvoiceABS/1.0"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/P2P/InvoiceAO/1.0"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns14="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns15="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/InvoiceABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="LaunchAutoInvoiceAPIRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/InvoiceABM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/OA_LaunchAutoInvoiceAPI.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_LaunchAutoInvoiceAPI"/>
        <oracle-xsl-mapper:param name="OA_LaunchAutoInvoiceAPI_OutputVariable.OutputParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/InvoiceABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="LaunchAutoInvoiceAPIResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/InvoiceABM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI FEB 12 00:07:48 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="OA_LaunchAutoInvoiceAPI_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <ns0:LaunchAutoInvoiceAPIResponseMessage>
      <ns9:HeaderRs>
        <ns9:RequestDetails>
          <ns9:TransactionRequestID>
            <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:TransactionRequestID"/>
          </ns9:TransactionRequestID>
          <ns9:Language>
            <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:Language"/>
          </ns9:Language>
          <ns9:ComponentID>
            <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:ComponentID"/>
          </ns9:ComponentID>
          <ns9:ServiceName>
            <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:ServiceName"/>
          </ns9:ServiceName>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:TransactionIDREF">
            <ns9:TransactionIDREF>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:TransactionIDREF"/>
            </ns9:TransactionIDREF>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:TransactionName">
            <ns9:TransactionName>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:TransactionName"/>
            </ns9:TransactionName>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:FileName">
            <ns9:FileName>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:FileName"/>
            </ns9:FileName>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:FileInstanceID">
            <ns9:FileInstanceID>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:FileInstanceID"/>
            </ns9:FileInstanceID>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:Source">
            <ns9:Source>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:Source"/>
            </ns9:Source>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:Target">
            <ns9:Target>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:Target"/>
            </ns9:Target>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:HostName">
            <ns9:HostName>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:HostName"/>
            </ns9:HostName>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:UserName">
            <ns9:UserName>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:UserName"/>
            </ns9:UserName>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:UserRole">
            <ns9:UserRole>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:UserRole"/>
            </ns9:UserRole>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:AdminEmail">
            <ns9:AdminEmail>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:AdminEmail"/>
            </ns9:AdminEmail>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:ApplicationResponsibility">
            <ns9:ApplicationResponsibility>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:ApplicationResponsibility"/>
            </ns9:ApplicationResponsibility>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:EOFFlag">
            <ns9:EOFFlag>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:EOFFlag"/>
            </ns9:EOFFlag>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:SOFFlag">
            <ns9:SOFFlag>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:SOFFlag"/>
            </ns9:SOFFlag>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:FileRecordCount">
            <ns9:FileRecordCount>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:FileRecordCount"/>
            </ns9:FileRecordCount>
          </xsl:if>
          <xsl:if test="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:TimeStamp">
            <ns9:TimeStamp>
              <xsl:value-of select="/ns0:LaunchAutoInvoiceAPIRequestMessage/ns9:HeaderRq/ns9:TimeStamp"/>
            </ns9:TimeStamp>
          </xsl:if>
        </ns9:RequestDetails>
        <ns9:Status>
          <ns9:Status>SUCCESS</ns9:Status>
        </ns9:Status>
      </ns9:HeaderRs>
      <ns0:OperationResult>
        <ns3:Stats>
          <xsl:value-of select="$OA_LaunchAutoInvoiceAPI_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_C_RESULT"/>
        </ns3:Stats>
        <ns3:Errors>
          <xsl:for-each select="$OA_LaunchAutoInvoiceAPI_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_INV_REJECTION_INFO/ns1:P_INV_REJECTION_INFO_ITEM">
            <ns3:OperationResultError>
              <xsl:value-of select='concat ("INVOICE_ID::", ns1:INVOICE_ID," ","INVOICE_NUM::",ns1:INVOICE_NUM," ","INTERFACE_TABLE::", ns1:INTERFACE_TABLE," ","REJECT_LOOKUP_CODE::", ns1:REJECT_LOOKUP_CODE," ","REJECTION_DESCRIPTION::", ns1:REJECTION_DESCRIPTION )'/>
            </ns3:OperationResultError>
          </xsl:for-each>
        </ns3:Errors>
        <ns3:Warnings>
          <ns3:OperationResultWarning/>
        </ns3:Warnings>
      </ns0:OperationResult>
    </ns0:LaunchAutoInvoiceAPIResponseMessage>
  </xsl:template>
</xsl:stylesheet>
