<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://xmlns.oracle.com/fmw/mft/soap"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Call_XXNUC_AP_CCARD_INV_WRAP_PKG"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns1="http://nucor.eia.com/ePayments/Reconciliation"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mftconfig="http://xmlns.oracle.com/fmw/mft/config/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/DV1_Application/NUC_ePayRecon_MFT_EBiz_ABF/DB_Call_XXNUC_AP_CCARD_INV_WRAP_PKG">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/MFTReceiveePayReconci.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MFTHeader" namespace="http://xmlns.oracle.com/fmw/mft/soap"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Call_XXNUC_AP_CCARD_INV_WRAP_PKG.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Call_XXNUC_AP_CCARD_INV_WRAP_PKG"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE APR 25 09:33:16 PDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:variable name="varDivision">
      <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/JPMBank_EBS_ORG_CODE_MAP.dvm", "FilePrefix", substring-before (/ns0:MFTHeader/ns0:TargetFilename, "." ), "OrgCode", "" )'/>
    </xsl:variable>
    <tns:InputParameters>
      <tns:P_TXN_ID/>
      <xsl:if test="/ns0:MFTHeader/ns0:TargetFilename">
        <tns:P_FILE_NAME>
          <xsl:value-of select="/ns0:MFTHeader/ns0:TargetFilename"/>
        </tns:P_FILE_NAME>
      </xsl:if>
      <tns:P_APPS_INIT>
        <tns:USER_NAME>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm', 'DIVISION', $varDivision, 'EBS_USER_NAME', '' )"/>
        </tns:USER_NAME>
        <tns:RESPONSIBILITY_NAME>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_ORG_RESP_NAME.dvm', 'DIVISION', $varDivision, 'EBS_RESP_NAME', '','EBS_FUNCTION_AREA','AP INVOICES' )"/>
        </tns:RESPONSIBILITY_NAME>
        <tns:ORG_ID>
          <xsl:value-of select="oraext:query-database(concat(&quot;Select organization_id as retvalue from APPS.hr_operating_units where SHORT_CODE='&quot;,$varDivision,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
        </tns:ORG_ID>
      </tns:P_APPS_INIT>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
