
  CREATE TABLE "XXNUC"."XXNUC_AR_CORP_CMRCL_DB_STG" 
   (	"RECORD_ID" NUMBER, 
	"ORG_ID" NUMBER, 
	"INVOICE_MILL_ID" VARCHAR2(240 BYTE), 
	"INVOICE_ID" VARCHAR2(20 BYTE), 
	"CREDIT_ADJ" NUMBER, 
	"AMT_PAID" NUMBER(9,2), 
	"CLOSED_YN" CHAR(1 BYTE), 
	"DISCOUNT_APPLIED" NUMBER(11,2), 
	"DISCOUNT_AMOUNT" NUMBER(11,2), 
	"DISCOUNT_CUTOFF_DATE" DATE, 
	"DUE_DATE" DATE, 
	"PAYMENT_TERMS" CHAR(15 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOOLS" ;
 
