
  CREATE TABLE "XXNUC"."XXNUC_AP_LIN_TRANS_STG" 
   (	"INVOICE_NUM" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LINE_NUMBER" NUMBER NOT NULL ENABLE, 
	"DIST_CODE_COMBINATION_ID" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"LINE_TYPE_LOOKUP_CODE" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"AMOUNT" NUMBER NOT NULL ENABLE, 
	"ACCOUNTING_DATE" DATE NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"TYPE_1099" VARCHAR2(10 BYTE), 
	"INCOME_TAX_REGION" VARCHAR2(10 BYTE), 
	"PO" VARCHAR2(100 BYTE), 
	"OPERATING_UNIT" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"VENDOR_NUM" VARCHAR2(30 BYTE), 
	"TAX_CODE" VARCHAR2(30 BYTE), 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOOLS" ;
 
