
  CREATE TABLE "XXNUC"."XXNUC_AR_BATCH_STG" 
   (	"RECORD_ID" NUMBER, 
	"BATCH_NUMBER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"BATCH_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOOLS" ;
 
