
  CREATE TABLE "XXNUC"."XXNUC_AP_HDR_TRANS_STG" 
   (	"INVOICE_NUM" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"INVOICE_TYPE_LOOKUP_CODE" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"INVOICE_DATE" DATE, 
	"VENDOR_NUM" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"VENDOR_NAME" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"VENDOR_SITE_CODE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"INVOICE_AMOUNT" NUMBER NOT NULL ENABLE, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"TERMS_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"SOURCE" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"PAYMENT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"DOC_CATEGORY_CODE" VARCHAR2(30 BYTE), 
	"VOUCHER_NUM" VARCHAR2(50 BYTE), 
	"PAYMENT_METHOD_LOOKUP_CODE" VARCHAR2(25 BYTE), 
	"PAY_GROUP_LOOKUP_CODE" VARCHAR2(25 BYTE), 
	"GL_DATE" DATE, 
	"EXCLUSIVE_PAYMENT_FLAG" VARCHAR2(1 BYTE), 
	"TERMS_DATE" DATE, 
	"INVOICE_RECEIVED_DATE" DATE, 
	"OPERATING_UNIT" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"ACCTS_PAY_CODE_CONCATENATED" VARCHAR2(250 BYTE), 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE), 
	"BATCH_NAME" VARCHAR2(120 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOOLS" ;
 
