
  CREATE TABLE "XXNUC"."XXNUC_AR_TRANS_DIST_STG" 
   (	"RECORD_ID" NUMBER, 
	"INTERFACE_LINE_CONTEXT" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"INTERFACE_LINE_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"INTERFACE_LINE_ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ACCOUNT_CLASS" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AMOUNT" NUMBER NOT NULL ENABLE, 
	"PERCENT" NUMBER, 
	"OPERATING_UNIT" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"SEGMENT1" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SEGMENT2" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SEGMENT3" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SEGMENT4" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SEGMENT5" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SEGMENT6" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SEGMENT7" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(240 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOOLS" ;
 
