
  CREATE TABLE "XXNUC"."XXNUC_GL_INT_STG" 
   (	"LEDGER" VARCHAR2(30 BYTE), 
	"USER_JE_CATEGORY_NAME" VARCHAR2(25 BYTE), 
	"USER_JE_SOURCE_NAME" VARCHAR2(25 BYTE), 
	"ACCOUNTED_DR" NUMBER, 
	"ACCOUNTED_CR" NUMBER, 
	"REFERENCE1" VARCHAR2(100 BYTE), 
	"REFERENCE2" VARCHAR2(240 BYTE), 
	"REFERENCE4" VARCHAR2(100 BYTE), 
	"REFERENCE5" VARCHAR2(240 BYTE), 
	"REFERENCE7" VARCHAR2(240 BYTE), 
	"REFERENCE8" VARCHAR2(240 BYTE), 
	"REFERENCE10" VARCHAR2(240 BYTE), 
	"PERIOD_NAME" VARCHAR2(15 BYTE), 
	"ACCOUNT" VARCHAR2(240 BYTE), 
	"ATTRIBUTE1" VARCHAR2(240 BYTE), 
	"ACTUAL_FLAG" VARCHAR2(2 BYTE), 
	"ACCOUNTING_DATE" DATE, 
	"REQUEST_ID" NUMBER DEFAULT -1    , 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(2000 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOOLS" ;
 
