
  CREATE TABLE "XXNUC"."XXNUC_CHK_CUT_STG" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUM" VARCHAR2(60 BYTE), 
	"INVOICE_DATE" DATE, 
	"CHECK_NUM" VARCHAR2(30 BYTE), 
	"SEQ_NUM" NUMBER, 
	"LOAD_AMOUNT" NUMBER, 
	"TOTAL_AMOUNT" NUMBER, 
	"STATUS" VARCHAR2(30 BYTE), 
	"RECORD_ID" NUMBER, 
	"REQUEST_ID" NUMBER DEFAULT -1    , 
	"PROCESS_STATUS" VARCHAR2(30 BYTE), 
	"PROCESS_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(2000 BYTE), 
	"LEGACY_VENDOR_NUM" VARCHAR2(30 BYTE), 
	"EBS_VENDOR_NUM" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TOOLS" ;
 
