<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.eia.com/fileService"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/PL_DB_InsertRecords_STG"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns1="http://xmlns.oracle.com/fmw/mft/soap"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 ns1 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mftconfig="http://xmlns.oracle.com/fmw/mft/config/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/MFT/NUC_ePayResponse_MFT_EBiz_ABF/PL_DB_InsertRecords_STG">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ePayResponse_MFT.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Payment" namespace="http://xmlns.eia.com/fileService"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ePayResponse_MFT.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MFTHeader" namespace="http://xmlns.oracle.com/fmw/mft/soap"/>
        <oracle-xsl-mapper:param name="Receive_submit_InputVariable.qheader"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ePayResponse_MFT.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MFTServiceInput" namespace="http://xmlns.oracle.com/fmw/mft/soap"/>
        <oracle-xsl-mapper:param name="Receive_submit_InputVariable.payload"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/PL_DB_InsertRecords_STG.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucApJpmcEpayStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PL_DB_InsertRecords_STG"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE APR 25 09:53:03 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="Receive_submit_InputVariable.qheader"/>
  <xsl:param name="Receive_submit_InputVariable.payload"/>
  <xsl:template match="/">
    <tns:XxnucApJpmcEpayStgCollection>
      <xsl:for-each select="/ns0:Payment/ns0:Order">
        <tns:XxnucApJpmcEpayStg>
          <tns:requestId>
            <xsl:value-of select="ns0:REQUEST_ID"/>
          </tns:requestId>
          <tns:organizationId>
            <xsl:value-of select="ns0:ORGANIZATION_ID"/>
          </tns:organizationId>
          <tns:loginId>
            <xsl:value-of select="ns0:LOGIN_ID"/>
          </tns:loginId>
          <tns:passPhrase>
            <xsl:value-of select="ns0:PASS_PHRASE"/>
          </tns:passPhrase>
          <tns:culture>
            <xsl:value-of select="ns0:CULTURE"/>
          </tns:culture>
          <tns:requestType>
            <xsl:value-of select="ns0:REQUEST_TYPE"/>
          </tns:requestType>
          <tns:accountPoolId>
            <xsl:value-of select="ns0:ACCOUNT_POOL_ID"/>
          </tns:accountPoolId>
          <tns:orderId>
            <xsl:value-of select="ns0:ORDER_ID"/>
          </tns:orderId>
          <tns:orderSettlementMethod>
            <xsl:value-of select="ns0:ORDER_SETTLEMENT_METHOD"/>
          </tns:orderSettlementMethod>
          <tns:orderSystemId>
            <xsl:value-of select="ns0:ORDER_SYSTEM_ID"/>
          </tns:orderSystemId>
          <tns:orderControlCode>
            <xsl:value-of select="ns0:ORDER_CONTROL_CODE"/>
          </tns:orderControlCode>
          <tns:orderStatus>
            <xsl:value-of select="ns0:ORDER_STATUS"/>
          </tns:orderStatus>
          <tns:orderEntryDate>
            <xsl:value-of select="ns0:ORDER_ENTRY_DATE"/>
          </tns:orderEntryDate>
          <tns:orderBeginDate>
            <xsl:value-of select="ns0:ORDER_BEGIN_DATE"/>
          </tns:orderBeginDate>
          <tns:orderEndDate>
            <xsl:value-of select="ns0:ORDER_END_DATE"/>
          </tns:orderEndDate>
          <tns:orderEstimatedFreight>
            <xsl:value-of select="ns0:ORDER_ESTIMATED_FREIGHT"/>
          </tns:orderEstimatedFreight>
          <tns:orderEstimatedTax>
            <xsl:value-of select="ns0:ORDER_ESTIMATED_TAX"/>
          </tns:orderEstimatedTax>
          <tns:orderOverTolerance>
            <xsl:value-of select="ns0:ORDER_OVER_TOLERANCE"/>
          </tns:orderOverTolerance>
          <tns:orderUnderTolerance>
            <xsl:value-of select="ns0:ORDER_UNDER_TOLERANCE"/>
          </tns:orderUnderTolerance>
          <tns:orderCurrencyCode>
            <xsl:value-of select="ns0:ORDER_CURRENCY_CODE"/>
          </tns:orderCurrencyCode>
          <tns:orderTotal>
            <xsl:value-of select="ns0:ORDER_TOTAL"/>
          </tns:orderTotal>
          <tns:orderCustomFieldName>
            <xsl:value-of select="ns0:ORDER_CUSTOM_FIELD_NAME"/>
          </tns:orderCustomFieldName>
          <tns:orderCustomFieldNameCc>
            <xsl:value-of select="ns0:ORDER_CUSTOM_FIELD_NAME_CC"/>
          </tns:orderCustomFieldNameCc>
          <tns:orderCustomFieldValue>
            <xsl:value-of select="ns0:ORDER_CUSTOM_FIELD_VALUE"/>
          </tns:orderCustomFieldValue>
          <tns:orderNotes>
            <xsl:value-of select="ns0:ORDER_NOTES"/>
          </tns:orderNotes>
          <tns:orderItemId>
            <xsl:value-of select="ns0:ORDER_ITEM_ID"/>
          </tns:orderItemId>
          <tns:orderItemDescription>
            <xsl:value-of select="ns0:ORDER_ITEM_DESCRIPTION"/>
          </tns:orderItemDescription>
          <tns:orderItemControlCode>
            <xsl:value-of select="ns0:ORDER_ITEM_CONTROL_CODE"/>
          </tns:orderItemControlCode>
          <tns:orderItemUnitPrice>
            <xsl:value-of select="ns0:ORDER_ITEM_UNIT_PRICE"/>
          </tns:orderItemUnitPrice>
          <tns:orderItemNoOfUnits>
            <xsl:value-of select="ns0:ORDER_ITEM_NO_OF_UNITS"/>
          </tns:orderItemNoOfUnits>
          <tns:orderItemUnitOfMeasure>
            <xsl:value-of select="ns0:ORDER_ITEM_UNIT_OF_MEASURE"/>
          </tns:orderItemUnitOfMeasure>
          <tns:accountId>
            <xsl:value-of select="ns0:ACCOUNT_ID"/>
          </tns:accountId>
          <tns:accountNumber>
            <xsl:value-of select="ns0:ACCOUNT_NUMBER"/>
          </tns:accountNumber>
          <tns:accountCv2>
            <xsl:value-of select="ns0:ACCOUNT_CV2"/>
          </tns:accountCv2>
          <tns:accountExpirationDate>
            <xsl:value-of select="ns0:ACCOUNT_EXPIRATION_DATE"/>
          </tns:accountExpirationDate>
          <tns:accountAuthorizationCcl>
            <xsl:value-of select="ns0:ACCOUNT_AUTHORIZATION_CCL"/>
          </tns:accountAuthorizationCcl>
          <tns:dailyTransactionLimitAmt>
            <xsl:value-of select="ns0:DAILY_TRANSACTION_LIMIT_AMT"/>
          </tns:dailyTransactionLimitAmt>
          <tns:dailyTransactionLimitNum>
            <xsl:value-of select="ns0:DAILY_TRANSACTION_LIMIT_NUM"/>
          </tns:dailyTransactionLimitNum>
          <tns:singleTransactionLimitAmt>
            <xsl:value-of select="ns0:SINGLE_TRANSACTION_LIMIT_AMT"/>
          </tns:singleTransactionLimitAmt>
          <tns:monthlyTransactionLimitNum>
            <xsl:value-of select="ns0:MONTHLY_TRANSACTION_LIMIT_NUM"/>
          </tns:monthlyTransactionLimitNum>
          <tns:accountMccgControlCode>
            <xsl:value-of select="ns0:ACCOUNT_MCCG_CONTROL_CODE"/>
          </tns:accountMccgControlCode>
          <tns:accountMccgCode>
            <xsl:value-of select="ns0:ACCOUNT_MCCG_CODE"/>
          </tns:accountMccgCode>
          <tns:accountMccgId>
            <xsl:value-of select="ns0:ACCOUNT_MCCG_ID"/>
          </tns:accountMccgId>
          <tns:supplierName>
            <xsl:value-of select="ns0:SUPPLIER_NAME"/>
          </tns:supplierName>
          <tns:merchantEmailControlCode>
            <xsl:value-of select="ns0:MERCHANT_EMAIL_CONTROL_CODE"/>
          </tns:merchantEmailControlCode>
          <tns:merchantEmailAddress>
            <xsl:value-of select="ns0:MERCHANT_EMAIL_ADDRESS"/>
          </tns:merchantEmailAddress>
          <tns:merchantEmailId>
            <xsl:value-of select="ns0:MERCHANT_EMAIL_ID"/>
          </tns:merchantEmailId>
          <tns:blank1>
            <xsl:value-of select="ns0:BLANK1"/>
          </tns:blank1>
          <tns:blank2>
            <xsl:value-of select="ns0:BLANK2"/>
          </tns:blank2>
          <tns:blank3>
            <xsl:value-of select="ns0:BLANK3"/>
          </tns:blank3>
          <tns:blank4>
            <xsl:value-of select="ns0:BLANK4"/>
          </tns:blank4>
          <tns:transactionCustomFieldName>
            <xsl:value-of select="ns0:TRANSACTION_CUSTOM_FIELD_NAME"/>
          </tns:transactionCustomFieldName>
          <tns:transactionCustomFieldCc>
            <xsl:value-of select="ns0:TRANSACTION_CUSTOM_FIELD_CC"/>
          </tns:transactionCustomFieldCc>
          <tns:transactionCustomFv>
            <xsl:value-of select="ns0:TRANSACTION_CUSTOM_FV"/>
          </tns:transactionCustomFv>
          <tns:errorNumber>
            <xsl:value-of select="ns0:ERROR_NUMBER"/>
          </tns:errorNumber>
          <tns:errorDescription>
            <xsl:value-of select="ns0:ERROR_DESCRIPTION"/>
          </tns:errorDescription>
          <tns:correlationId>
            <xsl:value-of select="ns0:CORRELATION_ID"/>
          </tns:correlationId>
          <tns:fileName>
            <xsl:value-of select="$Receive_submit_InputVariable.qheader/ns1:MFTHeader/ns1:TargetFilename"/>
          </tns:fileName>
          <tns:creationDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:creationDate>
          <tns:lastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:lastUpdateDate>
        </tns:XxnucApJpmcEpayStg>
      </xsl:for-each>
    </tns:XxnucApJpmcEpayStgCollection>
  </xsl:template>
</xsl:stylesheet>
