<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_LaunchPOCreateWrapper"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns2="http://xmlns.eia.com/ABS/EBiz/PurchaseOrderABS/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns10="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/apps/NucorSOA/NUC_EbizPurchaseOrder_ABS/OA_LaunchPOCreateWrapper"
                xmlns:ns15="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns14="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns17="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0"
                xmlns:ns16="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns18="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../OA_LaunchPOCreateWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_LaunchPOCreateWrapper"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/PurchaseOrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreatePurchaseOrderRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"/>
        <oracle-xsl-mapper:param name="CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/PurchaseOrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreatePurchaseOrderResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE DEC 29 07:38:44 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage"/>
  <xsl:template match="/">
    <ns1:CreatePurchaseOrderResponseMessage>
      <ns10:HeaderRs>
        <ns10:RequestDetails>
          <ns10:TransactionRequestID>
            <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:TransactionRequestID"/>
          </ns10:TransactionRequestID>
          <ns10:Language>
            <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:Language"/>
          </ns10:Language>
          <ns10:ComponentID>
            <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:ComponentID"/>
          </ns10:ComponentID>
          <ns10:ServiceName>
            <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:ServiceName"/>
          </ns10:ServiceName>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:TransactionIDREF">
            <ns10:TransactionIDREF>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:TransactionIDREF"/>
            </ns10:TransactionIDREF>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:TransactionName">
            <ns10:TransactionName>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:TransactionName"/>
            </ns10:TransactionName>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:FileName">
            <ns10:FileName>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:FileName"/>
            </ns10:FileName>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:FileInstanceID">
            <ns10:FileInstanceID>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:FileInstanceID"/>
            </ns10:FileInstanceID>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:Source">
            <ns10:Source>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:Source"/>
            </ns10:Source>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:Target">
            <ns10:Target>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:Target"/>
            </ns10:Target>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:HostName">
            <ns10:HostName>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:HostName"/>
            </ns10:HostName>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:UserName">
            <ns10:UserName>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:UserName"/>
            </ns10:UserName>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:UserRole">
            <ns10:UserRole>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:UserRole"/>
            </ns10:UserRole>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:AdminEmail">
            <ns10:AdminEmail>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:AdminEmail"/>
            </ns10:AdminEmail>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:ApplicationResponsibility">
            <ns10:ApplicationResponsibility>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:ApplicationResponsibility"/>
            </ns10:ApplicationResponsibility>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:EOFFlag">
            <ns10:EOFFlag>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:EOFFlag"/>
            </ns10:EOFFlag>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:SOFFlag">
            <ns10:SOFFlag>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:SOFFlag"/>
            </ns10:SOFFlag>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:FileRecordCount">
            <ns10:FileRecordCount>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:FileRecordCount"/>
            </ns10:FileRecordCount>
          </xsl:if>
          <xsl:if test="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:TimeStamp">
            <ns10:TimeStamp>
              <xsl:value-of select="$CreateListPurchaseOrders_SyncReqMsg.CreatePurchaseOrderRequestMessage/ns1:CreatePurchaseOrderRequestMessage/ns10:HeaderRq/ns10:TimeStamp"/>
            </ns10:TimeStamp>
          </xsl:if>
        </ns10:RequestDetails>
        <ns10:Status>
          <ns10:Status>SUCCESS</ns10:Status>
        </ns10:Status>
      </ns10:HeaderRs>
      <ns1:OperationResult>
        <xsl:if test="/ns0:OutputParameters/ns0:X_RETURN_STATUS">
          <ns3:Stats>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:OutputParameters/ns0:X_RETURN_STATUS/@xsi:nil"/>
            </xsl:attribute>
            <xsl:value-of select="/ns0:OutputParameters/ns0:X_RETURN_STATUS"/>
          </ns3:Stats>
        </xsl:if>
        <ns3:Errors>
          <xsl:if test="/ns0:OutputParameters/ns0:X_MSG_DATA">
            <ns3:OperationResultError>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/ns0:OutputParameters/ns0:X_MSG_DATA/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="/ns0:OutputParameters/ns0:X_MSG_DATA"/>
            </ns3:OperationResultError>
          </xsl:if>
        </ns3:Errors>
      </ns1:OperationResult>
    </ns1:CreatePurchaseOrderResponseMessage>
  </xsl:template>
</xsl:stylesheet>
