<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:eia="http://xmlns.eia.com/extensions/1.0" xmlns:tns="http://xmlns.eia.com/ABS/EBiz/PurchaseOrderABS/1.0" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://xmlns.eia.com/AO/EBiz/common/SupplierAO/1.0" xmlns:poam="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0" xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns7="http://xmlns.oracle.com/pcbpel/adapter/apps/WI_Application/NUC_EbizPurchaseOrder_ABS/OA_CancelPurchaseOrderEBS" xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_CancelPurchaseOrderEBS" xmlns:core="http://xmlns.eia.com/EO/Common/1.0" xmlns:ns0="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns5="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0" xmlns:ns10="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0" xmlns:ns11="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0" xmlns:ns3="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns ns8 poam ns4 ns9 soap12 soap wsdl mime core ns0 ns5 ns6 xsd ns2 ns10 ns11 ns3 plt ns7 db bpws xp20 eia bpel bpm utl ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/PurchaseOrderABS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CancelPurchaseOrderLineRequestMessage" namespace="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../OA_CancelPurchaseOrderEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_CancelPurchaseOrderEBS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED SEP 09 14:05:50 CDT 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <db:InputParameters>
      <db:P_API_VERSION>
        <xsl:value-of select="string(&quot;1.0&quot;)"/>
      </db:P_API_VERSION>
      <db:P_INIT_MSG_LIST>
        <xsl:value-of select="string(&quot;T&quot;)"/>
      </db:P_INIT_MSG_LIST>
      <db:P_COMMIT>
        <xsl:value-of select="string(&quot;T&quot;)"/>
      </db:P_COMMIT>
      <db:P_DOC_TYPE>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Doctypename/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Doctypename"/>
      </db:P_DOC_TYPE>
      <db:P_DOC_SUBTYPE>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Documentsubtype/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Documentsubtype"/>
      </db:P_DOC_SUBTYPE>
      <xsl:if test="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Documentnum">
        <db:P_DOC_NUM>
          <xsl:if test="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Documentnum/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Documentnum/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Documentnum"/>
        </db:P_DOC_NUM>
      </xsl:if>
      <db:P_RELEASE_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Poreleaseid/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Poreleaseid"/>
      </db:P_RELEASE_ID>
      <db:P_RELEASE_NUM>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Releasenum/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Releasenum"/>
      </db:P_RELEASE_NUM>
      <db:P_DOC_LINE_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Polineid/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Polineid"/>
      </db:P_DOC_LINE_ID>
      <xsl:if test="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Linenum">
        <db:P_DOC_LINE_NUM>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Linenum/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Linenum"/>
        </db:P_DOC_LINE_NUM>
      </xsl:if>
      <db:P_DOC_LINE_LOC_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Linelocationid/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Linelocationid"/>
      </db:P_DOC_LINE_LOC_ID>
      <db:P_DOC_SHIPMENT_NUM>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Shipmentnum/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Shipmentnum"/>
      </db:P_DOC_SHIPMENT_NUM>
      <db:P_ACTION>
        <xsl:value-of select="string(&quot;CANCEL&quot;)"/>
      </db:P_ACTION>
      <db:P_ACTION_DATE>
        <xsl:value-of select="xp20:current-dateTime()"/>
      </db:P_ACTION_DATE>
      <db:P_CANCEL_REASON>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Cancelreason/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:ListOfPurchaseOrderLines/ns3:PurchaseOrderLine/ns3:Cancelreason"/>
      </db:P_CANCEL_REASON>
      <db:P_CANCEL_REQS_FLAG>
        <xsl:value-of select="string(&quot;N&quot;)"/>
      </db:P_CANCEL_REQS_FLAG>
      <db:P_PRINT_FLAG>
        <xsl:text disable-output-escaping="no"/>
      </db:P_PRINT_FLAG>
      <db:P_NOTE_TO_VENDOR>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Notetovendor/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Notetovendor"/>
      </db:P_NOTE_TO_VENDOR>
      <db:P_USE_GLDATE>
        <xsl:value-of select="string(&quot;N&quot;)"/>
      </db:P_USE_GLDATE>
      <db:P_ORG_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Orgid/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/poam:CancelPurchaseOrderLineRequestMessage/poam:ListOfPurchaseOrders/ns3:PurchaseOrder/ns3:Orgid"/>
      </db:P_ORG_ID>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>