<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:eia="http://xmlns.eia.com/extensions/1.0"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/OA_PurchaseOrderEBS"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_LaunchPOCreateWrapper"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/apps/NucorSOA/NUC_EbizPurchaseOrder_ABS/OA_LaunchPOCreateWrapper"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/apps/WI_Application/NUC_EbizPurchaseOrder_ABS/OA_PurchaseOrderEBS"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl top plt wsdl xsd tns db ns0 bpws xp20 eia bpel bpm utl ora socket mhdr oraext dvm hwf med ids xdk xref ldap"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../OA_PurchaseOrderEBS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="PoHeadersInterfaceCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/OA_PurchaseOrderEBS"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../OA_LaunchPOCreateWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_LaunchPOCreateWrapper"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED SEP 09 14:05:50 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <db:InputParameters>
      <db:P_INTERFACE_HEADER_ID>
        <xsl:value-of select="/top:PoHeadersInterfaceCollection/top:PoHeadersInterface/top:interfaceHeaderId"/>
      </db:P_INTERFACE_HEADER_ID>
      <db:P_DOCUMENT_TYPE>
        <xsl:text disable-output-escaping="no">STANDARD</xsl:text>
      </db:P_DOCUMENT_TYPE>
      <db:P_CREATE_ITEMS>
        <xsl:text disable-output-escaping="no">N</xsl:text>
      </db:P_CREATE_ITEMS>
      <xsl:choose>
        <xsl:when test='/top:PoHeadersInterfaceCollection/top:PoHeadersInterface/top:orgId = "354"'>
          <db:P_APPROVED_STATUS>
            <xsl:text disable-output-escaping="no">APPROVED</xsl:text>
          </db:P_APPROVED_STATUS>
        </xsl:when>
        <xsl:otherwise>
          <db:P_APPROVED_STATUS>
            <xsl:value-of select="/top:PoHeadersInterfaceCollection/top:PoHeadersInterface/top:approvalStatus"/>
          </db:P_APPROVED_STATUS>
        </xsl:otherwise>
      </xsl:choose>
      <db:P_COMMIT_INTERVAL>
        <xsl:text disable-output-escaping="no">1</xsl:text>
      </db:P_COMMIT_INTERVAL>
      <db:P_PROCESS_CODE>
        <xsl:text disable-output-escaping="no">PENDING</xsl:text>
      </db:P_PROCESS_CODE>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>