<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://xmlns.oracle.com/xdb/APPS_NE"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://xmlns.oracle.com/xdb/XXNUC_LOGGING"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/aq/CommonLogging/CommonLogging/CommonLoggingRequesterAqAdapter"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/aq/CommonLogging/CommonLogging/CommonLoggingProviderAQAdapter">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../CommonLoggingRequesterAqAdapter.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XXNUC_COMM_LOGG_OBJ_TYP" namespace="http://xmlns.oracle.com/xdb/APPS_NE"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../CommonLoggingProviderAQAdapter.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XXNUC_COMM_LOGG_OBJ_TYP"
                                       namespace="http://xmlns.oracle.com/xdb/XXNUC_LOGGING"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JUL 02 08:10:04 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:XXNUC_COMM_LOGG_OBJ_TYP>
      <TRANSACTION_ID>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/TRANSACTION_ID"/>
      </TRANSACTION_ID>
      <PROJECT_NAME>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/PROJECT_NAME"/>
      </PROJECT_NAME>
      <COMPONENT_ID>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/COMPONENT_ID"/>
      </COMPONENT_ID>
      <TRANSACTION_NAME>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/TRANSACTION_NAME"/>
      </TRANSACTION_NAME>
      <PROCESS_NAME>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/PROCESS_NAME"/>
      </PROCESS_NAME>
      <MESSAGE_SOURCE_SYSTEM>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/MESSAGE_SOURCE_SYSTEM"/>
      </MESSAGE_SOURCE_SYSTEM>
      <SOURCE_SYSTEM>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/SOURCE_SYSTEM"/>
      </SOURCE_SYSTEM>
      <TARGET_SYSTEM>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/TARGET_SYSTEM"/>
      </TARGET_SYSTEM>
      <LOG_TYPE>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/LOG_TYPE"/>
      </LOG_TYPE>
      <MESSAGE_CODE>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/MESSAGE_CODE"/>
      </MESSAGE_CODE>
      <MESSAGE_DESCRIPTION>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/MESSAGE_DESCRIPTION"/>
      </MESSAGE_DESCRIPTION>
      <TRANSACTION_STATUS>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/TRANSACTION_STATUS"/>
      </TRANSACTION_STATUS>
      <CREATED_BY>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/CREATED_BY"/>
      </CREATED_BY>
      <UPDATED_BY>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/UPDATED_BY"/>
      </UPDATED_BY>
      <V_ATTRIBUTE1>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/V_ATTRIBUTE1"/>
      </V_ATTRIBUTE1>
      <V_ATTRIBUTE2>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/V_ATTRIBUTE2"/>
      </V_ATTRIBUTE2>
      <N_ATTRIBUTE1>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/N_ATTRIBUTE1"/>
      </N_ATTRIBUTE1>
      <N_ATTRIBUTE2>
        <xsl:value-of select="/ns0:XXNUC_COMM_LOGG_OBJ_TYP/N_ATTRIBUTE2"/>
      </N_ATTRIBUTE2>
    </tns:XXNUC_COMM_LOGG_OBJ_TYP>
  </xsl:template>
</xsl:stylesheet>
