<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="PublishSupplierABF"
     targetNamespace="http://xmlns.eia.com/ABS/EBiz/PublishSupplierABF/1.0"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.eia.com/ABS/EBiz/PublishSupplierABF/1.0"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="WS_ReceiveSupplierId1">
        <plnk:role name="PublishSupplier_SyncPort" portType="tns:PublishSupplier_SyncPort"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.eia.com/ABS/EBiz/PublishSupplierABF/1.0" location="oramds:/apps/EIAMetadata/ABF/PublishSupplierABF.wsdl"/>
</wsdl:definitions>
