<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="EbizOnHandQuantity_ABS"
     targetNamespace="http://oracle.com/sca/soapservice/NextGen/NUC_EbizOnHandQuantity_ABS/EbizOnHandQuantity_ABS"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://oracle.com/sca/soapservice/NextGen/NUC_EbizOnHandQuantity_ABS/EbizOnHandQuantity_ABS"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="EbizOnHandQuantity_ABS_ep">
        <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://oracle.com/sca/soapservice/NextGen/NUC_EbizOnHandQuantity_ABS/EbizOnHandQuantity_ABS"
         location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/ItemOnHandQuantity.wsdl"/>
</wsdl:definitions>
