<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertJDAMfgOrderEBS"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/NUC_JDA_Ebiz_BatchSchedule_ABF/mfg_order/1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_JDA_Ebiz_BatchSchedule_ABF/FTP_ReadManufacturing_Order"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_JDA_Ebiz_BatchSchedule_ABF/DB_InsertJDAMfgOrderEBS"
                xmlns:ns3="http://schemas.oracle.com/service/bpel/common">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadManufacturing_Order.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MfgOrderList"
                                       namespace="http://xmlns.oracle.com/NUC_JDA_Ebiz_BatchSchedule_ABF/mfg_order/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/EO/common/V1.0/XSLParameters.xsd"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="gblParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_InsertJDAMfgOrderEBS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaMfgOrderStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertJDAMfgOrderEBS"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 11 14:48:32 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="gblParameters"/>
  <xsl:template match="/">
    <tns:XxnucGmeJdaMfgOrderStgCollection>
      <xsl:for-each select="/ns0:MfgOrderList/ns0:MfgOrder">
        <tns:XxnucGmeJdaMfgOrderStg>
          <tns:recordId>
            <xsl:value-of select='oraext:sequence-next-val ("xxnuc.XXNUC_GME_JDA_MFG_ORDER_S", "jdbc/ebsapps" )'/>
          </tns:recordId>
          <tns:organizationId>
            <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/JDA_EBS_INSTANCE_ORG_RESOURCE_MAP.dvm", "Instance", $gblParameters/ns3:parameters/ns3:item[1]/ns3:value, "Org_Id", "0")'/>
          </tns:organizationId>
          <tns:assignedLots>
            <xsl:value-of select="ns0:ASSIGNED_LOTS"/>
          </tns:assignedLots>
          <tns:bomName>
            <xsl:value-of select="ns0:BOM_NAME"/>
          </tns:bomName>
          <tns:demandOrder>
            <xsl:value-of select="ns0:DEMAND_ORDER"/>
          </tns:demandOrder>
          <tns:ecnDate>
            <xsl:value-of select="ns0:ECN_DATE"/>
          </tns:ecnDate>
          <tns:ecnTimeFormat>
            <xsl:value-of select="ns0:ECN_TIME_FORMAT"/>
          </tns:ecnTimeFormat>
          <tns:formattedInputQuantity>
            <xsl:value-of select="ns0:FORMATTED_INPUT_QUANTITY"/>
          </tns:formattedInputQuantity>
          <tns:formattedOutputQuantity>
            <xsl:value-of select="ns0:FORMATTED_OUTPUT_QUANTITY"/>
          </tns:formattedOutputQuantity>
          <tns:inputQuantity>
            <xsl:value-of select="ns0:INPUT_QUANTITY"/>
          </tns:inputQuantity>
          <tns:inputQuantityFormat>
            <xsl:value-of select="ns0:INPUT_QUANTITY_FORMAT"/>
          </tns:inputQuantityFormat>
          <tns:inputQuantityUom>
            <xsl:value-of select="ns0:INPUT_QUANTITY_UOM"/>
          </tns:inputQuantityUom>
          <tns:lpct>
            <xsl:value-of select="ns0:LPCT"/>
          </tns:lpct>
          <tns:lpctFormat>
            <xsl:value-of select="ns0:LPCT_FORMAT"/>
          </tns:lpctFormat>
          <tns:lotId>
            <xsl:value-of select="ns0:LOT_ID"/>
          </tns:lotId>
          <tns:mfgOrder>
            <xsl:value-of select="ns0:MFG_ORDER"/>
          </tns:mfgOrder>
          <tns:outputQuantity>
            <xsl:value-of select="ns0:OUTPUT_QUANTITY"/>
          </tns:outputQuantity>
          <tns:outputQuantityFormat>
            <xsl:value-of select="ns0:OUTPUT_QUANTITY_FORMAT"/>
          </tns:outputQuantityFormat>
          <tns:outputQuantityUom>
            <xsl:value-of select="ns0:OUTPUT_QUANTITY_UOM"/>
          </tns:outputQuantityUom>
          <tns:pet>
            <xsl:value-of select="ns0:PET"/>
          </tns:pet>
          <tns:petFormat>
            <xsl:value-of select="ns0:PET_FORMAT"/>
          </tns:petFormat>
          <tns:primaryOutputPart>
            <xsl:value-of select="ns0:PRIMARY_OUTPUT_PART"/>
          </tns:primaryOutputPart>
          <tns:pst>
            <xsl:value-of select="ns0:PST"/>
          </tns:pst>
          <tns:pstFormat>
            <xsl:value-of select="ns0:PST_FORMAT"/>
          </tns:pstFormat>
          <tns:ptrt>
            <xsl:value-of select="ns0:PTRT"/>
          </tns:ptrt>
          <tns:ptrtFormat>
            <xsl:value-of select="ns0:PTRT_FORMAT"/>
          </tns:ptrtFormat>
          <tns:routing>
            <xsl:value-of select="ns0:ROUTING"/>
          </tns:routing>
          <tns:status>
            <xsl:value-of select="ns0:STATUS"/>
          </tns:status>
          <tns:wholeInputQuantity>
            <xsl:value-of select="ns0:WHOLE_INPUT_QUANTITY"/>
          </tns:wholeInputQuantity>
          <tns:wholeOutputQuantity>
            <xsl:value-of select="ns0:WHOLE_OUTPUT_QUANTITY"/>
          </tns:wholeOutputQuantity>
          <tns:withinMfgConsolidationHoriz>
            <xsl:value-of select="ns0:WITHIN_MFG_CONSOLIDATION_HORIZON"/>
          </tns:withinMfgConsolidationHoriz>
          <tns:lastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:lastUpdateDate>
          <tns:lastUpdatedBy>
            <xsl:value-of select="'-1'"/>
          </tns:lastUpdatedBy>
          <tns:lastUpdateLogin>
            <xsl:value-of select="'-1'"/>
          </tns:lastUpdateLogin>
          <tns:creationDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:creationDate>
          <tns:createdBy>
            <xsl:value-of select="'-1'"/>
          </tns:createdBy>
          <tns:processStatus>
            <xsl:value-of select="'NEW'"/>
          </tns:processStatus>
        </tns:XxnucGmeJdaMfgOrderStg>
      </xsl:for-each>
    </tns:XxnucGmeJdaMfgOrderStgCollection>
  </xsl:template>
</xsl:stylesheet>
