<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/NUC_JDA_Ebiz_BatchSchedule_ABF/mfg_order_plan/1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertJDAMfgOrderPlan"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_JDA_Ebiz_BatchSchedule_ABF/FTP_GetTriggerFile"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_JDA_Ebiz_BatchSchedule_ABF/FTP_ReadMfgOrderPlan"
                xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_JDA_Ebiz_BatchSchedule_ABF/DB_InsertJDAMfgOrderPlan"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadMfgOrderPlan.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MfgOrderPlanList"
                                       namespace="http://xmlns.oracle.com/NUC_JDA_Ebiz_BatchSchedule_ABF/mfg_order_plan/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_GetTriggerFile.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="gblParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_InsertJDAMfgOrderPlan.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaMfgPlanStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertJDAMfgOrderPlan"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 30 16:22:56 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="gblParameters"/>
  <xsl:template match="/">
    <tns:XxnucGmeJdaMfgPlanStgCollection>
      <xsl:for-each select="/ns0:MfgOrderPlanList/ns0:MfgOrderPlan">
        <tns:XxnucGmeJdaMfgPlanStg>
          <tns:recordId>
            <xsl:value-of select='oraext:sequence-next-val ("xxnuc.XXNUC_GME_JDA_MFG_PLAN_S", "jdbc/ebsapps" )'/>
          </tns:recordId>
          <tns:organizationId>
            <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/JDA_EBS_INSTANCE_ORG_RESOURCE_MAP.dvm", "Instance", $gblParameters/ns1:parameters/ns1:item[1.0]/ns1:value, "Org_Id", "0" )'/>
          </tns:organizationId>
          <tns:mfgOrderId>
            <xsl:value-of select="ns0:MFG_ORDER_ID"/>
          </tns:mfgOrderId>
          <tns:primaryResource>
            <xsl:value-of select="ns0:PRIMARY_RESOURCE"/>
          </tns:primaryResource>
          <tns:operationId>
            <xsl:value-of select="ns0:OPERATION_ID"/>
          </tns:operationId>
          <tns:stepNumber>
            <xsl:value-of select="ns0:STEP_NUMBER"/>
          </tns:stepNumber>
          <tns:operators>
            <xsl:value-of select="ns0:OPERATORS"/>
          </tns:operators>
          <tns:priority>
            <xsl:value-of select="ns0:PRIORITY"/>
          </tns:priority>
          <tns:taskPriority>
            <xsl:value-of select="ns0:TASK_PRIORITY"/>
          </tns:taskPriority>
          <tns:category>
            <xsl:value-of select="ns0:CATEGORY"/>
          </tns:category>
          <tns:plannedStartTimeSec>
            <xsl:value-of select="ns0:PLANNED_START_TIME_SEC"/>
          </tns:plannedStartTimeSec>
          <tns:defaultTimeFormat>
            <xsl:value-of select="ns0:DEFAULT_TIME_FORMAT"/>
          </tns:defaultTimeFormat>
          <tns:plannedStartTime>
            <xsl:value-of select="ns0:PLANNED_START_TIME"/>
          </tns:plannedStartTime>
          <tns:plannedEndTimeSec>
            <xsl:value-of select="ns0:PLANNED_END_TIME_SEC"/>
          </tns:plannedEndTimeSec>
          <tns:plannedEndTime>
            <xsl:value-of select="ns0:PLANNED_END_TIME"/>
          </tns:plannedEndTime>
          <tns:plannedTransitReadyTime>
            <xsl:value-of select="ns0:PLANNED_TRANSIT_READY_TIME"/>
          </tns:plannedTransitReadyTime>
          <tns:epst>
            <xsl:value-of select="ns0:EPST"/>
          </tns:epst>
          <tns:lpst>
            <xsl:value-of select="ns0:LPST"/>
          </tns:lpst>
          <tns:clst>
            <xsl:value-of select="ns0:CLST"/>
          </tns:clst>
          <tns:cest>
            <xsl:value-of select="ns0:CEST"/>
          </tns:cest>
          <tns:defaultScalarTimeUom>
            <xsl:value-of select="ns0:DEFAULT_SCALAR_TIME_UOM"/>
          </tns:defaultScalarTimeUom>
          <tns:balQueueTime>
            <xsl:value-of select="ns0:BAL_QUEUE_TIME"/>
          </tns:balQueueTime>
          <tns:balCooldownTimeUom>
            <xsl:value-of select="ns0:BAL_COOLDOWN_TIME_UOM"/>
          </tns:balCooldownTimeUom>
          <tns:balCooldownTime>
            <xsl:value-of select="ns0:BAL_COOLDOWN_TIME"/>
          </tns:balCooldownTime>
          <tns:balTransportTime>
            <xsl:value-of select="ns0:BAL_TRANSPORT_TIME"/>
          </tns:balTransportTime>
          <tns:lockCount>
            <xsl:value-of select="ns0:LOCK_COUNT"/>
          </tns:lockCount>
          <tns:defaultMaterialQtyUom>
            <xsl:value-of select="ns0:DEFAULT_MATERIAL_QTY_UOM"/>
          </tns:defaultMaterialQtyUom>
          <tns:plannedInputQty>
            <xsl:value-of select="ns0:PLANNED_INPUT_QTY"/>
          </tns:plannedInputQty>
          <tns:plannedOutputQty>
            <xsl:value-of select="ns0:PLANNED_OUTPUT_QTY"/>
          </tns:plannedOutputQty>
          <tns:plannedRuntime>
            <xsl:value-of select="ns0:PLANNED_RUNTIME"/>
          </tns:plannedRuntime>
          <tns:stretchedRuntime>
            <xsl:value-of select="ns0:STRETCHED_RUNTIME"/>
          </tns:stretchedRuntime>
          <tns:remainingPushes>
            <xsl:value-of select="ns0:REMAINING_PUSHES"/>
          </tns:remainingPushes>
          <tns:remainingPulls>
            <xsl:value-of select="ns0:REMAINING_PULLS"/>
          </tns:remainingPulls>
          <tns:scheduleTaskPriority>
            <xsl:value-of select="ns0:SCHEDULE_TASK_PRIORITY"/>
          </tns:scheduleTaskPriority>
          <tns:caoPriorityFormat>
            <xsl:value-of select="ns0:CAO_PRIORITY_FORMAT"/>
          </tns:caoPriorityFormat>
          <tns:caoPriority>
            <xsl:value-of select="normalize-space (ns0:CAO_PRIORITY)"/>
          </tns:caoPriority>
          <tns:routing>
            <xsl:value-of select="ns0:ROUTING"/>
          </tns:routing>
          <tns:parallelIndex>
            <xsl:value-of select="ns0:PARALLEL_INDEX"/>
          </tns:parallelIndex>
          <tns:numberOfParallelSubtasks>
            <xsl:value-of select="ns0:NUMBER_OF_PARALLEL_SUBTASKS"/>
          </tns:numberOfParallelSubtasks>
          <tns:granularity>
            <xsl:value-of select="ns0:GRANULARITY"/>
          </tns:granularity>
          <tns:schedulingPosition>
            <xsl:value-of select="ns0:SCHEDULING_POSITION"/>
          </tns:schedulingPosition>
          <tns:resourceSequenceId>
            <xsl:value-of select="ns0:RESOURCE_SEQUENCE_ID"/>
          </tns:resourceSequenceId>
          <tns:schedulerComments>
            <xsl:value-of select="ns0:SCHEDULER_COMMENTS"/>
          </tns:schedulerComments>
          <tns:originalScheduledStartTime>
            <xsl:value-of select="ns0:ORIGINAL_SCHEDULED_START_TIME"/>
          </tns:originalScheduledStartTime>
          <tns:keepUserScheduledStart>
            <xsl:value-of select="ns0:KEEP_USER_SCHEDULED_START"/>
          </tns:keepUserScheduledStart>
          <tns:setupStartTime>
            <xsl:value-of select="ns0:SETUP_START_TIME"/>
          </tns:setupStartTime>
          <tns:setupEndTime>
            <xsl:value-of select="ns0:SETUP_END_TIME"/>
          </tns:setupEndTime>
          <tns:lpct>
            <xsl:value-of select="ns0:LPCT"/>
          </tns:lpct>
          <tns:lpctFormat>
            <xsl:value-of select="ns0:LPCT_FORMAT"/>
          </tns:lpctFormat>
          <tns:lastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:lastUpdateDate>
          <tns:lastUpdatedBy>
            <xsl:value-of select="'1233'"/>
          </tns:lastUpdatedBy>
          <tns:lastUpdateLogin>
            <xsl:value-of select="'-1'"/>
          </tns:lastUpdateLogin>
          <tns:creationDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:creationDate>
          <tns:createdBy>
            <xsl:value-of select="'1233'"/>
          </tns:createdBy>
          <tns:processStatus>
            <xsl:value-of select="'NEW'"/>
          </tns:processStatus>
        </tns:XxnucGmeJdaMfgPlanStg>
      </xsl:for-each>
    </tns:XxnucGmeJdaMfgPlanStgCollection>
  </xsl:template>
</xsl:stylesheet>
