<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/JDAPRodScheduleTransition/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertJDAProductionSchedule"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ftp/NextGen/NUC_JDA_EBiz_BatchSchedule_ABF/FTP_ReadProduction_Schedule"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/ftp/1.1/NUC_JDA_Ebiz_BatchSchedule_ABF/FTP_GetTriggerFile"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen/NUC_JDA_EBiz_BatchSchedule_ABF/DB_InsertJDAProductionSchedule">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadProduction_Schedule.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ProdScheduleList"
                                       namespace="http://xmlns.oracle.com/NUC_Ebiz_JDA_Batch_ABF/JDAPRodScheduleTransition/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_GetTriggerFile.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="gblParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_InsertJDAProductionSchedule.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucGmeJdaTrnScheduleStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertJDAProductionSchedule"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 30 15:40:57 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="gblParameters"/>
  <xsl:template match="/">
    <tns:XxnucGmeJdaTrnScheduleStgCollection>
      <xsl:for-each select="/ns0:ProdScheduleList/ns0:ProdSchedule">
        <tns:XxnucGmeJdaTrnScheduleStg>
          <tns:recordId>
            <xsl:value-of select='oraext:sequence-next-val ("xxnuc.XXNUC_GME_JDA_TRN_SCHEDULE_S", "jdbc/ebsapps" )'/>
          </tns:recordId>
          <tns:organizationId>
            <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/JDA_EBS_INSTANCE_ORG_RESOURCE_MAP.dvm", "Instance", $gblParameters/ns1:parameters/ns1:item/ns1:value, "Org_Id", "0" )'/>
          </tns:organizationId>
          <tns:resourceId>
            <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/JDA_EBS_INSTANCE_ORG_RESOURCE_MAP.dvm", "Instance", $gblParameters/ns1:parameters/ns1:item/ns1:value, "Resource", "0" )'/>
          </tns:resourceId>
          <tns:formattedMfgOrderOutQty>
            <xsl:value-of select="ns0:formatted_mfg_order_output_qty"/>
          </tns:formattedMfgOrderOutQty>
          <tns:formattedPlannedInQty>
            <xsl:value-of select="ns0:formatted_planned_input_qty"/>
          </tns:formattedPlannedInQty>
          <tns:formattedPlannedOutQty>
            <xsl:value-of select="ns0:formatted_planned_output_qty"/>
          </tns:formattedPlannedOutQty>
          <tns:keepUserScheduledStart>
            <xsl:value-of select="ns0:keep_user_scheduled_start"/>
          </tns:keepUserScheduledStart>
          <tns:mfgOrderId>
            <xsl:value-of select="ns0:mfg_order_id"/>
          </tns:mfgOrderId>
          <tns:mfgOrderOutputQty>
            <xsl:value-of select="ns0:mfg_order_output_qty"/>
          </tns:mfgOrderOutputQty>
          <tns:mfgOrderOutputQtyFormat>
            <xsl:value-of select="ns0:mfg_order_output_qty_format"/>
          </tns:mfgOrderOutputQtyFormat>
          <tns:mfgOrderOutputQtyUom>
            <xsl:value-of select="ns0:mfg_order_output_qty_uom"/>
          </tns:mfgOrderOutputQtyUom>
          <tns:operationId>
            <xsl:value-of select="ns0:operation_id"/>
          </tns:operationId>
          <tns:originalSchedStartTime>
            <xsl:value-of select="ns0:original_scheduled_start_time"/>
          </tns:originalSchedStartTime>
          <tns:originalSchedStartTimeF>
            <xsl:value-of select="ns0:original_scheduled_start_time_format"/>
          </tns:originalSchedStartTimeF>
          <tns:parallelInd>
            <xsl:value-of select="ns0:parallel_index"/>
          </tns:parallelInd>
          <tns:plannedEndTime>
            <xsl:value-of select="ns0:planned_end_time"/>
          </tns:plannedEndTime>
          <tns:plannedEndTimeFormat>
            <xsl:value-of select="ns0:planned_end_time_format"/>
          </tns:plannedEndTimeFormat>
          <tns:plannedInputQty>
            <xsl:value-of select="ns0:planned_input_qty"/>
          </tns:plannedInputQty>
          <tns:plannedInputQtyFormat>
            <xsl:value-of select="ns0:planned_input_qty_format"/>
          </tns:plannedInputQtyFormat>
          <tns:plannedInputQtyUom>
            <xsl:value-of select="ns0:planned_input_qty_uom"/>
          </tns:plannedInputQtyUom>
          <tns:plannedOutputQty>
            <xsl:value-of select="ns0:planned_output_qty"/>
          </tns:plannedOutputQty>
          <tns:plannedOutputQtyFormat>
            <xsl:value-of select="ns0:planned_output_qty_format"/>
          </tns:plannedOutputQtyFormat>
          <tns:plannedOutputQtyUom>
            <xsl:value-of select="ns0:planned_output_qty_uom"/>
          </tns:plannedOutputQtyUom>
          <tns:plannedStartTime>
            <xsl:value-of select="ns0:planned_start_time"/>
          </tns:plannedStartTime>
          <tns:plannedStartTimeFormat>
            <xsl:value-of select="ns0:planned_start_time_format"/>
          </tns:plannedStartTimeFormat>
          <tns:plannedTransitReadyTime>
            <xsl:value-of select="ns0:planned_transit_ready_time"/>
          </tns:plannedTransitReadyTime>
          <tns:plannedTransitReadyTimeF>
            <xsl:value-of select="ns0:planned_transit_ready_time_format"/>
          </tns:plannedTransitReadyTimeF>
          <tns:primaryOutputPart>
            <xsl:value-of select="ns0:primary_output_part"/>
          </tns:primaryOutputPart>
          <tns:resourc>
            <xsl:value-of select="ns0:resource"/>
          </tns:resourc>
          <tns:routing>
            <xsl:value-of select="ns0:routing"/>
          </tns:routing>
          <tns:schedulerComments>
            <xsl:value-of select="ns0:scheduler_comments"/>
          </tns:schedulerComments>
          <tns:schedulingPosition>
            <xsl:value-of select="ns0:scheduling_position"/>
          </tns:schedulingPosition>
          <tns:setupEndTime>
            <xsl:value-of select="ns0:setup_end_time"/>
          </tns:setupEndTime>
          <tns:setupStartTime>
            <xsl:value-of select="ns0:setup_start_time"/>
          </tns:setupStartTime>
          <tns:setupTimeFormat>
            <xsl:value-of select="ns0:setup_time_format"/>
          </tns:setupTimeFormat>
          <tns:setupTime>
            <xsl:value-of select="ns0:setup_time"/>
          </tns:setupTime>
          <tns:setupTimeUom>
            <xsl:value-of select="ns0:setup_time_uom"/>
          </tns:setupTimeUom>
          <tns:stepNumber>
            <xsl:value-of select="ns0:step_number"/>
          </tns:stepNumber>
        </tns:XxnucGmeJdaTrnScheduleStg>
      </xsl:for-each>
    </tns:XxnucGmeJdaTrnScheduleStgCollection>
  </xsl:template>
</xsl:stylesheet>