package model.client;

import java.util.Date;

import model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 31 13:05:22 IST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public String callStoreprocedurePurgeScript(Date StartTime, Date EndTime,
                                                Integer TransactionStatus,
                                                Integer Days) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callStoreprocedurePurgeScript",new String [] {"java.util.Date","java.util.Date","java.lang.Integer","java.lang.Integer"},new Object[] {StartTime, EndTime, TransactionStatus, Days});
        return (String)_ret;
    }

    public String PurgeTimeStatus(Date StartTime, Date EndTime,
                                  Integer TransactionStatus) {
        Object _ret =
            this.riInvokeExportedMethod(this,"PurgeTimeStatus",new String [] {"java.util.Date","java.util.Date","java.lang.Integer"},new Object[] {StartTime, EndTime, TransactionStatus});
        return (String)_ret;
    }

    public String PurgeDays(Integer Days) {
        Object _ret =
            this.riInvokeExportedMethod(this,"PurgeDays",new String [] {"java.lang.Integer"},new Object[] {Days});
        return (String)_ret;
    }
}
