<wsdl:definitions
     name="DB_Proc_QMOS_PROD"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSUT_HeatCastBatch_QMOS_EBiz_ABF/DB_Proc_QMOS_PROD"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSUT_HeatCastBatch_QMOS_EBiz_ABF/DB_Proc_QMOS_PROD"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_QMOS_PROD"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Proc_QMOS_PROD_plt" >
    <plt:role name="DB_Proc_QMOS_PROD_role" >
      <plt:portType name="tns:DB_Proc_QMOS_PROD_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_QMOS_PROD"
               schemaLocation="../Schemas/DB_Proc_QMOS_PROD_sp.xsd" />
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="DB_Proc_QMOS_PROD_ptt">
        <wsdl:operation name="DB_Proc_QMOS_PROD">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
