<wsdl:definitions
     name="DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DV1_Application/NSUT_HeatCastBatch_QMOS_EBiz_ABF/DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DV1_Application/NSUT_HeatCastBatch_QMOS_EBiz_ABF/DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId_plt" >
    <plt:role name="DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId_role" >
      <plt:portType name="tns:DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId" schemaLocation="../Schemas/DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_Update_API_PROD_CONFIRM_MATERIALByHeaderIdInput_msg">
        <wsdl:part name="DB_Update_API_PROD_CONFIRM_MATERIALByHeaderIdInput_msg" element="db:DB_Update_API_PROD_CONFIRM_MATERIALByHeaderIdInput"/>
    </wsdl:message>
    <wsdl:portType name="DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId_ptt">
        <wsdl:operation name="DB_Update_API_PROD_CONFIRM_MATERIALByHeaderId">
            <wsdl:input message="tns:DB_Update_API_PROD_CONFIRM_MATERIALByHeaderIdInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
