<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/apps/otm"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/NUC_WriteBOLShipment_OTM_RailInc_ABF/BOLShipment/1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABF/NUC_WriteBOLShipment_OTM_Transentric_ABF/WriteBOLShipment"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/ftp/OTM/NUC_WriteBOLShipment_OTM_RailInc_ABF/FTP_PutFileRailInc"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/WriteBOLShipment.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_PutFileRailInc.wsdl"/>
        <oracle-xsl-mapper:rootElement name="BOL"
                                       namespace="http://xmlns.oracle.com/NUC_WriteBOLShipment_OTM_RailInc_ABF/BOLShipment/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JUL 06 11:33:47 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:BOL>
      <tns:CLUCInputHeader>
        <tns:InquiryID>CLU</tns:InquiryID>
        <tns:CustomInfoIndicator>C</tns:CustomInfoIndicator>
        <tns:TO>TO</tns:TO>
        <tns:Space1/>
        <tns:SCAC>RRDC</tns:SCAC>
        <tns:Space2/>
        <tns:FleetID>SMG</tns:FleetID>
        <tns:FleetaUpdateCode/>
        <tns:DateHour/>
        <tns:ControlID/>
      </tns:CLUCInputHeader>
      <tns:CLUCInputDetailLines>
        <tns:FleetStatusCode>T</tns:FleetStatusCode>
        <tns:EquipmentInitials>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:SEquipment/ns0:EquipmentInitial"/>
        </tns:EquipmentInitials>
        <tns:EquipmentNumber>
          <xsl:value-of select="string(number(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:SEquipment/ns0:EquipmentNumber))"/>
        </tns:EquipmentNumber>
        <tns:CustomInfo>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:ShipmentHeader/ns0:ShipmentRefnum[ns0:ShipmentRefnumQualifierGid/ns0:Gid/ns0:Xid='MBOL_NUMBER']/ns0:ShipmentRefnumValue"/>
        </tns:CustomInfo>
      </tns:CLUCInputDetailLines>
      <tns:CLUCInputTrailer>
        <tns:Trailer>EOM</tns:Trailer>
      </tns:CLUCInputTrailer>
    </tns:BOL>
  </xsl:template>
</xsl:stylesheet>
