<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Process_Billet_Trx_EBS"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Get_Billet_Trx"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSSEA_Billet_EBSMTLTrxImp_ABF/DB_Get_Billet_Trx"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSSEA_Billet_EBSMTLTrxImp_ABF/DB_Process_Billet_Trx_EBS">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Get_Billet_Trx.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiBilletTransCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Get_Billet_Trx"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Process_Billet_Trx_EBS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Process_Billet_Trx_EBS"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON APR 10 04:51:41 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_TRX_TAB>
        <xsl:for-each select="/ns0:ApiBilletTransCollection/ns0:ApiBilletTrans">
          <tns:P_TRX_TAB_ITEM>
            <tns:ID>
              <xsl:value-of select="ns0:id"/>
            </tns:ID>
            <tns:TRANSACTION_TYPE>
              <xsl:value-of select="ns0:transactionType"/>
            </tns:TRANSACTION_TYPE>
            <tns:HEAT_FROM>
              <xsl:value-of select="ns0:heatFrom"/>
            </tns:HEAT_FROM>
            <tns:HEAT>
              <xsl:value-of select="ns0:heat"/>
            </tns:HEAT>
            <tns:PART_CODE_FROM>
              <xsl:value-of select="ns0:partCodeFrom"/>
            </tns:PART_CODE_FROM>
            <tns:PART_CODE>
              <xsl:value-of select="ns0:partCode"/>
            </tns:PART_CODE>
            <tns:SHAPE>
              <xsl:value-of select="ns0:shape"/>
            </tns:SHAPE>
            <tns:BILLET_SIZE>
              <xsl:value-of select="ns0:billetSize"/>
            </tns:BILLET_SIZE>
            <tns:GRADE>
              <xsl:value-of select="ns0:grade"/>
            </tns:GRADE>
            <tns:LENGTH_INCHES>
              <xsl:value-of select="ns0:lengthInches"/>
            </tns:LENGTH_INCHES>
            <tns:SUBINVENTORY_CODE>CAST</tns:SUBINVENTORY_CODE>
            <tns:STACK_FROM>
              <xsl:value-of select="ns0:stackFrom"/>
            </tns:STACK_FROM>
            <tns:STACK_LAYER_FROM>
              <xsl:value-of select="ns0:stackLayerFrom"/>
            </tns:STACK_LAYER_FROM>
            <tns:STACK>
              <xsl:value-of select="ns0:stack"/>
            </tns:STACK>
            <tns:STACK_LAYER>
              <xsl:value-of select="ns0:stackLayer"/>
            </tns:STACK_LAYER>
            <tns:DISPOSITION_FROM>
              <xsl:value-of select="ns0:dispositionFrom"/>
            </tns:DISPOSITION_FROM>
            <tns:DISPOSITION>
              <xsl:value-of select="ns0:disposition"/>
            </tns:DISPOSITION>
            <tns:BILLET_COUNT>
              <xsl:value-of select="ns0:billetCount"/>
            </tns:BILLET_COUNT>
            <tns:WEIGHT_LBS>
              <xsl:value-of select="ns0:weightLbs"/>
            </tns:WEIGHT_LBS>
            <tns:CREW>
              <xsl:value-of select="ns0:crew"/>
            </tns:CREW>
            <tns:SHIFT>
              <xsl:value-of select="ns0:shift"/>
            </tns:SHIFT>
            <tns:USER_ID>
              <xsl:value-of select="ns0:userId"/>
            </tns:USER_ID>
            <tns:USER_FIRST_NAME>
              <xsl:value-of select="ns0:userFirstName"/>
            </tns:USER_FIRST_NAME>
            <tns:USER_LAST_NAME>
              <xsl:value-of select="ns0:userLastName"/>
            </tns:USER_LAST_NAME>
            <tns:HOLD_CODE_1_FROM>
              <xsl:value-of select="ns0:holdCode1_From"/>
            </tns:HOLD_CODE_1_FROM>
            <tns:HOLD_CODE_2_FROM>
              <xsl:value-of select="ns0:holdCode2_From"/>
            </tns:HOLD_CODE_2_FROM>
            <tns:HOLD_CODE_3_FROM>
              <xsl:value-of select="ns0:holdCode3_From"/>
            </tns:HOLD_CODE_3_FROM>
            <tns:HOLD_CODE_4_FROM>
              <xsl:value-of select="ns0:holdCode4_From"/>
            </tns:HOLD_CODE_4_FROM>
            <tns:HOLD_CODE_5_FROM>
              <xsl:value-of select="ns0:holdCode5_From"/>
            </tns:HOLD_CODE_5_FROM>
            <tns:HOLD_CODE_1>
              <xsl:value-of select="ns0:holdCode1"/>
            </tns:HOLD_CODE_1>
            <tns:HOLD_CODE_2>
              <xsl:value-of select="ns0:holdCode2"/>
            </tns:HOLD_CODE_2>
            <tns:HOLD_CODE_3>
              <xsl:value-of select="ns0:holdCode3"/>
            </tns:HOLD_CODE_3>
            <tns:HOLD_CODE_4>
              <xsl:value-of select="ns0:holdCode4"/>
            </tns:HOLD_CODE_4>
            <tns:HOLD_CODE_5>
              <xsl:value-of select="ns0:holdCode5"/>
            </tns:HOLD_CODE_5>
            <tns:PROCESSED>
              <xsl:value-of select="ns0:processed"/>
            </tns:PROCESSED>
            <tns:PROCESS_DATE>
              <xsl:value-of select="ns0:processDate"/>
            </tns:PROCESS_DATE>
            <tns:CREATE_DATE>
              <xsl:value-of select="ns0:createDate"/>
            </tns:CREATE_DATE>
            <tns:TAP_DATE>
              <xsl:value-of select="ns0:tapDate"/>
            </tns:TAP_DATE>
            <tns:CAST_DATE>
              <xsl:value-of select="ns0:castDate"/>
            </tns:CAST_DATE>
            <tns:PARTCODE_TO_COPY>
              <xsl:value-of select="ns0:partcodeToCopy"/>
            </tns:PARTCODE_TO_COPY>
            <tns:FACTORY>
              <xsl:value-of select="ns0:factory"/>
            </tns:FACTORY>
            <tns:JOB_NUMBER>
              <xsl:value-of select="ns0:jobNumber"/>
            </tns:JOB_NUMBER>
            <tns:REHEAT>
              <xsl:value-of select="ns0:reheat"/>
            </tns:REHEAT>
            <tns:PRODUCTION_MINUTES>
              <xsl:value-of select="ns0:productionMinutes"/>
            </tns:PRODUCTION_MINUTES>
            <tns:CUSTOMER_REFERENCE>
              <xsl:value-of select="ns0:customerReference"/>
            </tns:CUSTOMER_REFERENCE>
            <tns:REWORK>
              <xsl:value-of select="ns0:rework"/>
            </tns:REWORK>
            <tns:COBBLES>
              <xsl:value-of select="ns0:cobbles"/>
            </tns:COBBLES>
            <tns:ERROR_MESSAGE>
              <xsl:value-of select="ns0:errorMessage"/>
            </tns:ERROR_MESSAGE>
            <tns:BILLET_BATCH>
              <xsl:value-of select="ns0:billetBatch"/>
            </tns:BILLET_BATCH>
            <tns:BILLET_TRX_DTLS>
              <xsl:for-each select="ns0:apiBilletTransDtlsCollection/ns0:ApiBilletTransDtls">
                <tns:BILLET_TRX_DTLS_ITEM>
                  <tns:ID>
                    <xsl:value-of select="ns0:id"/>
                  </tns:ID>
                  <tns:API_BILLET_TRANS_ID>
                    <xsl:value-of select="../../ns0:id"/>
                  </tns:API_BILLET_TRANS_ID>
                  <tns:BILLET_ID>
                    <xsl:value-of select="ns0:billetId"/>
                  </tns:BILLET_ID>
                  <tns:PROCESSED>
                    <xsl:value-of select="ns0:processed"/>
                  </tns:PROCESSED>
                  <tns:PROCESS_DATE>
                    <xsl:value-of select="ns0:processDate"/>
                  </tns:PROCESS_DATE>
                  <tns:ERROR_MESSAGE>
                    <xsl:value-of select="ns0:errorMessage"/>
                  </tns:ERROR_MESSAGE>
                  <tns:PARENT_BILLET_ID>
                    <xsl:value-of select="ns0:parentBilletId"/>
                  </tns:PARENT_BILLET_ID>
                  <tns:PART_CODE>
                    <xsl:value-of select="ns0:partCode"/>
                  </tns:PART_CODE>
                  <tns:SHAPE>
                    <xsl:value-of select="ns0:shape"/>
                  </tns:SHAPE>
                  <tns:BILLET_SIZE>
                    <xsl:value-of select="ns0:billetSize"/>
                  </tns:BILLET_SIZE>
                  <tns:GRADE>
                    <xsl:value-of select="ns0:grade"/>
                  </tns:GRADE>
                  <tns:LENGTH_INCHES>
                    <xsl:value-of select="ns0:lengthInches"/>
                  </tns:LENGTH_INCHES>
                  <tns:STACK>
                    <xsl:value-of select="ns0:stack"/>
                  </tns:STACK>
                  <tns:BILLET_BATCH>
                    <xsl:value-of select="ns0:billetBatch"/>
                  </tns:BILLET_BATCH>
                  <tns:WEIGHT_LBS>
                    <xsl:value-of select="ns0:weightLbs"/>
                  </tns:WEIGHT_LBS>
                </tns:BILLET_TRX_DTLS_ITEM>
              </xsl:for-each>
            </tns:BILLET_TRX_DTLS>
          </tns:P_TRX_TAB_ITEM>
        </xsl:for-each>
      </tns:P_TRX_TAB>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
