<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_GetOrigSystemRef" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/OrigSystemRefAO/1.0" xmlns:osram="http://xmlns.eia.com/AO/EBiz/common/OrigSystemRefAM/1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://xmlns.eia.com/ABS/EBiz/OrigSystemRefABS/1.0" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:core="http://xmlns.eia.com/EO/Common/1.0" xmlns:ns1="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Test/NUC_EBizOrigSystemRef_ABS/DB_GetOrigSystemRef" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl top plt wsdl tns xsd ns2 osram ns0 soap12 soap mime core ns1 ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../DB_GetOrigSystemRef.wsdl"/>
            <oracle-xsl-mapper:rootElement name="HzOrigSysReferencesCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_GetOrigSystemRef"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/common/OrigSystemRefABS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="QueryOSRSyncResponseMessage" namespace="http://xmlns.eia.com/AO/EBiz/common/OrigSystemRefAM/1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED SEP 09 14:04:41 CDT 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <osram:QueryOSRSyncResponseMessage>
      <osram:ListOfOrigSystemRefs>
      <xsl:for-each select="/top:HzOrigSysReferencesCollection/top:HzOrigSysReferences">
        <ns2:OrigSystemRef>
          <ns2:BasicOrigSystemRef>
            <ns2:OldOrigSystemReference>
              <xsl:value-of select="top:oldOrigSystemReference"/>
            </ns2:OldOrigSystemReference>
            <ns2:OrigSystem>
              <xsl:value-of select="top:origSystem"/>
            </ns2:OrigSystem>
            <ns2:OrigSystemReference>
              <xsl:value-of select="top:origSystemReference"/>
            </ns2:OrigSystemReference>
            <ns2:OrigSystemRefId>
              <xsl:value-of select="top:origSystemRefId"/>
            </ns2:OrigSystemRefId>
          </ns2:BasicOrigSystemRef>
          <ns2:Attribute1>
            <xsl:value-of select="top:attribute1"/>
          </ns2:Attribute1>
          <ns2:Attribute10>
            <xsl:value-of select="top:attribute10"/>
          </ns2:Attribute10>
          <ns2:Attribute11>
            <xsl:value-of select="top:attribute11"/>
          </ns2:Attribute11>
          <ns2:Attribute12>
            <xsl:value-of select="top:attribute12"/>
          </ns2:Attribute12>
          <ns2:Attribute13>
            <xsl:value-of select="top:attribute13"/>
          </ns2:Attribute13>
          <ns2:Attribute14>
            <xsl:value-of select="top:attribute14"/>
          </ns2:Attribute14>
          <ns2:Attribute15>
            <xsl:value-of select="top:attribute15"/>
          </ns2:Attribute15>
          <ns2:Attribute16>
            <xsl:value-of select="top:attribute16"/>
          </ns2:Attribute16>
          <ns2:Attribute17>
            <xsl:value-of select="top:attribute17"/>
          </ns2:Attribute17>
          <ns2:Attribute18>
            <xsl:value-of select="top:attribute18"/>
          </ns2:Attribute18>
          <ns2:Attribute19>
            <xsl:value-of select="top:attribute19"/>
          </ns2:Attribute19>
          <ns2:Attribute2>
            <xsl:value-of select="top:attribute2"/>
          </ns2:Attribute2>
          <ns2:Attribute20>
            <xsl:value-of select="top:attribute20"/>
          </ns2:Attribute20>
          <ns2:Attribute3>
            <xsl:value-of select="top:attribute3"/>
          </ns2:Attribute3>
          <ns2:Attribute4>
            <xsl:value-of select="top:attribute4"/>
          </ns2:Attribute4>
          <ns2:Attribute5>
            <xsl:value-of select="top:attribute5"/>
          </ns2:Attribute5>
          <ns2:Attribute6>
            <xsl:value-of select="top:attribute6"/>
          </ns2:Attribute6>
          <ns2:Attribute7>
            <xsl:value-of select="top:attribute7"/>
          </ns2:Attribute7>
          <ns2:Attribute8>
            <xsl:value-of select="top:attribute8"/>
          </ns2:Attribute8>
          <ns2:Attribute9>
            <xsl:value-of select="top:attribute9"/>
          </ns2:Attribute9>
          <ns2:AttributeCategory>
            <xsl:value-of select="top:attributeCategory"/>
          </ns2:AttributeCategory>
          <ns2:CreatedByModule>
            <xsl:value-of select="top:createdByModule"/>
          </ns2:CreatedByModule>
          <ns2:CreatedByName>
            <xsl:value-of select="top:createdBy"/>
          </ns2:CreatedByName>
          <ns2:CreationDate>
            <xsl:value-of select="top:creationDate"/>
          </ns2:CreationDate>
          <ns2:EndDateActive>
            <xsl:value-of select="top:endDateActive"/>
          </ns2:EndDateActive>
          <ns2:LastUpdatedByName>
            <xsl:value-of select="top:lastUpdatedBy"/>
          </ns2:LastUpdatedByName>
          <ns2:LastUpdateDate>
            <xsl:value-of select="top:lastUpdateDate"/>
          </ns2:LastUpdateDate>
          <ns2:ObjectId>
            <xsl:value-of select="top:ownerTableId"/>
          </ns2:ObjectId>
          <ns2:ObjectType>
            <xsl:value-of select="top:ownerTableName"/>
          </ns2:ObjectType>
          <ns2:ProgramUpdateDate>
            <xsl:value-of select="top:programUpdateDate"/>
          </ns2:ProgramUpdateDate>
          <ns2:ReasonCode>
            <xsl:value-of select="top:reasonCode"/>
          </ns2:ReasonCode>
          <ns2:StartDateActive>
            <xsl:value-of select="top:startDateActive"/>
          </ns2:StartDateActive>
          <ns2:Status>
            <xsl:value-of select="top:status"/>
          </ns2:Status>
          <ns2:PartyId>
            <xsl:value-of select="top:partyId"/>
          </ns2:PartyId>
          <ns2:ObjectVersionNumber>
            <xsl:value-of select="top:objectVersionNumber"/>
          </ns2:ObjectVersionNumber>
        </ns2:OrigSystemRef>
        </xsl:for-each>
      </osram:ListOfOrigSystemRefs>
    </osram:QueryOSRSyncResponseMessage>
  </xsl:template>
</xsl:stylesheet>