<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:eia="http://xmlns.eia.com/extensions/1.0" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://xmlns.eia.com/AO/EBiz/common/OrigSystemRefAO/1.0" xmlns:osram="http://xmlns.eia.com/AO/EBiz/common/OrigSystemRefAM/1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:tns="http://xmlns.eia.com/ABS/EBiz/OrigSystemRefABS/1.0" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/apps/Test/NUC_EBizOrigSystemRef_ABS/OA_CreateOSR" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:core="http://xmlns.eia.com/EO/Common/1.0" xmlns:ns0="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_CreateOSR" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 osram tns soap12 soap wsdl mime core ns0 ns2 xsd plt ns3 db bpws xp20 eia bpel bpm utl ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/common/OrigSystemRefABS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateOSRSyncRequestMessage" namespace="http://xmlns.eia.com/AO/EBiz/common/OrigSystemRefAM/1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../OA_CreateOSR.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_CreateOSR"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED SEP 09 14:04:41 CDT 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <db:InputParameters>
      <db:P_ORIG_SYS_REFS>
        <db:P_ORIG_SYS_REFS_ITEM>
          <db:ACTION_TYPE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:ActionType"/>
          </db:ACTION_TYPE>
          <db:ORIG_SYSTEM_REF_ID>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:BasicOrigSystemRef/ns1:OrigSystemRefId"/>
          </db:ORIG_SYSTEM_REF_ID>
          <db:ORIG_SYSTEM>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:BasicOrigSystemRef/ns1:OrigSystem"/>
          </db:ORIG_SYSTEM>
          <db:ORIG_SYSTEM_REFERENCE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:BasicOrigSystemRef/ns1:OrigSystemReference"/>
          </db:ORIG_SYSTEM_REFERENCE>
          <db:OBJECT_TYPE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:ObjectType"/>
          </db:OBJECT_TYPE>
          <db:OBJECT_ID>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:ObjectId"/>
          </db:OBJECT_ID>
          <db:STATUS>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Status"/>
          </db:STATUS>
          <db:REASON_CODE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:ReasonCode"/>
          </db:REASON_CODE>
          <db:OLD_ORIG_SYSTEM_REFERENCE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:BasicOrigSystemRef/ns1:OldOrigSystemReference"/>
          </db:OLD_ORIG_SYSTEM_REFERENCE>
          <db:START_DATE_ACTIVE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:StartDateActive"/>
          </db:START_DATE_ACTIVE>
          <db:END_DATE_ACTIVE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:EndDateActive"/>
          </db:END_DATE_ACTIVE>
          <db:PROGRAM_UPDATE_DATE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:ProgramUpdateDate"/>
          </db:PROGRAM_UPDATE_DATE>
          <db:CREATED_BY_MODULE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:CreatedByModule"/>
          </db:CREATED_BY_MODULE>
          <db:CREATED_BY_NAME>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:CreatedByName"/>
          </db:CREATED_BY_NAME>
          <db:CREATION_DATE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:CreationDate"/>
          </db:CREATION_DATE>
          <db:LAST_UPDATE_DATE>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:LastUpdateDate"/>
          </db:LAST_UPDATE_DATE>
          <db:LAST_UPDATED_BY_NAME>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:LastUpdatedByName"/>
          </db:LAST_UPDATED_BY_NAME>
          <db:ATTRIBUTE_CATEGORY>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:AttributeCategory"/>
          </db:ATTRIBUTE_CATEGORY>
          <db:ATTRIBUTE1>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute1"/>
          </db:ATTRIBUTE1>
          <db:ATTRIBUTE2>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute2"/>
          </db:ATTRIBUTE2>
          <db:ATTRIBUTE3>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute3"/>
          </db:ATTRIBUTE3>
          <db:ATTRIBUTE4>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute4"/>
          </db:ATTRIBUTE4>
          <db:ATTRIBUTE5>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute5"/>
          </db:ATTRIBUTE5>
          <db:ATTRIBUTE6>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute6"/>
          </db:ATTRIBUTE6>
          <db:ATTRIBUTE7>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute7"/>
          </db:ATTRIBUTE7>
          <db:ATTRIBUTE8>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute8"/>
          </db:ATTRIBUTE8>
          <db:ATTRIBUTE9>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute9"/>
          </db:ATTRIBUTE9>
          <db:ATTRIBUTE10>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute10"/>
          </db:ATTRIBUTE10>
          <db:ATTRIBUTE11>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute11"/>
          </db:ATTRIBUTE11>
          <db:ATTRIBUTE12>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute12"/>
          </db:ATTRIBUTE12>
          <db:ATTRIBUTE13>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute13"/>
          </db:ATTRIBUTE13>
          <db:ATTRIBUTE14>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute14"/>
          </db:ATTRIBUTE14>
          <db:ATTRIBUTE15>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute15"/>
          </db:ATTRIBUTE15>
          <db:ATTRIBUTE16>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute16"/>
          </db:ATTRIBUTE16>
          <db:ATTRIBUTE17>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute17"/>
          </db:ATTRIBUTE17>
          <db:ATTRIBUTE18>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute18"/>
          </db:ATTRIBUTE18>
          <db:ATTRIBUTE19>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute19"/>
          </db:ATTRIBUTE19>
          <db:ATTRIBUTE20>
            <xsl:value-of select="/osram:CreateOSRSyncRequestMessage/osram:ListOfOrigSystemRefs/ns1:OrigSystemRef/ns1:Attribute20"/>
          </db:ATTRIBUTE20>
        </db:P_ORIG_SYS_REFS_ITEM>
      </db:P_ORIG_SYS_REFS>
      <db:P_CREATED_BY_MODULE>
        <xsl:text disable-output-escaping="no">TCA_V2_API</xsl:text>
      </db:P_CREATED_BY_MODULE>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>