<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../AccountABS.wsdl"/>
      <rootElement name="QueryByExampleAccountRequestMessage" namespace="http://xmlns.eia.com/AO/EBiz/A2R/AccountAM/1.0"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../DB_QueryByExampleAccountSync.wsdl"/>
      <rootElement name="XxnucGlCodeComboV" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QueryByExampleAccountSync"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU MAY 29 02:16:15 CDT 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:acctam="http://xmlns.eia.com/AO/EBiz/A2R/AccountAM/1.0"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns="http://xmlns.eia.com/ABS/EBiz/A2R/AccountABS/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/Nucor/NUC_EBizGLAccount_ABS/DB_QueryByExampleAccountSync"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QueryByExampleAccountSync"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://xmlns.eia.com/AO/EBiz/A2R/AccountAO/1.0"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl acctam tns soap12 soap mime wsdl core ns0 ns2 xsd ns1 plt ns3 top xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <top:XxnucGlCodeComboV>
      <top:codeCombinationId>
        <xsl:value-of select="/acctam:QueryByExampleAccountRequestMessage/acctam:BasicAccount/ns1:AccountIdentifier"/>
      </top:codeCombinationId>
      <top:concatenatedSegments>
        <xsl:value-of select="/acctam:QueryByExampleAccountRequestMessage/acctam:BasicAccount/ns1:AccountCombination"/>
      </top:concatenatedSegments>
      <top:enabledFlag>
        <xsl:value-of select="/acctam:QueryByExampleAccountRequestMessage/acctam:BasicAccount/ns1:ActiveFlag"/>
      </top:enabledFlag>
      <top:startDateActive>
        <xsl:value-of select="/acctam:QueryByExampleAccountRequestMessage/acctam:BasicAccount/ns1:StartDate"/>
      </top:startDateActive>
      <top:endDateActive>
        <xsl:value-of select="/acctam:QueryByExampleAccountRequestMessage/acctam:BasicAccount/ns1:EndDate"/>
      </top:endDateActive>
      <top:ledgerName>
        <xsl:value-of select="/acctam:QueryByExampleAccountRequestMessage/acctam:BasicAccount/ns1:LedgerName"/>
      </top:ledgerName>
    </top:XxnucGlCodeComboV>
  </xsl:template>
</xsl:stylesheet>
