<wsdl:definitions
     name="DB_Update_API_Billet_Control"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSUT_SubscribeInventory_EBiz_QMOS_ABF/DB_Update_API_Billet_Control"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSUT_SubscribeInventory_EBiz_QMOS_ABF/DB_Update_API_Billet_Control"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Update_API_Billet_Control"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Update_API_Billet_Control_plt" >
    <plt:role name="DB_Update_API_Billet_Control_role" >
      <plt:portType name="tns:DB_Update_API_Billet_Control_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_Update_API_Billet_Control_plt" >
    <plt:role name="DB_Update_API_Billet_Control_role" >
      <plt:portType name="tns:DB_Update_API_Billet_Control_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Update_API_Billet_Control" schemaLocation="../Schemas/DB_Update_API_Billet_Control.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Update_API_Billet_Control" schemaLocation="../Schemas/DB_Update_API_Billet_Control.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_Update_API_Billet_ControlInput_msg">
        <wsdl:part name="DB_Update_API_Billet_ControlInput_msg" element="db:DB_Update_API_Billet_ControlInput"/>
    </wsdl:message>
    <wsdl:portType name="DB_Update_API_Billet_Control_ptt">
        <wsdl:operation name="DB_Update_API_Billet_Control">
            <wsdl:input message="tns:DB_Update_API_Billet_ControlInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
