<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QueryReceiptEBS"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns20="http://xmlns.eia.com/AO/EBiz/common/CategoryAO/1.0"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns2="http://xmlns.eia.com/ABS/EBiz/ReceiptABS/1.0"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns11="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WI_Application/NUC_EBizPOReceipt_ABS/DB_QueryReceiptEBS"
                xmlns:ns16="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns15="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns14="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns18="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0"
                xmlns:ns17="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns19="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_QueryReceiptEBS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="RcvShipmentHeadersCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QueryReceiptEBS"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/ReceiptABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryReceiptRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0"/>
        <oracle-xsl-mapper:param name="QueryByExample_SyncReqMsg.QueryReceiptRequestMessage"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/ReceiptABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryReceiptResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 19 04:56:39 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="QueryByExample_SyncReqMsg.QueryReceiptRequestMessage"/>
  <xsl:template match="/">
    <ns1:QueryReceiptResponseMessage>
      <ns11:HeaderRs>
        <ns11:RequestDetails>
          <ns11:TransactionRequestID>
            <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:TransactionRequestID"/>
          </ns11:TransactionRequestID>
          <ns11:Language>
            <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:Language"/>
          </ns11:Language>
          <ns11:ComponentID>
            <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:ComponentID"/>
          </ns11:ComponentID>
          <ns11:ServiceName>
            <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:ServiceName"/>
          </ns11:ServiceName>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:TransactionIDREF">
            <ns11:TransactionIDREF>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:TransactionIDREF"/>
            </ns11:TransactionIDREF>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:TransactionName">
            <ns11:TransactionName>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:TransactionName"/>
            </ns11:TransactionName>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:FileName">
            <ns11:FileName>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:FileName"/>
            </ns11:FileName>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:FileInstanceID">
            <ns11:FileInstanceID>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:FileInstanceID"/>
            </ns11:FileInstanceID>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:Source">
            <ns11:Source>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:Source"/>
            </ns11:Source>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:Target">
            <ns11:Target>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:Target"/>
            </ns11:Target>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:HostName">
            <ns11:HostName>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:HostName"/>
            </ns11:HostName>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:UserName">
            <ns11:UserName>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:UserName"/>
            </ns11:UserName>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:UserRole">
            <ns11:UserRole>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:UserRole"/>
            </ns11:UserRole>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:AdminEmail">
            <ns11:AdminEmail>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:AdminEmail"/>
            </ns11:AdminEmail>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:ApplicationResponsibility">
            <ns11:ApplicationResponsibility>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:ApplicationResponsibility"/>
            </ns11:ApplicationResponsibility>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:EOFFlag">
            <ns11:EOFFlag>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:EOFFlag"/>
            </ns11:EOFFlag>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:SOFFlag">
            <ns11:SOFFlag>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:SOFFlag"/>
            </ns11:SOFFlag>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:FileRecordCount">
            <ns11:FileRecordCount>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:FileRecordCount"/>
            </ns11:FileRecordCount>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:TimeStamp">
            <ns11:TimeStamp>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:TimeStamp"/>
            </ns11:TimeStamp>
          </xsl:if>
          <xsl:if test="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:MillName">
            <ns11:MillName>
              <xsl:value-of select="$QueryByExample_SyncReqMsg.QueryReceiptRequestMessage/ns1:QueryReceiptRequestMessage/ns11:HeaderRq/ns11:MillName"/>
            </ns11:MillName>
          </xsl:if>
        </ns11:RequestDetails>
        <ns11:Status>
          <ns11:Status>SUCCESS</ns11:Status>
        </ns11:Status>
      </ns11:HeaderRs>
      <ns1:OperationResult>
        <ns3:Stats>S</ns3:Stats>
      </ns1:OperationResult>
      <ns1:ListOfReceipts>
        <xsl:for-each select="/ns0:RcvShipmentHeadersCollection/ns0:RcvShipmentHeaders">
          <ns7:Receipt>
            <ns7:BasicReceipt>
              <ns7:IndentfierID>
                <xsl:value-of select="ns0:shipmentHeaderId"/>
              </ns7:IndentfierID>
              <ns7:ReceiptNumber>
                <xsl:value-of select="ns0:receiptNum"/>
              </ns7:ReceiptNumber>
              <xsl:if test='ns0:shipmentNum and (ns0:shipmentNum != "")'>
                <ns7:ShipmentNumber>
                  <xsl:value-of select="ns0:shipmentNum"/>
                </ns7:ShipmentNumber>
              </xsl:if>
              <xsl:if test='ns0:billOfLading and (ns0:billOfLading != "")'>
                <ns7:BillOfLAdding>
                  <xsl:value-of select="ns0:billOfLading"/>
                </ns7:BillOfLAdding>
              </xsl:if>
              <xsl:if test='ns0:packingSlip and (ns0:packingSlip != "")'>
                <ns7:Packing>
                  <xsl:value-of select="ns0:packingSlip"/>
                </ns7:Packing>
              </xsl:if>
            </ns7:BasicReceipt>
            <ns7:OperatingUnit>
              <xsl:value-of select="ns0:hrOperatingUnits/ns0:name"/>
            </ns7:OperatingUnit>
            <xsl:if test='ns0:comments and (ns0:comments != "")'>
              <ns7:Comments>
                <xsl:value-of select="ns0:comments"/>
              </ns7:Comments>
            </xsl:if>
            <ns7:Creationdate>
              <xsl:value-of select="ns0:creationDate"/>
            </ns7:Creationdate>
            <ns7:Employeename>
              <xsl:value-of select="ns0:perPeopleX/ns0:fullName"/>
            </ns7:Employeename>
            <xsl:if test='ns0:expectedReceiptDate and (ns0:expectedReceiptDate != "")'>
              <ns7:Expectedreceiptdate>
                <xsl:value-of select="ns0:expectedReceiptDate"/>
              </ns7:Expectedreceiptdate>
            </xsl:if>
            <xsl:if test='ns0:freightAmount and (ns0:freightAmount != "")'>
              <ns7:Freightamount>
                <xsl:value-of select="ns0:freightAmount"/>
              </ns7:Freightamount>
            </xsl:if>
            <xsl:if test='ns0:freightBillNumber and (ns0:freightBillNumber != "")'>
              <ns7:Freightbillnumber>
                <xsl:value-of select="ns0:freightBillNumber"/>
              </ns7:Freightbillnumber>
            </xsl:if>
            <xsl:if test='ns0:freightCarrierCode and (ns0:freightCarrierCode != "")'>
              <ns7:Freightcarriercode>
                <xsl:value-of select="ns0:freightCarrierCode"/>
              </ns7:Freightcarriercode>
            </xsl:if>
            <xsl:if test='ns0:freightTerms and (ns0:freightTerms != "")'>
              <ns7:Freightterms>
                <xsl:value-of select="ns0:freightTerms"/>
              </ns7:Freightterms>
            </xsl:if>
            <ns7:Lastupdatedate>
              <xsl:value-of select="ns0:lastUpdateDate"/>
            </ns7:Lastupdatedate>
            <ns7:Orgid>
              <xsl:value-of select="ns0:hrOperatingUnits/ns0:organizationId"/>
            </ns7:Orgid>
            <xsl:if test='ns0:shippedDate and (ns0:shippedDate != "")'>
              <ns7:Shippeddate>
                <xsl:value-of select="ns0:shippedDate"/>
              </ns7:Shippeddate>
            </xsl:if>
            <xsl:if test='ns0:asnStatus and (ns0:asnStatus != "")'>
              <ns7:Asnstatus>
                <xsl:value-of select="ns0:asnStatus"/>
              </ns7:Asnstatus>
            </xsl:if>
              <ns7:Asntype>
                <xsl:value-of select="ns0:asnType"/>
              </ns7:Asntype>
            <xsl:if test='ns0:waybillAirbillNum and (ns0:waybillAirbillNum != "")'>
              <ns7:Waybillairbillnum>
                <xsl:value-of select="ns0:waybillAirbillNum"/>
              </ns7:Waybillairbillnum>
            </xsl:if>
            <ns7:HeaderDFF>
              <xsl:if test='ns0:attributeCategory and (ns0:attributeCategory != "")'>
                <ns15:AttributeCategory>
                  <xsl:if test="ns0:attributeCategory/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attributeCategory/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attributeCategory"/>
                </ns15:AttributeCategory>
              </xsl:if>
              <xsl:if test='ns0:attribute1 and (ns0:attribute1 != "")'>
                <ns15:Attribute1>
                  <xsl:if test="ns0:attribute1/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute1/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute1"/>
                </ns15:Attribute1>
              </xsl:if>
              <xsl:if test='ns0:attribute2 and (ns0:attribute2 != "")'>
                <ns15:Attribute2>
                  <xsl:if test="ns0:attribute2/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute2/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute2"/>
                </ns15:Attribute2>
              </xsl:if>
              <xsl:if test='ns0:attribute3 and (ns0:attribute3 != "")'>
                <ns15:Attribute3>
                  <xsl:if test="ns0:attribute3/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute3/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute3"/>
                </ns15:Attribute3>
              </xsl:if>
              <xsl:if test='ns0:attribute4 and (ns0:attribute4 != "")'>
                <ns15:Attribute4>
                  <xsl:if test="ns0:attribute4/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute4/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute4"/>
                </ns15:Attribute4>
              </xsl:if>
              <xsl:if test='ns0:attribute5 and (ns0:attribute5 != "")'>
                <ns15:Attribute5>
                  <xsl:if test="ns0:attribute5/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute5/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute5"/>
                </ns15:Attribute5>
              </xsl:if>
              <xsl:if test='ns0:attribute6 and (ns0:attribute6 != "")'>
                <ns15:Attribute6>
                  <xsl:if test="ns0:attribute6/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute6/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute6"/>
                </ns15:Attribute6>
              </xsl:if>
              <xsl:if test='ns0:attribute7 and (ns0:attribute7 != "")'>
                <ns15:Attribute7>
                  <xsl:if test="ns0:attribute7/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute7/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute7"/>
                </ns15:Attribute7>
              </xsl:if>
              <xsl:if test='ns0:attribute8 and (ns0:attribute8 != "")'>
                <ns15:Attribute8>
                  <xsl:if test="ns0:attribute8/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute8/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute8"/>
                </ns15:Attribute8>
              </xsl:if>
              <xsl:if test='ns0:attribute9 and (ns0:attribute9 != "")'>
                <ns15:Attribute9>
                  <xsl:if test="ns0:attribute9/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute9/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute9"/>
                </ns15:Attribute9>
              </xsl:if>
              <xsl:if test='ns0:attribute10 and (ns0:attribute10 != "")'>
                <ns15:Attribute10>
                  <xsl:if test="ns0:attribute10/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute10/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute10"/>
                </ns15:Attribute10>
              </xsl:if>
              <xsl:if test='ns0:attribute11 and (ns0:attribute11 != "")'>
                <ns15:Attribute11>
                  <xsl:if test="ns0:attribute11/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute11/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute11"/>
                </ns15:Attribute11>
              </xsl:if>
              <xsl:if test='ns0:attribute12 and (ns0:attribute12 != "")'>
                <ns15:Attribute12>
                  <xsl:if test="ns0:attribute12/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute12/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute12"/>
                </ns15:Attribute12>
              </xsl:if>
              <xsl:if test='ns0:attribute13 and (ns0:attribute13 != "")'>
                <ns15:Attribute13>
                  <xsl:if test="ns0:attribute13/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute13/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute13"/>
                </ns15:Attribute13>
              </xsl:if>
              <xsl:if test='ns0:attribute14 and (ns0:attribute14 != "")'>
                <ns15:Attribute14>
                  <xsl:if test="ns0:attribute14/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute14/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute14"/>
                </ns15:Attribute14>
              </xsl:if>
              <xsl:if test='ns0:attribute15 and (ns0:attribute15 != "")'>
                <ns15:Attribute15>
                  <xsl:if test="ns0:attribute15/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:attribute15/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:attribute15"/>
                </ns15:Attribute15>
              </xsl:if>
            </ns7:HeaderDFF>
            <ns7:ListOfBasicReceiptLines>
              <xsl:for-each select="ns0:rcvShipmentLinesCollection/ns0:RcvShipmentLines">
                <ns7:ReceiptLine>
                  <ns7:BasicReceiptLine>
                    <ns7:Identfier>
                      <xsl:value-of select="ns0:shipmentLineId"/>
                    </ns7:Identfier>
                    <ns7:HeaderIdentifier>
                      <xsl:value-of select="../../ns0:shipmentHeaderId"/>
                    </ns7:HeaderIdentifier>
                    <xsl:if test='ns0:quantityShipped and (ns0:quantityShipped != "")'>
                      <ns7:QuantityShipped>
                        <xsl:value-of select="ns0:quantityShipped"/>
                      </ns7:QuantityShipped>
                    </xsl:if>
                    <xsl:if test='ns0:quantityReceived and (ns0:quantityReceived != "")'>
                      <ns7:QuantityReceived>
                        <xsl:value-of select="ns0:quantityReceived"/>
                      </ns7:QuantityReceived>
                    </xsl:if>
                    <ns7:Uom>
                      <xsl:if test='ns0:unitOfMeasure and (ns0:unitOfMeasure != "")'>
                        <ns6:Code>
                          <xsl:if test="ns0:unitOfMeasure/@xsi:nil">
                            <xsl:attribute name="xsi:nil">
                              <xsl:value-of select="ns0:unitOfMeasure/@xsi:nil"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:value-of select="ns0:unitOfMeasure"/>
                        </ns6:Code>
                      </xsl:if>
                    </ns7:Uom>
                  </ns7:BasicReceiptLine>
                  <ns7:BasicItem>
                    <xsl:if test='ns0:mtlSystemItems/ns0:inventoryItemId and (ns0:mtlSystemItems/ns0:inventoryItemId != "")'>
                      <ns13:Identifier>
                        <xsl:value-of select="ns0:mtlSystemItems/ns0:inventoryItemId"/>
                      </ns13:Identifier>
                    </xsl:if>
                    <xsl:if test='ns0:mtlSystemItems/ns0:segment1 and (ns0:mtlSystemItems/ns0:segment1 != "")'>
                      <ns13:Item>
                        <xsl:value-of select="ns0:mtlSystemItems/ns0:segment1"/>
                      </ns13:Item>
                    </xsl:if>
                    <xsl:if test='ns0:itemDescription and (ns0:itemDescription != "")'>
                      <ns13:Description>
                        <xsl:value-of select="ns0:itemDescription"/>
                      </ns13:Description>
                    </xsl:if>
                  </ns7:BasicItem>
                  <ns7:BasicPurchaseOrder>
                    <ns18:POIndentfierID>
                      <xsl:value-of select="ns0:poHeadersAll/ns0:poHeaderId"/>
                    </ns18:POIndentfierID>
                    <ns18:PurchaseOrderNumber>
                      <xsl:value-of select="ns0:poHeadersAll/ns0:segment1"/>
                    </ns18:PurchaseOrderNumber>
                    <ns18:PurchaseOrderDate>
                      <xsl:value-of select="ns0:poHeadersAll/ns0:creationDate"/>
                    </ns18:PurchaseOrderDate>
                  </ns7:BasicPurchaseOrder>
                  <ns7:BasicPurchaseOrderLine>
                    <ns18:POIndentfierID>
                      <xsl:value-of select="ns0:poLinesAll/ns0:poLineId"/>
                    </ns18:POIndentfierID>
                    <ns18:PurchaseOrderNumber>
                      <xsl:value-of select="ns0:poLinesAll/ns0:lineNum"/>
                    </ns18:PurchaseOrderNumber>
                    <ns18:PurchaseOrderDate>
                      <xsl:value-of select="ns0:poLinesAll/ns0:creationDate"/>
                    </ns18:PurchaseOrderDate>
                  </ns7:BasicPurchaseOrderLine>
                  <xsl:if test='ns0:amountShipped and (ns0:amountShipped != "")'>
                    <ns7:AmountShipped>
                      <xsl:if test='ns0:amountShipped and (ns0:amountShipped != "")'>
                        <ns10:Value>
                          <xsl:if test="ns0:amountShipped/@xsi:nil">
                            <xsl:attribute name="xsi:nil">
                              <xsl:value-of select="ns0:amountShipped/@xsi:nil"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:value-of select="ns0:amountShipped"/>
                        </ns10:Value>
                      </xsl:if>
                    </ns7:AmountShipped>
                  </xsl:if>
                  <xsl:if test='ns0:packingSlip and (ns0:packingSlip != "")'>
                      <ns7:PackingSlip>
                        <xsl:value-of select="ns0:packingSlip"/>
                      </ns7:PackingSlip>
                    </xsl:if>
                    <xsl:if test='ns0:truckNum and (ns0:truckNum != "")'>
                      <ns7:TruckNum>
                        <xsl:value-of select="ns0:truckNum"/>
                      </ns7:TruckNum>
                    </xsl:if>
                    <ns7:DFF>
                    <xsl:if test='ns0:attributeCategory and (ns0:attributeCategory != "")'>
                      <ns15:AttributeCategory>
                        <xsl:if test="ns0:attributeCategory/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attributeCategory/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attributeCategory"/>
                      </ns15:AttributeCategory>
                    </xsl:if>
                    <xsl:if test='ns0:attribute1 and (ns0:attribute1 != "")'>
                      <ns15:Attribute1>
                        <xsl:if test="ns0:attribute1/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute1/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute1"/>
                      </ns15:Attribute1>
                    </xsl:if>
                    <xsl:if test='ns0:attribute2 and (ns0:attribute2 != "")'>
                      <ns15:Attribute2>
                        <xsl:if test="ns0:attribute2/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute2/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute2"/>
                      </ns15:Attribute2>
                    </xsl:if>
                    <xsl:if test='ns0:attribute3 and (ns0:attribute3 != "")'>
                      <ns15:Attribute3>
                        <xsl:if test="ns0:attribute3/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute3/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute3"/>
                      </ns15:Attribute3>
                    </xsl:if>
                    <xsl:if test='ns0:attribute4 and (ns0:attribute4 != "")'>
                      <ns15:Attribute4>
                        <xsl:if test="ns0:attribute4/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute4/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute4"/>
                      </ns15:Attribute4>
                    </xsl:if>
                    <xsl:if test='ns0:attribute5 and (ns0:attribute5 != "")'>
                      <ns15:Attribute5>
                        <xsl:if test="ns0:attribute5/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute5/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute5"/>
                      </ns15:Attribute5>
                    </xsl:if>
                    <xsl:if test='ns0:attribute6 and (ns0:attribute6 != "")'>
                      <ns15:Attribute6>
                        <xsl:if test="ns0:attribute6/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute6/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute6"/>
                      </ns15:Attribute6>
                    </xsl:if>
                    <xsl:if test='ns0:attribute7 and (ns0:attribute7 != "")'>
                      <ns15:Attribute7>
                        <xsl:if test="ns0:attribute7/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute7/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute7"/>
                      </ns15:Attribute7>
                    </xsl:if>
                    <xsl:if test='ns0:attribute8 and (ns0:attribute8 != "")'>
                      <ns15:Attribute8>
                        <xsl:if test="ns0:attribute8/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute8/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute8"/>
                      </ns15:Attribute8>
                    </xsl:if>
                    <xsl:if test='ns0:attribute9 and (ns0:attribute8 != "")'>
                      <ns15:Attribute9>
                        <xsl:if test="ns0:attribute9/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute9/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute9"/>
                      </ns15:Attribute9>
                    </xsl:if>
                    <xsl:if test='ns0:attribute10 and (ns0:attribute10 != "")'>
                      <ns15:Attribute10>
                        <xsl:if test="ns0:attribute10/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute10/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute10"/>
                      </ns15:Attribute10>
                    </xsl:if>
                    <xsl:if test='ns0:attribute11 and (ns0:attribute11 != "")'>
                      <ns15:Attribute11>
                        <xsl:if test="ns0:attribute11/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute11/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute11"/>
                      </ns15:Attribute11>
                    </xsl:if>
                    <xsl:if test='ns0:attribute12 and (ns0:attribute12 != "")'>
                      <ns15:Attribute12>
                        <xsl:if test="ns0:attribute12/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute12/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute12"/>
                      </ns15:Attribute12>
                    </xsl:if>
                    <xsl:if test='ns0:attribute13 and (ns0:attribute13 != "")'>
                      <ns15:Attribute13>
                        <xsl:if test="ns0:attribute13/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute13/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute13"/>
                      </ns15:Attribute13>
                    </xsl:if>
                    <xsl:if test='ns0:attribute14 and (ns0:attribute14 != "")'>
                      <ns15:Attribute14>
                        <xsl:if test="ns0:attribute14/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute14/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute14"/>
                      </ns15:Attribute14>
                    </xsl:if>
                    <xsl:if test='ns0:attribute15 and (ns0:attribute15 != "")'>
                      <ns15:Attribute15>
                        <xsl:if test="ns0:attribute15/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:attribute15/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:attribute15"/>
                      </ns15:Attribute15>
                    </xsl:if>
                  </ns7:DFF>
                </ns7:ReceiptLine>
              </xsl:for-each>
            </ns7:ListOfBasicReceiptLines>
            <ns7:ListOfTransactions>
              <xsl:for-each select="ns0:rcvShipmentLinesCollection/ns0:RcvShipmentLines/ns0:rcvTransactionsCollection/ns0:RcvTransactions">
                <ns7:Transaction>
                  <ns7:BasicTransaction>
                    <ns7:Identifier>
                      <xsl:value-of select="ns0:transactionId"/>
                    </ns7:Identifier>
                    <ns7:TransactionType>
                      <xsl:value-of select="ns0:transactionType"/>
                    </ns7:TransactionType>
                    <ns7:TransactionDate>
                      <xsl:value-of select="ns0:transactionDate"/>
                    </ns7:TransactionDate>
                    <ns7:Quantity>
                      <xsl:value-of select="ns0:quantity"/>
                    </ns7:Quantity>
                    <ns7:Uom>
                      <ns6:Code>
                        <xsl:value-of select="ns0:unitOfMeasure"/>
                      </ns6:Code>
                    </ns7:Uom>
                    <ns7:ShipmentHeaderId>
                      <xsl:value-of select="ns0:shipmentHeaderId"/>
                    </ns7:ShipmentHeaderId>
                    <ns7:ShipmentLineId>
                      <xsl:value-of select="../../ns0:shipmentLineId"/>
                    </ns7:ShipmentLineId>
                  </ns7:BasicTransaction>
                  <xsl:if test="ns0:amount">
                    <ns7:Amount>
                      <ns10:Value>
                        <xsl:value-of select="ns0:amount"/>
                      </ns10:Value>
                    </ns7:Amount>
                  </xsl:if>
                  <xsl:if test='ns0:amountBilled and (ns0:amountBilled != "")'>
                    <ns7:AmountBilled>
                      <ns10:Value>
                        <xsl:value-of select="ns0:amountBilled"/>
                      </ns10:Value>
                    </ns7:AmountBilled>
                  </xsl:if>
                  <xsl:if test='ns0:parentTransactionId and (ns0:parentTransactionId != "")'>
                    <ns7:ParentTransactionId>
                      <xsl:value-of select="ns0:parentTransactionId"/>
                    </ns7:ParentTransactionId>
                  </xsl:if>
                  <ns7:BasicPurchaseOrder>
                    <ns18:POIndentfierID>
                      <xsl:value-of select="../../ns0:poHeadersAll/ns0:poHeaderId"/>
                    </ns18:POIndentfierID>
                    <ns18:PurchaseOrderNumber>
                      <xsl:value-of select="../../ns0:poHeadersAll/ns0:segment1"/>
                    </ns18:PurchaseOrderNumber>
                    <ns18:PurchaseOrderDate>
                      <xsl:value-of select="../../ns0:poHeadersAll/ns0:creationDate"/>
                    </ns18:PurchaseOrderDate>
                  </ns7:BasicPurchaseOrder>
                  <ns7:BasicPurchaseOrderLine>
                    <ns18:POIndentfierID>
                      <xsl:value-of select="../../ns0:poLinesAll/ns0:poLineId"/>
                    </ns18:POIndentfierID>
                    <ns18:PurchaseOrderNumber>
                      <xsl:value-of select="../../ns0:poLinesAll/ns0:lineNum"/>
                    </ns18:PurchaseOrderNumber>
                    <ns18:PurchaseOrderDate>
                      <xsl:value-of select="../../ns0:poLinesAll/ns0:creationDate"/>
                    </ns18:PurchaseOrderDate>
                  </ns7:BasicPurchaseOrderLine>
                  
                  <!-- SysAid Ticket# 45227 15-Nov-2016 by NS Start -->
                  <xsl:if test='ns0:destinationTypeCode and (ns0:destinationTypeCode != "")'>
                    <ns7:DestinationTypeCode>
                      <xsl:value-of select="ns0:destinationTypeCode"/>
                    </ns7:DestinationTypeCode>
                  </xsl:if>
                  <!-- SysAid Ticket# 45227 15-Nov-2016 by NS End -->
                  
                  <xsl:if test='ns0:poUnitPrice and (ns0:poUnitPrice != "")'>
                    <ns7:PoUnitPrice>
                      <ns10:Value>
                        <xsl:value-of select="ns0:poUnitPrice"/>
                      </ns10:Value>
                      <ns10:CurrencyCode>
                        <xsl:value-of select="ns0:currencyCode"/>
                      </ns10:CurrencyCode>
                    </ns7:PoUnitPrice>
                  </xsl:if>
                  <xsl:if test='ns0:quantityBilled and (ns0:quantityBilled != "")'>
                    <ns7:QuantityBilled>
                      <xsl:value-of select="ns0:quantityBilled"/>
                    </ns7:QuantityBilled>
                  </xsl:if>
                  <xsl:if test='ns0:sourceDocQuantity and ("" != ../../ns0:poLinesAll/ns0:quantity)'>
                    <ns7:SourceDocQuantity>
                      <xsl:value-of select="../../ns0:poLinesAll/ns0:quantity"/>
                    </ns7:SourceDocQuantity>
                  </xsl:if>
                  <xsl:if test='ns0:sourceDocUnitOfMeasure and ("" != ../../ns0:poLinesAll/ns0:unitMeasLookupCode)'>
                    <ns7:SourceDocUnitOfMeasure>
                      <ns6:Code>
                        <xsl:value-of select="../../ns0:poLinesAll/ns0:unitMeasLookupCode"/>
                      </ns6:Code>
                    </ns7:SourceDocUnitOfMeasure>
                  </xsl:if>
                  <xsl:if test='ns0:sourceTransactionNum and (ns0:sourceTransactionNum != "")'>
                    <ns7:SourceTransactionNum>
                        <xsl:value-of select="ns0:sourceTransactionNum"/>
                    </ns7:SourceTransactionNum>
                  </xsl:if>
                  <xsl:if test='ns0:userEnteredFlag and (ns0:userEnteredFlag != "")'>
                    <ns7:UserEnteredFlag>
                      <xsl:value-of select="ns0:userEnteredFlag"/>
                    </ns7:UserEnteredFlag>
                  </xsl:if>
                  <ns7:VendorItemNum>
                    <xsl:value-of select="../../ns0:poLinesAll/ns0:attribute1"/>
                  </ns7:VendorItemNum>
                </ns7:Transaction>
              </xsl:for-each>
            </ns7:ListOfTransactions>
          </ns7:Receipt>
        </xsl:for-each>
      </ns1:ListOfReceipts>
    </ns1:QueryReceiptResponseMessage>
  </xsl:template>
</xsl:stylesheet>
