<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns1="http://xmlns.eia.com/CommonLogging"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/OA_CreateReceiptEBS"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_DeriveReceiptColumns"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/apps/WI_Application/NUC_EBizPOReceipt_ABS/OA_CreateReceiptEBS"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NUC_EBizPOReceipt_ABS/DB_DeriveReceiptColumns"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../OA_CreateReceiptEBS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="RcvHeadersInterfaceCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/OA_CreateReceiptEBS"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/Infrastracture/wsdls/V1.0/CommonLogging.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Input" namespace="http://xmlns.eia.com/CommonLogging"/>
        <oracle-xsl-mapper:param name="Invoke_CommonLogging_process_InputVariable.CommonLogging"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../DB_DeriveReceiptColumns.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_DeriveReceiptColumns"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JAN 14 12:42:02 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="Invoke_CommonLogging_process_InputVariable.CommonLogging"/>
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_TRX_ID>
        <xsl:value-of select="$Invoke_CommonLogging_process_InputVariable.CommonLogging/ns1:Input/ns1:TransactionId"/>
      </tns:P_TRX_ID>
      <tns:P_I_DERIVE>
        <tns:PO_NUMBER>
          <xsl:value-of select="/ns0:RcvHeadersInterfaceCollection/ns0:RcvHeadersInterface/ns0:rcvTransactionsInterfaceCollection/ns0:RcvTransactionsInterface[1]/ns0:documentNum"/>
        </tns:PO_NUMBER>
        <tns:PO_LINE>
          <xsl:for-each select="/ns0:RcvHeadersInterfaceCollection/ns0:RcvHeadersInterface/ns0:rcvTransactionsInterfaceCollection/ns0:RcvTransactionsInterface">
            <tns:PO_LINE_ITEM>
              <tns:PO_NUMBER>
                <xsl:value-of select="ns0:documentNum"/>
              </tns:PO_NUMBER>
              <tns:PO_LINE_NUM>
                <xsl:value-of select="ns0:documentLineNum"/>
              </tns:PO_LINE_NUM>
            </tns:PO_LINE_ITEM>
          </xsl:for-each>
        </tns:PO_LINE>
      </tns:P_I_DERIVE>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
