<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QMOS_TAB"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.eia.com/CommonLogging"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_QMOS_PROD"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSTX_HeatCastBatch_QMOS_EBiz_ABF/DB_QMOS_TAB"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSTX_HeatCastBatch_QMOS_EBiz_ABF/DB_Proc_QMOS_PROD"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSTX_HeatCastBatch_QMOS_EBiz_ABF/DB_Proc_QMOS_PROD">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/Infrastracture/wsdls/V1.0/CommonLogging.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Input" namespace="http://xmlns.eia.com/CommonLogging"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_QMOS_TAB.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiProdConfirmHeaderCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_QMOS_TAB"/>
        <oracle-xsl-mapper:param name="g_Invoke_DB_QMOS_TAB_OutputVariable.ApiProdConfirmHeaderCollection"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Proc_QMOS_PROD.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_QMOS_PROD"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON MAR 20 05:55:18 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_Invoke_DB_QMOS_TAB_OutputVariable.ApiProdConfirmHeaderCollection"/>
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_IN_TRX_ID>
        <xsl:value-of select="/ns0:Input/ns0:TransactionId"/>
      </tns:P_IN_TRX_ID>
      <tns:P_IN_TRX_NAME>
        <xsl:value-of select="/ns0:Input/ns0:TransactionName"/>
      </tns:P_IN_TRX_NAME>
      <tns:P_IN_SRC_SYSTEM>
        <xsl:value-of select="/ns0:Input/ns0:SourceSystem"/>
      </tns:P_IN_SRC_SYSTEM>
      <tns:P_IN_INIT_PARAMS>
        <tns:USER_NAME>SOAUSER</tns:USER_NAME>
        <tns:RESPONSIBILITY_NAME>NUC Production Interface User</tns:RESPONSIBILITY_NAME>
        <tns:ORG_ID>361</tns:ORG_ID>
      </tns:P_IN_INIT_PARAMS>
      <tns:P_TRX_TAB>
        <xsl:for-each select="$g_Invoke_DB_QMOS_TAB_OutputVariable.ApiProdConfirmHeaderCollection/ns1:ApiProdConfirmHeaderCollection/ns1:ApiProdConfirmHeader">
          <tns:P_TRX_TAB_ITEM>
            <tns:ID>
              <xsl:value-of select="ns1:id"/>
            </tns:ID>
            <tns:WOR_ORDER_NO>
              <xsl:value-of select="ns1:worOrderNo"/>
            </tns:WOR_ORDER_NO>
            <tns:HEAT_NO>
              <xsl:value-of select="ns1:heatNo"/>
            </tns:HEAT_NO>
            <tns:PROD_CODE>
              <xsl:value-of select="ns1:prodCode"/>
            </tns:PROD_CODE>
            <tns:PCD_PROD_TYPE>
              <xsl:value-of select="ns1:pcdProdType"/>
            </tns:PCD_PROD_TYPE>
            <tns:START_DATE>
              <xsl:value-of select="ns1:startDate"/>
            </tns:START_DATE>
            <tns:END_DATE>
              <xsl:value-of select="ns1:endDate"/>
            </tns:END_DATE>
            <tns:CREATE_USER>
              <xsl:value-of select="ns1:createUser"/>
            </tns:CREATE_USER>
            <tns:CREATE_DATE>
              <xsl:value-of select="ns1:createDate"/>
            </tns:CREATE_DATE>
            <tns:PROCESSED>
              <xsl:value-of select="ns1:processed"/>
            </tns:PROCESSED>
            <tns:PROCESS_DATE>
              <xsl:value-of select="ns1:processDate"/>
            </tns:PROCESS_DATE>
            <tns:ERROR_MESSAGE>
              <xsl:value-of select="ns1:errorMessage"/>
            </tns:ERROR_MESSAGE>
            <tns:PROD_CONF_MTL_DETAIL>
              <xsl:for-each select="ns1:apiProdConfirmMaterialCollection/ns1:ApiProdConfirmMaterial">
                <tns:PROD_CONF_MTL_DETAIL_ITEM>
                  <tns:ID>
                    <xsl:value-of select="ns1:id"/>
                  </tns:ID>
                  <tns:ID_HEADER>
                    <xsl:value-of select="../../ns1:id"/>
                  </tns:ID_HEADER>
                  <tns:WOR_ORDER_NO>
                    <xsl:value-of select="ns1:worOrderNo"/>
                  </tns:WOR_ORDER_NO>
                  <tns:WORK_CENTER_ID>
                    <xsl:value-of select="ns1:workCenterId"/>
                  </tns:WORK_CENTER_ID>
                  <tns:ERP_MAT_ID>
                    <xsl:value-of select="ns1:erpMatId"/>
                  </tns:ERP_MAT_ID>
                  <tns:ERP_CAST_LOT>
                    <xsl:value-of select="ns1:erpCastLot"/>
                  </tns:ERP_CAST_LOT>
                  <tns:TRANS_TYPE>
                    <xsl:value-of select="ns1:transType"/>
                  </tns:TRANS_TYPE>
                  <tns:MAT_PILE>
                    <xsl:value-of select="ns1:matPile"/>
                  </tns:MAT_PILE>
                  <tns:QTY>
                    <xsl:value-of select="ns1:qty"/>
                  </tns:QTY>
                  <tns:ADJ_QTY>
                    <xsl:value-of select="ns1:adjQty"/>
                  </tns:ADJ_QTY>
                  <tns:UOM>
                    <xsl:value-of select="ns1:uom"/>
                  </tns:UOM>
                  <tns:ERP_MAT_DESC>
                    <xsl:value-of select="ns1:erpMatDesc"/>
                  </tns:ERP_MAT_DESC>
                  <tns:MTG_GROUP_ID>
                    <xsl:value-of select="ns1:mtgGroupId"/>
                  </tns:MTG_GROUP_ID>
                  <tns:POUR_BACK_HEAT_NO>
                    <xsl:value-of select="ns1:pourBackHeatNo"/>
                  </tns:POUR_BACK_HEAT_NO>
                  <tns:POUR_BACK_REASON>
                    <xsl:value-of select="ns1:pourBackReason"/>
                  </tns:POUR_BACK_REASON>
                  <tns:CREATE_USER>
                    <xsl:value-of select="ns1:createUser"/>
                  </tns:CREATE_USER>
                  <tns:PROCESSED>
                    <xsl:value-of select="ns1:processed"/>
                  </tns:PROCESSED>
                  <tns:PROCESS_DATE>
                    <xsl:value-of select="ns1:processDate"/>
                  </tns:PROCESS_DATE>
                  <tns:ERROR_MESSAGE>
                    <xsl:value-of select="ns1:errorMessage"/>
                  </tns:ERROR_MESSAGE>
                </tns:PROD_CONF_MTL_DETAIL_ITEM>
              </xsl:for-each>
            </tns:PROD_CONF_MTL_DETAIL>
          </tns:P_TRX_TAB_ITEM>
        </xsl:for-each>
      </tns:P_TRX_TAB>
      <tns:P_IN_ORGN_CODE>110</tns:P_IN_ORGN_CODE>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
