<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Bundle_Trx"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Process_Bundle_Trx_EBS"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSUT_Bundle_EBSMTLTrxImp_ABF/DB_Process_Bundle_Trx_EBS"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSUT_Bundle_EBSMTLTrxImp_ABF/DB_Update_Bundle_Trx">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Process_Bundle_Trx_EBS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Process_Bundle_Trx_EBS"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Update_Bundle_Trx.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiBundleTransCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Bundle_Trx"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE APR 11 05:52:34 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ApiBundleTransCollection>
      <xsl:for-each select="/ns0:OutputParameters/ns0:P_RESULT_TAB/ns0:P_RESULT_TAB_ITEM">
        <tns:ApiBundleTrans>
          <tns:id>
            <xsl:value-of select="ns0:TRX_ID"/>
          </tns:id>
          <xsl:choose>
            <xsl:when test="ns0:RESULT_CODE = 'S'">
              <tns:processed>C</tns:processed>
            </xsl:when>
            <xsl:otherwise>
              <tns:processed>E</tns:processed>
            </xsl:otherwise>
          </xsl:choose>
          <tns:processDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:processDate>
          <tns:errorMessage>
            <xsl:value-of select="ns0:RESULT_MESSAGE"/>
          </tns:errorMessage>
        </tns:ApiBundleTrans>
      </xsl:for-each>
    </tns:ApiBundleTransCollection>
  </xsl:template>
</xsl:stylesheet>
