<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Get_Bundle_Trx"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Bundle_Trx"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:client="http://nucor.eia.com/Bundle_EBSMTLTrxImp"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSUT_Bundle_EBSMTLTrxImp_ABF/DB_Get_Bundle_Trx"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSUT_Bundle_EBSMTLTrxImp_ABF/DB_Update_Bundle_Trx">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Get_Bundle_Trx.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiBundleTransCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Get_Bundle_Trx"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Bundle_EBSMTLTrxImp.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="tmp_NVPair"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Update_Bundle_Trx.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiBundleTransCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Bundle_Trx"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU AUG 31 12:18:55 PDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="tmp_NVPair"/>
  <xsl:template match="/">
    <tns:ApiBundleTransCollection>
      <xsl:for-each select="/ns0:ApiBundleTransCollection/ns0:ApiBundleTrans">
        <tns:ApiBundleTrans>
          <tns:id>
            <xsl:value-of select="ns0:id"/>
          </tns:id>
          <tns:processed>E</tns:processed>
          <tns:processDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </tns:processDate>
          <tns:errorMessage>
            <xsl:value-of select="substring ($tmp_NVPair/ns1:parameters/ns1:item/ns1:value, 1, 2000 )"/>
          </tns:errorMessage>
        </tns:ApiBundleTrans>
      </xsl:for-each>
    </tns:ApiBundleTransCollection>
  </xsl:template>
</xsl:stylesheet>
