<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="MillScale_EBizSFT"
     targetNamespace="http://xmlns.eia.com/Implementation/ABF/NUC_MillScales_EBizSFT_ABF/MillScale_EBizSFT"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.eia.com/Implementation/ABF/NUC_MillScales_EBizSFT_ABF/MillScale_EBizSFT"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="MillScale_EBizSFT">
        <plnk:role name="execute" portType="tns:execute"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.eia.com/Implementation/ABF/NUC_MillScales_EBizSFT_ABF/MillScale_EBizSFT"
         location="MillScale_EBizSFT.wsdl"/>
</wsdl:definitions>
