<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns1="http://xmlns.eia.com/CommonLogging"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_GetQualitySpecDetails"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAM/1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 tns xp20 oraxsl mhdr oraext dvm xref utl socket"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NUC_EBizQualitySpec_ABS/DB_Proc_GetQualitySpecDetails"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://oracle.com/sca/soapservice/Manish/NUC_EBizQualitySpec_ABS/QualitySpecABS"
                xmlns:ns5="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Proc_GetQualitySpecDetails.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_GetQualitySpecDetails"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/Infrastracture/wsdls/V1.0/CommonLogging.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Input" namespace="http://xmlns.eia.com/CommonLogging"/>
        <oracle-xsl-mapper:param name="g_Invoke_CommonLogging_InputVariable.CommonLogging"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/QualitySpecABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryQualitySpecsAddRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU NOV 12 03:21:17 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_Invoke_CommonLogging_InputVariable.CommonLogging"/>
  <xsl:template match="/">
    <tns:QueryQualitySpecsAddRs>
      <ns9:HeaderRs>
        <ns9:TransactionID>
          <xsl:value-of select="$g_Invoke_CommonLogging_InputVariable.CommonLogging/ns1:Input/ns1:TransactionId"/>
        </ns9:TransactionID>
        <ns9:RequestDetails>
          <ns9:TransactionRequestID>
            <xsl:value-of select="$g_Invoke_CommonLogging_InputVariable.CommonLogging/ns1:Input/ns1:TransactionId"/>
          </ns9:TransactionRequestID>
          <ns9:Language>EN</ns9:Language>
          <!-- <ns9:ComponentID>
            <xsl:value-of select="$g_Invoke_CommonLogging_InputVariable.CommonLogging/ns1:Input/ns1:ComponentId"/>
          </ns9:ComponentID>
          <ns9:ServiceName/>
          <ns9:TransactionName>
            <xsl:value-of select="$g_Invoke_CommonLogging_InputVariable.CommonLogging/ns1:Input/ns1:TransactionName"/>
          </ns9:TransactionName>
          <ns9:Source>
            <xsl:value-of select="$g_Invoke_CommonLogging_InputVariable.CommonLogging/ns1:Input/ns1:SourceSystem"/>
          </ns9:Source>
          <ns9:Target>
            <xsl:value-of select="$g_Invoke_CommonLogging_InputVariable.CommonLogging/ns1:Input/ns1:TargetSystem"/>
          </ns9:Target> -->
        </ns9:RequestDetails>
      </ns9:HeaderRs>
      <xsl:for-each select="">
        <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM">
          <ns5:QualitySpecsDetails>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_ID">
              <ns5:SPEC_ID>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_ID"/>
              </ns5:SPEC_ID>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_NAME">
              <ns5:SPEC_NAME>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_NAME"/>
              </ns5:SPEC_NAME>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_VERS">
              <ns5:SPEC_VERS>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_VERS"/>
              </ns5:SPEC_VERS>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_STATUS">
              <ns5:SPEC_STATUS>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_STATUS"/>
              </ns5:SPEC_STATUS>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:DESCRIPTION">
              <ns5:DESCRIPTION>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:DESCRIPTION"/>
              </ns5:DESCRIPTION>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_TYPE">
              <ns5:SPEC_TYPE>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:SPEC_TYPE"/>
              </ns5:SPEC_TYPE>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:OVERLAY_IND">
              <ns5:OVERLAY_IND>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:OVERLAY_IND"/>
              </ns5:OVERLAY_IND>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:BASE_SPEC">
              <ns5:BASE_SPEC>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:BASE_SPEC"/>
              </ns5:BASE_SPEC>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:BASE_SPEC_VERSION">
              <ns5:BASE_SPEC_VERSION>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:BASE_SPEC_VERSION"/>
              </ns5:BASE_SPEC_VERSION>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:INV_ITEM">
              <ns5:INV_ITEM>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:INV_ITEM"/>
              </ns5:INV_ITEM>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:GRADE">
              <ns5:GRADE>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:GRADE"/>
              </ns5:GRADE>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:OWNER_ORGANIZATION_CODE">
              <ns5:OWNER_ORGANIZATION_CODE>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:OWNER_ORGANIZATION_CODE"/>
              </ns5:OWNER_ORGANIZATION_CODE>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:OWNER_ORGANIZATION_NAME">
              <ns5:OWNER_ORGANIZATION_NAME>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:OWNER_ORGANIZATION_NAME"/>
              </ns5:OWNER_ORGANIZATION_NAME>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:OWNER_NAME">
              <ns5:OWNER_NAME>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:OWNER_NAME"/>
              </ns5:OWNER_NAME>
            </xsl:if>
            <!--
            <ns5:ATTRIBUTE>
              <ns5:ATTRIBUTECATEGORY>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE_CATEGORY"/>
              </ns5:ATTRIBUTECATEGORY>
              <ns5:ATTRIBUTE1>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE1"/>
              </ns5:ATTRIBUTE1>
              <ns5:ATTRIBUTE2>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE2"/>
              </ns5:ATTRIBUTE2>
              <ns5:ATTRIBUTE3>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE3"/>
              </ns5:ATTRIBUTE3>
              <ns5:ATTRIBUTE4>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE4"/>
              </ns5:ATTRIBUTE4>
              <ns5:ATTRIBUTE5>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE5"/>
              </ns5:ATTRIBUTE5>
              <ns5:ATTRIBUTE6>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE6"/>
              </ns5:ATTRIBUTE6>
              <ns5:ATTRIBUTE7>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE7"/>
              </ns5:ATTRIBUTE7>
              <ns5:ATTRIBUTE8>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE8"/>
              </ns5:ATTRIBUTE8>
              <ns5:ATTRIBUTE9>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE9"/>
              </ns5:ATTRIBUTE9>
              <ns5:ATTRIBUTE10>
                <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:ATTRIBUTE10"/>
              </ns5:ATTRIBUTE10>
            </ns5:ATTRIBUTE>
            -->
            <ns5:QUALITY_SPECS_TEST>
              <xsl:for-each select="">
                <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM">
                  <ns5:QUALITY_SPECS_TEST>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:SPEC_ID">
                      <ns5:SPEC_ID>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:SPEC_ID"/>
                      </ns5:SPEC_ID>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:SEQ">
                      <ns5:SEQ>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:SEQ"/>
                      </ns5:SEQ>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_NAME">
                      <ns5:TEST_NAME>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_NAME"/>
                      </ns5:TEST_NAME>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_CLASS">
                      <ns5:TEST_CLASS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_CLASS"/>
                      </ns5:TEST_CLASS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_METHOD">
                      <ns5:TEST_METHOD>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_METHOD"/>
                      </ns5:TEST_METHOD>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TARGET_VALUE">
                      <ns5:TARGET_VALUE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TARGET_VALUE"/>
                      </ns5:TARGET_VALUE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:MINIMUM_VALUE">
                      <ns5:MINIMUM_VALUE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:MINIMUM_VALUE"/>
                      </ns5:MINIMUM_VALUE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:MAXIMUM_VALUE">
                      <ns5:MAXIMUM_VALUE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:MAXIMUM_VALUE"/>
                      </ns5:MAXIMUM_VALUE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_QTY">
                      <ns5:TEST_QTY>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_QTY"/>
                      </ns5:TEST_QTY>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_QTY_UOM">
                      <ns5:TEST_QTY_UOM>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_QTY_UOM"/>
                      </ns5:TEST_QTY_UOM>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_REPLICATE">
                      <ns5:TEST_REPLICATE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_REPLICATE"/>
                      </ns5:TEST_REPLICATE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_PRIORITY">
                      <ns5:TEST_PRIORITY>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_PRIORITY"/>
                      </ns5:TEST_PRIORITY>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:OPTIONAL_IND">
                      <ns5:OPTIONAL_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:OPTIONAL_IND"/>
                      </ns5:OPTIONAL_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:RETEST_LOT_EXPIRY_IND">
                      <ns5:RETEST_LOT_EXPIRY_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:RETEST_LOT_EXPIRY_IND"/>
                      </ns5:RETEST_LOT_EXPIRY_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:OUT_OF_SPEC_ACTION">
                      <ns5:OUT_OF_SPEC_ACTION>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:OUT_OF_SPEC_ACTION"/>
                      </ns5:OUT_OF_SPEC_ACTION>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:CHECK_RESULT_INTERVAL">
                      <ns5:CHECK_RESULT_INTERVAL>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:CHECK_RESULT_INTERVAL"/>
                      </ns5:CHECK_RESULT_INTERVAL>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:BELOW_SPEC_MIN">
                      <ns5:BELOW_SPEC_MIN>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:BELOW_SPEC_MIN"/>
                      </ns5:BELOW_SPEC_MIN>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:BELOW_MIN_ACTION_CODE">
                      <ns5:BELOW_MIN_ACTION_CODE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:BELOW_MIN_ACTION_CODE"/>
                      </ns5:BELOW_MIN_ACTION_CODE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ABOVE_SPEC_MIN">
                      <ns5:ABOVE_SPEC_MIN>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ABOVE_SPEC_MIN"/>
                      </ns5:ABOVE_SPEC_MIN>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ABOVE_MIN_ACTION_CODE">
                      <ns5:ABOVE_MIN_ACTION_CODE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ABOVE_MIN_ACTION_CODE"/>
                      </ns5:ABOVE_MIN_ACTION_CODE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:BELOW_SPEC_MAX">
                      <ns5:BELOW_SPEC_MAX>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:BELOW_SPEC_MAX"/>
                      </ns5:BELOW_SPEC_MAX>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:BELOW_MAX_ACTION_CODE">
                      <ns5:BELOW_MAX_ACTION_CODE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:BELOW_MAX_ACTION_CODE"/>
                      </ns5:BELOW_MAX_ACTION_CODE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ABOVE_SPEC_MAX">
                      <ns5:ABOVE_SPEC_MAX>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ABOVE_SPEC_MAX"/>
                      </ns5:ABOVE_SPEC_MAX>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ABOVE_MAX_ACTION_CODE">
                      <ns5:ABOVE_MAX_ACTION_CODE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ABOVE_MAX_ACTION_CODE"/>
                      </ns5:ABOVE_MAX_ACTION_CODE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_DISPLAY">
                      <ns5:TEST_DISPLAY>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:TEST_DISPLAY"/>
                      </ns5:TEST_DISPLAY>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:PRINT_SPEC_IND">
                      <ns5:PRINT_SPEC_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:PRINT_SPEC_IND"/>
                      </ns5:PRINT_SPEC_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:PRINT_RESULT_IND">
                      <ns5:PRINT_RESULT_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:PRINT_RESULT_IND"/>
                      </ns5:PRINT_RESULT_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:DISPLAY_PRECISION">
                      <ns5:DISPLAY_PRECISION>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:DISPLAY_PRECISION"/>
                      </ns5:DISPLAY_PRECISION>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:REPORT_PRECISION">
                      <ns5:REPORT_PRECISION>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:REPORT_PRECISION"/>
                      </ns5:REPORT_PRECISION>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:DAYS">
                      <ns5:DAYS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:DAYS"/>
                      </ns5:DAYS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:HOURS">
                      <ns5:HOURS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:HOURS"/>
                      </ns5:HOURS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:MINUTES">
                      <ns5:MINUTES>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:MINUTES"/>
                      </ns5:MINUTES>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:SECONDS">
                      <ns5:SECONDS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:SECONDS"/>
                      </ns5:SECONDS>
                    </xsl:if>
                    <!--
                    <ns5:ATTRIBUTE>
                      <ns5:ATTRIBUTECATEGORY>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE_CATEGORY"/>
                      </ns5:ATTRIBUTECATEGORY>
                      <ns5:ATTRIBUTE1>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE1"/>
                      </ns5:ATTRIBUTE1>
                      <ns5:ATTRIBUTE2>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE2"/>
                      </ns5:ATTRIBUTE2>
                      <ns5:ATTRIBUTE3>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE3"/>
                      </ns5:ATTRIBUTE3>
                      <ns5:ATTRIBUTE4>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE4"/>
                      </ns5:ATTRIBUTE4>
                      <ns5:ATTRIBUTE5>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE5"/>
                      </ns5:ATTRIBUTE5>
                      <ns5:ATTRIBUTE6>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE6"/>
                      </ns5:ATTRIBUTE6>
                      <ns5:ATTRIBUTE7>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE7"/>
                      </ns5:ATTRIBUTE7>
                      <ns5:ATTRIBUTE8>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE8"/>
                      </ns5:ATTRIBUTE8>
                      <ns5:ATTRIBUTE9>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE9"/>
                      </ns5:ATTRIBUTE9>
                      <ns5:ATTRIBUTE10>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_TESTS/ns0:QSPEC_TESTS_ITEM/ns0:ATTRIBUTE10"/>
                      </ns5:ATTRIBUTE10>
                    </ns5:ATTRIBUTE>
                    -->
                  </ns5:QUALITY_SPECS_TEST>
                </xsl:if>
              </xsl:for-each>
            </ns5:QUALITY_SPECS_TEST>
            <ns5:QLTY_SPECS_VRS>
              <xsl:for-each select="">
                <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM">
                  <ns5:QLTY_SPECS_VRS>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SPEC_VR_ID">
                      <ns5:SPEC_VR_ID>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SPEC_VR_ID"/>
                      </ns5:SPEC_VR_ID>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SPEC_ID">
                      <ns5:SPEC_ID>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SPEC_ID"/>
                      </ns5:SPEC_ID>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ORGANIZATION_CODE">
                      <ns5:ORGANIZATION_CODE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ORGANIZATION_CODE"/>
                      </ns5:ORGANIZATION_CODE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SPEC_VR_TYPE">
                      <ns5:SPEC_VR_TYPE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SPEC_VR_TYPE"/>
                      </ns5:SPEC_VR_TYPE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SPEC_VR_STATUS">
                      <ns5:SPEC_VR_STATUS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SPEC_VR_STATUS"/>
                      </ns5:SPEC_VR_STATUS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:START_DATE">
                      <ns5:START_DATE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:START_DATE"/>
                      </ns5:START_DATE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:END_DATE">
                      <ns5:END_DATE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:END_DATE"/>
                      </ns5:END_DATE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SAMPLING_PLAN_NAME">
                      <ns5:SAMPLING_PLAN_NAME>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SAMPLING_PLAN_NAME"/>
                      </ns5:SAMPLING_PLAN_NAME>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:COA_TYPE">
                      <ns5:COA_TYPE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:COA_TYPE"/>
                      </ns5:COA_TYPE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:COA_AT_SHIP_IND">
                      <ns5:COA_AT_SHIP_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:COA_AT_SHIP_IND"/>
                      </ns5:COA_AT_SHIP_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:COA_AT_INVOICE_IND">
                      <ns5:COA_AT_INVOICE_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:COA_AT_INVOICE_IND"/>
                      </ns5:COA_AT_INVOICE_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:COA_FROM_SUPPLIER_IND">
                      <ns5:COA_FROM_SUPPLIER_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:COA_FROM_SUPPLIER_IND"/>
                      </ns5:COA_FROM_SUPPLIER_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:LOT_OPTIONAL_ON_SAMPLE">
                      <ns5:LOT_OPTIONAL_ON_SAMPLE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:LOT_OPTIONAL_ON_SAMPLE"/>
                      </ns5:LOT_OPTIONAL_ON_SAMPLE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:AUTO_SAMPLE_IND">
                      <ns5:AUTO_SAMPLE_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:AUTO_SAMPLE_IND"/>
                      </ns5:AUTO_SAMPLE_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:DELAYED_LOT_ENTRY">
                      <ns5:DELAYED_LOT_ENTRY>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:DELAYED_LOT_ENTRY"/>
                      </ns5:DELAYED_LOT_ENTRY>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:DELAYED_LPN_ENTRY">
                      <ns5:DELAYED_LPN_ENTRY>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:DELAYED_LPN_ENTRY"/>
                      </ns5:DELAYED_LPN_ENTRY>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:CONTROL_LOT_ATTRB_IND">
                      <ns5:CONTROL_LOT_ATTRB_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:CONTROL_LOT_ATTRB_IND"/>
                      </ns5:CONTROL_LOT_ATTRB_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:IN_SPEC_LOT_STATUS">
                      <ns5:IN_SPEC_LOT_STATUS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:IN_SPEC_LOT_STATUS"/>
                      </ns5:IN_SPEC_LOT_STATUS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:OUT_OF_SPEC_LOT_STATUS">
                      <ns5:OUT_OF_SPEC_LOT_STATUS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:OUT_OF_SPEC_LOT_STATUS"/>
                      </ns5:OUT_OF_SPEC_LOT_STATUS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SAMPLE_INV_TRANS_IND">
                      <ns5:SAMPLE_INV_TRANS_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SAMPLE_INV_TRANS_IND"/>
                      </ns5:SAMPLE_INV_TRANS_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:OPERATING_UNIT">
                      <ns5:OPERATING_UNIT>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:OPERATING_UNIT"/>
                      </ns5:OPERATING_UNIT>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:PARENT_LOT_NUMBER">
                      <ns5:PARENT_LOT_NUMBER>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:PARENT_LOT_NUMBER"/>
                      </ns5:PARENT_LOT_NUMBER>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:LOT_NUMBER">
                      <ns5:LOT_NUMBER>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:LOT_NUMBER"/>
                      </ns5:LOT_NUMBER>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SUBINVENTORY">
                      <ns5:SUBINVENTORY>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SUBINVENTORY"/>
                      </ns5:SUBINVENTORY>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ITEM_LOCATOR">
                      <ns5:ITEM_LOCATOR>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ITEM_LOCATOR"/>
                      </ns5:ITEM_LOCATOR>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:BATCH_NO">
                      <ns5:BATCH_NO>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:BATCH_NO"/>
                      </ns5:BATCH_NO>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:RECIPE_NO">
                      <ns5:RECIPE_NO>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:RECIPE_NO"/>
                      </ns5:RECIPE_NO>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:RECIPE_VERS">
                      <ns5:RECIPE_VERS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:RECIPE_VERS"/>
                      </ns5:RECIPE_VERS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:FORMULA_NO">
                      <ns5:FORMULA_NO>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:FORMULA_NO"/>
                      </ns5:FORMULA_NO>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:FORMULA_VERS">
                      <ns5:FORMULA_VERS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:FORMULA_VERS"/>
                      </ns5:FORMULA_VERS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:FORMULALINE_NO">
                      <ns5:FORMULALINE_NO>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:FORMULALINE_NO"/>
                      </ns5:FORMULALINE_NO>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ROUTING_NO">
                      <ns5:ROUTING_NO>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ROUTING_NO"/>
                      </ns5:ROUTING_NO>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ROUTING_VERS">
                      <ns5:ROUTING_VERS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ROUTING_VERS"/>
                      </ns5:ROUTING_VERS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:STEP_NO">
                      <ns5:STEP_NO>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:STEP_NO"/>
                      </ns5:STEP_NO>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:CHARGE">
                      <ns5:CHARGE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:CHARGE"/>
                      </ns5:CHARGE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:OPRN_NO">
                      <ns5:OPRN_NO>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:OPRN_NO"/>
                      </ns5:OPRN_NO>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:OPRN_VERS">
                      <ns5:OPRN_VERS>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:OPRN_VERS"/>
                      </ns5:OPRN_VERS>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:CONTROL_BATCH_STEP_IND">
                      <ns5:CONTROL_BATCH_STEP_IND>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:CONTROL_BATCH_STEP_IND"/>
                      </ns5:CONTROL_BATCH_STEP_IND>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:AUTO_COMPLETE_BATCH_STEP">
                      <ns5:AUTO_COMPLETE_BATCH_STEP>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:AUTO_COMPLETE_BATCH_STEP"/>
                      </ns5:AUTO_COMPLETE_BATCH_STEP>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:CUSTOMER_NUMBER">
                      <ns5:CUSTOMER_NUMBER>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:CUSTOMER_NUMBER"/>
                      </ns5:CUSTOMER_NUMBER>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SHIPTO_LOCATION">
                      <ns5:SHIPTO_LOCATION>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SHIPTO_LOCATION"/>
                      </ns5:SHIPTO_LOCATION>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ORDER_NUMBER">
                      <ns5:ORDER_NUMBER>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ORDER_NUMBER"/>
                      </ns5:ORDER_NUMBER>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ORDER_TYPE">
                      <ns5:ORDER_TYPE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ORDER_TYPE"/>
                      </ns5:ORDER_TYPE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ORDER_LINE_NUM">
                      <ns5:ORDER_LINE_NUM>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ORDER_LINE_NUM"/>
                      </ns5:ORDER_LINE_NUM>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SUPPLIER_NO">
                      <ns5:SUPPLIER_NO>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SUPPLIER_NO"/>
                      </ns5:SUPPLIER_NO>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SUPPLIER_SITE">
                      <ns5:SUPPLIER_SITE>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:SUPPLIER_SITE"/>
                      </ns5:SUPPLIER_SITE>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:PO_NUMBER">
                      <ns5:PO_NUMBER>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:PO_NUMBER"/>
                      </ns5:PO_NUMBER>
                    </xsl:if>
                    <xsl:if test="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:PO_LINE_NUM">
                      <ns5:PO_LINE_NUM>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:PO_LINE_NUM"/>
                      </ns5:PO_LINE_NUM>
                    </xsl:if>
                    <!--
                    <ns5:ATTRIBUTE>
                      <ns5:ATTRIBUTECATEGORY>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE_CATEGORY"/>
                      </ns5:ATTRIBUTECATEGORY>
                      <ns5:ATTRIBUTE1>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE1"/>
                      </ns5:ATTRIBUTE1>
                      <ns5:ATTRIBUTE2>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE2"/>
                      </ns5:ATTRIBUTE2>
                      <ns5:ATTRIBUTE3>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE3"/>
                      </ns5:ATTRIBUTE3>
                      <ns5:ATTRIBUTE4>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE4"/>
                      </ns5:ATTRIBUTE4>
                      <ns5:ATTRIBUTE5>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE5"/>
                      </ns5:ATTRIBUTE5>
                      <ns5:ATTRIBUTE6>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE6"/>
                      </ns5:ATTRIBUTE6>
                      <ns5:ATTRIBUTE7>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE7"/>
                      </ns5:ATTRIBUTE7>
                      <ns5:ATTRIBUTE8>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE8"/>
                      </ns5:ATTRIBUTE8>
                      <ns5:ATTRIBUTE9>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE9"/>
                      </ns5:ATTRIBUTE9>
                      <ns5:ATTRIBUTE10>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_QSPEC_PAYLOAD/ns0:P_QSPEC_PAYLOAD_ITEM/ns0:QSPEC_VALIDITY_RULE/ns0:QSPEC_VALIDITY_RULE_ITEM/ns0:ATTRIBUTE10"/>
                      </ns5:ATTRIBUTE10>
                    </ns5:ATTRIBUTE>
                    -->
                  </ns5:QLTY_SPECS_VRS>
                </xsl:if>
              </xsl:for-each>
            </ns5:QLTY_SPECS_VRS>
          </ns5:QualitySpecsDetails>
        </xsl:if>
      </xsl:for-each>
    </tns:QueryQualitySpecsAddRs>
  </xsl:template>
</xsl:stylesheet>
