<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getDeliverAttribute"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/WSH_OTM_OUTBOUND/GET_DELIVERY_OBJECTS/"
                xmlns:tns="http://xmlns.oracle.com/apps/wsh/outbound/txn/WshSendDlvyToOtmService"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/WshSendDlvyToOtmService/getDeliverAttribute"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/DeliveryInformation/"
                xmlns:ns4="http://xmlns.oracle.com/apps/otm"
                xmlns:txn="http://xmlns.oracle.com/apps/wsh/outbound/util/WshOtmGlobalOutbound">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../partnerWsdls/DeliveryInformation.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/WSH_OTM_OUTBOUND/GET_DELIVERY_OBJECTS/"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../partnerWsdls/getDeliverAttribute.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getDeliverAttribute"/>
        <oracle-xsl-mapper:param name="g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WshSendDlvyToOtmService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="WshSendDlvyToOtmServiceProcessResponse"
                                       namespace="http://xmlns.oracle.com/apps/wsh/outbound/txn/WshSendDlvyToOtmService"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JUN 01 08:58:04 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <tns:WshSendDlvyToOtmServiceProcessResponse>
      <tns:result>
        <txn:entityidList>
          <xsl:for-each select="/ns0:OutputParameters/P_DLV_ID_TAB/P_DLV_ID_TAB_ITEM">
            <txn:entityId>
              <xsl:value-of select="."/>
            </txn:entityId>
          </xsl:for-each>
        </txn:entityidList>
        <txn:errorIdList>
          <xsl:for-each select="/ns0:OutputParameters/X_ERROR_DLV_ID_TAB/P_DLV_ID_TAB_ITEM">
            <txn:entityId>
              <xsl:value-of select="."/>
            </txn:entityId>
          </xsl:for-each>
        </txn:errorIdList>
        <ns4:Transmission>
          <ns4:TransmissionHeader>
            <ns4:UserName>
              <xsl:value-of select="/ns0:OutputParameters/X_OTM_USER_NAME"/>
            </ns4:UserName>
            <ns4:Password>
              <xsl:value-of select="/ns0:OutputParameters/X_OTM_PWD"/>
            </ns4:Password>
          </ns4:TransmissionHeader>
          <ns4:TransmissionBody>
            <xsl:for-each select="/ns0:OutputParameters/X_DLV_TAB/X_DLV_TAB_ITEM">
              <ns4:GLogXMLElement>
                <ns4:TransactionHeader>
                  <ns4:TimeZoneGid>
                    <ns4:Gid>
                      <ns4:Xid>
                        <xsl:value-of select="../../X_SERVER_TZ_CODE"/>
                      </ns4:Xid>
                    </ns4:Gid>
                  </ns4:TimeZoneGid>
                </ns4:TransactionHeader>
                <ns4:Release>
                  <ns4:ReleaseGid>
                    <ns4:Gid>
                      <ns4:DomainName>
                        <!-- <xsl:value-of select="../../X_DOMAIN_NAME"/>-->
                        <xsl:value-of select="concat(../../X_DOMAIN_NAME,'/','BMG')"/>
                      </ns4:DomainName>
                      <ns4:Xid>
                        <xsl:value-of select="DELIVERY_ID"/>
                      </ns4:Xid>
                    </ns4:Gid>
                  </ns4:ReleaseGid>
                  <ns4:TransactionCode>
                    <xsl:value-of select="TRANSACTION_CODE"/>
                  </ns4:TransactionCode>
                  <ns4:ReleaseHeader>
                    <ns4:ReleaseName>
                      <xsl:value-of select="NAME"/>
                    </ns4:ReleaseName>
                    <ns4:ReleaseMethodGid>
                      <ns4:Gid>
                        <ns4:Xid>
                          <xsl:value-of select='"PREPACK"'/>
                        </ns4:Xid>
                      </ns4:Gid>
                    </ns4:ReleaseMethodGid>
                    <xsl:if test="not((string-length(FREIGHT_TERMS) = 0.0)) or not((string-length(FOB_CODE) = 0.0))">
                      <ns4:CommercialTerms>
                        <xsl:if test="not(string-length(FREIGHT_TERMS) = 0.0)">
                          <ns4:PaymentMethodCodeGid>
                            <ns4:Gid>
                              <ns4:DomainName>
                                <xsl:value-of select="../../X_DOMAIN_NAME"/>
                              </ns4:DomainName>
                              <ns4:Xid>
                                <xsl:value-of select="FREIGHT_TERMS"/>
                              </ns4:Xid>
                            </ns4:Gid>
                          </ns4:PaymentMethodCodeGid>
                        </xsl:if>
                        <xsl:if test="not(string-length(FOB_CODE) = 0.0)">
                          <!-- Sreepati Commented as part of new chnages-->
                          <!--ns4:IncoTermGid>
                            <ns4:Gid>
                              <ns4:DomainName>
                                <xsl:value-of select="../../X_DOMAIN_NAME"/>
                              </ns4:DomainName>
                              <ns4:Xid>
                                <xsl:value-of select="FOB_CODE"/>
                              </ns4:Xid>
                            </ns4:Gid>
                          </ns4:IncoTermGid-->
                        </xsl:if>
                      </ns4:CommercialTerms>
                    </xsl:if>
                    <ns4:TimeWindowEmphasisGid>
                      <ns4:Gid>
                        <ns4:Xid>
                          <xsl:value-of select='"BOTH"'/>
                        </ns4:Xid>
                      </ns4:Gid>
                    </ns4:TimeWindowEmphasisGid>
                    <!--xsl:if test="not(string-length(SERVICE_LEVEL) = 0.0)">
                      <ns4:RateServiceGid>
                        <ns4:Gid>
                          <ns4:DomainName>
                            <xsl:value-of select="../../X_DOMAIN_NAME"/>
                          </ns4:DomainName>
                          <ns4:Xid>
                            <xsl:value-of select="SERVICE_LEVEL"/>
                          </ns4:Xid>
                        </ns4:Gid>
                      </ns4:RateServiceGid>
                    </xsl:if-->
                    <xsl:if test="not(string-length(CARRIER_ID) = 0.0)">
                      <ns4:ServiceProviderGid>
                        <ns4:Gid>
                          <ns4:DomainName>
                            <xsl:value-of select="../../X_DOMAIN_NAME"/>
                          </ns4:DomainName>
                          <ns4:Xid>
                            <xsl:value-of select="CARRIER_ID"/>
                          </ns4:Xid>
                        </ns4:Gid>
                      </ns4:ServiceProviderGid>
                    </xsl:if>
                    <xsl:if test="not(string-length(MODE_OF_TRANSPORT) = 0.0)">
                      <ns4:TransportModeGid>
                        <ns4:Gid>
                          <!--Sreepati -Domain name is commented-->
                          <!--ns4:DomainName>
                            <xsl:value-of select="../../X_DOMAIN_NAME"/>
                          </ns4:DomainName-->
                          <ns4:Xid>
                            <xsl:value-of select="MODE_OF_TRANSPORT"/>
                          </ns4:Xid>
                        </ns4:Gid>
                      </ns4:TransportModeGid>
                    </xsl:if>
                    <ns4:FlexFieldStrings>
                      <ns4:Attribute1>
                        <xsl:value-of select="SERVICE_LEVEL"/>
                      </ns4:Attribute1>
                      <ns4:Attribute6>
                        <xsl:value-of select="oraext:query-database (concat (&quot;select attribute3 FROM wsh_new_deliveries  WHERE delivery_id = '&quot;, DELIVERY_ID, &quot;' &quot; ), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
                      </ns4:Attribute6>
                    </ns4:FlexFieldStrings>
                  </ns4:ReleaseHeader>
                  <ns4:ShipFromLocationRef>
                    <ns4:LocationRef>
                      <ns4:LocationGid>
                        <ns4:Gid>
                          <ns4:DomainName>
                            <xsl:value-of select="../../X_DOMAIN_NAME"/>
                          </ns4:DomainName>
                          <ns4:Xid>
                            <xsl:value-of select="INITIAL_PICKUP_LOCATION_ID"/>
                          </ns4:Xid>
                        </ns4:Gid>
                      </ns4:LocationGid>
                    </ns4:LocationRef>
                  </ns4:ShipFromLocationRef>
                  <ns4:ShipToLocationRef>
                    <ns4:LocationRef>
                      <ns4:LocationGid>
                        <ns4:Gid>
                          <ns4:DomainName>
                            <xsl:value-of select="../../X_DOMAIN_NAME"/>
                          </ns4:DomainName>
                          <ns4:Xid>
                            <xsl:value-of select="ULTIMATE_DROPOFF_LOCATION_ID"/>
                          </ns4:Xid>
                        </ns4:Gid>
                      </ns4:LocationGid>
                    </ns4:LocationRef>
                  </ns4:ShipToLocationRef>
                  <!-- Code changes/commented done for CR#334-->
                  <ns4:TimeWindow>
                    <xsl:if test="not (string-length ($g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_ATTRIBUTE7 ) = 0 )">
                      <ns4:EarlyPickupDate>
                        <xsl:value-of select='xp20:format-dateTime($g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_ATTRIBUTE7,"[Y0001][M01][D01][H01][m01][s01]")'/>
                      </ns4:EarlyPickupDate>
                    </xsl:if>
                    <xsl:if test="not(string-length($g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_ATTRIBUTE8) = 0.0)">
                      <ns4:LatePickupDate>
                        <xsl:value-of select='xp20:format-dateTime($g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_ATTRIBUTE8,"[Y0001][M01][D01][H01][m01][s01]")'/>
                      </ns4:LatePickupDate>
                    </xsl:if>
                    <xsl:if test="not(string-length($g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_ATTRIBUTE9) = 0.0)">
                      <ns4:EarlyDeliveryDate>
                        <xsl:value-of select='xp20:format-dateTime($g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_ATTRIBUTE9,"[Y0001][M01][D01][H01][m01][s01]")'/>
                      </ns4:EarlyDeliveryDate>
                    </xsl:if>
                    <xsl:if test="not (string-length ($g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_ATTRIBUTE10 ) = 0 )">
                      <ns4:LateDeliveryDate>
                        <xsl:value-of select='xp20:format-dateTime($g_Invoke_getDeliverAttribute_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_ATTRIBUTE10,"[Y0001][M01][D01][H01][m01][s01]")'/>
                      </ns4:LateDeliveryDate>
                    </xsl:if>
                  </ns4:TimeWindow>
                  <xsl:for-each select="RL_DETAILS/RL_DETAILS_ITEM">
                    <ns4:ReleaseLine>
                      <ns4:ReleaseLineGid>
                        <ns4:Gid>
                          <ns4:DomainName>
                            <xsl:value-of select="concat(../../../../X_DOMAIN_NAME,'/','BMG')"/>
                          </ns4:DomainName>
                          <ns4:Xid>
                            <xsl:value-of select="DELIVERY_DETAIL_ID"/>
                          </ns4:Xid>
                        </ns4:Gid>
                      </ns4:ReleaseLineGid>
                      <ns4:PackagedItemRef>
                        <ns4:PackagedItemGid>
                          <ns4:Gid>
                            <ns4:DomainName>
                              <xsl:value-of select="../../../../X_DOMAIN_NAME"/>
                            </ns4:DomainName>
                            <ns4:Xid>
                              <xsl:value-of select="INVENTORY_ITEM_ID"/>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:PackagedItemGid>
                      </ns4:PackagedItemRef>
                      <ns4:ItemQuantity>
                        <xsl:if test="not(string-length(LOT_NUMBER) = 0.0)">
                          <ns4:ItemTag1>
                            <xsl:value-of select="LOT_NUMBER"/>
                          </ns4:ItemTag1>
                        </xsl:if>
                        <xsl:if test="not(string-length(SERIAL_NUMBER) = 0.0)">
                          <ns4:ItemTag2>
                            <xsl:value-of select="SERIAL_NUMBER"/>
                          </ns4:ItemTag2>
                        </xsl:if>
                        <xsl:if test="not(string-length(TO_SERIAL_NUMBER) = 0.0)">
                          <ns4:ItemTag3>
                            <xsl:value-of select="TO_SERIAL_NUMBER"/>
                          </ns4:ItemTag3>
                        </xsl:if>
                        <ns4:IsSplitAllowed>
                          <xsl:value-of select='"N"'/>
                        </ns4:IsSplitAllowed>
                        <ns4:WeightVolume>
                          <xsl:if test="not(string-length(GROSS_WEIGHT) = 0.0)">
                            <ns4:Weight>
                              <ns4:WeightValue>
                                <xsl:value-of select="GROSS_WEIGHT"/>
                              </ns4:WeightValue>
                              <ns4:WeightUOMGid>
                                <ns4:Gid>
                                  <ns4:Xid>
                                    <xsl:value-of select="WEIGHT_UOM_CODE"/>
                                  </ns4:Xid>
                                </ns4:Gid>
                              </ns4:WeightUOMGid>
                            </ns4:Weight>
                          </xsl:if>
                          <xsl:if test="not(string-length(VOLUME) = 0.0)">
                            <ns4:Volume>
                              <ns4:VolumeValue>
                                <xsl:value-of select="VOLUME"/>
                              </ns4:VolumeValue>
                              <ns4:VolumeUOMGid>
                                <ns4:Gid>
                                  <ns4:Xid>
                                    <xsl:value-of select="VOLUME_UOM_CODE"/>
                                  </ns4:Xid>
                                </ns4:Gid>
                              </ns4:VolumeUOMGid>
                            </ns4:Volume>
                          </xsl:if>
                        </ns4:WeightVolume>
                        <xsl:if test="not(string-length(REQUESTED_QUANTITY) = 0.0)">
                          <ns4:PackagedItemCount>
                            <xsl:value-of select="ceiling(REQUESTED_QUANTITY)"/>
                          </ns4:PackagedItemCount>
                        </xsl:if>
                      </ns4:ItemQuantity>
                      <xsl:for-each select="CUST_PO_NUMBER">
                        <xsl:if test="not(string-length(.) = 0.0)">
                          <ns4:Refnum>
                            <ns4:RefnumQualifierGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:value-of select="../CUST_PO_NUMBER_QLFR"/>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:RefnumQualifierGid>
                            <ns4:RefnumValue>
                              <xsl:value-of select="."/>
                            </ns4:RefnumValue>
                          </ns4:Refnum>
                        </xsl:if>
                      </xsl:for-each>
                      <xsl:for-each select="SOURCE_HEADER_NUMBER">
                        <xsl:if test="not(string-length(.) = 0.0)">
                          <ns4:Refnum>
                            <ns4:RefnumQualifierGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:value-of select="../SOURCE_HEADER_NUMBER_QLFR"/>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:RefnumQualifierGid>
                            <ns4:RefnumValue>
                              <xsl:value-of select="."/>
                            </ns4:RefnumValue>
                          </ns4:Refnum>
                        </xsl:if>
                      </xsl:for-each>
                      <!-- edited by ashwin for duplication of record bug 13518617 -->
                      <ns4:Remark>
                        <ns4:RemarkSequence>
                          <xsl:text disable-output-escaping="no">1</xsl:text>
                        </ns4:RemarkSequence>
                        <ns4:RemarkQualifierGid>
                          <ns4:Gid>
                            <ns4:Xid>
                              <xsl:text disable-output-escaping="no">ITEM_ID</xsl:text>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:RemarkQualifierGid>
                        <ns4:RemarkText>
                          <!--<xsl:text disable-output-escaping="no"><xsl:value-of select="substring-after(INVENTORY_ITEM_ID,'-')"/></xsl:text>-->
                          <xsl:value-of select="substring-after(INVENTORY_ITEM_ID,'-')"/>
                        </ns4:RemarkText>
                      </ns4:Remark>
                      <ns4:Remark>
                        <ns4:RemarkSequence>
                          <xsl:text disable-output-escaping="no">2</xsl:text>
                        </ns4:RemarkSequence>
                        <ns4:RemarkQualifierGid>
                          <ns4:Gid>
                            <ns4:Xid>
                              <xsl:text disable-output-escaping="no">ORG_ID</xsl:text>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:RemarkQualifierGid>
                        <ns4:RemarkText>
                          <xsl:value-of select="substring-before(INVENTORY_ITEM_ID,'-')"/>
                        </ns4:RemarkText>
                      </ns4:Remark>
                      <!-- editing ended by ashwin 13518617 -->
                    </ns4:ReleaseLine>
                  </xsl:for-each>
                  <xsl:for-each select="LPN/LPN_ITEM">
                    <ns4:ShipUnit>
                      <ns4:ShipUnitGid>
                        <ns4:Gid>
                          <ns4:DomainName>
                            <xsl:value-of select="concat(../../../../X_DOMAIN_NAME,'/','BMG')"/>
                          </ns4:DomainName>
                          <ns4:Xid>
                            <xsl:value-of select="LPN_ID"/>
                          </ns4:Xid>
                        </ns4:Gid>
                      </ns4:ShipUnitGid>
                      <ns4:TransactionCode>
                        <xsl:value-of select="../../TRANSACTION_CODE"/>
                      </ns4:TransactionCode>
                      <xsl:if test="not(string-length(CONTAINER_TYPE_CODE) = 0.0)">
                        <ns4:ShipUnitSpecGid>
                          <ns4:Gid>
                            <ns4:DomainName>
                              <xsl:value-of select="../../../../X_DOMAIN_NAME"/>
                            </ns4:DomainName>
                            <ns4:Xid>
                              <xsl:value-of select="CONTAINER_TYPE_CODE"/>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:ShipUnitSpecGid>
                      </xsl:if>
                      <ns4:WeightVolume>
                        <xsl:if test="not(string-length(GROSS_WEIGHT) = 0.0)">
                          <ns4:Weight>
                            <ns4:WeightValue>
                              <xsl:value-of select="GROSS_WEIGHT"/>
                            </ns4:WeightValue>
                            <ns4:WeightUOMGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:value-of select="WEIGHT_UOM_CODE"/>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:WeightUOMGid>
                          </ns4:Weight>
                        </xsl:if>
                        <xsl:if test="not(string-length(VOLUME) = 0.0)">
                          <ns4:Volume>
                            <ns4:VolumeValue>
                              <xsl:value-of select="VOLUME"/>
                            </ns4:VolumeValue>
                            <ns4:VolumeUOMGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:value-of select="VOLUME_UOM_CODE"/>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:VolumeUOMGid>
                          </ns4:Volume>
                        </xsl:if>
                      </ns4:WeightVolume>
                      <ns4:UnitNetWeightVolume>
                        <xsl:if test="not(string-length(NET_WEIGHT) = 0.0)">
                          <ns4:Weight>
                            <ns4:WeightValue>
                              <xsl:value-of select="NET_WEIGHT"/>
                            </ns4:WeightValue>
                            <ns4:WeightUOMGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:value-of select="WEIGHT_UOM_CODE"/>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:WeightUOMGid>
                          </ns4:Weight>
                        </xsl:if>
                      </ns4:UnitNetWeightVolume>
                      <!--ns4:LengthWidthHeight>
                        <xsl:if test="not(string-length(UNIT_LENGTH) = 0.0)">
                          <ns4:Length>
                            <ns4:LengthValue>
                              <xsl:value-of select="UNIT_LENGTH"/>
                            </ns4:LengthValue>
                            <ns4:LengthUOMGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:value-of select="DIMENSION_UM_CODE"/>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:LengthUOMGid>
                          </ns4:Length>
                        </xsl:if>
                        <xsl:if test="not(string-length(UNIT_WIDTH) = 0.0)">
                          <ns4:Width>
                            <ns4:WidthValue>
                              <xsl:value-of select="UNIT_WIDTH"/>
                            </ns4:WidthValue>
                            <ns4:WidthUOMGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:value-of select="DIMENSION_UM_CODE"/>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:WidthUOMGid>
                          </ns4:Width>
                        </xsl:if>
                        <xsl:if test="not(string-length(UNIT_HEIGHT) = 0.0)">
                          <ns4:Height>
                            <ns4:HeightValue>
                              <xsl:value-of select="UNIT_HEIGHT"/>
                            </ns4:HeightValue>
                            <ns4:HeightUOMGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:value-of select="DIMENSION_UM_CODE"/>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:HeightUOMGid>
                          </ns4:Height>
                        </xsl:if>
                      </ns4:LengthWidthHeight-->
                      <ns4:ShipUnitSeal>
                        <ns4:SealNumber>
                          <xsl:value-of select="SEAL_CODE"/>
                        </ns4:SealNumber>
                      </ns4:ShipUnitSeal>
                      <xsl:for-each select="PACKED_ITEMS/PACKED_ITEMS_ITEM">
                        <ns4:ShipUnitContent>
                          <ns4:LineNumber>
                            <xsl:value-of select="LINE_NUMBER"/>
                          </ns4:LineNumber>
                          <ns4:ItemQuantity>
                            <ns4:WeightVolume>
                              <ns4:Weight>
                                <ns4:WeightValue>
                                  <xsl:value-of select="GROSS_WEIGHT"/>
                                </ns4:WeightValue>
                                <ns4:WeightUOMGid>
                                  <ns4:Gid>
                                    <ns4:Xid>
                                      <xsl:value-of select="WEIGHT_UOM_CODE"/>
                                    </ns4:Xid>
                                  </ns4:Gid>
                                </ns4:WeightUOMGid>
                              </ns4:Weight>
                              <ns4:Volume>
                                <ns4:VolumeValue>
                                  <xsl:value-of select="VOLUME"/>
                                </ns4:VolumeValue>
                                <ns4:VolumeUOMGid>
                                  <ns4:Gid>
                                    <ns4:Xid>
                                      <xsl:value-of select="VOLUME_UOM_CODE"/>
                                    </ns4:Xid>
                                  </ns4:Gid>
                                </ns4:VolumeUOMGid>
                              </ns4:Volume>
                            </ns4:WeightVolume>
                            <ns4:PackagedItemCount>
                              <xsl:value-of select="ITEM_QUANTITY"/>
                            </ns4:PackagedItemCount>
                          </ns4:ItemQuantity>
                          <ns4:ReleaseGid>
                            <ns4:Gid>
                              <ns4:DomainName>
                                <xsl:value-of select="concat(../../../../../../X_DOMAIN_NAME,'/','BMG')"/>
                              </ns4:DomainName>
                              <ns4:Xid>
                                <xsl:value-of select="../../../../DELIVERY_ID"/>
                              </ns4:Xid>
                            </ns4:Gid>
                          </ns4:ReleaseGid>
                          <ns4:ReleaseLineGid>
                            <ns4:Gid>
                              <ns4:DomainName>
                                <xsl:value-of select="concat(../../../../../../X_DOMAIN_NAME,'/','BMG')"/>
                              </ns4:DomainName>
                              <ns4:Xid>
                                <xsl:value-of select="CONTENT_ID"/>
                              </ns4:Xid>
                            </ns4:Gid>
                          </ns4:ReleaseLineGid>
                          <!-- edited by ashwin for duplication of record bug 13518617 -->
                          <ns4:Remark>
                            <ns4:RemarkSequence>
                              <xsl:text disable-output-escaping="no">1</xsl:text>
                            </ns4:RemarkSequence>
                            <ns4:RemarkQualifierGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:text disable-output-escaping="no">ITEM_ID</xsl:text>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:RemarkQualifierGid>
                            <ns4:RemarkText>
                              <xsl:value-of select="substring-after(ITEM_REF,'-')"/>
                            </ns4:RemarkText>
                          </ns4:Remark>
                          <ns4:Remark>
                            <ns4:RemarkSequence>
                              <xsl:text disable-output-escaping="no">2</xsl:text>
                            </ns4:RemarkSequence>
                            <ns4:RemarkQualifierGid>
                              <ns4:Gid>
                                <ns4:Xid>
                                  <xsl:text disable-output-escaping="no">ORG_ID</xsl:text>
                                </ns4:Xid>
                              </ns4:Gid>
                            </ns4:RemarkQualifierGid>
                            <ns4:RemarkText>
                              <xsl:value-of select="substring-before(ITEM_REF,'-')"/>
                            </ns4:RemarkText>
                          </ns4:Remark>
                          <!-- editing ended by ashwin 13518617 -->
                        </ns4:ShipUnitContent>
                      </xsl:for-each>
                      <ns4:ShipUnitCount>
                        <xsl:value-of select='"1"'/>
                      </ns4:ShipUnitCount>
                    </ns4:ShipUnit>
                  </xsl:for-each>
                  <ns4:TotalWeightVolume>
                    <ns4:WeightVolume>
                      <xsl:if test="not(string-length(GROSS_WEIGHT) = 0.0)">
                        <ns4:Weight>
                          <ns4:WeightValue>
                            <xsl:value-of select="GROSS_WEIGHT"/>
                          </ns4:WeightValue>
                          <ns4:WeightUOMGid>
                            <ns4:Gid>
                              <ns4:Xid>
                                <xsl:value-of select="WEIGHT_UOM_CODE"/>
                              </ns4:Xid>
                            </ns4:Gid>
                          </ns4:WeightUOMGid>
                        </ns4:Weight>
                      </xsl:if>
                      <xsl:if test="not(string-length(VOLUME) = 0.0)">
                        <ns4:Volume>
                          <ns4:VolumeValue>
                            <xsl:value-of select="VOLUME"/>
                          </ns4:VolumeValue>
                          <ns4:VolumeUOMGid>
                            <ns4:Gid>
                              <ns4:Xid>
                                <xsl:value-of select="VOLUME_UOM_CODE"/>
                              </ns4:Xid>
                            </ns4:Gid>
                          </ns4:VolumeUOMGid>
                        </ns4:Volume>
                      </xsl:if>
                    </ns4:WeightVolume>
                  </ns4:TotalWeightVolume>
                  <ns4:TotalNetWeightVolume>
                    <xsl:if test="not(string-length(NET_WEIGHT) = 0.0)">
                      <ns4:Weight>
                        <ns4:WeightValue>
                          <xsl:value-of select="NET_WEIGHT"/>
                        </ns4:WeightValue>
                        <ns4:WeightUOMGid>
                          <ns4:Gid>
                            <ns4:Xid>
                              <xsl:value-of select="WEIGHT_UOM_CODE"/>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:WeightUOMGid>
                      </ns4:Weight>
                    </xsl:if>
                  </ns4:TotalNetWeightVolume>
                  <ns4:TotalPackagedItemCount>
                    <xsl:value-of select="TOTAL_ITEM_COUNT"/>
                  </ns4:TotalPackagedItemCount>
                  <xsl:if test="not(string-length(.) = 0.0)">
                    <ns4:ReleaseRefnum>
                      <ns4:ReleaseRefnumQualifierGid>
                        <ns4:Gid>
                          <ns4:Xid>
                            <xsl:value-of select="REVISION_QLFR"/>
                          </ns4:Xid>
                        </ns4:Gid>
                      </ns4:ReleaseRefnumQualifierGid>
                      <ns4:ReleaseRefnumValue>
                        <xsl:value-of select="REVISION"/>
                      </ns4:ReleaseRefnumValue>
                    </ns4:ReleaseRefnum>
                  </xsl:if>
                  <xsl:for-each select="REASON_OF_TRANSPORT">
                    <xsl:if test="not(string-length(.) = 0.0)">
                      <ns4:Remark>
                        <ns4:RemarkQualifierGid>
                          <ns4:Gid>
                            <ns4:Xid>
                              <xsl:value-of select="../REASON_OF_TRANSPORT_QLFR"/>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:RemarkQualifierGid>
                        <ns4:RemarkText>
                          <xsl:value-of select="."/>
                        </ns4:RemarkText>
                      </ns4:Remark>
                    </xsl:if>
                  </xsl:for-each>
                  <xsl:for-each select="DESCRIPTION">
                    <xsl:if test="not(string-length(.) = 0.0)">
                      <ns4:Remark>
                        <ns4:RemarkQualifierGid>
                          <ns4:Gid>
                            <ns4:Xid>
                              <xsl:value-of select="../DESCRIPTION_QLFR"/>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:RemarkQualifierGid>
                        <ns4:RemarkText>
                          <xsl:value-of select="."/>
                        </ns4:RemarkText>
                      </ns4:Remark>
                    </xsl:if>
                  </xsl:for-each>
                  <xsl:for-each select="ADDITIONAL_SHIPMENT_INFO">
                    <xsl:if test="not(string-length(.) = 0.0)">
                      <ns4:Remark>
                        <ns4:RemarkQualifierGid>
                          <ns4:Gid>
                            <ns4:Xid>
                              <xsl:value-of select="../ADDITIONAL_SHIPMENT_INFO_QLFR"/>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:RemarkQualifierGid>
                        <ns4:RemarkText>
                          <xsl:value-of select="."/>
                        </ns4:RemarkText>
                      </ns4:Remark>
                    </xsl:if>
                  </xsl:for-each>
                  <xsl:for-each select="ROUTING_INSTRUCTIONS">
                    <xsl:if test="not(string-length(.) = 0.0)">
                      <ns4:Remark>
                        <ns4:RemarkQualifierGid>
                          <ns4:Gid>
                            <ns4:Xid>
                              <xsl:value-of select="../ROUTING_INSTRUCTIONS_QLFR"/>
                            </ns4:Xid>
                          </ns4:Gid>
                        </ns4:RemarkQualifierGid>
                        <ns4:RemarkText>
                          <xsl:value-of select="."/>
                        </ns4:RemarkText>
                      </ns4:Remark>
                    </xsl:if>
                  </xsl:for-each>
                </ns4:Release>
              </ns4:GLogXMLElement>
            </xsl:for-each>
          </ns4:TransmissionBody>
        </ns4:Transmission>
        <txn:returnStatus>
          <xsl:value-of select="/ns0:OutputParameters/X_RETURN_STATUS"/>
        </txn:returnStatus>
      </tns:result>
    </tns:WshSendDlvyToOtmServiceProcessResponse>
  </xsl:template>
</xsl:stylesheet>
