<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="www.Nucor.com"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="www.Nucor.com"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="SAP_FI_Posting_Service">
        <plnk:role name="SapDataSoap" portType="tns:SapDataSoap"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="www.Nucor.com" location="NucorSAPData.asmx.wsdl"/>
</wsdl:definitions>
