<wsdl:definitions
     name="DB_DeleteSapSpsData"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NUCOR/NUC_Emp_SAP_EBiz_ABF/DB_DeleteSapSpsData"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_DeleteSapSpsData"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NUCOR/NUC_Emp_SAP_EBiz_ABF/DB_DeleteSapSpsData"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="DB_DeleteSapSpsData_plt" >
    <plt:role name="DB_DeleteSapSpsData_role" >
      <plt:portType name="tns:DB_DeleteSapSpsData_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_DeleteSapSpsData_plt" >
    <plt:role name="DB_DeleteSapSpsData_role" >
      <plt:portType name="tns:DB_DeleteSapSpsData_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_DeleteSapSpsData_plt" >
    <plt:role name="DB_DeleteSapSpsData_role" >
      <plt:portType name="tns:DB_DeleteSapSpsData_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_DeleteSapSpsData" schemaLocation="xsd/DB_DeleteSapSpsData.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_DeleteSapSpsData" schemaLocation="xsd/DB_DeleteSapSpsData.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_DeleteSapSpsData" schemaLocation="xsd/DB_DeleteSapSpsData.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_DeleteSapSpsDataInput_msg">
        <wsdl:part name="DB_DeleteSapSpsDataInput_msg" element="db:DB_DeleteSapSpsDataInput"/>
    </wsdl:message>
    <wsdl:portType name="DB_DeleteSapSpsData_ptt">
        <wsdl:operation name="DB_DeleteSapSpsData">
            <wsdl:input message="tns:DB_DeleteSapSpsDataInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
