<wsdl:definitions
     name="DB_SelectUpdateEmpRecs"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NucorPordSup/NUC_Emp_SAP_EBiz_ABF/DB_SelectUpdateEmpRecs"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NucorPordSup/NUC_Emp_SAP_EBiz_ABF/DB_SelectUpdateEmpRecs"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="DB_SelectUpdateEmpRecs_plt" >
    <plt:role name="DB_SelectUpdateEmpRecs_role" >
      <plt:portType name="tns:DB_SelectUpdateEmpRecs_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_SelectUpdateEmpRecs_plt" >
    <plt:role name="DB_SelectUpdateEmpRecs_role" >
      <plt:portType name="tns:DB_SelectUpdateEmpRecs_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_SelectUpdateEmpRecs_plt" >
    <plt:role name="DB_SelectUpdateEmpRecs_role" >
      <plt:portType name="tns:DB_SelectUpdateEmpRecs_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_SelectUpdateEmpRecs_plt" >
    <plt:role name="DB_SelectUpdateEmpRecs_role" >
      <plt:portType name="tns:DB_SelectUpdateEmpRecs_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs" schemaLocation="xsd/DB_SelectUpdateEmpRecs.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs" schemaLocation="xsd/DB_SelectUpdateEmpRecs.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs" schemaLocation="xsd/DB_SelectUpdateEmpRecs.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_SelectUpdateEmpRecs" schemaLocation="xsd/DB_SelectUpdateEmpRecs.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_SelectUpdateEmpRecsInput_msg">
        <wsdl:part name="DB_SelectUpdateEmpRecsInput_msg" element="db:DB_SelectUpdateEmpRecsInput"/>
    </wsdl:message>
    <wsdl:message name="DB_SelectUpdateEmpRecsOutputCollection_msg">
        <wsdl:part name="DB_SelectUpdateEmpRecsOutputCollection" element="db:DB_SelectUpdateEmpRecsOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_SelectUpdateEmpRecs_ptt">
        <wsdl:operation name="DB_SelectUpdateEmpRecs">
            <wsdl:input message="tns:DB_SelectUpdateEmpRecsInput_msg"/>
            <wsdl:output message="tns:DB_SelectUpdateEmpRecsOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
