<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Demographic"
     targetNamespace="http://tempuri.org/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://tempuri.org/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="WS_Demographics">
        <plnk:role name="IDemo">
            <plnk:portType name="tns:IDemo"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://tempuri.org/" location="oramds:/apps/EIAMetadata/ABS/SAP/V1.0/demographics.wsdl"/>
</wsdl:definitions>
