<wsdl:definitions
     name="DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/i102/NUC_UpdateLogEntry_EBS_CP_ABF/DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/i102/NUC_UpdateLogEntry_EBS_CP_ABF/DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG_plt" >
    <plt:role name="DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG_role" >
      <plt:portType name="tns:DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG_plt" >
    <plt:role name="DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG_role" >
      <plt:portType name="tns:DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG" schemaLocation="../Schemas/DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="XxnucWshCpFreinvHdrStgCollection_msg">
        <wsdl:part name="XxnucWshCpFreinvHdrStgCollection" element="top:XxnucWshCpFreinvHdrStgCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Poll_XXNUC_WSH_CP_FREINV_HDR_STG_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:XxnucWshCpFreinvHdrStgCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
