-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_OA_LAUNCHAUTOINVOICEAPI AS
   FUNCTION ap_import_invoices_pkg$import (P_BATCH_NAME VARCHAR2,
	P_GL_DATE DATE,
	P_HOLD_CODE VARCHAR2,
	P_HOLD_REASON VARCHAR2,
	P_COMMIT_CYCLES NUMBER,
	P_SOURCE VARCHAR2,
	P_GROUP_ID VARCHAR2,
	P_CONC_REQUEST_ID NUMBER,
	P_DEBUG_SWITCH VARCHAR2,
	P_ORG_ID NUMBER,
	P_BATCH_ERROR_FLAG OUT VARCHAR2,
	P_INVOICES_FETCHED OUT NUMBER,
	P_INVOICES_CREATED OUT NUMBER,
	P_TOTAL_INVOICE_AMOUNT OUT NUMBER,
	P_PRINT_BATCH OUT VARCHAR2,
	P_CALLING_SEQUENCE VARCHAR2,
	P_INVOICE_INTERFACE_ID NUMBER,
	P_NEEDS_INVOICE_APPROVAL VARCHAR2,
	P_COMMIT VARCHAR2
	) RETURN INTEGER;
END BPEL_OA_LAUNCHAUTOINVOICEAPI;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_OA_LAUNCHAUTOINVOICEAPI IS

   FUNCTION ap_import_invoices_pkg$import (P_BATCH_NAME VARCHAR2,
	P_GL_DATE DATE,
	P_HOLD_CODE VARCHAR2,
	P_HOLD_REASON VARCHAR2,
	P_COMMIT_CYCLES NUMBER,
	P_SOURCE VARCHAR2,
	P_GROUP_ID VARCHAR2,
	P_CONC_REQUEST_ID NUMBER,
	P_DEBUG_SWITCH VARCHAR2,
	P_ORG_ID NUMBER,
	P_BATCH_ERROR_FLAG OUT VARCHAR2,
	P_INVOICES_FETCHED OUT NUMBER,
	P_INVOICES_CREATED OUT NUMBER,
	P_TOTAL_INVOICE_AMOUNT OUT NUMBER,
	P_PRINT_BATCH OUT VARCHAR2,
	P_CALLING_SEQUENCE VARCHAR2,
	P_INVOICE_INTERFACE_ID NUMBER,
	P_NEEDS_INVOICE_APPROVAL VARCHAR2,
	P_COMMIT VARCHAR2
	) RETURN INTEGER IS
 RETURN_ INTEGER;
   BEGIN
      RETURN_ := SYS.SQLJUTL.BOOL2INT(APPS.AP_IMPORT_INVOICES_PKG.IMPORT_INVOICES(P_BATCH_NAME,
	P_GL_DATE,
	P_HOLD_CODE,
	P_HOLD_REASON,
	P_COMMIT_CYCLES,
	P_SOURCE,
	P_GROUP_ID,
	P_CONC_REQUEST_ID,
	P_DEBUG_SWITCH,
	P_ORG_ID,
	P_BATCH_ERROR_FLAG,
	P_INVOICES_FETCHED,
	P_INVOICES_CREATED,
	P_TOTAL_INVOICE_AMOUNT,
	P_PRINT_BATCH,
	P_CALLING_SEQUENCE,
	P_INVOICE_INTERFACE_ID,
	P_NEEDS_INVOICE_APPROVAL,
	P_COMMIT
	));
      return RETURN_;
   END ap_import_invoices_pkg$import;

END BPEL_OA_LAUNCHAUTOINVOICEAPI;
/
show errors
exit
