<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_GetSegment2FromEBS"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/WSH_OTM_SYNC_ITEM_PKG/GET_EBS_ITEM_INFO/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/apps/wsh/outbound/ref/WshSendItemRefDataToOtm"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns5 ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/getEBSItemInfo/"
                xmlns:ns1="http://xmlns.oracle.com/apps/otm"
                xmlns:ref="http://xmlns.oracle.com/apps/wsh/outbound/util/WshOtmGlobalOutbound"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/OTMDEC/SendItemRefDataToOtm/DB_GetSegment2FromEBS">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../partnerWsdls/getEBSItemInfo.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/WSH_OTM_SYNC_ITEM_PKG/GET_EBS_ITEM_INFO/"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_GetSegment2FromEBS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_GetSegment2FromEBS"/>
        <oracle-xsl-mapper:param name="Invoke_GetSegementCode_DB_GetSegment2FromEBS_OutputVariable.OutputParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WshSendItemRefDataToOtm.wsdl"/>
        <oracle-xsl-mapper:rootElement name="WshSendItemRefDataToOtmProcessResponse"
                                       namespace="http://xmlns.oracle.com/apps/wsh/outbound/ref/WshSendItemRefDataToOtm"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE DEC 22 04:46:46 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="Invoke_GetSegementCode_DB_GetSegment2FromEBS_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <tns:WshSendItemRefDataToOtmProcessResponse>
      <tns:result>
        <ref:transmissionId>
          <xsl:value-of select="/ns0:OutputParameters/X_TRANSMISSION_ID"/>
        </ref:transmissionId>
        <ns1:Transmission>
          <ns1:TransmissionBody>
            <xsl:for-each select="/ns0:OutputParameters/GET_EBS_ITEM_INFO/GET_EBS_ITEM_INFO_ITEM">
              <xsl:variable name="id" select="ITEM/ITEMGID/GID/XID"/>
              <ns1:GLogXMLElement>
                <ns1:ItemMaster>
                  <xsl:for-each select="ITEM">
                    <ns1:Item>
                      <ns1:TransactionCode>
                        <xsl:value-of select="TRANSACTIONCODE"/>
                      </ns1:TransactionCode>
                      <ns1:ItemGid>
                        <ns1:Gid>
                          <ns1:DomainName>
                            <xsl:value-of select="ITEMGID/GID/DOMAINNAME"/>
                          </ns1:DomainName>
                          <ns1:Xid>
                            <xsl:value-of select="ITEMGID/GID/XID"/>
                          </ns1:Xid>
                        </ns1:Gid>
                      </ns1:ItemGid>
                      <ns1:ItemName>
                        <xsl:value-of select="ITEMNAME"/>
                      </ns1:ItemName>
                      <ns1:Description>
                        <xsl:value-of select="DESCRIPTION"/>
                      </ns1:Description>
                      <xsl:for-each select="$Invoke_GetSegementCode_DB_GetSegment2FromEBS_OutputVariable.OutputParameters/ns5:OutputParameters/ns5:P_ORG_ITEM/ns5:P_ORG_ITEM_ITEM[ns5:ORG_ID_ITEM_ID=$id]">
                        <!--ns1:STCCGid>
                          <ns1:Gid>
                            <ns1:Xid>
                              <xsl:value-of select="ns5:SEGMENT1"/>
                            </ns1:Xid>
                            <ns1:DomainName>SMG</ns1:DomainName>
                          </ns1:Gid>
                        </ns1:STCCGid-->
                        <xsl:choose>
                          <xsl:when test="ns5:SEGMENT1 != ''">
                            <ns1:STCCGid>
                              <ns1:Gid>
                                <ns1:Xid>
                                  <xsl:value-of select="ns5:SEGMENT1"/>
                                </ns1:Xid>
                                <ns1:DomainName>SMG</ns1:DomainName>
                              </ns1:Gid>
                            </ns1:STCCGid>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </ns1:Item>
                  </xsl:for-each>
                  <xsl:for-each select="PACKAGING">
                    <ns1:Packaging>
                      <ns1:PackagedItemGid>
                        <ns1:Gid>
                          <ns1:DomainName>
                            <xsl:value-of select="PACKAGEDITEMGID/GID/DOMAINNAME"/>
                          </ns1:DomainName>
                          <ns1:Xid>
                            <xsl:value-of select="PACKAGEDITEMGID/GID/XID"/>
                          </ns1:Xid>
                        </ns1:Gid>
                      </ns1:PackagedItemGid>
                      <ns1:Description>
                        <xsl:value-of select="DESCRIPTION"/>
                      </ns1:Description>
                      <xsl:for-each select="$Invoke_GetSegementCode_DB_GetSegment2FromEBS_OutputVariable.OutputParameters/ns5:OutputParameters/ns5:P_ORG_ITEM/ns5:P_ORG_ITEM_ITEM[ns5:ORG_ID_ITEM_ID=$id]">
                        <!--ns1:PackageShipUnitLWH>
                          <ns1:Length>
                            <ns1:LengthValue>
                              <xsl:value-of select="ns5:UNIT_LENGTH"/>
                            </ns1:LengthValue>
                            <ns1:LengthUOMGid>
                              <ns1:Gid>
                                <ns1:Xid>
                                  <xsl:value-of select="ns5:DIMENSION_UOM_CODE"/>
                                </ns1:Xid>
                              </ns1:Gid>
                            </ns1:LengthUOMGid>
                          </ns1:Length>
                        </ns1:PackageShipUnitLWH-->
                        <xsl:choose>
                          <xsl:when test="ns5:DIMENSION_UOM_CODE != '' and ns5:UNIT_LENGTH != ''">
                            <ns1:PackageShipUnitLWH>
                              <ns1:Length>
                                <ns1:LengthValue>
                                  <xsl:value-of select="ns5:UNIT_LENGTH"/>
                                </ns1:LengthValue>
                                <ns1:LengthUOMGid>
                                  <ns1:Gid>
                                    <ns1:Xid>
                                      <xsl:value-of select="ns5:DIMENSION_UOM_CODE"/>
                                    </ns1:Xid>
                                  </ns1:Gid>
                                </ns1:LengthUOMGid>
                              </ns1:Length>
                            </ns1:PackageShipUnitLWH>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </ns1:Packaging>
                  </xsl:for-each>
                </ns1:ItemMaster>
              </ns1:GLogXMLElement>
            </xsl:for-each>
          </ns1:TransmissionBody>
        </ns1:Transmission>
        <ref:returnStatus>
          <xsl:value-of select="/ns0:OutputParameters/X_RETURN_STATUS"/>
        </ref:returnStatus>
      </tns:result>
    </tns:WshSendItemRefDataToOtmProcessResponse>
  </xsl:template>
</xsl:stylesheet>
