<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/Db_Insert_NSSEAAPIWorkOrder"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAM/1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns6="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAO/1.0" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/jms/DV1_Application/NSSEA_SubscribeEBizJobDetails_EBiz_QMOS_ABF/JMS_DEQ_JobDetails"
                xmlns:ns3="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns8="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns9="http://xmlns.oracle.com/pcbpel/adapter/db/DV1_Application/NSSEA_SubscribeEBizJobDetails_EBiz_QMOS_ABF/Db_Insert_NSSEAAPIWorkOrder">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_DEQ_JobDetails.wsdl"/>
        <oracle-xsl-mapper:rootElement name="BatchJobAddRq"
                                       namespace="http://nucor.eia.com/AO/Ebiz/D2S/BatchJobAM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMS_DEQ_JobDetails.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="parameterVar"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Db_Insert_NSSEAAPIWorkOrder.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiWorkOrderCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Db_Insert_NSSEAAPIWorkOrder"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE FEB 21 07:14:38 PST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="parameterVar"/>
  <xsl:template match="/">
    <tns:ApiWorkOrderCollection>
      <xsl:for-each select="/ns0:BatchJobAddRq/ns6:BatchJobDetails">
        <xsl:if test='((ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS[1.0]/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES[1.0]/ns6:BATCH_RESOURCES[1.0]/ns6:RESOURCES = "RM1") or ((ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS[1.0]/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES[1.0]/ns6:BATCH_RESOURCES[1.0]/ns6:RESOURCES = "RM2") or (ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS[1.0]/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES[1.0]/ns6:BATCH_RESOURCES[1.0]/ns6:RESOURCES = "TPOST")) or (ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS[1.0]/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES[1.0]/ns6:BATCH_RESOURCES[1.0]/ns6:RESOURCES = "CASTER" and ns6:GME_SO_DTLS_TABS/ns6:GME_SO_DTLS_TABS[1.0]/ns6:SO_NUM != ""))'>
          <tns:ApiWorkOrder>
            <tns:id>
              <xsl:value-of select='oraext:sequence-next-val ("SEQ_API_WORK_ORDER_ID", $parameterVar/ns1:parameters/ns1:item/ns1:value )'/>
            </tns:id>
            <tns:cycle>TBD</tns:cycle>
            <tns:productGroup>TBD</tns:productGroup>
            <!--xsl:choose>
            <xsl:when test='ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS[1]/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES[1]/ns6:BATCH_RESOURCES[1]/ns6:RESOURCES = "RM1"'>
              <tns:millId>PA</tns:millId>
            </xsl:when>
            <xsl:when test='ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS[1]/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES[1]/ns6:BATCH_RESOURCES[1]/ns6:RESOURCES = "RM2"'>
              <tns:millId>PB</tns:millId>
            </xsl:when>
            <xsl:otherwise>
              <tns:millId></tns:millId>
            </xsl:otherwise>
          </xsl:choose-->
            <xsl:choose>
              <xsl:when test='ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)]/ns6:Item_Type = "NUC_HWY PROD"'>
                <tns:millId>GF</tns:millId>
              </xsl:when>
              <xsl:otherwise>
                <xsl:choose>
                  <xsl:when test='ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)]/ns6:Item_Type = "NUC_BILLET"'>
                    <tns:millId>CC</tns:millId>
                  </xsl:when>
                  <xsl:otherwise>
                    <xsl:choose>
                      <xsl:when test='(ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)]/ns6:Item_Type = "NUC_HOT ROLL BUNDLE"  or  ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)]/ns6:Item_Type = "NUC_WIRE ROD"     ) and ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS[1.0]/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES[1.0]/ns6:BATCH_RESOURCES[1.0]/ns6:RESOURCES = "RM1"'>
                        <tns:millId>PA</tns:millId>
                      </xsl:when>
                      <xsl:otherwise>
                        <xsl:choose>
                          <xsl:when test='(ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)]/ns6:Item_Type = "NUC_HOT ROLL BUNDLE" or  ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)]/ns6:Item_Type = "NUC_WIRE ROD"  ) and ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS[1.0]/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES[1.0]/ns6:BATCH_RESOURCES[1.0]/ns6:RESOURCES = "RM2"'>
                            <tns:millId>PB</tns:millId>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:otherwise>
                    </xsl:choose>
                  </xsl:otherwise>
                </xsl:choose>
              </xsl:otherwise>
            </xsl:choose>
            <!--tns:millId>
            <xsl:value-of select="ns6:GME_BATCH_STEPS/ns6:GME_BATCH_STEPS/ns6:BATCH_ACTIVITIES/ns6:BATCH_ACTIVITIES/ns6:BATCH_RESOURCES/ns6:RESOURCES"/>
          </tns:millId-->
            <tns:partCode>
              <xsl:value-of select="ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)][1.0]/ns6:ITEM_NO"/>
            </tns:partCode>
            <xsl:if test="ns6:BATCH_NO">
              <tns:orderNumber>
                <xsl:value-of select="ns6:BATCH_NO"/>
              </tns:orderNumber>
            </xsl:if>
            <xsl:if test="ns6:PLAN_START_DATE">
              <tns:startDate>
                <xsl:value-of select="ns6:PLAN_START_DATE"/>
              </tns:startDate>
            </xsl:if>
            <xsl:if test="ns6:PLAN_CMPLT_DATE">
              <tns:endDate>
                <xsl:value-of select="ns6:PLAN_CMPLT_DATE"/>
              </tns:endDate>
            </xsl:if>
            <tns:scheduledTons>
              <xsl:value-of select="oraext:query-database (concat (&quot;SELECT ROUND ( inv_convert.inv_um_convert_new (&quot;,ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)][1.0]/ns6:INVENTORY_ITEM_ID, &quot;,null,&quot;, ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)][1.0]/ns6:PLAN_QTY, &quot;,'&quot;, ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)][1.0]/ns6:DTL_UM, &quot;','TON',null,null, 'W')) result FROM DUAL&quot; ), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
            </tns:scheduledTons>
            <tns:binLocation>
              <xsl:value-of select="ns6:GME_MATERIAL_DETAILS/ns6:GME_MATERIAL_DETAILS[(ns6:LINE_TYPE=1)][1.0]/ns6:ITEM_LOCATOR"/>
            </tns:binLocation>
            <xsl:if test="ns6:CUST_NUM">
              <tns:customerNumber>
                <xsl:value-of select="ns6:CUST_NUM"/>
              </tns:customerNumber>
            </xsl:if>
            <xsl:if test="ns6:CUST_NAME">
              <tns:customerName>
                <xsl:value-of select="substring(ns6:CUST_NAME,1,30)"/>
              </tns:customerName>
            </xsl:if>
            <tns:userId>SOAUSER</tns:userId>
            <tns:processed>N</tns:processed>
            <tns:processDate/>
            <tns:createDate>
              <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:createDate>
            <xsl:choose>
              <xsl:when test='/ns0:BatchJobAddRq/ns6:BatchJobDetails[1.0]/ns6:BATCH_STATUS = "Cancelled" or /ns0:BatchJobAddRq/ns6:BatchJobDetails[1.0]/ns6:TERMINATED_IND = 1'>
                <tns:jobStatus>D</tns:jobStatus>
              </xsl:when>
              <xsl:otherwise>
                <tns:jobStatus>P</tns:jobStatus>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:if test="ns6:CONCAT_NOTES">
              <tns:note>
                <xsl:value-of select="ns6:CONCAT_NOTES"/>
              </tns:note>
            </xsl:if>
          </tns:ApiWorkOrder>
        </xsl:if>
      </xsl:for-each>
    </tns:ApiWorkOrderCollection>
  </xsl:template>
</xsl:stylesheet>
