<wsdl:definitions
     name="JMS_Publish_Receipt"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/NUCOR/NUC_PublishPOReceipt_EBiz_ABF/JMS_Publish_Receipt"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/NUCOR/NUC_PublishPOReceipt_EBiz_ABF/JMS_Publish_Receipt"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:imp1="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0"
    >
  <plt:partnerLinkType name="Produce_Message_plt" >
    <plt:role name="Produce_Message_role" >
      <plt:portType name="tns:Produce_Message_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.eia.com/AO/EBiz/P2P/ReceiptABM/1.0" schemaLocation="oramds:/apps/EIAMetadata/AO/EBiz/P2P/V1.0/ReceiptABM.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Produce_Message_msg">
        <wsdl:part name="body" element="imp1:QueryReceiptResponseMessage"/>
    </wsdl:message>
    <wsdl:portType name="Produce_Message_ptt">
        <wsdl:operation name="Produce_Message">
            <wsdl:input message="tns:Produce_Message_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
