<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:submitrequestAMObj="http://xmlns.eia.com/AO/EBiz/common/SubmitRequestAM/1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_SubmitRequest"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd db submitrequestAMObj xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/apps/Nucor/NUC_EBizSubmitRequest_ABS/OA_SubmitRequest"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/common/SubmitRequestAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns2="http://xmlns.eia.com/ABS/EBiz/common/SubmitRequestABS/1.0"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../OA_SubmitRequest.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_SubmitRequest"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/common/SubmitRequestABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SubmitRequestResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/common/SubmitRequestAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN OCT 02 17:42:40 IST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <submitrequestAMObj:SubmitRequestResponseMessage>
      <submitrequestAMObj:OperationResult>
        <ns3:Stats>
          <xsl:value-of select="/db:OutputParameters/db:RETURN_CODE"/>
        </ns3:Stats>
        <ns3:Errors>
          <ns3:OperationResultError>
            <xsl:value-of select="/db:OutputParameters/db:RETURN_MESSAGE"/>
          </ns3:OperationResultError>
        </ns3:Errors>
        <ns3:Warnings>
          <ns3:OperationResultWarning>
            <xsl:value-of select="/db:OutputParameters/db:RETURN_MESSAGE"/>
          </ns3:OperationResultWarning>
        </ns3:Warnings>        
      </submitrequestAMObj:OperationResult>
    </submitrequestAMObj:SubmitRequestResponseMessage>
  </xsl:template>
</xsl:stylesheet>
