<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:submitrequestAMObj="http://xmlns.eia.com/AO/EBiz/common/SubmitRequestAM/1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_SubmitRequest"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl submitrequestAMObj db oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/SubmitRequestAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.eia.com/ABS/EBiz/common/SubmitRequestABS/1.0"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/apps/Nucor/NUC_EBizSubmitRequest_ABS/OA_SubmitRequest"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/common/SubmitRequestABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SubmitRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/common/SubmitRequestAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../OA_SubmitRequest.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_SubmitRequest"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN OCT 02 13:08:32 IST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:variable name="varEscapeXml"
                  select='oraext:query-database ("select chr(0) escape_xml from dual", false ( ), false ( ), "jdbc/ebsapps" )'/>
    <db:InputParameters>
      <db:APPLICATION>
        <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Application"/>
      </db:APPLICATION>
      <db:PROGRAM>
        <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Program"/>
      </db:PROGRAM>
      <db:DESCRIPTION>
        <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Description"/>
      </db:DESCRIPTION>
      <db:START_TIME>
        <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:StartTime"/>
      </db:START_TIME>
      <db:SUB_REQUEST>
        <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:SubRequest"/>
      </db:SUB_REQUEST>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument1">
          <db:ARGUMENT1>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument1"/>
          </db:ARGUMENT1>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT1>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT1>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument2">
          <db:ARGUMENT2>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument2"/>
          </db:ARGUMENT2>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT2>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT2>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument3">
          <db:ARGUMENT3>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument3"/>
          </db:ARGUMENT3>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT3>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT3>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument4">
          <db:ARGUMENT4>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument4"/>
          </db:ARGUMENT4>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT4>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT4>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument5">
          <db:ARGUMENT5>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument5"/>
          </db:ARGUMENT5>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT5>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT5>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument6">
          <db:ARGUMENT6>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument6"/>
          </db:ARGUMENT6>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT6>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT6>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument7">
          <db:ARGUMENT7>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument7"/>
          </db:ARGUMENT7>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT7>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT7>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument8">
          <db:ARGUMENT8>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument8"/>
          </db:ARGUMENT8>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT8>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT8>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument9">
          <db:ARGUMENT9>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument9"/>
          </db:ARGUMENT9>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT9>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT9>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument10">
          <db:ARGUMENT10>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument10"/>
          </db:ARGUMENT10>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT10>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT10>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument11">
          <db:ARGUMENT11>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument11"/>
          </db:ARGUMENT11>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT11>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT11>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument12">
          <db:ARGUMENT12>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument12"/>
          </db:ARGUMENT12>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT12>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT12>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument13">
          <db:ARGUMENT13>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument13"/>
          </db:ARGUMENT13>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT13>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT13>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument14">
          <db:ARGUMENT14>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument14"/>
          </db:ARGUMENT14>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT14>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT14>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument15">
          <db:ARGUMENT15>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument15"/>
          </db:ARGUMENT15>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT15>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT15>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument16">
          <db:ARGUMENT16>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument16"/>
          </db:ARGUMENT16>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT16>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT16>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument17">
          <db:ARGUMENT17>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument17"/>
          </db:ARGUMENT17>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT17>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT17>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument18">
          <db:ARGUMENT18>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument18"/>
          </db:ARGUMENT18>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT18>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT18>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument19">
          <db:ARGUMENT19>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument19"/>
          </db:ARGUMENT19>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT19>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT19>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument20">
          <db:ARGUMENT20>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument20"/>
          </db:ARGUMENT20>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT20>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT20>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument21">
          <db:ARGUMENT21>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument21"/>
          </db:ARGUMENT21>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT21>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT21>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument22">
          <db:ARGUMENT22>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument22"/>
          </db:ARGUMENT22>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT22>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT22>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument23">
          <db:ARGUMENT23>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument23"/>
          </db:ARGUMENT23>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT23>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT23>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument24">
          <db:ARGUMENT24>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument24"/>
          </db:ARGUMENT24>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT24>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT24>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument25">
          <db:ARGUMENT25>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument25"/>
          </db:ARGUMENT25>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT25>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT25>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument26">
          <db:ARGUMENT26>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument26"/>
          </db:ARGUMENT26>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT26>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT26>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument27">
          <db:ARGUMENT27>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument27"/>
          </db:ARGUMENT27>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT27>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT27>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument28">
          <db:ARGUMENT28>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument28"/>
          </db:ARGUMENT28>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT28>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT28>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument29">
          <db:ARGUMENT29>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument29"/>
          </db:ARGUMENT29>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT29>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT29>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument30">
          <db:ARGUMENT30>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument30"/>
          </db:ARGUMENT30>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT30>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT30>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument31">
          <db:ARGUMENT31>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument31"/>
          </db:ARGUMENT31>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT31>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT31>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument32">
          <db:ARGUMENT32>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument32"/>
          </db:ARGUMENT32>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT32>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT32>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument33">
          <db:ARGUMENT33>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument33"/>
          </db:ARGUMENT33>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT33>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT33>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument34">
          <db:ARGUMENT34>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument34"/>
          </db:ARGUMENT34>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT34>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT34>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument35">
          <db:ARGUMENT35>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument35"/>
          </db:ARGUMENT35>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT35>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT35>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument36">
          <db:ARGUMENT36>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument36"/>
          </db:ARGUMENT36>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT36>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT36>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument37">
          <db:ARGUMENT37>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument37"/>
          </db:ARGUMENT37>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT37>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT37>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument38">
          <db:ARGUMENT38>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument38"/>
          </db:ARGUMENT38>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT38>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT38>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument39">
          <db:ARGUMENT39>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument39"/>
          </db:ARGUMENT39>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT39>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT39>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument40">
          <db:ARGUMENT40>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument40"/>
          </db:ARGUMENT40>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT40>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT40>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument41">
          <db:ARGUMENT41>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument41"/>
          </db:ARGUMENT41>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT41>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT41>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument42">
          <db:ARGUMENT42>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument42"/>
          </db:ARGUMENT42>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT42>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT42>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument43">
          <db:ARGUMENT43>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument43"/>
          </db:ARGUMENT43>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT43>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT43>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument44">
          <db:ARGUMENT44>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument44"/>
          </db:ARGUMENT44>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT44>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT44>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument45">
          <db:ARGUMENT45>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument45"/>
          </db:ARGUMENT45>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT45>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT45>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument46">
          <db:ARGUMENT46>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument46"/>
          </db:ARGUMENT46>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT46>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT46>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument47">
          <db:ARGUMENT47>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument47"/>
          </db:ARGUMENT47>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT47>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT47>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument48">
          <db:ARGUMENT48>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument48"/>
          </db:ARGUMENT48>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT48>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT48>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument49">
          <db:ARGUMENT49>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument49"/>
          </db:ARGUMENT49>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT49>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT49>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument50">
          <db:ARGUMENT50>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument50"/>
          </db:ARGUMENT50>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT50>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT50>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument51">
          <db:ARGUMENT51>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument51"/>
          </db:ARGUMENT51>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT51>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT51>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument52">
          <db:ARGUMENT52>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument52"/>
          </db:ARGUMENT52>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT52>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT52>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument53">
          <db:ARGUMENT53>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument53"/>
          </db:ARGUMENT53>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT53>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT53>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument54">
          <db:ARGUMENT54>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument54"/>
          </db:ARGUMENT54>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT54>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT54>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument55">
          <db:ARGUMENT55>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument55"/>
          </db:ARGUMENT55>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT55>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT55>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument56">
          <db:ARGUMENT56>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument56"/>
          </db:ARGUMENT56>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT56>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT56>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument57">
          <db:ARGUMENT57>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument57"/>
          </db:ARGUMENT57>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT57>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT57>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument58">
          <db:ARGUMENT58>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument18"/>
          </db:ARGUMENT58>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT58>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT58>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument59">
          <db:ARGUMENT59>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument59"/>
          </db:ARGUMENT59>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT59>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT59>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument60">
          <db:ARGUMENT60>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument60"/>
          </db:ARGUMENT60>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT60>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT60>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument61">
          <db:ARGUMENT61>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument61"/>
          </db:ARGUMENT61>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT61>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT61>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument62">
          <db:ARGUMENT62>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument62"/>
          </db:ARGUMENT62>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT62>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT62>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument63">
          <db:ARGUMENT63>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument63"/>
          </db:ARGUMENT63>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT63>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT63>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument64">
          <db:ARGUMENT64>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument64"/>
          </db:ARGUMENT64>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT64>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT64>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument65">
          <db:ARGUMENT65>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument65"/>
          </db:ARGUMENT65>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT65>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT65>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument66">
          <db:ARGUMENT66>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument66"/>
          </db:ARGUMENT66>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT66>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT66>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument67">
          <db:ARGUMENT67>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument67"/>
          </db:ARGUMENT67>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT67>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT67>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument68">
          <db:ARGUMENT68>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument68"/>
          </db:ARGUMENT68>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT68>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT68>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument69">
          <db:ARGUMENT69>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument69"/>
          </db:ARGUMENT69>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT69>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT69>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument70">
          <db:ARGUMENT70>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument70"/>
          </db:ARGUMENT70>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT70>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT70>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument71">
          <db:ARGUMENT71>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument71"/>
          </db:ARGUMENT71>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT71>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT71>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument72">
          <db:ARGUMENT72>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument72"/>
          </db:ARGUMENT72>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT72>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT72>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument73">
          <db:ARGUMENT73>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument73"/>
          </db:ARGUMENT73>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT73>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT73>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument74">
          <db:ARGUMENT74>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument74"/>
          </db:ARGUMENT74>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT74>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT74>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument75">
          <db:ARGUMENT75>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument75"/>
          </db:ARGUMENT75>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT75>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT75>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument76">
          <db:ARGUMENT76>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument76"/>
          </db:ARGUMENT76>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT76>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT76>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument77">
          <db:ARGUMENT77>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument77"/>
          </db:ARGUMENT77>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT77>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT77>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument78">
          <db:ARGUMENT78>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument78"/>
          </db:ARGUMENT78>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT78>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT78>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument79">
          <db:ARGUMENT79>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument79"/>
          </db:ARGUMENT79>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT79>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT79>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument80">
          <db:ARGUMENT80>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument80"/>
          </db:ARGUMENT80>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT80>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT80>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument81">
          <db:ARGUMENT81>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument81"/>
          </db:ARGUMENT81>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT81>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT81>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument82">
          <db:ARGUMENT82>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument82"/>
          </db:ARGUMENT82>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT82>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT82>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument83">
          <db:ARGUMENT83>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument83"/>
          </db:ARGUMENT83>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT83>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT83>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument84">
          <db:ARGUMENT84>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument84"/>
          </db:ARGUMENT84>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT84>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT84>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument85">
          <db:ARGUMENT85>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument85"/>
          </db:ARGUMENT85>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT85>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT85>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument86">
          <db:ARGUMENT86>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument86"/>
          </db:ARGUMENT86>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT86>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT86>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument87">
          <db:ARGUMENT87>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument87"/>
          </db:ARGUMENT87>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT87>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT87>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument88">
          <db:ARGUMENT88>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument88"/>
          </db:ARGUMENT88>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT88>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT88>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument89">
          <db:ARGUMENT89>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument89"/>
          </db:ARGUMENT89>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT89>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT89>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument90">
          <db:ARGUMENT90>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument90"/>
          </db:ARGUMENT90>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT90>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT90>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument91">
          <db:ARGUMENT91>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument91"/>
          </db:ARGUMENT91>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT91>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT91>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument92">
          <db:ARGUMENT92>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument92"/>
          </db:ARGUMENT92>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT92>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT92>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument93">
          <db:ARGUMENT93>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument93"/>
          </db:ARGUMENT93>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT93>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT93>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument94">
          <db:ARGUMENT94>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument94"/>
          </db:ARGUMENT94>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT94>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT94>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument95">
          <db:ARGUMENT95>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument95"/>
          </db:ARGUMENT95>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT95>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT95>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument96">
          <db:ARGUMENT96>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument96"/>
          </db:ARGUMENT96>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT96>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT96>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument97">
          <db:ARGUMENT97>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument97"/>
          </db:ARGUMENT97>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT97>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT97>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument98">
          <db:ARGUMENT98>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument98"/>
          </db:ARGUMENT98>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT98>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT98>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument99">
          <db:ARGUMENT99>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument99"/>
          </db:ARGUMENT99>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT99>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT99>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument100">
          <db:ARGUMENT100>
            <xsl:value-of select="/submitrequestAMObj:SubmitRequestMessage/submitrequestAMObj:SubmitRequest/ns4:Argument100"/>
          </db:ARGUMENT100>
        </xsl:when>
        <xsl:otherwise>
          <db:ARGUMENT100>
            <xsl:value-of select="$varEscapeXml"/>
          </db:ARGUMENT100>
        </xsl:otherwise>
      </xsl:choose>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>
