<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.eia.com/CommonLogging"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm utl oraxsl"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns16="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns17="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns2="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns1="http://xmlns.eia.com/ABS/EBiz/PurchaseOrderABS/1.0"
                xmlns:ns11="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns12="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns14="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns15="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/PurchaseOrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryPurchaseOrderRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/PurchaseOrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ProcessHeader" namespace="http://xmlns.eia.com/EO/Common/1.0"/>
        <oracle-xsl-mapper:param name="EIA_HEADER_MESSAGE"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/Infrastracture/wsdls/V1.0/CommonLogging.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Input" namespace="http://xmlns.eia.com/CommonLogging"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED NOV 25 08:33:45 PST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="EIA_HEADER_MESSAGE"/>
  <xsl:template match="/">
    <tns:Input>
      <xsl:choose>
        <xsl:when test="/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:TransactionIDREF !=''">
          <tns:TransactionId>
            <xsl:value-of select="/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:TransactionIDREF"/>
          </tns:TransactionId>
        </xsl:when>
        <xsl:otherwise>
          <tns:TransactionId>
            <xsl:value-of select="$EIA_HEADER_MESSAGE/core:ProcessHeader/core:ProcessInstanceID"/>
          </tns:TransactionId>
        </xsl:otherwise>
      </xsl:choose>
      <tns:ProjectName>NextGen</tns:ProjectName>
      <xsl:choose>
        <xsl:when test="/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:ComponentID != ''">
          <tns:ComponentId>
            <xsl:value-of select="/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:ComponentID"/>
          </tns:ComponentId>
        </xsl:when>
        <xsl:otherwise>
          <tns:ComponentId>QueryPayment</tns:ComponentId>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:TransactionName">
          <tns:TransactionName>
            <xsl:value-of select='/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:TransactionName != ""'/>
          </tns:TransactionName>
        </xsl:when>
        <xsl:otherwise>
          <tns:TransactionName>PurchaseOrder</tns:TransactionName>
        </xsl:otherwise>
      </xsl:choose>
      <tns:ProcessName>
        <xsl:value-of select="$EIA_HEADER_MESSAGE/core:ProcessHeader/core:ProcessName"/>
      </tns:ProcessName>
      <tns:LoggingSystem>1</tns:LoggingSystem>
      <xsl:choose>
        <xsl:when test="/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:Source">
          <tns:SourceSystem>
            <xsl:value-of select='/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:Source != ""'/>
          </tns:SourceSystem>
        </xsl:when>
        <xsl:otherwise>
          <tns:SourceSystem/>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:Target">
          <tns:TargetSystem>
            <xsl:value-of select='/ns0:QueryPurchaseOrderRequestMessage/ns5:HeaderRq/ns5:Target != ""'/>
          </tns:TargetSystem>
        </xsl:when>
        <xsl:otherwise>
          <tns:TargetSystem/>
        </xsl:otherwise>
      </xsl:choose>
      <tns:LogType>4</tns:LogType>
      <!--tns:MessageCode>BMG-003</tns:MessageCode-->
      <tns:MessageDescription>Temp</tns:MessageDescription>
      <tns:TransactionStatus>1</tns:TransactionStatus>
      <tns:CreatedBy>SOA</tns:CreatedBy>
      <tns:UpdatedBy>SOA</tns:UpdatedBy>
    </tns:Input>
  </xsl:template>
</xsl:stylesheet>
