<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel2="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:MYORACLE="http://xmlns.oracle.com/xdb/MYORACLE"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl MYORACLE xsd bpws xp20 mhdr bpel2 oraext dvm hwf med ids bpm xdk xref ora socket ldap"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/MYORACLE_EMAIL_NOTIFICATION_OBJ.xsd"/>
        <oracle-xsl-mapper:rootElement name="EMAIL_NOTIFICATION_OBJ" namespace="http://xmlns.oracle.com/xdb/MYORACLE"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../xsd/MYORACLE_EMAIL_NOTIFICATION_OBJ.xsd"/>
        <oracle-xsl-mapper:rootElement name="EMAIL_NOTIFICATION_OBJ" namespace="http://xmlns.oracle.com/xdb/MYORACLE"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUN 19 20:00:23 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <MYORACLE:EMAIL_NOTIFICATION_OBJ>
      <AUDIT_STEP_LOG>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_STEP_LOG/@xsi:nil"/>
        </xsl:attribute>
        <xsl:for-each select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_STEP_LOG/AUDIT_STEP_LOG_ITEM">
          <AUDIT_STEP_LOG_ITEM>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="@xsi:nil"/>
            </xsl:attribute>
            <STEP_LOG_ID>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="STEP_LOG_ID/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="STEP_LOG_ID"/>
            </STEP_LOG_ID>
            <LOG_ID>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="LOG_ID/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="LOG_ID"/>
            </LOG_ID>
            <COMPONENT_ID>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="COMPONENT_ID/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="COMPONENT_ID"/>
            </COMPONENT_ID>
            <MESSAGE_SOURCE_SYSTEM>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="MESSAGE_SOURCE_SYSTEM/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="MESSAGE_SOURCE_SYSTEM"/>
            </MESSAGE_SOURCE_SYSTEM>
            <PROCESS_NAME>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="PROCESS_NAME/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="PROCESS_NAME"/>
            </PROCESS_NAME>
            <LOG_TYPE>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="LOG_TYPE/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="LOG_TYPE"/>
            </LOG_TYPE>
            <MESSAGE_CODE>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="MESSAGE_CODE/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="MESSAGE_CODE"/>
            </MESSAGE_CODE>
            <MESSAGE_DESCRIPTION>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="MESSAGE_DESCRIPTION/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="MESSAGE_DESCRIPTION"/>
            </MESSAGE_DESCRIPTION>
            <CREATED_TIME>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="CREATED_TIME/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="CREATED_TIME"/>
            </CREATED_TIME>
            <V_ATTRIBUTE1>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="V_ATTRIBUTE1/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="V_ATTRIBUTE1"/>
            </V_ATTRIBUTE1>
            <V_ATTRIBUTE2>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="V_ATTRIBUTE2/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="V_ATTRIBUTE2"/>
            </V_ATTRIBUTE2>
            <N_ATTRIBUTE1>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="N_ATTRIBUTE1/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="N_ATTRIBUTE1"/>
            </N_ATTRIBUTE1>
            <N_ATTRIBUTE2>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="N_ATTRIBUTE2/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="N_ATTRIBUTE2"/>
            </N_ATTRIBUTE2>
          </AUDIT_STEP_LOG_ITEM>
        </xsl:for-each>
      </AUDIT_STEP_LOG>
      <AUDIT_LOG>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/@xsi:nil"/>
        </xsl:attribute>
        <LOG_ID>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/LOG_ID/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/LOG_ID"/>
        </LOG_ID>
        <TRANSACTION_ID>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/TRANSACTION_ID/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/TRANSACTION_ID"/>
        </TRANSACTION_ID>
        <PROJECT_NAME>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/PROJECT_NAME/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/PROJECT_NAME"/>
        </PROJECT_NAME>
        <TRANSACTION_NAME>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/TRANSACTION_NAME/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/TRANSACTION_NAME"/>
        </TRANSACTION_NAME>
        <SOURCE_SYSTEM>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/SOURCE_SYSTEM/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/SOURCE_SYSTEM"/>
        </SOURCE_SYSTEM>
        <TARGET_SYSTEM>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/TARGET_SYSTEM/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/TARGET_SYSTEM"/>
        </TARGET_SYSTEM>
        <TRANSACTION_STATUS>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/TRANSACTION_STATUS/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/TRANSACTION_STATUS"/>
        </TRANSACTION_STATUS>
        <CREATED_TIME>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/CREATED_TIME/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/CREATED_TIME"/>
        </CREATED_TIME>
        <CREATED_BY>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/CREATED_BY/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/CREATED_BY"/>
        </CREATED_BY>
        <UPDATED_TIME>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/UPDATED_TIME/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/UPDATED_TIME"/>
        </UPDATED_TIME>
        <UPDATED_BY>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/UPDATED_BY/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/UPDATED_BY"/>
        </UPDATED_BY>
        <V_ATTRIBUTE1>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/V_ATTRIBUTE1/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/V_ATTRIBUTE1"/>
        </V_ATTRIBUTE1>
        <V_ATTRIBUTE2>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/V_ATTRIBUTE2/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/V_ATTRIBUTE2"/>
        </V_ATTRIBUTE2>
        <N_ATTRIBUTE1>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/N_ATTRIBUTE1/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/N_ATTRIBUTE1"/>
        </N_ATTRIBUTE1>
        <N_ATTRIBUTE2>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/N_ATTRIBUTE2/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/AUDIT_LOG/N_ATTRIBUTE2"/>
        </N_ATTRIBUTE2>
      </AUDIT_LOG>
      <ACTOR_EMAIL_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/ACTOR_EMAIL_ID/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/ACTOR_EMAIL_ID"/>
      </ACTOR_EMAIL_ID>
      <FYI_EMAIL_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/FYI_EMAIL_ID/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/MYORACLE:EMAIL_NOTIFICATION_OBJ/FYI_EMAIL_ID"/>
      </FYI_EMAIL_ID>
    </MYORACLE:EMAIL_NOTIFICATION_OBJ>
  </xsl:template>
</xsl:stylesheet>