<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:eia="http://xmlns.eia.com/extensions/1.0" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/OA_CreateJournal_Sync" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns2="http://xmlns.eia.com/AO/EBiz/A2R/JournalAO/1.0" xmlns:tns="http://xmlns.eia.com/ABS/EBiz/A2R/JournalABS/1.0" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/apps/NucorSOA/NUC_EBizGLJE_ABS/OA_CreateJournal_Sync" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jeam="http://xmlns.eia.com/AO/EBiz/A2R/JournalAM/1.0" xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:core="http://xmlns.eia.com/EO/Common/1.0" xmlns:ns0="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns1="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns2 tns soap12 soap jeam mime wsdl core ns0 ns1 xsd top ns3 plt xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/A2R/JournalABS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateJournalRequestMessage" namespace="http://xmlns.eia.com/AO/EBiz/A2R/JournalAM/1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../OA_CreateJournal_Sync.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GlInterfaceCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/OA_CreateJournal_Sync"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED SEP 09 14:04:25 CDT 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <top:GlInterfaceCollection>
      <top:GlInterface>
        <top:status>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Status"/>
        </top:status>
        <top:ledgerId>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:LedgerId/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:LedgerId"/>
        </top:ledgerId>
        <top:accountingDate>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:AccountingDate"/>
        </top:accountingDate>
        <top:currencyCode>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:CurrencyCode"/>
        </top:currencyCode>
        <xsl:choose>
          <xsl:when test="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:DateCreated != &quot;&quot;">
            <top:dateCreated>
              <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:DateCreated"/>
            </top:dateCreated>
          </xsl:when>
          <xsl:otherwise>
            <top:dateCreated>
              <xsl:value-of select="xp20:current-dateTime()"/>
            </top:dateCreated>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:CreatedBy != &quot;&quot;">
            <top:createdBy>
              <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:CreatedBy"/>
            </top:createdBy>
          </xsl:when>
          <xsl:otherwise>
            <top:createdBy>
              <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm&quot;,&quot;DIVISION&quot;,&quot;Yamato&quot;,&quot;EBS_USER_ID&quot;,&quot;&quot;)"/>
            </top:createdBy>
          </xsl:otherwise>
        </xsl:choose>
        <top:actualFlag>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:ActualFlag"/>
        </top:actualFlag>
        <top:userJeCategoryName>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:UserJECategoryName"/>
        </top:userJeCategoryName>
        <top:userJeSourceName>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:UserJESourceName"/>
        </top:userJeSourceName>
        <top:currencyConversionDate>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:CurrencyConversionDate"/>
        </top:currencyConversionDate>
        <top:encumbranceTypeId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:EncumbranceTypeId"/>
        </top:encumbranceTypeId>
        <top:budgetVersionId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:BudgetVersionId"/>
        </top:budgetVersionId>
        <top:currencyConversionRate>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:CurrencyConversionRate"/>
        </top:currencyConversionRate>
        <top:averageJournalFlag>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:AverageJournalFlag"/>
        </top:averageJournalFlag>
        <top:originatingBalSegValue>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:OriginatingBalSegValue"/>
        </top:originatingBalSegValue>
        <top:segment1>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment1"/>
        </top:segment1>
        <top:segment2>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment2"/>
        </top:segment2>
        <top:segment3>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment3"/>
        </top:segment3>
        <top:segment4>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment4"/>
        </top:segment4>
        <top:segment5>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment5"/>
        </top:segment5>
        <top:segment6>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment6"/>
        </top:segment6>
        <top:segment7>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment7"/>
        </top:segment7>
        <top:segment8>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment8"/>
        </top:segment8>
        <top:segment9>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment9"/>
        </top:segment9>
        <top:segment10>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment10"/>
        </top:segment10>
        <top:segment11>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment11"/>
        </top:segment11>
        <top:segment12>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment12"/>
        </top:segment12>
        <top:segment13>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment13"/>
        </top:segment13>
        <top:segment14>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment14"/>
        </top:segment14>
        <top:segment15>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment15"/>
        </top:segment15>
        <top:segment16>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment16"/>
        </top:segment16>
        <top:segment17>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment17"/>
        </top:segment17>
        <top:segment18>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment18"/>
        </top:segment18>
        <top:segment19>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment19"/>
        </top:segment19>
        <top:segment20>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment20"/>
        </top:segment20>
        <top:segment21>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment21"/>
        </top:segment21>
        <top:segment22>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment22"/>
        </top:segment22>
        <top:segment23>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment23"/>
        </top:segment23>
        <top:segment24>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment24"/>
        </top:segment24>
        <top:segment25>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment25"/>
        </top:segment25>
        <top:segment26>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment26"/>
        </top:segment26>
        <top:segment27>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment27"/>
        </top:segment27>
        <top:segment28>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment28"/>
        </top:segment28>
        <top:segment29>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment29"/>
        </top:segment29>
        <top:segment30>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Segment30"/>
        </top:segment30>
        <top:enteredDr>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:EnteredDR/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:EnteredDR"/>
        </top:enteredDr>
        <top:enteredCr>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:EnteredCR/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:EnteredCR"/>
        </top:enteredCr>
        <top:accountedDr>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:AccountDR"/>
        </top:accountedDr>
        <top:accountedCr>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:AccountCR"/>
        </top:accountedCr>
        <top:transactionDate>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:TransactionDate"/>
        </top:transactionDate>
        <top:reference1>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference1"/>
        </top:reference1>
        <top:reference2>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference2"/>
        </top:reference2>
        <top:reference3>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference3"/>
        </top:reference3>
        <top:reference4>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference4"/>
        </top:reference4>
        <top:reference5>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference5"/>
        </top:reference5>
        <top:reference6>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference6"/>
        </top:reference6>
        <top:reference7>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference7"/>
        </top:reference7>
        <top:reference8>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference8"/>
        </top:reference8>
        <top:reference9>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference9"/>
        </top:reference9>
        <top:reference10>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference10"/>
        </top:reference10>
        <top:reference11>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference11"/>
        </top:reference11>
        <top:reference12>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference12"/>
        </top:reference12>
        <top:reference13>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference13"/>
        </top:reference13>
        <top:reference14>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference14"/>
        </top:reference14>
        <top:reference15>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference15"/>
        </top:reference15>
        <top:reference16>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference16"/>
        </top:reference16>
        <top:reference17>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference17"/>
        </top:reference17>
        <top:reference18>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference18"/>
        </top:reference18>
        <top:reference19>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference19"/>
        </top:reference19>
        <top:reference20>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference20"/>
        </top:reference20>
        <top:reference21>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference21"/>
        </top:reference21>
        <top:reference22>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference22"/>
        </top:reference22>
        <top:reference23>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference23"/>
        </top:reference23>
        <top:reference24>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference24"/>
        </top:reference24>
        <top:reference25>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference25"/>
        </top:reference25>
        <top:reference26>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference26"/>
        </top:reference26>
        <top:reference27>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference27"/>
        </top:reference27>
        <top:reference28>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference28"/>
        </top:reference28>
        <top:reference29>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference29"/>
        </top:reference29>
        <top:reference30>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Reference30"/>
        </top:reference30>
        <top:jeBatchId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:JEBatchId"/>
        </top:jeBatchId>
        <top:periodName>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:PeriodName/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:PeriodName"/>
        </top:periodName>
        <top:jeHeaderId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:JEHeaderId"/>
        </top:jeHeaderId>
        <top:jeLineNum>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:JELineNum"/>
        </top:jeLineNum>
        <top:chartOfAccountsId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:ChartOfAccountsId"/>
        </top:chartOfAccountsId>
        <top:functionalCurrencyCode>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:FunctionalCurrencyCode"/>
        </top:functionalCurrencyCode>
        <top:codeCombinationId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:CodeCombinationId"/>
        </top:codeCombinationId>
        <top:dateCreatedInGl>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:DateCreatedInGL"/>
        </top:dateCreatedInGl>
        <top:warningCode>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:WarningCode"/>
        </top:warningCode>
        <top:statusDescription>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:StatusDescription"/>
        </top:statusDescription>
        <top:statAmount>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:StatAmount"/>
        </top:statAmount>
        <top:groupId>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:GroupId/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:GroupId"/>
        </top:groupId>
        <top:requestId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:RequestId"/>
        </top:requestId>
        <top:subledgerDocSequenceId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:SubledgerDocSequenceId"/>
        </top:subledgerDocSequenceId>
        <top:subledgerDocSequenceValue>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:SubledgerDocSequenceValue"/>
        </top:subledgerDocSequenceValue>
        <top:attribute1>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute1"/>
        </top:attribute1>
        <top:attribute2>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute2"/>
        </top:attribute2>
        <top:glSlLinkId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:GLSLLinkId"/>
        </top:glSlLinkId>
        <top:glSlLinkTable>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:GLSLLinkTable"/>
        </top:glSlLinkTable>
        <top:attribute3>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute3"/>
        </top:attribute3>
        <top:attribute4>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute4"/>
        </top:attribute4>
        <top:attribute5>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute5"/>
        </top:attribute5>
        <top:attribute6>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute6"/>
        </top:attribute6>
        <top:attribute7>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute7"/>
        </top:attribute7>
        <top:attribute8>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute8"/>
        </top:attribute8>
        <top:attribute9>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute9"/>
        </top:attribute9>
        <top:attribute10>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute10"/>
        </top:attribute10>
        <top:attribute11>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute11"/>
        </top:attribute11>
        <top:attribute13>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute13"/>
        </top:attribute13>
        <top:attribute14>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute14"/>
        </top:attribute14>
        <top:attribute15>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute15"/>
        </top:attribute15>
        <top:attribute16>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute16"/>
        </top:attribute16>
        <top:attribute17>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute17"/>
        </top:attribute17>
        <top:attribute18>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute18"/>
        </top:attribute18>
        <top:attribute19>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute19"/>
        </top:attribute19>
        <top:attribute20>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Attribute20"/>
        </top:attribute20>
        <top:context>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Context"/>
        </top:context>
        <top:invoiceDate>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:InvoiceDate"/>
        </top:invoiceDate>
        <top:taxCode>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:TaxCode"/>
        </top:taxCode>
        <top:invoiceIdentifier>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:InvoiceIdentifier"/>
        </top:invoiceIdentifier>
        <top:invoiceAmount>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:InvoiceAmount"/>
        </top:invoiceAmount>
        <top:context3>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:Context3"/>
        </top:context3>
        <top:ussglTransactionCode>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:USSGLransactionCode"/>
        </top:ussglTransactionCode>
        <top:descrFlexErrorMessage>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:DescrFlexErrorMessage"/>
        </top:descrFlexErrorMessage>
        <top:jgzzReconRef>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:JGZZReconRef"/>
        </top:jgzzReconRef>
        <top:referenceDate>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:ReferenceDate"/>
        </top:referenceDate>
        <top:setOfBooksId>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:SetOfBooksId"/>
        </top:setOfBooksId>
        <top:balancingSegmentValue>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:BalancingSegmentValue"/>
        </top:balancingSegmentValue>
        <top:managementSegmentValue>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:ManagementSegmentValue"/>
        </top:managementSegmentValue>
        <top:fundsReservedFlag>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:FundsReservedFlag"/>
        </top:fundsReservedFlag>
        <top:codeCombinationIdInterim>
          <xsl:value-of select="/jeam:CreateJournalRequestMessage/jeam:Journal/ns2:CodeCombinationIDInterim"/>
        </top:codeCombinationIdInterim>
      </top:GlInterface>
    </top:GlInterfaceCollection>
  </xsl:template>
</xsl:stylesheet>