<wsdl:definitions
     name="DB_Insert"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_BatchJobDetails_EBiz_QMOS_ABF/DB_Insert"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_BatchJobDetails_EBiz_QMOS_ABF/DB_Insert"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Insert_plt" >
    <plt:role name="DB_Insert_role" >
      <plt:portType name="tns:DB_Insert_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert" schemaLocation="../Schemas/DB_Insert_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ApiWorkOrderCollection_msg">
        <wsdl:part name="ApiWorkOrderCollection" element="top:ApiWorkOrderCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Insert_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:ApiWorkOrderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
