DROP TABLE XXNUC_RCV_TRANS_HEADERS CASCADE CONSTRAINTS;

CREATE TABLE XXNUC_RCV_TRANS_HEADERS
(
  RCV_HEADER_KEY         NUMBER,
  RECEIPT_SOURCE_CODE    VARCHAR2(25 BYTE),
  TRANSACTION_TYPE       VARCHAR2(25 BYTE),
  SHIPMENT_NUM           VARCHAR2(30 BYTE),
  RECEIPT_NUMBER         VARCHAR2(30 BYTE),
  EXPECTED_RECEIPT_DATE  DATE,
  VENDOR_NAME            VARCHAR2(240 BYTE),
  VENDOR_NUM             VARCHAR2(30 BYTE),
  VENDOR_SITE_CODE       VARCHAR2(35 BYTE),
  SHIP_TO_ORGANIZATION   VARCHAR2(60 BYTE),
  SHIPPED_DATE           DATE,
  OPERATING_UNIT         VARCHAR2(240 BYTE),
  FREIGHT_CARRIER        VARCHAR2(80 BYTE),
  FREIGHT_AMOUNT         NUMBER,
  FREIGHT_TERMS          VARCHAR2(25 BYTE),
  PAYMENT_TERMS          VARCHAR2(50 BYTE),
  CURRENCY_CODE          VARCHAR2(10 BYTE),
  PACKING_SLIP           VARCHAR2(25 BYTE),
  EMPLOYEE_NUM           VARCHAR2(30 BYTE),
  ATTRIBUTE_CATEGORY     VARCHAR2(30 BYTE),
  ATTRIBUTE1             VARCHAR2(150 BYTE),
  ATTRIBUTE2             VARCHAR2(150 BYTE),
  ATTRIBUTE3             VARCHAR2(150 BYTE),
  ATTRIBUTE4             VARCHAR2(150 BYTE),
  ATTRIBUTE5             VARCHAR2(150 BYTE),
CREATION_DATE                     DATE,         -- Standard Who Columns
  LAST_UPDATE_DATE                DATE,         -- Standard Who Columns
CREATED_BY                        VARCHAR2(240),         -- Standard Who Columns
LAST_UPDATED_BY                   VARCHAR2(240),         -- Standard Who Columns
  PROCESS_DATE                    DATE,         -- Standard Interface Status Columns
  PROCESS_STATUS                  VARCHAR2(100 BYTE), -- Standard Interface Status Columns
  ERROR_MSG                       VARCHAR2(2000 BYTE), -- Standard Interface Status Columns
  REQUEST_ID                      VARCHAR2(100 BYTE) -- Standard Interface Status Columns
);


DROP SEQUENCE XXNUC_RCV_TRANS_HEADERS_S ;

CREATE SEQUENCE  XXNUC_RCV_TRANS_HEADERS_S  START WITH 1000 INCREMENT BY 1;

CREATE UNIQUE INDEX XXNUC_RCV_TRANS_HEADERS_U1 ON XXNUC_RCV_TRANS_HEADERS ( RCV_HEADER_KEY);

DROP TABLE XXNUC_RCV_TRANS_LINES CASCADE CONSTRAINTS;


CREATE TABLE XXNUC_RCV_TRANS_LINES
(
  RCV_LINE_KEY         NUMBER,
  RCV_HEADER_KEY      NUMBER,
  RECEIPT_NUMBER      VARCHAR2(30 BYTE),
  TRANSACTION_TYPE    VARCHAR2(25 BYTE),
  TRANSACTION_DATE    DATE,
  PO_NUMBER           VARCHAR2(25 BYTE),
  PO_LINE_NUMBER      NUMBER,
  PO_SHIPMENT_NUMBER  VARCHAR2(30 BYTE),
  ITEM_CATEGORY       VARCHAR2(81 BYTE),
  ITEM                VARCHAR2(81 BYTE),
  ITEM_DESCRIPTION    VARCHAR2(240 BYTE),
  TOTAL_QUANTITY      NUMBER,
  QUANTITY_SHIPPED    NUMBER,
  QUANTITY_INVOICED   NUMBER,
  UNIT_OF_MEASURE     VARCHAR2(25 BYTE),
  SHIP_TO_LOCATION    VARCHAR2(120 BYTE),
  OPERATING_UNIT      VARCHAR2(240 BYTE),
  CURRENCY_CODE       VARCHAR2(10 BYTE),
  DESTINATION_TYPE    VARCHAR2(25 BYTE),
  ATTRIBUTE_CONTEXT   VARCHAR2(30 BYTE),
  ATTRIBUTE1          VARCHAR2(150 BYTE),
  ATTRIBUTE2          VARCHAR2(150 BYTE),
  ATTRIBUTE3          VARCHAR2(150 BYTE),
  ATTRIBUTE4          VARCHAR2(150 BYTE),
  ATTRIBUTE5          VARCHAR2(150 BYTE),
CREATION_DATE                     DATE,         -- Standard Who Columns
  LAST_UPDATE_DATE                DATE,         -- Standard Who Columns
CREATED_BY                        VARCHAR2(240),         -- Standard Who Columns
LAST_UPDATED_BY                   VARCHAR2(240),         -- Standard Who Columns
  PROCESS_DATE                    DATE,         -- Standard Interface Status Columns
  PROCESS_STATUS                  VARCHAR2(100 BYTE), -- Standard Interface Status Columns
  ERROR_MSG                       VARCHAR2(2000 BYTE), -- Standard Interface Status Columns
  REQUEST_ID                      VARCHAR2(100 BYTE) -- Standard Interface Status Columns
);

DROP SEQUENCE XXNUC_RCV_TRANS_LINES_S ;

CREATE SEQUENCE  XXNUC_RCV_TRANS_LINES_S  START WITH 1000 INCREMENT BY 1;

CREATE UNIQUE INDEX XXNUC_RCV_TRANS_LINES_U1 ON XXNUC_RCV_TRANS_LINES ( RCV_LINE_KEY);

CREATE  INDEX XXNUC_RCV_TRANS_LINES_N1 ON XXNUC_RCV_TRANS_LINES ( RCV_HEADER_KEY);
