-- Purge ESS tables 
-- CAUTION!.-- CAUTION!.-- CAUTION!.-- CAUTION!.-- CAUTION!.-- CAUTION!.-- CAUTION!.
-- This will purge everything in ESS table
-- After this script run  with purge_ess_reclaim_space_new.sql  to reclaim space
-- CAUTION!.
-- CAUTION!.

-- Disable constraints
alter table request_metadata DISABLE constraint REQUEST_METADATA_FK;
ALTER TABLE JOB_INCOMPATIBILITY DISABLE CONSTRAINT JOB_INCOMPATIBILITY_FK;
ALTER TABLE REQUEST_METADATA DISABLE CONSTRAINT REQUEST_METADATA_FK;
ALTER TABLE REQUEST_INCOMPATIBILITY DISABLE CONSTRAINT REQUEST_INCOMPAT_FK;
ALTER TABLE REQUEST_PROPERTY DISABLE CONSTRAINT REQUEST_PROPERTY_FK;
ALTER TABLE PARAMETER_STASH DISABLE CONSTRAINT PARAMETER_STASH_FK;
ALTER TABLE REQUEST_CONSTRAINT DISABLE CONSTRAINT REQUEST_CONSTRAINT_FK;
ALTER TABLE EVENT_FILTER DISABLE CONSTRAINT EVENT_FILTER_FK;
ALTER TABLE REQUEST_CP DISABLE CONSTRAINT REQUEST_CP_FK;
ALTER TABLE WAIT_QUEUE DISABLE CONSTRAINT WAIT_QUEUE_FK;
ALTER TABLE ESS_WS_ASYNC_INFO DISABLE CONSTRAINT WS_ASYNC_FK;
ALTER TABLE FAILED_EXECUTION_HISTORY DISABLE CONSTRAINT EXECUTION_HISTORY_FK;
ALTER TABLE REQUEST_CONTENT DISABLE CONSTRAINT REQUEST_CONTENT_FK;
ALTER TABLE REQUEST_ATTRIBUTE DISABLE CONSTRAINT REQUEST_ATTRIBUTE_FK;
ALTER TABLE REQUEST_METADATA DISABLE CONSTRAINT REQUEST_METADATA_FK;
ALTER TABLE REQUEST_INCOMPATIBILITY DISABLE CONSTRAINT REQUEST_INCOMPAT_FK;
ALTER TABLE REQUEST_PROPERTY DISABLE CONSTRAINT REQUEST_PROPERTY_FK;
ALTER TABLE PARAMETER_STASH DISABLE CONSTRAINT PARAMETER_STASH_FK;
ALTER TABLE REQUEST_CONSTRAINT DISABLE CONSTRAINT REQUEST_CONSTRAINT_FK;
ALTER TABLE EVENT_FILTER DISABLE CONSTRAINT EVENT_FILTER_FK;
ALTER TABLE REQUEST_CP DISABLE CONSTRAINT REQUEST_CP_FK;
ALTER TABLE WAIT_QUEUE DISABLE CONSTRAINT WAIT_QUEUE_FK;
ALTER TABLE ESS_WS_ASYNC_INFO DISABLE CONSTRAINT WS_ASYNC_FK;
ALTER TABLE FAILED_EXECUTION_HISTORY DISABLE CONSTRAINT EXECUTION_HISTORY_FK;
ALTER TABLE REQUEST_CONTENT DISABLE CONSTRAINT REQUEST_CONTENT_FK;
ALTER TABLE REQUEST_ATTRIBUTE DISABLE CONSTRAINT REQUEST_ATTRIBUTE_FK;
ALTER TABLE REQUEST_METADATA DISABLE CONSTRAINT REQUEST_METADATA_FK;
ALTER TABLE REQUEST_INCOMPATIBILITY DISABLE CONSTRAINT REQUEST_INCOMPAT_FK;
ALTER TABLE REQUEST_PROPERTY DISABLE CONSTRAINT REQUEST_PROPERTY_FK;
ALTER TABLE PARAMETER_STASH DISABLE CONSTRAINT PARAMETER_STASH_FK;
ALTER TABLE REQUEST_CONSTRAINT DISABLE CONSTRAINT REQUEST_CONSTRAINT_FK;
ALTER TABLE EVENT_FILTER DISABLE CONSTRAINT EVENT_FILTER_FK;
ALTER TABLE REQUEST_CP DISABLE CONSTRAINT REQUEST_CP_FK;
ALTER TABLE WAIT_QUEUE DISABLE CONSTRAINT WAIT_QUEUE_FK;
ALTER TABLE ESS_WS_ASYNC_INFO DISABLE CONSTRAINT WS_ASYNC_FK;
ALTER TABLE FAILED_EXECUTION_HISTORY DISABLE CONSTRAINT EXECUTION_HISTORY_FK;
ALTER TABLE REQUEST_CONTENT DISABLE CONSTRAINT REQUEST_CONTENT_FK;
ALTER TABLE REQUEST_ATTRIBUTE DISABLE CONSTRAINT REQUEST_ATTRIBUTE_FK;
ALTER TABLE REQUEST_METADATA DISABLE CONSTRAINT REQUEST_METADATA_FK;
ALTER TABLE REQUEST_INCOMPATIBILITY DISABLE CONSTRAINT REQUEST_INCOMPAT_FK;
ALTER TABLE REQUEST_PROPERTY DISABLE CONSTRAINT REQUEST_PROPERTY_FK;
ALTER TABLE PARAMETER_STASH DISABLE CONSTRAINT PARAMETER_STASH_FK;
ALTER TABLE REQUEST_CONSTRAINT DISABLE CONSTRAINT REQUEST_CONSTRAINT_FK;
ALTER TABLE EVENT_FILTER DISABLE CONSTRAINT EVENT_FILTER_FK;
ALTER TABLE REQUEST_CP DISABLE CONSTRAINT REQUEST_CP_FK;
ALTER TABLE WAIT_QUEUE DISABLE CONSTRAINT WAIT_QUEUE_FK;
ALTER TABLE ESS_WS_ASYNC_INFO DISABLE CONSTRAINT WS_ASYNC_FK;
ALTER TABLE FAILED_EXECUTION_HISTORY DISABLE CONSTRAINT EXECUTION_HISTORY_FK;
ALTER TABLE REQUEST_CONTENT DISABLE CONSTRAINT REQUEST_CONTENT_FK;
ALTER TABLE REQUEST_ATTRIBUTE DISABLE CONSTRAINT REQUEST_ATTRIBUTE_FK;

-- Traucate tables
truncate table event_filter;
truncate table FAILED_EXECUTION_HISTORY;
truncate table REQUEST_CONSTRAINT;
truncate table REQUEST_PROPERTY;
truncate table REQUEST_INCOMPATIBILITY;
truncate table JOB_INCOMPATIBILITY;
truncate table REQUEST_METADATA;
truncate table ESS_WS_ASYNC_INFO;
truncate table REQUEST_CONTENT;
truncate table REQUEST_ATTRIBUTE;
truncate table WORK_UNITS;
truncate table EVENT_WORK;
truncate table COMMAND_WORK;
truncate table PARAMETER_STASH;
truncate table REQUEST_CP;
truncate table WAIT_QUEUE;
truncate table REQUEST_HISTORY;

-- Enable constraints
alter table request_metadata enable constraint REQUEST_METADATA_FK;
ALTER TABLE JOB_INCOMPATIBILITY enable CONSTRAINT JOB_INCOMPATIBILITY_FK;
ALTER TABLE REQUEST_METADATA ENABLE CONSTRAINT REQUEST_METADATA_FK;
ALTER TABLE REQUEST_INCOMPATIBILITY ENABLE CONSTRAINT REQUEST_INCOMPAT_FK;
ALTER TABLE REQUEST_PROPERTY ENABLE CONSTRAINT REQUEST_PROPERTY_FK;
ALTER TABLE PARAMETER_STASH ENABLE CONSTRAINT PARAMETER_STASH_FK;
ALTER TABLE REQUEST_CONSTRAINT ENABLE CONSTRAINT REQUEST_CONSTRAINT_FK;
ALTER TABLE EVENT_FILTER ENABLE CONSTRAINT EVENT_FILTER_FK;
ALTER TABLE REQUEST_CP ENABLE CONSTRAINT REQUEST_CP_FK;
ALTER TABLE WAIT_QUEUE ENABLE CONSTRAINT WAIT_QUEUE_FK;
ALTER TABLE ESS_WS_ASYNC_INFO ENABLE CONSTRAINT WS_ASYNC_FK;
ALTER TABLE FAILED_EXECUTION_HISTORY ENABLE CONSTRAINT EXECUTION_HISTORY_FK;
ALTER TABLE REQUEST_CONTENT ENABLE CONSTRAINT REQUEST_CONTENT_FK;
ALTER TABLE REQUEST_ATTRIBUTE ENABLE CONSTRAINT REQUEST_ATTRIBUTE_FK;
ALTER TABLE REQUEST_METADATA ENABLE CONSTRAINT REQUEST_METADATA_FK;
ALTER TABLE REQUEST_INCOMPATIBILITY ENABLE CONSTRAINT REQUEST_INCOMPAT_FK;
ALTER TABLE REQUEST_PROPERTY ENABLE CONSTRAINT REQUEST_PROPERTY_FK;
ALTER TABLE PARAMETER_STASH ENABLE CONSTRAINT PARAMETER_STASH_FK;
ALTER TABLE REQUEST_CONSTRAINT ENABLE CONSTRAINT REQUEST_CONSTRAINT_FK;
ALTER TABLE EVENT_FILTER ENABLE CONSTRAINT EVENT_FILTER_FK;
ALTER TABLE REQUEST_CP ENABLE CONSTRAINT REQUEST_CP_FK;
ALTER TABLE WAIT_QUEUE ENABLE CONSTRAINT WAIT_QUEUE_FK;
ALTER TABLE ESS_WS_ASYNC_INFO ENABLE CONSTRAINT WS_ASYNC_FK;
ALTER TABLE FAILED_EXECUTION_HISTORY ENABLE CONSTRAINT EXECUTION_HISTORY_FK;
ALTER TABLE REQUEST_CONTENT ENABLE CONSTRAINT REQUEST_CONTENT_FK;
ALTER TABLE REQUEST_ATTRIBUTE ENABLE CONSTRAINT REQUEST_ATTRIBUTE_FK;
ALTER TABLE REQUEST_METADATA ENABLE CONSTRAINT REQUEST_METADATA_FK;
ALTER TABLE REQUEST_INCOMPATIBILITY ENABLE CONSTRAINT REQUEST_INCOMPAT_FK;
ALTER TABLE REQUEST_PROPERTY ENABLE CONSTRAINT REQUEST_PROPERTY_FK;
ALTER TABLE PARAMETER_STASH ENABLE CONSTRAINT PARAMETER_STASH_FK;
ALTER TABLE REQUEST_CONSTRAINT ENABLE CONSTRAINT REQUEST_CONSTRAINT_FK;
ALTER TABLE EVENT_FILTER ENABLE CONSTRAINT EVENT_FILTER_FK;
ALTER TABLE REQUEST_CP ENABLE CONSTRAINT REQUEST_CP_FK;
ALTER TABLE WAIT_QUEUE ENABLE CONSTRAINT WAIT_QUEUE_FK;
ALTER TABLE ESS_WS_ASYNC_INFO ENABLE CONSTRAINT WS_ASYNC_FK;
ALTER TABLE FAILED_EXECUTION_HISTORY ENABLE CONSTRAINT EXECUTION_HISTORY_FK;
ALTER TABLE REQUEST_CONTENT ENABLE CONSTRAINT REQUEST_CONTENT_FK;
ALTER TABLE REQUEST_ATTRIBUTE ENABLE CONSTRAINT REQUEST_ATTRIBUTE_FK;
ALTER TABLE REQUEST_METADATA ENABLE CONSTRAINT REQUEST_METADATA_FK;
ALTER TABLE REQUEST_INCOMPATIBILITY ENABLE CONSTRAINT REQUEST_INCOMPAT_FK;
ALTER TABLE REQUEST_PROPERTY ENABLE CONSTRAINT REQUEST_PROPERTY_FK;
ALTER TABLE PARAMETER_STASH ENABLE CONSTRAINT PARAMETER_STASH_FK;
ALTER TABLE REQUEST_CONSTRAINT ENABLE CONSTRAINT REQUEST_CONSTRAINT_FK;
ALTER TABLE EVENT_FILTER ENABLE CONSTRAINT EVENT_FILTER_FK;
ALTER TABLE REQUEST_CP ENABLE CONSTRAINT REQUEST_CP_FK;
ALTER TABLE WAIT_QUEUE ENABLE CONSTRAINT WAIT_QUEUE_FK;
ALTER TABLE ESS_WS_ASYNC_INFO ENABLE CONSTRAINT WS_ASYNC_FK;
ALTER TABLE FAILED_EXECUTION_HISTORY ENABLE CONSTRAINT EXECUTION_HISTORY_FK;
ALTER TABLE REQUEST_CONTENT ENABLE CONSTRAINT REQUEST_CONTENT_FK;
ALTER TABLE REQUEST_ATTRIBUTE ENABLE CONSTRAINT REQUEST_ATTRIBUTE_FK;