CREATE PROFILE "SERVICE_ACCOUNTS"
    LIMIT 
         COMPOSITE_LIMIT DEFAULT 
         SESSIONS_PER_USER DEFAULT 
         CPU_PER_SESSION DEFAULT 
         CPU_PER_CALL DEFAULT 
         LOGICAL_READS_PER_SESSION DEFAULT 
         LOGICAL_READS_PER_CALL DEFAULT 
         IDLE_TIME DEFAULT 
         CONNECT_TIME DEFAULT 
         PRIVATE_SGA DEFAULT 
         FAILED_LOGIN_ATTEMPTS UNLIMITED 
         PASSWORD_LIFE_TIME UNLIMITED 
         PASSWORD_REUSE_TIME UNLIMITED 
         PASSWORD_REUSE_MAX UNLIMITED 
         PASSWORD_VERIFY_FUNCTION DEFAULT 
         PASSWORD_LOCK_TIME DEFAULT 
         PASSWORD_GRACE_TIME DEFAULT
         
ALTER USER SOA_MDS PROFILE SERVICE_ACCOUNTS                  
ALTER USER SOA_SOAINFRA PROFILE SERVICE_ACCOUNTS                  
ALTER USER SOA_ORASDPM PROFILE SERVICE_ACCOUNTS  