DROP TABLE XXNUC_SUPPLIERS_OUT CASCADE CONSTRAINTS;

CREATE TABLE XXNUC_SUPPLIERS_OUT
(
  SUPPLIER_OUT_KEY         NUMBER,
  LEGACY_SUPPLIER_NUMBER  VARCHAR2(100 BYTE),
  REF_SUPPLIER_SITE_ID    NUMBER,
  REF_SUPPLIER_ID         NUMBER,
  REF_PARTY_ID            NUMBER,
  REF_PARTYSITE_ID        NUMBER,
  REF_LOCATION_ID         NUMBER,
  CREATION_DATE            DATE,
  LAST_UPDATE_DATE         DATE,
CREATED_BY               VARCHAR2(240),
LAST_UPDATED_BY          VARCHAR2(240),
  PROCESS_DATE             DATE,
  PROCESS_STATUS           VARCHAR2(10 BYTE),
  ERROR_MSG                VARCHAR2(2000 BYTE),
ATTRIBUTE_CATEGORY       VARCHAR2(30),
ATTRIBUTE1               VARCHAR2(150),
ATTRIBUTE2               VARCHAR2(150),
ATTRIBUTE3               VARCHAR2(150),
ATTRIBUTE4               VARCHAR2(150),
ATTRIBUTE5               VARCHAR2(150),
ATTRIBUTE6               VARCHAR2(150),
ATTRIBUTE7               VARCHAR2(150),
ATTRIBUTE8               VARCHAR2(150),
ATTRIBUTE9               VARCHAR2(150),
ATTRIBUTE10               VARCHAR2(150),
ATTRIBUTE11               VARCHAR2(150),
ATTRIBUTE12               VARCHAR2(150),
ATTRIBUTE13               VARCHAR2(150),
ATTRIBUTE14               VARCHAR2(150),
ATTRIBUTE15               VARCHAR2(150)
);

 DROP SEQUENCE XXNUC_SUPPLIERS_OUT_S;
   
 CREATE SEQUENCE  XXNUC_SUPPLIERS_OUT_S  START WITH 1000 INCREMENT BY 1;
   
 CREATE UNIQUE INDEX XXNUC_SUPPLIERS_OUT_U1 ON XXNUC_SUPPLIERS_OUT ( SUPPLIER_OUT_KEY);
  
