-- Cross Reference table 1.0
-- 6/8/2013

CREATE TABLE XREF_GL_CODE_EBS_CSP (ROW_ID VARCHAR2(48) NOT NULL, CSP VARCHAR2(2000), 
EBS VARCHAR2(2000),LAST_MODIFIED TIMESTAMP NOT NULL);
/
Create Index XREF_GL_CODE_EBS_CSP_N1 on XREF_GL_CODE_EBS_CSP(Row_ID) reverse;
Create Index XREF_GL_CODE_EBS_CSP_N2 on XREF_GL_CODE_EBS_CSP(EBS);
Create Index XREF_GL_CODE_EBS_CSP_N3 on XREF_GL_CODE_EBS_CSP(CSP);
