-- Cross Reference table 1.0
-- 6/8/2013

CREATE TABLE XREF_GL_CODE_EBS_NDC (ROW_ID VARCHAR2(48) NOT NULL, NDC VARCHAR2(2000), 
EBS VARCHAR2(2000),LAST_MODIFIED TIMESTAMP NOT NULL);
/
Create Index XREF_GL_CODE_EBS_NDC_N1 on XREF_GL_CODE_EBS_NDC(Row_ID) reverse;
Create Index XREF_GL_CODE_EBS_NDC_N2 on XREF_GL_CODE_EBS_NDC(EBS);
Create Index XREF_GL_CODE_EBS_NDC_N3 on XREF_GL_CODE_EBS_NDC(NDC);
