 CREATE TABLE XXNUC_SOA_DEPLOYMENT_LOGS 
   (	RELEASE_IDENTIFIER VARCHAR2(100 BYTE), 
	RELEASE_BRANCH VARCHAR2(240 BYTE), 
	COMPOSITE_NAME VARCHAR2(240 BYTE), 
	COMPOSITE_DIR VARCHAR2(512 BYTE), 
	COMPOSITE_VERSION VARCHAR2(30 BYTE), 
	COMPOSITE_PARTITION VARCHAR2(100 BYTE), 
	REVISION VARCHAR2(100 BYTE), 
	ENVIRONMENT VARCHAR2(100 BYTE), 
	METADATA_REVISION VARCHAR2(100 BYTE), 
	CONFIG_REVISION VARCHAR2(100 BYTE), 
	CREATION_TSTAMP TIMESTAMP (6), 
	UPDATE_TSTAMP TIMESTAMP (6)
   ) ;
