DROP VIEW APPS.XXNUC_SUP_SITE_ORIG_SYS_REFS_V;

/* Formatted on 3/28/2014 11:21:14 AM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW APPS.XXNUC_SUP_SITE_ORIG_SYS_REFS_V
(
   VENDOR_SITE_ID,
   VENDOR_SITE_CODE,
   VENDOR_SITE_CODE_ALT,
   VENDOR_ID,
   ORG_ID,
   ORIG_SYSTEM_REF_ID,
   ORIG_SYSTEM,
   ORIG_SYSTEM_REFERENCE,
   OWNER_TABLE_NAME,
   OWNER_TABLE_ID,
   STATUS,
   REASON_CODE,
   OLD_ORIG_SYSTEM_REFERENCE,
   START_DATE_ACTIVE,
   END_DATE_ACTIVE,
   CREATED_BY,
   CREATION_DATE,
   LAST_UPDATED_BY,
   LAST_UPDATE_DATE,
   LAST_UPDATE_LOGIN,
   OBJECT_VERSION_NUMBER,
   CREATED_BY_MODULE,
   APPLICATION_ID,
   ATTRIBUTE_CATEGORY,
   ATTRIBUTE1,
   ATTRIBUTE2,
   ATTRIBUTE3,
   ATTRIBUTE4,
   ATTRIBUTE5,
   ATTRIBUTE6,
   ATTRIBUTE7,
   ATTRIBUTE8,
   ATTRIBUTE9,
   ATTRIBUTE10,
   ATTRIBUTE11,
   ATTRIBUTE12,
   ATTRIBUTE13,
   ATTRIBUTE14,
   ATTRIBUTE15,
   ATTRIBUTE16,
   ATTRIBUTE17,
   ATTRIBUTE18,
   ATTRIBUTE19,
   ATTRIBUTE20,
   PARTY_ID,
   REQUEST_ID,
   PROGRAM_APPLICATION_ID,
   PROGRAM_ID,
   PROGRAM_UPDATE_DATE
)
AS
   SELECT pv.vendor_site_id,
          pv.vendor_site_code,
          pv.vendor_site_code_alt,
          pv.vendor_id,
          pv.org_id,
          os.orig_system_ref_id,
          os.orig_system,
          os.orig_system_reference,
          os.owner_table_name,
          os.owner_table_id,
          os.status,
          os.reason_code,
          os.old_orig_system_reference,
          os.start_date_active,
          os.end_date_active,
          os.created_by,
          os.creation_date,
          os.last_updated_by,
          os.last_update_date,
          os.last_update_login,
          os.object_version_number,
          os.created_by_module,
          os.application_id,
          os.attribute_category,
          os.attribute1,
          os.attribute2,
          os.attribute3,
          os.attribute4,
          os.attribute5,
          os.attribute6,
          os.attribute7,
          os.attribute8,
          os.attribute9,
          os.attribute10,
          os.attribute11,
          os.attribute12,
          os.attribute13,
          os.attribute14,
          os.attribute15,
          os.attribute16,
          os.attribute17,
          os.attribute18,
          os.attribute19,
          os.attribute20,
          os.party_id,
          os.request_id,
          os.program_application_id,
          os.program_id,
          os.program_update_date
     FROM hz_orig_sys_references os, po_vendor_sites_all pv
    WHERE     os.owner_table_name = 'HZ_PARTY_SITES'
          AND os.owner_table_id = pv.party_site_id
          AND os.status = 'A'
          AND (pv.inactive_date is null OR pv.inactive_date > sysdate);


GRANT SELECT ON APPS.XXNUC_SUP_SITE_ORIG_SYS_REFS_V TO APPS_READ_ROLE;
