CREATE TABLE XXNUC_SOA_REL_ARTIFACTS
  (
    "REL_ARTIFACT_ID"       NUMBER,
    "RELEASE_ID"            NUMBER,
    "REL_ARTIFACT_TYPE"     VARCHAR2(30),   
    "SVN_PATH"              VARCHAR2(240),
    "ARTIFACT_NAME"         VARCHAR2(240),
    "SVN_VERSION"           VARCHAR2(512),
    "PARTITION"             VARCHAR2(100),
    "SOURCE_ATTRIBUTE1"     VARCHAR2(100),
    "SOURCE_ATTRIBUTE2"     VARCHAR2(100),
    "SOURCE_ATTRIBUTE3"     VARCHAR2(100),
    "SOURCE_ATTRIBUTE4"     VARCHAR2(100),      
    "TARGET_ATTRIBUTE1"     VARCHAR2(100),
    "TARGET_ATTRIBUTE2"     VARCHAR2(100),
    "TARGET_ATTRIBUTE3"     VARCHAR2(100),
    "TARGET_ATTRIBUTE4"     VARCHAR2(100),   
    "CREATION_TSTAMP"       TIMESTAMP (6),
    "UPDATE_TSTAMP"         TIMESTAMP (6),
    "CREATED_BY"            VARCHAR2(100),
    "LAST_UPDATED_BY"       VARCHAR2(100)   
  );