CREATE TABLE XXNUC_SOA_ARTIFACT_TYPES
  (
    "ARTIFACT_TYPE_ID"  NUMBER,
    "ARTIFACT_TYPE"     VARCHAR2(240),
    "DEPLOYER_URL"      VARCHAR2(240),  
    "CREATION_TSTAMP"   TIMESTAMP (6),
    "UPDATE_TSTAMP"     TIMESTAMP (6),
    "CREATED_BY"        VARCHAR2(100),
    "LAST_UPDATED_BY"   VARCHAR2(100)
    );