CREATE TABLE XXNUC_SOA_ENVIRONMENTS
  (
    "ENV_ID"          NUMBER,
    "ENV_CODE"        VARCHAR2(240),
    "ENV_DESC"        VARCHAR2(240),
    "ENV_USER_NAME"   VARCHAR2(80),
    "ENV_PASSWORD"   VARCHAR2(80),
    "ATTRIBUTE1"            VARCHAR2(100),
    "ATTRIBUTE2"         VARCHAR2(100),
    "ATTRIBUTE3"   VARCHAR2(100),
    "ATTRIBUTE4"   VARCHAR2(100),
    "ATTRIBUTE5"   VARCHAR2(100),   
    "CREATION_TSTAMP" TIMESTAMP(6),
    "UPDATE_TSTAMP" TIMESTAMP(6)
  );