CREATE TABLE XXNUC_SOA_CM_RELEASES
  (
    "RELEASE_ID"            NUMBER,
    "RELEASE_NAME"          VARCHAR2(80),
    "RELEASE_DESCRIPTION"   VARCHAR2(240),
    "RELEASE_DATE"          DATE,
    "CREATED_BY"            VARCHAR2(100),
    "LAST_UPDATED_BY"       VARCHAR2(100),
    "CREATION_TSTAMP"       TIMESTAMP(6),
    "UPDATE_TSTAMP"         TIMESTAMP(6),
    "SVN_BASE_PATH"         VARCHAR2(2000)
  );