<wsdl:definitions
     name="DB_Update_Bundle_Trx"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSTX_Bundle_EBSMTLTrxImp_ABF/DB_Update_Bundle_Trx"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen1.1/NSTX_Bundle_EBSMTLTrxImp_ABF/DB_Update_Bundle_Trx"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Bundle_Trx"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Update_Bundle_Trx_plt" >
    <plt:role name="DB_Update_Bundle_Trx_role" >
      <plt:portType name="tns:DB_Update_Bundle_Trx_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Update_Bundle_Trx" schemaLocation="../Schemas/DB_Update_Bundle_Trx_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ApiBundleTransCollection_msg">
        <wsdl:part name="ApiBundleTransCollection" element="top:ApiBundleTransCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Update_Bundle_Trx_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:ApiBundleTransCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
