<wsdl:definitions
     name="DB_DeleteJDAPlanTransData"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen/NUC_JDA_EBiz_BatchSchedule_ABF/DB_DeleteJDAPlanTransData"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen/NUC_JDA_EBiz_BatchSchedule_ABF/DB_DeleteJDAPlanTransData"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_DeleteJDAPlanTransData"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_DeleteJDAPlanTransData_plt" >
    <plt:role name="DB_DeleteJDAPlanTransData_role" >
      <plt:portType name="tns:DB_DeleteJDAPlanTransData_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_DeleteJDAPlanTransData" schemaLocation="../Schemas/DB_DeleteJDAPlanTransData.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_DeleteJDAPlanTransDataInput_msg">
        <wsdl:part name="DB_DeleteJDAPlanTransDataInput_msg" element="db:DB_DeleteJDAPlanTransDataInput"/>
    </wsdl:message>
    <wsdl:portType name="DB_DeleteJDAPlanTransData_ptt">
        <wsdl:operation name="DB_DeleteJDAPlanTransData">
            <wsdl:input message="tns:DB_DeleteJDAPlanTransDataInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
