<wsdl:definitions
     name="DB_DeleteJDAPlanInvAsgmts"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen/NUC_JDA_EBiz_BatchSchedule_ABF/DB_DeleteJDAPlanInvAsgmts"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen/NUC_JDA_EBiz_BatchSchedule_ABF/DB_DeleteJDAPlanInvAsgmts"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_DeleteJDAPlanInvAsgmts"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_DeleteJDAPlanInvAsgmts_plt" >
    <plt:role name="DB_DeleteJDAPlanInvAsgmts_role" >
      <plt:portType name="tns:DB_DeleteJDAPlanInvAsgmts_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_DeleteJDAPlanInvAsgmts" schemaLocation="../Schemas/DB_DeleteJDAPlanInvAsgmts.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_DeleteJDAPlanInvAsgmtsInput_msg">
        <wsdl:part name="DB_DeleteJDAPlanInvAsgmtsInput_msg" element="db:DB_DeleteJDAPlanInvAsgmtsInput"/>
    </wsdl:message>
    <wsdl:portType name="DB_DeleteJDAPlanInvAsgmts_ptt">
        <wsdl:operation name="DB_DeleteJDAPlanInvAsgmts">
            <wsdl:input message="tns:DB_DeleteJDAPlanInvAsgmtsInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
