<wsdl:definitions
     name="DB_InsertJDAMfgOrderPlan"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_JDA_Ebiz_BatchSchedule_ABF/DB_InsertJDAMfgOrderPlan"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/1.1/NUC_JDA_Ebiz_BatchSchedule_ABF/DB_InsertJDAMfgOrderPlan"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertJDAMfgOrderPlan"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_InsertJDAMfgOrderPlan_plt" >
    <plt:role name="DB_InsertJDAMfgOrderPlan_role" >
      <plt:portType name="tns:DB_InsertJDAMfgOrderPlan_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertJDAMfgOrderPlan" schemaLocation="../Schemas/DB_InsertJDAMfgOrderPlan_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="XxnucGmeJdaMfgPlanStgCollection_msg">
        <wsdl:part name="XxnucGmeJdaMfgPlanStgCollection" element="top:XxnucGmeJdaMfgPlanStgCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_InsertJDAMfgOrderPlan_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:XxnucGmeJdaMfgPlanStgCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
