<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="NUC_ReceiveARFreight_OTM_Ebiz_ABF" targetNamespace="http://xmlns.eia.com/Implementation/ABF/NUC_ReceiveARFreight_OTM_EBiz_ABF/NUC_ReceiveARFreight_OTM_EBiz_ABF/NUC_ReceiveARFreight_OTM_Ebiz_ABF" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.eia.com/Implementation/ABF/NUC_ReceiveARFreight_OTM_EBiz_ABF/NUC_ReceiveARFreight_OTM_EBiz_ABF/NUC_ReceiveARFreight_OTM_Ebiz_ABF" xmlns:ns1="http://xmlns.oracle.com/apps/otm" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/service/bpel/common">
   <plnk:partnerLinkType name="NUC_ReceiveARFreight_OTM_Ebiz_ABF">
      <plnk:role name="NUC_ReceiveARFreight_OTM_Ebiz_ABFProvider" portType="client:NUC_ReceiveARFreight_OTM_Ebiz_ABF"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.eia.com/Implementation/ABF/NUC_ReceiveARFreight_OTM_EBiz_ABF/NUC_ReceiveARFreight_OTM_EBiz_ABF/NUC_ReceiveARFreight_OTM_Ebiz_ABF" xmlns:ns1="http://xmlns.oracle.com/apps/otm" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/service/bpel/common">
         <import namespace="http://xmlns.oracle.com/apps/otm" schemaLocation="oramds:/apps/EIAMetadata/AO/OTM/common/V1.0/GLogXML.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.eia.com/Implementation/ABF/NUC_ReceiveARFreight_OTM_EBiz_ABF/NUC_ReceiveARFreight_OTM_EBiz_ABF/NUC_ReceiveARFreight_OTM_Ebiz_ABF" xmlns:ns1="http://xmlns.oracle.com/apps/otm" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/service/bpel/common">
         <xsd:import namespace="http://schemas.oracle.com/service/bpel/common" schemaLocation="oramds:/apps/EIAMetadata/EO/common/V1.0/XSLParameters.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="NUC_ReceiveARFreight_OTM_Ebiz_ABFRequestMessage">
      <wsdl:part name="payload" element="ns1:Transmission"/>
   </wsdl:message>
   <wsdl:portType name="NUC_ReceiveARFreight_OTM_Ebiz_ABF">
      <wsdl:operation name="process">
         <wsdl:input message="client:NUC_ReceiveARFreight_OTM_Ebiz_ABFRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
