<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/apps/otm"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_WshOtmShipStatusInbound"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:client="http://xmlns.oracle.com/apps/wsh/inbound/WshReceivePShipmentFromOtm"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/OTMDEC/ReceivePShipmentFromOtm/DB_WshOtmShipStatusInbound"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WshReceivePShipmentFromOtm.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../partnerWsdls/DB_WshOtmShipStatusInbound.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_WshOtmShipStatusInbound"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JAN 21 01:58:30 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_TRIP_STOP_INFO>
        <xsl:for-each select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment">
          <tns:P_TRIP_STOP_INFO_ITEM>
            <tns:TRIP_ID>
              <xsl:value-of select="ns0:Shipment/ns0:ShipmentHeader/ns0:ShipmentGid/ns0:Gid/ns0:Xid"/>
            </tns:TRIP_ID>
            <tns:TRIP_STOPS_STATUS_INFO>
              <xsl:for-each select="ns0:Shipment/ns0:ShipmentStop">
                <xsl:if test="ns0:StopType  = 'D'">
                  <tns:TRIP_STOPS_STATUS_INFO_ITEM>
                    <tns:STOP_LOCATION_ID>
                      <xsl:value-of select="substring-after(substring-after(ns0:LocationRef/ns0:LocationGid/ns0:Gid/ns0:Xid,'-'),'-')"/>
                    </tns:STOP_LOCATION_ID>
                    <tns:STOP_SEQUENCE_NUMBER>
                      <xsl:value-of select="ns0:ExtStopSequence"/>
                    </tns:STOP_SEQUENCE_NUMBER>
                    <tns:PLANNED_ARRIVAL_DATE>
                      <xsl:value-of select='concat(substring(ns0:ArrivalTime/ns0:EventTime/ns0:ActualTime,1.0,4.0),"-",substring(ns0:ArrivalTime/ns0:EventTime/ns0:ActualTime,5.0,2.0),"-",substring(ns0:ArrivalTime/ns0:EventTime/ns0:ActualTime,7.0,2.0),"T",substring(ns0:ArrivalTime/ns0:EventTime/ns0:ActualTime,9.0,2.0),":",substring(ns0:ArrivalTime/ns0:EventTime/ns0:ActualTime,11.0,2.0),":",substring(ns0:ArrivalTime/ns0:EventTime/ns0:ActualTime,13.0,2.0))'/>
                    </tns:PLANNED_ARRIVAL_DATE>
                    <tns:PLANNED_DEPARTURE_DATE></tns:PLANNED_DEPARTURE_DATE>
                    <tns:ATTRIBUTE8>Delivered</tns:ATTRIBUTE8>
                    <tns:ATTRIBUTE9></tns:ATTRIBUTE9>
                    <tns:ATTRIBUTE10></tns:ATTRIBUTE10>
                  </tns:TRIP_STOPS_STATUS_INFO_ITEM>
                </xsl:if>
              </xsl:for-each>
            </tns:TRIP_STOPS_STATUS_INFO>
          </tns:P_TRIP_STOP_INFO_ITEM>
        </xsl:for-each>
      </tns:P_TRIP_STOP_INFO>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
