<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.eia.com/CommonLogging" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_HeatChemistry"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSNE_Chemistry_L2_EBS_ABF/DB_HeatChemistry"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns6="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns11="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns3="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns8="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABS/NUC_NUC_EBizQualityResults_ABS/QualityResults/1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/Infrastracture/wsdls/V1.0/CommonLogging.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Input" namespace="http://xmlns.eia.com/CommonLogging"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_HeatChemistry.wsdl"/>
        <oracle-xsl-mapper:rootElement name="vw_L2_Heat_Batch_ChemistryCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_HeatChemistry"/>
        <oracle-xsl-mapper:param name="g_Invoke_DB_HeatChemistry_OutputVariable.vw_L2_Heat_Batch_ChemistryCollection"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsUpdateRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON APR 17 12:11:31 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_Invoke_DB_HeatChemistry_OutputVariable.vw_L2_Heat_Batch_ChemistryCollection"/>
  <xsl:template match="/">
    <tns:QualityResultsUpdateRq>
     <ns6:HeaderRq>
        <ns6:TransactionRequestID/>
        <ns6:Language>ENG</ns6:Language>
        <ns6:ComponentID>
          <xsl:value-of select="/ns0:Input/ns0:ComponentId"/>
        </ns6:ComponentID>
        <ns6:TransactionIDREF>
          <xsl:value-of select="/ns0:Input/ns0:TransactionId"/>
        </ns6:TransactionIDREF>
        <ns6:TransactionName>
          <xsl:value-of select="/ns0:Input/ns0:TransactionName"/>
        </ns6:TransactionName>
        <ns6:Source>
          <xsl:value-of select="/ns0:Input/ns0:SourceSystem"/>
        </ns6:Source>
        <ns6:Target>
          <xsl:value-of select="/ns0:Input/ns0:TargetSystem"/>
        </ns6:Target>
        <ns6:MillName>NSNE</ns6:MillName>
      </ns6:HeaderRq>
      <ns8:GmdResultsPub>
        <xsl:for-each select="$g_Invoke_DB_HeatChemistry_OutputVariable.vw_L2_Heat_Batch_ChemistryCollection/ns1:vw_L2_Heat_Batch_ChemistryCollection/ns1:vw_L2_Heat_Batch_Chemistry">
          <ns8:GmdResultPub>
            <ns8:TxnID>
              <xsl:value-of select="/ns0:Input/ns0:TransactionId"/>
            </ns8:TxnID>
            <ns8:OrganizationId/>
            <ns8:OrganizationCode>100</ns8:OrganizationCode>
            <ns8:SampleSource>W</ns8:SampleSource>
            <xsl:choose>
              <xsl:when test="ns1:OracleBatchID = 0">
                <ns8:item_id>
                  <xsl:value-of select="oraext:query-database (concat (&quot;select inventory_item_id from (select mmt.transaction_source_id , mmt.creation_Date, mmt.inventory_item_id from mtl_transaction_lot_numbers mtl ,mtl_material_transactions mmt where mmt.transaction_id = mtl.transaction_id and mtl.lot_number='&quot;, ns1:LotNumber, &quot;' and mmt.transaction_source_type_id = 5 order by mmt.creation_Date desc) batch_source where rownum &lt; 2&quot; ), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
                </ns8:item_id>
              </xsl:when>
              <xsl:otherwise>
                <ns8:item_id>
                  <xsl:value-of select='oraext:query-database (concat ("SELECT   inventory_item_id  FROM   gme_material_details WHERE   batch_id =", ns1:OracleBatchID, "  AND line_type = 1" ), false(), false(), "jdbc/ebsapps" )'/>
                </ns8:item_id>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="ns1:OracleBatchID = 0">
                <ns8:BatchID>
                  <xsl:value-of select="oraext:query-database (concat (&quot;select transaction_source_id from (select mmt.transaction_source_id , mmt.creation_Date, mmt.inventory_item_id from mtl_transaction_lot_numbers mtl ,mtl_material_transactions mmt where mmt.transaction_id = mtl.transaction_id and mtl.lot_number='&quot;, ns1:LotNumber, &quot;' and mmt.transaction_source_type_id = 5 order by mmt.creation_Date desc) batch_source where rownum &lt; 2&quot; ), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
                </ns8:BatchID>
              </xsl:when>
              <xsl:otherwise>
                <ns8:BatchID>
                  <xsl:value-of select="ns1:OracleBatchID"/>
                </ns8:BatchID>
              </xsl:otherwise>
            </xsl:choose>
            <ns8:LotNo>
              <xsl:value-of select="ns1:LotNumber"/>
            </ns8:LotNo>
            <ns8:Sampler>SOAUSER</ns8:Sampler>
            <ns8:Test_results>
              <xsl:if test='ns1:Al and ns1:Al != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Al</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Al"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:As and ns1:As != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>As</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:As"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:b and ns1:b != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>B</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:b"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Bi and ns1:Bi != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Bi</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Bi"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:c and ns1:c != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>C</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:c"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Ca and ns1:Ca != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Ca</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Ca"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Cb and ns1:Cb != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Cb</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Cb"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Ce and ns1:Ce != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Ce</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Ce"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Co and ns1:Co != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Co</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Co"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Cr and ns1:Cr != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Cr</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Cr"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Cu and ns1:Cu != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Cu</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Cu"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Mn and ns1:Mn != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Mn</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Mn"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Mo and ns1:Mo != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Mo</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Mo"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:N2_ppm and ns1:N2_ppm != ""'>
                <ns8:Test_results>
                  <!--ns8:TestCode>N2_ppm</ns8:TestCode-->
                  <ns8:TestCode>N</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:N2_ppm"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Ni and ns1:Ni != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Ni</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Ni"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:o and ns1:o != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>O</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:o"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:p and ns1:p != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>P</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:p"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:s and ns1:s != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>S</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:s"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Sa and ns1:Sa != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Sa</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Sa"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Sb and ns1:Sb != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Sb</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Sb"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Se and ns1:Se != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Se</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Se"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Si and ns1:Si != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Si</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Si"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Sn and ns1:Sn != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Sn</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Sn"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Te and ns1:Te != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Te</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Te"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Ti and ns1:Ti != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Ti</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Ti"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:v and ns1:v != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>V</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:v"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Zn and ns1:Zn != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Zn</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Zn"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Zr and ns1:Zr != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Zr</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Zr"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Liquidus and ns1:Liquidus != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Liquidus</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Liquidus"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Nb and ns1:Nb != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Nb</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Nb"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Pb and ns1:Pb != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Pb</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Pb"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:fe and ns1:fe != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>FE%</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:fe"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:lecoC and ns1:lecoC != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>LECO_C</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:lecoC"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:lecoS and ns1:lecoS != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>LECO_S</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:lecoS"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:lecoN2 and ns1:lecoN2 != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>LECO_N2</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:lecoN2"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:lecoTox and ns1:lecoTox != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>LECO_TOX</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:lecoTox"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Tensile and ns1:Tensile != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Tensile</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Tensile"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:Yield and ns1:Yield != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>Yield</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:Yield"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:CarbonEQ and ns1:CarbonEQ != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>CarbonEQ</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:CarbonEQ"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:ce1 and ns1:ce1 != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>CE1</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:ce1"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:gsttensile and ns1:gsttensile != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>GSTTENSILE</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:gsttensile"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:kfactor and ns1:kfactor != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>KFACTOR</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:kfactor"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:USCuEQ and ns1:USCuEQ != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>USCuEQ</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:USCuEQ"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:c6 and ns1:c6 != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>C6</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:c6"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:di and ns1:di != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>DI</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:di"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
              <xsl:if test='ns1:h and ns1:h != ""'>
                <ns8:Test_results>
                  <ns8:TestCode>H</ns8:TestCode>
                  <ns8:Tester>SOAUSER</ns8:Tester>
                  <ns8:ResultValue>
                    <xsl:value-of select="ns1:h"/>
                  </ns8:ResultValue>
                  <ns8:ResultDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                  </ns8:ResultDate>
                </ns8:Test_results>
              </xsl:if>
            </ns8:Test_results>
          </ns8:GmdResultPub>
        </xsl:for-each>
      </ns8:GmdResultsPub>
    </tns:QualityResultsUpdateRq>
  </xsl:template>
</xsl:stylesheet>
