<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns9 ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns5="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAO/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns2="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABS/NUC_NUC_EBizQualityResults_ABS/QualityResults/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns9="http://schemas.oracle.com/service/bpel/common"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/EO/common/V1.0/XSLParameters.xsd"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="params"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsUpdateRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON APR 10 22:19:18 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <xsl:param name="params"/>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:QualityResultsAddRq>
      <xsl:variable name="currentGMDnode">
        <xsl:value-of select="$params/ns9:parameters/ns9:item/ns9:value"/>
      </xsl:variable>
      <ns3:HeaderRq>
        <ns3:TransactionRequestID>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:TransactionRequestID"/>
        </ns3:TransactionRequestID>
        <ns3:Language>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:Language"/>
        </ns3:Language>
        <ns3:ComponentID>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:ComponentID"/>
        </ns3:ComponentID>
        <ns3:ServiceName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:ServiceName"/>
        </ns3:ServiceName>
        <ns3:TransactionIDREF>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:TransactionIDREF"/>
        </ns3:TransactionIDREF>
        <ns3:TransactionName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:TransactionName"/>
        </ns3:TransactionName>
        <ns3:Source>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:Source"/>
        </ns3:Source>
        <ns3:Target>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:Target"/>
        </ns3:Target>
        <ns3:MillName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:HeaderRq/ns3:MillName"/>
        </ns3:MillName>
      </ns3:HeaderRq>
      <ns0:AppsContext>
        <ns6:UserName></ns6:UserName>
        <ns6:UserId>2385</ns6:UserId>
        <ns6:ResponsibilityName>NUC Quality Interface User</ns6:ResponsibilityName>
        <ns6:OrgId>86</ns6:OrgId>
      </ns0:AppsContext>
      <ns5:GmdResultsPub>
        <ns5:GmdResultPub>
          <ns5:TxnID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:TxnID"/>
          </ns5:TxnID>
          <ns5:record_source>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:record_source"/>
          </ns5:record_source>
          <ns5:SampleId>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleId"/>
          </ns5:SampleId>
          <ns5:SampleNo>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleNo"/>
          </ns5:SampleNo>
          <ns5:OrganizationId>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OrganizationId"/>
          </ns5:OrganizationId>
          <ns5:LabOrganizationId>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:LabOrganizationId"/>
          </ns5:LabOrganizationId>
          <ns5:OrganizationCode>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OrganizationCode"/>
          </ns5:OrganizationCode>
          <ns5:SampleSource>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleSource"/>
          </ns5:SampleSource>
          <ns5:item_id>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:item_id"/>
          </ns5:item_id>
          <ns5:item_no>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:item_no"/>
          </ns5:item_no>
          <ns5:BatchID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:BatchID"/>
          </ns5:BatchID>
          <ns5:BatchNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:BatchNO"/>
          </ns5:BatchNO>
          <ns5:StepID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:StepID"/>
          </ns5:StepID>
          <ns5:StepNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:StepNO"/>
          </ns5:StepNO>
          <ns5:Charge>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:Charge"/>
          </ns5:Charge>
          <ns5:SourceSubInventory>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SourceSubInventory"/>
          </ns5:SourceSubInventory>
          <ns5:WIPParentLot>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:WIPParentLot"/>
          </ns5:WIPParentLot>
          <ns5:ReceipeNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ReceipeNO"/>
          </ns5:ReceipeNO>
          <ns5:receipeID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:receipeID"/>
          </ns5:receipeID>
          <ns5:ParentLotNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ParentLotNO"/>
          </ns5:ParentLotNO>
          <ns5:LotNo>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:LotNo"/>
          </ns5:LotNo>
          <ns5:FormulaNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:FormulaNO"/>
          </ns5:FormulaNO>
          <ns5:FormulaID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:FormulaID"/>
          </ns5:FormulaID>
          <ns5:RoutingNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:RoutingNO"/>
          </ns5:RoutingNO>
          <ns5:RoutingID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:RoutingID"/>
          </ns5:RoutingID>
          <ns5:OprnNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OprnNO"/>
          </ns5:OprnNO>
          <ns5:OprnID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OprnID"/>
          </ns5:OprnID>
          <ns5:LpnNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:LpnNO"/>
          </ns5:LpnNO>
          <ns5:LpnID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:LpnID"/>
          </ns5:LpnID>
          <ns5:RetainAS>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:RetainAS"/>
          </ns5:RetainAS>
          <ns5:revision>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:revision"/>
          </ns5:revision>
          <ns5:Priority xsi:nil="">
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:Priority"/>
          </ns5:Priority>
          <ns5:SampleQTY>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleQTY"/>
          </ns5:SampleQTY>
          <ns5:RemainingQTY>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:RemainingQTY"/>
          </ns5:RemainingQTY>
          <ns5:SampleQtyUOM>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleQtyUOM"/>
          </ns5:SampleQtyUOM>
          <ns5:SampleQtyUnitOfMeasure>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleQtyUnitOfMeasure"/>
          </ns5:SampleQtyUnitOfMeasure>
          <ns5:dateDrawn>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:dateDrawn"/>
          </ns5:dateDrawn>
          <ns5:RetrievalDate>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:RetrievalDate"/>
          </ns5:RetrievalDate>
          <ns5:dateReceived>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:dateReceived"/>
          </ns5:dateReceived>
          <ns5:DateRequired>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:DateRequired"/>
          </ns5:DateRequired>
          <ns5:ExpirationDate>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ExpirationDate"/>
          </ns5:ExpirationDate>
          <ns5:SampleInstance>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleInstance"/>
          </ns5:SampleInstance>
          <ns5:ExternalID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ExternalID"/>
          </ns5:ExternalID>
          <ns5:StorageOrganizationCode>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:StorageOrganizationCode"/>
          </ns5:StorageOrganizationCode>
          <ns5:StorageOrganizationID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:StorageOrganizationID"/>
          </ns5:StorageOrganizationID>
          <ns5:StorageSubInventory>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:StorageSubInventory"/>
          </ns5:StorageSubInventory>
          <ns5:Sampler>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:Sampler"/>
          </ns5:Sampler>
          <ns5:SamplerID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SamplerID"/>
          </ns5:SamplerID>
          <ns5:SampleApprover>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleApprover"/>
          </ns5:SampleApprover>
          <ns5:SampleApproverID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SampleApproverID"/>
          </ns5:SampleApproverID>
          <ns5:InvApprover>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:InvApprover"/>
          </ns5:InvApprover>
          <ns5:InvApproverID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:InvApproverID"/>
          </ns5:InvApproverID>
          <ns5:SourceComment>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SourceComment"/>
          </ns5:SourceComment>
          <ns5:CustomerName>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:CustomerName"/>
          </ns5:CustomerName>
          <ns5:CustID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:CustID"/>
          </ns5:CustID>
          <ns5:OperatingUnit>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OperatingUnit"/>
          </ns5:OperatingUnit>
          <ns5:OrgID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OrgID"/>
          </ns5:OrgID>
          <ns5:ShipToName>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ShipToName"/>
          </ns5:ShipToName>
          <ns5:ShipToSiteID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ShipToSiteID"/>
          </ns5:ShipToSiteID>
          <ns5:OrderNo>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OrderNo"/>
          </ns5:OrderNo>
          <ns5:OrderID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OrderID"/>
          </ns5:OrderID>
          <ns5:OrderLineNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OrderLineNO"/>
          </ns5:OrderLineNO>
          <ns5:OrderLineID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:OrderLineID"/>
          </ns5:OrderLineID>
          <ns5:SubInventory>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SubInventory"/>
          </ns5:SubInventory>
          <ns5:SupplierName>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SupplierName"/>
          </ns5:SupplierName>
          <ns5:SupplierID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SupplierID"/>
          </ns5:SupplierID>
          <ns5:SupplierSite>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SupplierSite"/>
          </ns5:SupplierSite>
          <ns5:SupplierSiteID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SupplierSiteID"/>
          </ns5:SupplierSiteID>
          <ns5:SupplierLotNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:SupplierLotNO"/>
          </ns5:SupplierLotNO>
          <ns5:PoNumber>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:PoNumber"/>
          </ns5:PoNumber>
          <ns5:PoHeaderID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:PoHeaderID"/>
          </ns5:PoHeaderID>
          <ns5:PoLineNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:PoLineNO"/>
          </ns5:PoLineNO>
          <ns5:PoLineID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:PoLineID"/>
          </ns5:PoLineID>
          <ns5:ReceiptNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ReceiptNO"/>
          </ns5:ReceiptNO>
          <ns5:ReceiptID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ReceiptID"/>
          </ns5:ReceiptID>
          <ns5:ReceiptLineNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ReceiptLineNO"/>
          </ns5:ReceiptLineNO>
          <ns5:ReceiptLineID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:ReceiptLineID"/>
          </ns5:ReceiptLineID>
          <ns5:disposition_status>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:disposition_status"/>
          </ns5:disposition_status>
          <ns5:Test_results>
            <xsl:for-each select="/ns0:QualityResultsAddRq/ns5:GmdResultsPub/ns5:GmdResultPub[ns5:LotNo = $currentGMDnode]/ns5:Test_results/ns5:Test_results">
              <ns5:Test_results>
                <ns5:SeqNO>
                  <xsl:value-of select="ns5:SeqNO"/>
                </ns5:SeqNO>
                <ns5:TestCode>
                  <xsl:value-of select="ns5:TestCode"/>
                </ns5:TestCode>
                <ns5:TestID>
                  <xsl:value-of select="ns5:TestID"/>
                </ns5:TestID>
                <ns5:Tester>
                  <xsl:value-of select="ns5:Tester"/>
                </ns5:Tester>
                <ns5:TesterID>
                  <xsl:value-of select="ns5:TesterID"/>
                </ns5:TesterID>
                <ns5:ResultValue>
                  <xsl:value-of select="ns5:ResultValue"/>
                </ns5:ResultValue>
                <ns5:TestQTY>
                  <xsl:value-of select="ns5:TestQTY"/>
                </ns5:TestQTY>
                <ns5:ResultDate>
                  <xsl:value-of select="ns5:ResultDate"/>
                </ns5:ResultDate>
                <ns5:EvalInd>
                  <xsl:value-of select="ns5:EvalInd"/>
                </ns5:EvalInd>
                <ns5:ActionCode>
                  <xsl:value-of select="ns5:ActionCode"/>
                </ns5:ActionCode>
                <ns5:Replicate>
                  <xsl:value-of select="ns5:Replicate"/>
                </ns5:Replicate>
              </ns5:Test_results>
            </xsl:for-each>
          </ns5:Test_results>
        </ns5:GmdResultPub>
      </ns5:GmdResultsPub>
    </ns0:QualityResultsAddRq>
  </xsl:template>
</xsl:stylesheet>
