<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns2="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns8="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns3="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABS/NUC_NUC_EBizQualityResults_ABS/QualityResults/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/EO/common/V1.0/XSLParameters.xsd"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="params"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI FEB 05 11:30:51 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="params"/>
  <xsl:template match="/">
    <ns0:QualityResultsAddRq>
      <xsl:variable name="currentGMDnode">
        <xsl:value-of select="$params/ns1:parameters/ns1:item/ns1:value"/>
      </xsl:variable>
      <ns8:HeaderRq>
        <ns8:TransactionRequestID>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:TransactionRequestID"/>
        </ns8:TransactionRequestID>
        <ns8:Language>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:Language"/>
        </ns8:Language>
        <ns8:ComponentID>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:ComponentID"/>
        </ns8:ComponentID>
        <ns8:ServiceName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:ServiceName"/>
        </ns8:ServiceName>
        <ns8:TransactionIDREF>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:TransactionIDREF"/>
        </ns8:TransactionIDREF>
        <ns8:TransactionName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:TransactionName"/>
        </ns8:TransactionName>
        <ns8:Source>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:Source"/>
        </ns8:Source>
        <ns8:Target>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:Target"/>
        </ns8:Target>
        <ns8:MillName>
          <xsl:value-of select="/ns0:QualityResultsAddRq/ns8:HeaderRq/ns8:MillName"/>
        </ns8:MillName>
      </ns8:HeaderRq>
      <ns0:AppsContext>
        <ns6:UserName></ns6:UserName>
        <ns6:UserId>2385</ns6:UserId>
        <ns6:ResponsibilityName>NSNE PO Superuser</ns6:ResponsibilityName>
        <ns6:OrgId>88</ns6:OrgId>
      </ns0:AppsContext>
      <ns3:GmdResultsPub>
        <ns3:GmdResultPub>
          <ns3:TxnID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:TxnID"/>
          </ns3:TxnID>
          <ns3:record_source>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:record_source"/>
          </ns3:record_source>
          <ns3:SampleId>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleId"/>
          </ns3:SampleId>
          <ns3:SampleNo>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleNo"/>
          </ns3:SampleNo>
          <ns3:OrganizationId>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OrganizationId"/>
          </ns3:OrganizationId>
          <ns3:LabOrganizationId>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:LabOrganizationId"/>
          </ns3:LabOrganizationId>
          <ns3:OrganizationCode>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OrganizationCode"/>
          </ns3:OrganizationCode>
          <ns3:SampleSource>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleSource"/>
          </ns3:SampleSource>
          <ns3:item_id>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:item_id"/>
          </ns3:item_id>
          <ns3:item_no>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:item_no"/>
          </ns3:item_no>
          <ns3:BatchID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:BatchID"/>
          </ns3:BatchID>
          <ns3:BatchNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:BatchNO"/>
          </ns3:BatchNO>
          <ns3:StepID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:StepID"/>
          </ns3:StepID>
          <ns3:StepNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:StepNO"/>
          </ns3:StepNO>
          <ns3:Charge>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:Charge"/>
          </ns3:Charge>
          <ns3:SourceSubInventory>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SourceSubInventory"/>
          </ns3:SourceSubInventory>
          <ns3:WIPParentLot>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:WIPParentLot"/>
          </ns3:WIPParentLot>
          <ns3:ReceipeNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ReceipeNO"/>
          </ns3:ReceipeNO>
          <ns3:receipeID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:receipeID"/>
          </ns3:receipeID>
          <ns3:ParentLotNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ParentLotNO"/>
          </ns3:ParentLotNO>
          <ns3:LotNo>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:LotNo"/>
          </ns3:LotNo>
          <ns3:FormulaNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:FormulaNO"/>
          </ns3:FormulaNO>
          <ns3:FormulaID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:FormulaID"/>
          </ns3:FormulaID>
          <ns3:RoutingNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:RoutingNO"/>
          </ns3:RoutingNO>
          <ns3:RoutingID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:RoutingID"/>
          </ns3:RoutingID>
          <ns3:OprnNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OprnNO"/>
          </ns3:OprnNO>
          <ns3:OprnID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OprnID"/>
          </ns3:OprnID>
          <ns3:LpnNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:LpnNO"/>
          </ns3:LpnNO>
          <ns3:LpnID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:LpnID"/>
          </ns3:LpnID>
          <ns3:RetainAS>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:RetainAS"/>
          </ns3:RetainAS>
          <ns3:revision>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:revision"/>
          </ns3:revision>
          <ns3:Priority xsi:nil="">
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:Priority"/>
          </ns3:Priority>
          <ns3:SampleQTY>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleQTY"/>
          </ns3:SampleQTY>
          <ns3:RemainingQTY>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:RemainingQTY"/>
          </ns3:RemainingQTY>
          <ns3:SampleQtyUOM>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleQtyUOM"/>
          </ns3:SampleQtyUOM>
          <ns3:SampleQtyUnitOfMeasure>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleQtyUnitOfMeasure"/>
          </ns3:SampleQtyUnitOfMeasure>
          <ns3:dateDrawn>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:dateDrawn"/>
          </ns3:dateDrawn>
          <ns3:RetrievalDate>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:RetrievalDate"/>
          </ns3:RetrievalDate>
          <ns3:dateReceived>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:dateReceived"/>
          </ns3:dateReceived>
          <ns3:DateRequired>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:DateRequired"/>
          </ns3:DateRequired>
          <ns3:ExpirationDate>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ExpirationDate"/>
          </ns3:ExpirationDate>
          <ns3:SampleInstance>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleInstance"/>
          </ns3:SampleInstance>
          <ns3:ExternalID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ExternalID"/>
          </ns3:ExternalID>
          <ns3:StorageOrganizationCode>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:StorageOrganizationCode"/>
          </ns3:StorageOrganizationCode>
          <ns3:StorageOrganizationID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:StorageOrganizationID"/>
          </ns3:StorageOrganizationID>
          <ns3:StorageSubInventory>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:StorageSubInventory"/>
          </ns3:StorageSubInventory>
          <ns3:Sampler>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:Sampler"/>
          </ns3:Sampler>
          <ns3:SamplerID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SamplerID"/>
          </ns3:SamplerID>
          <ns3:SampleApprover>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleApprover"/>
          </ns3:SampleApprover>
          <ns3:SampleApproverID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SampleApproverID"/>
          </ns3:SampleApproverID>
          <ns3:InvApprover>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:InvApprover"/>
          </ns3:InvApprover>
          <ns3:InvApproverID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:InvApproverID"/>
          </ns3:InvApproverID>
          <ns3:SourceComment>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SourceComment"/>
          </ns3:SourceComment>
          <ns3:CustomerName>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:CustomerName"/>
          </ns3:CustomerName>
          <ns3:CustID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:CustID"/>
          </ns3:CustID>
          <ns3:OperatingUnit>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OperatingUnit"/>
          </ns3:OperatingUnit>
          <ns3:OrgID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OrgID"/>
          </ns3:OrgID>
          <ns3:ShipToName>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ShipToName"/>
          </ns3:ShipToName>
          <ns3:ShipToSiteID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ShipToSiteID"/>
          </ns3:ShipToSiteID>
          <ns3:OrderNo>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OrderNo"/>
          </ns3:OrderNo>
          <ns3:OrderID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OrderID"/>
          </ns3:OrderID>
          <ns3:OrderLineNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OrderLineNO"/>
          </ns3:OrderLineNO>
          <ns3:OrderLineID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:OrderLineID"/>
          </ns3:OrderLineID>
          <ns3:SubInventory>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SubInventory"/>
          </ns3:SubInventory>
          <ns3:SupplierName>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SupplierName"/>
          </ns3:SupplierName>
          <ns3:SupplierID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SupplierID"/>
          </ns3:SupplierID>
          <ns3:SupplierSite>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SupplierSite"/>
          </ns3:SupplierSite>
          <ns3:SupplierSiteID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SupplierSiteID"/>
          </ns3:SupplierSiteID>
          <ns3:SupplierLotNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:SupplierLotNO"/>
          </ns3:SupplierLotNO>
          <ns3:PoNumber>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:PoNumber"/>
          </ns3:PoNumber>
          <ns3:PoHeaderID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:PoHeaderID"/>
          </ns3:PoHeaderID>
          <ns3:PoLineNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:PoLineNO"/>
          </ns3:PoLineNO>
          <ns3:PoLineID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:PoLineID"/>
          </ns3:PoLineID>
          <ns3:ReceiptNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ReceiptNO"/>
          </ns3:ReceiptNO>
          <ns3:ReceiptID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ReceiptID"/>
          </ns3:ReceiptID>
          <ns3:ReceiptLineNO>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ReceiptLineNO"/>
          </ns3:ReceiptLineNO>
          <ns3:ReceiptLineID>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:ReceiptLineID"/>
          </ns3:ReceiptLineID>
          <ns3:disposition_status>
            <xsl:value-of select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:disposition_status"/>
          </ns3:disposition_status>
          <ns3:Test_results>
            <xsl:for-each select="/ns0:QualityResultsAddRq/ns3:GmdResultsPub/ns3:GmdResultPub[ns3:LotNo = $currentGMDnode]/ns3:Test_results/ns3:Test_results">
              <ns3:Test_results>
                <ns3:SeqNO>
                  <xsl:value-of select="ns3:SeqNO"/>
                </ns3:SeqNO>
                <ns3:TestCode>
                  <xsl:value-of select="ns3:TestCode"/>
                </ns3:TestCode>
                <ns3:TestID>
                  <xsl:value-of select="ns3:TestID"/>
                </ns3:TestID>
                <ns3:Tester>
                  <xsl:value-of select="ns3:Tester"/>
                </ns3:Tester>
                <ns3:TesterID>
                  <xsl:value-of select="ns3:TesterID"/>
                </ns3:TesterID>
                <ns3:ResultValue>
                  <xsl:value-of select="ns3:ResultValue"/>
                </ns3:ResultValue>
                <ns3:TestQTY>
                  <xsl:value-of select="ns3:TestQTY"/>
                </ns3:TestQTY>
                <ns3:ResultDate>
                  <xsl:value-of select="ns3:ResultDate"/>
                </ns3:ResultDate>
                <ns3:EvalInd>
                  <xsl:value-of select="ns3:EvalInd"/>
                </ns3:EvalInd>
                <ns3:ActionCode>
                  <xsl:value-of select="ns3:ActionCode"/>
                </ns3:ActionCode>
                <ns3:Replicate>
                  <xsl:value-of select="ns3:Replicate"/>
                </ns3:Replicate>
              </ns3:Test_results>
            </xsl:for-each>
          </ns3:Test_results>
        </ns3:GmdResultPub>
      </ns3:GmdResultsPub>
    </ns0:QualityResultsAddRq>
  </xsl:template>
</xsl:stylesheet>
