<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Call_XXNUC_WSH_BOL_GMD_RSLT_PKG"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DV1Application/NUC_EBizQualityResults_ABS/DB_Call_XXNUC_WSH_BOL_GMD_RSLT_PKG"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns3="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABS/NUC_NUC_EBizQualityResults_ABS/QualityResults/1.0"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryQAResultsByBolNoRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Call_XXNUC_WSH_BOL_GMD_RSLT_PKG.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Call_XXNUC_WSH_BOL_GMD_RSLT_PKG"/>
        <oracle-xsl-mapper:param name="Invoke_DB_Call_XXNUC_WSH_BOL_GMD_RSLT_PKG_OutputVariable.OutputParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryQAResultsByBolNoRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 13 04:38:33 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="Invoke_DB_Call_XXNUC_WSH_BOL_GMD_RSLT_PKG_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <ns0:QueryQAResultsByBolNoRs>
      <ns9:HeaderRs>
        <ns9:RequestDetails>
          <ns9:TransactionRequestID>
            <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:TransactionRequestID"/>
          </ns9:TransactionRequestID>
          <ns9:Language>
            <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:Language"/>
          </ns9:Language>
          <ns9:ComponentID>
            <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:ComponentID"/>
          </ns9:ComponentID>
          <ns9:ServiceName>
            <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:ServiceName"/>
          </ns9:ServiceName>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:TransactionIDREF">
            <ns9:TransactionIDREF>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:TransactionIDREF"/>
            </ns9:TransactionIDREF>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:TransactionName">
            <ns9:TransactionName>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:TransactionName"/>
            </ns9:TransactionName>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:FileName">
            <ns9:FileName>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:FileName"/>
            </ns9:FileName>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:FileInstanceID">
            <ns9:FileInstanceID>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:FileInstanceID"/>
            </ns9:FileInstanceID>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:Source">
            <ns9:Source>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:Source"/>
            </ns9:Source>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:Target">
            <ns9:Target>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:Target"/>
            </ns9:Target>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:HostName">
            <ns9:HostName>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:HostName"/>
            </ns9:HostName>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:UserName">
            <ns9:UserName>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:UserName"/>
            </ns9:UserName>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:UserRole">
            <ns9:UserRole>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:UserRole"/>
            </ns9:UserRole>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:AdminEmail">
            <ns9:AdminEmail>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:AdminEmail"/>
            </ns9:AdminEmail>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:ApplicationResponsibility">
            <ns9:ApplicationResponsibility>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:ApplicationResponsibility"/>
            </ns9:ApplicationResponsibility>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:EOFFlag">
            <ns9:EOFFlag>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:EOFFlag"/>
            </ns9:EOFFlag>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:SOFFlag">
            <ns9:SOFFlag>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:SOFFlag"/>
            </ns9:SOFFlag>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:FileRecordCount">
            <ns9:FileRecordCount>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:FileRecordCount"/>
            </ns9:FileRecordCount>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:TimeStamp">
            <ns9:TimeStamp>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:TimeStamp"/>
            </ns9:TimeStamp>
          </xsl:if>
          <xsl:if test="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:MillName">
            <ns9:MillName>
              <xsl:value-of select="/ns0:QueryQAResultsByBolNoRq/ns9:HeaderRq/ns9:MillName"/>
            </ns9:MillName>
          </xsl:if>
        </ns9:RequestDetails>
        <ns9:Status>
          <ns9:Status>SUCCESS</ns9:Status>
        </ns9:Status>
      </ns9:HeaderRs>
      <ns0:OperationResult>
        <ns2:Stats>S</ns2:Stats>
      </ns0:OperationResult>
      <ns4:GmdResultsPub>
        <xsl:for-each select="$Invoke_DB_Call_XXNUC_WSH_BOL_GMD_RSLT_PKG_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_TEST_RSLT/ns1:P_TEST_RSLT_ITEM">
          <ns4:GmdResultPub>
            <xsl:if test="ns1:SAMPLE_NO">
              <ns4:SampleNo>
                <xsl:value-of select="ns1:SAMPLE_NO"/>
              </ns4:SampleNo>
            </xsl:if>
            <xsl:if test="ns1:ORGANIZATION_ID">
              <ns4:OrganizationId>
                <xsl:value-of select="ns1:ORGANIZATION_ID"/>
              </ns4:OrganizationId>
            </xsl:if>
            <xsl:if test="ns1:LAB_ORGANIZATION_CODE">
              <ns4:LabOrganizationCode>
                <xsl:value-of select="ns1:LAB_ORGANIZATION_CODE"/>
              </ns4:LabOrganizationCode>
            </xsl:if>
            <xsl:if test="ns1:ORGANIZATION_CODE">
              <ns4:OrganizationCode>
                <xsl:value-of select="ns1:ORGANIZATION_CODE"/>
              </ns4:OrganizationCode>
            </xsl:if>
            <xsl:if test="ns1:MILLDUNS">
              <ns4:MillDUNS>
                <xsl:value-of select="ns1:MILLDUNS"/>
              </ns4:MillDUNS>
            </xsl:if>
            <xsl:if test="ns1:MELT_COUNTRY">
              <ns4:MeltCountry>
                <xsl:value-of select="ns1:MELT_COUNTRY"/>
              </ns4:MeltCountry>
            </xsl:if>
            <xsl:if test="ns1:ROLL_COUNTRY">
              <ns4:RollCountry>
                <xsl:value-of select="ns1:ROLL_COUNTRY"/>
              </ns4:RollCountry>
            </xsl:if>
            <xsl:if test="ns1:GRAIN_PRACTICE">
              <ns4:GrainPractice>
                <xsl:value-of select="ns1:GRAIN_PRACTICE"/>
              </ns4:GrainPractice>
            </xsl:if>
            <xsl:if test="ns1:SOURCE">
              <ns4:SampleSource>
                <xsl:value-of select="ns1:SOURCE"/>
              </ns4:SampleSource>
            </xsl:if>
            <xsl:if test="ns1:ITEM_ID">
              <ns4:item_id>
                <xsl:value-of select="ns1:ITEM_ID"/>
              </ns4:item_id>
            </xsl:if>
            <xsl:if test="ns1:ITEM_NO">
              <ns4:item_no>
                <xsl:value-of select="ns1:ITEM_NO"/>
              </ns4:item_no>
            </xsl:if>
            <xsl:if test="ns1:PARENT_LOT">
              <ns4:ParentLotNO>
                <xsl:value-of select="ns1:PARENT_LOT"/>
              </ns4:ParentLotNO>
            </xsl:if>
            <xsl:if test="ns1:LOT_NO">
              <ns4:LotNo>
                <xsl:value-of select="ns1:LOT_NO"/>
              </ns4:LotNo>
            </xsl:if>
            <xsl:if test="ns1:LPN_NO">
              <ns4:LpnNO>
                <xsl:value-of select="ns1:LPN_NO"/>
              </ns4:LpnNO>
            </xsl:if>
            <xsl:if test="ns1:SAMPLE_QTY">
              <ns4:SampleQTY>
                <xsl:value-of select="ns1:SAMPLE_QTY"/>
              </ns4:SampleQTY>
            </xsl:if>
            <xsl:if test="ns1:DRAWN_DATE">
              <ns4:dateDrawn>
                <xsl:value-of select="ns1:DRAWN_DATE"/>
              </ns4:dateDrawn>
            </xsl:if>
            <xsl:if test="ns1:DATE_RECEIVED">
              <ns4:dateReceived>
                <xsl:value-of select="ns1:DATE_RECEIVED"/>
              </ns4:dateReceived>
            </xsl:if>
            <xsl:if test="ns1:DATE_REQUIRED">
              <ns4:DateRequired>
                <xsl:value-of select="ns1:DATE_REQUIRED"/>
              </ns4:DateRequired>
            </xsl:if>
            <xsl:if test="ns1:OPERATING_UNIT">
              <ns4:OperatingUnit>
                <xsl:value-of select="ns1:OPERATING_UNIT"/>
              </ns4:OperatingUnit>
            </xsl:if>
            <xsl:if test="ns1:CUST_PO_NUM">
              <ns4:PoNumber>
                <xsl:value-of select="ns1:CUST_PO_NUM"/>
              </ns4:PoNumber>
            </xsl:if>
            <xsl:if test="ns1:CUST_PO_LINE_NUM">
              <ns4:PoLineNO>
                <xsl:value-of select="ns1:CUST_PO_LINE_NUM"/>
              </ns4:PoLineNO>
            </xsl:if>
            <xsl:if test="ns1:BOL_NUMBER">
              <ns4:BolNo>
                <xsl:value-of select="ns1:BOL_NUMBER"/>
              </ns4:BolNo>
            </xsl:if>
            <xsl:if test="ns1:SAMPLE_DESC">
              <ns4:SampleDesc>
                <xsl:value-of select="ns1:SAMPLE_DESC"/>
              </ns4:SampleDesc>
            </xsl:if>
            <xsl:if test="ns1:ROLL_DATE">
              <ns4:RollDate>
                <xsl:value-of select="ns1:ROLL_DATE"/>
              </ns4:RollDate>
            </xsl:if>
            <xsl:if test="ns1:MELT_DATE">
              <ns4:MiltDate>
                <xsl:value-of select="ns1:MELT_DATE"/>
              </ns4:MiltDate>
            </xsl:if>
            <xsl:if test="ns1:CUST_NUM">
              <ns4:CustNo>
                <xsl:value-of select="ns1:CUST_NUM"/>
              </ns4:CustNo>
            </xsl:if>
            <xsl:if test="ns1:SIZE_H">
              <ns4:SizeH>
                <xsl:value-of select="ns1:SIZE_H"/>
              </ns4:SizeH>
            </xsl:if>
            <xsl:if test="ns1:SALES_DIV">
              <ns4:SalesDiv>
                <xsl:value-of select="ns1:SALES_DIV"/>
              </ns4:SalesDiv>
            </xsl:if>
            <xsl:if test="ns1:TEST_MILL">
              <ns4:TestResultsMill>
                <xsl:value-of select="ns1:TEST_MILL"/>
              </ns4:TestResultsMill>
            </xsl:if>
            <xsl:if test="ns1:NUM_SIZE">
              <ns4:NumSize>
                <xsl:value-of select="ns1:NUM_SIZE"/>
              </ns4:NumSize>
            </xsl:if>
            <xsl:if test="ns1:FLAT_SIZE">
              <ns4:FlatSize>
                <xsl:value-of select="ns1:FLAT_SIZE"/>
              </ns4:FlatSize>
            </xsl:if>
            <xsl:if test="ns1:SPEC_NAME">
              <ns4:SpecName>
                <xsl:value-of select="ns1:SPEC_NAME"/>
              </ns4:SpecName>
            </xsl:if>
            <xsl:if test="ns1:GRADE_CODE">
              <ns4:GradeCode>
                <xsl:value-of select="ns1:GRADE_CODE"/>
              </ns4:GradeCode>
            </xsl:if>
            <xsl:if test="ns1:UPDATE_INVENTORY_QTY">
              <ns4:UpdateInventoryQty>
                <xsl:value-of select="ns1:UPDATE_INVENTORY_QTY"/>
              </ns4:UpdateInventoryQty>
            </xsl:if>
            <xsl:if test="ns1:COMMENTS">
              <ns4:Comments>
                <xsl:value-of select="ns1:COMMENTS"/>
              </ns4:Comments>
            </xsl:if>
            <xsl:if test="ns1:PRODUCT_SHAPE">
              <ns4:ProductShape>
                <xsl:value-of select="ns1:PRODUCT_SHAPE"/>
              </ns4:ProductShape>
            </xsl:if>
            <xsl:if test="ns1:ORDER_TYPE">
              <ns4:OrderType>
                <xsl:value-of select="ns1:ORDER_TYPE"/>
              </ns4:OrderType>
            </xsl:if>
            <ns4:Test_results>
              <xsl:for-each select="ns1:TST_RESULTS/ns1:TST_RESULTS_ITEM">
                <ns4:Test_results>
                  <xsl:if test="ns1:TEST_CLASS">
                    <ns4:TestClass>
                      <xsl:value-of select="ns1:TEST_CLASS"/>
                    </ns4:TestClass>
                  </xsl:if>
                  <xsl:if test="ns1:TEST_CODE">
                    <ns4:TestCode>
                      <xsl:value-of select="ns1:TEST_CODE"/>
                    </ns4:TestCode>
                  </xsl:if>
                  <xsl:if test="ns1:SEQ">
                    <ns4:SeqNO>
                      <xsl:value-of select="ns1:SEQ"/>
                    </ns4:SeqNO>
                  </xsl:if>
                  <xsl:if test="ns1:TEST_ID">
                    <ns4:TestID>
                      <xsl:value-of select="ns1:TEST_ID"/>
                    </ns4:TestID>
                  </xsl:if>
                  <xsl:if test="ns1:TEST_UNIT">
                    <ns4:TestUnit>
                      <xsl:value-of select="ns1:TEST_UNIT"/>
                    </ns4:TestUnit>
                  </xsl:if>
                  <xsl:if test="ns1:RESULT_VALUE">
                    <ns4:ResultValue>
                      <xsl:value-of select="ns1:RESULT_VALUE"/>
                    </ns4:ResultValue>
                  </xsl:if>
                  <xsl:if test="ns1:TEST_REPLICATE_CNT">
                    <ns4:Replicate>
                      <xsl:value-of select="ns1:TEST_REPLICATE_CNT"/>
                    </ns4:Replicate>
                  </xsl:if>
                  <xsl:if test="ns1:MIN_VALUE_NUM">
                    <ns4:MinValueNum>
                      <xsl:value-of select="ns1:MIN_VALUE_NUM"/>
                    </ns4:MinValueNum>
                  </xsl:if>
                  <xsl:if test="ns1:MAX_VALUE_NUM">
                    <ns4:MaxValueNum>
                      <xsl:value-of select="ns1:MAX_VALUE_NUM"/>
                    </ns4:MaxValueNum>
                  </xsl:if>
                  <xsl:if test="ns1:ABOVE_MIN_ACTION_CODE">
                    <ns4:AboveMinActionCode>
                      <xsl:value-of select="ns1:ABOVE_MIN_ACTION_CODE"/>
                    </ns4:AboveMinActionCode>
                  </xsl:if>
                  <xsl:if test="ns1:ABOVE_MAX_ACTION_CODE">
                    <ns4:AboveMaxActionCode>
                      <xsl:value-of select="ns1:ABOVE_MAX_ACTION_CODE"/>
                    </ns4:AboveMaxActionCode>
                  </xsl:if>
                  <xsl:if test="ns1:ABOVE_SPEC_MIN">
                    <ns4:AboveSpecMin>
                      <xsl:value-of select="ns1:ABOVE_SPEC_MIN"/>
                    </ns4:AboveSpecMin>
                  </xsl:if>
                  <xsl:if test="ns1:ABOVE_SPEC_MAX">
                    <ns4:AboveSpecMax>
                      <xsl:value-of select="ns1:ABOVE_SPEC_MAX"/>
                    </ns4:AboveSpecMax>
                  </xsl:if>
                  <xsl:if test="ns1:BELOW_SPEC_MIN">
                    <ns4:BelowSpecMin>
                      <xsl:value-of select="ns1:BELOW_SPEC_MIN"/>
                    </ns4:BelowSpecMin>
                  </xsl:if>
                  <xsl:if test="ns1:BELOW_SPEC_MAX">
                    <ns4:BelowSpecMax>
                      <xsl:value-of select="ns1:BELOW_SPEC_MAX"/>
                    </ns4:BelowSpecMax>
                  </xsl:if>
                  <xsl:if test="ns1:GAGE_LEN">
                    <ns4:GageLen>
                      <xsl:value-of select="ns1:GAGE_LEN"/>
                    </ns4:GageLen>
                  </xsl:if>
                </ns4:Test_results>
              </xsl:for-each>
            </ns4:Test_results>
            <ns4:LPNDetails>
              <xsl:for-each select="ns1:LPN_DETAILS/ns1:LPN_DETAILS_ITEM">
                <ns4:LPNDetail>
                  <xsl:if test="ns1:LPN_NUM">
                    <ns4:LPNNo>
                      <xsl:value-of select="ns1:LPN_NUM"/>
                    </ns4:LPNNo>
                  </xsl:if>
                  <xsl:if test="ns1:LPN_ID">
                    <ns4:LPNId>
                      <xsl:value-of select="ns1:LPN_ID"/>
                    </ns4:LPNId>
                  </xsl:if>
                </ns4:LPNDetail>
              </xsl:for-each>
            </ns4:LPNDetails>
            <!--ns4:C_Attributes>
              <ns4:C_Attribute>
                <xsl:if test="ns1:C_ATTRIBUTE6">
                  <ns4:Attribute6>
                    <xsl:value-of select="ns1:C_ATTRIBUTE6"/>
                  </ns4:Attribute6>
                </xsl:if>
                <xsl:if test="ns1:C_ATTRIBUTE7">
                  <ns4:Attribute7>
                    <xsl:value-of select="ns1:C_ATTRIBUTE7"/>
                  </ns4:Attribute7>
                </xsl:if>
                <xsl:if test="ns1:C_ATTRIBUTE8">
                  <ns4:Attribute8>
                    <xsl:value-of select="ns1:C_ATTRIBUTE8"/>
                  </ns4:Attribute8>
                </xsl:if>
                <xsl:if test="ns1:C_ATTRIBUTE9">
                  <ns4:Attribute9>
                    <xsl:value-of select="ns1:C_ATTRIBUTE9"/>
                  </ns4:Attribute9>
                </xsl:if>
                <xsl:if test="ns1:C_ATTRIBUTE10">
                  <ns4:Attribute10>
                    <xsl:value-of select="ns1:C_ATTRIBUTE10"/>
                  </ns4:Attribute10>
                </xsl:if>
                <xsl:if test="ns1:C_ATTRIBUTE11">
                  <ns4:Attribute11>
                    <xsl:value-of select="ns1:C_ATTRIBUTE11"/>
                  </ns4:Attribute11>
                </xsl:if>
                <xsl:if test="ns1:C_ATTRIBUTE12">
                  <ns4:Attribute12>
                    <xsl:value-of select="ns1:C_ATTRIBUTE12"/>
                  </ns4:Attribute12>
                </xsl:if>
                <xsl:if test="ns1:C_ATTRIBUTE13">
                  <ns4:Attribute13>
                    <xsl:value-of select="ns1:C_ATTRIBUTE13"/>
                  </ns4:Attribute13>
                </xsl:if>
                <xsl:if test="ns1:C_ATTRIBUTE14">
                  <ns4:Attribute14>
                    <xsl:value-of select="ns1:C_ATTRIBUTE14"/>
                  </ns4:Attribute14>
                </xsl:if>
              </ns4:C_Attribute>
            </ns4:C_Attributes-->
          </ns4:GmdResultPub>
        </xsl:for-each>
      </ns4:GmdResultsPub>
    </ns0:QueryQAResultsByBolNoRs>
  </xsl:template>
</xsl:stylesheet>
