<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_Call_XNUC_GMD_TSTRSLT_UPSERT_PKG"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns3="http://xmlns.eia.com/EO/common/Header/1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns5="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAO/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns2="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABS/NUC_NUC_EBizQualityResults_ABS/QualityResults/1.0"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns9="http://xmlns.oracle.com/pcbpel/adapter/apps/Nucor_ABF/NUC_EBizQualityResults_ABS/EBS_Call_XNUC_GMD_TSTRSLT_UPSERT_PKG"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns10="http://schemas.oracle.com/service/bpel/common">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/QualityResults.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QualityResultsUpdateRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualityResultsAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/EBS_Call_XNUC_GMD_TSTRSLT_UPSERT_PKG.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_Call_XNUC_GMD_TSTRSLT_UPSERT_PKG"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE APR 11 10:47:37 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_SMPL_TST_RES>
        <tns:TXN_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:TxnID"/>
        </tns:TXN_ID>
        <tns:RECORD_SOURCE>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:record_source"/>
        </tns:RECORD_SOURCE>
        <tns:SAMPLE_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleId"/>
        </tns:SAMPLE_ID>
        <tns:SAMPLE_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleNo"/>
        </tns:SAMPLE_NO>
        <tns:TRANSACTION_NAME>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns3:HeaderRq/ns3:TransactionName"/>
        </tns:TRANSACTION_NAME>
        <tns:SRC_SYSTEM>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns3:HeaderRq/ns3:Source"/>
        </tns:SRC_SYSTEM>
        <tns:ORGANIZATION_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OrganizationId"/>
        </tns:ORGANIZATION_ID>
        <tns:LAB_ORGANIZATION_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:LabOrganizationId"/>
        </tns:LAB_ORGANIZATION_ID>
        <tns:ORGANIZATION_CODE>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OrganizationCode"/>
        </tns:ORGANIZATION_CODE>
        <tns:SAMPLE_SOURCE>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleSource"/>
        </tns:SAMPLE_SOURCE>
        <tns:ITEM_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:item_id"/>
        </tns:ITEM_ID>
        <tns:ITEM_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:item_no"/>
        </tns:ITEM_NO>
        <tns:BATCH_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:BatchID"/>
        </tns:BATCH_ID>
        <tns:BATCH_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:BatchNO"/>
        </tns:BATCH_NO>
        <tns:STEP_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:StepID"/>
        </tns:STEP_ID>
        <tns:STEP_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:StepNO"/>
        </tns:STEP_NO>
        <tns:CHARGE>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:Charge"/>
        </tns:CHARGE>
        <tns:SOURCE_SUBINVENTORY>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SourceSubInventory"/>
        </tns:SOURCE_SUBINVENTORY>
        <tns:PARENT_LOT>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ParentLotNO"/>
        </tns:PARENT_LOT>
        <tns:RECIPE_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ReceipeNO"/>
        </tns:RECIPE_NO>
        <tns:RECIPE_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:receipeID"/>
        </tns:RECIPE_ID>
        <tns:LOT_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:LotNo"/>
        </tns:LOT_NO>
        <tns:FORMULA_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:FormulaNO"/>
        </tns:FORMULA_NO>
        <tns:FORMULA_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:FormulaID"/>
        </tns:FORMULA_ID>
        <tns:ROUTING_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:RoutingNO"/>
        </tns:ROUTING_NO>
        <tns:ROUTING_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:RoutingID"/>
        </tns:ROUTING_ID>
        <tns:OPRN_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OprnNO"/>
        </tns:OPRN_NO>
        <tns:OPRN_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OprnID"/>
        </tns:OPRN_ID>
        <tns:LPN_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:LpnNO"/>
        </tns:LPN_NO>
        <tns:LPN_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:LpnID"/>
        </tns:LPN_ID>
        <tns:RETAIN_AS>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:RetainAS"/>
        </tns:RETAIN_AS>
        <tns:REVISION>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:revision"/>
        </tns:REVISION>
        <tns:PRIORITY>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:Priority"/>
        </tns:PRIORITY>
        <tns:SAMPLE_QTY>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleQTY"/>
        </tns:SAMPLE_QTY>
        <tns:REMAINING_QTY>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:RemainingQTY"/>
        </tns:REMAINING_QTY>
        <tns:SAMPLE_QTY_UOM>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleQtyUOM"/>
        </tns:SAMPLE_QTY_UOM>
        <tns:SAMPLE_QTY_UNIT_O_MEAS>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleQtyUnitOfMeasure"/>
        </tns:SAMPLE_QTY_UNIT_O_MEAS>
        <!--<tns:DATE_DRAWN>
          <xsl:value-of select="xp20:current-date ( )"/>
        </tns:DATE_DRAWN>
        <tns:RETRIEVAL_DATE>
          <xsl:value-of select="xp20:current-date ( )"/>
        </tns:RETRIEVAL_DATE>
        <tns:DATE_RECEIVED>
          <xsl:value-of select="xp20:current-date ( )"/>
        </tns:DATE_RECEIVED>
        <tns:DATE_REQUIRED>
          <xsl:value-of select="xp20:current-date ( )"/>
        </tns:DATE_REQUIRED>
        <tns:EXPIRATION_DATE>
          <xsl:value-of select="xp20:current-date ( )"/>
        </tns:EXPIRATION_DATE>-->
        <tns:SAMPLE_INSTANCE>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleInstance"/>
        </tns:SAMPLE_INSTANCE>
        <tns:EXTERNAL_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ExternalID"/>
        </tns:EXTERNAL_ID>
        <tns:STORAGE_ORGANIZATION_CODE>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:StorageOrganizationCode"/>
        </tns:STORAGE_ORGANIZATION_CODE>
        <tns:STORAGE_ORGANIZATION_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:StorageOrganizationID"/>
        </tns:STORAGE_ORGANIZATION_ID>
        <tns:STORAGE_SUBINVENTORY>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:StorageSubInventory"/>
        </tns:STORAGE_SUBINVENTORY>
        <tns:SAMPLER>
          <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm', 'DIVISION', /ns0:QualityResultsUpdateRq/ns3:HeaderRq/ns3:MillName, 'EBS_USER_NAME','')"/>
        </tns:SAMPLER>
        <tns:SAMPLER_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SamplerID"/>
        </tns:SAMPLER_ID>
        <tns:SAMPLE_APPROVER>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleApprover"/>
        </tns:SAMPLE_APPROVER>
        <tns:SAMPLE_APPROVER_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleApproverID"/>
        </tns:SAMPLE_APPROVER_ID>
        <tns:INV_APPROVER>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:InvApprover"/>
        </tns:INV_APPROVER>
        <tns:INV_APPROVER_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:InvApproverID"/>
        </tns:INV_APPROVER_ID>
        <tns:SOURCE_COMMENT>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SourceComment"/>
        </tns:SOURCE_COMMENT>
        <tns:CUSTOMER_NAME>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:CustomerName"/>
        </tns:CUSTOMER_NAME>
        <tns:CUST_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:CustID"/>
        </tns:CUST_ID>
        <tns:OPERATING_UNIT>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OperatingUnit"/>
        </tns:OPERATING_UNIT>
        <tns:ORG_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OrgID"/>
        </tns:ORG_ID>
        <tns:SHIP_TO_NAME>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ShipToName"/>
        </tns:SHIP_TO_NAME>
        <tns:SHIP_TO_SITE_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ShipToSiteID"/>
        </tns:SHIP_TO_SITE_ID>
        <tns:ORDER_NUMBER>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OrderNo"/>
        </tns:ORDER_NUMBER>
        <tns:ORDER_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OrderID"/>
        </tns:ORDER_ID>
        <tns:ORDER_LINE_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OrderLineNO"/>
        </tns:ORDER_LINE_NO>
        <tns:ORDER_LINE_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:OrderLineID"/>
        </tns:ORDER_LINE_ID>
        <tns:SUBINVENTORY>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SubInventory"/>
        </tns:SUBINVENTORY>
        <tns:SUPPLIER_NAME>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SupplierName"/>
        </tns:SUPPLIER_NAME>
        <tns:SUPPLIER_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SupplierID"/>
        </tns:SUPPLIER_ID>
        <tns:SUPPLIER_SITE>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SupplierSite"/>
        </tns:SUPPLIER_SITE>
        <tns:SUPPLIER_SITE_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SupplierSiteID"/>
        </tns:SUPPLIER_SITE_ID>
        <tns:SUPPLIER_LOT_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SupplierLotNO"/>
        </tns:SUPPLIER_LOT_NO>
        <tns:PO_NUMBER>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:PoNumber"/>
        </tns:PO_NUMBER>
        <tns:PO_HEADER_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:PoHeaderID"/>
        </tns:PO_HEADER_ID>
        <tns:PO_LINE_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:PoLineNO"/>
        </tns:PO_LINE_NO>
        <tns:PO_LINE_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:PoLineID"/>
        </tns:PO_LINE_ID>
        <tns:RECEIPT_NO>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ReceiptNO"/>
        </tns:RECEIPT_NO>
        <tns:RECEIPT_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ReceiptID"/>
        </tns:RECEIPT_ID>
        <tns:RECEIPT_LINE_NUM>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ReceiptLineNO"/>
        </tns:RECEIPT_LINE_NUM>
        <tns:RECEIPT_LINE_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:ReceiptLineID"/>
        </tns:RECEIPT_LINE_ID>
        <tns:TEST_RESULTS>
          <xsl:for-each select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:Test_results/ns5:Test_results">
            <tns:TEST_RESULTS_ITEM>
              <tns:SEQ_NO>
                <xsl:value-of select="ns5:SeqNO"/>
              </tns:SEQ_NO>
              <tns:TEST_CODE>
                <xsl:value-of select="ns5:TestCode"/>
              </tns:TEST_CODE>
              <tns:TEST_ID>
                <xsl:value-of select="ns5:TestID"/>
              </tns:TEST_ID>
              <tns:TESTER>
                <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm', 'DIVISION', /ns0:QualityResultsUpdateRq/ns3:HeaderRq/ns3:MillName, 'EBS_USER_NAME','')"/>
              </tns:TESTER>
              <tns:TESTER_ID>
                <xsl:value-of select="ns5:TesterID"/>
              </tns:TESTER_ID>
              <tns:RESULT_VALUE>
                <xsl:value-of select="ns5:ResultValue"/>
              </tns:RESULT_VALUE>
              <tns:TEST_QTY>
                <xsl:value-of select="ns5:TestQTY"/>
              </tns:TEST_QTY>
              <tns:RESULT_DATE>
                <xsl:value-of select="xp20:current-date ( )"/>
              </tns:RESULT_DATE>
              <tns:EVAL_IND>
                <xsl:value-of select="ns5:EvalInd"/>
              </tns:EVAL_IND>
              <tns:ACTION_CODE>
                <xsl:value-of select="ns5:ActionCode"/>
              </tns:ACTION_CODE>
              <tns:TEST_REPLICATE>
                <xsl:value-of select="ns5:Replicate"/>
              </tns:TEST_REPLICATE>
            </tns:TEST_RESULTS_ITEM>
          </xsl:for-each>
        </tns:TEST_RESULTS>
      </tns:P_SMPL_TST_RES>
      <tns:P_APPS_INIT>
        <!--<tns:USER_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns0:AppsContext/ns6:UserId"/>
        </tns:USER_ID>
        <tns:USER_NAME>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns0:AppsContext/ns6:UserName"/>
        </tns:USER_NAME>
        <tns:RESPONSIBILITY_NAME>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns0:AppsContext/ns6:ResponsibilityName"/>
        </tns:RESPONSIBILITY_NAME>
        <tns:ORG_ID>
          <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns0:AppsContext/ns6:OrgId"/>
        </tns:ORG_ID> -->
        <tns:USER_NAME>
          <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm', 'DIVISION', /ns0:QualityResultsUpdateRq/ns3:HeaderRq/ns3:MillName, 'EBS_USER_NAME','')"/>
        </tns:USER_NAME>
        <tns:RESPONSIBILITY_NAME>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_ORG_RESP_NAME.dvm', 'DIVISION', /ns0:QualityResultsUpdateRq/ns3:HeaderRq/ns3:MillName, 'EBS_RESP_NAME', 'Quality Manager' , 'EBS_FUNCTION_AREA', 'Quality')"/>
        </tns:RESPONSIBILITY_NAME>
        <tns:ORG_ID>
          <xsl:value-of select="dvm:lookupValue('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_ORG_RESP_NAME.dvm', 'DIVISION', /ns0:QualityResultsUpdateRq/ns3:HeaderRq/ns3:MillName, 'EBS_ORG_ID','85' , 'EBS_FUNCTION_AREA', 'Quality')"/>
        </tns:ORG_ID>
      </tns:P_APPS_INIT>
      <tns:P_SAMPLE_ID>
        <xsl:value-of select="/ns0:QualityResultsUpdateRq/ns5:GmdResultsPub/ns5:GmdResultPub/ns5:SampleId"/>
      </tns:P_SAMPLE_ID>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
