<?xml version="1.0" encoding="UTF-8" ?>
<!--$Header$-->
<definitions
     name="EIAAsyncErrorHandlingBPELProcess"
     targetNamespace="http://xmlns.eia.com/Infrastructure/EIAAsyncErrorHandlingBPELProcess/1.0"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://xmlns.eia.com/EO/Common/1.0"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:client="http://xmlns.eia.com/Infrastructure/EIAAsyncErrorHandlingBPELProcess/1.0"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.eia.com/EO/Common/1.0" schemaLocation="../../EO/common/Common.xsd"/>
        </xsd:schema>
    </types>
    <message name="EIAAsyncErrorHandlingBPELProcessRequestMessage">
        <part name="FaultMessage" element="ns1:Fault"/>
    </message>
    <portType name="EIAAsyncErrorHandlingBPELProcess">
        <operation name="processFault">
            <input message="client:EIAAsyncErrorHandlingBPELProcessRequestMessage"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="EIAAsyncErrorHandlingBPELProcess">
        <plnk:role name="EIAAsyncErrorHandlingBPELProcessProvider">
            <plnk:portType name="client:EIAAsyncErrorHandlingBPELProcess"/>
        </plnk:role>
    </plnk:partnerLinkType>
   
    <binding name="EIAAsyncErrorHandlingBPELProcessBinding"
    	type="client:EIAAsyncErrorHandlingBPELProcess">
    	<soap:binding style="document"
    		transport="http://schemas.xmlsoap.org/soap/http" />
    	<operation name="processFault">
    		<soap:operation
    			soapAction="http://xmlns.eia.com/Infrastructure/EIAAsyncErrorHandlingBPELProcess/1.0/processFault" />
    		<input>
    			<soap:body use="literal" />
    		</input>
    	</operation>
    </binding>
    <service name="processFault_ep">
        <port name="EIAAsyncErrorHandlingBPELProcess_pt"
        	binding="client:EIAAsyncErrorHandlingBPELProcessBinding">
        	<soap:address location="www.example.org" />
        </port>
    </service>
</definitions>

