<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CreateSalesOrderABF"
     targetNamespace="http://xmlns.eia.com/NucorSOA/NUC_SalesOrder_Corporate_EBS_ABF/CreateSalesOrderABF/1.0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.eia.com/NucorSOA/NUC_SalesOrder_Corporate_EBS_ABF/CreateSalesOrderABF/1.0"
     xmlns:ns1="http://xmlns.eia.com/ABF/CreateSalesOrder_ABF/1.0/SalesOrder"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     
     xmlns:ns3="http://www.nucor.com/scmschemas/CorpXMLOrder.xsd"
    >
    <plnk:partnerLinkType name="CreateSalesOrderABF">
        <plnk:role name="CreateSalesOrderABFProvider" portType="client:CreateSalesOrderABF"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.eia.com/ABF/CreateSalesOrder_ABF/1.0/SalesOrder" schemaLocation="../Schemas/input_order.xsd"/>
        </schema>
        <!--xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.nucor.com/scmschemas/XMLOrder.xsd" schemaLocation="oramds:/apps/Schema/Enterprise/External/EcommerceSalesOrder/1.0/Weborder.xsd"/>
        </xsd:schema-->
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.nucor.com/scmschemas/CorpXMLOrder.xsd" schemaLocation="oramds:/apps/EIAMetadata/AO/Corporate/O2C/Orders/V1.0/Weborder.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="CreateSalesOrderABFRequestMessage">
        <wsdl:part name="payload" element="ns1:Input"/>
    </wsdl:message>
    <wsdl:message name="CreateSalesOrderABFResponseMessage">
        <wsdl:part name="payload" element="ns1:Output"/>
    </wsdl:message>
    <wsdl:portType name="CreateSalesOrderABF">
        <wsdl:operation name="process">
            <wsdl:input message="client:CreateSalesOrderABFRequestMessage"/>
            <wsdl:output message="client:CreateSalesOrderABFResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
