<wsdl:definitions
     name="DB_Select_API_WorkOrder_Status"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSSEA_WorkOrder_EBizBatchJobs_ABF/DB_Select_API_WorkOrder_Status"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Manish/NSSEA_WorkOrder_EBizBatchJobs_ABF/DB_Select_API_WorkOrder_Status"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_API_WorkOrder_Status"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Select_API_WorkOrder_Status_plt" >
    <plt:role name="DB_Select_API_WorkOrder_Status_role" >
      <plt:portType name="tns:DB_Select_API_WorkOrder_Status_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_Select_API_WorkOrder_Status_plt" >
    <plt:role name="DB_Select_API_WorkOrder_Status_role" >
      <plt:portType name="tns:DB_Select_API_WorkOrder_Status_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_Select_API_WorkOrder_Status_plt" >
    <plt:role name="DB_Select_API_WorkOrder_Status_role" >
      <plt:portType name="tns:DB_Select_API_WorkOrder_Status_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_Select_API_WorkOrder_Status_plt" >
    <plt:role name="DB_Select_API_WorkOrder_Status_role" >
      <plt:portType name="tns:DB_Select_API_WorkOrder_Status_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_Select_API_WorkOrder_Status_plt" >
    <plt:role name="DB_Select_API_WorkOrder_Status_role" >
      <plt:portType name="tns:DB_Select_API_WorkOrder_Status_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_Select_API_WorkOrder_Status_plt" >
    <plt:role name="DB_Select_API_WorkOrder_Status_role" >
      <plt:portType name="tns:DB_Select_API_WorkOrder_Status_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_API_WorkOrder_Status" schemaLocation="../Schemas/DB_Select_API_WorkOrder_Status.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_API_WorkOrder_Status" schemaLocation="../Schemas/DB_Select_API_WorkOrder_Status.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_API_WorkOrder_Status" schemaLocation="../Schemas/DB_Select_API_WorkOrder_Status.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_API_WorkOrder_Status" schemaLocation="../Schemas/DB_Select_API_WorkOrder_Status.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_API_WorkOrder_Status" schemaLocation="../Schemas/DB_Select_API_WorkOrder_Status.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_API_WorkOrder_Status" schemaLocation="../Schemas/DB_Select_API_WorkOrder_Status.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_Select_API_WorkOrder_StatusInput_msg">
        <wsdl:part name="DB_Select_API_WorkOrder_StatusInput_msg" element="db:DB_Select_API_WorkOrder_StatusInput"/>
    </wsdl:message>
    <wsdl:message name="DB_Select_API_WorkOrder_StatusOutputCollection_msg">
        <wsdl:part name="DB_Select_API_WorkOrder_StatusOutputCollection" element="db:DB_Select_API_WorkOrder_StatusOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Select_API_WorkOrder_Status_ptt">
        <wsdl:operation name="DB_Select_API_WorkOrder_Status">
            <wsdl:input message="tns:DB_Select_API_WorkOrder_StatusInput_msg"/>
            <wsdl:output message="tns:DB_Select_API_WorkOrder_StatusOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
