<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:eia="http://xmlns.eia.com/extensions/1.0" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/NucorSOAMacBranches/EIAJMSErroHandlingBPELProcess/JMS_ConsumeEIAErrorTopic" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:imp1="http://xmlns.eia.com/EO/Common/1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:client="http://xmlns.eia.com/Infrastructure/EIAAsyncErrorHandlingBPELProcess/1.0" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns pc plt wsdl imp1 jca xsd soap client bpws xp20 eia bpel bpm utl ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../JMS_ConsumeEIAErrorTopic.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Fault" namespace="http://xmlns.eia.com/EO/Common/1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/Infrastracture/wsdls/EIAAsyncErrorHandlingBPELProcessV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Fault" namespace="http://xmlns.eia.com/EO/Common/1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI SEP 04 18:57:03 CDT 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <imp1:Fault>
      <imp1:FaultMessage>
        <xsl:if test="/imp1:Fault/imp1:FaultMessage/imp1:Code">
          <imp1:Code>
            <xsl:value-of select="/imp1:Fault/imp1:FaultMessage/imp1:Code"/>
          </imp1:Code>
        </xsl:if>
        <xsl:if test="/imp1:Fault/imp1:FaultMessage/imp1:Text">
          <xsl:for-each select="/imp1:Fault/imp1:FaultMessage/imp1:Text">
            <imp1:Text>
              <xsl:value-of select="."/>
            </imp1:Text>
          </xsl:for-each>
        </xsl:if>
        <xsl:if test="/imp1:Fault/imp1:FaultMessage/imp1:Severity">
          <imp1:Severity>
            <xsl:value-of select="/imp1:Fault/imp1:FaultMessage/imp1:Severity"/>
          </imp1:Severity>
        </xsl:if>
        <xsl:if test="/imp1:Fault/imp1:FaultMessage/imp1:Stack">
          <imp1:Stack>
            <xsl:value-of select="/imp1:Fault/imp1:FaultMessage/imp1:Stack"/>
          </imp1:Stack>
        </xsl:if>
      </imp1:FaultMessage>
      <imp1:ReportingDateTime>
        <xsl:value-of select="xp20:current-dateTime()"/>
      </imp1:ReportingDateTime>
      <imp1:CorrectiveAction>
        <xsl:value-of select="utl:getServiceProperty(/imp1:Fault/imp1:FaultingService/imp1:Process,&quot;ERROR_CORRECTION_RECOMMENDATION&quot;)"/>
      </imp1:CorrectiveAction>
      <xsl:if test="/imp1:Fault/imp1:FaultingService">
        <imp1:FaultingService>
          <xsl:if test="/imp1:Fault/imp1:FaultingService/imp1:ID">
            <imp1:ID>
              <xsl:value-of select="/imp1:Fault/imp1:FaultingService/imp1:ID"/>
            </imp1:ID>
          </xsl:if>
          <xsl:if test="/imp1:Fault/imp1:FaultingService/imp1:Process">
            <imp1:Process>
              <xsl:value-of select="/imp1:Fault/imp1:FaultingService/imp1:Process"/>
            </imp1:Process>
          </xsl:if>
          <imp1:InstanceID>
            <xsl:value-of select="/imp1:Fault/imp1:FaultingService/imp1:InstanceID"/>
          </imp1:InstanceID>
        </imp1:FaultingService>
      </xsl:if>
    </imp1:Fault>
  </xsl:template>
</xsl:stylesheet>