<wsdl:definitions
     name="DB_API_SPEC_CONTROL"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NSSEA/NSSEA_SubscribeQualitySpecs_QMOS_ABF/DB_API_SPEC_CONTROL"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NSSEA/NSSEA_SubscribeQualitySpecs_QMOS_ABF/DB_API_SPEC_CONTROL"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_API_SPEC_CONTROL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_API_SPEC_CONTROL_plt" >
    <plt:role name="DB_API_SPEC_CONTROL_role" >
      <plt:portType name="tns:DB_API_SPEC_CONTROL_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_API_SPEC_CONTROL" schemaLocation="../Schemas/DB_API_SPEC_CONTROL.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_API_SPEC_CONTROLInput_msg">
        <wsdl:part name="DB_API_SPEC_CONTROLInput_msg" element="db:DB_API_SPEC_CONTROLInput"/>
    </wsdl:message>
    <wsdl:portType name="DB_API_SPEC_CONTROL_ptt">
        <wsdl:operation name="DB_API_SPEC_CONTROL">
            <wsdl:input message="tns:DB_API_SPEC_CONTROLInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
