<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/apps/otm"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_WshOtmInboundGrp"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:client="http://xmlns.oracle.com/apps/wsh/inbound/WshReceivePShipmentFromOtm"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/OTMDEC/ReceivePShipmentFromOtm/DB_WshOtmInboundGrp">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WshReceivePShipmentFromOtm.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../partnerWsdls/DB_WshOtmInboundGrp.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_WshOtmInboundGrp"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JAN 04 22:33:13 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="BusinessDomain"/>
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_INT_TRIP_INFO>
        <xsl:for-each select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment">
          <tns:P_INT_TRIP_INFO_ITEM>
            <tns:SHIPMENT_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:ShipmentGid/ns0:Gid/ns0:Xid"/>
            </tns:SHIPMENT_XID>
            <tns:SHIPMENT_NAME>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:ShipmentName"/>
            </tns:SHIPMENT_NAME>
            <tns:SHIPMENT_REFNUM>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:ShipmentRefnum/ns0:ShipmentRefnumValue"/>
            </tns:SHIPMENT_REFNUM>
            <tns:TRANSACTION_CODE>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:TransactionCode"/>
            </tns:TRANSACTION_CODE>
            <tns:SERVICE_PROVIDER_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:ServiceProviderGid/ns0:Gid/ns0:Xid"/>
            </tns:SERVICE_PROVIDER_XID>
            <tns:CONTACT_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:ContactGid/ns0:Gid/ns0:Xid"/>
            </tns:CONTACT_XID>
            <tns:TRANSPORT_MODE_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:TransportModeGid/ns0:Gid/ns0:Xid"/>
            </tns:TRANSPORT_MODE_XID>
            <tns:RATE_SERVICE_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:RateServiceGid/ns0:Gid/ns0:Xid"/>
            </tns:RATE_SERVICE_XID>
            <tns:WEIGHT_UOM_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:TotalWeightVolume/ns0:WeightVolume/ns0:Weight/ns0:WeightUOMGid/ns0:Gid/ns0:Xid"/>
            </tns:WEIGHT_UOM_XID>
            <tns:VOLUME>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:TotalWeightVolume/ns0:WeightVolume/ns0:Volume/ns0:VolumeValue"/>
            </tns:VOLUME>
            <tns:VOLUME_UOM_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:TotalWeightVolume/ns0:WeightVolume/ns0:Volume/ns0:VolumeUOMGid/ns0:Gid/ns0:Xid"/>
            </tns:VOLUME_UOM_XID>
            <tns:SHIPUNIT_COUNT>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:TotalShipUnitCount"/>
            </tns:SHIPUNIT_COUNT>
            <tns:PAYMENT_CODE_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:CommercialTerms/ns0:PaymentMethodCodeGid/ns0:Gid/ns0:Xid"/>
            </tns:PAYMENT_CODE_XID>
            <tns:STOP_COUNT>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:StopCount"/>
            </tns:STOP_COUNT>
            <tns:RELEASE_COUNT>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:NumOrderReleases"/>
            </tns:RELEASE_COUNT>
            <tns:VOYAGE_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:VoyageGid/ns0:Gid/ns0:Xid"/>
            </tns:VOYAGE_XID>
            <tns:VESSEL_XID>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:VesselGid/ns0:Gid/ns0:Xid"/>
            </tns:VESSEL_XID>
            <tns:EQUIPMENT_XID>
              <xsl:value-of select="ns0:SEquipment/ns0:EquipmentGid/ns0:Gid/ns0:Xid"/>
            </tns:EQUIPMENT_XID>
            <tns:EQUIPMENT_INITIAL>
              <xsl:value-of select="ns0:SEquipment/ns0:EquipmentInitial"/>
            </tns:EQUIPMENT_INITIAL>
            <tns:EQUIPMENT_NUMBER>
              <xsl:value-of select="ns0:SEquipment/ns0:EquipmentNumber"/>
            </tns:EQUIPMENT_NUMBER>
            <tns:EQUIPMENT_TYPE_XID>
              <xsl:value-of select="ns0:SEquipment/ns0:EquipmentTypeGid/ns0:Gid/ns0:Xid"/>
            </tns:EQUIPMENT_TYPE_XID>
            <tns:EQUIPMENT_GROUP_XID>
              <xsl:value-of select="ns0:SEquipment/ns0:EquipmentGroupGid/ns0:Gid/ns0:Xid"/>
            </tns:EQUIPMENT_GROUP_XID>
            <tns:EQUIPMENT_SEAL>
              <xsl:value-of select="ns0:SEquipment/ns0:SEquipmentSeal/ns0:SealNumber"/>
            </tns:EQUIPMENT_SEAL>
            <tns:PLANNED_FLAG>F</tns:PLANNED_FLAG>
            <tns:GROSS_WEIGHT>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:TotalWeightVolume/ns0:WeightVolume/ns0:Weight/ns0:WeightValue"/>
            </tns:GROSS_WEIGHT>
            <tns:NET_WEIGHT>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:TotalNetWeightVolume/ns0:Weight/ns0:WeightValue"/>
            </tns:NET_WEIGHT>
            <tns:TRIP_ID></tns:TRIP_ID>
            <tns:ATTRIBUTE_CATEGORY>
              <xsl:value-of select="$BusinessDomain"/>
            </tns:ATTRIBUTE_CATEGORY>
            <tns:ATTRIBUTE1></tns:ATTRIBUTE1>
            <tns:ATTRIBUTE2>New</tns:ATTRIBUTE2>
            <tns:ATTRIBUTE3></tns:ATTRIBUTE3>
            <tns:ATTRIBUTE4>New Shipment</tns:ATTRIBUTE4>
            <tns:ATTRIBUTE5></tns:ATTRIBUTE5>
            <tns:ATTRIBUTE6>
              <xsl:value-of select="ns0:ShipmentHeader/ns0:FlexFieldStrings/ns0:Attribute6"/>
            </tns:ATTRIBUTE6>
            <tns:ATTRIBUTE7></tns:ATTRIBUTE7>
            <tns:ATTRIBUTE8></tns:ATTRIBUTE8>
            <tns:ATTRIBUTE9></tns:ATTRIBUTE9>
            <tns:ATTRIBUTE10></tns:ATTRIBUTE10>
            <tns:ATTRIBUTE11></tns:ATTRIBUTE11>
            <tns:ATTRIBUTE12></tns:ATTRIBUTE12>
            <tns:ATTRIBUTE13></tns:ATTRIBUTE13>
            <tns:ATTRIBUTE14></tns:ATTRIBUTE14>
            <tns:ATTRIBUTE15></tns:ATTRIBUTE15>
            <tns:SHIPMENT_STOPS>
              <xsl:for-each select="ns0:ShipmentStop">
                <tns:SHIPMENT_STOPS_ITEM>
                  <tns:STOP_LOCATION_XID>
                    <xsl:value-of select="ns0:LocationRef/ns0:LocationGid/ns0:Gid/ns0:Xid"/>
                  </tns:STOP_LOCATION_XID>
                  <tns:STOP_SEQUENCE_NUMBER>
                    <xsl:value-of select="ns0:ExtStopSequence"/>
                  </tns:STOP_SEQUENCE_NUMBER>
                  <tns:TRANSACTION_CODE>
                    <xsl:value-of select="ns0:TransactionCode"/>
                  </tns:TRANSACTION_CODE>
                  <tns:PLANNED_ARRIVAL_TIME>
                    <xsl:value-of select="ns0:ArrivalTime/ns0:EventTime/ns0:PlannedTime/ns0:GLogDate"/>
                  </tns:PLANNED_ARRIVAL_TIME>
                  <tns:PLANNED_DEPARTURE_TIME>
                    <xsl:value-of select="ns0:DepartureTime/ns0:EventTime/ns0:PlannedTime/ns0:GLogDate"/>
                  </tns:PLANNED_DEPARTURE_TIME>
                  <tns:ACTUAL_ARRIVAL_TIME>
                    <xsl:value-of select="ns0:ArrivalTime/ns0:EventTime/ns0:ActualTime/ns0:GLogDate"/>
                  </tns:ACTUAL_ARRIVAL_TIME>
                  <tns:ACTUAL_DEPARTURE_TIME>
                    <xsl:value-of select="ns0:DepartureTime/ns0:EventTime/ns0:ActualTime/ns0:GLogDate"/>
                  </tns:ACTUAL_DEPARTURE_TIME>
                  <xsl:if test="starts-with(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:ShipmentStop/ns0:Appointment/ns0:AppointmentInfo/ns0:LocationResourceGid/ns0:Gid/ns0:Xid,'DOCK-')">
                    <tns:DOCK_DOOR_XID>
                      <xsl:value-of select="ns0:Appointment/ns0:AppointmentInfo/ns0:LocationResourceGid/ns0:Gid/ns0:Xid"/>
                    </tns:DOCK_DOOR_XID>
                  </xsl:if>
                  <xsl:if test="starts-with(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:ShipmentStop/ns0:Appointment/ns0:AppointmentInfo/ns0:LocationResourceGid/ns0:Gid/ns0:Xid,'DOCK-')">
                    <tns:START_TIME>
                      <xsl:value-of select="ns0:Appointment/ns0:AppointmentInfo/ns0:StartTime/ns0:GLogDate"/>
                    </tns:START_TIME>
                  </xsl:if>
                  <xsl:if test="starts-with(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:ShipmentStop/ns0:Appointment/ns0:AppointmentInfo/ns0:LocationResourceGid/ns0:Gid/ns0:Xid,'DOCK-')">
                    <tns:END_TIME>
                      <xsl:value-of select="ns0:Appointment/ns0:AppointmentInfo/ns0:EndTime/ns0:GLogDate"/>
                    </tns:END_TIME>
                  </xsl:if>
                  <tns:ATTRIBUTE_CATEGORY>
                    <xsl:value-of select="$BusinessDomain"/>
                  </tns:ATTRIBUTE_CATEGORY>
                  <tns:ATTRIBUTE1></tns:ATTRIBUTE1>
                  <tns:ATTRIBUTE2></tns:ATTRIBUTE2>
                  <tns:ATTRIBUTE3></tns:ATTRIBUTE3>
                  <tns:ATTRIBUTE4></tns:ATTRIBUTE4>
                  <tns:ATTRIBUTE5></tns:ATTRIBUTE5>
                  <tns:ATTRIBUTE6></tns:ATTRIBUTE6>
                  <tns:ATTRIBUTE7></tns:ATTRIBUTE7>
                  <tns:ATTRIBUTE8></tns:ATTRIBUTE8>
                  <tns:ATTRIBUTE9></tns:ATTRIBUTE9>
                  <tns:ATTRIBUTE10></tns:ATTRIBUTE10>
                  <tns:ATTRIBUTE11></tns:ATTRIBUTE11>
                  <tns:ATTRIBUTE12>
                    <xsl:value-of select="ns0:FlexFieldStrings/ns0:Attribute1"/>
                  </tns:ATTRIBUTE12>
                  <tns:ATTRIBUTE13></tns:ATTRIBUTE13>
                  <tns:ATTRIBUTE14></tns:ATTRIBUTE14>
                  <tns:ATTRIBUTE15></tns:ATTRIBUTE15>
                </tns:SHIPMENT_STOPS_ITEM>
              </xsl:for-each>
            </tns:SHIPMENT_STOPS>
            <tns:SHIPMENT_SHIP_UNITS>
              <xsl:for-each select="ns0:ShipUnit">
                <tns:SHIPMENT_SHIP_UNITS_ITEM>
                  <tns:SHIP_UNIT_XID>
                    <xsl:value-of select="ns0:ShipUnitGid/ns0:Gid/ns0:Xid"/>
                  </tns:SHIP_UNIT_XID>
                  <tns:TRANSACTION_CODE>
                    <xsl:value-of select="ns0:TransactionCode"/>
                  </tns:TRANSACTION_CODE>
                  <tns:SHIP_FROM_LOCATION_XID>
                    <xsl:value-of select="ns0:ShipFromLocationRef/ns0:LocationRef/ns0:LocationGid/ns0:Gid/ns0:Xid"/>
                  </tns:SHIP_FROM_LOCATION_XID>
                  <tns:SHIP_TO_LOCATION_XID>
                    <xsl:value-of select="ns0:ShipToLocationRef/ns0:LocationRef/ns0:LocationGid/ns0:Gid/ns0:Xid"/>
                  </tns:SHIP_TO_LOCATION_XID>
                  <tns:RELEASE_XID>
                    <xsl:value-of select="ns0:ShipUnitContent/ns0:ReleaseGid/ns0:Gid/ns0:Xid"/>
                  </tns:RELEASE_XID>
                </tns:SHIPMENT_SHIP_UNITS_ITEM>
              </xsl:for-each>
            </tns:SHIPMENT_SHIP_UNITS>
            <tns:SHIPMENT_RELEASES>
              <xsl:for-each select="ns0:Release">
                <tns:SHIPMENT_RELEASES_ITEM>
                  <tns:RELEASE_XID>
                    <xsl:value-of select="ns0:ReleaseGid/ns0:Gid/ns0:Xid"/>
                  </tns:RELEASE_XID>
                  <tns:TRANSACTION_CODE>
                    <xsl:value-of select="ns0:TransactionCode"/>
                  </tns:TRANSACTION_CODE>
                  <tns:SHIP_FROM_LOCATION_XID>
                    <xsl:value-of select="ns0:ShipFromLocationRef/ns0:LocationRef/ns0:LocationGid/ns0:Gid/ns0:Xid"/>
                  </tns:SHIP_FROM_LOCATION_XID>
                  <tns:SHIP_TO_LOCATION_XID>
                    <xsl:value-of select="ns0:ShipToLocationRef/ns0:LocationRef/ns0:LocationGid/ns0:Gid/ns0:Xid"/>
                  </tns:SHIP_TO_LOCATION_XID>
                  <xsl:for-each select="ns0:ReleaseRefnum">
                    <xsl:if test='ns0:ReleaseRefnumQualifierGid/ns0:Gid/ns0:Xid = "REVNUM"'>
                      <tns:RELEASE_REFNUM>
                        <xsl:value-of select="ns0:ReleaseRefnumValue"/>
                      </tns:RELEASE_REFNUM>
                    </xsl:if>
                  </xsl:for-each>
                  <tns:EARLY_PICKUP_DATE>
                    <xsl:value-of select="ns0:TimeWindow/ns0:EarlyPickupDate"/>
                  </tns:EARLY_PICKUP_DATE>
                  <tns:LATE_PICKUP_DATE>
                    <xsl:value-of select="ns0:TimeWindow/ns0:LatePickupDate"/>
                  </tns:LATE_PICKUP_DATE>
                  <tns:EARLY_DELIVERY_DATE>
                    <xsl:value-of select="ns0:TimeWindow/ns0:EarlyDeliveryDate"/>
                  </tns:EARLY_DELIVERY_DATE>
                  <tns:LATE_DELIVERY_DATE>
                    <xsl:value-of select="ns0:TimeWindow/ns0:LateDeliveryDate"/>
                  </tns:LATE_DELIVERY_DATE>
                  <tns:RELEASE_FREIGHT_COSTS>
                    <xsl:for-each select="ns0:ReleaseAllocationInfo/ns0:ReleaseAllocByType">
                      <xsl:if test='ns0:AllocTypeQualGid/ns0:Gid/ns0:Xid = "PLANNING"'>
                        <xsl:for-each select="ns0:ReleaseAllocShipment">
                          <tns:RELEASE_FREIGHT_COSTS_ITEM>
                            <tns:SHIPMENT_XID>
                              <xsl:value-of select="ns0:ShipmentGid/ns0:Gid/ns0:Xid"/>
                            </tns:SHIPMENT_XID>
                            <tns:MONETARY_AMOUNT>
                              <xsl:value-of select="ns0:TotalAllocCost/ns0:FinancialAmount/ns0:MonetaryAmount"/>
                            </tns:MONETARY_AMOUNT>
                            <tns:CURRENCY_CODE>
                              <xsl:value-of select="ns0:TotalAllocCost/ns0:FinancialAmount/ns0:GlobalCurrencyCode"/>
                            </tns:CURRENCY_CODE>
                            <tns:BASE_RATE>
                              <xsl:value-of select="ns0:TotalAllocCost/ns0:FinancialAmount/ns0:RateToBase"/>
                            </tns:BASE_RATE>
                          </tns:RELEASE_FREIGHT_COSTS_ITEM>
                        </xsl:for-each>
                      </xsl:if>
                    </xsl:for-each>
                  </tns:RELEASE_FREIGHT_COSTS>
                </tns:SHIPMENT_RELEASES_ITEM>
              </xsl:for-each>
            </tns:SHIPMENT_RELEASES>
            <tns:STOP_LOCATIONS>
              <xsl:for-each select="ns0:Location">
                <tns:STOP_LOCATIONS_ITEM>
                  <tns:LOCATION_XID>
                    <xsl:value-of select="ns0:LocationGid/ns0:Gid/ns0:Xid"/>
                  </tns:LOCATION_XID>
                  <tns:LOCATION_NAME>
                    <xsl:value-of select="ns0:LocationName"/>
                  </tns:LOCATION_NAME>
                  <tns:TIMEZONE_XID>
                    <xsl:value-of select="ns0:Address/ns0:TimeZoneGid/ns0:Gid/ns0:Xid"/>
                  </tns:TIMEZONE_XID>
                  <tns:LATITUDE>
                    <xsl:value-of select="ns0:Address/ns0:Latitude"/>
                  </tns:LATITUDE>
                  <tns:LONGITUDE>
                    <xsl:value-of select="ns0:Address/ns0:Longitude"/>
                  </tns:LONGITUDE>
                </tns:STOP_LOCATIONS_ITEM>
              </xsl:for-each>
            </tns:STOP_LOCATIONS>
          </tns:P_INT_TRIP_INFO_ITEM>
        </xsl:for-each>
      </tns:P_INT_TRIP_INFO>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
