create or replace 
PACKAGE XXNUC_ARPT_SQL_FUNC_UTIL_PKG AS

/*
Description: Package used by SOA Webservices to aggregate customer balances into Aging buckets
Date: 4/29/2014
Author: KPIT
*/


	TYPE bucket_lines_Tbl is TABLE of iex_aging_buckets_pkg.bucket_lines_Rec;


type transactions_rec is record (
PAYMENT_SCHEDULE_ID	NUMBER(15)
,TRX_NUMBER	VARCHAR2(30)
,TRX_DATE	DATE
,TERMS_SEQUENCE_NUMBER	NUMBER(15)
,INVOICE_CURRENCY_CODE	VARCHAR2(15)
,EXCHANGE_RATE	NUMBER
,GL_DATE	DATE
,ATTRIBUTE_CATEGORY	VARCHAR2(30)
,ATTRIBUTE1	VARCHAR2(150)
,ATTRIBUTE2	VARCHAR2(150)
,ATTRIBUTE3	VARCHAR2(150)
,ATTRIBUTE4	VARCHAR2(150)
,ATTRIBUTE5	VARCHAR2(150)
,ATTRIBUTE6	VARCHAR2(150)
,ATTRIBUTE7	VARCHAR2(150)
,ATTRIBUTE8	VARCHAR2(150)
,ATTRIBUTE9	VARCHAR2(150)
,ATTRIBUTE10	VARCHAR2(150)
,ATTRIBUTE11	VARCHAR2(150)
,ATTRIBUTE12	VARCHAR2(150)
,ATTRIBUTE13	VARCHAR2(150)
,ATTRIBUTE14	VARCHAR2(150)
,ATTRIBUTE15	VARCHAR2(150)
,CUSTOMER_ID	NUMBER(15)
,CUSTOMER_SITE_USE_ID	NUMBER(15)
,CUSTOMER_TRX_ID	NUMBER(15)
,CUST_TRX_TYPE_ID	NUMBER(15)
,CASH_RECEIPT_ID	NUMBER(15)
,CLASS	VARCHAR2(20)
,STATUS	VARCHAR2(30)
,STATE_DSP	VARCHAR2(4000)
,STATE	VARCHAR2(30)
,RECEIPT_CONFIRMED_FLAG	VARCHAR2(1)
,SELECTED_FOR_RECEIPT_BATCH_ID	NUMBER(15)
,COLLECTOR_LAST	NUMBER(15)
,FOLLOW_UP_CODE_LAST	VARCHAR2(30)
,IN_COLLECTION	VARCHAR2(200)
,TERM_ID	NUMBER(15)
,RAC_CUSTOMER_NAME	VARCHAR2(360)
,RAC_CUSTOMER_NUMBER	VARCHAR2(30)
,SU_LOCATION	VARCHAR2(40)
,BS_BATCH_SOURCE_NAME	VARCHAR2(50)
,TYPE_NAME	VARCHAR2(30)
,AL_CLASS_MEANING	VARCHAR2(4000)
,DOC_SEQUENCE_VALUE	NUMBER(15)
,CT_PURCHASE_ORDER	VARCHAR2(50)
,CT_PREVIOUS_CUSTOMER_TRX_ID	NUMBER
,INTERFACE_HEADER_CONTEXT	VARCHAR2(30)
,INTERFACE_HEADER_ATTRIBUTE1	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE2	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE3	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE4	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE5	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE6	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE7	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE8	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE9	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE10	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE11	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE12	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE13	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE14	VARCHAR2(150)
,INTERFACE_HEADER_ATTRIBUTE15	VARCHAR2(150)
,DUE_DAYS	NUMBER
,DUE_DATE	DATE
,AMOUNT_DUE_ORIGINAL	NUMBER
,ACCTD_AMOUNT_DUE_ORIGINAL	NUMBER
,AMOUNT_DUE_REMAINING	NUMBER
,ACCTD_AMOUNT_DUE_REMAINING	NUMBER
,AL_STATUS_MEANING	VARCHAR2(4000)
,ACTUAL_DATE_CLOSED	DATE
,GL_DATE_CLOSED	DATE
,AMOUNT_LINE_ITEMS_ORIGINAL	NUMBER
,ACCTD_AMOUNT_LINE_ITEMS_ORIG	NUMBER
,AMOUNT_LINE_ITEMS_REMAINING	NUMBER
,ACCTD_AMOUNT_LINE_ITEMS_REMAIN	NUMBER
,TAX_ORIGINAL	NUMBER
,ACCTD_TAX_ORIGINAL	NUMBER
,TAX_REMAINING	NUMBER
,ACCTD_TAX_REMAINING	NUMBER
,FREIGHT_ORIGINAL	NUMBER
,ACCTD_FREIGHT_ORIGINAL	NUMBER
,FREIGHT_REMAINING	NUMBER
,ACCTD_FREIGHT_REMAINING	NUMBER
,AMOUNT_ADJUSTED	NUMBER
,ACCTD_AMOUNT_ADJUSTED	NUMBER
,AMOUNT_ADJUSTED_PENDING	NUMBER
,ACCTD_AMOUNT_ADJUSTED_PENDING	NUMBER
,RECEIVABLES_CHARGES_CHARGED	NUMBER
,ACCTD_REC_CHARGES_CHARGED	NUMBER
,RECEIVABLES_CHARGES_REMAINING	NUMBER
,ACCTD_REC_CHARGES_REMAINING	NUMBER
,AMOUNT_APPLIED	NUMBER
,ACCTD_AMOUNT_APPLIED	NUMBER
,AMOUNT_CREDITED	NUMBER
,ACCTD_AMOUNT_CREDITED	NUMBER
,AMOUNT_IN_DISPUTE	NUMBER
,ACCTD_AMOUNT_IN_DISPUTE	NUMBER
,DISPUTE_DATE	DATE
,DISCOUNT_TAKEN_EARNED	NUMBER
,ACCTD_DISCOUNT_TAKEN_EARNED	NUMBER
,DISCOUNT_TAKEN_UNEARNED	NUMBER
,ACCTD_DISCOUNT_TAKEN_UNEARNED	NUMBER
,AL_SELECTED_FOR_RECEIPT_FLAG	VARCHAR2(4000)
,AL_SELECTED_FOR_RECEIPT_CODE	VARCHAR2(1)
,AL_RECEIPT_CONFIRMED_MEANING	VARCHAR2(4000)
,CR_SELECTED_RECEIPT_NUMBER	VARCHAR2(200)
,ARB_SELECTED_BATCH_NAME	VARCHAR2(200)
,ARB_SELECTED_BATCH_DATE	VARCHAR2(200)
,DAYS_PAST_DUE	NUMBER
,DUNNING_DATE_LAST	VARCHAR2(33)
,CALL_DATE_LAST	DATE
,PROMISE_AMOUNT_LAST	NUMBER
,ACCTD_PROMISE_AMOUNT_LAST	NUMBER
,PROMISE_DATE_LAST	DATE
,AL_FOLLOW_UP_LAST_MEANING	VARCHAR2(4000)
,FOLLOW_UP_DATE_LAST	DATE
,AL_IN_COLLECTION_MEANING	VARCHAR2(200)
,RAT_TERM_NAME	VARCHAR2(4000)
,CHARGEBACK_INVOICE_NUM	VARCHAR2(90)
,CHARGEBACK_BATCH_SOURCE	VARCHAR2(150)
,BILLING_NUMBER	VARCHAR2(30)
,STAGED_DUNNING_LEVEL	NUMBER(2)
,DUNNING_LEVEL_OVERRIDE_DATE	DATE
,REMITTANCE_METHOD	VARCHAR2(30)
,GLOBAL_ATTRIBUTE_CATEGORY	VARCHAR2(30)
,GLOBAL_ATTRIBUTE1	VARCHAR2(150)
,GLOBAL_ATTRIBUTE2	VARCHAR2(150)
,GLOBAL_ATTRIBUTE3	VARCHAR2(150)
,GLOBAL_ATTRIBUTE4	VARCHAR2(150)
,GLOBAL_ATTRIBUTE5	VARCHAR2(150)
,GLOBAL_ATTRIBUTE6	VARCHAR2(150)
,GLOBAL_ATTRIBUTE7	VARCHAR2(150)
,GLOBAL_ATTRIBUTE8	VARCHAR2(150)
,GLOBAL_ATTRIBUTE9	VARCHAR2(150)
,GLOBAL_ATTRIBUTE10	VARCHAR2(150)
,GLOBAL_ATTRIBUTE11	VARCHAR2(150)
,GLOBAL_ATTRIBUTE12	VARCHAR2(150)
,GLOBAL_ATTRIBUTE13	VARCHAR2(150)
,GLOBAL_ATTRIBUTE14	VARCHAR2(150)
,GLOBAL_ATTRIBUTE15	VARCHAR2(150)
,GLOBAL_ATTRIBUTE16	VARCHAR2(150)
,GLOBAL_ATTRIBUTE17	VARCHAR2(150)
,GLOBAL_ATTRIBUTE18	VARCHAR2(150)
,GLOBAL_ATTRIBUTE19	VARCHAR2(150)
,GLOBAL_ATTRIBUTE20	VARCHAR2(150)
,CONS_INV_ID	NUMBER(15)
,LAST_UPDATED_BY	NUMBER(15)
,LAST_UPDATE_DATE	DATE
,LAST_UPDATE_LOGIN	NUMBER(15)
,CREATED_BY	NUMBER(15)
,CREATION_DATE	DATE
,COMMENTS	VARCHAR2(2000)
,LEGAL_ENTITY_ID	NUMBER(15)
,BILLING_DATE	DATE
,ORG_ID	NUMBER(15)
);

TYPE transactions_tbl is TABLE of transactions_rec;

TYPE aging_tbl is TABLE of XXEIS.EIS_AR_AGING_V%rowtype;


-- This function is called from a Aging view utilized by SOA Customer Balance Webservice for NSA
-- this function specifically written to non-org sensitive  

FUNCTION aging_details (p_org_id IN NUMBER)  return aging_tbl PIPELINED;

FUNCTION cust_org_trx (p_customer_id IN NUMBER, p_org_id IN NUMBER)  RETURN transactions_tbl PIPELINED;

function org_cust_aging (p_customer_id IN number, p_org_id in number ,p_credit_option in varchar2,p_bucket_name in varchar2) return bucket_lines_Tbl 
PIPELINED;


-- This function is called from a Aging view utilized by SOA Customer Balance Webservice for NSA
-- this function specifically written to non-org sensitive  

FUNCTION aging_details_csr (p_cursor in sys_refcursor, p_org_id IN NUMBER)  RETURN aging_tbl PIPELINED;

-- This function is called from a Aging view utilized by SOA Customer Balance Webservice
-- this function specifically written to non-org sensitive  
FUNCTION amount_remaining_gl_date (p_payment_schedule_id in number,
                                   p_as_of_date in date,
                                p_class in varchar2 ) RETURN NUMBER;

FUNCTION amount_remaining(p_applied_payment_schedule_id in number,
                          p_as_of_date in date,
                          p_class in varchar2 
                          ) RETURN NUMBER;

FUNCTION amount_remaining_new(p_payment_schedule_id in number,
                                p_as_of_date in date,
                                p_class in varchar2 ,
                                p_days_from in number,
                                p_days_to in number,
                                p_due_date IN date
                                ) return number;                               
 END XXNUC_ARPT_SQL_FUNC_UTIL_PKG;
 /