ALTER TABLE XXNUC.XXNUC_SPS_EMPLOYEES
 DROP PRIMARY KEY CASCADE;

DROP TABLE XXNUC.XXNUC_SPS_EMPLOYEES CASCADE CONSTRAINTS;

CREATE TABLE XXNUC.XXNUC_SPS_EMPLOYEES
(
  SAP_EMP_NUM          VARCHAR2(50 BYTE)        NOT NULL,
  LAST_NAME            VARCHAR2(40 BYTE)        NOT NULL,
  FIRST_NAME           VARCHAR2(40 BYTE)        NOT NULL,
  MIDDLE_INITIAL       VARCHAR2(40 BYTE),
  SUFFIX               VARCHAR2(30 BYTE),
  GENDER               VARCHAR2(1 BYTE)         NOT NULL,
  LEDGER               VARCHAR2(30 BYTE),
  EMPLOYMENT_DATE      DATE                     NOT NULL,
  EMPLOYMENT_END_DATE  DATE,
  EMAIL_ADDRESS        VARCHAR2(50 BYTE),
  ADDRESS_LINE1        VARCHAR2(50 BYTE),
  ADDRESS_LINE2        VARCHAR2(50 BYTE),
  CITY                 VARCHAR2(25 BYTE),
  STATE                VARCHAR2(25 BYTE),
  ZIP_CODE             VARCHAR2(25 BYTE),
  COUNTRY              VARCHAR2(25 BYTE),
  TELEPHONE            VARCHAR2(15 BYTE),
  JOB                  VARCHAR2(50 BYTE),
  SUPERVISORID         VARCHAR2(40 BYTE),
  DEPT                 VARCHAR2(50 BYTE),
  DEPARTMENTID         VARCHAR2(15 BYTE),
  PERSONNELAREAID      VARCHAR2(10 BYTE),
  RECORD_STATUS        VARCHAR2(10 BYTE)        NOT NULL,
  DIV_NO               VARCHAR2(5 BYTE)
)
TABLESPACE XXNUC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX XXNUC.XXNUC_SPS_EMPLOYEES_PK ON XXNUC.XXNUC_SPS_EMPLOYEES
(SAP_EMP_NUM, RECORD_STATUS)
LOGGING
TABLESPACE XXNUC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE XXNUC.XXNUC_SPS_EMPLOYEES ADD (
  CONSTRAINT XXNUC_SPS_EMPLOYEES_PK
  PRIMARY KEY
  (SAP_EMP_NUM, RECORD_STATUS)
  USING INDEX .XXNUC_SPS_EMPLOYEES_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON XXNUC.XXNUC_SPS_EMPLOYEES TO SPS_BLOWE;

GRANT SELECT ON XXNUC.XXNUC_SPS_EMPLOYEES TO XXNUC_READ_ONLY;
