<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://nucor.eia.com"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/Manish/NUC_SubscribeBundleTestResults_JMS_ROSS_ABF/FTP_File_Write_Ross"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_File_Write_Ross.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Envelope" namespace="http://nucor.eia.com"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_File_Write_Ross.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Envelope" namespace="http://nucor.eia.com"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI NOV 04 14:07:57 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:Envelope>
      <xsl:if test="/ns0:Envelope/@MsgType">
        <xsl:attribute name="MsgType">
          <xsl:value-of select="/ns0:Envelope/@MsgType"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Envelope/@Ver">
        <xsl:attribute name="Ver">
          <xsl:value-of select="/ns0:Envelope/@Ver"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Envelope/@CreatedDate">
        <xsl:attribute name="CreatedDate">
          <xsl:value-of select="/ns0:Envelope/@CreatedDate"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Envelope/@OpMode">
        <xsl:attribute name="OpMode">
          <xsl:value-of select="/ns0:Envelope/@OpMode"/>
        </xsl:attribute>
      </xsl:if>
      <ns0:SupplierInfo>
        <ns0:MillDUNS>
          <xsl:value-of select="/ns0:Envelope/ns0:SupplierInfo/ns0:MillDUNS"/>
        </ns0:MillDUNS>
        <ns0:Name>
          <xsl:value-of select="/ns0:Envelope/ns0:SupplierInfo/ns0:Name"/>
        </ns0:Name>
        <ns0:Addr>
          <xsl:value-of select="/ns0:Envelope/ns0:SupplierInfo/ns0:Addr"/>
        </ns0:Addr>
        <ns0:City>
          <xsl:value-of select="/ns0:Envelope/ns0:SupplierInfo/ns0:City"/>
        </ns0:City>
        <ns0:State>
          <xsl:value-of select="/ns0:Envelope/ns0:SupplierInfo/ns0:State"/>
        </ns0:State>
        <ns0:PostalCode>
          <xsl:value-of select="/ns0:Envelope/ns0:SupplierInfo/ns0:PostalCode"/>
        </ns0:PostalCode>
      </ns0:SupplierInfo>
      <ns0:CustomerInfo>
        <ns0:SoldTo>
          <ns0:Name>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:SoldTo/ns0:Name"/>
          </ns0:Name>
          <ns0:SupplierCustID>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:SoldTo/ns0:SupplierCustID"/>
          </ns0:SupplierCustID>
          <ns0:Addr>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:SoldTo/ns0:Addr"/>
          </ns0:Addr>
          <ns0:City>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:SoldTo/ns0:City"/>
          </ns0:City>
          <ns0:State>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:SoldTo/ns0:State"/>
          </ns0:State>
          <ns0:PostalCode>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:SoldTo/ns0:PostalCode"/>
          </ns0:PostalCode>
        </ns0:SoldTo>
        <ns0:BillTo>
          <ns0:Name>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:BillTo/ns0:Name"/>
          </ns0:Name>
          <ns0:SupplierCustID>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:BillTo/ns0:SupplierCustID"/>
          </ns0:SupplierCustID>
          <ns0:Addr>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:BillTo/ns0:Addr"/>
          </ns0:Addr>
          <ns0:City>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:BillTo/ns0:City"/>
          </ns0:City>
          <ns0:State>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:BillTo/ns0:State"/>
          </ns0:State>
          <ns0:PostalCode>
            <xsl:value-of select="/ns0:Envelope/ns0:CustomerInfo/ns0:BillTo/ns0:PostalCode"/>
          </ns0:PostalCode>
        </ns0:BillTo>
      </ns0:CustomerInfo>
      <ns0:FreightInfo>
        <ns0:ShipMode>
          <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:ShipMode"/>
        </ns0:ShipMode>
        <ns0:ShipDate>
          <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:ShipDate"/>
        </ns0:ShipDate>
        <ns0:FreightTerm>
          <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:FreightTerm"/>
        </ns0:FreightTerm>
        <ns0:Carrier>
          <ns0:Name>
            <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:Carrier/ns0:Name"/>
          </ns0:Name>
          <ns0:VehicleID>
            <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:Carrier/ns0:VehicleID"/>
          </ns0:VehicleID>
        </ns0:Carrier>
        <ns0:ShipTo>
          <ns0:Name>
            <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:ShipTo/ns0:Name"/>
          </ns0:Name>
          <ns0:SupplierCustID>
            <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:ShipTo/ns0:SupplierCustID"/>
          </ns0:SupplierCustID>
          <ns0:Addr>
            <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:ShipTo/ns0:Addr"/>
          </ns0:Addr>
          <ns0:City>
            <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:ShipTo/ns0:City"/>
          </ns0:City>
          <ns0:State>
            <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:ShipTo/ns0:State"/>
          </ns0:State>
          <ns0:PostalCode>
            <xsl:value-of select="/ns0:Envelope/ns0:FreightInfo/ns0:ShipTo/ns0:PostalCode"/>
          </ns0:PostalCode>
        </ns0:ShipTo>
      </ns0:FreightInfo>
      <ns0:Waybills>
        <ns0:Waybill>
          <xsl:if test="/ns0:Envelope/ns0:Waybills/ns0:Waybill/@Type">
            <xsl:attribute name="Type">
              <xsl:value-of select="/ns0:Envelope/ns0:Waybills/ns0:Waybill/@Type"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="/ns0:Envelope/ns0:Waybills/ns0:Waybill/@Revision">
            <xsl:attribute name="Revision">
              <xsl:value-of select="/ns0:Envelope/ns0:Waybills/ns0:Waybill/@Revision"/>
            </xsl:attribute>
          </xsl:if>
          <ns0:WaybillNum>
            <xsl:value-of select="/ns0:Envelope/ns0:Waybills/ns0:Waybill/ns0:WaybillNum"/>
          </ns0:WaybillNum>
          <ns0:WaybillDateTime>
            <xsl:value-of select="/ns0:Envelope/ns0:Waybills/ns0:Waybill/ns0:WaybillDateTime"/>
          </ns0:WaybillDateTime>
          <ns0:WaybillLines>
            <xsl:for-each select="/ns0:Envelope/ns0:Waybills/ns0:Waybill/ns0:WaybillLines/ns0:WaybillLine">
              <ns0:WaybillLine>
                <ns0:LineNum>
                  <xsl:value-of select="position()"/>
                </ns0:LineNum>
                <ns0:CustPO>
                  <xsl:value-of select="ns0:CustPO"/>
                </ns0:CustPO>
                <ns0:CustPartNum>
                  <xsl:value-of select="ns0:CustPartNum"/>
                </ns0:CustPartNum>
                <ns0:SupplierOrderNum>
                  <xsl:value-of select="ns0:SupplierOrderNum"/>
                </ns0:SupplierOrderNum>
                <ns0:QtyBundles>
                  <xsl:value-of select="ns0:QtyBundles"/>
                </ns0:QtyBundles>
                <ns0:LineWgtTtl>
                  <xsl:if test="ns0:LineWgtTtl/@UOM">
                    <xsl:attribute name="UOM">
                      <xsl:value-of select="ns0:LineWgtTtl/@UOM"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:LineWgtTtl/@Qual">
                    <xsl:attribute name="Qual">
                      <xsl:value-of select="ns0:LineWgtTtl/@Qual"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:LineWgtTtl"/>
                </ns0:LineWgtTtl>
                <ns0:Bundles>
                  <xsl:for-each select="ns0:Bundles/ns0:Bundle">
                    <ns0:Bundle>
                      <ns0:BundleNum>
                        <xsl:value-of select="ns0:BundleNum"/>
                      </ns0:BundleNum>
                      <ns0:RollDateTime>
                        <xsl:value-of select="ns0:RollDateTime"/>
                      </ns0:RollDateTime>
                      <ns0:SupplierProductCode>
                        <xsl:value-of select="ns0:SupplierProductCode"/>
                      </ns0:SupplierProductCode>
                      <ns0:SupplierProductDesc>
                        <xsl:value-of select="ns0:SupplierProductDesc"/>
                      </ns0:SupplierProductDesc>
                      <ns0:Grade>
                        <xsl:value-of select="ns0:Grade"/>
                      </ns0:Grade>
                      <ns0:GradeDesc>
                        <xsl:value-of select="ns0:GradeDesc"/>
                      </ns0:GradeDesc>
                      <ns0:Shape>
                        <xsl:value-of select="ns0:Shape"/>
                      </ns0:Shape>
                      <ns0:Size>
                        <xsl:value-of select="ns0:Size"/>
                      </ns0:Size>
                      <ns0:TagNum>
                        <xsl:value-of select="ns0:TagNum"/>
                      </ns0:TagNum>
                      <ns0:Length>
                        <xsl:value-of select="ns0:Length"/>
                      </ns0:Length>
                      <ns0:QtyPcs>
                        <xsl:value-of select="ns0:QtyPcs"/>
                      </ns0:QtyPcs>
                      <ns0:TtlWgt>
                        <xsl:if test="ns0:TtlWgt/@UOM">
                          <xsl:attribute name="UOM">
                            <xsl:value-of select="ns0:TtlWgt/@UOM"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:TtlWgt/@Qual">
                          <xsl:attribute name="Qual">
                            <xsl:value-of select="ns0:TtlWgt/@Qual"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TtlWgt"/>
                      </ns0:TtlWgt>
                      <ns0:HeatNum>
                        <xsl:value-of select="ns0:HeatNum"/>
                      </ns0:HeatNum>
                      <ns0:ReheatNum>
                        <xsl:value-of select="ns0:ReheatNum"/>
                      </ns0:ReheatNum>
                    </ns0:Bundle>
                  </xsl:for-each>
                </ns0:Bundles>
              </ns0:WaybillLine>
            </xsl:for-each>
          </ns0:WaybillLines>
        </ns0:Waybill>
      </ns0:Waybills>
      <ns0:Tests>
        <xsl:for-each select="/ns0:Envelope/ns0:Tests/ns0:TestSet">
          <ns0:TestSet>
            <ns0:Bundles>
              <xsl:for-each select="ns0:Bundles/ns0:BundleNum">
                <ns0:BundleNum>
                  <xsl:value-of select="."/>
                </ns0:BundleNum>
              </xsl:for-each>
            </ns0:Bundles>
            <ns0:HeatNum>
              <xsl:value-of select="ns0:HeatNum"/>
            </ns0:HeatNum>
            <ns0:ReheatNum>
              <xsl:value-of select="ns0:ReheatNum"/>
            </ns0:ReheatNum>
            <ns0:MeltCountry>
              <xsl:value-of select="ns0:MeltCountry"/>
            </ns0:MeltCountry>
            <ns0:MeltDate>
              <xsl:value-of select="ns0:MeltDate"/>
            </ns0:MeltDate>
            <ns0:MeltMill>
              <xsl:value-of select="ns0:MeltMill"/>
            </ns0:MeltMill>
            <ns0:RollCountry>
              <xsl:value-of select="ns0:RollCountry"/>
            </ns0:RollCountry>
            <ns0:RollDate>
              <xsl:value-of select="ns0:RollDate"/>
            </ns0:RollDate>
            <ns0:RollMill>
              <xsl:value-of select="ns0:RollMill"/>
            </ns0:RollMill>
            <ns0:FinalCountry>
              <xsl:value-of select="ns0:FinalCountry"/>
            </ns0:FinalCountry>
            <ns0:FinalDate>
              <xsl:value-of select="ns0:FinalDate"/>
            </ns0:FinalDate>
            <ns0:FinalMill>
              <xsl:value-of select="ns0:FinalMill"/>
            </ns0:FinalMill>
            <ns0:Measures>
              <xsl:for-each select="ns0:Measures/ns0:Measure">
                <ns0:Measure>
                  <xsl:if test="@Test">
                    <xsl:attribute name="Test">
                      <xsl:value-of select="@Test"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@Replicate">
                    <xsl:attribute name="Replicate">
                      <xsl:value-of select="@Replicate"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@UOM">
                    <xsl:attribute name="UOM">
                      <xsl:value-of select="@UOM"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="."/>
                </ns0:Measure>
              </xsl:for-each>
            </ns0:Measures>
          </ns0:TestSet>
        </xsl:for-each>
      </ns0:Tests>
    </ns0:Envelope>
  </xsl:template>
</xsl:stylesheet>
