<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns1="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns2="http://xmlns.eia.com/AO/EBiz/O2C/CustomerAO/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://xmlns.eia.com/ABS/EBiz/CustomerABS/1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NUCOR/NUC_EBizCustomer_ABS/DB_CustomerSitesEBS" xmlns:ns5="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:core="http://xmlns.eia.com/EO/Common/1.0" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_CustomerSitesEBS" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:custam="http://xmlns.eia.com/AO/EBiz/O2C/CustomerAM/1.0" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns plt wsdl top xsd ns1 ns2 ns0 ns5 soap12 soap mime core ns4 ns3 custam aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../DB_CustomerSitesEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxnucSiteOrigSysRefsVCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_CustomerSitesEBS"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/CustomerABS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="QueryByOrigSystemRef_BasicSiteResponseMessage" namespace="http://xmlns.eia.com/AO/EBiz/O2C/CustomerAM/1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI SEP 04 19:03:06 CDT 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <custam:QueryByOrigSystemRef_BasicSiteResponseMessage>
      <custam:BasicSite>
        <ns2:Identifier>
          <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:hzCustAcctSitesAll/top:custAcctSiteId"/>
        </ns2:Identifier>
        <ns2:Status>
          <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:hzCustAcctSitesAll/top:status"/>
        </ns2:Status>
       <ns2:CustomerAccountID> <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:hzCustAcctSitesAll/top:custAccountId"/>
            </ns2:CustomerAccountID>
        <ns2:OrigSystemReference>
          <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:hzCustAcctSitesAll/top:origSystemReference"/>
        </ns2:OrigSystemReference>
        <ns2:CustomerAccountID> <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:hzCustAcctSitesAll/top:custAccountId"/>
            </ns2:CustomerAccountID>

        <ns2:ListOrigSystemReferences>
          <ns2:OrigSystem>
            <ns2:TableName>
              <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:ownerTableName"/>
            </ns2:TableName>
            <ns2:OrigSystem>
              <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:origSystem"/>
            </ns2:OrigSystem>
            <ns2:OrigSystemReference>
              <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:origSystemReference"/>
            </ns2:OrigSystemReference>
            <ns2:ObjectVersionNumber>
              <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:objectVersionNumber"/>
            </ns2:ObjectVersionNumber>
            <ns2:Status>
              <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:status"/>
            </ns2:Status>
            <ns2:StartDate>
              <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:startDateActive"/>
            </ns2:StartDate>
            <ns2:EndDate>
              <xsl:value-of select="/top:XxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV/top:endDateActive"/>
            </ns2:EndDate>
          </ns2:OrigSystem>
        </ns2:ListOrigSystemReferences>
      </custam:BasicSite>
    </custam:QueryByOrigSystemRef_BasicSiteResponseMessage>
  </xsl:template>
</xsl:stylesheet>