<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:eia="http://xmlns.eia.com/extensions/1.0" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns1="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://xmlns.eia.com/AO/EBiz/O2C/CustomerAO/1.0" xmlns:ns0="http://xmlns.eia.com/ABS/EBiz/CustomerABS/1.0" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_CustomerEBS" xmlns:ns5="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:core="http://xmlns.eia.com/EO/Common/1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WI_Application/NUC_EBizCustomer_ABS/DB_CustomerEBS" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0" xmlns:custam="http://xmlns.eia.com/AO/EBiz/O2C/CustomerAM/1.0" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl top plt wsdl tns xsd ns1 ns2 ns0 ns5 soap12 soap mime core ns4 ns3 custam bpws xp20 eia bpel bpm utl ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../DB_CustomerEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxnucCustOrigSysRefsVCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_CustomerEBS"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/O2C/CustomerABS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="QueryByOrigSystemRef_BasicCustomerResponseMessage" namespace="http://xmlns.eia.com/AO/EBiz/O2C/CustomerAM/1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI SEP 04 19:03:06 CDT 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <custam:QueryByOrigSystemRef_BasicCustomerResponseMessage>
      <custam:BasicCustomer>
        <ns2:Identifier>
          <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:hzCustAccountsAll/top:custAccountId"/>
        </ns2:Identifier>
        <ns2:CustomerName>
          <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:hzCustAccountsAll/top:accountName"/>
        </ns2:CustomerName>
        <ns2:CustomerNumber>
          <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:hzCustAccountsAll/top:accountNumber"/>
        </ns2:CustomerNumber>
        <ns2:OrgName>
          <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:hzCustAccountsAll/top:hzParties/top:partyName"/>
        </ns2:OrgName>
        <ns2:OrigSystem>
          <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:origSystem"/>
        </ns2:OrigSystem>
        <ns2:OrigSystemReference>
          <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:origSystemReference"/>
        </ns2:OrigSystemReference>
        <ns2:ListOrigSystemReferences>
          <ns2:OrigSystem>
            <ns2:OrigSystem>
              <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:origSystem"/>
            </ns2:OrigSystem>
            <ns2:OrigSystemReference>
              <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:origSystemReference"/>
            </ns2:OrigSystemReference>
            <ns2:Status>
              <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:status"/>
            </ns2:Status>
            <ns2:StartDate>
              <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:startDateActive"/>
            </ns2:StartDate>
            <ns2:EndDate>
              <xsl:value-of select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:endDateActive"/>
            </ns2:EndDate>
          </ns2:OrigSystem>
        </ns2:ListOrigSystemReferences>
        <ns2:ListBasicSiteInfo>
          <xsl:for-each select="/top:XxnucCustOrigSysRefsVCollection/top:XxnucCustOrigSysRefsV/top:hzCustAccountsAll/top:hzCustAcctSitesAllCollection/top:HzCustAcctSitesAll">
            <ns2:BasicSiteInfo>
              <ns2:Identifier>
                <xsl:value-of select="top:custAcctSiteId"/>
              </ns2:Identifier>
              <ns2:Status>
                <xsl:value-of select="top:status"/>
              </ns2:Status>
              <ns2:ListOrigSystemReferences>
                <xsl:for-each select="top:xxnucSiteOrigSysRefsVCollection/top:XxnucSiteOrigSysRefsV">
                  <ns2:OrigSystem>
                    <ns2:TableName>
                      <xsl:value-of select="top:ownerTableName"/>
                    </ns2:TableName>
                    <ns2:OrigSystem>
                      <xsl:value-of select="top:origSystem"/>
                    </ns2:OrigSystem>
                    <ns2:OrigSystemReference>
                      <xsl:value-of select="top:origSystemReference"/>
                    </ns2:OrigSystemReference>
                    <ns2:Status>
                      <xsl:value-of select="top:status"/>
                    </ns2:Status>
                    <ns2:StartDate>
                      <xsl:value-of select="top:startDateActive"/>
                    </ns2:StartDate>
                    <ns2:EndDate>
                      <xsl:value-of select="top:endDateActive"/>
                    </ns2:EndDate>
                  </ns2:OrigSystem>
                </xsl:for-each>
              </ns2:ListOrigSystemReferences>
            </ns2:BasicSiteInfo>
          </xsl:for-each>
        </ns2:ListBasicSiteInfo>
      </custam:BasicCustomer>
    </custam:QueryByOrigSystemRef_BasicCustomerResponseMessage>
  </xsl:template>
</xsl:stylesheet>