<wsdl:definitions
     name="EBS_LotCreation"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/apps/I109byManish/NUC_EBizLot_ABS/EBS_LotCreation"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/apps/I109byManish/NUC_EBizLot_ABS/EBS_LotCreation"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_LotCreation"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="EBS_LotCreation_plt" >
    <plt:role name="EBS_LotCreation_role" >
      <plt:portType name="tns:EBS_LotCreation_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_LotCreation"
               schemaLocation="../Schemas/EBS_LotCreation_sp.xsd" />
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="EBS_LotCreation_ptt">
        <wsdl:operation name="EBS_LotCreation">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
