<wsdl:definitions
     name="FTP_PutFileRailInc"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/OTM/NUC_WriteBOLShipment_OTM_RailInc_ABF/FTP_PutFileRailInc"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/OTM/NUC_WriteBOLShipment_OTM_RailInc_ABF/FTP_PutFileRailInc"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:imp1="http://xmlns.oracle.com/NUC_WriteBOLShipment_OTM_RailInc_ABF/BOLShipment/1.0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Put_plt" >
    <plt:role name="Put_role" >
      <plt:portType name="tns:Put_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/OTM/NUC_WriteBOLShipment_OTM_RailInc_ABF/FTP_PutFileRailInc"
              xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/NUC_WriteBOLShipment_OTM_RailInc_ABF/BOLShipment/1.0" schemaLocation="../Schemas/RailInc.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Put_msg">
        <wsdl:part name="body" element="imp1:BOL"/>
    </wsdl:message>
    <wsdl:portType name="Put_ptt">
        <wsdl:operation name="Put">
            <wsdl:input message="tns:Put_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
