<?binding.jca DB_GetOrigSystemRef_db.jca?>
<wsdl:definitions name="DB_GetOrigSystemRef" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Test/NUC_EBizOrigSystemRef_ABS/DB_GetOrigSystemRef" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Test/NUC_EBizOrigSystemRef_ABS/DB_GetOrigSystemRef" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_GetOrigSystemRef">
    <plt:partnerLinkType name="DB_GetOrigSystemRef_plt">
        <plt:role name="DB_GetOrigSystemRef_role">
            <plt:portType name="tns:DB_GetOrigSystemRef_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_GetOrigSystemRef" schemaLocation="xsd/DB_GetOrigSystemRef_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="HzOrigSysReferences_msg">
        <wsdl:part name="HzOrigSysReferences" element="top:HzOrigSysReferences"/>
    </wsdl:message>
    <wsdl:message name="HzOrigSysReferencesCollection_msg">
        <wsdl:part name="HzOrigSysReferencesCollection" element="top:HzOrigSysReferencesCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_GetOrigSystemRef_ptt">
        <wsdl:operation name="queryByExample">
            <wsdl:input message="tns:HzOrigSysReferences_msg"/>
            <wsdl:output message="tns:HzOrigSysReferencesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
