<?binding.jca OA_UpdateOSR_apps.jca?>
<wsdl:definitions name="OA_UpdateOSR" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/apps/Test/NUC_EBizOrigSystemRef_ABS/OA_UpdateOSR" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_UpdateOSR" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/apps/Test/NUC_EBizOrigSystemRef_ABS/OA_UpdateOSR" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="OA_UpdateOSR_plt">
        <plt:role name="OA_UpdateOSR_role">
            <plt:portType name="tns:OA_UpdateOSR_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/OA_UpdateOSR" schemaLocation="xsd/OA_UpdateOSR_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="OA_UpdateOSR_ptt">
        <wsdl:operation name="OA_UpdateOSR">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
