<?xml version="1.0" encoding="UTF-8"?>
<!--$Header$-->
<wsdl:definitions targetNamespace="http://xmlns.eia.com/CommonArtifacts/wsdl/EIAFault/1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.eia.com/CommonArtifacts/wsdl/EIAFault/1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://xmlns.eia.com/EO/Common/1.0" schemaLocation="../../EO/common/Common.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="EIAFaultMessageType">
		<wsdl:part name="Fault" element="core:Fault"/>
	</wsdl:message>
	<wsdl:message name="ProcessHeaderMessageType">
		<wsdl:part name="ProcessHeader" element="core:ProcessHeader"/>
	</wsdl:message>
</wsdl:definitions>
