<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns14="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns16="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0"
                xmlns:ns15="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/DV1Application/NUC_PublishCustomerEBiz_ABF/JMSConsumePO"
                xmlns:ns17="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns18="http://xmlns.oracle.com/DV1Application/NUC_SubscribeEBizPO_JMS_DJJ_ABF/Rest_DJJCreatePO"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMSConsumePO.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryPurchaseOrderResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/JMSConsumePO.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="tmp_Parameter"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Rest_DJJCreatePO.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MillContract" namespace=""/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON APR 18 08:08:06 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="tmp_Parameter"/>
  <xsl:template match="/">
    <xsl:variable name="POLineIdx"
                  select="number($tmp_Parameter/ns1:parameters/ns1:item[ns1:name = 'POLineIdx']/ns1:value)"/>
    <MillContract>
      <!-- Modified as a part of CR Defect# 1776-->
      <xsl:choose>
        <xsl:when test="(/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:PoLocationsAllClosedcode = '') or (/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:PoLocationsAllClosedcode = 'OPEN')">
          <Active>true</Active>
        </xsl:when>
        <xsl:otherwise>
          <Active>false</Active>
        </xsl:otherwise>
      </xsl:choose>
      <ConsumerId>
        <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_CUSTOMERID_DEFAULTS.dvm", "EBS_OPERATING_UNIT_NAME", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:OperatingUnit, "DJJ_CUSTOMER_ID", "" )'/>
      </ConsumerId>
      <xsl:choose>
        <xsl:when test="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:HeaderDFF/ns12:Attribute5 = 'Non-Brokered'">
          <ContractTypeId>2</ContractTypeId>
        </xsl:when>
        <xsl:when test="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:HeaderDFF/ns12:Attribute5 = 'Non-Scrap'">
          <ContractTypeId>3</ContractTypeId>
        </xsl:when>
        <xsl:when test="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:HeaderDFF/ns12:Attribute5 = 'Miscellaneous'">
          <ContractTypeId>4</ContractTypeId>
        </xsl:when>
      </xsl:choose>
      <!--xsl:if test="(/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:HeaderDFF/ns12:Attribute5 = 'Non-Brokered') or (/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:HeaderDFF/ns12:Attribute5 = 'Non-Scrap' or (/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:HeaderDFF/ns12:Attribute5 = 'Miscellaneous'))"-->
      <xsl:variable name="varShipToOrganization"
                    select='oraext:query-database (concat ("Select organization_code from org_organization_definitions where ORGANIZATION_ID = ", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Shiptoorganizationid ), false(), false(), "jdbc/ebsapps")'/>
      <CustomerRefID>
        <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm", "EBS_SHIP_TO_ORGANIZATION", $varShipToOrganization, "CONSUMER_REF_ID", "" )'/>
      </CustomerRefID>
      <EffectiveDate>
        <xsl:value-of select='substring-before (/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Needbydate, "T" )'/>
      </EffectiveDate>
      <ExpirationDate>
        <xsl:value-of select='substring-before (/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Needbydate, "T" )'/>
      </ExpirationDate>
      <GradeDescription>
        <xsl:value-of select="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Itemdescription"/>
      </GradeDescription>
      <MillContractLine>
        <xsl:value-of select="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Linenum"/>
      </MillContractLine>
      <MillContractNumBase>
        <xsl:value-of select="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:Segment1"/>
      </MillContractNumBase>
      <MillGradeCode>
        <xsl:value-of select='oraext:query-database (concat ("select segment1 from mtl_system_items_b where inventory_item_id= ", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Itemid, " and organization_id = ", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Shiptoorganizationid ), false ( ), false ( ), "jdbc/ebsapps" )'/>
      </MillGradeCode>
      <ModeCode>
        <xsl:value-of select="oraext:query-database (concat (&quot;SELECT attribute2 from po_lines_all where po_line_id = '&quot;, /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Polineid, &quot;'&quot; ), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
      </ModeCode>
      <!-- Modified as part of CR OATS# 1775 -->
      <!--PriceRate>
        <xsl:value-of select="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Unitprice"/>
      </PriceRate-->
      <PriceRate>0.0</PriceRate>
      <PriceRateUOMCode>
        <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_DJJ_PO_UOM_CODE_MAP.dvm", "EBS_UOM_CODE", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Unitmeaslookupcode, "DJJ_UOM_CODE", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Unitmeaslookupcode )'/>
      </PriceRateUOMCode>
      <QtyOrderedUOMCode>
        <xsl:value-of select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_DJJ_PO_UOM_CODE_MAP.dvm", "EBS_UOM_CODE", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Unitmeaslookupcode, "DJJ_UOM_CODE", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Unitmeaslookupcode )'/>
      </QtyOrderedUOMCode>
      <!-- <QtyOrderedUomCode>
        <xsl:value-of select="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Unitmeaslookupcode"/>
      </QtyOrderedUomCode> -->
      <Quantity>
        <xsl:value-of select="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Quantity"/>
      </Quantity>
      <xsl:choose>
        <xsl:when test="oraext:query-database (concat(&quot;select nuc_scale_connect_yn from ego_nuc_scale_connec_agv where inventory_item_id = '&quot;,/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Itemid,&quot;' and organization_id = '&quot;,/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:ListOfPurchaseOrderLines/ns16:PurchaseOrderLine[$POLineIdx]/ns16:Shiptoorganizationid,&quot;'&quot;), false ( ), false ( ), &quot;jdbc/ebsapps&quot; ) = 'Y'">
          <SendReceipt>true</SendReceipt>
        </xsl:when>
        <xsl:otherwise>
          <SendReceipt>false</SendReceipt>
        </xsl:otherwise>
      </xsl:choose>
      <SupplierName>
        <xsl:value-of select='oraext:query-database (concat ("select vendor_name from ap_suppliers where vendor_id = ", /ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:Vendorid ), false ( ), false ( ), "jdbc/ebsapps" )'/>
      </SupplierName>
      <SupplierNumber>
        <xsl:value-of select="/ns0:QueryPurchaseOrderResponseMessage/ns0:ListOfPurchaseOrders/ns16:PurchaseOrder/ns16:Vendorid"/>
      </SupplierNumber>
      <!--/xsl:if-->
    </MillContract>
  </xsl:template>
</xsl:stylesheet>
