/*******************************************************************************
-- Originating Release :  1.0
-- Process Name        :  xxnuc_comm_inserts_updates.sql
-- Author              :  CAPGEMINI
-- Date Created        :  09-JUN-2015
-- Purpose             :  Insert records
--$Header: https://brmkea940.bar.nucorsteel.local:18080/svn/NextGen/branches/RB-1.0.x/soa/utilities/sql/CommonLogging/xxnuc_comm_inserts.sql 3287 2015-11-27 09:22:54Z manishkumar.gujar $
--------------------------------------------------------------------------------
--                       Modification History
--------------------------------------------------------------------------------
-- Version    Name                   Date             Description of Change
-- -------    ---------------------- ---------------  --------------------------
-- 1.0        Sudeep Deshpande       09-JUN-2015      Initial version
-- 2.0        Jyoti Kukreja          30-NOV-2015      Updated for ARFreight
-- 3.0        Venkatesan B           30-NOV-2015      Added B2B Transaction Name
*******************************************************************************/

SET DEFINE OFF;


DECLARE

l_count NUMBER;

BEGIN 

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_GROUP_SETTING WHERE GROUPNAME='AuditLog';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_GROUP_SETTING WHERE GROUPNAME='AuditLog';
Insert into XXNUC_COMM_GROUP_SETTING (GROUPNAME,DESCRIPTION) values ('AuditLog','Audit Log User Group');
ELSE
Insert into XXNUC_COMM_GROUP_SETTING (GROUPNAME,DESCRIPTION) values ('AuditLog','Audit Log User Group');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_GROUP_SETTING WHERE GROUPNAME='NUC';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_GROUP_SETTING WHERE GROUPNAME='NUC';
Insert into XXNUC_COMM_GROUP_SETTING (GROUPNAME,DESCRIPTION) values ('NUC','NUC User Group');
ELSE
Insert into XXNUC_COMM_GROUP_SETTING (GROUPNAME,DESCRIPTION) values ('NUC','NUC User Group');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_GROUP_SETTING WHERE GROUPNAME='NSNE';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_GROUP_SETTING WHERE GROUPNAME='NSNE';
Insert into XXNUC_COMM_GROUP_SETTING (GROUPNAME,DESCRIPTION) values ('NSNE','NSNE User Group');
ELSE
Insert into XXNUC_COMM_GROUP_SETTING (GROUPNAME,DESCRIPTION) values ('NSNE','NSNE User Group');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog'  and EMAIL_ID='manishkumar.gujar@capgemini.com';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog'   and EMAIL_ID='manishkumar.gujar@capgemini.com';
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','manishkumar.gujar@capgemini.com','ENABLED');
ELSE
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','manishkumar.gujar@capgemini.com','ENABLED');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog' and EMAIL_ID='jagannath.rao@capgemini.com';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog' and EMAIL_ID='jagannath.rao@capgemini.com';
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','jagannath.rao@capgemini.com','ENABLED');
ELSE
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','jagannath.rao@capgemini.com','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog' and EMAIL_ID='vinay.bhonsle@capgemini.com';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog' and EMAIL_ID='vinay.bhonsle@capgemini.com';
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','vinay.bhonsle@capgemini.com','ENABLED');
ELSE
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','vinay.bhonsle@capgemini.com','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog' and EMAIL_ID='nirav.sanghavi@capgemini.com';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog' and EMAIL_ID='nirav.sanghavi@capgemini.com';
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','nirav.sanghavi@capgemini.com','ENABLED');
ELSE
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','nirav.sanghavi@capgemini.com','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog' and EMAIL_ID='sudeep.deshpande@capgemini.com';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='AuditLog' and EMAIL_ID='sudeep.deshpande@capgemini.com';
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','sudeep.deshpande@capgemini.com','ENABLED');
ELSE
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('AuditLog','sudeep.deshpande@capgemini.com','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='NUC' and EMAIL_ID='manishkumar.gujar@capgemini.com';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='NUC' and EMAIL_ID='manishkumar.gujar@capgemini.com';
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('NUC','manishkumar.gujar@capgemini.com','ENABLED');
ELSE
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('NUC','manishkumar.gujar@capgemini.com','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='NSNE' and EMAIL_ID='nirav.sanghavi@capgemini.com';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EMAIL_GROUP WHERE GROUPNAME='NSNE' and EMAIL_ID='nirav.sanghavi@capgemini.com';
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('NSNE','nirav.sanghavi@capgemini.com','ENABLED');
ELSE
Insert into XXNUC_COMM_EMAIL_GROUP (GROUPNAME,EMAIL_ID,NOTIFICATION) values ('NSNE','nirav.sanghavi@capgemini.com','ENABLED');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ConsumeB2BErrorMsg';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ConsumeB2BErrorMsg';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ConsumeB2BErrorMsg','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ConsumeB2BErrorMsg','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='SalesOrder';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='SalesOrder';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('SalesOrder','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('SalesOrder','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='AuditLog';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='AuditLog';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('AuditLog','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('AuditLog','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='CPFreightCostInvRate';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='CPFreightCostInvRate';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('CPFreightCostInvRate','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('CPFreightCostInvRate','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Invoice';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Invoice';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Invoice','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Invoice','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Employee';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Employee';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Employee','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Employee','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='QualityResults';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='QualityResults';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('QualityResults','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('QualityResults','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='FreightPayments';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='FreightPayments';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('FreightPayments','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('FreightPayments','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='LBX';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='LBX';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('LBX','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('LBX','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='STMT';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='STMT';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('STMT','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('STMT','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Shipping';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Shipping';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Shipping','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Shipping','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='GeneralLedger';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='GeneralLedger';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('GeneralLedger','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('GeneralLedger','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='LabelPrinting';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='LabelPrinting';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('LabelPrinting','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('LabelPrinting','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OPMBatchJobs';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OPMBatchJobs';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OPMBatchJobs','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OPMBatchJobs','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='CustomerInfo';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='CustomerInfo';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('CustomerInfo','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('CustomerInfo','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='APInvoices';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='APInvoices';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('APInvoices','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('APInvoices','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ItemAttribute';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ItemAttribute';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ItemAttribute','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ItemAttribute','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='QualitySpecs';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='QualitySpecs';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('QualitySpecs','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('QualitySpecs','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='BatchJobs';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='BatchJobs';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('BatchJobs','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('BatchJobs','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ARFreight';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ARFreight';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ARFreight','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ARFreight','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='TripStop';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='TripStop';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('TripStop','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('TripStop','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='CarrierPointOutbound';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='CarrierPointOutbound';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('CarrierPointOutbound','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('CarrierPointOutbound','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='WriteBOLShipment';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='WriteBOLShipment';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('WriteBOLShipment','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('WriteBOLShipment','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OTMDelivery';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OTMDelivery';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OTMDelivery','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OTMDelivery','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OTMPlannedShipment';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OTMPlannedShipment';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OTMPlannedShipment','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OTMPlannedShipment','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OTMPlannedShipmentStatus';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OTMPlannedShipmentStatus';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OTMPlannedShipmentStatus','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OTMPlannedShipmentStatus','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='PurchaseOrder';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='PurchaseOrder';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('PurchaseOrder','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('PurchaseOrder','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='POReceipts';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='POReceipts';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('POReceipts','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('POReceipts','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ReadBOLShipmentAck';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ReadBOLShipmentAck';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ReadBOLShipmentAck','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ReadBOLShipmentAck','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ReadShippingExcep';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='ReadShippingExcep';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ReadShippingExcep','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('ReadShippingExcep','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='QualityResults';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='QualityResults';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('QualityResults','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('QualityResults','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='EntityResponse';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='EntityResponse';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('EntityResponse','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('EntityResponse','ENABLED');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='RCVResponse';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='RCVResponse';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('RCVResponse','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('RCVResponse','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Bundle_TestResults';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Bundle_TestResults';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Bundle_TestResults','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Bundle_TestResults','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='LoadVMICustForeCastInfo';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='LoadVMICustForeCastInfo';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('LoadVMICustForeCastInfo','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('LoadVMICustForeCastInfo','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='MROTagLabelPrinring';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='MROTagLabelPrinring';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('MROTagLabelPrinring','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('MROTagLabelPrinring','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OPMBatchTrx';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OPMBatchTrx';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OPMBatchTrx','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OPMBatchTrx','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OSPTags';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='OSPTags';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OSPTags','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('OSPTags','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='NSNEQMOSTrxImport';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='NSNEQMOSTrxImport';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('NSNEQMOSTrxImport','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('NSNEQMOSTrxImport','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='QualityResults_ROSS';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='QualityResults_ROSS';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('QualityResults_ROSS','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('QualityResults_ROSS','ENABLED');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='MTR_Report';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='MTR_Report';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('MTR_Report','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('MTR_Report','ENABLED');
END IF;
-- Begin 0.3 --
l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Nucor_USBankNSNE_ACH_1_1';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Nucor_USBankNSNE_ACH_1_1';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Nucor_USBankNSNE_ACH_1_1','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Nucor_USBankNSNE_ACH_1_1','ENABLED');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Nucor_USBankNSNE_PP_1_1';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Nucor_USBankNSNE_PP_1_1';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Nucor_USBankNSNE_PP_1_1','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Nucor_USBankNSNE_PP_1_1','ENABLED');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Nucor_USBankNSNE_STMT_1_1';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Nucor_USBankNSNE_STMT_1_1';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Nucor_USBankNSNE_STMT_1_1','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Nucor_USBankNSNE_STMT_1_1','ENABLED');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Nucor_USBankNSNE_LBX_1_1';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_TRX_NOTIF WHERE TRANSACTION_NAME='Nucor_USBankNSNE_LBX_1_1';
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Nucor_USBankNSNE_LBX_1_1','ENABLED');
ELSE
Insert into XXNUC_COMM_TRX_NOTIF (TRANSACTION_NAME,NOTIFICATION) values ('Nucor_USBankNSNE_LBX_1_1','ENABLED');
END IF;

-- End 0.3
l_count := 0;
SELECT COUNT(*) 
  INTO l_count 
  FROM XXNUC_COMM_EML_NOTIF 
WHERE TRANSACTION_NAME='ConsumeB2BErrorMsg' 
  and EMAIL_GROUP = 'AuditLog' 
  and NOTIFICTION_TYPE = 'ACTOR(TO:)' 
  and ERROR_NOTIFICATION = 'YES' 
  and WARNING_NOTIFICATION = 'YES' 
  and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ConsumeB2BErrorMsg';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ConsumeB2BErrorMsg','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ConsumeB2BErrorMsg','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='SalesOrder' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='SalesOrder';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('SalesOrder','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('SalesOrder','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='CPFreightCostInvRate' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='CPFreightCostInvRate';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('CPFreightCostInvRate','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('CPFreightCostInvRate','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='AuditLog' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='AuditLog';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('AuditLog','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('AuditLog','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='QualityResults' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='QualityResults';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('QualityResults','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('QualityResults','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='FreightPayments' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='FreightPayments';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('FreightPayments','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('FreightPayments','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='LBX' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='LBX';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('LBX','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('LBX','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='STMT' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='STMT';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('STMT','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('STMT','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OPMBatchJobs' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OPMBatchJobs';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OPMBatchJobs','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OPMBatchJobs','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='Shipping' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='Shipping';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('Shipping','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('Shipping','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='GeneralLedger' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='GeneralLedger';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('GeneralLedger','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('GeneralLedger','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='LabelPrinting' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='LabelPrinting';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('LabelPrinting','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('LabelPrinting','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='CustomerInfo' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='CustomerInfo';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('CustomerInfo','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('CustomerInfo','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='APInvoices' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='APInvoices';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('APInvoices','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('APInvoices','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ItemAttribute' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ItemAttribute';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ItemAttribute','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ItemAttribute','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='QualitySpecs' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='QualitySpecs';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('QualitySpecs','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('QualitySpecs','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='BatchJobs' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='BatchJobs';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('BatchJobs','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('BatchJobs','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ARFreight' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ARFreight';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ARFreight','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ARFreight','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='TripStop' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='TripStop';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('TripStop','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('TripStop','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='CarrierPointOutbound' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='CarrierPointOutbound';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('CarrierPointOutbound','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('CarrierPointOutbound','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='WriteBOLShipment' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='WriteBOLShipment';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('WriteBOLShipment','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('WriteBOLShipment','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OTMDelivery' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OTMDelivery';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OTMDelivery','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OTMDelivery','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OTMPlannedShipment' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OTMPlannedShipment';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OTMPlannedShipment','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OTMPlannedShipment','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OTMPlannedShipmentStatus' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OTMPlannedShipmentStatus';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OTMPlannedShipmentStatus','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OTMPlannedShipmentStatus','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='PurchaseOrder' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='PurchaseOrder';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('PurchaseOrder','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('PurchaseOrder','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='POReceipts' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='POReceipts';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('POReceipts','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('POReceipts','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ReadBOLShipmentAck' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ReadBOLShipmentAck';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ReadBOLShipmentAck','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ReadBOLShipmentAck','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ReadShippingExcep' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='ReadShippingExcep';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ReadShippingExcep','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('ReadShippingExcep','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='QualityResults' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='QualityResults';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('QualityResults','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('QualityResults','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='RCVResponse' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='RCVResponse';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('RCVResponse','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('RCVResponse','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='EntityResponse' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='EntityResponse';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('EntityResponse','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('EntityResponse','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='LoadVMICustForeCastInfo' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='LoadVMICustForeCastInfo';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('LoadVMICustForeCastInfo','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('LoadVMICustForeCastInfo','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='MROTagLabelPrinring' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='MROTagLabelPrinring';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('MROTagLabelPrinring','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('MROTagLabelPrinring','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OSPTags' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OSPTags';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OSPTags','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OSPTags','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OPMBatchTrx' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='OPMBatchTrx';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OPMBatchTrx','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('OPMBatchTrx','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='NSNEQMOSTrxImport' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='NSNEQMOSTrxImport';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('NSNEQMOSTrxImport','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('NSNEQMOSTrxImport','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='Bundle_TestResults' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='Bundle_TestResults';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('Bundle_TestResults','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('Bundle_TestResults','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='QualityResults_ROSS' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='QualityResults_ROSS';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('QualityResults_ROSS','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('QualityResults_ROSS','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='MTR_Report' and EMAIL_GROUP = 'AuditLog' and NOTIFICTION_TYPE = 'ACTOR(TO:)' and ERROR_NOTIFICATION = 'YES' and WARNING_NOTIFICATION = 'YES' and (COMPLETED_NOTIFICATION = 'YES' or COMPLETED_NOTIFICATION = 'NO');
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_EML_NOTIF WHERE TRANSACTION_NAME='MTR_Report';
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('MTR_Report','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
ELSE
Insert into XXNUC_COMM_EML_NOTIF (TRANSACTION_NAME,EMAIL_GROUP,NOTIFICTION_TYPE,NOTIFICATION,ERROR_NOTIFICATION,WARNING_NOTIFICATION,COMPLETED_NOTIFICATION) values ('MTR_Report','AuditLog','ACTOR(TO:)','ENABLED','YES','YES','NO');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_AUDIT_STATUS WHERE CODE=1;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_AUDIT_STATUS WHERE CODE=1;
Insert into XXNUC_COMM_AUDIT_STATUS (CODE,MEANING) values (1,'Inprocess');
ELSE
Insert into XXNUC_COMM_AUDIT_STATUS (CODE,MEANING) values (1,'Inprocess');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_AUDIT_STATUS WHERE CODE=2;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_AUDIT_STATUS WHERE CODE=2;
Insert into XXNUC_COMM_AUDIT_STATUS (CODE,MEANING) values (2,'Success');
ELSE
Insert into XXNUC_COMM_AUDIT_STATUS (CODE,MEANING) values (2,'Success');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_AUDIT_STATUS WHERE CODE=3;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_AUDIT_STATUS WHERE CODE=3;
Insert into XXNUC_COMM_AUDIT_STATUS (CODE,MEANING) values (3,'Warning');
ELSE
Insert into XXNUC_COMM_AUDIT_STATUS (CODE,MEANING) values (3,'Warning');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_AUDIT_STATUS WHERE CODE=4;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_AUDIT_STATUS WHERE CODE=4;
Insert into XXNUC_COMM_AUDIT_STATUS (CODE,MEANING) values (4,'Error');
ELSE
Insert into XXNUC_COMM_AUDIT_STATUS (CODE,MEANING) values (4,'Error');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=3;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=3;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (3,'SAP');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (3,'SAP');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=4;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=4;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (4,'Bank');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (4,'Bank');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=5;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=5;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (5,'CarrierPoint');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (5,'CarrierPoint');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=6;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=6;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (6,'Tensile');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (6,'Tensile');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=7;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=7;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (7,'Suppliers');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (7,'Suppliers');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=8;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=8;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (8,'Customers');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (8,'Customers');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=9;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=9;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (9,'Inclusion');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (9,'Inclusion');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=10;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=10;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (10,'American Bar Products');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (10,'American Bar Products');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=11;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=11;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (11,'Arcelor - Mittal');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (11,'Arcelor - Mittal');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=12;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=12;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (12,'Berkeley');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (12,'Berkeley');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=13;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=13;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (13,'CFNE');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (13,'CFNE');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=14;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=14;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (14,'Chemistry Upload');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (14,'Chemistry Upload');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=15;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=15;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (15,'DJJ');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (15,'DJJ');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=16;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=16;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (16,'EnMark');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (16,'EnMark');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=17;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=17;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (17,'IFS');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (17,'IFS');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=18;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=18;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (18,'INFOR');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (18,'INFOR');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=19;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=19;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (19,'INFOR (WS)');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (19,'INFOR (WS)');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=20;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=20;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (20,'Local MillDB');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (20,'Local MillDB');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=21;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=21;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (21,'QMOS');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (21,'QMOS');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=22;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=22;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (22,'Shipware(WS)');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (22,'Shipware(WS)');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=23;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=23;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (23,'Tagware');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (23,'Tagware');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=24;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=24;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (24,'WS(SMS)');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (24,'WS(SMS)');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=25;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=25;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (25,'Spectrometer');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (25,'Spectrometer');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=26;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=26;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (26,'Corporate');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (26,'Corporate');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=1;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=1;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (1,'SOA');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (1,'SOA');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=2;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=2;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (2,'EBS');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (2,'EBS');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=28;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=28;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (28,'B2B');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (28,'B2B');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=27;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=27;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (27,'NiceLabel');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (27,'NiceLabel');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=81;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=81;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (81,'USBankNSNE');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (81,'USBankNSNE');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=0;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=0;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (0,'Not Registered System');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (0,'Not Registered System');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=82;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=82;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (82,'USBankNCFNE');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (82,'USBankNCFNE');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=83;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=83;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (83,'NTCBankNCFWI');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (83,'NTCBankNCFWI');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=29;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=29;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (29,'JMS');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (29,'JMS');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=30;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=30;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (30,'MES Systems');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (30,'MES Systems');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=31;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=31;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (31,'OTM');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (31,'OTM');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=32;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=32;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (32,'Transentric');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (32,'Transentric');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=33;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=33;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (33,'L2');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (33,'L2');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=34;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=34;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (34,'RailInc');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (34,'RailInc');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=35;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=35;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (35,'ASN');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (35,'ASN');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_INTEG_SYS WHERE CODE=37;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_INTEG_SYS WHERE CODE=37;
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (37,'AS400');
ELSE
Insert into XXNUC_COMM_INTEG_SYS (CODE,MEANING) values (37,'AS400');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_AUDIT_LOGTYP WHERE CODE=1;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_AUDIT_LOGTYP WHERE CODE=1;
Insert into XXNUC_COMM_AUDIT_LOGTYP (CODE,MEANING) values (1,'Information');
ELSE
Insert into XXNUC_COMM_AUDIT_LOGTYP (CODE,MEANING) values (1,'Information');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_AUDIT_LOGTYP WHERE CODE=2;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_AUDIT_LOGTYP WHERE CODE=2;
Insert into XXNUC_COMM_AUDIT_LOGTYP (CODE,MEANING) values (2,'Report');
ELSE
Insert into XXNUC_COMM_AUDIT_LOGTYP (CODE,MEANING) values (2,'Report');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_AUDIT_LOGTYP WHERE CODE=3;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_AUDIT_LOGTYP WHERE CODE=3;
Insert into XXNUC_COMM_AUDIT_LOGTYP (CODE,MEANING) values (3,'Warning');
ELSE
Insert into XXNUC_COMM_AUDIT_LOGTYP (CODE,MEANING) values (3,'Warning');
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_AUDIT_LOGTYP WHERE CODE=4;
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_AUDIT_LOGTYP WHERE CODE=4;
Insert into XXNUC_COMM_AUDIT_LOGTYP (CODE,MEANING) values (4,'Error');
ELSE
Insert into XXNUC_COMM_AUDIT_LOGTYP (CODE,MEANING) values (4,'Error');
END IF;


l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_GLOBAL_SETT WHERE ATTRIBUTENAME='EmailNotification';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_GLOBAL_SETT WHERE ATTRIBUTENAME='EmailNotification';
Insert into XXNUC_COMM_GLOBAL_SETT (ATTRIBUTENAME,V_ATTRIBUTEVALUE1,V_ATTRIBUTEVALUE2,N_ATTRIBUTEVALUE1,N_ATTRIBUTEVALUE2) values ('EmailNotification','ENABLED',null,null,null);
ELSE
Insert into XXNUC_COMM_GLOBAL_SETT (ATTRIBUTENAME,V_ATTRIBUTEVALUE1,V_ATTRIBUTEVALUE2,N_ATTRIBUTEVALUE1,N_ATTRIBUTEVALUE2) values ('EmailNotification','ENABLED',null,null,null);
END IF;

l_count := 0;
SELECT COUNT(*) INTO l_count FROM XXNUC_COMM_GLOBAL_SETT WHERE ATTRIBUTENAME='AuditLog';
IF l_count > 0 THEN 
DELETE FROM XXNUC_COMM_GLOBAL_SETT WHERE ATTRIBUTENAME='AuditLog';
Insert into XXNUC_COMM_GLOBAL_SETT (ATTRIBUTENAME,V_ATTRIBUTEVALUE1,V_ATTRIBUTEVALUE2,N_ATTRIBUTEVALUE1,N_ATTRIBUTEVALUE2) values ('AuditLog','ENABLED',null,null,null);
ELSE
Insert into XXNUC_COMM_GLOBAL_SETT (ATTRIBUTENAME,V_ATTRIBUTEVALUE1,V_ATTRIBUTEVALUE2,N_ATTRIBUTEVALUE1,N_ATTRIBUTEVALUE2) values ('AuditLog','ENABLED',null,null,null);
END IF;



COMMIT;
END;