<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="DJJGetAPInvoiceV1_ep" targetNamespace="http://xmlns.eia.com/ABF/NUC_APInvoice_DJJ_EBiz_ABF/DJJGetAPInvoiceV1_ep" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://xmlns.eia.com/ABF/NUC_APInvoice_DJJ_EBiz_ABF/DJJGetAPInvoiceV1_ep" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="DJJGetAPInvoiceV1_ep">
      <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://xmlns.eia.com/ABF/NUC_APInvoice_DJJ_EBiz_ABF/DJJGetAPInvoiceV1_ep" location="DJJGetAPInvoiceV1_ep.wsdl"/>
</wsdl:definitions>
