<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns0="http://xmlns.oracle.com/SOAAppDev/NUC_PurchaseOrder_DJJ_EBiz_ABF/DJJGetPurchaseOrdersV1"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://xmlns.eia.com/ABS/EBiz/PurchaseOrderABS/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns10="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns15="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns14="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns17="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0"
                xmlns:ns16="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns18="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DJJGetPurchaseOrdersV1.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiResponsePOHeader" namespace=""/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DJJGetPurchaseOrdersV1.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
        <oracle-xsl-mapper:param name="POCounterParams"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/PurchaseOrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CancelPurchaseOrderLineRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JAN 04 07:19:38 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="POCounterParams"/>
  <xsl:template match="/">
    <xsl:variable name="varPOLineCounter"
                  select="number($POCounterParams/ns1:parameters/ns1:item[ns1:name='POLineCounter']/ns1:value)"/>
    <xsl:variable name="varDivision"
                  select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm", "CONSUMER_REF_ID", /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, "EBS_DIVISION", "" )'/>
    <xsl:variable name="varOrgName"
                  select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm", "CONSUMER_REF_ID", /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, "EBS_OPERATING_UNIT_NAME", "" )'/>
    <xsl:variable name="varOrgId"
                  select="oraext:query-database(concat(&quot;Select organization_id as retvalue from APPS.hr_operating_units where name='&quot;,$varOrgName,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
    <tns:CancelPurchaseOrderLineRequestMessage>
      <ns10:HeaderRq>
        <ns10:Language>ENG</ns10:Language>
        <ns10:ComponentID>I093</ns10:ComponentID>
        <ns10:ServiceName>TEMP</ns10:ServiceName>
        <ns10:TransactionIDREF>TEMP</ns10:TransactionIDREF>
        <ns10:TransactionName>PurchaseOrder</ns10:TransactionName>
        <ns10:Source>15</ns10:Source>
        <ns10:Target>2</ns10:Target>
        <ns10:TimeStamp>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </ns10:TimeStamp>
      </ns10:HeaderRq>
      <tns:AppsContext>
        <ns11:UserName>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm', 'DIVISION', $varDivision, 'EBS_USER_NAME', '' )"/>
        </ns11:UserName>
        <!--ns11:UserId>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm', 'DIVISION', 'NSNE', 'EBS_USER_ID', '' )"/>
        </ns11:UserId-->
        <ns11:ResponsibilityName>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_ORG_RESP_NAME.dvm', 'DIVISION', $varDivision, 'EBS_RESP_NAME', '', 'EBS_FUNCTION_AREA', 'PURCHASE ORDER' )"/>
        </ns11:ResponsibilityName>
        <ns11:OrgId>
          <xsl:value-of select="$varOrgId"/>
        </ns11:OrgId>
      </tns:AppsContext>
      <tns:ListOfPurchaseOrders>
        <ns17:PurchaseOrder>
          <ns17:Doctypename>PO</ns17:Doctypename>
          <ns17:Documentnum>
            <xsl:value-of select="/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/POID"/>
          </ns17:Documentnum>
          <ns17:Documentsubtype>STANDARD</ns17:Documentsubtype>
          <ns17:ListOfPurchaseOrderLines>
            <ns17:PurchaseOrderLine>
              <ns17:Linenum>
                <xsl:value-of select="/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/POLine/POConsumerLineModel[$varPOLineCounter]/POLineID"/>
              </ns17:Linenum>
              <ns17:Orgid>
                <xsl:value-of select="$varOrgId"/>
              </ns17:Orgid>
              <ns17:Shipmentnum>
                <xsl:text disable-output-escaping="no">1</xsl:text>
              </ns17:Shipmentnum>
            </ns17:PurchaseOrderLine>
          </ns17:ListOfPurchaseOrderLines>
        </ns17:PurchaseOrder>
      </tns:ListOfPurchaseOrders>
    </tns:CancelPurchaseOrderLineRequestMessage>
  </xsl:template>
</xsl:stylesheet>
