<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns2="http://xmlns.eia.com/ABS/EBiz/PurchaseOrderABS/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/common/UomAO/1.0"
                xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/AO/EBiz/common/ItemAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns0="http://schemas.oracle.com/service/bpel/common"
                xmlns:tns="http://xmlns.oracle.com/SOAAppDev/NUC_PurchaseOrder_DJJ_EBiz_ABF/DJJGetPurchaseOrdersV1"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns10="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns15="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns14="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns13="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns17="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderAO/1.0"
                xmlns:ns16="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns18="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DJJGetPurchaseOrdersV1.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ApiResponsePOHeader" namespace=""/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/PurchaseOrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryPurchaseOrderResponseMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"/>
        <oracle-xsl-mapper:param name="QueryPurchaseOrderByExample_RespMsg.QueryPurchaseOrderResponseMessage"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/PurchaseOrderABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreatePurchaseOrderRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/PurchaseOrderABM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JAN 14 01:22:02 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="QueryPurchaseOrderByExample_RespMsg.QueryPurchaseOrderResponseMessage"/>
  <xsl:template match="/">
    <xsl:variable name="varOrgName"
                  select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm", "CONSUMER_REF_ID", /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, "EBS_OPERATING_UNIT_NAME", "" )'/>
    <xsl:variable name="varDivision"
                  select='dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm", "CONSUMER_REF_ID", /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, "EBS_DIVISION", "" )'/>
    <xsl:variable name="varOrgId"
                  select="oraext:query-database(concat(&quot;Select organization_id as retvalue from APPS.hr_operating_units where name='&quot;,$varOrgName,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
    <ns1:CreatePurchaseOrderRequestMessage>
      <ns10:HeaderRq>
        <ns10:Language>ENG</ns10:Language>
        <ns10:ComponentID>I093</ns10:ComponentID>
        <ns10:ServiceName>TEMP</ns10:ServiceName>
        <ns10:TransactionIDREF>TEMP</ns10:TransactionIDREF>
        <ns10:TransactionName>PurchaseOrder</ns10:TransactionName>
        <ns10:Source>15</ns10:Source>
        <ns10:Target>2</ns10:Target>
        <ns10:TimeStamp>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </ns10:TimeStamp>
      </ns10:HeaderRq>
      <ns1:AppsContext>
        <ns11:UserName>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm', 'DIVISION', $varDivision, 'EBS_USER_NAME', '' )"/>
        </ns11:UserName>
        <!--ns11:UserId>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm', 'DIVISION', 'NSNE', 'EBS_USER_ID', $oracle_empty_param )"/>
        </ns11:UserId-->
        <ns11:ResponsibilityName>
          <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_ORG_RESP_NAME.dvm', 'DIVISION', $varDivision, 'EBS_RESP_NAME', '', 'EBS_FUNCTION_AREA', 'PURCHASE ORDER' )"/>
        </ns11:ResponsibilityName>
        <ns11:OrgId>
          <xsl:value-of select="$varOrgId"/>
        </ns11:OrgId>
      </ns1:AppsContext>
      <ns1:ListOfPurchaseOrders>
        <ns17:PurchaseOrder>
          <ns17:Action>UPDATE</ns17:Action>
          <ns17:Agentname>
            <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_AGENT_NAME', '' )"/>
          </ns17:Agentname>
          <!-- Changed Approval Status as part of I093 CR for Release 1.1
          <ns17:Approvalstatus>INITIATE APPROVAL</ns17:Approvalstatus-->
          
          <xsl:choose>
            <xsl:when test='(dvm:lookupValue ("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_VENDORSITECODE_DEFAULTS.dvm", "DJJ_ORG_ID", /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/DJJOrgID, "EBS_PO_AUTOAPPROVAL_FLAG", "","CONSUMER_REF_ID", /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID)) = "true"'>
              <ns17:Approvalstatus>APPROVED</ns17:Approvalstatus>
            </xsl:when>
            <xsl:otherwise>
              <ns17:Approvalstatus>INITIATE APPROVAL</ns17:Approvalstatus>
            </xsl:otherwise>
          </xsl:choose>
          
          <ns17:Approveddate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </ns17:Approveddate>
          <ns17:Creationdate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
          </ns17:Creationdate>
          <ns17:Currencycode>USD</ns17:Currencycode>
          <ns17:Documentnum>
            <xsl:value-of select="/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/POID"/>
          </ns17:Documentnum>
          <ns17:Documentsubtype>PO</ns17:Documentsubtype>
          <ns17:Documenttypecode>STANDARD</ns17:Documenttypecode>
          <xsl:if test="/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/POLine/POConsumerLineModel/ShipToLocation/POConsumerLineShipToModel/POFufillment/POFufillmentModel/SupplierName">
            <ns17:Globalattribute4>
              <xsl:value-of select="/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/POLine/POConsumerLineModel/ShipToLocation/POConsumerLineShipToModel/POFufillment/POFufillmentModel/SupplierName"/>
            </ns17:Globalattribute4>
          </xsl:if>
          <ns17:Globalattribute5>Brokered</ns17:Globalattribute5>
          <ns17:Globalattributecategory>STANDARD</ns17:Globalattributecategory>
          <ns17:Interfacesourcecode>DJJ</ns17:Interfacesourcecode>
          <ns17:OperatingUnit>
            <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_OPERATING_UNIT_NAME', '' )"/>
          </ns17:OperatingUnit>
          <ns17:Paymentterms xsi:nil="true"></ns17:Paymentterms>
          <!--ns17:Processcode>PENDING</ns17:Processcode-->
          <ns17:Shiptolocation>
            <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_SHIP_TO_LOCATION_CODE', '' )"/>
          </ns17:Shiptolocation>
          <ns17:Vendorname>
            <!-- As a part of Defect#1586-->
            <!--xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_VENDORSITECODE_DEFAULTS.dvm', 'DJJ_OFFICE_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/DJJOfficeID, 'EBS_VENDOR_NAME', '', 'CONSUMER_REF_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'DJJ_ORG_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/DJJOrgID)"/-->
            <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_VENDORSITECODE_DEFAULTS.dvm', 'DJJ_ORG_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/DJJOrgID, 'EBS_VENDOR_NAME', '', 'CONSUMER_REF_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID)"/>
          </ns17:Vendorname>
          <ns17:Vendorsitecode>
            <!-- As a part of Defect#1586-->
            <!--xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_VENDORSITECODE_DEFAULTS.dvm', 'DJJ_OFFICE_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/DJJOfficeID, 'EBS_VENDOR_SITE_CODE', '', 'CONSUMER_REF_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'DJJ_ORG_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/DJJOrgID)"/-->
            <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_VENDORSITECODE_DEFAULTS.dvm', 'DJJ_ORG_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/DJJOrgID, 'EBS_VENDOR_SITE_CODE', '', 'CONSUMER_REF_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID)"/>
          </ns17:Vendorsitecode>
          <ns17:ListOfPurchaseOrderLines>
            <xsl:for-each select="/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/POLine/POConsumerLineModel">
              <xsl:variable name="CurrentLine" select="POLineID"/>
              <xsl:variable name="varSecondaryUOM"
                            select="oraext:query-database (concat(&quot;select decode(NVL(msi.tracking_quantity_ind,'P'),'P',NULL,msi.secondary_uom_code) secondar_uom from mtl_system_items msi where msi.segment1 = '&quot;, ConsumerItemRefID ,&quot;' and msi.organization_id  in (select mp.master_organization_id from org_organization_Definitions ood, mtl_parameters mp where ood.operating_unit = &quot;,$varOrgId, &quot; and rownum &lt; 2)&quot;), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
              <xsl:if test="not($QueryPurchaseOrderByExample_RespMsg.QueryPurchaseOrderResponseMessage/ns1:QueryPurchaseOrderResponseMessage/ns1:ListOfPurchaseOrders/ns17:PurchaseOrder/ns17:ListOfPurchaseOrderLines/ns17:PurchaseOrderLine[(ns17:Linenum = $CurrentLine)]/ns17:Linenum)">
                <ns17:PurchaseOrderLine>
                  <ns17:Action>ADD</ns17:Action>
                  <ns17:Interfacelineid xsi:nil="true"/>
                  <xsl:if test="ConsumerItemRefID">
                    <ns17:Item>
                      <xsl:value-of select="ConsumerItemRefID"/>
                    </ns17:Item>
                    <!--ns17:Item>200030</ns17:Item-->
                    <!--xsl:choose>
                      <xsl:when test="ConsumerItemRefID !=''">
                        <ns17:Item-->
                    <!--xsl:value-of select="ConsumerItemRefID"/-->
                    <!--xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_ITEM', '' )"/>
                        </ns17:Item>
                      </xsl:when>
                      <xsl:otherwise>
                        <ns17:Item-->
                    <!--ns17:Item>100000205</ns17:Item-->
                    <!--xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID', /ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_ITEM', '' )"/>
                        </ns17:Item>
                      </xsl:otherwise>
                    </xsl:choose-->
                  </xsl:if>
                  <!--xsl:if test="ShipToLocation/POConsumerLineShipToModel/POFufillment/POFufillmentModel/ShipFromName"-->
                  <ns17:Lineattribute1>
                    <xsl:value-of select="concat(ShipToLocation/POConsumerLineShipToModel/POFufillment/POFufillmentModel/ShipFromCity,' ',ShipToLocation/POConsumerLineShipToModel/POFufillment/POFufillmentModel/ShipFromState)"/>
                  </ns17:Lineattribute1>
                  <!--/xsl:if-->
                  <xsl:variable name="varModeCode"
                                select="normalize-space (ShipToLocation/POConsumerLineShipToModel[1]/ModeCode)"/>
                  <ns17:Lineattribute2>
                    <xsl:value-of select="$varModeCode"/>
                  </ns17:Lineattribute2>
                  <ns17:Lineattributecategorylines>Raw Materials</ns17:Lineattributecategorylines>
                  <xsl:if test="POLineID">
                    <ns17:Linenum>
                      <xsl:value-of select="POLineID"/>
                    </ns17:Linenum>
                  </xsl:if>
                  <ns17:Linetype>Goods</ns17:Linetype>
                  <ns17:Needbydate>
                    <!--xsl:value-of select="xp20:add-dayTimeDuration-to-dateTime (xp20:current-date ( ), 'P2D' )"/-->
                    <xsl:value-of select="/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ExpirationDate"/>
                  </ns17:Needbydate>
                  <ns17:Orgid>
                    <xsl:value-of select="$varOrgId"/>
                  </ns17:Orgid>
                  <ns17:Paymentterms xsi:nil="true"/>
                  <xsl:if test="QtyOrderedLB">
                    <ns17:Quantity>
                      <xsl:value-of select="QtyOrderedLB"/>
                    </ns17:Quantity>
                  </xsl:if>
                  <xsl:choose>
                    <xsl:when test='$varModeCode = "RL"'>
                      <ns17:Receivingrouting>Direct Delivery</ns17:Receivingrouting>
                    </xsl:when>
                    <xsl:when test='$varModeCode = "TK"'>
                      <ns17:Receivingrouting>Direct Delivery</ns17:Receivingrouting>
                    </xsl:when>
                    <xsl:otherwise>
                      <ns17:Receivingrouting>Direct Delivery</ns17:Receivingrouting>
                    </xsl:otherwise>
                  </xsl:choose>
                  <xsl:choose>
                    <xsl:when test="$varSecondaryUOM != ''">
                      <ns17:Secondaryquantity>
                        <xsl:value-of select="oraext:query-database (concat(&quot;select inv_convert.inv_um_convert_new(msi.inventory_item_id,NULL,&quot;,QtyOrderedLB,&quot;,msi.primary_uom_code,decode(NVL(msi.tracking_quantity_ind,'P'),'P',NULL,msi.secondary_uom_code),NULL,NULL,'W') secondary_quantity from mtl_system_items msi where msi.segment1 = '&quot;,ConsumerItemRefID,&quot;' and msi.organization_id  in (select mp.master_organization_id from org_organization_Definitions ood, mtl_parameters mp where ood.operating_unit = &quot;,$varOrgId,&quot;and rownum &lt; 2 )&quot;), false ( ), false ( ), &quot;jdbc/ebsapps&quot; )"/>
                      </ns17:Secondaryquantity>
                    </xsl:when>
                  </xsl:choose>
                  <xsl:choose>
                    <xsl:when test="$varSecondaryUOM != ''">
                      <ns17:Secondaryuom>
                        <xsl:value-of select="$varSecondaryUOM"/>
                      </ns17:Secondaryuom>
                    </xsl:when>
                  </xsl:choose>
                  <ns17:Shipmentnum>1</ns17:Shipmentnum>
                  <ns17:Shiptolocation>
                    <xsl:value-of select="dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm','CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_SHIP_TO_LOCATION_CODE', '' )"/>
                  </ns17:Shiptolocation>
                  <ns17:Unitprice>
                    <xsl:value-of select="ShipToLocation/POConsumerLineShipToModel/PriceRateLBS"/>
                  </ns17:Unitprice>
                  <ns17:Uomcode>LBS</ns17:Uomcode>
                  <ns17:ListOfPurchaseOrderDistLines>
                    <ns17:PurchaseOrderDistLines>
                      <!--ns17:Chargeaccountsegment1>
                        <xsl:value-of select="substring(dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_GL_CC', '' ),1.0,4.0)"/>
                      </ns17:Chargeaccountsegment1>
                      <ns17:Chargeaccountsegment2>
                        <xsl:value-of select="substring(dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_GL_CC', '' ),6.0,2.0)"/>
                      </ns17:Chargeaccountsegment2>
                      <ns17:Chargeaccountsegment3>
                        <xsl:value-of select="substring(dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_GL_CC', '' ),9.0,3.0)"/>
                      </ns17:Chargeaccountsegment3>
                      <ns17:Chargeaccountsegment4>
                        <xsl:value-of select="substring(dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_GL_CC', '' ),13.0,5.0)"/>
                      </ns17:Chargeaccountsegment4>
                      <ns17:Chargeaccountsegment5>
                        <xsl:value-of select="substring(dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_GL_CC', '' ),20.0,4.0)"/>
                      </ns17:Chargeaccountsegment5>
                      <ns17:Chargeaccountsegment6>
                        <xsl:value-of select="substring(dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_GL_CC', '' ),25.0,4.0)"/>
                      </ns17:Chargeaccountsegment6>
                      <ns17:Chargeaccountsegment7>
                        <xsl:value-of select="substring(dvm:lookupValue ('oramds:/apps/EIAMetadata/CommonArtifacts/dvm/DJJ_EBS_DIVISION_DEFAULTS.dvm', 'CONSUMER_REF_ID',/ApiResponsePOHeader/POHeader/POConsumerHeaderModel/ConsumerRefID, 'EBS_DEFAULT_GL_CC', '' ),30.0,4.0)"/>
                      </ns17:Chargeaccountsegment7-->
                      <ns17:Distributionnum>1</ns17:Distributionnum>
                      <ns17:Linenum>
                        <xsl:value-of select="POLineID"/>
                      </ns17:Linenum>
                      <ns17:Orgid>
                        <xsl:value-of select="$varOrgId"/>
                      </ns17:Orgid>
                      <xsl:if test="QtyOrderedLB">
                        <ns17:Quantityordered>
                          <xsl:value-of select="QtyOrderedLB"/>
                        </ns17:Quantityordered>
                      </xsl:if>
                      <ns17:Setofbooks xsi:nil="true"/>
                    </ns17:PurchaseOrderDistLines>
                  </ns17:ListOfPurchaseOrderDistLines>
                </ns17:PurchaseOrderLine>
              </xsl:if>
            </xsl:for-each>
          </ns17:ListOfPurchaseOrderLines>
        </ns17:PurchaseOrder>
      </ns1:ListOfPurchaseOrders>
    </ns1:CreatePurchaseOrderRequestMessage>
  </xsl:template>
</xsl:stylesheet>
