<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions
     name="QualitySpecABS"
     targetNamespace="http://oracle.com/sca/soapservice/Manish/NUC_EBizQualitySpec_ABS/QualitySpecABS"
     xmlns:tns="http://oracle.com/sca/soapservice/Manish/NUC_EBizQualitySpec_ABS/QualitySpecABS"
     xmlns:inp1="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAM/1.0"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    >
	<!--
    <wsdl:documentation>
        <abstractWSDL>http://rzmkea252.rz.nucorsteel.local:8001/soa-infra/services/nuc/NUC_EBizQualitySpec_ABS!1.0/WSDLs/QualitySpecABS.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="QualitySpecABS">
        <plnk:role name="QualitySpecABSProvider" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
<wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="wss_username_token_service_policy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <sp:SupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
      <wsp:Policy>
         <sp:UsernameToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
            <wsp:Policy>
               <sp:WssUsernameToken10/>
            </wsp:Policy>
         </sp:UsernameToken>
      </wsp:Policy>
   </sp:SupportingTokens>
</wsp:Policy>  -->   <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.eia.com/AO/Ebiz/D2S/QualitySpecsAM/1.0" schemaLocation="../../../../AO/EBiz/D2S/V1.0/QualitySpecsAM.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="querySpecsReq" element="inp1:QueryQualitySpecsAddRq"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="querySpecsRes" element="inp1:QueryQualitySpecsAddRs"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="queryQualitySpec">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_pttBinding" type="tns:execute_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
      <!-- <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#wss_username_token_service_policy" wsdl:required="false"/> -->
        <wsdl:operation name="queryQualitySpec">
            <soap:operation style="document" soapAction="queryQualitySpec"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="QualitySpecABS">
        <wsdl:port name="execute_pt" binding="tns:execute_pttBinding">
            <soap:address location="http://www.org.com"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
