<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.eia.com/Infrastructure/UtilityXREF/1.0"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_XREF_Polling"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/SMG_SOA_PS/UtilityXREF_LoadDB/DB_XREF_Polling"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_XREF_Polling.wsdl"/>
        <oracle-xsl-mapper:rootElement name="XxnucXrefDataStgCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_XREF_Polling"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/processXREF_ep.wsdl"/>
        <oracle-xsl-mapper:rootElement name="processXREFData"
                                       namespace="http://xmlns.eia.com/Infrastructure/UtilityXREF/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAR 14 13:32:16 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:processXREFData>
      <tns:XREFName>
        <xsl:value-of select="/ns0:XxnucXrefDataStgCollection/ns0:XxnucXrefDataStg/ns0:xrefTableName"/>
      </tns:XREFName>
      <tns:ReferenceColumn>
        <xsl:value-of select="/ns0:XxnucXrefDataStgCollection/ns0:XxnucXrefDataStg/ns0:referenceColumn"/>
      </tns:ReferenceColumn>
      <tns:ReferenceValue>
        <xsl:value-of select="/ns0:XxnucXrefDataStgCollection/ns0:XxnucXrefDataStg/ns0:referenceValue"/>
      </tns:ReferenceValue>
      <tns:LookupColumn>
        <xsl:value-of select="/ns0:XxnucXrefDataStgCollection/ns0:XxnucXrefDataStg/ns0:lookupColumn"/>
      </tns:LookupColumn>
      <tns:LookupValue>
        <xsl:value-of select="/ns0:XxnucXrefDataStgCollection/ns0:XxnucXrefDataStg/ns0:lookupValue"/>
      </tns:LookupValue>
    </tns:processXREFData>
  </xsl:template>
</xsl:stylesheet>
