<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/InventoryTransactionAM/1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Get_InventoryTrx"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns2="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns8="http://xmlns.oracle.com/pcbpel/adapter/db/NextGen/NUC_EBizInventory_ABS/DB_Get_InventoryTrx"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns6="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:tns="http://oracle.com/sca/soapservice/NextGen/NUC_EBizInventory_ABS/EbizInventory_ABS"
                xmlns:ns7="http://xmlns.eia.com/AO/Ebiz/D2S/InventoryTransactionAO/1.0"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns3="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/EbizInventory_ABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryInventoryTransactionAddRq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/InventoryTransactionAM/1.0"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Get_InventoryTrx.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Get_InventoryTrx"/>
        <oracle-xsl-mapper:param name="g_Invoke_DB_Get_InventoryTrx_OutputVariable.OutputParameters"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/EbizInventory_ABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryInventoryTransactionAddRs"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/InventoryTransactionAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUN 30 02:15:05 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="g_Invoke_DB_Get_InventoryTrx_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <ns0:QueryInventoryTransactionAddRs>
      <ns6:HeaderRs>
        <ns6:RequestDetails>
          <ns6:Language>
            <xsl:value-of select="/ns0:QueryInventoryTransactionAddRq/ns6:HeaderRq/ns6:Language"/>
          </ns6:Language>
          <ns6:ComponentID>
            <xsl:value-of select="/ns0:QueryInventoryTransactionAddRq/ns6:HeaderRq/ns6:ComponentID"/>
          </ns6:ComponentID>
          <ns6:ServiceName>
            <xsl:value-of select="/ns0:QueryInventoryTransactionAddRq/ns6:HeaderRq/ns6:ServiceName"/>
          </ns6:ServiceName>
          <ns6:TransactionIDREF>
            <xsl:value-of select="/ns0:QueryInventoryTransactionAddRq/ns6:HeaderRq/ns6:TransactionIDREF"/>
          </ns6:TransactionIDREF>
          <ns6:TransactionName>
            <xsl:value-of select="/ns0:QueryInventoryTransactionAddRq/ns6:HeaderRq/ns6:TransactionName"/>
          </ns6:TransactionName>
          <ns6:Source>
            <xsl:value-of select="/ns0:QueryInventoryTransactionAddRq/ns6:HeaderRq/ns6:Source"/>
          </ns6:Source>
          <ns6:Target>
            <xsl:value-of select="/ns0:QueryInventoryTransactionAddRq/ns6:HeaderRq/ns6:Target"/>
          </ns6:Target>
          <ns6:TimeStamp>
            <xsl:value-of select="/ns0:QueryInventoryTransactionAddRq/ns6:HeaderRq/ns6:TimeStamp"/>
          </ns6:TimeStamp>
        </ns6:RequestDetails>
        <ns6:Status>
          <ns6:Status>Success</ns6:Status>
        </ns6:Status>
      </ns6:HeaderRs>
      <xsl:for-each select="$g_Invoke_DB_Get_InventoryTrx_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_TRX_PAYLOAD/ns1:P_TRX_PAYLOAD_ITEM">
        <ns7:InventoryTransactionDetails>
          <ns7:ListOfInvTrx>
            <ns7:TransactionID>
              <xsl:value-of select="ns1:TRANSACTION_ID"/>
            </ns7:TransactionID>
            <ns7:OrgID>
              <xsl:value-of select="ns1:ORGN_ID"/>
            </ns7:OrgID>
            <ns7:OrgCode>
              <xsl:value-of select="ns1:ORGN_CODE"/>
            </ns7:OrgCode>
            <ns7:OrgName>
              <xsl:value-of select="ns1:ORGN_NAME"/>
            </ns7:OrgName>
            <ns7:ResourceName>
              <xsl:value-of select="ns1:RESOURCE_NAME"/>
            </ns7:ResourceName>
            <ns7:TransactionTypeID>
              <xsl:value-of select="ns1:TRANSACTION_TYPE_ID"/>
            </ns7:TransactionTypeID>
            <ns7:TransactionType>
              <xsl:value-of select="ns1:TRANSACTION_TYPE"/>
            </ns7:TransactionType>
            <ns7:SubinventoryCode>
              <xsl:value-of select="ns1:SUBINVENTORY_CODE"/>
            </ns7:SubinventoryCode>
            <ns7:LocatorID>
              <xsl:value-of select="ns1:LOCATOR_ID"/>
            </ns7:LocatorID>
            <ns7:Locator>
              <xsl:value-of select="ns1:LOCATOR"/>
            </ns7:Locator>
            <ns7:LocatorStatus>
              <xsl:value-of select="ns1:LOCATOR_STATUS"/>
            </ns7:LocatorStatus>
            <ns7:ItemID>
              <xsl:value-of select="ns1:ITEM_ID"/>
            </ns7:ItemID>
            <ns7:ItemNumber>
              <xsl:value-of select="ns1:ITEM_NUMBER"/>
            </ns7:ItemNumber>
            <ns7:ItemDescription>
              <xsl:value-of select="ns1:ITEM_DESCRIPTION"/>
            </ns7:ItemDescription>
            <ns7:ItemType>
              <xsl:value-of select="ns1:ITEM_TYPE"/>
            </ns7:ItemType>
            <ns7:Revision>
              <xsl:value-of select="ns1:REVISION"/>
            </ns7:Revision>
            <ns7:PriUOMCode>
              <xsl:value-of select="ns1:PRI_UOM_CODE"/>
            </ns7:PriUOMCode>
            <ns7:TransactionDate>
              <xsl:value-of select="ns1:TRANSACTION_DATE"/>
            </ns7:TransactionDate>
            <ns7:TransactionQty>
              <xsl:value-of select="ns1:TRANSACTION_QTY"/>
            </ns7:TransactionQty>
            <ns7:TrxUOMCode>
              <xsl:value-of select="ns1:TRX_UOM_CODE"/>
            </ns7:TrxUOMCode>
            <ns7:XferOrgnID>
              <xsl:value-of select="ns1:XFER_ORGN_ID"/>
            </ns7:XferOrgnID>
            <ns7:XferOrgnCode>
              <xsl:value-of select="ns1:XFER_ORGN_CODE"/>
            </ns7:XferOrgnCode>
            <ns7:XferSubinventory>
              <xsl:value-of select="ns1:XFER_SUBINVENTORY"/>
            </ns7:XferSubinventory>
            <ns7:XferLocatorID>
              <xsl:value-of select="ns1:XFER_LOCATOR_ID"/>
            </ns7:XferLocatorID>
            <ns7:XferLocator>
              <xsl:value-of select="ns1:XFER_LOCATOR"/>
            </ns7:XferLocator>
            <ns7:TransactionReason>
              <xsl:value-of select="ns1:TRANSACTION_REASON"/>
            </ns7:TransactionReason>
            <ns7:TrxSourceCode>
              <xsl:value-of select="ns1:TRX_SOURCE_CODE"/>
            </ns7:TrxSourceCode>
            <ns7:TrxSourceName>
              <xsl:value-of select="ns1:TRX_SOURCE_NAME"/>
            </ns7:TrxSourceName>
            <ns7:LPNID>
              <xsl:value-of select="ns1:LPN_ID"/>
            </ns7:LPNID>
            <ns7:LPN>
              <xsl:value-of select="ns1:LPN"/>
            </ns7:LPN>
            <ns7:Attribute>
              <ns7:ATTRIBUTECATEGORY>
                <xsl:value-of select="ns1:ATTRIBUTE_CATEGORY"/>
              </ns7:ATTRIBUTECATEGORY>
              <ns7:ATTRIBUTE1>
                <xsl:value-of select="ns1:ATTRIBUTE1"/>
              </ns7:ATTRIBUTE1>
              <ns7:ATTRIBUTE2>
                <xsl:value-of select="ns1:ATTRIBUTE2"/>
              </ns7:ATTRIBUTE2>
              <ns7:ATTRIBUTE3>
                <xsl:value-of select="ns1:ATTRIBUTE3"/>
              </ns7:ATTRIBUTE3>
              <ns7:ATTRIBUTE4>
                <xsl:value-of select="ns1:ATTRIBUTE4"/>
              </ns7:ATTRIBUTE4>
              <ns7:ATTRIBUTE5>
                <xsl:value-of select="ns1:ATTRIBUTE5"/>
              </ns7:ATTRIBUTE5>
            </ns7:Attribute>
            <ns7:LPNAttribute>
              <ns7:ATTRIBUTE1>
                <xsl:value-of select="ns1:LPN_ATTRIBUTE1"/>
              </ns7:ATTRIBUTE1>
              <ns7:ATTRIBUTE2>
                <xsl:value-of select="ns1:LPN_ATTRIBUTE2"/>
              </ns7:ATTRIBUTE2>
              <ns7:ATTRIBUTE3>
                <xsl:value-of select="ns1:LPN_ATTRIBUTE3"/>
              </ns7:ATTRIBUTE3>
              <ns7:ATTRIBUTE4>
                <xsl:value-of select="ns1:LPN_ATTRIBUTE4"/>
              </ns7:ATTRIBUTE4>
              <ns7:ATTRIBUTE5>
                <xsl:value-of select="ns1:LPN_ATTRIBUTE5"/>
              </ns7:ATTRIBUTE5>
            </ns7:LPNAttribute>
            <ns7:ListOfInvTrxSrcDetails>
              <xsl:for-each select="ns1:TRX_SOURCE_DTLS/ns1:TRX_SOURCE_DTLS_ITEM">
                <ns7:InvTrxSrcDetails>
                  <ns7:TransactionID>
                    <xsl:value-of select="ns1:TRANSACTION_ID"/>
                  </ns7:TransactionID>
                  <ns7:TrxSourceType>
                    <xsl:value-of select="ns1:TRX_SOURCE_TYPE"/>
                  </ns7:TrxSourceType>
                  <ns7:TrxSourceNumber>
                    <xsl:value-of select="ns1:TRX_SOURCE_NUMBER"/>
                  </ns7:TrxSourceNumber>
                  <ns7:TrxSourceLine>
                    <xsl:value-of select="ns1:TRX_SOURCE_LINE"/>
                  </ns7:TrxSourceLine>
                  <ns7:TrxSourceInfo1>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO1"/>
                  </ns7:TrxSourceInfo1>
                  <ns7:TrxSourceInfo2>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO2"/>
                  </ns7:TrxSourceInfo2>
                  <ns7:TrxSourceInfo3>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO3"/>
                  </ns7:TrxSourceInfo3>
                  <ns7:TrxSourceInfo4>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO4"/>
                  </ns7:TrxSourceInfo4>
                  <ns7:TrxSourceInfo5>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO5"/>
                  </ns7:TrxSourceInfo5>
                  <ns7:TrxSourceInfo6>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO6"/>
                  </ns7:TrxSourceInfo6>
                  <ns7:TrxSourceInfo7>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO7"/>
                  </ns7:TrxSourceInfo7>
                  <ns7:TrxSourceInfo8>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO8"/>
                  </ns7:TrxSourceInfo8>
                  <ns7:TrxSourceInfo9>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO9"/>
                  </ns7:TrxSourceInfo9>
                  <ns7:TrxSourceInfo10>
                    <xsl:value-of select="ns1:TRX_SOURCE_INFO10"/>
                  </ns7:TrxSourceInfo10>
                </ns7:InvTrxSrcDetails>
              </xsl:for-each>
            </ns7:ListOfInvTrxSrcDetails>
            <ns7:ListOfInvTrxDetails>
              <xsl:for-each select="ns1:TRX_LOT_LPN_SERIAL/ns1:TRX_LOT_LPN_SERIAL_ITEM">
                <xsl:if test=".">
                  <ns7:InvTrxDetails>
                    <ns7:TransactionID>
                      <xsl:value-of select="ns1:TRANSACTION_ID"/>
                    </ns7:TransactionID>
                    <ns7:LPNID>
                      <xsl:value-of select="ns1:LPN_ID"/>
                    </ns7:LPNID>
                    <ns7:LPN>
                      <xsl:value-of select="ns1:LPN"/>
                    </ns7:LPN>
                    <ns7:PrimaryLot>
                      <xsl:value-of select="ns1:PRIMARY_LOT"/>
                    </ns7:PrimaryLot>
                    <ns7:LotNumber>
                      <xsl:value-of select="ns1:LOT_NUMBER"/>
                    </ns7:LotNumber>
                    <ns7:TrxLotQuantity>
                      <xsl:value-of select="ns1:TRX_LOT_QUANTITY"/>
                    </ns7:TrxLotQuantity>
                    <ns7:LotExpirationDate>
                      <xsl:value-of select="ns1:LOT_EXPIRATION_DATE"/>
                    </ns7:LotExpirationDate>
                    <ns7:SupplierLot>
                      <xsl:value-of select="ns1:SUPPLIER_LOT"/>
                    </ns7:SupplierLot>
                    <ns7:GradeCode>
                      <xsl:value-of select="ns1:GRADE_CODE"/>
                    </ns7:GradeCode>
                    <ns7:LotStatus>
                      <xsl:value-of select="ns1:LOT_STATUS"/>
                    </ns7:LotStatus>
                    <ns7:SerialNumber>
                      <xsl:value-of select="ns1:SERIAL_NUMBER"/>
                    </ns7:SerialNumber>
                    <ns7:UnitNumber>
                      <xsl:value-of select="ns1:UNIT_NUMBER"/>
                    </ns7:UnitNumber>
                    <ns7:SerialStatus>
                      <xsl:value-of select="ns1:SERIAL_STATUS"/>
                    </ns7:SerialStatus>
                  </ns7:InvTrxDetails>
                </xsl:if>
              </xsl:for-each>
            </ns7:ListOfInvTrxDetails>
          </ns7:ListOfInvTrx>
        </ns7:InventoryTransactionDetails>
      </xsl:for-each>
    </ns0:QueryInventoryTransactionAddRs>
  </xsl:template>
</xsl:stylesheet>
