DROP INDEX XREF_SAP_EBS_GL_CODE_U1;
DROP INDEX XREF_SAP_EBS_GL_CODE_U2;
DROP INDEX XREF_SAP_EBS_GL_CODE_U3;

DROP TABLE XREF_SAP_EBS_GL_CODE;

CREATE TABLE XREF_SAP_EBS_GL_CODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    SAP VARCHAR2(100),
    EBS VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);

CREATE INDEX XREF_SAP_EBS_GL_CODE_U1 ON XREF_SAP_EBS_GL_CODE(ROW_ID) REVERSE;
CREATE INDEX XREF_SAP_EBS_GL_CODE_U2 ON XREF_SAP_EBS_GL_CODE(SAP);
CREATE INDEX XREF_SAP_EBS_GL_CODE_U3 ON XREF_SAP_EBS_GL_CODE(EBS);