<wsdl:definitions
     name="InsertWSH_OTRIPS_STG_DBInsertAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/I027New/NUC_TripAssignment_CP_EBS_ABF/InsertWSH_OTRIPS_STG_DBInsertAdapter"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/I027New/NUC_TripAssignment_CP_EBS_ABF/InsertWSH_OTRIPS_STG_DBInsertAdapter"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertWSH_OTRIPS_STG_DBInsertAdapter"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="InsertWSH_OTRIPS_STG_DBInsertAdapter_plt" >
    <plt:role name="InsertWSH_OTRIPS_STG_DBInsertAdapter_role" >
      <plt:portType name="tns:InsertWSH_OTRIPS_STG_DBInsertAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertWSH_OTRIPS_STG_DBInsertAdapter" schemaLocation="../Schemas/InsertWSH_OTRIPS_STG_DBInsertAdapter_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="XxnucWshOtripsStgCollection_msg">
        <wsdl:part name="XxnucWshOtripsStgCollection" element="top:XxnucWshOtripsStgCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertWSH_OTRIPS_STG_DBInsertAdapter_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:XxnucWshOtripsStgCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
