<wsdl:definitions
     name="PollOMSI_DBAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/I027/NUC_TripAssignment_CP_EBS_ABF/PollOMSI_DBAdapter"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/I027/NUC_TripAssignment_CP_EBS_ABF/PollOMSI_DBAdapter"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollOMSI_DBAdapter"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollOMSI_DBAdapter_plt" >
    <plt:role name="PollOMSI_DBAdapter_role" >
      <plt:portType name="tns:PollOMSI_DBAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollOMSI_DBAdapter" schemaLocation="../Schemas/PollOMSI_DBAdapter_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="LogEntryCollection_msg">
        <wsdl:part name="LogEntryCollection" element="top:LogEntryCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollOMSI_DBAdapter_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:LogEntryCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
