<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/apps/otm"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.eia.com/AO/EBiz/P2P/InvoiceABM/1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns1="http://oracle.com/sca/soapservice/NUC_APInvoice_OTM_EBiz_ABF/NUC_APInvoice_OTM_EBiz_ABF/OTMGetAPInvoice_client"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns9="http://xmlns.eia.com/AO/EBiz/common/WhoAO/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://xmlns.eia.com/ABS/EBiz/InvoiceABS/1.0"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/P2P/OrganizationAO/1.0"
                xmlns:ns8="http://xmlns.eia.com/AO/EBiz/P2P/InvoiceAO/1.0"
                xmlns:ns10="http://xmlns.eia.com/AO/EBiz/common/AmountAO/1.0"
                xmlns:ns11="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/common/CommonAO/1.0"
                xmlns:ns5="http://xmlns.eia.com/AO/EBiz/P2P/SupplierSiteAO/1.0"
                xmlns:ns6="http://xmlns.eia.com/AO/EBiz/P2P/SupplierAO/1.0"
                xmlns:ns12="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns13="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns14="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns15="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns16="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/OTMGetAPInvoice_client.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/InvoiceABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateInvoiceRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/P2P/InvoiceABM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED NOV 18 03:16:32 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CreateInvoiceRequestMessage>
      <ns14:HeaderRq>
        <ns14:Language>ENG</ns14:Language>
        <ns14:ComponentID>I129</ns14:ComponentID>
        <ns14:ServiceName>temp</ns14:ServiceName>
        <ns14:TransactionIDREF>temp</ns14:TransactionIDREF>
        <ns14:TransactionName>APInvoices</ns14:TransactionName>
        <ns14:Source>31</ns14:Source>
        <ns14:Target>2</ns14:Target>
        <ns14:TimeStamp>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </ns14:TimeStamp>
      </ns14:HeaderRq>
      <tns:Invoice>
        <xsl:variable name="Temp_GlogDate">
          <xsl:if test="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceDate/ns0:GLogDate != '' ">
            <xsl:value-of select='concat(substring(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceDate/ns0:GLogDate,1.0,4.0),"-",substring(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceDate/ns0:GLogDate,5.0,2.0),"-",substring(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceDate/ns0:GLogDate,7.0,2.0),"T",substring(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceDate/ns0:GLogDate,9.0,2.0),":",substring(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceDate/ns0:GLogDate,11.0,2.0),":",substring(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceDate/ns0:GLogDate,13.0,2.0))'/>
          </xsl:if>
        </xsl:variable>
        <!--ns8:Gldate>
          <xsl:value-of select='$Temp_GlogDate'/>
        </ns8:Gldate-->
        <ns8:Invoiceamount>
          <xsl:value-of select="format-number(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:AmountToPay/ns0:FinancialAmount/ns0:MonetaryAmount, '#.00')"/>
        </ns8:Invoiceamount>
        <ns8:Invoicecurrencycode>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:AmountToPay/ns0:FinancialAmount/ns0:GlobalCurrencyCode"/>
        </ns8:Invoicecurrencycode>
        <ns8:Invoicedate>
          <xsl:value-of select='$Temp_GlogDate'/>
        </ns8:Invoicedate>
        <ns8:Invoiceid>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:VoucherGid/ns0:Gid/ns0:Xid"/>
        </ns8:Invoiceid>
        <ns8:Invoicenum>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:VoucherNum"/>
        </ns8:Invoicenum>
        <xsl:choose>
          <xsl:when test="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:AmountToPay/ns0:FinancialAmount/ns0:MonetaryAmount > 0">
            <ns8:Invoicetypelookupcode>STANDARD</ns8:Invoicetypelookupcode>
          </xsl:when>
          <xsl:when test="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:AmountToPay/ns0:FinancialAmount/ns0:MonetaryAmount &lt; 0">
            <ns8:Invoicetypelookupcode>CREDIT</ns8:Invoicetypelookupcode>
          </xsl:when>
        </xsl:choose>
        <xsl:for-each select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:VoucherRefnum">
          <xsl:if test="ns0:VoucherRefnumQualifierGid/ns0:Gid/ns0:Xid = 'ORGID'">
            <ns8:Orgid>
              <xsl:value-of select="ns0:VoucherRefnumValue"/>
            </ns8:Orgid>
          </xsl:if>
          <xsl:if test="ns0:VoucherRefnumQualifierGid/ns0:Gid/ns0:Xid = 'OP_UNIT'">
            <ns8:Operatingunit>
              <xsl:value-of select="ns0:VoucherRefnumValue"/>
            </ns8:Operatingunit>
          </xsl:if>
          <xsl:if test="ns0:VoucherRefnumQualifierGid/ns0:Gid/ns0:Xid = 'SUPPLIER_ID'">
            <ns8:Vendorid>
              <xsl:value-of select="ns0:VoucherRefnumValue"/>
            </ns8:Vendorid>
          </xsl:if>
          <xsl:if test="ns0:VoucherRefnumQualifierGid/ns0:Gid/ns0:Xid = 'SUPPLIER_SITE_ID'">
            <ns8:Vendorsiteid>
              <xsl:value-of select="ns0:VoucherRefnumValue"/>
            </ns8:Vendorsiteid>
          </xsl:if>
        </xsl:for-each>
        <ns8:Source>OTM</ns8:Source>
        <ns8:HeaderDFF>
          <ns7:Attribute4>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Shipment/ns0:ShipmentHeader/ns0:ShipmentGid/ns0:Gid/ns0:Xid"/>
          </ns7:Attribute4>
          <ns7:Attribute5>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceGid/ns0:Gid/ns0:Xid"/>
          </ns7:Attribute5>
          <xsl:for-each select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:VoucherRefnum">
            <xsl:if test="ns0:VoucherRefnumQualifierGid/ns0:Gid/ns0:Xid = 'MBOL_NUMBER'">
              <ns7:Attribute6>
                <xsl:value-of select="ns0:VoucherRefnumValue"/>
              </ns7:Attribute6>
            </xsl:if>
            <xsl:if test="ns0:VoucherRefnumQualifierGid/ns0:Gid/ns0:Xid = 'OP_UNIT'">
              <ns7:Attribute7>
                <xsl:value-of select="ns0:VoucherRefnumValue"/>
              </ns7:Attribute7>
            </xsl:if>
          </xsl:for-each>
          <ns7:Attribute8>
            <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:VoucherGid/ns0:Gid/ns0:Xid"/>
          </ns7:Attribute8>
        </ns8:HeaderDFF>
        <ns8:ListOfInvoiceLines>
          <xsl:for-each select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentModeDetail/ns0:GenericDetail/ns0:GenericLineItem">
            <xsl:variable name="Temp_AssignedNum">
              <xsl:value-of select="ns0:AssignedNum"/>
            </xsl:variable>
            <ns8:InvoiceLines>
              <ns8:Accountingdate>
                <xsl:value-of select="xp20:current-dateTime()"/>
              </ns8:Accountingdate>
              <xsl:for-each select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:VoucherInvoiceLineItem">
                <xsl:if test="ns0:AssignedNum = $Temp_AssignedNum">
                  <ns8:Amount>
                    <!--xsl:value-of select="format-number (ns0:AmountToPay/ns0:FinancialAmount/ns0:MonetaryAmount, &quot;#.00&quot; )"/-->
                    <xsl:value-of select="format-number(ns0:AmountToPay/ns0:FinancialAmount/ns0:MonetaryAmount, '#.00')"/>
                  </ns8:Amount>
                </xsl:if>
              </xsl:for-each>
              <ns8:Description>
                <xsl:value-of select="ns0:CommonInvoiceLineElements/ns0:Commodity/ns0:Description"/>
              </ns8:Description>
              <ns8:Distcodeconcatenated>
                <xsl:value-of select="ns0:CommonInvoiceLineElements/ns0:GeneralLedgerGid/ns0:Gid/ns0:Xid"/>
              </ns8:Distcodeconcatenated>
              <ns8:Invoiceid>
                <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:VoucherGid/ns0:Gid/ns0:Xid"/>
              </ns8:Invoiceid>
              <ns8:Invoicelineid>
                <xsl:value-of select="concat(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:Payment/ns0:PaymentHeader/ns0:InvoiceGid/ns0:Gid/ns0:Xid,'-',ns0:AssignedNum)"/>
              </ns8:Invoicelineid>
              <ns8:Linenumber>
                <xsl:value-of select='$Temp_AssignedNum'/>
              </ns8:Linenumber>
              <ns8:Linetypelookupcode>FREIGHT</ns8:Linetypelookupcode>
              <xsl:for-each select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:Voucher/ns0:VoucherRefnum">
                <xsl:if test="ns0:VoucherRefnumQualifierGid/ns0:Gid/ns0:Xid = 'ORGID'">
                  <ns8:Orgid>
                    <xsl:value-of select="ns0:VoucherRefnumValue"/>
                  </ns8:Orgid>
                </xsl:if>
              </xsl:for-each>
              <ns8:LineDFF>
                <ns7:Attribute1>
                  <xsl:value-of select="ns0:CommonInvoiceLineElements/ns0:FreightRate/ns0:SpecialCharge/ns0:SpecialChargeCode"/>
                </ns7:Attribute1>
              </ns8:LineDFF>
            </ns8:InvoiceLines>
          </xsl:for-each>
        </ns8:ListOfInvoiceLines>
      </tns:Invoice>
    </tns:CreateInvoiceRequestMessage>
  </xsl:template>
</xsl:stylesheet>
