<?binding.jca DB_QueryPOReceiptSummary_db.jca?>
<wsdl:definitions name="DB_QueryPOReceiptSummary" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Nucor/NUC_EBizPOReceipt_ABS/DB_QueryPOReceiptSummary" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DB_QueryPOReceiptSummary" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Nucor/NUC_EBizPOReceipt_ABS/DB_QueryPOReceiptSummary" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="DB_QueryPOReceiptSummary_plt">
        <plt:role name="DB_QueryPOReceiptSummary_role">
            <plt:portType name="tns:DB_QueryPOReceiptSummary_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_QueryPOReceiptSummary" schemaLocation="xsd/DB_QueryPOReceiptSummary.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DB_QueryPOReceiptSummaryInput_msg">
        <wsdl:part name="DB_QueryPOReceiptSummaryInput_msg" element="db:DB_QueryPOReceiptSummaryInput"/>
    </wsdl:message>
    <wsdl:message name="DB_QueryPOReceiptSummaryOutputCollection_msg">
        <wsdl:part name="DB_QueryPOReceiptSummaryOutputCollection" element="db:DB_QueryPOReceiptSummaryOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_QueryPOReceiptSummary_ptt">
        <wsdl:operation name="DB_QueryPOReceiptSummary">
            <wsdl:input message="tns:DB_QueryPOReceiptSummaryInput_msg"/>
            <wsdl:output message="tns:DB_QueryPOReceiptSummaryOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
