CREATE TABLE L2_GME_BATCH_DETAILS
   (
	process_batch_id						NUMBER,
	material_detail_id 						NUMBER,
    batch_id 								NUMBER,
    formula_line_id 						NUMBER,
    line_no 								VARCHAR2 (5),
    item_no 								VARCHAR2 (40),
    line_type 								NUMBER,
    plan_qty 								NUMBER,
    item_um 								VARCHAR2 (4),
    item_um2 								VARCHAR2 (4),
    actual_qty 								NUMBER,
    release_type 							NUMBER,
    scrap_factor 							NUMBER,
    scale_type 								NUMBER,
    phantom_type 							NUMBER,
    cost_alloc 								NUMBER,
    alloc_ind 								NUMBER,
    cost 									NUMBER,
    text_code 								NUMBER,
    phantom_id 								NUMBER,
    rounding_direction 						NUMBER,
    scale_rounding_variance 				NUMBER,
    scale_multiple 							NUMBER,
    contribute_yield_ind 					VARCHAR2 (1),
    contribute_step_qty 					VARCHAR2 (1),
    wip_plan_qty 							NUMBER,
    original_qty 							NUMBER,
    by_product_type 						VARCHAR2 (1),
    backordered_qty 						NUMBER,
    dispense_ind 							VARCHAR2 (1),
    dtl_um 									VARCHAR2 (3),
    inventory_item_id 						NUMBER,
    locator_id 								NUMBER,
    material_requirement_date 				DATE,
    move_order_line_id 						NUMBER,
    organization_id 						NUMBER,
    original_primary_qty 					NUMBER,
    phantom_line_id 						NUMBER,
    revision 								VARCHAR2 (3),
    subinventory 							VARCHAR2 (10),
    attribute_category 						VARCHAR2 (240),
    attribute1 								VARCHAR2 (240),
    attribute2 								VARCHAR2 (240),
    attribute3 								VARCHAR2 (240),
    attribute4 								VARCHAR2 (240),
    attribute5 								VARCHAR2 (240),
    attribute6 								VARCHAR2 (240),
    attribute7 								VARCHAR2 (240),
    attribute8 								VARCHAR2 (240),
    attribute9 								VARCHAR2 (240),
    attribute10 							VARCHAR2 (240),
    attribute11 							VARCHAR2 (240),
    attribute12 							VARCHAR2 (240),
    attribute13 							VARCHAR2 (240),
    attribute14 							VARCHAR2 (240),
    attribute15 							VARCHAR2 (240),
    creation_date 							DATE,
    created_by 								NUMBER,
    last_update_date 						DATE,
    last_updated_by 						NUMBER,
	is_read									VARCHAR2(2)
	);