CREATE TABLE L2_GME_BATCH_HEADER
   (
	process_batch_id					NUMBER,
	organization_code 					VARCHAR2 (3),
    batch_id 							NUMBER,
    plant_code 							VARCHAR2 (4),
    batch_no 							VARCHAR2 (32),
    batch_type 							NUMBER,
    recipe_no 							NUMBER,
    recipe_version 						NUMBER,
    plan_start_date 					DATE,
    plan_cmplt_date 					DATE,
    due_date 							DATE,
    batch_status 						VARCHAR2 (80),
    parent_batch 						VARCHAR2 (32),
    actual_start_date 					DATE,
    actual_completion_date 				DATE,
    batch_close_date 					DATE,
    update_inventory 					VARCHAR2 (1),
    formula_number 						VARCHAR2 (32),
    formula_version 					NUMBER,
    routing_number 						VARCHAR2 (32),
    routing_version 					NUMBER,
    recipe 								VARCHAR2 (240),
    formula_description 				VARCHAR2 (240),
    routing_description 				VARCHAR2 (240),
    fpo_id 								NUMBER,
    enforce_step_dependency 			NUMBER,
    automatic_step_calculation 			NUMBER,
	order_number						NUMBER,
	order_line_num						NUMBER,
    attribute_category 					VARCHAR2 (240),
    attribute1 							VARCHAR2 (240),
    attribute2 							VARCHAR2 (240),
    attribute3 							VARCHAR2 (240),
    attribute4 							VARCHAR2 (240),
    attribute5 							VARCHAR2 (240),
    attribute6 							VARCHAR2 (240),
    attribute7 							VARCHAR2 (240),
    attribute8 							VARCHAR2 (240),
    attribute9 							VARCHAR2 (240),
    attribute10 						VARCHAR2 (240),
    attribute11 						VARCHAR2 (240),
    attribute12 						VARCHAR2 (240),
    attribute13 						VARCHAR2 (240),
    attribute14 						VARCHAR2 (240),
    attribute15 						VARCHAR2 (240),
    creation_date 						DATE,
    created_by 							NUMBER,
    last_update_date 					DATE,
    last_updated_by 					NUMBER,
	is_read								VARCHAR2(2),
	CONSTRAINT L2_GME_BATCH_HEADER_PK PRIMARY KEY (process_batch_id,batch_id)
	);