CREATE TABLE L2_GME_BATCH_STEPS
   (
	process_batch_id				NUMBER,
	batchstep_id 					NUMBER,
    batch_id 						NUMBER,
    routingstep_id 					NUMBER,
    batchstep_no 					NUMBER,
    oprn_id 						NUMBER,
    plan_step_qty 					NUMBER,
    actual_step_qty 				NUMBER,
    step_qty_uom 					VARCHAR2(4),
    plan_start_date 				DATE,
    actual_start_date 				DATE,
    due_date 						DATE,
    plan_cmplt_date 				DATE,
    actual_cmplt_date 				DATE,
    step_close_date 				DATE,
    step_status 					NUMBER,
    delete_mark 					NUMBER,
    steprelease_type 				NUMBER,
    max_step_capacity 				NUMBER,
    max_step_capacity_uom 			VARCHAR2 (4),
    plan_charges 					NUMBER,
    actual_charges 					NUMBER,
    text_code 						NUMBER,
    quality_status 					NUMBER,
    minimum_transfer_qty 			NUMBER,
    max_step_capacity_um 			VARCHAR2 (3),
    step_qty_um 					VARCHAR2 (3),
	activity 						VARCHAR2 (16),
	resources 						VARCHAR2 (16),
    resource_desc 					VARCHAR2 (240),
    res_plan_start_date 			DATE,
    res_plan_cmplt_date 			DATE,
    attribute_category 				VARCHAR2 (240),
    attribute1 						VARCHAR2 (240),
    attribute2 						VARCHAR2 (240),
    attribute3 						VARCHAR2 (240),
    attribute4 						VARCHAR2 (240),
    attribute5 						VARCHAR2 (240),
    attribute6 						VARCHAR2 (240),
    attribute7 						VARCHAR2 (240),
    attribute8 						VARCHAR2 (240),
    attribute9 						VARCHAR2 (240),
    attribute10 					VARCHAR2 (240),
    attribute11 					VARCHAR2 (240),
    attribute12 					VARCHAR2 (240),
    attribute13 					VARCHAR2 (240),
    attribute14 					VARCHAR2 (240),
    attribute15 					VARCHAR2 (240),
    creation_date 					DATE,
    created_by 						NUMBER,
    last_update_date 				DATE,
    last_updated_by 				NUMBER,
	is_read							VARCHAR2(2)
	);