<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:eia="http://xmlns.eia.com/extensions/1.0"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:tns="www.Nucor.com"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/A2R/JournalAO/1.0"
                xmlns:ns0="http://xmlns.eia.com/ABS/EBiz/A2R/JournalABS/1.0"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:jeam="http://xmlns.eia.com/AO/EBiz/A2R/JournalAM/1.0"
                xmlns:utl="http://www.oracle.com/XSL/Transform/java/com.eia.soa.util.Configuration"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns2="http://xmlns.eia.com/AO/EBiz/common/OperationResultAO/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl bpel tns wsdl ns1 plnk xsd ns4 ns0 soap12 soap jeam mime ns2 ns3 bpws xp20 eia bpel bpm utl ora socket mhdr oraext dvm hwf med ids xdk xref ldap"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns9="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../NucorSAPDataWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Envelope" namespace=""/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/A2R/JournalABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateListOfJournalsRequestMessage"
                                       namespace="http://xmlns.eia.com/AO/EBiz/A2R/JournalAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED OCT 14 10:28:39 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <jeam:CreateListOfJournalsRequestMessage>
      <xsl:variable name="ledgername"
                    select='dvm:lookupValue("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_LEGACY_LEDGER_NAME_MAP.dvm","LEGACY_DIV_NUM",/Envelope/@DivCode,"EBS_LEDGER_NAME","")'/>
      <xsl:variable name="bookid"
                    select="oraext:query-database(concat(&quot;Select set_of_books_id from gl_sets_of_books where name='&quot;,$ledgername,&quot;'&quot;),false(),false(),&quot;jdbc/ebsapps&quot;)"/>
      <xsl:variable name="varGLGroupId" select='oraext:sequence-next-val ("gl_journal_import_s", "jdbc/ebsapps" )'/>
      <ns9:HeaderRq>
        <ns9:TransactionRequestID>''</ns9:TransactionRequestID>
        <ns9:ComponentID>''</ns9:ComponentID>
        <ns9:TransactionName>''</ns9:TransactionName>
        <ns9:Source>''</ns9:Source>
        <ns9:Target>''</ns9:Target>
      </ns9:HeaderRq>
      <jeam:AppsContext>
        <ns3:UserName>
          <xsl:value-of select='dvm:lookupValue("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_USER_NAME_DIVISION_MAP.dvm","DIV_CODE",/Envelope/@DivCode,"EBS_USER_NAME","SOAUSER")'/>
        </ns3:UserName>
        <ns3:ResponsibilityName>
          <xsl:value-of select='dvm:lookupValue("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_ORG_RESP_NAME.dvm","DIV_CODE",/Envelope/@DivCode,"EBS_RESP_NAME","General Ledger Super User","EBS_FUNCTION_AREA","JOURNALS")'/>
        </ns3:ResponsibilityName>
        <ns3:OrganizationName>
          <xsl:value-of select='dvm:lookupValue("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_ORG_RESP_NAME.dvm","DIV_CODE",/Envelope/@DivCode,"EBS_ORG_NAME","","EBS_FUNCTION_AREA","JOURNALS")'/>
        </ns3:OrganizationName>
      </jeam:AppsContext>
      <jeam:Journal>
        <xsl:for-each select="/Envelope/PostingSet/Posting">
          <!--xsl:choose>
            <xsl:when test='@CostCenter = ""'>
              <xsl:variable name="EBSSegment"
                            select='xref:lookupXRef(dvm:lookupValue("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_LEGACY_LEDGER_NAME_MAP.dvm","LEGACY_DIV_NUM",../../@DivCode,"NATURAL_SEGMENT_XREF_NAME",""),"SAP",concat(@GL,"-",../@CompanyCode,"-",../../@DivCode),"EBS",false())'/>
              <EBSSegment/>
            </xsl:when>
            <xsl:otherwise>
              <xsl:variable name="EBSSegment"
                            select='xref:lookupXRef(dvm:lookupValue("oramds:/apps/EIAMetadata/CommonArtifacts/dvm/EBS_LEGACY_LEDGER_NAME_MAP.dvm","LEGACY_DIV_NUM",../../@DivCode,"NATURAL_SEGMENT_XREF_NAME",""),"SAP",concat(@GL,"-",@CostCenter),"EBS",false())'/>
              <EBSSegment/>
            </xsl:otherwise>
          </xsl:choose-->
          <ns4:Journal>
            <ns4:Status>NEW</ns4:Status>
            <ns4:CodeCombinationIDInterim/>
            <ns4:SetOfBooksId>
              <xsl:value-of select="$bookid"/>
            </ns4:SetOfBooksId>
            <ns4:GroupId>
              <!--xsl:value-of select='concat ("PayrollPost_Div-", ../../@DivCode )'/-->
              <xsl:value-of select='$varGLGroupId'/>
            </ns4:GroupId>
            <xsl:choose>
              <xsl:when test='@CostCenter = ""'>
                <ns4:Reference10>
                  <xsl:value-of select='concat (@GL, "-", ../@CompanyCode, "-", ../../@DivCode )'/>
                </ns4:Reference10>
              </xsl:when>
              <xsl:otherwise>
                <ns4:Reference10>
                  <xsl:value-of select='concat(@GL,"-",@CostCenter,"-",@Desc)'/>
                </ns4:Reference10>
              </xsl:otherwise>
            </xsl:choose>
            <ns4:Reference5>
              <xsl:value-of select="../@PostingDate"/>
            </ns4:Reference5>
            <ns4:Reference4>
              <xsl:value-of select='concat("RunID-",../@RunID," Company-",../@CompanyCode," Div-",../../@DivCode)'/>
            </ns4:Reference4>
            <ns4:EnteredCR>
              <xsl:value-of select="xp20:abs(@CreditAmount)"/>
            </ns4:EnteredCR>
            <ns4:EnteredDR>
              <xsl:value-of select="xp20:abs(@DebitAmount)"/>
            </ns4:EnteredDR>
            <ns4:Segment7>0000</ns4:Segment7>
            <ns4:Segment6>0000</ns4:Segment6>
            <ns4:Segment5>0000</ns4:Segment5>
            <xsl:choose>
              <xsl:when test='@CostCenter = ""'>
                <ns4:Segment4>
                  <xsl:value-of select='substring(xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_GL_CODE.xref","SAP",concat(@GL,"-",../@CompanyCode,"-",../../@DivCode),"EBS",false()),13.0,6.0)'/>
                </ns4:Segment4>
              </xsl:when>
              <xsl:otherwise>
                <ns4:Segment4>
                  <xsl:value-of select='substring(xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_GL_CODE.xref","SAP",concat(@GL,"-",@CostCenter),"EBS",false()),13.0,6.0)'/>
                </ns4:Segment4>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test='@CostCenter = ""'>
                <ns4:Segment3>
                  <xsl:value-of select='substring(xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_GL_CODE.xref","SAP",concat(@GL,"-",../@CompanyCode,"-",../../@DivCode),"EBS",false()),9.0,3.0)'/>
                </ns4:Segment3>
              </xsl:when>
              <xsl:otherwise>
                <ns4:Segment3>
                  <xsl:value-of select='substring(xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_GL_CODE.xref","SAP",concat(@GL,"-",@CostCenter),"EBS",false()),9.0,3.0)'/>
                </ns4:Segment3>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test='@CostCenter = ""'>
                <ns4:Segment2>
                  <xsl:value-of select='substring(xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_GL_CODE.xref","SAP",concat(@GL,"-",../@CompanyCode,"-",../../@DivCode),"EBS",false()),6.0,2.0)'/>
                </ns4:Segment2>
              </xsl:when>
              <xsl:otherwise>
                <ns4:Segment2>
                  <xsl:value-of select='substring(xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_GL_CODE.xref","SAP",concat(@GL,"-",@CostCenter),"EBS",false()),6.0,2.0)'/>
                </ns4:Segment2>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test='@CostCenter = ""'>
                <ns4:Segment1>
                  <xsl:value-of select='substring(xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_GL_CODE.xref","SAP",concat(@GL,"-",../@CompanyCode,"-",../../@DivCode),"EBS",false()),1.0,4.0)'/>
                </ns4:Segment1>
              </xsl:when>
              <xsl:otherwise>
                <ns4:Segment1>
                  <xsl:value-of select='substring(xref:lookupXRef("oramds:/apps/EIAMetadata/CommonArtifacts/xref/SAP_EBS_GL_CODE.xref","SAP",concat(@GL,"-",@CostCenter),"EBS",false()),1.0,4.0)'/>
                </ns4:Segment1>
              </xsl:otherwise>
            </xsl:choose>
            <ns4:UserJESourceName>
              <xsl:value-of select='utl:getServiceProperty("NUC_EBiz_SAP_GLJE_ABF","DEFAULT_USER_JE_SOURCE_NAME")'/>
            </ns4:UserJESourceName>
            <ns4:UserJECategoryName>
              <xsl:value-of select='utl:getServiceProperty("NUC_EBiz_SAP_GLJE_ABF","DEFAULT_USER_JE_CATEGORY_NAME")'/>
            </ns4:UserJECategoryName>
            <ns4:ActualFlag>A</ns4:ActualFlag>
            <ns4:CreatedBy>1986</ns4:CreatedBy>
            <ns4:DateCreated>
              <xsl:value-of select="xp20:current-date()"/>
            </ns4:DateCreated>
            <ns4:CurrencyCode>
              <xsl:value-of select='utl:getServiceProperty("NUC_EBiz_SAP_GLJE_ABF","DEFAULT_CURRENCY_CODE")'/>
            </ns4:CurrencyCode>
            <ns4:AccountingDate>
              <xsl:value-of select="../@PostingDate"/>
            </ns4:AccountingDate>
            <ns4:LedgerId>
              <xsl:value-of select="$bookid"/>
            </ns4:LedgerId>
          </ns4:Journal>
        </xsl:for-each>
      </jeam:Journal>
    </jeam:CreateListOfJournalsRequestMessage>
  </xsl:template>
</xsl:stylesheet>