<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_GetOnHandQuantity"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://xmlns.eia.com/AO/Ebiz/D2S/OnHandQuantityAM/1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns1="http://oracle.com/sca/soapservice/NextGen/NUC_EbizOnHandQuantity_ABS/EbizOnHandQuantity_ABS"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:ns6="http://xmlns.eia.com/AO/Ebiz/D2S/OnHandQuantityAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns7="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns8="http://xmlns.oracle.com/pcbpel/adapter/db/Nucor_ABF/NUC_EBizOnHandQuantity_ABS/DB_Proc_GetOnHandQuantity"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/OnHandQuantity.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryOnHandQuantityReq"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/OnHandQuantityAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Proc_GetOnHandQuantity.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_GetOnHandQuantity"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUL 31 16:33:28 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:InputParameters>
      <tns:P_ORGANIZATION_CODE>
        <xsl:value-of select="/ns0:QueryOnHandQuantityReq/ns6:OnHandQuantityDetails/ns6:OrganizationCode"/>
      </tns:P_ORGANIZATION_CODE>
      <tns:P_USER_ITEM_TYPE>
        <xsl:value-of select="/ns0:QueryOnHandQuantityReq/ns6:OnHandQuantityDetails/ns6:UserItemType"/>
      </tns:P_USER_ITEM_TYPE>
      <tns:P_ITEM_NUMBER>
        <xsl:value-of select="/ns0:QueryOnHandQuantityReq/ns6:OnHandQuantityDetails/ns6:Item"/>
      </tns:P_ITEM_NUMBER>
      <tns:P_LOCATOR>
        <xsl:value-of select="/ns0:QueryOnHandQuantityReq/ns6:OnHandQuantityDetails/ns6:Locator"/>
      </tns:P_LOCATOR>
      <tns:P_LPN>
        <xsl:value-of select="/ns0:QueryOnHandQuantityReq/ns6:OnHandQuantityDetails/ns6:LPN"/>
      </tns:P_LPN>
      <tns:P_LOT_NUMBER>
        <xsl:value-of select="/ns0:QueryOnHandQuantityReq/ns6:OnHandQuantityDetails/ns6:LotNumber"/>
      </tns:P_LOT_NUMBER>
      <tns:P_SHOW_RESERVED>
        <xsl:value-of select="/ns0:QueryOnHandQuantityReq/ns6:OnHandQuantityDetails/ns6:ShowReserved"/>
      </tns:P_SHOW_RESERVED>
    </tns:InputParameters>
  </xsl:template>
</xsl:stylesheet>
