<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_GetOnHandQuantity"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://xmlns.eia.com/AO/Ebiz/D2S/OnHandQuantityAM/1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/Nucor_ABF/NUC_EBizOnHandQuantity_ABS/DB_Proc_GetOnHandQuantity"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns7="http://xmlns.eia.com/AO/Ebiz/D2S/OnHandQuantityAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns2="http://oracle.com/sca/soapservice/NextGen/NUC_EbizOnHandQuantity_ABS/EbizOnHandQuantity_ABS"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns4="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DB_Proc_GetOnHandQuantity.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_Proc_GetOnHandQuantity"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/D2S/OnHandQuantity.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryOnHandQuantityRes"
                                       namespace="http://xmlns.eia.com/AO/Ebiz/D2S/OnHandQuantityAM/1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUL 31 16:35:34 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:QueryOnHandQuantityRes>
      <ns7:OnHandQuantityResponse>
        <xsl:for-each select="/ns0:OutputParameters/ns0:X_ITEM_ONHAND_DET_TYPE/ns0:X_ITEM_ONHAND_DET_TYPE_ITEM">
          <ns7:OnHandQuantityResult>
            <ns7:ItemType>
              <xsl:value-of select="ns0:X_ITEM_TYPE"/>
            </ns7:ItemType>
            <ns7:Item>
              <xsl:value-of select="ns0:X_ITEM_NO"/>
            </ns7:Item>
            <ns7:ItemDescription>
              <xsl:value-of select="ns0:X_ITEM_DESCRIPTION"/>
            </ns7:ItemDescription>
            <ns7:PrimaryQuantity>
              <xsl:value-of select="ns0:X_PRIMARY_QUANTITY"/>
            </ns7:PrimaryQuantity>
            <ns7:PrimaryUOM>
              <xsl:value-of select="ns0:X_PRIMARY_UOM"/>
            </ns7:PrimaryUOM>
            <ns7:AvailableToTransact>
              <xsl:value-of select="ns0:X_AVAILABLE_TO_TRANSACT"/>
            </ns7:AvailableToTransact>
            <ns7:AvailableToReserve>
              <xsl:value-of select="ns0:X_AVAILABLE_TO_RESERVE"/>
            </ns7:AvailableToReserve>
            <ns7:SecondaryQuantity>
              <xsl:value-of select="ns0:X_SECONDARY_QUANTITY"/>
            </ns7:SecondaryQuantity>
            <ns7:SecondaryUOM>
              <xsl:value-of select="ns0:X_SECONDARY_UOM"/>
            </ns7:SecondaryUOM>
            <ns7:LPN>
              <xsl:value-of select="ns0:X_LPN"/>
            </ns7:LPN>
            <ns7:LotNumber>
              <xsl:value-of select="ns0:X_LOT"/>
            </ns7:LotNumber>
            <ns7:Locator>
              <xsl:value-of select="ns0:X_LOCATOR"/>
            </ns7:Locator>
            <ns7:OrganizationCode>
              <xsl:value-of select="ns0:X_ORGANIZATIONCODE"/>
            </ns7:OrganizationCode>
          </ns7:OnHandQuantityResult>
        </xsl:for-each>
        <ns7:ErrorMsg>
          <xsl:value-of select="/ns0:OutputParameters/ns0:P_ERR_MSG"/>
        </ns7:ErrorMsg>
        <ns7:ErrorStatus>
          <xsl:value-of select="/ns0:OutputParameters/ns0:P_ERR_FLAG"/>
        </ns7:ErrorStatus>
      </ns7:OnHandQuantityResponse>
    </tns:QueryOnHandQuantityRes>
  </xsl:template>
</xsl:stylesheet>
