USE [Requisition]
GO

/****** Object:  Table [dbo].[XXNUC_SUPPLIERS_IN]    Script Date: 5/7/2014 9:32:17 PM ******/
DROP TABLE [dbo].[XXNUC_SUPPLIERS_IN]
GO

/****** Object:  Table [dbo].[XXNUC_SUPPLIERS_IN]    Script Date: 5/7/2014 9:32:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XXNUC_SUPPLIERS_IN](
	[SUPPLIER_IN_KEY] [bigint] IDENTITY(1,1) NOT NULL,
	[PAY_SITE_FLAG] [nvarchar](100) NULL,
	[PURCHASING_SITE_FLAG] [nvarchar](100) NULL,
	[EMAIL_ADDRESS] [nvarchar](100) NULL,
	[FAX_NUMBER] [nvarchar](100) NULL,
	[FAX_AREA_CODE] [nvarchar](100) NULL,
	[PHONE_NUMBER] [nvarchar](100) NULL,
	[PHONE_AREA_CODE] [nvarchar](100) NULL,
	[ACTIVE] [nvarchar](100) NULL,
	[ADDRESS_NAME] [nvarchar](300) NULL,
	[COUNTRY] [nvarchar](100) NULL,
	[COUNTY] [nvarchar](100) NULL,
	[POSTAL_CODE] [nvarchar](100) NULL,
	[STATE] [nvarchar](100) NULL,
	[CITY] [nvarchar](100) NULL,
	[ADDRESS_LINE4] [nvarchar](300) NULL,
	[ADDRESS_LINE3] [nvarchar](300) NULL,
	[ADDRESS_LINE2] [nvarchar](300) NULL,
	[ADDRESS_LINE1] [nvarchar](300) NULL,
	[SHIP_TO_ADDRESS] [nvarchar](200) NULL,
	[CONFIRMATION_REQUIRED] [nvarchar](100) NULL,
	[BANK_NUMBER] [nvarchar](100) NULL,
	[CREDIT_LIMIT] [nvarchar](100) NULL,
	[VENDOR_SORT_NAME] [nvarchar](300) NULL,
	[TAX_CLASSIFICATION] [nvarchar](100) NULL,
	[FREIGHT_TERMS] [nvarchar](100) NULL,
	[RMA_REQUIRED] [nvarchar](100) NULL,
	[TERMS_NAME] [nvarchar](100) NULL,
	[SINGLE_INVOICE_PROCESSOR] [nvarchar](100) NULL,
	[SUPPLIER_GROUP] [nvarchar](100) NULL,
	[SUPPLIER_TYPE] [nvarchar](100) NULL,
	[TAXPAYER_ID] [nvarchar](100) NULL,
	[EMPLOYEES_TOTAL] [nvarchar](100) NULL,
	[INCORP_YEAR] [nvarchar](100) NULL,
	[YEAR_ESTABLISHED] [nvarchar](100) NULL,
	[DUNS_NUMBER] [nvarchar](100) NULL,
	[URL] [nvarchar](100) NULL,
	[END_DATE_ACTIVE] [nvarchar](100) NULL,
	[SIC_CODE] [nvarchar](100) NULL,
	[VENDOR_NUMBER] [nvarchar](100) NULL,
	[VENDOR_NAME] [nvarchar](100) NULL,
	[OPERATING_UNIT] [nvarchar](100) NULL,
	[ACTION] [nvarchar](100) NULL,
	[STATUS] [nvarchar](100) NULL,
	[PARTY_ID] [nvarchar](100) NULL,
	[ADDRESS_NUMBER] [nvarchar](100) NULL,
	[TAX_REPORTING_NAME] [nvarchar](100) NULL,
	[PAYMENT_METHOD] [nvarchar](100) NULL,
	[INVOICE_CURRENCY_CODE] [nvarchar](100) NULL,
	[EXCLUDE_FREIGHT_FROM_DISCOUNT] [nvarchar](100) NULL,
	[TYPE_1099] [nvarchar](100) NULL,
	[VENDOR_1099_FLAG] [nvarchar](100) NULL,
	[MINORITY_GROUP_CODE] [nvarchar](100) NULL,
	[SHIP_VIA] [nvarchar](100) NULL,
	[HOLD_PAYMENT] [nvarchar](100) NULL,
	[AP_CLERK] [nvarchar](100) NULL,
	[FOB_LOOKUP_CODE] [nvarchar](100) NULL,
	[STOP_PAYMENT] [nvarchar](100) NULL,
	[STATE_TAX_ID] [nvarchar](100) NULL,
	[RECEPIENT] [nvarchar](100) NULL,
	[NOTES] [nvarchar](100) NULL,
	[NOTIFICATION_METHOD] [nvarchar](100) NULL,
	[P_CARD_SITE_FLAG] [nvarchar](100) NULL,
	[INSURANCE] [nvarchar](1) NULL,
	[INSURANCE_DATE] [date] NULL,
	[CONTRACT] [nvarchar](1) NULL,
	[CONTRACT_DATE] [date] NULL,
	[SAFETY] [nvarchar](1) NULL,
	[SAFETY_DATE] [date] NULL,
	[STIPULATION] [nvarchar](1) NULL,
	[DOC_DIST] [nvarchar](1) NULL,
	[MARKETABLE] [nvarchar](1) NULL,
	[APPT_REQD] [nvarchar](1) NULL,
	[CERTIFICATION_NUMBER] [nvarchar](20) NULL,
	[ITEM_CLASS] [nvarchar](4) NULL,
	[QUESTIONNAIRE_ONLY] [nvarchar](1) NULL,
	[REF_SUPPLIER_SITE_ID] [nvarchar](100) NULL,
	[REF_SUPPLIER_ID] [nvarchar](100) NULL,
	[REF_PARTY_ID] [nvarchar](100) NULL,
	[REF_PARTY_SITE_ID] [nvarchar](100) NULL,
	[REF_LOCATION_ID] [nvarchar](100) NULL,
	[CREATION_DATE] [date] NULL,
	[LAST_UPDATE_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](240) NULL,
	[LAST_UPDATED_BY] [nvarchar](240) NULL,
	[PROCESS_DATE] [nvarchar](100) NULL,
	[PROCESS_STATUS] [nvarchar](100) NULL,
	[ERROR_MSG] [nvarchar](2000) NULL,
	[REQUEST_ID] [nvarchar](100) NULL,
	[ATTRIBUTE_CATEGORY] [nvarchar](30) NULL,
	[ATTRIBUTE1] [nvarchar](150) NULL,
	[ATTRIBUTE2] [nvarchar](150) NULL,
	[ATTRIBUTE3] [nvarchar](150) NULL,
	[ATTRIBUTE4] [nvarchar](150) NULL,
	[ATTRIBUTE5] [nvarchar](150) NULL,
	[ATTRIBUTE6] [nvarchar](150) NULL,
	[ATTRIBUTE7] [nvarchar](150) NULL,
	[ATTRIBUTE8] [nvarchar](150) NULL,
	[ATTRIBUTE9] [nvarchar](150) NULL,
	[ATTRIBUTE10] [nvarchar](150) NULL,
	[ATTRIBUTE11] [nvarchar](150) NULL,
	[ATTRIBUTE12] [nvarchar](150) NULL,
	[ATTRIBUTE13] [nvarchar](150) NULL,
	[ATTRIBUTE14] [nvarchar](150) NULL,
	[ATTRIBUTE15] [nvarchar](150) NULL,
 CONSTRAINT [PK_XXNUC_SUPPLIERS_IN] PRIMARY KEY CLUSTERED 
(
	[SUPPLIER_IN_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


