<wsdl:definitions
     name="DB_Select_Trips"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/I027New/NUC_PublisherEBSTrips_ABS/DB_Select_Trips"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/I027New/NUC_PublisherEBSTrips_ABS/DB_Select_Trips"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Select_Trips"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Select_Trips_plt" >
    <plt:role name="DB_Select_Trips_role" >
      <plt:portType name="tns:DB_Select_Trips_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Select_Trips" schemaLocation="../Schemas/DB_Select_Trips_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_Select_TripsSelect_inputParameters">
        <wsdl:part name="DB_Select_TripsSelect_inputParameters" element="top:DB_Select_TripsSelect_recordIdentifierInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxnucWshTripsStgCollection_msg">
        <wsdl:part name="XxnucWshTripsStgCollection" element="top:XxnucWshTripsStgCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Select_Trips_ptt">
        <wsdl:operation name="DB_Select_TripsSelect">
            <wsdl:input message="tns:DB_Select_TripsSelect_inputParameters"/>
            <wsdl:output message="tns:XxnucWshTripsStgCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
