<wsdl:definitions name="Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter"
                  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/I028/NUC_PublisherEBSTrips_ABS/Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter"
                  xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/I028/NUC_PublisherEBSTrips_ABS/Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter"
                  xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                  xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/Update_XXNUC_WSH_TRIPS_STG_PureSQLDBAdapter"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter_plt">
    <plt:role name="Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter_role">
      <plt:portType name="tns:Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Update_XXNUC_WSH_TRIPS_STG_PureSQLDBAdapter"
              schemaLocation="../Schemas/Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapterInput_msg">
    <wsdl:part name="Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapterInput_msg"
               element="db:Update_XXNUC_WSH_TRIPS_STG_PureSQLDBAdapterInput"/>
  </wsdl:message>
  <wsdl:portType name="Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter_ptt">
    <wsdl:operation name="Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapter">
      <wsdl:input message="tns:Update_XXNUC_WSH_TRIPS_TBL_PureSQLDBAdapterInput_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
