<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="DJJGetPurchaseOrder_ep"
     targetNamespace="http://xmlns.eia.com/ABF/NUC_PurchaseOrder_DJJ_EBiz_ABF/v1_0"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.eia.com/ABF/NUC_PurchaseOrder_DJJ_EBiz_ABF/v1_0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="DJJGetPurchaseOrder_ep">
        <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.eia.com/ABF/NUC_PurchaseOrder_DJJ_EBiz_ABF/v1_0" location="DJJGetPurchaseOrder_ep.wsdl"/>
</wsdl:definitions>
