<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_LotCreation"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.eia.com/AM/EBiz/P2P/LotAM/1.0"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/P2P/LotAO/1.0"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABS/NUC_EBizLot_ABS/EBizLotABS/1.0"
                xmlns:core="http://xmlns.eia.com/EO/Common/1.0"
                xmlns:ns8="http://xmlns.oracle.com/pcbpel/adapter/apps/I109byManish/NUC_EBizLot_ABS/EBS_LotCreation"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/LotABS.wsdl"/>
                <oracle-xsl-mapper:rootElement name="CreateLotRequest"
                                               namespace="http://xmlns.eia.com/AM/EBiz/P2P/LotAM/1.0"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/EBS_LotCreation.wsdl"/>
                <oracle-xsl-mapper:rootElement name="InputParameters"
                                               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EBS_LotCreation"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE AUG 09 02:24:56 CDT 2016].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:InputParameters>
            <tns:P_I_TRX_ID>
                <xsl:value-of select="/ns0:CreateLotRequest/ns7:CreateLotReq/ns7:TransactionID"/>
            </tns:P_I_TRX_ID>
            <tns:P_I_TRX_NAME>
                <xsl:value-of select="/ns0:CreateLotRequest/ns5:HeaderRq/ns5:TransactionName"/>
            </tns:P_I_TRX_NAME>
            <tns:P_I_SRC_SYSTEM>
                <xsl:value-of select="/ns0:CreateLotRequest/ns5:HeaderRq/ns5:Source"/>
            </tns:P_I_SRC_SYSTEM>
            <tns:P_APPS_INIT>
                <tns:USER_ID>
                    <xsl:value-of select="/ns0:CreateLotRequest/ns0:AppsContext/ns4:UserId"/>
                </tns:USER_ID>
                <tns:USER_NAME>
                    <xsl:value-of select="/ns0:CreateLotRequest/ns0:AppsContext/ns4:UserName"/>
                </tns:USER_NAME>
                <tns:RESPONSIBILITY_NAME>
                    <xsl:value-of select="/ns0:CreateLotRequest/ns0:AppsContext/ns4:ResponsibilityName"/>
                </tns:RESPONSIBILITY_NAME>
                <tns:ORG_ID>
                    <xsl:value-of select="/ns0:CreateLotRequest/ns0:AppsContext/ns4:OrgId"/>
                </tns:ORG_ID>
            </tns:P_APPS_INIT>
            <tns:P_I_LOT>
                <xsl:for-each select="/ns0:CreateLotRequest/ns7:CreateLotReq/ns7:LotDetails/ns7:P_I_LOT_ITEM">
                    <tns:P_I_LOT_ITEM>
                        <tns:INVENTORY_ITEM_ID>
                            <xsl:value-of select="ns7:INVENTORY_ITEM_ID"/>
                        </tns:INVENTORY_ITEM_ID>
                        <tns:ITEM_NUMBER>
                            <xsl:value-of select="ns7:ITEM_NUMBER"/>
                        </tns:ITEM_NUMBER>
                        <tns:ORGANIZATION_ID>
                            <xsl:value-of select="ns7:ORGANIZATION_ID"/>
                        </tns:ORGANIZATION_ID>
                        <tns:HEAT_NUMBER>
                            <xsl:value-of select="ns7:HEAT_NUMBER"/>
                        </tns:HEAT_NUMBER>
                        <tns:WAYBILL_NUM>
                            <xsl:value-of select="ns7:WAYBILL_NUM"/>
                        </tns:WAYBILL_NUM>
                        <tns:WAYBILL_LINE_NUM>
                            <xsl:value-of select="ns7:WAYBILL_LINE_NUM"/>
                        </tns:WAYBILL_LINE_NUM>
                        <tns:LOT_NUMBER>
                            <xsl:value-of select="ns7:LOT_NUMBER"/>
                        </tns:LOT_NUMBER>
                        <tns:SUPPLIER_LOT_NUMBER>
                            <xsl:value-of select="ns7:SUPPLIER_LOT_NUMBER"/>
                        </tns:SUPPLIER_LOT_NUMBER>
                        <tns:COUNTRY_OF_ORIGIN/>
                        <tns:COUNTRY_OF_ORIGIN_CODE>
                            <xsl:value-of select="ns7:COUNTRY_OF_ORIGIN"/>
                        </tns:COUNTRY_OF_ORIGIN_CODE>
                        <tns:ORIGINATION_DATE>
                            <xsl:value-of select="ns7:ORIGINATION_DATE"/>
                        </tns:ORIGINATION_DATE>
                        <tns:C_ATTRIBUTE1>
                            <xsl:value-of select="ns7:C_ATTRIBUTE1"/>
                        </tns:C_ATTRIBUTE1>
                        <tns:C_ATTRIBUTE2>
                            <xsl:value-of select="ns7:C_ATTRIBUTE2"/>
                        </tns:C_ATTRIBUTE2>
                        <tns:C_ATTRIBUTE3>
                            <xsl:value-of select="ns7:C_ATTRIBUTE3"/>
                        </tns:C_ATTRIBUTE3>
                        <tns:C_ATTRIBUTE4>
                            <xsl:value-of select="ns7:C_ATTRIBUTE4"/>
                        </tns:C_ATTRIBUTE4>
                        
                        
                         <tns:C_ATTRIBUTE5>
                            <xsl:value-of select="ns7:C_ATTRIBUTE5"/>
                        </tns:C_ATTRIBUTE5>
                        <tns:C_ATTRIBUTE6>
                            <xsl:value-of select="ns7:C_ATTRIBUTE6"/>
                        </tns:C_ATTRIBUTE6>
                        <tns:C_ATTRIBUTE7>
                            <xsl:value-of select="ns7:C_ATTRIBUTE7"/>
                        </tns:C_ATTRIBUTE7>
                        <tns:C_ATTRIBUTE8>
                            <xsl:value-of select="ns7:C_ATTRIBUTE8"/>
                        </tns:C_ATTRIBUTE8>
                        
                        
                         <tns:C_ATTRIBUTE9>
                            <xsl:value-of select="ns7:C_ATTRIBUTE9"/>
                        </tns:C_ATTRIBUTE9>
                        <tns:C_ATTRIBUTE10>
                            <xsl:value-of select="ns7:C_ATTRIBUTE10"/>
                        </tns:C_ATTRIBUTE10>
                        <tns:C_ATTRIBUTE11>
                            <xsl:value-of select="ns7:C_ATTRIBUTE11"/>
                        </tns:C_ATTRIBUTE11>
                        <tns:C_ATTRIBUTE12>
                            <xsl:value-of select="ns7:C_ATTRIBUTE12"/>
                        </tns:C_ATTRIBUTE12>
                        
                         <tns:C_ATTRIBUTE13>
                            <xsl:value-of select="ns7:C_ATTRIBUTE13"/>
                        </tns:C_ATTRIBUTE13>
                        <tns:C_ATTRIBUTE14>
                            <xsl:value-of select="ns7:C_ATTRIBUTE14"/>
                        </tns:C_ATTRIBUTE14>
                        <tns:C_ATTRIBUTE15>
                            <xsl:value-of select="ns7:C_ATTRIBUTE15"/>
                        </tns:C_ATTRIBUTE15>
                       
                        <tns:PARENT_LOT_NUMBER>
                            <xsl:value-of select="ns7:PARENT_LOT_NUMBER"/>
                        </tns:PARENT_LOT_NUMBER>
                    </tns:P_I_LOT_ITEM>
                </xsl:for-each>
            </tns:P_I_LOT>
        </tns:InputParameters>
    </xsl:template>
</xsl:stylesheet>
