<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.eia.com/AO/EBiz/O2C/TripsAM/1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertForceDispatch"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns3="http://xmlns.eia.com/AO/EBiz/O2C/TripsAO/1.0"
                xmlns:ns4="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns2="http://schemas.oracle.com/service/bpel/common"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:ns7="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/I028NewDesign/NUC_SubscribeTrips_CP_ABS/JMS_SubscribeTrips"
                xmlns:ns5="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns8="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:ns9="http://xmlns.oracle.com/pcbpel/adapter/db/I028/NUC_SubscribeTrips_CP_ABS/DB_InsertForceDispatch">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="WSDLs/JMS_SubscribeTrips.wsdl"/>
        <oracle-xsl-mapper:rootElement name="TripsAddRq" namespace="http://xmlns.eia.com/AO/EBiz/O2C/TripsAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="WSDLs/DB_InsertForceDispatch.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OperationCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertForceDispatch"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUL 08 09:42:29 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:OperationCollection>
      <tns:Operation>
        <tns:operationId>
        <xsl:value-of select="oraext:sequence-next-val('OPERATION_SEQ','jdbc/omsi')"/>
        </tns:operationId>
        <tns:operation>1600</tns:operation>
        <tns:isReady>1</tns:isReady>
        <tns:isRead>0</tns:isRead>
        <tns:resultCode>0</tns:resultCode>
        <tns:creationTimestamp>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </tns:creationTimestamp>
        <tns:forceDispatchCollection>
          <tns:ForceDispatch>
            <tns:clientKey1>
              <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:clientKey1"/>
            </tns:clientKey1>
            <tns:clientKey2>
              <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:tripId"/>
            </tns:clientKey2>
            <tns:clientKey3>
              <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:name"/>
            </tns:clientKey3>
            <tns:clientKey4>EBS</tns:clientKey4>
            <tns:carrierScacCode>
              <xsl:value-of select="/ns0:TripsAddRq/ns3:Trips/ns3:Trips/ns3:attribute15"/>
            </tns:carrierScacCode>
          </tns:ForceDispatch>
        </tns:forceDispatchCollection>
      </tns:Operation>
    </tns:OperationCollection>
  </xsl:template>
</xsl:stylesheet>
