<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.eia.com/AM/EBiz/P2P/LotAM/1.0"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.eia.com/EO/common/Common/1.0"
                xmlns:ns3="http://xmlns.eia.com/EO/Standard/External/ISO/Country/3166-1/2006/Country"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns5="http://xmlns.eia.com/EO/common/Header/1.0"
                xmlns:ns4="http://xmlns.eia.com/AO/EBiz/common/AppsContextAO/1.0"
                xmlns:ns7="http://xmlns.eia.com/AO/EBiz/P2P/LpnAO/1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://xmlns.eia.com/EO/Standard/External/ISO/Language/639-3/2007/Language"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns6="http://xmlns.eia.com/EO/Standard/External/ISO/Currency/4217/2001/Currency"
                xmlns:client="http:/xmlns.eia.com/Implementation/ABS/NUC_EBizLPN_ABS/EBizLPNABS/1.0"
                xmlns:ns9="http://xmlns.eia.com/ABS/EBiz/PurchaseOrderABS/1.0"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:imp1="http://www.example.org"
                xmlns:ns8="http://xmlns.oracle.com/pcbpel/adapter/ftp/109/NUC_ASNQualityResults_Suppliers_Ross_ABF/FTP_ReadASNSupplier_Ross"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns10="http:/xmlns.eia.com/Implementation/ABS/NUC_EBizLot_ABS/EBizLotABS/1.0"
                xmlns:ns="http://xmlns.eia.com/ABS/EBiz/ReceiptABS/1.0"
                xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ns11="http://xmlns.eia.com/EDN/1.0/Event"
                xmlns:cor="http:/xmlns.eia.com/Implementation/ABF/NSNE_ASNQualityResults_Suppliers_Ross_ABF/ASNQualityResults_Suppliers/1.0/correlationset">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/EIAMetadata/ABS/EBiz/V1.0/P2P/LpnABS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateLpnResp" namespace="http://xmlns.eia.com/AM/EBiz/P2P/LotAM/1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FTP_ReadASNSupplier_Ross.wsdl"/>
        <oracle-xsl-mapper:rootElement name="parameters" namespace="http://schemas.oracle.com/service/bpel/common"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI AUG 26 06:35:06 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:parameters>
      <xsl:variable name="LPNsWarning">
        <xsl:for-each select="/ns0:CreateLpnResp/ns7:CreateLpnResp/ns7:LpnStatus/ns7:LpnStatusItem[ns7:STATUS = 'Warning']">
          <xsl:value-of select='concat (ns7:LPN_NUMBER, "/" )'/>
        </xsl:for-each>
      </xsl:variable>
      <xsl:variable name="lastIndexW" select="oraext:last-index-within-string ($LPNsWarning, '/' )"></xsl:variable>
      <tns:item>
        <tns:name>Warning</tns:name>
        <tns:value>
          <xsl:value-of select="substring($LPNsWarning,1,$lastIndexW)"/>
        </tns:value>
      </tns:item>
      <xsl:variable name="LPNsSuccess">
        <xsl:for-each select="/ns0:CreateLpnResp/ns7:CreateLpnResp/ns7:LpnStatus/ns7:LpnStatusItem[ns7:STATUS = 'Success']">
          <xsl:value-of select='concat (ns7:LPN_NUMBER, "/" )'/>
        </xsl:for-each>
      </xsl:variable>
      <xsl:variable name="lastIndexs" select="oraext:last-index-within-string ($LPNsSuccess, '/' )"></xsl:variable>
      <tns:item>
        <tns:name>Success</tns:name>
        <tns:value>
          <xsl:value-of select="substring($LPNsSuccess,1,$lastIndexs)"/>
        </tns:value>
      </tns:item>
    </tns:parameters>
  </xsl:template>
</xsl:stylesheet>
