<wsdl:definitions
     name="DB_Insert_XXNUC_AP_CCARD_INV_STG"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DV1_Application/NUC_ePayRecon_MFT_EBiz_ABF/DB_Insert_XXNUC_AP_CCARD_INV_STG"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DV1_Application/NUC_ePayRecon_MFT_EBiz_ABF/DB_Insert_XXNUC_AP_CCARD_INV_STG"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_XXNUC_AP_CCARD_INV_STG"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Insert_XXNUC_AP_CCARD_INV_STG_plt" >
    <plt:role name="DB_Insert_XXNUC_AP_CCARD_INV_STG_role" >
      <plt:portType name="tns:DB_Insert_XXNUC_AP_CCARD_INV_STG_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_XXNUC_AP_CCARD_INV_STG" schemaLocation="../Schemas/DB_Insert_XXNUC_AP_CCARD_INV_STG_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="XxnucApCcardInvStgCollection_msg">
        <wsdl:part name="XxnucApCcardInvStgCollection" element="top:XxnucApCcardInvStgCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Insert_XXNUC_AP_CCARD_INV_STG_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:XxnucApCcardInvStgCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
